### ISSUE TITLE
anchor/tag in HTTP Request to the documentation does not work

### ISSUE THREAD

**Issue by ramosmediavalet** [a85/POSTMan-Chrome-Extension#10017]
Hello,

It's a common practice to link to parts of the API Documentation in other documents, e-mails or customer communications.

The link sometimes needs to be precise and send to the specific FOLDER or REQUEST.

If we try to do it, it does not work, instead all links will ignore the anchor/tag and will open the top of the page.

https://docs.mediavalet.com/#4ea51e9f-bfd3-4f2d-9469-3bec0295ea37
![image](https://user-images.githubusercontent.com/82291124/121544926-ecdfef00-c9be-11eb-9cd9-40761de387cd.png)

https://docs.mediavalet.com/#77dbec30-65fa-4c03-809c-7cd72178b041
![image](https://user-images.githubusercontent.com/82291124/121544953-f1a4a300-c9be-11eb-8e51-32e1882b6783.png)

How do I link to my specific elements (request/folders etc) externally without being sent back to the top page?

Can you please help with this issue?

Thank you.
Felipe Ramos

**Comment by dcal** [comment]
I second this. I'd like to be able to link to other parts of the documentation from inside the documentation itself, as well as send clients to specific parts of the documentation. Currently, as far as I can tell, you have to manually click through the navigation to load specific documentation segments.

**Comment by kultom86** [comment]
Yes, please do add this. Looks so much nicer in emails to be able ot link to 
f. ex. ` https://ourAPIdoc.com/folder#endpoint `
than `https://ourAPIdoc.com/view/174444697/UV6dduEJ#228ee267-4eae-4d90-8862-4f95481c2f3e`

**Comment by akshaydeo** [comment]
👋 @ramosmediavalet, thank you so much for this feature request. We are looking into it and will update this space asap.

**Comment by Raja-Simha** [comment]
Hey @dcal @kultom86 @ramosmediavalet 

We fixed the issue with anchor tags. Links with anchor tags will take you to the corresponding section in documentation as you would expect. We will soon be working on the suggested improvements. 

@ramosmediavalet would love to have quick chat with you to understand your team's workflow to build, manage and share your API publicly. It will be helpful to understand the challenges your team faces so that we can build solutions accordingly. If interested, feel free to setup a call with me [here](https://calendly.com/raja-postman/office-hours).

**Comment by akshaydeo** [comment]
Hi @ramosmediavalet, this issue is fixed with our latest release of public documentation. [The link](https://docs.mediavalet.com/#4ea51e9f-bfd3-4f2d-9469-3bec0295ea37) mentioned in the issue takes the user directly to the How To guide.

Feel free to re-open the issue if something is not working for you 🙇‍♂️
