### ISSUE TITLE
"Encode URL Automatically" Not Working

### ISSUE THREAD

**Issue by DodgeDeBoulet** [a85/POSTMan-Chrome-Extension#10033]
**Postman version:** 8.6.2

**Issue:** "Encode URL Automatically" request configuration option does not seem to do anything with query params in GET operation

**Steps to reproduce:**

1. Verify "Encode URL Automatically" is enabled
2. Create query param key and value, the latter with slashes, spaces, whatever would normally be encoded
3. Click Send
4. 400 error response makes you sad
5. Select param value, right-click, choose "EncodeURIComponent"
6. Click Send
7. 200 Success response makes you happy (but mad at Postman)

If you're **supposed** to manually select EncodeURIComponent, then I would suggest that the "Encode URL Automatically" option is incorrectly claiming to "Encode the URL's path, **query parameters**, and authentication fields."

I searched for this issue but the only tickets I could find were for older versions of Postman.

**Comment by codenirvana** [comment]
@DodgeDeBoulet, `Encode URL Automatically` is working as expected.

This confusion is probably because Postman follows the WHATWG URL standard (Ref #8154) which only encodes the following characters: `SPACE`, `"`, `#`, `'`, `<`, `>`.

Anything outside this has to be manually encoded.
Can you share the characters you are expecting to encode automatically?

**Comment by DodgeDeBoulet** [comment]
Here's an example of a value that is not being encoded:
![image](https://user-images.githubusercontent.com/4532366/122907250-ed627900-d320-11eb-977a-37d28d5aa2eb.png)

The ~~spaces,  double quotes, and~~ equal signs are not being encoded with "Encode URL Automatically" enabled.

![image](https://user-images.githubusercontent.com/4532366/122908660-63b3ab00-d322-11eb-855b-d61da1e3fda6.png)

**Comment by DannyDainton** [comment]
Closing this based on @codenirvana's comment. 

> Postman follows the WHATWG URL standard (Ref https://github.com/postmanlabs/postman-app-support/issues/8154) which only encodes the following characters: SPACE, ", #, ', <, >.

> Anything outside this has to be manually encoded.

**Comment by progmars** [comment]
Then could we please have a feature that works automatically exactly as "EncodeURIComponent"?

Otherwise, they both are inconsistent. If "Encode URL Automatically" follows the WHATWG URL standard then why EncodeURIComponent does not? 
But actually I'm glad EncodeURIComponent doesn't otherwise I would have to encode all = to %3d manually. I just wish there was an option to do EncodeURIComponent on all query params automatically.
