### ISSUE TITLE
Something went wrong in fetching the status of the team on API Network

### ISSUE THREAD

**Issue by samirotiv** [a85/POSTMan-Chrome-Extension#10079]
**Describe the Issue**
When I try editing the team name, it shows: Something went wrong in fetching the status of the team on API Network

**Steps to Reproduce**
1. Create new account
2. Create team
3. Edit team profile
4. Change team name & url
5. Save

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/4405935/123817529-dec62400-d915-11eb-8ca9-e7b5cbf19966.png)

**Environment Information**

 - Platform Type: Chrome browser
 - Postman Version: Web version
 - Operating System: Windows 10

**Comment by timbochamp** [comment]
Hi @samirotiv , I think this is due to the performance degradation we're experiencing in our API network platform. Apologies for the inconvenience here. 

You can follow the resolution at https://status.postman.com/ . Please feel free to reopen this issue if you're still experiencing problems post fix at the same time!
