### ISSUE TITLE
All my information has been deleted

### ISSUE THREAD

**Issue by sbrfarhadi** [a85/POSTMan-Chrome-Extension#10074]
I wanted to download a 500 MB video to test
I went to settings and changed the max response size in MB to 5000
It was downloading when suddenly my postman was restarted and I realized that none of my information is available, including all collections.

![image](https://user-images.githubusercontent.com/24922779/123598037-beef0d00-d7fc-11eb-8806-062f760930c6.png)

**Environment Information**

 - Platform Type: 
 - Postman Version: v8.7.0
 - Operating System: windows 10

Is there any hope of getting my data back?

**Comment by postman-staff** [comment]
Hi @sbrfarhadi,

Sorry to hear that, happy to help!

May I know if you are using postman offline or were you logged in to the application? If you are using the application with the account, logging back should sync back all of your data.

If not a _possible_ workaround would involve importing local backups, but this isn't guaranteed to work. If it does work, the backups imported usually aren't entirely up to date with changes. Before resorting to this workaround, I'd like to get a better understanding of the issue here.

1) From screenshot, we see the API tab has been selected - can you click on Collections on the left tab and see the data there?
2) As you've mentioned the response size is of 500 MB, Increase the `Max response size` to 500 or 0 (Infinity) and also check if the request timeout is set to 0(infinity)? To do this please navigate: `Settings -> General`.

​  ![](https://postman.zendesk.com/attachments/token/CrBiE84H6VycNpPW4Mx7ZrrGK/?name=inline-1758483660.png)
3) I believe using Postman Web should also help you get this response with no issues: https://go.postman.co/home

via @Raj-postman | Postman Support

**Comment by sbrfarhadi** [comment]
Thanks for your prompt reply
I use the offline version
I checked all the parts (also the collection), unfortunately it seems to be back to factory settings


------------------------------------------------------

According to your recommendation, I re-entered the settings and set the value to 5000 and started the download operation
A strange but good thing happened, that my postman was closed again
When I opened my postman , I saw that all my information came back

![image](https://user-images.githubusercontent.com/24922779/123623874-9e33b100-d816-11eb-8a0a-1dca60515551.png)

**Comment by sbrfarhadi** [comment]
My problem is solved

If you have no questions, I will close the request

**Comment by postman-staff** [comment]
@sbrfarhadi Awesome! Glad to know you're requests are back :)

Would recommend logging into an account to avoid and loss of data or create regular backups as per this link here: https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#exporting-data-dumps.

We see that there is an issue on similar lines raised here #9739 - hence we will track the same there. You may close this request next.

Stay safe and Have a nice day!

via @Raj-postman | Postman Support

**Comment by sbrfarhadi** [comment]
tanks
