### ISSUE TITLE
Postman 8.8 not working on WIndows 8.1

### ISSUE THREAD

**Issue by sajidmohammed88** [a85/POSTMan-Chrome-Extension#10120]
**Describe the Issue**
Postman 8.8 not working on WIndows 8.1

**Steps to Reproduce**
1 - Update postman to V8.8 (for me it's updated automatically)
2 - Launch postman
3 - A gray screen stay displayed.

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/5097315/125681936-7df057c5-9d86-471d-99dc-422fa6c4d78b.png)

**Environment Information**

 - Platform Type: Windows
 - Postman Version: 8.8
 - Operating System: Wibdows 8.1

**Additional Context**
I had to uninstall  and install the old version.
Can you please fix the bug?

**Comment by postman-staff** [comment]
@sajidmohammed88 Sorry to hear about this experience.

I believe the issue here is due to update and it should be resolved by clearing local cache as per this document here: https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-

Do try the same and let us know if that helps. You may also install Postman Canary prior to this, to confirm that the issue will be indeed resolved with the above instructions.

_Note: There is not much difference between Postman Prod and Postman Canary. The only difference is that the Canary application gets all the newest releases/updates. That means that you can test all the features in the application as soon as they are built and released in the Postman canary. Both of the applications would help you test the APIs the same way._

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@sajidmohammed88 Just checking to see if our previous response helped? Do you also see issues with Canary?

via @Raj-postman | Postman Support

**Comment by sajidmohammed88** [comment]
it doesn't work for me, yes i have checked the canary postman too and i have the same issue for the same version.

**Comment by postman-staff** [comment]
Thank you for letting us know @sajidmohammed88.

Would you try disabling GPU as per this document here: https://support.postman.com/hc/en-us/articles/360026088854-Postman-window-is-blank and see if that helps?

If the issue persists, please provide the logs as explained in this article: https://support.postman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application- by submitting a ticket to us: http://postman.com/support. We will check this further from there.

via @Raj-postman | Postman Support

**Comment by sajidmohammed88** [comment]
@postman-support it works again by disabling the GPU.
Thank you.

**Comment by postman-staff** [comment]
@sajidmohammed88 Awesome! Glad to know that helped :)

Have a nice day.

via @Raj-postman | Postman Support
