### ISSUE TITLE
Pre-request script doesn't resolve environment variables in url object

### ISSUE THREAD

**Issue by GrayedFox** [a85/POSTMan-Chrome-Extension#10138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Pre-request scripts don't resolve environment variables inside the `pm.request.url` object.

For example, if I have set an environment variable called `apiUrl` to the value `www.example.com` and use that as the base of a request like so: `{{apiUrl}}/some.path.here` then I would expect `pm.request.url.getRaw()` to output the following: `www.example.com/some.path.here`.

It instead outputs `{{apiUrl}}/some.path.here` - that is, the apiUrl variable is not resolved and displayed inside double curly brackets.

### Steps To Reproduce

1. Create a new collection
2. Create a new environment and add the following variable: `apiUrl` with the value `www.example.com`
3. Create a new request that with the following path/domain: `{{apiUrl}}/some.path`
4. In the pre-request script, paste the following code:

```
console.log("Host: " + pm.request.url.getHost())
console.log("Raw: " + pm.request.url.getRaw());
console.log("Env: " + pm.environment.get("apiUrl"));
```

5. Observe the console output:

```
Host: {{apiUrl}}
Raw: {{apiUrl}}/some.path
Env: www.example.com
```

### Screenshots or Videos

![postman-bug](https://user-images.githubusercontent.com/6493307/126477592-2ce17d01-b544-4310-a65a-1376aa3dfe02.gif)

### Environment Information

```markdown
- Operating System: Ubuntu 20.04
- Platform Type: Native App
- Postman Version: 8.5.0
```

**Comment by neilstudd** [comment]
Hi @GrayedFox,

Thanks for such a detailed description, it's extremely helpful!

The good news is, it's intentional behaviour that can be overridden very easily. 

By default, the pre-request script will echo-back its variables exactly as stored; if you want to resolve variables within, you can do so by wrapping the variable name with `pm.variables.replaceIn()`. 

For example:
`console.log("Host: " + pm.variables.replaceIn(pm.request.url.getHost()))
` 

The console will now show the result of the variable after substitutions have occurred.

You can see other such examples here: [Postman Sandbox API reference](https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#using-environment-variables-in-scripts)

**Comment by GrayedFox** [comment]
Great, than I will close this since it was just me not understanding this behaviour, thanks for the quick reply
