### ISSUE TITLE
Postman Response body assertion error

### ISSUE THREAD

**Issue by sdet11** [a85/POSTMan-Chrome-Extension#10178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Given  trying to validate the response 
When  you type non existing response key 
Then it still gives 200 and success, even if the key and value are not existed in response payload

### Steps To Reproduce

1. Make POST request with payload
2. Go to Test tab and try to validate Response  with non existing key and value 
3. Still gives 200 and Success ... not reliable assertion 

### Screenshots or Videos

<img width="925" alt="Screen Shot 2021-07-30 at 10 50 23 AM" src="https://user-images.githubusercontent.com/88205394/127686956-73e3d17a-5db2-4b47-877e-d1b09c1b2307.png">

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

**Comment by neilstudd** [comment]
For better or worse, this is standard Javascript behaviour. If, for example, you print the same erroneous parameter to the console:

`console.log(response.content[0].kkkkkk)`

...then the result in the console is `undefined`. Therefore, when you do your comparison in the test, `undefined` is not equal to `445533`.

**Comment by sdet11** [comment]
Saying that,  any non existing response key and value will be giving 200 ?!
Honestly that does not help... i need to validate that the key is present and has a value ... what if i specify my key wrong ... having more than 500+ collection to test it is possible to be wrong  ... then this kind of validation is not reliable .... any different solution ? (reliable?)

**Comment by neilstudd** [comment]
> i need to validate that the key is present and has a value ...

In your screenshotted example, you were checking that the key does **not** have a specified value. If you want to check "key is present and has a value", the Javascript syntax will behave as you expect it to:

```
// this will fail if kkkkkk does not exist
tests["Line id exists with value 12345"] = response.content[0].kkkkkk === 12345
```

If you want to verify that the key exists AND does not have a value, you could write a check such as this:

```
// this will fail if kkkkkk does not exist, OR if it exists and doesn't equal 3
tests["Line id exists and does not equal 3"] = response.content[0].kkkkkk !== undefined && response.content[0].kkkkkk !== 3
```

...and if you want to do this sort of check many times, you could write a global function to reduce the amount of code and repetition. For example:

```
function ParameterExistsButNotWithThisValue(param, value) {
    return param !== undefined && param !== value
}

tests["Line id exists and does not equal 3"] = ParameterExistsButNotWithThisValue (response.content[0].kkkkkk, 3)
tests["Field xx exists and does not equal 123"] = ParameterExistsButNotWithThisValue (response.content[0].xx, 123)
```

As this is a query regarding language/syntax rather than Postman functionality, I would recommend continuing the discussion in our [Community Forum](https://community.postman.com/) if you would like further advice from Postman experts about the best way to structure your scripts.

**Comment by praveendvd** [comment]
use:

.hasOwnProperty('property1') to validate if the object has the particular key , 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty

**Comment by DannyDainton** [comment]
Closing due to age and inactivity. If this is still an issue you're facing in the latest version of the platform, we can look at reopening this again.
