### ISSUE TITLE
Postman 2 as a chrome tab

### ISSUE THREAD

**Issue by Maltronic** [a85/POSTMan-Chrome-Extension#1017]
I've been using Postman as a tabbed window but after upgrading to Postman 2 can only appear to open it as a separate window. Is it possible to open Postman 2 as a tabbed window like in previous versions?

**Comment by a85** [comment]
Restrictions of the Chrome app platform unfortunately. :(

**Comment by rusterholz** [comment]
@a85 I don't mean to beat a dead horse, but can you explain a little more about this? 

There are _several_ Chrome extensions that open in tabbed windows just fine: LastPass, AdBlock Plus, etc. They all work with a url of the form `chrome-extension://<lots-of-hex-characters-indicating-the-specific-extension>/<some-page>.html`. This doesn't appear to be a "restriction" that other extensions suffer from. Can you explain what it is about Postman that prevents the same approach from working?

If it's truly impossible to force Postman 2 to behave like other extensions, then I can accept that. But then for me the question becomes: is there any way at this time to re-obtain a copy of Postman 1?

It was working just fine for me, and the upgrade to Postman 2 is causing some serious aggravation in my workflow. (It's not that having Postman as a separate window or app is problematic in itself, it's that Chrome still considers the Postman window to be one of _its_ windows, so if I app-switch from Postman back to Chrome, the "real" Chrome window with all my tabs in it will not pop to the front. Any time I switch back to Chrome from another app, I get the Postman window instead of the Chrome window. In other words: running Postman 2 makes it significantly harder to use _the entire rest of my browser,_ which I'm sure you understand is a non-starter for a web developer.) 

If there's no way to resolve this issue by reverting to Postman 1, I'll have to give up and start using a different product... which I'd rather not do, because I like Postman, but that's what happens when inconveniences are branded as upgrades.

**Comment by a85** [comment]
@rusterholz Chrome deprecated the existing Chrome app platform (legacy-chrome-apps) a while back: https://blog.chromium.org/2014/06/migrate-your-legacy-packaged-apps-to.html. The primary reason that they cited was a separation between the main Chrome browser and apps for security reasons and "user expectations". Postman 3.0+ is based on the Chrome app platform and all apps run in a separate sandbox away from Chrome. The issue around window switching is due to a bug in Chrome itself. We are in touch with folks from the Chrome team to close this at the earliest. Issues on the Chrome bug tracker indicate that this would me a major change for Chrome itself and hence it's taking time. I had posted on the Chromium bug tracker here: https://code.google.com/p/chromium/issues/detail?id=308382. 

You can still install the legacy version: https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm.

However, as this platform is deprecated by Chrome (we can't create a new Chrome app listing for the legacy platform to test something for example), we can't guarantee updates or fixes.

We are beta testing native app versions and you can shoot us an email at help@getpostman.com to try it out.

**Comment by rusterholz** [comment]
Thank you for providing a more detailed explanation of the situation. I definitely appreciate the time you took to write that all out. I'm super-grateful for the link to the legacy version too (for now I will be switching back, but I love Postman and I'll keep my eyes peeled for when the native versions are released! I definitely understand that there's no support for the legacy version, too).

My team might be good beta testers for the native version -- I'll talk to the office and hopefully some of us will sign up. Thanks!
