### ISSUE TITLE
Cant open last update (8.9.1) on Windows

### ISSUE THREAD

**Issue by eric-ueta** [a85/POSTMan-Chrome-Extension#10176]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the Issue

Cant open the 8.9.1v on Windows, when I run the program the load animation freezes and the CPU usage increases a lot.

Tried to uninstall and install it (cleared all remaining files), but didnt worked, so I installed the 8.7.0v and works normally, but the app auto update to 8.9.1v and occurs again.

### Steps To Reproduce

1. Just run the app

### Screenshots or Videos

![screenshot 1](https://user-images.githubusercontent.com/37991851/127649177-3549f2ab-b301-44db-bb37-046d43c33138.png)
![screenshot 2](https://user-images.githubusercontent.com/37991851/127649256-b9297c42-cc4e-41df-9245-c661abc0e247.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 8.9.1
```

**Comment by Sanabalis** [comment]
Same thing here, started with version 8.8.0
Main.log only contains couple of lines, attached it here:
[main.log](https://github.com/postmanlabs/postman-app-support/files/6918616/main.log)

I don't even have v8.7.0 anymore because I cleaned everything up.

**Comment by mattcoz** [comment]
I have the exact same issue. Installed the canary build and it works.

**Comment by twitharshil** [comment]
Hey,

Thanks for reporting the issue, we have recently shipped a platform upgrade for the application which might have some rendering issues with certain GPU/driver combinations. Please forward your application logs from `%AppData%\Postman\logs` to `help@postman.com` so that we can take a deeper look at it? Please mention this GitHub issue id in the subject.

To unblock, users can try disabling the GPU setting for the postman application using an environment variable. Refer this [doc ](https://support.postman.com/hc/en-us/articles/360026088854-Postman-having-issues-launching-with-certain-GPUs-and-goes-blank-or-shows-black-screen) for the same !!

**Comment by postman-staff** [comment]
Hey @eric-ueta,

Thanks for getting in touch and really sorry for the hassle here.

Would you please try [disabling hardware acceleration](https://learning.postman.com/docs/getting-started/settings/#gpu-hardware-acceleration) from the Help menu in Windows and see if that helps?

Thanks for your cooperation on this.
I am looking forward to hearing back from you!

via @taehoshino | Postman Support

**Comment by Sanabalis** [comment]
It works after disabling the GPU setting for the postman application using an environment variable, as suggested by twitharshil above.

Thank you!

**Comment by eric-ueta** [comment]
> Hey @eric-ueta,
> 
> Thanks for getting in touch and really sorry for the hassle here.
> 
> Would you please try [disabling hardware acceleration](https://learning.postman.com/docs/getting-started/settings/#gpu-hardware-acceleration) from the Help menu in Windows and see if that helps?
> 
> Thanks for your cooperation on this.
> I am looking forward to hearing back from you!
> 
> via @taehoshino | Postman Support

Hello,

the @twitharshil solution worked,

curiously I deleted the environment variable to reproduce the error and catch the log file, but the app is still working.

Thank you guys.

**Comment by postman-staff** [comment]
Hey @eric-ueta,

Great to hear that the issue has been resolved! Thanks for keeping us updated!

Please do feel free to let us know if there is anything else I can help! Otherwise, I will go ahead and close this ticket for now.

Thanks again for reaching out! Have a great day!

via @taehoshino | Postman Support
