### ISSUE TITLE
Better tabs User experience in the Postman app

### ISSUE THREAD

**Issue by giridharvc7** [a85/POSTMan-Chrome-Extension#10184]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

From a Zendesk ticket:

The display of the TAB page is unfriendly. When the user opens too many tabs, the title of the note page becomes invisible. You can set tabs to scroll left and right rather than shorten them
![Snipaste_2021-03-02_20-07-45](https://user-images.githubusercontent.com/1040583/127862226-83371831-86d6-478b-8e06-bd01c5850ffd.png)

### Describe the solution you'd like

Better tab user experience

**Comment by numaanashraf** [comment]
Related to #3939

**Comment by zoom-scott-sancetta** [comment]
Yes please:
1. The left and right arrows should be bold if there are more tabs to that side, unbolded otherwise
2. An option to group tabs, or possibly have 2 rows of tabs

**Comment by enricjaen** [comment]
is there any plan to make tabs user-friendly?

**Comment by STeeL835** [comment]
I have these suggestions:
* Move the tabs to the top (like in browsers), or rearrange panels to the left and to the right - to make more room for tabs horizontally. Ideally, the full width of the window, but I guess, Environment dropdown can stay
* make a setting to make ctrl+tab cycle through tabs in recently used order (like alt+tab or like in Firefox)
* Set a minimum width for tabs that will allow to show at least 2 words instead of 1 letter (like in Firefox again - they even show a dropdown button with a vertical list of opened tabs, when the tabs need to be scrolled)
* Tabs could have color marks to help you find what you need.
  _In browser every website has a different colorful favicon - they help you find **that one tab** based on favicon shape and color, since people scan these things a lot faster than words. In Postman every tab looks almost the same (you can distinguish environment tab from a request tab, but I struggle to find needed request tab or needed collection tab in a heap of many others). An option to add a distinguishable color mark (border/fill/dot/underline, whatever) to tabs based on collection would help to see needed tabs, when you work with different collections/environments/etc._

Unneseccary:
* while I keep comparing referencing Firefox - now it has tabs that can display 2 lines of information. Postman could do the same with showing details like collection name for requests or request name for examples in the context line. 

Edit: an image to illustrate. There tabs strip has more room, min-width for environment dropdown is smaller (we can resize it to make it as big as we want, why not as small as we want, right?), tab scroll arrow buttons are emphasized with borders, arrow that can't scroll further is semi-transparent (to show that clicking won't do anything), min-width of tabs is slightly greater and can fit a word (this size can be made even a bit more wider, but this is still something) and tabs that don't show a close button actually use this free real estate to show a bit more of their title.

![изображение](https://user-images.githubusercontent.com/25896927/151442779-98fcbb7e-2f4e-4354-9c61-e4ef997e1f56.png)

**Comment by adrianAtProresult** [comment]
To be honest, I think vertical tabs is the way to go. Just collapse the tab view when it's not hovered, and expand it above content on hover, like in Microsoft Edge on Chromium:
Collapsed:
![image](https://user-images.githubusercontent.com/34372505/176617033-46ddee63-7124-4965-acbb-388c235d192a.png)
Expanded:
![image](https://user-images.githubusercontent.com/34372505/176617180-61eed460-dc9e-45da-9083-b2080f750f61.png)
When there are more tabs than the full window height can display, make the tab list scrollable.
This kills a minimum of working space in the application, while offering maximum readability and searchability when you need to switch tabs. I thought I was going to hate vertical tabs, but I gave them an honest try and I'm never going back now. No more 3mm wide tabs with ellipsis for names.

Bonus points if we'll be able to group tabs ourselves, or provide settings to toggle automatic grouping by folder for instance.

**Comment by IcodeNet** [comment]
I think the search tabs feature of Chrome is a very efficient way of using tabs.

![image](https://github.com/postmanlabs/postman-app-support/assets/991694/d5eeb445-f9f8-4f73-9c7a-acbbd0e9a1d7)

**Comment by chris-torruella** [comment]
Hey everyone, exciting news! ⭐
We've just introduced **Tab Search**, a new step in our journey to improve tabs UX and management at Postman. Now, you can easily read the entire name of all your opened tabs, regardless of their number.

**What's New:**
1. Dropdown display with all of your tabs.
2. Recently closed section for easy recovery.
3. Search bar for quick tab access.
4. Moved "Close all tabs" options to right-click tab menu to gain more tab bar space.

![demo](https://github.com/postmanlabs/postman-app-support/assets/120389184/ac9bb7cf-2832-44dc-a5b6-7da917c0134b)

Give it a try and let us know what you think. Your feedback is key to help us taking Postman to the next level! 🚀

**Comment by SafSoufTouk** [comment]
@chris-torruella What we were expecting is not a search by tab name (we already have that in the left sidebar). We want a search by URL. What I mean is, if I duplicate a tab and change the URL, then switch to another tab, I should still be able to return to that tab. Exactly like what Chrome does.
It's similar to what you do in Find and Replace, except that in Find and Replace, I can see my tab and know it's open somewhere, but I can't access it.

![image](https://github.com/user-attachments/assets/e95b6195-7b8a-4605-bb06-655fe2efafa9)
