### ISSUE TITLE
API Key Authorization values do not propagate to documentation

### ISSUE THREAD

**Issue by paulwis** [a85/POSTMan-Chrome-Extension#10192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Define auth values for a collection:
<img width="542" alt="Screen Shot 2021-08-04 at 3 15 08 PM" src="https://user-images.githubusercontent.com/1090185/128241309-fd125deb-296f-43fb-95f3-83a47d5c2d4c.png">

When generating documentation, this is the resulting auth block:
<img width="345" alt="Screen Shot 2021-08-04 at 3 11 47 PM" src="https://user-images.githubusercontent.com/1090185/128240975-cc75e1cc-32b1-4eb6-9291-f6f2f3b0a4b2.png">

I expect that instead of `<key>`, the auth api key "key" to be `api_key`. Same goes for value, which has the value of `<value>` instead of the actual value.

### Steps To Reproduce

Create a collection
Define API Key auth for the collection
View documentation for the collection

### Environment Information

```markdown
- Operating System: MacOS
- Platform Type: Native app and postman web
- Postman Version: 8.9.1
```

**Comment by seanryankeegan** [comment]
I am seeing a similar issue in a partner conversation. I can’t get the value for the `Key` parameter to show up as expected. I also can’t tell where it’s being assigned the `<key>` value from. I thought this may be an issue with the request inheriting auth from the collection level authorization, but this issue persisted when manually added the `x-api-key` to the header as well. Is this expected behavior? Is there a way to control what shows up in the documentation for the Key?
![Screen Shot 2021-08-20 at 2 59 51 PM](https://user-images.githubusercontent.com/14284310/130283623-f7995d2e-c385-433c-9bad-473995e34d0a.png)

From the images, you can see that the documentation is taking the value from the auto-generated header as well. (The value in the docs is `enter-your-api-key-here`) Is this also expected behavior?
![Screen Shot 2021-08-20 at 2 59 38 PM](https://user-images.githubusercontent.com/14284310/130283645-e9cfc6e5-3f99-4219-ad37-aa78eabcdd16.png)

**Comment by deefactorial** [comment]
I'm seeing the same issue as well, when can we have an ETA on this?

**Comment by akshaydeo** [comment]
@deefactorial, we are looking into this on priority. I will keep this thread updated 🙇‍♂️

**Comment by satyam-postman** [comment]
Hi @paulwis @deefactorial  We have merged the update, suggested changes will hopefully be available in next release.

cc @akshaydeo
