### ISSUE TITLE
Settings tab should have Application Logs location

### ISSUE THREAD

**Issue by Swapnil-getpostman** [a85/POSTMan-Chrome-Extension#10218]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

It's difficult to locate app logs sometimes for some users.

### Describe the solution you'd like

It's nice to have default logs located (based on the OS) in the general tab of the app settings, as shown in the below screenshot:

<img width="1353" alt="logs_dirc" src="https://user-images.githubusercontent.com/52168965/129355138-c1832d01-8542-446b-a345-29444a2bf8b1.png">

**Comment by numaanashraf** [comment]
Application logs are accessible via this Menu option. Since the log location is not user configurable, we do not show it under the 'Settings' dialog.

<img width="703" alt="Screenshot 2021-08-13 at 5 58 32 PM" src="https://user-images.githubusercontent.com/3295568/129357173-b19d2631-6f6e-477f-a840-8aaf68b4c275.png">
