### ISSUE TITLE
Error: tunneling socket could not be established

### ISSUE THREAD

**Issue by nstekelenburg** [a85/POSTMan-Chrome-Extension#10284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

After version 8.11 is updated into 8.12 we get this error.
By re-installing 8.11 the  api calls are normally processed by our proxy.
Postman automatically updates to 8.12, so we need to reinstall version 8.11 daily

### Steps To Reproduce

Call any API using our proxy

### Screenshots or Videos

Console error:
```
GET https://<domain>/v3/resources/agent?rs:id=<SOME-ID>&rs:latest=true
Error: tunneling socket could not be established, cause=connect EACCES <IP>:<PORT>
Proxy
id: "<id>"
host: "<host>"
match: {…}
port: 3128
tunnel: false
authenticate: false
Request Headers
Content-Type: application/json
Authorization: Basic <base64-encoded-password>
User-Agent: PostmanRuntime/7.28.4
Accept: */*
Postman-Token: dce43b69-b622-44b0-b0f0-f11ed6630a27
Host: odh.goudse.com
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```

### Environment Information

```markdown
- Operating System: win32 10.0.19043 / x64
- Platform Type: postman for Windows
- Postman Version: 8.12.1
```

**Comment by xk0der** [comment]
Hey @nstekelenburg 👋   your initial message contained sensitive information which I've edited and removed. **I strongly suggest your rotate your secrets and passwords just in case, to be safe**. In the future make sure to sanitize the information before posting it on public forums 🙌

**Comment by postman-staff** [comment]
Hey @nstekelenburg,

Thanks for reaching out!
Really sorry to hear you are getting an error after updating the app to v8.12.1, which you are not seeing on v8.11.

You mentioned you are behind proxy - may I ask you if your API is behind proxy as well? Also, we seem to have had a similar issue in the past. Would you please check if [this issue](https://github.com/postmanlabs/postman-app-support/issues/8783) is the same problem you are facing?

Also, can you please tell me if you are seeing the same issue if you send the sam request on our web app (go.postman.co)?

via @taehoshino | Postman Support

**Comment by nstekelenburg** [comment]
Hi @taehoshino,

Thanks for picking this up.
I saw the issue that you are referring to. The error shown there was different then ours. Also that issue had to do with the password containing other characters then digits and letters. The password we use in Postman to connect to the services is only containing digits and letters.

Our rest services are created by our supplier and hosted in the azure cloud. I have asked our supplier if the rest services we are calling are behind a proxy there. I will let you know.

I have also tried the web app, this gives the following error:
Could not send request
Cloud Agent Error: Request is taking longer than 30 seconds to fulfill. Use another agent to send a request without time limitations.
Use Postmans's Desktop Agent.

**Comment by nstekelenburg** [comment]
Hi @taehoshino,

Replay of our supplier:
Our service are running in Azure VMs and we have an Application Gateway configured for handling the HHTPS calls. 
The access to the application is not public as we offer access via NSG inbound rules. 
Is the new version (8.12) doing any IP mapping or masking?

**Comment by postman-staff** [comment]
Hey @nstekelenburg,

Thanks for your response and clarifying the issue is different from the previously reported issue.

I will consult with our internal team if there has been any change in v8.12 from v8.11.

In the meantime, would you please try sending a request using cURL command (https://en.wikipedia.org/wiki/CURL) from terminal window and see if the response is returned without any issue?

With regard to the "Cloud Agent Error" on web app, please try installing Desktop Agent from https://www.postman.com/downloads/ and ​​​select "Desktop Agent" on go.postman.co on the bottom right corner of the page?  ![](https://postman.zendesk.com/attachments/token/sxMNy9Ex3zZWVCC0qE1dnLTOA/?name=Screen+Shot+2021-09-15+at+2.11.38+pm.png)​
 ![](https://postman.zendesk.com/attachments/token/XJ75IzkGBhzH4WPfU4nRdZcJx/?name=Screen+Shot+2021-09-15+at+2.13.04+pm.png)

Thanks for your cooperation on this.
I am looking forward to hearing back from you!

via @taehoshino | Postman Support

**Comment by postman-staff** [comment]
Hey @nstekelenburg,

I am currently consulting with our engineering team and could I please confirm one more thing?

Do you need proxy configured for you to be able to send requests? (i.e. Is it possible to bypass proxy?)

via @taehoshino | Postman Support

**Comment by nstekelenburg** [comment]
Hi @taehoshino,

I tried the web version with desktop agent installed. When calling our API, I get the same error as in 8.12: Error: tunneling socket could not be established, cause=connect EACCES <url>:<port>

I now see 8.12 is removed from Postman Website and I am on 8.11. So I cannot call https://en.wikipedia.org/wiki/CURL from 8.12 desktop version. I did it from the web version and I received a response. That seems to be working.

About the proxy. Yes, that needs to be configured. I cannot bypass it, some URL's are forwarded using VPN.

**Comment by postman-staff** [comment]
Hey @nstekelenburg,

Thanks for your response and clarifying that you need proxy configured.

Our engineering team is currently trying to reproduce the behaviour. I will be in touch as soon as I hear any updates from them.

via @taehoshino | Postman Support

**Comment by nstekelenburg** [comment]
Hi @taehoshino,

I do not know where version 8.12 went, but I saw that version 9.0.1., is launched today. I installed that and tried to call our rest services. I still get the tunneling socket error so Postman still cannot reach our rest services.

After that I tried the curl command in 9.0.1.. That worked smoothly, I received a response.

Checking our network connections I found the following. 
From our local device using a VPN client we are routed to a VPN gateway, behind that VPN server is the proxy, the proxy reverts traffic back to the VPN gateway and then reaches out to the internet.
Don't ask me why, please. This is the way it works for us.

I removed 9.0.1. and installed 8.11.1. again. That will do the trick for us for now. In 8.11.1. Postman is able to connect to the server that hosts the rest services.

**Comment by postman-staff** [comment]
Hey @nstekelenburg,

Thanks for your response! Really sorry to hear the issue is still persisting with v9.0.1.

I have shared the information with our engineering team and asking for the next step.

I will be in touch with you as soon as I hear back from our team.

via @taehoshino | Postman Support

**Comment by postman-staff** [comment]
Hey @nstekelenburg,

Thanks for your patience.

Our engineer would like you to re-configure the proxy settings on the app and see if the issue persists?

Also, would you please tell me the app version (v9.0.x) you are currently using where you see the issue?

Thanks for your cooperation on this.
I am looking forward to hearing back from you!

via @taehoshino | Postman Support

**Comment by nstekelenburg** [comment]
Hi @taehoshino,

I have installed latest version of Postman for Windows, 9.0.3. Tunneling error still occurs.
Tried Postman for web version 9.0.4-210922-1300. Tunneling error still occurs.
In both apps I re-configured the proxy settings.
I have enabled and disabled all functions under Default Proxy Configuration and  Proxy configurations for sending requests.
In all cases Postman is not able to reach our rest services.

After removing Postman for Windows version 9.0.3, I installed Postman for Windows version 8.11.1 again.
Using version 8.11.1 we still can reach are rest services. So from now on we will stay on 8.11.1 until the problem is found and fixed.

Regards,
@nstekelenburg

**Comment by postman-staff** [comment]
Hey @nstekelenburg,

Thanks so much for testing out different versions and I am really sorry that the issue still exists in v9.0.3. or 9.0.4 on web.

I will share that information and I will reach out to you as soon as the issue gets fixed.

Again apologies for the inconvenience.

via @taehoshino | Postman Support

**Comment by postman-staff** [comment]
Hey @nstekelenburg,

Sorry for my multiple responses. To speed up our investigation, we would like to request for additional information.

As it may contain sensitive information, would you please submit a support request from the following link?
https://support.postman.com/hc/en-us/requests/new

In the request, please mention this GitHub issue number (https://github.com/postmanlabs/postman-app-support/issues/10284) so that we can keep track of your case.

Thanks so much for your cooperation. We are looking forward to receiving your support request.

via @taehoshino | Postman Support

**Comment by postman-staff** [comment]
Hey @nstekelenburg,

I hope all is well! I just wanted to follow up on my previous message.

Please do let us know if the issue is still persisting. We'd be happy to troubleshoot further.

Thanks so much for your cooperation. We are looking forward to receiving your support request.

via @taehoshino | Postman Support

**Comment by nstekelenburg** [comment]
Hi @postman-support,

Sorry for not responding so long. It has been a bit hectic around here. 
The problem is still not solved on our side, but because we are still able to use version 8.11.1 we can still continue working.
We found out that in can possibly be a problem on our side. Maybe one of our firewalls is not allowing traffic from certain application to pass through. It is still strange that version 8 can pass and version 9 not. Our own ICT people are looking into that now. When I know more, I will inform you.

Thanks!
@nstekelenburg

**Comment by postman-staff** [comment]
Hey @nstekelenburg,

Thanks for getting back to us!
Sure, please let us know how it goes!

In case the issue still persists even after troubleshooting by your IT team, please submit a support request from the following link so that we can look into this more closely by analysing logs etc:
https://support.postman.com/hc/en-us/requests/new

In the request, please mention this GitHub issue number (https://github.com/postmanlabs/postman-app-support/issues/10284) so that we can keep track of your case.

via @taehoshino | Postman Support

**Comment by postman-staff** [comment]
Hey @nstekelenburg,

I hope all is well! I just wanted to follow up on my previous message.

As mentioned in my previous message, please submit a support ticket from the below link in case the issue still persists after your IT team has reviewed the case.
https://support.postman.com/hc/en-us/requests/new

We will then be able to closely look into the issue and assist further in troubleshooting.
Therefore, for this GitHub issue, I will go ahead and close it for now.

via @taehoshino | Postman Support
