### ISSUE TITLE
Syncing documentation with schema disregards from parameters and responses

### ISSUE THREAD

**Issue by lobbin** [a85/POSTMan-Chrome-Extension#10295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When syncing an API with documentation, it doesn't see changes in parameters and responses.

### Steps To Reproduce

1. Create an API
2. Create documentation from API
3. Change a parameter and/or response on an API method
4. Validate the changes

In this case, Postman will say that everything is validated and no changes needed. Even if forcing a change via the Postman API call, the change will happen. The only way is to know which method that change, remove that method and then initiate a sync.

### Environment Information

```markdown
- Platform Type: Postman Web / Postman API
```

**Comment by VShingala** [comment]
@lobbin Could you share specification or short video where you're facing the issue? We've taken a look and the validation flow seems to be working fine. For example, take a look at video shared in this comment: https://github.com/postmanlabs/postman-app-support/issues/10643#issuecomment-1049033356

**Comment by lobbin** [comment]
@VShingala No, this is still an issue. Simply setting "required" from true to false breaks this. I can continue on the other thread, I think that one is better as it contains a video as well.

**Comment by VShingala** [comment]
@lobbin Is the issue you're facing the same as the issue that I mentioned? #10643

**Comment by lobbin** [comment]
@VShingala, I think so. I can't really recall since it was such a long time ago ;) but the #10643 describes the problem I had so I'm closing this one.

**Comment by petkostas** [comment]
I am experiencing similar issues, to provide some context, I will demonstrate this with the petstore yaml file:

- Have the [petstore.yaml](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml)file in my Gitlab repo under a specific branch
- I import it (e.g would be nice to add importing from Gitlab, since you do have sync, but that is a different topic) into postman and generate a new collection.
- Make a change to the collection (simple, pretend you are tech writter and add a description for one of the endpoints).
- Make a change the schema file itself (e.g. for our example and the petstore.yaml) change the name of the optional parameter `limit` to `limit-pets` of the `listPets` operationId in your local branch
![yaml-changes](https://user-images.githubusercontent.com/3758537/161261662-f73c02f4-73cf-4424-84cf-439095c3e52c.png)
- commit the changes and push the branch
- pull the changes from within Postman
![postman-pull](https://user-images.githubusercontent.com/3758537/161261735-f90e79ad-2569-4c38-9ef3-bb20e1fc674f.png)
- review the issues from within Postman
  - Postman only informs that the parameter was deleted (check screenshots)
  - Postman complains that the added documentation (in the collection) is not present in the schema
![review-changes](https://user-images.githubusercontent.com/3758537/161261758-c933e561-b47b-44ca-aefb-ec5bed2448a8.png)
