### ISSUE TITLE
Proxy does not work: ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by arakis** [a85/POSTMan-Chrome-Extension#10336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When enable Proxy (not Interceptor) for logging requests, it does not work. Not in program code (for example WebClient in .NET) or in Google Chrome (when enabled in System settings.

### Steps To Reproduce

- Enable Proxy, listening on Port 5555.
- Setup this proxy in Operating System Settings. IP: 127.0.0.1, Port 5555.
- Open Google Chrome (or any other Browser)
- Visit any Page

### Environment Information

```markdown
- Operating System: Windows 10 win32 10.0.19043 / x64
- Platform Type: Windows
- Postman Version: 9.0.3
```

### Additional Context?

I ensured Windows Firewall is setup correctly or even disabled.

**Comment by arakis** [comment]
I figured out, it happens only on HTTPS requests. (HTTP requests will work). So i followed the instructions here: https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests

But in Folder `%appdata%\Roaming\Postman\proxy\certificates` there's only a `cert.json` an nothing more. I've installed openssl correctly, and it's added to the PATH variable, and Postman (and even the computer) was restarted.

**Comment by postman-staff** [comment]
Hello @arakis
I have tried to replicate the issue, but I was unable to.

Since you mentioned that the problem only occurs with HTTPS requests, this most likely happens because the proxy certificate was not installed. Without that certificate, Postman won't be able to capture HTTPS traffic

According to what you mentioned you are not seeing the postman-proxy-ca.crt file on your end.

Can you please let me know what version of OpenSSL you are running? Currently, Postman supports version 1.1 and any later versions might not work.

If that's not the version you have on your end can you please uninstall the current OpenSSL version and install 1.1:

You can find older OpenSSL versions on the following link:
https://slproweb.com/products/Win32OpenSSL.html

via @nasco-a | Postman Support

**Comment by postman-staff** [comment]
Hello @arakis,

Just checking in if you were able to go through my previous reply - if yes did it yield any positive results

Please let us know in case you continue to face the issue even after following the steps listed earlier.
via @nasco-a | Postman Support

**Comment by postman-staff** [comment]
Hello @arakis

Since we haven't heard from you and we fail to replicate the reported behavior, I'll go ahead and mark the issue as **Closed**

Please feel free to let us know in case you continue to experience the issue, even after following the recommendations to install an earlier version of openSSL (1.1)

Best Regards,
Atanas

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by arakis** [comment]
Ok, i followed your adivse. With OpenSSL 1.1, it works as expected. Please Update your documentation for forcing install OpenSSL 1.1, or better, make it OpenSSL 3 compatible :-)

**Comment by postman-staff** [comment]
Hello @arakis,
Thanks for the update.

I'm glad to see the issue was resolved on your end.

Regarding your other note -  Thanks for flagging that - I agree, our team is aware of the issue and we'll be making changes to the documentation.

Since everything here seems to be resolved I'll go ahead and **close** the thread.

via @nasco-a | Postman Support

**Comment by elbaulp** [comment]
I have similar issues, I can not get the proxy to work on an iPhone, I installed the certificate as specified [here](https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/#built-in-proxy), but I don't have any internet connection after setting the proxy on the phone.

**Comment by postman-staff** [comment]
[GitHub] Proxy does not work: ERR_EMPTY_RESPONSE
Hello @elbaulp,
Given the fact that this is most likely a separate issue, and you might have to provide us with some more details, can you please reach us out directly by logging a ticket so we can assist you forward:


- https://support.postman.com/hc/en-us

via @nasco-a | Postman Support

**Comment by postman-staff** [comment]
Hello @elbaulp,
We still haven't received your ticket, please feel free to let us know if you need any assistance - we'll be happy to help.

via @nasco-a | Postman Support

**Comment by elbaulp** [comment]
Ah, sorry, haven't had the time. Will try to create the ticket today

**Comment by postman-staff** [comment]
Hello @elbaulp
Thanks for the update!

We just want to make sure we have received your ticket since the thread will be marked as closed and we want to continue assisting you forward.
via @nasco-a | Postman Support

**Comment by elbaulp** [comment]
> Hello @elbaulp Thanks for the update!
> 
> We just want to make sure we have received your ticket since the thread will be marked as closed and we want to continue assisting you forward. via @nasco-a | Postman Support

Done, I sent a email through the support button

**Comment by shashankawasthi88** [comment]
Closing this issue as the solution has been provided. The iPhone issue is being handled via the support route.
