### ISSUE TITLE
'Certificate has expired' error for Let's Encrypt certificates (DST Root CA X3 issued)

### ISSUE THREAD

**Issue by felipeabou** [a85/POSTMan-Chrome-Extension#10338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I've seen that this problem has happened before: https://github.com/postmanlabs/postman-app-support/issues/8589

The problem started today. Postman says the SLL certificate is expired, but it's not:
![image](https://user-images.githubusercontent.com/78875782/135486097-ea7b0eaa-fba1-42ab-a4c5-fa0a763acb36.png)

We use Letsencrypt to deal with SSL on our APIs and believe it could have something to do with this: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

By now, I'm using the disable “SSL certificate verification” workaround.

This problem happened with version 9.0.3 and also with version 8~, because I tried to rollback to solve it, with no luck.

Also, when using the Postman Web, the issue is **not** happening. It only happens with the Native App version.

### Steps To Reproduce

1. Try to hit any API that uses Letsencrypt to deal with SSL certificates.

### Screenshots or Videos

Postman error:
![image](https://user-images.githubusercontent.com/78875782/135486001-d7ba1dfa-be34-4c9a-8ba2-392c6d315a96.png)

Checking the same SSL on Chromium:
![image](https://user-images.githubusercontent.com/78875782/135485766-4a3e0ec8-88cf-42d0-81a7-0090d23f3220.png)

### Environment Information

```markdown
- Operating System: Ubuntu 20.02
- Platform Type: Native App
- Postman Version: 9.0.3
```

**Comment by adamsommer** [comment]
+1

```
- Operating System: macOS 10.15.7
- Postman Version: 9.0.3
```

**Comment by numaanashraf** [comment]
Postman v8 and v9 seems to be impacted by the recent cert expiry https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/. We are investigating this now.

**Comment by numaanashraf** [comment]
As a workaround, please turn off SSL verification via Settings > General.

<img width="721" alt="Screenshot 2021-09-30 at 8 53 58 PM" src="https://user-images.githubusercontent.com/3295568/135484638-9c1eb64f-55ca-4c91-aa30-4ecdac69cad3.png">

**Comment by amurrell** [comment]
+1

also using lets encrypt and valid certs till nov 1st - acting up today. Upgraded to latest postman version and it's still not working. Disabled ssl verification for now.

**Comment by ghost** [comment]
+1

- OS: Ubuntu 21.04
- Kernel Release: 5.11.0-37-generic
- Postman Version: 8.12.2

**Comment by idkw** [comment]
Same : 
- OS : Linux Mint 20
- Kernel : 5.4.0-88-generic
- Postman : 8.11.1

**Comment by Ray-B** [comment]
+1

- OS: Big Sur 11.6
- Postman: 9.0.3

**Comment by numaanashraf** [comment]
Thanks for your patience everyone. We have identified the issue and are testing out a potential fix internally. Once we have the fix verified, we'll release a patch on our v8.x and v9.x release lines.

**Comment by trixie88** [comment]
+1
postman V: 9.0.3

**Comment by mikeamcbrien** [comment]
+1

- OS: Big Sur 11.6
- Postman: 9.0.3

**Comment by danielgelling** [comment]
Also on:
- Postman Version 8.12.1
- OS X 20.6.0 / x64

**Comment by Freyert** [comment]
The LetsEncrypt expiration is a bit confusing because the expired certificate is left in the chain for backwards compatibility purposes from what we've read on their blog.

So there are two paths for the certificates, the new shorter valid path, and the longer expired path.

That is to say the issue is likely _not_ that the trust store is missing a certificate, but that postman is ignoring the valid certificate path.

**Update:**

If postman is using a version of NodeJS older than 5 years it's likely they don't have the ISRG Root X1 in the trust chain.

https://github.com/nodejs/node/blame/master/src/node_root_certs.h#L2602-L2631

If someone wants to try you can extend the built in certificates via the environment variable `NODE_EXTRA_CA_CERTS` https://github.com/nodejs/node/pull/9139

**Update 2:**

I've tried manually adding the CA for ISRG Root X1 from NodeJS to no avail. It's likely a conflict in the TLS resolution paths. If you want to try yourself just copy and paste the certificate I linked [here](https://github.com/nodejs/node/blame/master/src/node_root_certs.h#L2602-L2631) into a file ending with `.pem` and import it into postman as you are accustomed to.

I don't know much about Postman so maybe someone can figure out how to get more details from there or correctly configure the certificate.

**Comment by numaanashraf** [comment]
@Freyert Postman uses Electron, which has a non-standard Node + BoringSSL integration. We believe this is happening cuz boringSSL is not configured to prefer the shorter part by default. We have patched this internally and is also working on upstreaming this. 

https://github.com/electron/electron/pull/31213

**Comment by Freyert** [comment]
@numaanashraf thanks for the transparency! I was a bit in the dark from the older issues on what was fixed last time. Thank you all for the quick turn around :)

**Comment by felipeabou** [comment]
Thanks, guys, for the fast response!

**Comment by cfecherolle** [comment]
+1 !
OS : Big Sur 11.2.2
Postman : 9.0.3
Indeed, the problem occurs when hitting URLs from domains with Let's Encrypt certificates.

**Comment by kabadabra** [comment]
+1
- OS: Big Sur 11.6
- Postman: 9.0.3
- Let's Encrypt Certificate

&
- OS: Windows 10 21H1 Build 19043.1237
- Postman: 9.0.3
- Let's Encrypt Certificate

**Comment by karelbilek** [comment]
You don't need to keep adding +1 folks, the error is already fixed on master and will get released

**Comment by CleverHosting** [comment]
9.04 still facing the problem

**Comment by tomswinkels** [comment]
+1 

macOS Big Sur 11.5
Postman 9.0.3

**Comment by numaanashraf** [comment]
The fix for this issue is available now on v9.0.5 version. If you are on Postman v9.0 and above, do 'Check for Updates' to get access to this version. Looking forward to hearing if the issue is resolved at your end. 

[EDIT] If you are on Postman v8, v8.12.4 is available as well with the fix.

**Comment by goran-insby** [comment]
Wow this was fast, installed and works perfect.

**Comment by libalex** [comment]
+1
OS: Windows 10
Postman: 9.0.3

**Comment by felipeabou** [comment]
Wow, you guys were really fast with this! Thank you very much!
Using version 9.0.5 and everything is working perfectly.

**Comment by cretara** [comment]
Thanks for fix, now works great in Postman v.9.0.5

**Comment by numaanashraf** [comment]
The fix is now available on both v9 & v8 release lines via v9.0.5 & v8.12.4. Closing this issue.

**Comment by drissfoo** [comment]
Still have this issue for the last version v9.0.5 for macOS Big Sur 11.4
Certificate is valid til 31 October. Seems like a random issue happening only to me and not my colleagues.
<img width="301" alt="Screenshot 2021-10-06 at 17 38 36" src="https://user-images.githubusercontent.com/667058/136236858-bd64d67e-279f-4e83-96da-46da3ae74de3.png">
"<img width="445" alt="Screenshot 2021-10-06 at 17 40 50" src="https://user-images.githubusercontent.com/667058/136237379-4f0314ef-8ced-46ab-a7c2-cbf76330a8bb.png">
<img width="421" alt="Screenshot 2021-10-06 at 17 42 46" src="https://user-images.githubusercontent.com/667058/136237604-1913b587-7fc0-4341-84db-64724097dceb.png">

**Comment by nhanledev** [comment]
Postman Desktop Agent v0.3.9 is also experiencing this issue

**Comment by zhuww0236** [comment]
> The fix for this issue is available now on v9.0.5 version. If you are on Postman v9.0 and above, do 'Check for Updates' to get access to this version. Looking forward to hearing if the issue is resolved at your end.
> 
> [EDIT] If you are on Postman v8, v8.12.4 is available as well with the fix.

My electron application also shows' certificate has expired '. Can you share how to solve this problem? Thank you very much

**Comment by dan-j** [comment]
I thought the same thing as @drissfoo with it not working for me but working for colleagues, but they still had "verify ssl certs" disabled.

<img width="499" alt="Screenshot 2021-10-12 at 13 52 38" src="https://user-images.githubusercontent.com/5727701/136960246-322b190c-c114-45d8-b620-43c2da01db86.png">

**Comment by evpill** [comment]
I'm on Postman version 9.1.1 (Windows) and still having this issue. I had "verify ssl certs" disabled but enabled it because I'm getting similar errors when setting up webhooks from GitHub and OpenShift Container Platform and was wondering why I wasn't getting the error there. Looks like it is still a widespread issue, possibly all these services are pulling from the same source for their Trusted CAs. However, it looks like my web-browsers are the only apps that can verify certificates correctly at the moment... :( ... Fortunately (???), I can disable SSL verification with GitHub webhooks and in Postman but haven't figured out how to make OSCP less secure yet... 

It looks like I may have to adjust my expectations while waiting for everyone to adjust to CST (You thought DST was hard to adjust to, Covid Savings Time has everyone in a dream-like vacation daze). I would have thought that getting certificates to work properly would have been higher on peoples' priorities.

**Comment by davidaugustus-focusmate** [comment]
Seeing the same issue on Postman version 9.0.9 (MacOS, Chrome)

<img width="224" alt="Screen Shot 2021-10-28 at 1 46 41 PM" src="https://user-images.githubusercontent.com/87717697/139308325-9dfc0e16-9d01-44a8-9cfb-63c489a6f257.png">
<img width="351" alt="Screen Shot 2021-10-28 at 1 47 02 PM" src="https://user-images.githubusercontent.com/87717697/139308329-9da0c7eb-f66f-4107-b7c9-402e4383147a.png">
<img width="467" alt="Screen Shot 2021-10-28 at 1 47 27 PM" src="https://user-images.githubusercontent.com/87717697/139308332-5f9c78ae-10ab-4893-ae98-ea101c06147f.png">

**Comment by bumblefudge** [comment]
Same here, 
Windows 10 x64
Postman Agent W64 v0.3.9
![image](https://user-images.githubusercontent.com/37127325/139447527-e4ed497b-73c4-4c50-b197-d50961ed4940.png)

**Comment by vivekmittal** [comment]
+1

**Comment by superboyiii** [comment]
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
See here. It's a dependency issue. Please update your OS dependency to the latest, then make POST or GET to the server with `DST Root CA X3`

**Comment by johnathany505** [comment]
Nothing  ritenow

**Comment by AmiinaAhmed** [comment]
still have the same problem 
OS: Windows 10 
Postman v9.4.0 is the latest version.
and it is needed to disable the SSL certificate to works (however I have a warning)

**Comment by KamilWitkowski7** [comment]
This issue happens when one of the certs in pem files is outdated.
In my case removing the outdated cert from the pem file made this issue disappear.

**Comment by AlejandroDaneri** [comment]
+1
