### ISSUE TITLE
Postman 9.0.3 generated cURL does not work on terminal (--data-urlencode)

### ISSUE THREAD

**Issue by Dentrax** [a85/POSTMan-Chrome-Extension#10332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Copy the following [consul catalog](https://www.consul.io/api-docs/catalog) URL into Postman:
```
http://10.11.0.111:8500/v1/catalog/service/thanos-query-store-api?filter=(ServiceTags not contains "team=foo")
```
**Generated cURL code snippet returns different response status in terminal.**

It generates:
```
$ curl -L -X GET 'http://10.11.0.111:8500/v1/catalog/service/thanos-query-store-api?filter=(ServiceTags not contains "team=foo")'

400 Bad Request
```

But I expect something like:
```
$ curl -L -X GET http://10.11.0.111:8500/v1/catalog/service/thanos-query-store-api --data-urlencode 'filter=(ServiceTags not contains "team=foo")'

# 200 OK
```

### Steps To Reproduce

1. Open a new request tab
2. Paste the following URL: `http://10.11.0.111:8500/v1/catalog/service/thanos-query-store-api?filter=(ServiceTags not contains "team=foo")`
3. Get the cURL code snippet:
```bash
curl -L -X GET 'http://10.11.0.111:8500/v1/catalog/service/thanos-query-store-api?filter=(ServiceTags not contains "team=foo")'
```
4. Paste into terminal and expect non-200 (400 bad request) response

### Screenshots or Videos

![Screen Shot 2021-09-28 at 15 41 52](https://user-images.githubusercontent.com/16493751/135088905-ea117ede-4004-4cc3-b346-ce369e9ffedb.png)

### Environment Information

```markdown
- Operating System: macOS 11.5.2
- Platform Type: Postman Native App
- Postman Version: 9.0.3
```

**Comment by DannyDainton** [comment]
Hey @Dentrax 

Is this still an issue for you? From what you have added to a request, it appears to be working correctly. 

The URL contains a query param `?filter=(ServiceTags not contains "team=foo")` so the generate code snippet reflects this value.

In order to have the expected response you mentioned, it would need to be added to the request body configuration which also adds the correct header for that type of request.

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/17089546/158988068-a64cd581-181a-48a4-8c8e-d0d8954b8a29.png">

**Comment by DannyDainton** [comment]
Hey @Dentrax 

I'm going to close this issue - If you're still facing we can look to open it again.
