### ISSUE TITLE
Postman Flows does not run Test javascript

### ISSUE THREAD

**Issue by OtherLeadingBrand** [a85/POSTMan-Chrome-Extension#10359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman Flows does not execute the javascript in the Test tab of a request. Consequently this is preventing me from creating environmental variables shared between requests when using the new flow feature.

### Steps To Reproduce

1. Open a new request tab and configure it.
2. Click the Tests tab and add script to create/set an environmental variable. (ie "postman.setEnvironmentVariable")
3. Save the request
4. Create a new Flow and add the request.
5. Run the request.
6. Note the script in the Test tab of the request did not run.

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: 
- Postman Version: 9.0.5
```

### Additional Context?

I am unable to find a workaround. Unfortunately the Create Variables node of Flows does not allow me to specify JSON and select variables from the output of a request.

**Comment by saswatds** [comment]
Hi @OtherLeadingBrand , thanks for reaching out.
Could you confirm if tests are not running or just updating environment is not working. In the latest version, you will notice a new `test` port to also be present on the Send Request block. 

Currently, Flows only uses environment in a ReadOnly mode, so updating environment from requests within flows will not work. The reason behind this decision is that, flows allows running request across various and this has potential to update unrelated environments.

The create variable is supposed to solve all the use-cases dealing with variables. Could you explain to me what problems you are facing with it.

**Comment by OtherLeadingBrand** [comment]
Thanks for the quick response @saswatds.

1. I am currently on version 9.0.5 and do not see a Test port but I will check for updates later this week to see if it is available.
2. I believe your assumption is correct and the issue is that the environment variables are read-only in this flow. Apologies for not considering that possibility.
3. After further investigation, the issue I'm having with the Create Variables block is because the response I'm receiving from the service is JSON encoded as text/plain. I think I either need to fix the return type of this legacy API to encode as JSON or utilize the Parse JSON block to parse the data into vars that I can use as the input for another Send Request block.

At this time I believe this issue should be closed. 

Thanks again,
OLB

**Comment by saswatds** [comment]
@OtherLeadingBrand 
1. The desktop version of the app is updated very slowly. You can try out http://go.postman.co/ which is the web version of postman. We try to update and push to Flows everyday in web.
3. Yup you are right. There is also a small bug in Parse JSON block because of which it is not able to create the schema for the data, but we will fix it asap and let you know.

**Comment by AskMeAgain** [comment]
> Currently, Flows only uses environment in a ReadOnly mode, so updating environment from requests within flows will not work. The reason behind this decision is that, flows allows running request across various and this has potential to update unrelated environments.

This is sad to read, as i have a usecase where we setup different environments for different users. I would argue that this is a decision which should be on the user. there is no reason to protect the users from themselves :(

**Comment by saswatds** [comment]
Cross posting here https://community.postman.com/t/user-feedback-postman-flows/28121/109?u=saswatds 

This is not a permanent decision, just a temporary one while we figure-out the logistics of environment with flows.

We also want to let uses define and use multiple environments within flows, so that they are not limited to defining a single environment for the entire flow. It is also possible to use one flow inside another flow in the future, which again brings in the question as to which environment should be used.

We also are exploring providing a storage block which will be capable of storing any kind of data and persist across executions, and not limited by the key value pair format that Environment's allow. We wish environments to be true [Environment Variable](https://en.wikipedia.org/wiki/Environment_variable) where we are also able to load Environments from the OS when we enable running flows in CI environments.

There are a lot of decision that we have not taken yet, so it was safest for us to make the current environment readonly :crossed_fingers: We promise to figure this out soon.
