### ISSUE TITLE
Postman email alert does not work for Distribution list

### ISSUE THREAD

**Issue by pmathur21** [a85/POSTMan-Chrome-Extension#10419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

when setting up the monitor for postman, the alerts do not send emails to a distribution list, but sends it for individual ids.

### Steps To Reproduce

1. create monitor for a collection
2. put DL in email alerts
3. run monitor

### Environment Information

```markdown
- windows 
- postman web
- 8.8.0
```

**Comment by xk0der** [comment]
Hey @pmathur21  👋  make sure the Distribution-List alias is externally available. You should be able to test this by sending an email from your personal email ID to the DL. If that doesn't work, you would need your IT team to enable it to accept emails from external sources.

If the DL is externally available and is accepting emails from external sources, do raise a ticket with us here: https://postman.com/support so that we can collect some more data to troubleshoot this issue.
