### ISSUE TITLE
No longer able to open more tabs after viewing "Globals".

### ISSUE THREAD

**Issue by rjprmr** [a85/POSTMan-Chrome-Extension#10424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I click to view "Globals", subsequent items in the collection tree only open in the same tab instead of opening in a new tab. This now prevents opening further tabs.

### Steps To Reproduce

1. Navigate to "Globals" in the "Environments" section and click to view, should open in a new tab.
2. Click on an existing collection item (folder or request), this will now open the in tab that was showing the Globals.
3. Subsequent items now all open in the same tab.

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: v9.1.3
```

### Additional Context?

Opening new tabs works fine. Also closed and restarted the app a couple of times with the same result.
Even after closing the tab that I viewed the Globals in, when clicking on any other item and opening a new tab in it's place exhibits the same problem. e.g. If I opened Globals in the 3rd tab, closing it and open another item as tab 3, will then prevent opening any further tabs. If opening Globals as the first tab will restrict you to 1 tab (for existing items).

**Comment by malvikach** [comment]
@rajparmar-tsw thanks for writing to us about this. However, this is expected behavior. Items will open up in new tabs when the current tab has unsaved changes (so you don't lose them). We open collections/requests/environment or any other work items on the same tab if the current tab doesn't have any unsaved changes. This is true for globals and other work items as well.

Please let me know if you require any further information/help in this regard. 

I will be closing the issue for now.
