### ISSUE TITLE
Problem whit get request

### ISSUE THREAD

**Issue by andry0092** [a85/POSTMan-Chrome-Extension#10471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hi , i'm trying to call a local API , a simple HTTP GET like this : http://localhost:9000/api/spool , on chrome it works :

![Schermata da 2021-11-30 11-34-23](https://user-images.githubusercontent.com/85300482/144031654-8a4245b3-2327-41ba-a850-8d960b4fa931.png)

But if i try it on Postman i have this error : 

![Schermata da 2021-11-30 11-36-37](https://user-images.githubusercontent.com/85300482/144031813-cdd0176a-f3ea-4a56-813c-6860d7e14a8e.png)

The headers that i return are this : 

![2021-11-30_11-49](https://user-images.githubusercontent.com/85300482/144033777-f3409142-7916-40e6-bcac-9fb2309ad4d2.png)

Can you tell me which is the wrong one ?

Thanks for the help.

### Steps To Reproduce

1. Try a GET request

### Environment Information

```markdown
- Operating System: Ubuntu 20.04.3 LTS
- Platform Type: Native APP
- Postman Version: 7.36.5
```

**Comment by postman-staff** [comment]
Hi there,

Thank you for opening this query. I'm happy to help!

I'm sorry you are running into this issue when trying a GET request.

Since this issue is not present when you run the request on the Postman Web App. There seems to be something going on in your Desktop app.

To be able to further troubleshoot I will need more information about your device. For your privacy and security, would you mind logging a case directly with our team on: https://www.postman.com/support

Kind Regards,
Rubi
Technical Support Engineer | Postman



Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by postman-staff** [comment]
Hello there,

Just letting you know that I'm going ahead and closing this support conversation.

Please reach out to our team directly on: https://www.postman.com/support

To be able to further troubleshoot while protecting your privacy and security.

Have a great day!
Rubi
Technical Support Engineer | Postman


Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`
