### ISSUE TITLE
Postman does no start after installation with "preparation workspaces" message

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#10480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman versions higher than 8.6.0 (e.g. 8.10.0,  9.3.1) does not start at all. After installation there is a message Please wait for preparation workspaces forever.
The only workout I have found is to get back to 8.6.0.

### Steps To Reproduce

1. Install 9.3.1
2. See error

### Environment Information

```markdown
- Operating System: windows 7 x64
- Platform Type: i5 desktop machine with 3 gb ram
- Postman Version: 9.3.1
```

**Comment by postman-staff** [comment]
Hello @m3dbedb,
Sorry to see you're facing difficulties with starting the latest version of Postman.

Would you be able to try clearing your installation's local cache and try to install the latest version after that to see if that helps?

-  https://support.postman.com/hc/en-us/articles/360025359014#h_b38048ee-6505-4f83-a0f0-5d4f51fcb6d5

After clearing the local cache you can run the installer for the latest version, I'll link it below

- Windows - https://dl.pstmn.io/download/version/9.3.1/win64

Please let us know how it goes

via @nasco-a | Postman Support

**Comment by postman-staff** [comment]
Hello @m3dbedb,
We're checking in if you had the chance to go over our last reply.

Please let us know if you had the chance to try the steps listed there and if they helped?

via @nasco-a | Postman Support

**Comment by postman-staff** [comment]
Hello @m3dbedb,

Since we haven't heard from you in a while, we will go ahead and mark the ticket as closed.

In case you have any further questions or issues, it's recommended that you create a new support ticket, so we can assist you better:

-  https://support.postman.com/

Thank you!

Best Regards,
Atanas

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`
