### ISSUE TITLE
Please remove the redundant title below the tabs

### ISSUE THREAD

**Issue by Jebarson** [a85/POSTMan-Chrome-Extension#10510]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Please remove the title that is above the textbox where you enter the url.

1. The information is redundant.
2. The amount of time I have clicked the title instead of textbox is humongous. Since the title is bold, it is human tendancy that the user would overlook the normal text

### Describe the solution you'd like

Just remove that title. The text box is sufficient

![image](https://user-images.githubusercontent.com/10510974/146850270-eb346cad-fd40-4d32-b648-04117a02e413.png)

**Comment by shubhbhargav** [comment]
@Jebarson If I am not wrong, you are referring to the name / slug of the request which is generally used for human readable names. Since URLs could become lengthy to identify the requests in a collection, the slug / name helps with the identification better.

For example, in the above screenshot, the highlighted string can be `Get Weather Map`.

Let me know if this helps. :) Closing the issue for now. We can reopen it if you need any further help on the same.
