### ISSUE TITLE
Wrong work with escaped character "/"

### ISSUE THREAD

**Issue by AlexandrTairov** [a85/POSTMan-Chrome-Extension#10519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When using the desktop version, an error was noticed that when sending a variable in path variables, it was necessary to escape spaces and slashes in %20 and %2F, respectively.
Everything works well with spaces encoding, but sending%2F returns 400 http status "Bad request"

### Steps To Reproduce

1. Open a new request tab
2. Make request to service with escaped "/" (%2F)
3. See the error message

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/57834376/147379806-222fc585-0a61-464d-a12c-56e4c9d4ec39.png)

### Environment Information

```markdown
- Operating System: Windows 10 Business
- Platform Type: Desktop
- Postman Version: 9.6.0
```

**Comment by shubhbhargav** [comment]
@AlexandrTairov I tried reproducing the issue with httpbin but wasn't able to do the same. It could be specific to the service you are calling. In order to verify it further, can you please have a look at the `Console` in the left bottom corner of the app and see if the request is being sent as expected by the server?

---
Regarding the test I did on my end to validate the issue, I used a request: `GET https://httpbin.org/anything/:anything` with path variable value `1234%20-%20567%2F89` and got a 200 response.

**Comment by shubhbhargav** [comment]
@AlexandrTairov I am closing this ticket as of now. Please feel free to let us know if you are still facing the issue. We will re-open the ticket and debug / resolve accordingly.

**Comment by AlexandrTairov** [comment]
@shubhbhargav 
Sorry, I forgot about this issue. Problem was from our side and thank you for your help :)
Of course, You can close this tickect)
