### ISSUE TITLE
Postman v9.5.0 stuck on loading screen

### ISSUE THREAD

**Issue by Fuzzo** [a85/POSTMan-Chrome-Extension#10526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Existing issues searched but are about different environment.

Postman v9.5.0+ crash on loading screen right after run, a kill is required.
v9.4.1 works perfectly.
The problem is that is not possible to avoid auto-update between minor versions, so i've to re-install v9.4.1 every time i need to use it.

### Steps To Reproduce

1. Open Postmap
2. Wait forever on the loading screen

### Environment Information

```markdown
- Operating System: Windows Server 2019
- Platform Type: Native App
- Postman Version: 9.5.0+
```

**Comment by jbool24** [comment]
To add to this... This is because the APP is a dirty bird and shutdown does not clean up after itself :facepalm: 
The global lock is left between launches in the temp directory for the socket.  A work around is to find and unlink the `SS` link from the Postman configs directory. Hopefully Postman can clean up this sloppy behavior.

For Linux: 
`unlink ~/.config/Postman/SS`  

and cleanup the dir that the link pointed to
`rm /temp/.org.chromium.Chromium.ysNRD4`

**Comment by bavulapati** [comment]
@Fuzzo Can you please share the logs when this happened?

**Comment by Raj-postman** [comment]
@Fuzzo @jbool24 Could you please submit a support request: https://support.postman.com/hc/en-us/requests/new to help us look into this further?
 
Including the application logs and system details as per [this article here](https://support.postman.com/hc/en-us/articles/360047765713-How-to-open-my-logs-directory), would be really helpful to check this from here.

**Comment by Fuzzo** [comment]
Done: https://support.postman.com/hc/en-us/requests/94497

**Comment by lflucasferreira** [comment]
I am facing the same issue after each update.

So I proceed to the command line in order to find the job id to kill it.

1. `ps -e | grep postman`
> 24445 tty2     00:00:00 postman
24446 tty2     00:00:00 postman
24485 tty2     00:00:06 postman
24509 tty2     00:00:01 postman
24524 tty2     00:00:01 postman
24561 tty2     00:00:02 postman
24582 tty2     00:00:42 postman
26967 ?        00:00:03 postman
26971 ?        00:00:00 postman
26972 ?        00:00:00 postman
27013 ?        00:00:13 postman
27075 ?        00:00:00 postman
27079 ?        00:00:06 postman
27090 ?        00:00:00 postman
2. `kill <jobId>` => `kill 26967`

**Comment by y0rd4nis** [comment]
Facing the same problem over here too.

I'm currently running Postman v9.8.2 but I notice this issue in some versions prior to 9.8.2. Every time I update Postman using the "update" notification in Settings, it tries to reload itself and get stuck in the splash-like loading window, every time I needed to access System Monitor and kill all running "postman" processes, including the one named swap_and_relaunch.sh".

OS: Fedora Linux 34 and 35
Postman: Native Postman app for Linux

**Comment by twitharshil** [comment]
Thanks for reporting! 
Seems to be a genuine issue that is reproducible after applying the updates on the Linux platform. We have sent a fix in Postman v9.8.3 for this issue. Marking the ticket closed for now, feel free to re-open if the issue is still reproducible on Postman v9.8.3 onwards :)

**Comment by lylest** [comment]
as i am currently speaking i have downloaded the latest version and it has stuck on loading

**Comment by luisalvarado** [comment]
Same thing here. It randomly gets stuck loading, either the loading screen or loading the calls for a specific collection

![image](https://github.com/user-attachments/assets/86db3758-ff45-42b5-bd06-15869e2c6881)


Just stays like that loading.

**Comment by jbool24** [comment]
I use Postman quite a bit and loved it in the past but I just disagree that I should have to Log-In before I can use a desktop tool.

[Bruno](https://www.usebruno.com/) is a local tool that allows you to check in saved calls and other data directly into your api and test directories in a git repo.

In my opinion this scratches the itch the way the original Postman application did prior to requiring web logins for the desktop.

**Comment by DSchau** [comment]
@jbool24 hello! Thanks for your comment, I wanted to share some detail on one particular point you make.

> I use Postman quite a bit and loved it in the past but I just disagree that I should have to Log-In before I can use a desktop tool.

We're discussing this on a platform that requires a login. Additionally, the point you make here is inaccurate, the Postman desktop application does not require a login. We support a ["Lightweight API Client"](https://learning.postman.com/docs/getting-started/basics/using-api-client/) that is intended to be used for non-collaborative, individual developer use cases for developers perhaps like yourself who do not have a desire or need to log-in. Importantly I will also note that the signed-in experience has more useful functionality even for the single-player developer like collections (to group requests, write tests and automate these tests, and so on), workspaces (to group collections and segment your work for private, public, or team visibility), Postman Vault (for secure-by-default local-first secrets that never touch the Postman "cloud"), and many others but we understand that not signing in can be important for some users!

@luisalvarado sorry to hear about your experience, that's frustrating. Would you mind opening a new issue, as it's highly unlikely your issue is related to this issue on Postman v9.5.0 which has since been resolved. We'd love to get to the bottom of it to understand why you are hitting that error.

**Comment by luisalvarado** [comment]
@DSchau Much appreciated friend. For now there is no need to open another ticket. I uninstalled postman and installed again and it  works properly. If it happens again I will follow your guidance with a new ticket. Thank you for your help.

**Comment by luisalvarado** [comment]
Just letting you know that for the last 2 weeks, I have had to uninstall postman 3 times already. Today is the 4th time because it stays like this:

![image](https://github.com/user-attachments/assets/7ae720e0-fadd-4b33-ab91-ff0490c1f624)

This "might" be related to some people saying that the session for their account ended but postman had no way of letting the user know, so it was stuck in a loop between a user session that ended and the notification of updating them again.

This is, if it helps, the snap version of postman on Ubuntu. This started happening on Ubuntu 24.04 and up.
