### ISSUE TITLE
Postman not responding to keyboard

### ISSUE THREAD

**Issue by MohammadMirsafaei** [a85/POSTMan-Chrome-Extension#10520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I try to type in any part of the application(url, body, ...) only 'w' and 'z' keys work. When I press other keys nothing happens. I have to type in another app and then paste in postman

### Steps To Reproduce

1. open app
2. try to type!

### Environment Information

```markdown
- Operating System: Ubuntu 20.04
- Platform Type: Postman for Linux
- Postman Version: 7.36.5
```

### Additional Context?

I tried changing keyboard but issue still exists.
Also I think it's may be related to electron cause I face some kind of same issues in vscode.

**Comment by m3dbedb** [comment]
I confirm the issue both in windows and linux https://github.com/postmanlabs/postman-app-support/issues/9950

**Comment by postman-staff** [comment]
Hi there,

Sorry to see you are facing issues using the app.

To investigate further and we will need App logs, your email ID & other details. Since GitHub is a public platform it is not good to get those details on this thread from you for security reasons.

To assist you further - could you open a new support request from our support channel using this link - https://www.postman.com/support/ , please? Also, do not forget to add this GitHub issue number and your GitHub username in the support request description to make it easy for us to track. We will wait to hear back from you on our support channel.

Meanwhile, to get you unblocked you can use Postman on Web - https://go.postman.co/ as it has the same UI & feature set as that of the desktop/native application and let me know how it goes.

via @Swapnil-getpostman | Postman Support

**Comment by MohammadMirsafaei** [comment]
I installed version 9.8.2 and it seems to work ok.

**Comment by postman-staff** [comment]
Glad to know it's working as expected now. We are going ahead and closing only the support request but the GitHub request will still be open, so feel free to respond to this thread if you have any other queries.

via @Swapnil-getpostman | Postman Support

**Comment by develaparX** [comment]
hello, i cant type anything in postman app on ubuntu. the version is 11.14.1, can you help me?

**Comment by mohdhammad786** [comment]
Facing the issue , once i try to type some thing it crash in ubunto some with other similar apps kike bruno , what is the main cause of it ?

**Comment by ddatdt12** [comment]
I’m still having this issue on macOS M3. The URL gets messed up when I type in the address bar.

**Comment by dani-fadli** [comment]
I am using Postman version 11.49.1. The problem occurred for the first time for me. Restarting the app doesn't help. Until I tried to log off from Ubuntu and log back in, it solved the problem. Hope this helps someone.
