### ISSUE TITLE
The collections saved on Windows machine is not viewable on Mac machine  & vice-versa using same credentials.

### ISSUE THREAD

**Issue by PathakAditya** [a85/POSTMan-Chrome-Extension#10528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The title is sufficient, please comment for more details

### Steps To Reproduce

Log in to Mac and Windows with the same credentials.
verify the collections in both machines.
Collections created in Windows are not visible on Mac and vice and versa.

### Screenshots or Videos

NA

### Environment Information

```markdown
- Operating System: Windows - 10 and macOS Monterey
- Platform Type: NA
- Postman Version: Lates
```

### Additional Context?

NA

**Comment by postman-staff** [comment]
Hi @PathakAditya

Thank you for reaching out to postman.

We tried replicating the issue from our end and it seems that it worked for us as expected and the collections were showing up on both the machines. We have tested it on the latest version (v9.7.1) on both machines.

Could you please provide us with some more information about the issue so that we can check and investigate further:

- Have you encountered this issue earlier?
- Can you try reinstalling/updating the app to the latest one on both the machines?
- Are you seeing a similar issue on Postman web(http://go.postman.co/ )?

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @PathakAditya

Hope you are doing well.

I just wanted to follow up on the previous message to check if you have missed it.

Please provide the requested details so that we will work together on it.



Feel free to reach back out if you need anything else. I'd be more than happy to help:)

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi **@**PathakAditya,

Just letting you know I’m still here so feel free to give me a shout if you’re still running into any issues.
via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi hello,

Just letting you know that I'm going ahead and closing this conversation. If you still need help, just respond to this ticket to re-open it. Otherwise, please feel free to reach out again later!

Have a great day:)

via @Lincimary | Postman Support
