### ISSUE TITLE
Parse request body error using `import request`

### ISSUE THREAD

**Issue by taozi0818** [a85/POSTMan-Chrome-Extension#10600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

OS: MacOS
Postman Version: 9.0.9 (9.0.9)

When a field in request body contains JSON string, Postman can't parse JSON string correct by import request.

### Steps To Reproduce

1. Create request by `import request`
2. Select tab `Raw text`
3. Paste raw text
4. click button `continue`
5. click checkbox `body` in new tab

Then you can see error in request body. There is a code demo:
```
curl --location --request POST 'localhost:3000/api' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonStr": "{\"test\": \"value\"}",
    "number": 1
}'
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/18347146/150737465-b9646bb6-2b14-437a-9548-e1e1478abfc8.png)

### Environment Information

```markdown
- Operating System: MacOS
- Platform Type: Native APP
- Postman Version: 9.0.9 (9.0.9)
```

**Comment by shubhbhargav** [comment]
@taozi0818 Thanks for reporting the issue. I tried reproducing it on the latest Postman app 9.10.1 and wasn't able to reproduce it. Can you please try upgrading the app and see if the issue is persisting at your end?

I am sharing a reference recording below to verify if I followed the right steps:

https://user-images.githubusercontent.com/41579749/151114914-9bd78174-7d10-4e56-9091-9b535d000741.mov

**Comment by taozi0818** [comment]
@shubhbhargav Thanks for your reply. It works on App(Version: `9.10.1`) !  I found this issue after `check for updates`  a few weeks ago, but didn't create issue at that time. I remember this bug a few days ago, so create this issue without upgrade. I'm sorry about this.
