### ISSUE TITLE
Using _ => {} function notation rather than () => {} in pm.test causes test not to show up in tests results

### ISSUE THREAD

**Issue by apptio-milarsen** [a85/POSTMan-Chrome-Extension#10612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When writing postman tests, if you use underscore for the "empty parameter" notation on the test callback function:
`pm.test("Some test", _ => { pm.response.to.have.status(200); })`
the code inside the test callback function will run, but will not show up in Postman's test report. 
This occurs both for a single request and in the request runner.

The parentheses notation works fine:
`pm.test("Some test", () => { pm.response.to.have.status(200); })`

### Steps To Reproduce

1. Create a new request with any url (https://google.com)
2. Add a test like `pm.test("Some test", _ => { pm.response.to.have.status(200); })`
3. Send the request
4. No passed test will show up in the test results, and the test page will say "There are no tests for this request"

### Screenshots or Videos

<img width="1783" alt="Screen Shot 2022-01-27 at 5 08 10 PM" src="https://user-images.githubusercontent.com/92469268/151453621-e044bab0-0857-44c2-ae61-d55f01cc17a0.png">

### Environment Information

```markdown
- Operating System: macOS Big Sur 11.6
- Platform Type: Native App
- Postman Version: 9.11.0
```

**Comment by shubhbhargav** [comment]
@apptio-milarsen Thanks for highlighting this behaviour. 

This is actually expected because `_` is considered as an argument in sandbox, similar to how `done` or `callback` is provided in javascript. Hence, similar to how `done()` or `callback()` works , `_()` needs to be called for the async callback to happen and the corresponding test results to be shown on the test report.

More info around this available here: https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#writing-test-assertions

Let me know if this helps.

**Comment by apptio-milarsen** [comment]
Thanks! That clears this up.
