### ISSUE TITLE
"GET /collections" is not listing all collections from all workspaces

### ISSUE THREAD

**Issue by olivermonaco** [a85/POSTMan-Chrome-Extension#10617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I believe this duplicates https://github.com/postmanlabs/postman-app-support/issues/10535 but this issue has been closed without resolution.

I'm only getting one result when executing the following code, and there should be more than eight results.

`curl --location --request GET "https://api.getpostman.com/collections" \
-H "X-Api-Key: $api_key" | jq > postman_collections.json`

We have multiple workspaces, I am an admin for more than one workspace, and I have "watched" multiple collections.

A colleague ran the same command, and received six responses. Two of the responses are duplicates of each other. See below:
```{
    "collections": [
      {
        "id": "e0caed8a-9665-4e79-9a50-7726e7c6addf",
        "name": "Collection 1",
        "owner": "16503731",
        "createdAt": "2021-07-22T18:51:50.000Z",
        "updatedAt": "2022-01-03T21:21:43.000Z",
        "uid": "16503731-e0caed8a-9665-4e79-9a50-7726e7c6addf",
        "isPublic": false
      },
      {
        "id": "e52a54f4-c3a9-4eb2-98fa-6a74ebf640e7",
        "name": "Collection 2",
        "owner": "17110559",
        "createdAt": "2021-12-01T00:13:06.000Z",
        "updatedAt": "2022-01-04T20:29:27.000Z",
        "uid": "17110559-e52a54f4-c3a9-4eb2-98fa-6a74ebf640e7",
        "isPublic": false
      },
      {
        "id": "fb869463-dd5c-44f5-aa5e-5b16b5b81bf1",
        "name": "Collection 3",
        "owner": "17110559",
        "createdAt": "2021-10-05T15:29:54.000Z",
        "updatedAt": "2022-01-18T20:37:49.000Z",
        "uid": "17110559-fb869463-dd5c-44f5-aa5e-5b16b5b81bf1",
        "isPublic": false
      },
      {
        "id": "fb869463-dd5c-44f5-aa5e-5b16b5b81bf1",
        "name": "Collection 3",
        "owner": "17110559",
        "createdAt": "2021-10-05T15:29:54.000Z",
        "updatedAt": "2022-01-18T20:37:49.000Z",
        "uid": "17110559-fb869463-dd5c-44f5-aa5e-5b16b5b81bf1",
        "isPublic": false
      },
      {
        "id": "a1572f8e-7557-419b-b06e-b961a7fa5b32",
        "name": "Collection 4",
        "owner": "3199667",
        "createdAt": "2021-03-22T20:14:58.000Z",
        "updatedAt": "2022-01-25T20:45:48.000Z",
        "uid": "3199667-a1572f8e-7557-419b-b06e-b961a7fa5b32",
        "isPublic": false
      },
      {
        "id": "a7e35c62-eec4-4fa6-ac52-8487e4796ec1",
        "name": "Collection 5",
        "owner": "3199667",
        "createdAt": "2021-03-19T14:08:39.000Z",
        "updatedAt": "2022-01-28T16:21:34.000Z",
        "uid": "3199667-a7e35c62-eec4-4fa6-ac52-8487e4796ec1",
        "isPublic": false
      }
    ]
  }
```

This will greatly help our testing. Can someone look into this?

### Steps To Reproduce

Send a GET /collections request and review the response

### Environment Information

```markdown
- Operating System: Mac OS Big Sur v 11.6
- Platform Type: Postman API
- Postman Version: Version 9.10.0
```

**Comment by bpedro** [comment]
Hi @olivermonaco,

Can you access the collections individually, e.g. by performing a `GET /collections/{collectionId}`? If not, what is the error message that you receive?

Thanks!

**Comment by olivermonaco** [comment]
Hi @bpedro , thanks for the response. Yes, I am able to get each collection individually via the collectionId listed in the Postman UI. I can even obtain the collections that were missing from my colleague's response.

**Comment by valentinbeggi** [comment]
Hello @bpedro , sorry for the delay.

After some investigations I think I know where the issue comes from.

When calling `GET /collections` with `API Key A`, it seems that only the collections created (or forked) using `API key A` are retrieved. 

_To reproduce:_

Consider `workspace A` and `B`, `dev A` and `B`.
If collections in `workspace A` were all created by `dev A` and collections in `workspace B` were all created by `dev B`, if `dev A` calls `GET /collections` with `API Key A` he will only retrieve collections from his workspace. However if he forks one of his collection into `workspace B` (while still using `Api Key A`), `GET /collections` will list his collections from `workspace A` + the forked collection from `workspace B`.

For me, the expected behavior would be : `GET /collections` lists all collections from workspaces of which `dev A` has at least read rights.

_______________________________

We tried a workaround by listing all workspaces (`GET /workspaces`), then for each of these workspaces calling (`GET /workspace/{workspaceId}`) to list all collection IDs and then for each collection calling `GET /collection/{collectionId}`in order to retrieve fork labels of all collections from all workspaces, regardless of who the author of the collection is, but we also found that `GET /collections/{collectionId}` does not return information about the fork status of the collection (whereas `GET /collections` does).

Do you think I should create an issue about this ? I think it would makes sense for `GET /collections/{collectionId}` returned data to be at least as informative as `GET /collections`'s.

**Comment by bpedro** [comment]
Hi @olivermonaco and @valentinbeggi,

Thank you so much for providing those details. That helps a lot!

So, to summarize, there are two identified issues:

1. `GET /collections` is only listing collections that have been created or forked by the user making the request.
2. `GET /collections/{collectionId}` is not returning the fork status of the collection.

Can you please create a separate issue for item 2?

In the meanwhile, we will start on better understanding item 1 and finding a potential improvement.

**Comment by davidespihernandez** [comment]
Hi, @olivermonaco!
This issue should be solved now. I'm closing the ticket, feel free to reopen it if the issue persists.
Thanks for your patience!

**Comment by olivermonaco** [comment]
Amazing @davidespihernandez , thanks for your attention to this. I'll test this week
