### ISSUE TITLE
Linux non-snap installation breaks itself, most likely on update

### ISSUE THREAD

**Issue by NelsonAPenn** [a85/POSTMan-Chrome-Extension#10679]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

This is a relatively new issue I have been having related to (I'm assuming) Postman updating itself with the non-snap installation. I will sometimes go to open postman and find that it seems to have had a problem mid-update. 

Here is the output of an `ls -l` in the directory I installed postman before.
```
total 160160
-rw-rw-r-- 1 nelson nelson       306 Feb 17 18:20 log.txt
lrwxrwxrwx 1 nelson nelson        11 Feb  3 15:11 Postman -> app/Postman
drwxrwxr-x 7 nelson nelson      4096 Feb 18 09:15 Postman-1645110386321-old
-rw-rw-r-- 1 nelson nelson 163993744 Feb 17 10:06 Postman-1645110386321.tar.gz
```
The link `Postman -> app/Postman` is broken in this case, and the contents of `log.txt` are
```
2022/02/17 18:20:56:973 Postman-1645110386321 Swapping the old app with new one
2022/02/17 18:20:56:976 Postman-1645110386321 Swapping done
2022/02/17 18:20:56:984 Postman-1645110386321 Swapping the old app with new one
2022/02/17 18:20:56:986 Postman-1645110386321 Parent process is alive, killing it now
```

A couple more (maybe) relevant pieces of information: it is installed in a location that does not need root permissions. I have seen this issue exactly 3 times, so that may help point to an update that started the issue, updates worked fine before then. My install directory is called `postman`, not `Postman`, so `app` would appear in a directory called `postman`, not `postman/Postman/app`.

In each instance, replacing the contents of the directory with the contents of the archive fixes the issue.

### Steps To Reproduce

1. Power up your system
2. Try to open your desktop file that points to Postman
3. Find that it has, at some point, replaced itself with a log, *-old directory and a tar.gz archive (see image and `ls -l` output).

### Screenshots or Videos

![Screenshot from 2022-02-18 09-15-50](https://user-images.githubusercontent.com/46758351/154699018-b4925c2b-cde6-412d-b038-e77f21489c49.png)

### Environment Information

```markdown
- Operating System: Ubuntub 20.04
- Platform Type: Native App
- Postman Version:
(after fixing the issue the latest time)

Postman for Linux

Version 9.14.0

Architecture x64

Platform linux 5.13.0-28-generic
```
```


### Additional Context?

_No response_

**Comment by twitharshil** [comment]
Hey @NelsonAPenn 

Thanks for reporting the issue! Apologies for the trouble caused from our end. It seems to be a genuine issue & a fix for this is implemented already & planned to be out soon with the next minor version release for the postman application. 


This issue happens when an update is downloaded in the background & the user chooses to close the application. There are two ways to avoid this issue for the time being: 
1. You can choose to click on the `update download & restart now` item from the settings icon dropdown once an update is downloaded to avoid this issue. This issue will go away once the application is moved to Postman `v9.14.0` 
<img width="447" alt="Screenshot 2022-02-21 at 9 14 32 AM" src="https://user-images.githubusercontent.com/25850676/154885866-c2bf789d-029d-455a-8762-edc63da64ea3.png">

2. You can install postman using [snap](https://learning.postman.com/docs/getting-started/installation-and-updates/#installing-postman-on-linux). Snap updates the postman application automatically whenever it is available. 

----------
Edit: The fix is now available in Postman v9.14.0+ onwards.
