### ISSUE TITLE
Error importing collection - but appears to work

### ISSUE THREAD

**Issue by byrdman** [a85/POSTMan-Chrome-Extension#10692]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

When importing a collection I get a popup about "error importing collection", yet the collection appears to import fine.  Newman parses the collection fine.  Is there a log somewhere that will tell me what it thinks it doesn't like?

### Steps To Reproduce

Import a collection (that supposedly has a problem)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.14.1
```

**Comment by Harsh-Bansal** [comment]
@byrdman thanks for bringing this to our attention.

Can you help specify if this error comes immediately or after a while.

If it is coming after a while (say around 60 seconds) then this could be happening because you tried importing a large collection. In such cases the app assumes the import operation failed since no response was received for ~60 seconds but the import does proceed in the background and succeeds after some time.

It if is coming immediately logs will be helpful.
You can refer to these articles on how to collect the logs: 
1. https://support.postman.com/hc/en-us/articles/360038234154-How-to-generate-a-HAR-file-
2. https://support.postman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application-

**Comment by deigratia86** [comment]
@Harsh-Bansal 
I've ran into this issue as well. I have exported my logs and can attach, without combing through every line is there anything I need to scrub from the logs? 
Per some of the logs I got request timed out. 
So I tried raw text and file as well. So I'm not sure if the timeout would be expected here as well if it's literally sitting in postman. 

Also to note: 
I tried importing and attempted a few times so when I finally noticed they did indeed import, the APIs tab was filled with 6 API collections. 

When trying to I got an error here as well 'failed to delete' and it reappeared a second later.

**Comment by byrdman** [comment]
Somehow I missed the original reply, I'll get some logs pulled together.  The collections are indeed large.  I wouldn't say the "error" pops up immediately, say, within a couple of minutes of asking it to import probably.  And then a minute or so later the collection shows up imported.

I can also say I've had the behavior of when I delete, it deletes and then reappears (I think I've logged a second ticket on it).

**Comment by byrdman** [comment]
Here's what's in the log when the import throws the failure message:
`
[1280][1647895667637][requester][info]["SyncWindowService~Sync is disabled"]
[1280][1647895673988][requester][error]["CollectionInterfaceV2~createCollection - Error: ",{"error":{"name":"serverError","message":"Something went wrong with the server","details":"ESOCKETTIMEDOUT","source":"downstream"},"status":500,"headers":{}}]
[1280][1647895677647][requester][info]["SyncWindowService~Sync is disabled"]`

**Comment by byrdman** [comment]
Any news on this?  Need anything else from me?

**Comment by Harsh-Bansal** [comment]
@byrdman apologies for the delay.

The issue here is performance. Incase the collections to be imported are too large, the server ends up taking a long time and the client assumes the request failed, propagating the timeout error to the user.

Do note the collection will get imported after some time and will show up on the UI (as you have already mentioned)

We have made performance improvements to the collection import flow to address this issue.
However we have not made it General Available just yet.

Can you please share your issue information at `help@postman.com` so we can look into enabling the optimised flow for your team, thanks.

**Comment by Harsh-Bansal** [comment]
@deigratia86 in continuation with the above comment can you please share your issue information at `help@postman.com` so we can look into enabling the optimised flow for your team too, thanks.

**Comment by shubhbhargav** [comment]
@byrdman We have made some improvements to the collection import flows. Can you please let us know if you are still facing this issue?

**Comment by byrdman** [comment]
Could you elaborate on "share your issue information"?  What exactly do I
need to send to ***@***.***?

Sam

**Comment by shubhbhargav** [comment]
@byrdman We will need the collection JSON to be shared at `help@postman.com` (removing any sensitive data). You should be able to get the JSON via the `Export` action on the collection sidebar menu.

**Comment by byrdman** [comment]
Either the recent updates or clearing my postman cache seem to have fixed
the problem.

**Comment by shubhbhargav** [comment]
Thanks for the confirmation @byrdman. I am closing this issue as of now.
