### ISSUE TITLE
Version 9.4.1 the problem still exists

### ISSUE THREAD

**Issue by landsnail** [a85/POSTMan-Chrome-Extension#10706]
Version 9.4.1 the problem still exists
link：
https://tech-release.api.fuliaoyi.com/app-customer/v2/api-docs
Others can import success。like : https://tech-release.api.fuliaoyi.com/app-purchase/v2/api-docs

_Originally posted by @DQJ0521 in https://github.com/postmanlabs/postman-app-support/issues/8686#issuecomment-994726660_

---------------------------------

version 9.12.2 the problem still exists

**Comment by landsnail** [comment]
when i import data from link ，it throw error，the message is：Error while fetching data from link.

if is the  data too big to import?

**Comment by xioumau** [comment]
I'm having the same error

**Comment by Shivani2772** [comment]
Is there a solution for this?

**Comment by umeshp7** [comment]
The fix for import via link is available from 9.14.8 onward on the web. @landsnail The links you shared I am not able to get any content from them even when I try to hit it through the browser. Could you check the links and try again? 

@xioumau @Shivani2772 Could share some more details about the issue? Which version are you on, which type of app Web or Desktop? And if possible which link/url are you trying to import.

**Comment by xioumau** [comment]
@umeshp7 I was able to import by raw text not by link, for that I copied and pasted all the content of the json file in the raw text field. Im using Postman for Linux Version 8.12.5.

**Comment by umeshp7** [comment]
@xioumau if you could update the app to the recent version from here: https://www.postman.com/downloads/ and try again?

**Comment by DannyDainton** [comment]
Closing this as the fix was shipped in version 9.14.8.
