### ISSUE TITLE
NTLM Password Shown in Clear Text

### ISSUE THREAD

**Issue by kvnpttrsn** [a85/POSTMan-Chrome-Extension#10860]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The NTLM password is shown in clear text on the Collection Documentation pane. The password was stored as a secret global variable in an Environment.

### Steps To Reproduce

1. Create a global secret variable for NTML password in an Environment.
2. Create a Collection with NTLM Authentication, using the global secret variable.
3. Click the Documentation icon.
4. The clear text password is shown under the Authorization heading.

### Screenshots or Videos

![NTLM Password in Clear Text](https://user-images.githubusercontent.com/104160633/164516778-0655a6f7-3ae8-4ad2-a8d6-b8c3c1f233a3.png)

### Operating System

Windows 10 Professional

### Postman Version

9.15.11

### Postman Platform

Postman App

**Comment by akshaydeo** [comment]
@kvnpttrsn thank you for reporting this bug. We are looking into it on priority and we will keep this thread updated 🙇

**Comment by akshaydeo** [comment]
@kvnpttrsn We are working on this issue right now. I will update this thread as soon as the fix is available.

**Comment by uschwag** [comment]
@akshaydeo please recognise that this behaviour, the password shows up in documentation, isn't only the case for NTML but even classic basic auth.

**Comment by ajeet-postman** [comment]
@kvnpttrsn @uschwag 
This is an intentional flow to allow users to set custom placeholders or sharable values!

- Initial values are intended and used for placeholders/dummy values.
- For authentication specifically, any values saved in the collection are masked with default placeholders like `<key>`, `<value>`, `<username>`, `<password>` etc . The only way for users to use custom place holders like `<api-key>`, `<x-access-key>`, `use_key_here`  instead of `<key>` is through environments initial value. 

<img width="1062" alt="Screenshot 2022-04-27 at 10 25 16 PM" src="https://user-images.githubusercontent.com/99759143/169264789-b85dcb4d-3986-45df-810e-8a30f9a13252.png">

**To avoid revealing secret values, we suggest to use tokens in Current value and not Initial value.**

**Comment by akshaydeo** [comment]
@uschwag let me know if this helps you solve the issue 🙇

**Comment by uschwag** [comment]
@akshaydeo that is not a solution as the Learning Center explicitly says:

Secret type masks the [initial and current values](https://learning.postman.com/docs/sending-requests/variables/#specifying-variable-detail) for all workspace members and can be used to prevent unintentional disclosure of sensitive data, including API secrets, passwords, tokens, and keys.

There is no reason why just the documentation feature of a collection should make the exception. Exactly there it should be masked from my perspective.

**Comment by kvnpttrsn** [comment]
I definitely upvote the previous comments: this is not a solution. As a corporate user with strict requirements to protect login credential secrets, I feel betrayed by Postman revealing what its own documentation says the application will protect “unintentional disclosure of sensitive data, including API secrets, passwords, tokens, and keys.”


—
KEVIN PATTERSON
Corgan

D — 214-757-1893

**Comment by akshaydeo** [comment]
Thanks @kvnpttrsn @uschwag for your feedback. We are working on a fix. Will update this ticket as soon as we have the fix deployed 🙇‍♂️

**Comment by akshaydeo** [comment]
The fix is available on our latest versions and web app 🙇‍♂️
