### ISSUE TITLE
Newline is corrupted in JSON view

### ISSUE THREAD

**Issue by artem-karpenko** [a85/POSTMan-Chrome-Extension#1093]
Newline symbol written as "\n" turns into just "\", i.e.

> außerdem\n Anwendung

becomes

> außerdem\ Anwendung

**Comment by numaanashraf** [comment]
Which version of Postman are you using?

**Comment by artem-karpenko** [comment]
Version 2.1.6 (packaged).

**Comment by abhijitkane** [comment]
@artem-karpenko Are you still seeing this in v3.0.4?

**Comment by artem-karpenko** [comment]
Huh, now it's adding two more slashes to it:

> außerdem\\\n Anwendung

**Comment by nlwillia** [comment]
I'm only seeing the problem in the pretty view (v3.0.5).  The raw view is correct.  It seems like this has changed recently.

Raw: ["\n"]
Pretty: [  "\\\n"  ]

I guess it depends on the context you're interpreting the content in.  The raw form could be pasted into JavaScript, but would break JSON.parse.  The pretty form looks like it's being escaped for parsing, but if so, then it needs to use "\\n" instead of "\\\n".

**Comment by abhijitkane** [comment]
@nlwillia Are you still seeing this in 4.1.3?

**Comment by nlwillia** [comment]
The Pretty and Raw formats seem to be interpreting newlines the same now in 4.1.3.  I returned `["\n"]` from a test service and Postman rendered the literal as `"\n"` in both cases as expected.
