### ISSUE TITLE
Allow import of a gRPC service proto through Postman APIs

### ISSUE THREAD

**Issue by togiles** [a85/POSTMan-Chrome-Extension#10948]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

We have built automation around publishing open API specs to our postman workspaces, and would like to automat publishing gRPC apis as well.

### Describe the solution you'd like

I'd like a way to programmatically send a gRPC service (e.g. proto file) to postman via e.g. curl to a postman API and have it import that API into a given workspace (similar to how https://api.getpostman.com/import/openapi works for openapi specs).

Also, I'd like to be able to update an existing gRPC service in postman with newer versions via API.

### Describe alternatives you've considered

Manually ... which isn't all that great.

**Comment by abhijitkane** [comment]
@togiles The Postman API lets you:
1. Create APIs (https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-84071d33-c55a-4e21-912c-902b05151774)
2. Create versions within APIs (https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-9285095f-857c-4c6e-8274-508086fff766)
3. Add an API definition to a version (https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-138fe484-7f35-4b00-977e-4e433e67b4ce)

For gRPC, you can set the `type` in the third endpoint with `proto2` or `proto3`, and the `language` to `pr`. 

Hope this helps.

**Comment by togiles** [comment]
Thanks @abhijitkane at first glance this looks like everything we need - we got caught up in the import API, this interface looks much better.  Quick follow-up question, can one have both an openapi schema and a grpc schema for the same API in postman?  I ask - as we expose grpc end-points via grpc-gateway with an accompanying openapi schema, however we'd like to expose the underlying grpc endpoint as well which is the same endpoint just at a lower layer... does this make sense?  (I'm still pretty new to postman, so appreciate the help here)

**Comment by lennrt** [comment]
Thanks for those details @abhijitkane, this works well for our use case! In case anyone stumbles upon this issue, it seems that the language must be set to `proto` rather than `pr` to avoid an `InvalidParamsError`.

I noticed that [the docs in the public Postman workspace](https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a?entity=request-12959542-138fe484-7f35-4b00-977e-4e433e67b4ce) for Create Schema don't include these details about gRPC/protobuf support:

![image](https://user-images.githubusercontent.com/9429203/171437754-97e76763-e6be-41de-8ec4-fd0dc4bdcfc2.png)

For the sake of discoverability of this feature (both here and in Update Schema), would it make sense to include `proto2` and `proto3` in the list of allowed types, and `proto` in the list of allowed languages?

**Comment by abhijitkane** [comment]
@togiles Not in the way you're describing, but in this flow what we'd recommend is creating two versions in the same API. Versions are what consumers of your API can self-select into, so if consumers can choose between using the lower-level gRPC interface or the ones exposed over OpenAPI, the version construct might help. You will need to separate out the collections/tests etc. for the two versions, though.

**Comment by abhijitkane** [comment]
@lennrt Yep - we're on it :). Thanks for the update.

**Comment by jaredtbates** [comment]
It looks like this is deprecated in the Postman v10 APIs- what is the preferred method of doing this now?
