### ISSUE TITLE
White screen with a json

### ISSUE THREAD

**Issue by vlad-gaman** [a85/POSTMan-Chrome-Extension#11002]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The application opens with a json and i cannot do anything

### Steps To Reproduce

1. I am not sure what I did before re-opening the application

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/96066666/173581860-f0e2a576-c8af-4b67-9c3a-ad6e50cbd117.png)

### Operating System

Windows

### Postman Version

9.14

### Postman Platform

Postman App

### Additional Context?

Nothing to add

**Comment by vlad-gaman** [comment]
Also I cannot seem to close the application.

**Comment by kamalaknn** [comment]
Hey @vlad-gaman 

Could you share some more information to help us get to the root cause of the issue? 

**Steps To Capture Netlogs**

1. Use command prompt or Powershell
2. Switch to your application directory `cd %LOCALAPPDATA%\Postman`
3. Launch the app with netlog flag`.\Postman.exe --log-net-log=%APPDATA%\Postman\logs\postman-net.json`
4. Quit the application when you see the error

Please share the netlog and application logs from `%APPDATA%\Postman\logs` with us via email to `help@postman.com`.

**Comment by vlad-gaman** [comment]
Hey @kamalaknn I sent the a zip file with the logs

**Comment by Lincimary** [comment]
Thank you for providing the logs. 
I will go ahead and close this one since we have a open ticket with you.
