### ISSUE TITLE
Developer can not run all requests in a folder but can a collection. Admin role required for run at folder level

### ISSUE THREAD

**Issue by BrianJonesNMI** [a85/POSTMan-Chrome-Extension#11086]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have had to make all my staff Admins because they can not run all requests in a folder but they can a collection.

In any given collection we have folder, the folders are different aspects of the collections purpose. Folder A connects to our external data servcie, Folder B connects to our API and folder C connects to our Web interface.

Depending on what you are working on you may not need to run every request in a collection and since our collection folders can have as many as 100 requests that can take a long time to run 100 requests across all three folders. 

An Admin can right click on a folder and run just a folder but a developer can not. They can only run and entire collection.

### Steps To Reproduce

as a developer
open a collection
navigate to a folder with requests 
right click on the folder note the lack of a Run Folder option

as an admin
open a collection
navigate to a folder with requests 
right click on the folder note the existence of a Run Folder option

### Operating System

Windows

### Postman Version

Desktop Platform Version 9.22.2

### Postman Platform

Postman App

### Additional Context?

If a developer can run a collection why can they not run a single folder? I can not see a security issue here. Please advise.

**Comment by postman-staff** [comment]
Hi @BrianJonesNMI,
Thank you for reaching out.

I understand that this is not the expected behavior as you are able to run a collection but unable to run a folder, Happy to assist!

To help us replicate this behavior, could you please answer the following questions:

1. May I know if it is happening with a specific collection/ all of the collections?
2. May I know your role in the workspace where this collection lies?
3. May I know your role for that collection?

Ref doc for roles and definitions:
https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/

Looking forward to your response.

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @BrianJonesNMI,

Additionally, could you also check if you are able to run the folder from the workbench?
Ref screenshot:
 ![](https://postman.zendesk.com/attachments/token/w4dDBRUDrIKNCY7ohGwiwvMmo/?name=image.png)

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi hello,

Just letting you know I’m still here so feel free to give me a shout if you’re still running into any issues.
via @Lincimary | Postman Support
