### ISSUE TITLE
Postman deletes all collections and environment when disk space is low

### ISSUE THREAD

**Issue by quintafeira** [a85/POSTMan-Chrome-Extension#11101]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Today I opened Postman and for my surprise, all my collections were deleted. I searched the web, found some possible solutions to restore everything, but nothing worked for me. Then I found a backup in ~/.config/Postman/ and restored it. I tried to copy the backup to another folder just to be sure I could restore it again in case Postman deleted my collections again in the future, and the file manager notified me I could not copy it because of low disk space. I freed some space (like 500 MB) and started Postman again. When I opened Postman, it filled the disk again (I just opened it and Postman occupied 500 MB, maybe it's another bug) and stopped sending requests. I closed it and opened again. All my collections were deleted again. I repeated the process one more time just to be sure it was being cause due to low disk space. I think this is not the correct behavior. Postman should not delete collections, even with low disk space. The best thing to do if it can't work with low disk space is just not work at all. 

### Steps To Reproduce

1. Open postman when you have low disk space (500 MB or less).
2. See all your collection were deleted.

### Operating System

Arch Linux

### Postman Version

9.25.0

### Postman Platform

Postman App

**Comment by postman-staff** [comment]
Hey @quintafeira
This is not the expected behaviour.


- May I know if you are using Postman locally, that is, without logging in?
- If you are logged in, could you please navigate to our web version - go.postman.co, to check if your collections are present?

via @VaishnaviChallaPostman | Postman Support

**Comment by quintafeira** [comment]
I'm using Postman locally, without logging in.

**Comment by postman-staff** [comment]
Hey @quintafeira
Apologies for the delay here.
May I request to know if you are still facing this issue on your end?
As far as the application is concerned, I can confirm that it doesn't delete collections due to space limitations.
I will wait to her back from you.

via @VaishnaviChallaPostman | Postman Support
