### ISSUE TITLE
Cannot import FIWARE collection samples

### ISSUE THREAD

**Issue by zeldalegends** [a85/POSTMan-Chrome-Extension#11112]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Cannot import json exported for FIWARE, e.g., this one:
https://github.com/FIWARE/tutorials.PEP-Proxy/blob/NGSI-LD/FIWARE%20PEP%20Proxy.postman_collection.json
or this (more recent) one
https://github.com/FIWARE/tutorials.PEP-Proxy/blob/master/FIWARE%20PEP%20Proxy.postman_collection.json

### Steps To Reproduce

Dowbload the json file previously linked or paste the content as raw data.
"Error while importing : format not recognized"

### Operating System

Windows

### Postman Version

Version 9.25.3-220722-0800

### Postman Platform

Postman Web

### Additional Context?

Chrome 103 / Windows 11

**Comment by shubhbhargav** [comment]
@zeldalegends I was able to successfully import the first link i.e. https://github.com/FIWARE/tutorials.PEP-Proxy/blob/NGSI-LD/FIWARE%20PEP%20Proxy.postman_collection.json, however the second link failed for me as well.

From what I could see, in the second collection JSON, the format of the collection is not recognized due to missing ID fields in certain sections of the JSON such as line number 91 which has a ID field in the first collection JSON.

As a next step, can you please confirm if you can import the collection from the first link i.e. https://github.com/FIWARE/tutorials.PEP-Proxy/blob/NGSI-LD/FIWARE%20PEP%20Proxy.postman_collection.json?

**Comment by zeldalegends** [comment]
Yes, NGSI-LD worked for me, thank you so much, but only the import, but not the run, actually. With Keyrock 8.1.0-distroless it returns 404 Unauthorized. You have to switch back to version 7.9.2 to make the tests work succesfully. I guess it is a problem of the underlying MySQL db, which had breaking changes in version 8, making the Postman collection not runnable with the latest version of the IdM. Another problem is the call GET http://localhost:1027/v2/entities/ which does not work / is not supported by Orion LD, so it should be updated, too, to make it works.

**Comment by shubhbhargav** [comment]
@zeldalegends Regarding the MySQL db references, I am assuming that it is a concern with the locally hosted application / service, not Postman. If yes, let us know if there is anything else we can help out with, else please feel free to close off the ticket. :)

**Comment by zeldalegends** [comment]
Sure, thanks for the great support. Best regards.
