### ISSUE TITLE
When we switch from scratchpad to workspace the collections are not restored

### ISSUE THREAD

**Issue by sseenivasan89** [a85/POSTMan-Chrome-Extension#11178]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

i have not logged in to postman and I don't have any workspace in postman, I have a few collections in the local scratchpad when logged into postman the collections are not restored

### Steps To Reproduce

1. Create a few collections in the local scratchpad
2. Click on move to workspace button
3. Signup to postman
4. Confirm the collections are restored in workspace

### Operating System

Windows

### Postman Version

9.27.1

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @sseenivasan89 

Could you expand on what you mean by 'not restored', please? What were the expectations after you had logged in?

The local Collections _should_ still be on the scratchpad, these don't automatically get transferred to a Workspace. I believe we did have a flow that gave you the ability to do this but I'm unsure if you were presented with that option.

**Comment by sseenivasan89** [comment]
Hi @DannyDainton,

when we signed up to postman, my scratchpad collections will not be moved to my workspace automatically ?

**Comment by DannyDainton** [comment]
Those remain stored locally on your machine and are not pushed to the new account automatically. 

https://learning.postman.com/docs/getting-started/using-scratch-pad/#exporting-data-from-the-scratch-pad

**Comment by sseenivasan89** [comment]
Can't we implement this as feature ?

**Comment by DannyDainton** [comment]
This appears to have regressed as there should have been a modal displayed during the signup flow, asking you if you're like to migrate your Collection to a Workspace or leave them in the Scratchpad. 

The team are aware of this issue and is looking into a fix. I will update the thread when we have more information.

Unfortunately, this isn't a retrospective action so you would still need to export/import those Collections from the Scratchpad to a Workspace. This won't be the case for new users when the fix is in place, as you would be given the option to migrate them.

**Comment by DannyDainton** [comment]
The fix for the scratchpad data migration issue, when signing up for a new account is part of version 9.28.1. 

I'm going to close for now.

**Comment by raphaelpreston** [comment]
Nothing is restored for me either. Quite frustrating to have to go through one by one now that the [export data option has been removed](https://github.com/postmanlabs/postman-app-support/issues/11738).

Edit: I stand corrected. A sign out, restart, sign in allowed the prompt to appear.
