### ISSUE TITLE
Search bar in Environments tab

### ISSUE THREAD

**Issue by AravindShan** [a85/POSTMan-Chrome-Extension#11200]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When we have a hundreds of variables created under an environment it is difficult to look or search for a specific variable

### Describe the solution you'd like

A search bar without case sensitive to return the values that we search for

### Describe alternatives you've considered

Scroll through the variable list to identify if a variable is present

**Comment by OwensCode** [comment]
An alternative would be to allow sorting the list, which would still be much less tedious than scrolling through it

**Comment by Z-Farook** [comment]
If there are hundreds of environment variables in the **`environment TAB`** (thus an environment collection under this tab) then **finding them is greatly painful**, when you quickly want to change the value of a variable X. 

Please, can you give people the possibility to search for the XYZ variable there(when a collection is opened or in the find and replace Tab) and `**go directly to that variable**`? 

For example, I have all the environment variables found here: [Huge number of environment variables](https://community.opengroup.org/osdu/platform/testing/-/blob/master/Postman%20Collection/00_CICD_Setup_Environment/azure.OSDU%20R3%20PROD%20v2.4.postman_environment.json).

You can not imagine how hard it is to find a variable XYZ in the list if/because **` you want to change its value`**. 
Because the only thing that has been provided is that:

1.  you can use the **find and replace** feature BUT
2.  once there, you search for the XYZ and click on open `**then**`
3.  it **opens** the **`**whole collection**`** of the environment variables
4. so it **does not** take you right **to the XYZ variable** `that you wish to change`


I have taken the time to give this extremely valuable feedback because I think it will help all users if you can provide the functionality for:
1.  finding an XYZ variable in the environment collection. 
2. **when a match is found** you click on it then `it must take you to that exact variable's location` and you must be able to change the `initial or current value` of it there.

So something like a code editor's feature that takes you to the line number/exact place where the word is found and you can change it.

We would love to know what are you going to do about this feedback.

Kind regards,
Zahid

**Comment by christianrocchetti** [comment]
I think it is possible to add this feature in the main search bar.

![image](https://user-images.githubusercontent.com/37518765/218337378-e2b0da0e-ccd0-40ca-9eb3-326f3b707b5d.png)

**Comment by vedkribhu** [comment]
@AravindShan @christianrocchetti @Z-Farook 
In our latest release v10.10, we have introduced filtering support in the variables list. Do let us know your feedback. 
![Screenshot 2023-02-15 at 12 29 24 PM](https://user-images.githubusercontent.com/37595282/219371251-9df004e1-fd43-400d-b094-8354cbc774c4.png)

**Comment by AravindShan** [comment]
@vedkribhu Thank you! It works like charm :-)

**Comment by Z-Farook** [comment]
Is this version available[ via chocolaty](https://community.chocolatey.org/packages/postman#versionhistory)?

I see this:
 
**Version:** Postman for Windows` 10.9.4 `
**Last Updated:** Sunday, February 12, 2023

**Comment by Z-Farook** [comment]
@vedkribhu Please can you push the latest version for chocolaty, the latest version there is: **10.9.4**!!!

**Comment by vedkribhu** [comment]
Sure, checking on that. Meanwhile, you can use it on postman-web.

**Comment by Z-Farook** [comment]
@vedkribhu 

Well, I just tested with a manual install. 

Sadly, the problem is not solved yet!!! Sorry to say, It seems a quick and dirty fix!!!

Why? 

Because it **does not filter** the list of variables but very _poorly highlights the match_ and **if you hit** `Enter` it **does not go to the next matching** result either.

The problem is poorly solved as one will still need to scroll with the mouse to find stuff :(

The filter should hide/discard all other variables that do not match the wildcard.
@vedkribhu, I also tried typing some **ABCD** filter that does not exist and it still shows me the whole list of variables!!!

**Comment by Z-Farook** [comment]
> @vedkribhu
> 
> Well, I just tested with a manual install.
> 
> Sadly, the problem is not solved yet!!! Sorry to say, It seems a quick and dirty fix!!!
> 
> Why?
> 
> Because it **does not filter** the list of variables but very _poorly highlights the match_ and **if you hit** `Enter` it **does not go to the next matching** result either.
> 
> The problem is poorly solved as one will still need to scroll with the mouse to find stuff :(
> 
> The filter should hide/discard all other variables that do not match the wildcard.

I hope the developers are not cursing me after reading my feedback, lol.

**Comment by christianrocchetti** [comment]
@vedkribhu 

I have the same problem as @Z-Farook, instead my work colleague who has windows 11 doesn't redescribe this problem

**OS**: is Ubuntu 22.04 LTS and use snap.
**Version**:   v10/stable:       10.10.3 2023-02-16

**Comment by Z-Farook** [comment]
> @vedkribhu
> 
> Well, I just tested with a manual install.
> 
> Sadly, the problem is not solved yet!!! Sorry to say, It seems a quick and dirty fix!!!
> 
> Why?
> 
> Because it **does not filter** the list of variables but very _poorly highlights the match_ and **if you hit** `Enter` it **does not go to the next matching** result either.
> 
> The problem is poorly solved as one will still need to scroll with the mouse to find stuff :(
> 
> The filter should hide/discard all other variables that do not match the wildcard. @vedkribhu, I also tried typing some **ABCD** filter that does not exist and it still shows me the whole list of variables!!!

I hope the developers are not cursing me after reading my feedback, lol.

**Comment by vedkribhu** [comment]
@Z-Farook thanks for the feedback. I agree that there is scope for improvement in the solution. Will work on improving the experience in coming releases. Meanwhile, we have raised PR to chocolatey to upgrade the version, will let you know once merged https://github.com/kendaleiv/chocolatey-postman/pull/38

Also regarding "I also tried typing some ABCD filter that does not exist and it still shows me the whole list of variables!!!" can you share a screen recording?

**Comment by Z-Farook** [comment]
> @Z-Farook thanks for the feedback. I agree that there is scope for improvement in the solution. Will work on improving the experience in coming releases. Meanwhile, we have raised PR to chocolatey to upgrade the version, will let you know once merged [kendaleiv/chocolatey-postman#38](https://github.com/kendaleiv/chocolatey-postman/pull/38)
> 
> Also regarding "I also tried typing some ABCD filter that does not exist and it still shows me the whole list of variables!!!" can you share a screen recording?

I am for some reason not able to upload a screenshot here!
You can try yourself at first try it might be a success, but if you delete and again type a random bla bla it will `not `work!

**Comment by giridharvc7** [comment]
@Z-Farook @christianrocchetti Would it be possible for either of you to get on a call with us, we'd love to understand your usecase a bit more deeper. We understand the is a lot of scope for improvement here, but understanding your workflow will help us understand the problem better 
Feel free to setup a time that's convenient for you [here](https://calendly.com/giridhar-vc-postman/)

**Comment by Z-Farook** [comment]
> @Z-Farook @christianrocchetti Would it be possible for either of you to get on a call with us, we'd love to understand your usecase a bit more deeper. We understand the is a lot of scope for improvement here, but understanding your workflow will help us understand the problem better Feel free to setup a time that's convenient for you [here](https://calendly.com/giridhar-vc-postman/)

@giridharvc7  I am here and we can call right now!

**Comment by Z-Farook** [comment]
Join me here on this open-source meeting platform, Jitsi, [using this link](https://meet.jit.si/Postman-Zahid)
@giridharvc7 please let me know if you can now, otherwise I will have to step out!

**Comment by giridharvc7** [comment]
Can do now. Joining

**Comment by vedkribhu** [comment]
@Z-Farook thanks for quickly jumping on the call. We have identified the root cause for the issue you mentioned around filter not working correctly. It is due to using a custom (non-standard) keyboard layout. We are working on a fix for this, we might raise a hotfix depending on the number of users that are impacted by this.

**Comment by Z-Farook** [comment]
> @Z-Farook thanks for quickly jumping on the call. We have identified the root cause for the issue you mentioned around filter not working correctly. It is due to using a custom (non-standard) keyboard layout. We are working on a fix for this, we might raise a hotfix depending on the number of users that are impacted by this.

I am using English (United State)
US Keyboard

It would be a big disappointment for me if it is not fixed, as I have invested my precious time to give you feedback and mentioned the issue.

**Comment by Z-Farook** [comment]
In the meanwhile, can you tell users what **is** the  `standard keyboard ` for the time being?

**Comment by christianrocchetti** [comment]
> @Z-Farook thanks for quickly jumping on the call. We have identified the root cause for the issue you mentioned around filter not working correctly. It is due to using a custom (non-standard) keyboard layout. We are working on a fix for this, we might raise a hotfix depending on the number of users that are impacted by this.

I'm using  Italian layout.

**Comment by vedkribhu** [comment]
By standard I meant 'English ABC' layout

**Comment by vedkribhu** [comment]
@Z-Farook @christianrocchetti we have identified an issue due to which you might be facing this. Can you verify if the filter is working fine in the builds here https://drive.google.com/drive/folders/1IWvfomtSzWxS6YPycQuzSY2NcgNT7lNr?usp=share_link. These are custom canary builds, we will push the fix as a hotfix once we are sure it solves all the problems.

**Comment by christianrocchetti** [comment]
> @Z-Farook @christianrocchetti we have identified an issue due to which you might be facing this. Can you verify if the filter is working fine in the builds here https://drive.google.com/drive/folders/1IWvfomtSzWxS6YPycQuzSY2NcgNT7lNr?usp=share_link. These are custom canary builds, we will push the fix as a hotfix once we are sure it solves all the problems.

I tried and it has been fixed. @vedkribhu, I wanted to thank you for  the speed of implementing the feature and fixing the bugs.

**Comment by Z-Farook** [comment]
I tested it and it seems to work as expected. 
Please push it to the official website and for **chocolaty too**!! 
Great job @vedkribhu 🥇

**Comment by vedkribhu** [comment]
The fix is out, you should be able to see the fix on the web, and on desktop app after restarting your app(v10.10.x app). 
If you don't see the fix after restarting the app try clicking clear cache and reload. 
![Screenshot 2023-02-17 at 9 25 58 PM](https://user-images.githubusercontent.com/37595282/219702600-01881ea7-4980-4254-ab53-ee539e94e8b8.png)
