### ISSUE TITLE
Export does not work properly

### ISSUE THREAD

**Issue by jekakos** [a85/POSTMan-Chrome-Extension#11225]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the current version ( Version 9.29.6 ) there is incorrectly export:
1)  Content-Type (more details here https://github.com/apideck-libraries/postman-to-k6/issues/80 )
2) Unchecked variables in Body (should be excluded, but present in export) 

### Steps To Reproduce

Try to export this
<img width="761" alt="image" src="https://user-images.githubusercontent.com/80619441/187683608-6e73c235-ddfe-4ce7-9a40-000bea61cbe5.png">

### Operating System

MacOS

### Postman Version

9.29.6

### Postman Platform

Postman App

**Comment by parthverma1** [comment]
Hi @jekakos. I replicated the request that you've mentioned above and exported using the recommended Collection v2.1 format and got the following JSON
```json
{
	"info": {
		"_postman_id": "974b7a3c-bdfd-45cd-baff-b94b9d5e33f2",
		"name": "New Collection",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "19427782"
	},
	"item": [
		{
			"name": "New Request",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "urlencoded",
					"urlencoded": [
						{
							"key": "id",
							"value": "1",
							"type": "text"
						},
						{
							"key": "params",
							"value": "[]",
							"type": "text",
							"disabled": true
						}
					]
				},
				"url": {
					"raw": "{{url}}/api/blabla",
					"host": [
						"{{url}}"
					],
					"path": [
						"api",
						"blabla"
					]
				}
			},
			"response": []
		}
	]
}
```

Which is correct since the Content-Type header is a calculated header and the `params` key is flagged as disabled. The `Content-Type` can be inferred from the `mode` parameter present in the `body` key. 

If I manually add the `Content-Type` header to the request, it gets exported but with a warning flag added to it

```json
{
	"info": {
		"_postman_id": "974b7a3c-bdfd-45cd-baff-b94b9d5e33f2",
		"name": "New Collection",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "19427782"
	},
	"item": [
		{
			"name": "New Request",
			"request": {
				"method": "POST",
				"header": [
					{
						"warning": "This is a duplicate header and will be overridden by the Content-Type header generated by Postman.",
						"key": "Content-Type",
						"value": "application/json",
						"type": "text"
					}
				],
				"body": {
					"mode": "urlencoded",
					"urlencoded": [
						{
							"key": "id",
							"value": "1",
							"type": "text"
						},
						{
							"key": "params",
							"value": "[]",
							"type": "text",
							"disabled": true
						}
					]
				},
				"url": {
					"raw": "{{url}}/api/blabla",
					"host": [
						"{{url}}"
					],
					"path": [
						"api",
						"blabla"
					]
				}
			},
			"response": []
		}
	]
}
```

The Postman client doesn't normally export default headers such as `Content-Type`, `Content-Length` etc unless they are manually added.

The Postman Collection Schemas are publicly available at https://schema.postman.com which you can review.

**Comment by giridharvc7** [comment]
@jekakos let us know if the above comment clarifies the export behavior.
