### ISSUE TITLE
[feature request] Service API Keys 

### ISSUE THREAD

**Issue by clairefro** [a85/POSTMan-Chrome-Extension#11242]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Automating workflows with Postman's API currently requires personal API keys. These are difficult to manage when someone leaves a team or the API Key needs to be changed for security issues. 

### Describe the solution you'd like

Service account API Keys that can be managed by a team, with RBAC

**Comment by chill389cc** [comment]
@davidespihernandez is there still work being done on this feature?

**Comment by davidespihernandez** [comment]
We are not working actively on this initiative at this moment, but it's something we want to tackle soon. @chill389cc Can you please tell me more about your use case?

**Comment by chill389cc** [comment]
@davidespihernandez My organization uses postman collections in CI/CD workflows (GitHub Actions) to verify the functionality of deployments. We've started using newman to run our collections, but we need a Postman API token to do so. We have been moving away from user-based API tokens/keys and Postman is one of the only services we have where we can't get a personless API key. Instead, we'd like to manage the tokens/keys on some higher level so that the key does not depend on one single user's account.

**Comment by davidespihernandez** [comment]
In this case, we recommend creating a new account and treating it as a service account, using API keys belonging to that account.
We don't plan to add different types of API keys soon.
