### ISSUE TITLE
Showes boxes when selecting files

### ISSUE THREAD

**Issue by Raj00377** [a85/POSTMan-Chrome-Extension#11268]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Im using postman app v9.31.5 in Ubuntu 20.04.5 LTS. while selecting files in form data section it shows boxes

### Steps To Reproduce

Select files in form data

### Screenshots or Videos

![Screenshot from 2022-09-14 12-28-09](https://user-images.githubusercontent.com/40709274/190083646-d19d316b-199e-406e-a18c-15ab7aaa8b67.png)

### Operating System

Linux

### Postman Version

9.31.5

### Postman Platform

Postman App

**Comment by jviotti** [comment]
Hi @Raj00377 ,

Thanks for reporting this! Are using Snaps by any chance? A while ago, we dug into this (see https://github.com/postmanlabs/postman-app-support/issues/10449) and identified that this is an upstream issue with Snaps themselves.

While we cannot fix the issue from our side, there are various workarounds discussed in the Ubuntu issue tracker (https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1864365) that seemed to have worked for other people. Hopefully it gets properly fixed by Snaps themselves at some point!

I'll go ahead and close this one, but let us know (preferably in https://github.com/postmanlabs/postman-app-support/issues/10449 so we keep the conversation in a single place) if none of the workarounds helped!

**Comment by Aakeeo** [comment]
Was this ever resolved... It works on the web but not on the postman app

**Comment by gaddarGlassfrog** [comment]
> Was this ever resolved... It works on the web but not on the postman app

Did you fixed this issue

**Comment by gaddarkumar7447** [comment]
> Was this ever resolved... It works on the web but not on the postman app

I have also updated my system from 22.04 to 24.04, and I am also facing this issue with my Postman.
