### ISSUE TITLE
Postman limit

### ISSUE THREAD

**Issue by Sahandi81** [a85/POSTMan-Chrome-Extension#11282]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Why Postman workspace in unavailable for Iranians?

### Steps To Reproduce

1. open workspace with my nurture IP and I get an error (unable to load)
2. change my IP to Europe and everything is done right.

### Operating System

windows

### Postman Version

9.14.0

### Postman Platform

Postman App

**Comment by postman-staff** [comment]
Hi **@****Sahandi81****,**

We have verified with our team and can confirm there are no blockers of any sort from Postman's end for Iran users.

Since this issue is only affecting users in Iran, it is highly possible that traffic is getting dropped within the carrier (ISP) networks for users. I think the next step here is for you to contact the local ISP (Internet Service Provider) so that you can investigate any connectivity issues to the United States via the ISP network.

via @Raj-postman | Postman Support
