### ISSUE TITLE
env variable is not synced when modified

### ISSUE THREAD

**Issue by c98** [a85/POSTMan-Chrome-Extension#11349]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

after i upgrade postman to 10.0.22, the env variable does NOT work in some case.

### Steps To Reproduce

when i modified a variable and saved it, then i send request, the request code does NOT contain my new variable value.

### Screenshots or Videos

https://user-images.githubusercontent.com/6177211/195243041-e002e565-0dfe-4b55-85fa-7f2427e5cfb2.mov

### Operating System

macOS

### Postman Version

10.0.22

### Postman Platform

Postman App

**Comment by c98** [comment]
#11348

**Comment by DannyDainton** [comment]
Hey @c98 

Can you provide a short video of the behaviour that you're seeing please, it's going to be difficult for us to take this forward without seeing what's happening in your Postman instance.

**Comment by c98** [comment]
Thanks for your reply @DannyDainton 
I upload a video for repreduce the case.

after i modified the {{token}} variable and save it, the send request does NOT used the newest value.

**Comment by DannyDainton** [comment]
Thank you for the video.

Looks like it might be related to this https://github.com/postmanlabs/postman-app-support/issues/11348

**Comment by giridharvc7** [comment]
@c98 We've raised a fix for #11348 , can you try restarting the app (which should get you the fix), try again and let us know if it works for you

**Comment by martinstenhoff** [comment]
It's confusing that the Postman UI shows a stale value of an environment variable. 
If there is no change listener so, that everywhere an env variable is referenced, it can show the current value then it would be better to just display the name of the env variable and not the value of it. i.e. "Bearer {{accessToken}}" instead of "Bearer [value of accessToken env variable when request tab was opened]"

See attached. The accessToken variable has value "accessToken 2", but the UI shows "accessToken 1". Note that the correct "accessToken 2" value is however sent in the request.

![PostmanDoesNotRefreshEnvValues](https://user-images.githubusercontent.com/21321853/195587026-e3bfcd19-1b5f-44c8-95c1-cef3915cb321.gif)

**Comment by shubhbhargav** [comment]
@martinstenhoff Thanks for the feedback. It looks like a separate issue. I have filed the same here: https://github.com/postmanlabs/postman-app-support/issues/11360

Closing off this issue for now.

**Comment by c98** [comment]
Thanks, i upgrade to 10.0.27, and it works!
