### ISSUE TITLE
Hash(#) in URL is not getting encoded

### ISSUE THREAD

**Issue by Ludatick** [a85/POSTMan-Chrome-Extension#11357]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When "Encode URL Automatically" is enabled, the call request path is not being encoded for specific characters. The characters not being encoded are treated differently when used as a query parameter value. Attached are two screenshots displaying this behavior. The first screenshot is showing the GET request containing multiple # characters in the path and the console log showing the request made is not encoding this character. The second screenshot is showing when I make a request to a different endpoint where it accepts query parameters, the # character is being encoded in the request showing in the console.

### Steps To Reproduce

1. Open a new request
2. Enable the "Encode URL Automatically" setting
3. Update the uri path to include a # character
4. Submit the request and review the console log

Conflicting behavior replication steps
1. Open a new request
2. Enable the "Encode URL Automatically" setting
3. Add a query parameter with a value that includes the # character
4. Submit the request and review the console log

### Screenshots or Videos

![tempsnip2](https://user-images.githubusercontent.com/96807580/195424301-e3a6c9a5-dee6-467a-a011-88abbc1ba6a4.png)

![tempsnip](https://user-images.githubusercontent.com/96807580/195423964-90f5c9a6-faaa-47b6-a6fd-c2f4851e9390.png)

### Operating System

Windows

### Postman Version

10.0.25

### Postman Platform

Postman App

**Comment by codenirvana** [comment]
@Ludatick This happens because `#`  in a URL string represents a [URI fragment](https://en.wikipedia.org/wiki/URI_fragment).
The "Encode URL automatically" setting encodes reserved characters (as per WHATWG spec) in URL segments, but `#` holds a different meaning.

It's working for the query-params input because the URL string has `%23`.

<img width="592" alt="Screenshot 2022-10-13 at 12 56 48 AM" src="https://user-images.githubusercontent.com/4865836/195430783-f9dd926e-e063-40e6-b47d-89c91a2778ee.png">

As a workaround, I will suggest having this Pre-request script to encode `#`s before sending the request.
```js
pm.request.url.update(pm.request.url.toString().replace(/#/g, '%23'));
```

<img width="819" alt="Screenshot 2022-10-13 at 1 00 39 AM" src="https://user-images.githubusercontent.com/4865836/195431480-cfc8338d-ed4f-4159-9347-f85b130bfda0.png">

**Comment by DannyDainton** [comment]
Hey @Ludatick 

Closing this issue for now as @codenirvana has provided a reason as to why this happens and a workaround.
