### ISSUE TITLE
Collection Runner - A new Run resets previously selected requests

### ISSUE THREAD

**Issue by dunder** [a85/POSTMan-Chrome-Extension#11361]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The selected requests for a test run are reset when you press the New Run button. The previous behaviour was to keep the selections made in the previous run.

### Steps To Reproduce

1. Open a runner tab
2. Uncheck some of the requests
3. Start the runner
4. Press the New Run button
5. All requests are checked again

### Screenshots or Videos

Uncheck some of the requests

![image](https://user-images.githubusercontent.com/3801893/195811837-9adb1943-0405-4b16-970f-131ff89634b1.png)

Press the New Run button

![image](https://user-images.githubusercontent.com/3801893/195811154-b01261c7-ea3e-40dc-ad5b-3bef83f8cee8.png)

### Operating System

Windows

### Postman Version

10.0.27

### Postman Platform

Postman App

**Comment by malvikach** [comment]
Hi @dunder  👋 
This is the expected behavior with the `New Run` 
If you like to run the customized set of requests (skipping or reordering some requests), then use the 'Run Again' button.
Do note that `Run Again`, will pick the settings within the same session for you and we are tracking an [improvement](https://github.com/postmanlabs/postman-app-support/issues/8433) on this where Run Again remembers the settings across sessions too. 

I hope this unblocks you.  I would be happy to understand more if you have any further inputs or feedback. (Closing the ticket, but feel free to reopen it if this does not help)

Cheers!
Malvika
