### ISSUE TITLE
Postman API: Add folder UID to get collection response 

### ISSUE THREAD

**Issue by MitriSan** [a85/POSTMan-Chrome-Extension#11413]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Our team is trying to automate some workflows to keep our postman collections up to date. In this [issue](https://github.com/postmanlabs/postman-app-support/issues/11407) we found out that in order to get a folder, it's better to use folder UUID to get information about a folder within a collection. However, this UUID is not present in collections response, therefore we can't use it for folder operations.
Example response for get collection operation:
```
{
    "collection": {
        "info": {
            "_postman_id": "815889ca-de9b-46d0-adf8-03aefd6f98a7",
            "name": "Test collection",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            "updatedAt": "2022-11-01T10:38:36.000Z"
        },
        "item": [
            {
                "name": "New Folder",
                "item": [],
                "id": "2a4541e1-1cb5-4b62-bc35-1e01e95644eb"
            }
        ]
    }
}
```

### Describe the solution you'd like

It'd be great to include folder uuid in `get collection` response, the same way as you have collection uuid in `get workspace` response. Also, It'd be great to add folder operations to Postman API collection, and use UUID instead of ID in examples.

**Comment by davidespihernandez** [comment]
Hi, @MitriSan! Thanks for taking the time to write this issue!

Regarding terminology, at Postman we manage two different concepts: ID and UID. You can see the difference in the [documentation](https://www.postman.com/postman/workspace/postman-public-workspace/collection/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a?ctx=documentation).

> ID and UID
> All items in Postman, such as collections, workspaces, and APIs, have ID and UIDs:
> 
> An ID is the unique ID assigned to a Postman item. For example, ec29121c-5203-409f-9e84-e83ffc10f226.
> The UID is the full ID of a Postman item. This value is the user ID concatenated with the item's unique ID. For example, in the 12345678-ec29121c-5203-409f-9e84-e83ffc10f226 UID:
> 12345678 is the user's ID.
> ec29121c-5203-409f-9e84-e83ffc10f226 is the item's ID.

So you are asking to add the UID to the collection response for each item, which makes total sense to me. 

However, in my opinion, we should allow access to that folder using the ID if the requesting user has access to it, regardless of using the UID or the ID to retrieve the information (both should be accepted).

We will initially add the UID to the response, as it's not a breaking change and can be useful information, but we will also investigate why this 404 is being returned because the endpoint should work.

**Comment by davidespihernandez** [comment]
Hi, @MitriSan!
The new `uid` field is now returned in the collection detail response. You can find examples in our [documentation](https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-41e7361d-28e9-4a4d-b1d9-e969ded3bb83).
Thank you for your patience.
Regards,
David.

**Comment by olbapd** [comment]
Is there a setting to remove this uid being added everywhere? It is causing breaking changes.
