### ISSUE TITLE
Updating auth property to null on call in collection via API yields "noAuth" instead

### ISSUE THREAD

**Issue by crubach** [a85/POSTMan-Chrome-Extension#11428]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Updating an existing Postman collection via the API.

The root of the collection has OAuth authentication (type: oauth2) set up that works properly. 

On individual request child entries, when setting the auth property to null yields a request for which the auth is set to noauth in the Postman client. Exporting the collection yields "noauth" for the auth method; removing these entries and re-importing the file yields the expected result of all requests inheriting from the parent.

At this point, there does not appear to be a documented way to make child requests in a collection inherit from the parent.

### Steps To Reproduce

1. Create a collection in Postman with Oauth configured for root and at least one child request.
2. Call GET collections/${collectionUid}
3. Replace auth entries on all request with null e.g. using
const processObject = (o) => { for (var k in o) {  if (k === 'request') { if (o[k].auth && ['oauth2', 'noauth'].includes(o[k].auth.type)) { o[k].auth = null; } } ...
4. Update collection with PUT collections/${collectionUid}
5. Open postman client; requests show "No auth" instead of "Inherit auth from parent" as expected

### Operating System

macOs

### Postman Version

v10

### Postman Platform

Postman App

**Comment by shubhbhargav** [comment]
@crubach Can you try removing the `auth` field on the request level and add it to the collection level? That should set it as auth inherited from the parent.

Sample request (with API Key based Auth):
```
POST /collections?workspace=<workspace-id>

{
    "collection": {
        "info": {
            "name": "Test Collection",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "item": [
            {
                "name": "Echo",
                "request": {
                    "method": "GET",
                    "header": [],
                    "url": "https://echo.getpostman.com/headers"
                },
                "response": []
            }
        ],
        "auth": {
            "type": "apikey",
            "apikey": [
                {
                    "key": "value",
                    "value": "{{api_key}}",
                    "type": "string"
                },
                {
                    "key": "key",
                    "value": "X-API-Key",
                    "type": "string"
                }
            ]
        }
    }
}
```

**Comment by crubach** [comment]
The collection _has_ OAuth authentication configured. The issue is that when we add request to that collection using the API, we cannot make those new requests "Inherit from parent" via the API as they always default back to "No Auth" both when "auth": is omitted and when "auth": null is sent when updating the request.

**Comment by shubhbhargav** [comment]
Can you share the request alongside the payload that is being made? That will help debug this further. I tried out the request creation with OAuth as well and it is working for me. ([ref endpoint](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-bc8b292b-ffbb-4c67-a2a1-2fc416e2aef8))

**Comment by davidespihernandez** [comment]
@crubach Since last year, several improvements have been made to the Postman API that can help you with this issue:

- New [Collection Items](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-efeda219-66e1-474c-a83b-253d15723bf7) endpoints. Now, you can CRUD requests, folders, and responses individually, you don't need to do a costly whole PUT collection anymore. We have a specific example to clean the request auth property so it inherits from the parent [here](https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-34ee1e4d-0894-4e1d-8fab-425ee6906f06).
- You can also update the collection authentication property using the collection [PATCH](https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-6e221172-53cd-47bf-b0cc-aa267f4e3004) endpoint.

I'm closing this issue, please let me know if you continue having problems.
