### ISSUE TITLE
Automation - Collection Run Flow Break | Stop When Response Time Longer Than 5 Seconds

### ISSUE THREAD

**Issue by ShadowLeiPolestar** [a85/POSTMan-Chrome-Extension#11437]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

hi Team,
I tried to use "Run Collection" function for an automation test - test a API flow.
During the test everything goes fine but just when on a special test case ("checkout" in my collection) which response time is more than 5 seconds, then the subsequent flow won't run.
> Tried on web it's the same.
> I doubt it's because longer time on this request.

Check the screenshot here please:
You can see it only run the first 5 API request, and break | stop at the 6th. one.
And don't run the rest.
If I remove the 5th. "checkout" data flow (which would run longer than 5 seconds) then everything looks fine, the test won't be stopped.
> Note the test cases in the 5th. one also looks good, so no ideas why it won't continue on the 6th. one, just doubt the response time is too long.

Could you help to take a look please?

Version Info.:
Postman for Mac
Version 10.2.0
UI Version 10.2.0-ui-221107-1307
Desktop Platform Version 10.1.2
Architecture x64
OS Platform OS X 22.1.0

Thanks.
-Shadow

### Steps To Reproduce

1. Create a collection.
2. Create 3 folders w/ several API inside, w/ a few pre-scripts | test-scripts there.
3. In the 2nd. folder - cause a delay (more than 5 seconds).
4. Run the collection.

I can't send a full json data to repro. if necessary.

### Screenshots or Videos

1. Run the full flow:
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/57431855/201010975-d3115a2a-32bb-479d-a5da-f63854cbb6bf.png">

2. Result shows it stop after the 5th. one:
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/57431855/201011350-5712a802-3136-4197-9b6b-1568a37cd7e0.png">

3.  Try to remove the 5th. one & re-run:
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/57431855/201011435-203b8741-cc7c-407e-a07f-2675b56ceb37.png">

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/57431855/201011523-528800e5-1e7b-44ef-a6ad-f146563239d4.png">

 Example of the 5th. (Checkout Request-Response):
<img width="1776" alt="image" src="https://user-images.githubusercontent.com/57431855/201013354-01ae7eda-c6f6-4f9b-b900-6d2e3d433e32.png">

### Operating System

macOS

### Postman Version

10.2.0

### Postman Platform

Both

**Comment by malvikach** [comment]
@ShadowLeiPolestar We are looking into this, thanks for providing the detailed information. 
Just a quick check- Was this testing working on an earlier Postman version and stopped working for you recently? Let us know if that's the case.  

Also just a quick check, could you verify what timeout settings you are using. You can check this here:  _settings_-> _Set Request timeout_ . If this is set to 5 seconds (5000ms) then you might want to increase it or set it to 0 if you never want your requests to error because of timeouts.

<img width="720" alt="Screenshot 2022-11-21 at 6 39 02 PM" src="https://user-images.githubusercontent.com/89449769/203063628-42b73297-9891-422b-b68f-b947f7641070.png">

**Comment by ShadowLeiPolestar** [comment]
hi @malvikach 
Thanks & double checked the settings, it as "0" by default for the timeout field so I guess it's not the case.
Besides, maybe it's not caused by executing too long, I just found another request execute 7s which looks still good, just for this request it somehow would break | stop the next even on 200 status.

_Was this testing working on an earlier Postman version and stopped working for you recently_
> No, this is my first time try to use the automation of Postman, previously I used single request instead of the automation test flow.

It's very strange, I don't know why it broke every time at the "checkout "step...

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/57431855/203278247-11870b1c-77e2-465a-a089-629d778a0178.png">

**Comment by malvikach** [comment]
@ShadowLeiPolestar I have a feeling that this might not have something to do with the response time. 

I tried to reproduce the issue at my side and I observe the following:
1. Following shows the actual requests that I was trying to run: 
<img width="887" alt="Screenshot 2022-11-24 at 8 33 03 PM" src="https://user-images.githubusercontent.com/89449769/203815406-a4438269-d9ee-4e42-b70b-5eeb5515d269.png">

2. The Patch request had an error due to which the remaining requests didn't get executed (notice the error badge on the run):

<img width="1050" alt="Screenshot 2022-11-24 at 8 31 44 PM" src="https://user-images.githubusercontent.com/89449769/203815490-5431577c-37b5-41e9-8bbb-2e3c580959f1.png">

When you observe closely, you will see that for the Patch requests the tests didn't run as well. 

I see that in the screenshots that you have shared, the tests of the checkout request have been executed successfully. This means there was no error that Postman saw while hitting the request or after it. Your console logs also don't indicate any error to me. I also don't see any timeout errors happening which is usually indicated in the logs if that had been the case. 

I believe there might be something else going on with this. Is there any logic being executed in the test scripts after the tests have run for the 'Checkout' request that is making the collection runner skip the remaining requests? (if you are using a pm.setNextRequest(null) this might happen) 

Could you share the collection JSON with us so we can try and reproduce the problem? You can send it to us [here](https://support.postman.com/hc/en-us/requests/new/). 
You can also try discussing this with the other members of Postman community by starting a discussion thread [here](https://community.postman.com/).

**Comment by ShadowLeiPolestar** [comment]
Thanks a lot @malvikach 
Just submit the cases via the link provided as I tried several times & checked the scripts you mentioned, still can't find where's problem.

-Shadow

**Comment by loutsiros** [comment]
Hi @ShadowLeiPolestar  Thank you for submitting your cases via the recommended link.  Upon review, I can confirm that you were using “pm.setNextRequest(null)” logic in your pre-request test script for the ‘Checkout’ request that was making the collection runner skip the remaining requests. (similar to the recommendations earlier outlined by @malvikach) 

When I proceeded to comment out this logic from your script, and then save the changes, I was then able to successfully to run all of your requests through the Collection Runner without any break | stop.  I hope this helps in the meantime.

![collection run](https://user-images.githubusercontent.com/107296759/205881128-d942208e-200e-4c4d-b8e4-9efc6167f479.png)

via @loutsiros | Postman Support

**Comment by ShadowLeiPolestar** [comment]
hi @loutsiros  @malvikach 
Sorry total my fault that I'm checking on the wrong section & ignore the the pre section.
Apologize for my carelessness.

Thanks for your patient consult, have a nice day~
-Shadow
