### ISSUE TITLE
Not every request header is captured on postman interceptor debug session

### ISSUE THREAD

**Issue by hanyrenando** [a85/POSTMan-Chrome-Extension#11448]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I try capture request and cookies from a sites using interceptor plugin on chrome

after succesfully captured and saved into collection,
and then comparing request on chrome inspect> network tab header versus captured request header there is missing header 
that exist on the browser but not on postman

notably "Origin"

is it an expected behaviour?

### Steps To Reproduce

1) Capture via interceptor then compare to chrome network tab
<img width="702" alt="image" src="https://user-images.githubusercontent.com/11401124/202133506-ebf5a17b-5f44-4f24-887f-f7f5fdaaf747.png">

2)
<img width="846" alt="image" src="https://user-images.githubusercontent.com/11401124/202133617-1397b569-2627-427e-b955-cdaeff847ebd.png">

### Operating System

macOs

### Postman Version

Postman v10.2.2

### Postman Platform

Postman App

**Comment by postman-staff** [comment]
Hi **@****hanyrenando****-** Thank you for reporting this.

We will have this reviewed and keep you posted on the same.

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@hanyrenando We have reviewed the issue and have concluded that the headers which are missing are blocked by the Chrome APIs (Which are used by the interceptor extension to intercept the requests) due to performance concerns. Hence we won’t be making any further changes here and this is the expected behaviour for now. Thanks!

via @Raj-postman | Postman Support
