### ISSUE TITLE
PUT on Postman collection point works as DELETE -> CREATE rather than as an UPDATE

### ISSUE THREAD

**Issue by khazamov** [a85/POSTMan-Chrome-Extension#11461]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

HTTP RFC specifies PUT operation as an update operation. In reality, Postman's API does not adhere to this principle. You can verify this by following the steps below.

### Steps To Reproduce

1. Create a collection. 
2. Add a sample pre-request script to the collection.
3. Perform PUT operation on said collection
4. Collection is updated, but the pre-request script is gone

### Operating System

mac

### Postman Version

10.3

### Postman Platform

Postman App

### Additional Context?

n/a

**Comment by bpedro** [comment]
Hi, @khazamov, thanks for creating this issue.

Can you please share (as much as possible avoiding any private data) the payload that you are sending on the `PUT` operation?

**Comment by davidespihernandez** [comment]
Hi, @khazamov. Thanks for your question.

The PUT operation in REST is an update operation, but it updates the whole resource, replacing the existing resource with the new one. This is how PUT requests work usually in REST APIs. So if you modify something in the collection, and then you send a PUT request, your changes made in the UI will be lost, because the whole resource is replaced. This is not an error, is how it works, and it's explained in the request documentation [here](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-bc8b292b-ffbb-4c67-a2a1-2fc416e2aef8?ctx=documentation).

In order to modify a resource partially, REST APIs usually expose a PATCH endpoint, that allows you to update specific parts of the resource. We currently don't have a PATCH endpoint for collections in the Postman API v1, but we expose an endpoint called [Collection individual items](https://www.postman.com/postman/workspace/postman-public-workspace/collection/16473433-f2f0cb8f-609d-443f-913c-9831187c326e), that you can use to update requests, responses, and folders in a specific collection.

Please try to use that endpoint, and let me know if it solves your problem or not. In the meantime I'll close this ticket, feel free to reopen it if you need something else.

Thanks!
