### ISSUE TITLE
"There was an error with our servers" when creating Flows Release

### ISSUE THREAD

**Issue by jessemenning** [a85/POSTMan-Chrome-Extension#11518]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Trying to create release of a Flow.  Click on Create Release.  Immediately an error box emerges from lower right of screen stating "There was an error in our servers while creating the release.  Try again in some time."   Have tried repeatedly over past 3 days to create release, always get same error message

### Steps To Reproduce

1. Open a flow
2. Click on Release Version
3. First time attempting will get screen with five failed attempts.
![2022-12-06 11_37_07-Window](https://user-images.githubusercontent.com/62108913/205970042-b5c4836f-5b9c-41f1-a34c-e92b757534e6.png)
5. Additional times, will get flag at bottom of window
![2022-12-06 11_32_38-Window](https://user-images.githubusercontent.com/62108913/205970044-1d8ed866-eb4f-4b31-b888-877c8b906845.png)

### Operating System

Windows

### Postman Version

10.5.8

### Postman Platform

Postman App

**Comment by saswatds** [comment]
Hey @jessemenning, thanks for reporting this issue. Could you please update your Postman Version to `v10.6.x` or higher. We had got a lot of early feedback around this feature and made the implementation much simpler in the new version.

Thanks.

**Comment by jessemenning** [comment]
@saswatds , I tried to update the Desktop app, but it's telling me v10.5.8 is the latest version, is there something additional I need to do?
![image](https://user-images.githubusercontent.com/62108913/206195966-a54a75f8-ac27-4093-90f9-2684bf750b03.png)

**Comment by saswatds** [comment]
@jessemenning, Oh ohk. Let me check with our release team, will let you know.

**Comment by viko42** [comment]
Same problem here.

Using 10.5.8 on mac OS
Also tried on the web version
Also tried on the Postman Canary but seems outdated for Flows

When we try to request the release, I can see the success response via sockets.
The link *.flow.pstmn.io is not working
<img width="630" alt="Screenshot 2022-12-14 at 15 05 02" src="https://user-images.githubusercontent.com/18552774/207632051-09ccca5c-92f3-4edd-8a20-5c4ee6ceaefd.png">

**Comment by jon-flowers** [comment]
Note for those who are having issues with the "Check for Updates" button, I talked to Postman Support on that and the issue is that they are still staging the rollout of the newest version (which is 10.6).  The app will *eventually* allow you to correctly update to that version, but for now I had to manually download the newest version from the websites and install it myself.

This did significantly change the "Release" feature (which I was having the same "server error" problems with).  It is now replaced with a "Deploy" function which works in a significantly different way (it's closer tied to the Cloud Flowers / webhooks function than release/version control).  It still had some minor intermittent issues for me but generally the deploy did seem to work most of the time

![Screen Shot 2022-12-15 at 10 53 42 AM](https://user-images.githubusercontent.com/24556426/207920695-ad2da15a-d3ff-4f96-9c3a-0ee879e65a68.png)

**Comment by viko42** [comment]
Thank you [jon-flowers](https://github.com/jon-flowers)
I upgraded to 10.6.x and it's working perfectly

**Comment by DannyDainton** [comment]
Hey @jessemenning 

Is this still an issue for you in the latest version?

**Comment by jessemenning** [comment]
@DannyDainton , thank you for following up.   It does work with the new Deploy button!

**Comment by jessemenning** [comment]
Closing
