### ISSUE TITLE
Can't import RAML 0.8 File 

### ISSUE THREAD

**Issue by redhell** [a85/POSTMan-Chrome-Extension#11604]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I can't import an RAML 0.8 file to postman

### Steps To Reproduce

1. Open import
2. Select this file: https://support.smartbear.com/zephyr-scale-server/api-docs/v1/kanoah/api.raml
3. Click import

### Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/391080/211315317-c925b978-21e4-4ead-92cd-d4c09fd5ce1d.png)

### Operating System

Windows

### Postman Version

10.7.

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by VShingala** [comment]
@redhell Thanks for reporting the issue! We're able to reproduce the issue and will be fixing this with the upcoming release next month. We'll add update here once fix is done and available.

**Comment by VShingala** [comment]
@redhell This issue should be fixed with upcoming release of postman coming next month.

However there's also an issue in schema that you've reported where there is invalid type = `json` present in RAML schema. You can remove this type = `json` and use `string` or something else and it should import fine once next app version is available.

**Comment by VShingala** [comment]
@redhell This issue is now fixed with latest postman app v10.13. With the suggested change in above comment (at line no. 1210 and 1251) in the mentioned file, it's importing as expected now.
