### ISSUE TITLE
405 method not allowed

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#11613]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello, I create my very first collection based on Swagger PetStore documentation. And I have proplem with methods POST DELETE and PUT. When I send as reqest  correct body with JSON format (raw), with headers CONTENT_TYPE application/JSON in response i have status code :405 method not allowed. and in Content-type application/xml. Please help me :) It's my first collection and I really don't have idea what's going on....
In Swagger documentation this reqest work correctly.
![mistake](https://user-images.githubusercontent.com/114069648/211932321-3dc585bc-1c44-42eb-a681-343f820f7a72.png)
![mistake2](https://user-images.githubusercontent.com/114069648/211932332-197f69a2-0792-48aa-adc3-7c106e2ffc5c.png)

### Steps To Reproduce

1. Used Swagger Petstore documentation and create any  reqest with method POST where needs body in aw format with JSON.

### Screenshots or Videos

![mistake](https://user-images.githubusercontent.com/114069648/211932532-ffc2a1a0-b646-4830-9f11-4eca284494fa.png)
![mistake2](https://user-images.githubusercontent.com/114069648/211932547-7a071797-8c5e-46da-a051-4fcc701bb208.png)

### Operating System

Postman for Windows 

### Postman Version

 Version 10.7.1  UI Version 10.7.1-ui-230107-1501  Desktop Platform Version 10.7.0  Architecture x64  OS Platform win32 10.0.19045

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by postman-staff** [comment]
Hello **kulak-daria****,**

The “405 Method Not Allowed” error occurs when the server is configured in a way that does not allow you to perform a specific action for a particular endpoint (URL). It's an HTTP response status code that indicates that the request method is known by the server but is not supported by the target resource (your request URL).

There are multiple causes for this error, but most commonly, this is caused by the server (endpoint URL) configuration.


1. Firstly, You want to confirm which methods are supported for each endpoint and ensure that the POST method is configured. Ensure that your **baseURL** variable associated with your POST method is point to  https://petstore3.swagger.io/api/v3
      (as highlighted in my screenshot below, as I was unable to reproduce this issue)

  2.  Secondly, you want to confirm the then request URL is written correctly for the POST request (confirm it has no trailing spaces for example).

  3.  Lastly, test if your POST request succeeds outside Postman; Send a request using cURL in your terminal. To do this, copy the cURL code generated by your request, paste it into your terminal, and send the request.

I have also referenced a discussion about this response in our Community: https://community.postman.com/t/405-method-not-allowed/16743/3 which has some additional troubleshooting steps you may try.


 ![](https://postman.zendesk.com/attachments/token/N1Ni93gTyzgVMpAYKo6qAjMaz/?name=image.png)

I hope that this information is helpful, and I have included an export of my working collection based on Swagger PetStore documentation - should you wish to test the POST method to "Add a new pet to the store"

via @loutsiros | Postman Support

**Comment by loutsiros** [comment]
[Swagger Petstore - OpenAPI 3.0.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/10396897/Swagger.Petstore.-.OpenAPI.3.0.postman_collection.json.zip)

**Comment by ghost** [comment]
Thank You! I changed base URL in my POST METHOD request and it WORKS! :)

**Comment by Rahulrokkz666** [comment]
You can also check out this comprehensive guide on "[How to Fix the “405 Method not Allowed” Error. (8 methods)](https://www.wpoven.com/blog/405-method-not-allowed/)"  For complete step by step method to fix this.
