### ISSUE TITLE
Notification come back after dismiss it

### ISSUE THREAD

**Issue by jgauthi** [a85/POSTMan-Chrome-Extension#11645]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman does not dismiss definitively the “Looks like your team is full” notification at the top of the window. Can you fix it ?

### Steps To Reproduce

Open postman
Add 2 accounts to a team
Close Postman
Open postman
Dismiss “Looks like your team is full” notification
Close Postman
Re-open postman
“Looks like your team is full” notification is come back
/cry

### Operating System

Windows and Linux (ubuntu)

### Postman Version

10

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by postman-staff** [comment]
Hi **@**jgauthi
Thank you for reaching out.

I understand that you are seeing the "Looks like your team is full"  message while you navigate to your workspace and would like to get rid of it, Right?

Actually, this message appears as if you are part of a **free** team that has more than three members(pending invites).

In order to work collaboratively on our free plan without any interruption, you would have to reduce down your team size to three (3) users. Check if you have any Fourth invite to cancel it.

You can refer to the below links to know more details:
https://support.postman.com/hc/en-us/articles/4415898005783-Why-do-I-see-the-message-your-trial-ends-in-days

https://learning.postman.com/docs/administration/managing-your-team/managing-your-team/#removing-team-members

Feel free to let us know if there is anything else that we can help you with.

via @Lincimary | Postman Support

**Comment by jgauthi** [comment]
Hello,
Thank you for your reply.

However, I have no new member [invitations pending](https://lunar-eclipse-420409.postman.co/settings/team/members), my team is made up of 3 people, no more.

> Team members 3/3
> Support users 0/2

The notification returns at each launch, it is indeed a bug.

**Comment by postman-staff** [comment]
Hi @jgauthi,
Thank you for writing back!

Sorry that you are still facing the issue.

To investigate further, Could you please submit a ticket(https://support.postman.com/hc/en-us/requests/new/) with us so that we will be able to check with the team details?

via @Lincimary | Postman Support
