### ISSUE TITLE
Collection is not sync in the new version of postman

### ISSUE THREAD

**Issue by cpanato** [a85/POSTMan-Chrome-Extension#1169]
I have some collections and I can see my collections in the web interface, but when I loggin in the new postman (3.0.0.31) is not getting in sync and shows nothing.

**Comment by sobtiankit** [comment]
The collections in the web interface are the ones you have explicitly shared by uploading to getpostman.com in the past. In the near future, we will add the ability to show your synced collections also on the web interface. 

Can you describe what you mean by not getting in sync? You can email us at help@getpostman.com with your userid/email and we'll help you out.

**Comment by sobtiankit** [comment]
I just realized, you're also on the team sync beta. Since it's a beta, it has its own separate database and app (for now). You'll have to manually export your data from your 2.1.6 app and import it into the 3.0.0.31 app. 

You can do that by Settings > Data > Export Data > Download in 2.1.6 and Settings > Data > Import Data in 3.0.0.31 and then your data will be available on the beta app and for sharing with the team.

Note, this does not mean that your main app and beta app will be in sync. But once we're out of beta, we will safely migrate your data back to the main app.

**Comment by cpanato** [comment]
ok thanks!

**Comment by anreddy018** [comment]
testing from Rest service from Postman app getting Error : Socket not connected. any help much appreciated.
