### ISSUE TITLE
Disable workspace overview on app launch/startup

### ISSUE THREAD

**Issue by l3ender** [a85/POSTMan-Chrome-Extension#11721]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Postman shows the workspace overview page on startup/launch if Postman was previously closed with no open tabs.

### Describe the solution you'd like

If Postman is closed with no open tabs, it should open in the same state.

### Describe alternatives you've considered

I've looked through app settings, but don't see any such feature/toggle.

### Additional context

Postman for Mac
Version 10.9.4
UI Version 10.9.4-ui-230208-0923
Desktop Platform Version 10.9.4
Architecture arm64
OS Platform OS X 22.2.0

**Comment by akshay-kulkarni-03** [comment]
@l3ender could you please elaborate your use-case a little bit?

**Comment by pgregorio-signalytic** [comment]
I would like to have this option as well but not necessarily dependent on whether I closed the app without any tabs open. With VS Code for example, I always have the welcome screen disabled because it's another tab that I have to close every time I open the app. These tabs are not important to me so I have no use for them such as the workspace overview for Postman. I'd much rather have an empty window and start there. An option to disable this tab from opening when you launch the app will save me from closing it every single time.

**Comment by l3ender** [comment]
@akshay-kulkarni-03 - my use case is the same as what @pgregorio-signalytic mentions: I don't have any use or interest in any workspace overview tabs. That they open automatically in some scenarios causes them to need to be manually closed each time.

I have observed the workspace overview tab opening automatically if Postman was previously closed with no open tabs. The VS Code example @pgregorio-signalytic gave is a good one: being able to disable the screens would be a good approach here too.

Thanks!

**Comment by akshay-kulkarni-03** [comment]
@pgregorio-signalytic , @l3ender thanks for providing the details. Workspace enables you to get your work done faster and overview helps you to navigate to your required collections with ease as well with our recent pin collections functionality. Let us know if there are any additional use-cases which is causing overview to be a trouble for you. Would be more than happy to look into it in detail.

**Comment by pgregorio-signalytic** [comment]
> @pgregorio-signalytic , @l3ender thanks for providing the details. Workspace enables you to get your work done faster and overview helps you to navigate to your required collections with ease as well with our recent pin collections functionality. Let us know if there are any additional use-cases which is causing overview to be a trouble for you. Would be more than happy to look into it in detail.

Not everyone works the same way - if you make this an option (like others, just show a checkbox: "Do not show overview page on startup") is enough and would cater to whatever your user's preferences are. I know some people who would use the overview page and I also know people who don't - and I'm one of them. I prefer navigating through the sidebar, and if available like in the case of VS Code, a command palette since navigation through keyboard is very easy. I have used the overview pages on these dev apps zero percent of the time. I think making this a user preference that they can set for themselves is the way to go.
