### ISSUE TITLE
400 Bad request There was an error parsing the body

### ISSUE THREAD

**Issue by adpablos** [a85/POSTMan-Chrome-Extension#11739]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

A Curl 

```
curl --location 'http://localhost:8000/upload-file' \
--form 'file=@"/Users/xxxxx/Downloads/yyyy.mp3"' \
--form 'name="John"' \
--form 'description="Description"'
```

Which is the code Postman generates in its Code snippet section works perfectly when it is executed via terminal, but via Postman it retrieves a 400 Bad Request with a response body 
```
{
    "detail": "There was an error parsing the body"
}
```

<img width="849" alt="CleanShot 2023-02-18 at 23 55 23@2x" src="https://user-images.githubusercontent.com/9111938/219923074-890d5b17-6067-4162-9fe9-6be243eb8edf.png">

<img width="891" alt="CleanShot 2023-02-18 at 23 55 49@2x" src="https://user-images.githubusercontent.com/9111938/219923081-ac7bb8cf-3717-4580-a529-7fe2d970aac9.png">

Thanks in advance.

### Steps To Reproduce

1. Import >> Raw Text
2. Include the curl and save the request
3. select a file for the File key in the Body (form-data )
4. send

### Operating System

macOS

### Postman Version

10.10.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by xk0der** [comment]
Hey @adpablos make sure the file that you are sending is available in [Postman's working directory](https://learning.postman.com/docs/getting-started/settings/#working-directory) so that it can ready the file.

I'm guessing, in your case, the file is located outside the "Working Directory" and hence it is not being picked and sent over to the server, so the server is responding with the `error parsing` message.

Make sure you re-check the Working-Directory setting, and also make sure that the file you are sending resides in the working directory.

**Comment by adpablos** [comment]
Ok! That was it, yeah! Thanks so much!!
