### ISSUE TITLE
Using the collection JSON via collection access key isn't working

### ISSUE THREAD

**Issue by mmalcorn** [a85/POSTMan-Chrome-Extension#11749]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

newman run https://api.postman.com/collections/collectionID?access_key=https://api.postman.com/collections/collectionId?access_key=PMAT-xxxxx...

returns

`zsh: no matches found: https://api.postman.com/collections/collectionID?access_key=https://api.postman.com/collections/collectionI?access_key=PMAT-xxxxx...`

I removed the actual collectionID and access_key above

### Steps To Reproduce

1. Click "Share" in the collection and "Via API" tab
2. Click "Generate a new collection API key"
3. Copy the URL 
4. Confirm that the new key matches the collection API key in "Manage keys" -> /settings/me/api-keys
5. Confirm that the collection ID matches the one provided in the info section for the collection

### Operating System

Mac OSX

### Postman Version

 10.10.6

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

I followed the blog below as a guide. I noticed that the URL is slightly different in the blog post and just in case that was the issue I modified the URL to match what is in it, but no dice

https://blog.postman.com/newman-run-and-test-your-collections-from-the-command-line/

**Comment by DannyDainton** [comment]
Hey @mmalcorn 

The link to the Collection that you have doesn't look quite right to me.

It should just be something like this:
```
https://api.postman.com/collections/<collection_uuid>?access_key=PMAT-XXXX
```

**Comment by sony-mathew** [comment]
Hey @mmalcorn , 

The blog post you referenced is outdated. We've since improved our systems and documentation. For the latest information on features and commands, please refer to our [Learning Center](https://learning.postman.com/). Specifically, you can find information on running collections with Newman here: [Run Newman and use the Postman API](https://learning.postman.com/docs/collections/using-newman-cli/continuous-integration/#run-newman-and-use-the-postman-api).

We hope this resolves your issue. If you have any further concerns or questions, please feel free to reopen this discussion. We're here to help and support you.
