### ISSUE TITLE
Support For Monorepos

### ISSUE THREAD

**Issue by jjkirby** [a85/POSTMan-Chrome-Extension#11817]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Postman has the constraint of supporting only one API/repo.  This is a problem in doing a Github sync with a repo containing more than one OpenAPI spec file.
This is also a problem in creating a collection for publishing where the API has multiple versions and namespace APIs which are represented as collection folders.  The problem is when you copy an API to a collection and then move the API to a folder (e.g, for a version or namespace) it substitutes a {{baseUrl}} for the server path.  Since the collection is a combination of different versions and namespaces it is useless.

### Describe the solution you'd like

1. Support for monorepos to allow in a Postman workspace to sync multiple APIs from the same repo.
2. Support publishing collections that have a hierarchy of different folders (e.g., version/namespace/openapi.yml) to allow the correct server URL in the API documentation

### Describe alternatives you've considered

A workaround we thought of is to create a separate GitHub Repo for Postman publishing where we merge all of our individual versioned namespace APIs into one API.  The servers' URLs would just be the host names.  The method paths would include the version/namespace and then the BaseUrl is the hostname

### Additional context

We have an AWS API Gateway deployment where a custom domain has multiple APIs which use the mapping path of version/namespace to allow us to deploy many APIs to a custom domain and the same APIs with different versions.  To allow this to work in OpenAPI spec v3.x  we define our servers in the spec as:

https://hostname/version/namespace

Then the method path in the spec becomes relative to those servers' URLs.   We would like Postman to support this concept.

**Comment by shashankawasthi88** [comment]
@jjkirby thanks for raising the issue. I am the product manager looking into this domain. The first issue i.e. Postman not supporting monorepo is being already addressed in the upcoming release. With the next upgrade (scheduled this week itself), you would be able to connect multiple APIs to the same repo.
For point 2, can you expand a bit more? How are your APIs structured, how are corresponding schema and collections structured? If possible we can get on a short call to understand this better and provide a solution. You can schedule a call with me using [this](https://calendly.com/shashank-awasthi/v10-feedback) link.

**Comment by tanepiper** [comment]
Just found this comment through Google Search because I have the same question.

@shashankawasthi88 This suggestion doesn't really work for monorepos either.  In our case, we are setting up a single repo for multiple internal service apps that have some shared dependencies and domains.

Because of the way Postman works, we've tried to set up a single location for specs and for collections and have one per app inside the repo, but the problem seems to be the "root" spec file - no matter how many files you have in the repo, this is the only one that displays in the editor. 

With this we'll currently have to go back to moving the openapi files back to per project (so no shared components) and setting up multiple connections to our repo.

**Comment by shashankawasthi88** [comment]
@tanepiper I was not able to understand your repository structure very clearly. Can we connect over a short call? It will help me understand the structure and see why only root file is being displayed. You can setup a call using [this](https://calendly.com/shashank-awasthi/v10-feedback?month=2023-04) link or you could reach out to me on shashank.awasthi@postman.com

**Comment by sourceful-karlson** [comment]
This is a very important feature for us, is there a ETA?

**Comment by sourceful-karlson** [comment]
This is something Insomnia is looking into as well

https://github.com/Kong/insomnia/issues/4789

**Comment by jatin3893** [comment]
@sourceful-karlson This is now supported since the September release.
You can now connect multiple Postman APIs with a single repository. And we now allow you to specify the root Schema file instead of the folder (dependent files within the repo will be fetched irrespective of their location in the repository) 

So you can have multiple schema files at the root of your repository each connected to a different API in postman.
You can refer to this for example: https://postman.slack.com/archives/C03NA40QB26/p1665496959499949
