### ISSUE TITLE
Runner run limit completely incorrect

### ISSUE THREAD

**Issue by cjmay86** [a85/POSTMan-Chrome-Extension#11823]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When going to use the postman runner then it claims **61/25 runs (244%) used**. Which is obviously incorrect, plus last time I used the Runner would have been around December. Confirmed by checking in the history which only shows single API calls

### Steps To Reproduce

1. Open Runner
2. Drag collection to centre pane
3. Error appears

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/88488733/225378358-49e081c0-f664-4c8b-9f9b-04d3695b84c8.png)

### Operating System

Windows

### Postman Version

 v10.11.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by malvikach** [comment]
hi @cjmay86 the usage for runner is being calculated at a team level so likely the 61 runs you see is because some of your team members might have utilized the runs. 

The usage is also captured in a monthly cycle, this means that your usage counter will go back to 0 after the monthly cycle resets. You can visit the 'Resource Usage' page under the team dropdown to know more about your current usage and monthly resets.
<img width="1432" alt="Screenshot 2023-03-16 at 11 42 17 AM" src="https://user-images.githubusercontent.com/89449769/225530803-43c83f1c-85db-43c6-a8e9-54c591428268.png">

You can also read more about Postman Runner limits on our [learning center.](https://learning.postman.com/docs/administration/resource-usage/#collection-runs-usage) 

Postman offers higher limits on its Professional plan, which might be better suited for teams that are looking for using Runner for testing their endpoints and/or workflows. 

 If you have any further questions or would like to discuss this further, please feel free to write to us [here](https://support.postman.com/hc/en-us/requests/new). 
 
 Thanks
 Malvika

**Comment by andrew-jones** [comment]
You only get 25 local runners across your whole team?  For a runner i run on my local machine.

**Comment by Seika85** [comment]
@andrew-jones Yep. Also your monthly limit does not reset at start of each month, but on your next "billing period", which you have even on "Free" plan.
You need to look at your 'Resource Usage', which you can find clicking the "Upgrade" dropdown (or your Team-Name). There you find a little text (you need to look really hard), which states "Monthly limit resets on [date]".

I also use Postman to make some API-Calls to automatically retrieve and calculate needed KPIs using REST-APIs for different tools. We recently moved from self-hosted server to cloud, so I needed to update all my scripts. The cloud used a newer version of the REST-API with some breaking changes, I needed to adapt my scripts to. Of course I use variables from previous requests stored as environment variables, which in turn are used for the next requests in the same Run. Depending on the values I need to use `setNextRequest()` to call the correct next request.
Therefor I needed to re-run the Run several times, to adjust my scripts step by step. Suddenly I reached the limit. I cannot further correct my script until next month. Great, isn't it?

I won't pay $29-39 per month, to be able to start more than just 25 Runs a month. I would at least need the Professional plan, as the Basic plan still has this exact same Run limit.
I just want to run requests and work with their responses, nothing more.
If they cannot make a tier/plan for just that, then I don't need to use Postman. Time to look for alternatives.

**Comment by andrew-jones** [comment]
@Seika85 yeah we had a dev blow through our 25 monthly runners in an hour testing the API tests.  We've switched to running our folders and collections with the newman docker image for now while we migrate all our tests to Robot framework.  Can't wait to be done with Postman, so many things wrong with it when you get to a reasonable scale.  All our documentation is being migrated to openapi specs with auto generation.  Glad Postman forced us to migrate the future of our testing and docs are no longer constrained by Postmans poor usability.
