### ISSUE TITLE
Can't build API documentation, no violations found.

### ISSUE THREAD

**Issue by clmpi** [a85/POSTMan-Chrome-Extension#11861]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am trying to upload an API definition file and would like to use the automatically generated documentation.

However, after uploading the definition file, and navigating to 'Definition' where that documentation should be found, I see a message that reads :

```
Couldn't create documentation
Please fix violations in the definition to view the updated documentation.
```

However, navigating to the definition, it shows 0 violations found.

### Steps To Reproduce

1. Create a new API
2. Add definition > Import Files
3. Upload the file found [here](https://community.onespan.com/sites/default/files/interactive_api_references/oss_1150.yaml)
4. After the definition has finished loading, verify that no violations were found (may need to refresh to view results of check)
5. Go to 'Definition' page for API, verify that documentation is unable to load 

### Screenshots or Videos

[
![Screenshot 2023-03-27 093227](https://user-images.githubusercontent.com/117836548/227971578-c979ad0c-c8e1-4746-a1ad-7b37636be7be.png)
![Screenshot 2023-03-27 093250](https://user-images.githubusercontent.com/117836548/227971585-09f513cd-7ab5-466c-a9e5-838e874d9951.png)
](url)

### Operating System

Windows

### Postman Version

10.12

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by shashankawasthi88** [comment]
@clmpi I see some non-printable characters in the schema and the error is pointed out in the syntax error tab. Once you remove those, the documentation gets generated.
"description: >-
        Retrieves a list of the users in an account. Optional query parameters
        can be used to filter the list. By default, only one sender is
        retrieved. To retrieve additional users you must modify the â€œtoâ€ and
        â€œfromâ€ parameters, where each number in the parameter corresponds to a
        user. For example: to = 3 from = 10 Will return users 3 to 10 in the
        user list."
        
    

https://user-images.githubusercontent.com/71059054/227997799-a1537fe8-0075-4bf1-a27c-468d74eb78cf.mov

May I know if this is intentional?

**Comment by clmpi** [comment]
Those unprintable characters should not be in there, it is interesting they showed up in yours, and that deleting them fixes the issue. 

When I import the definition file, either by just uploading it directly from my machine, or by importing using the provided URL, those unprintable characters display in Postman just as double quotes `"`, and deleting them does not fix the issue, with the documentation still being unavailable.

![image](https://user-images.githubusercontent.com/117836548/228001345-662203a9-ff64-417c-8baf-3b04a4d9d117.png)


Also, just to confirm, by documentation, I mean the documentation found here: 
![image](https://user-images.githubusercontent.com/117836548/228001465-ec4fb9e6-556c-4a3a-88a3-d2bf27b44a3c.png),
here is an example from the boilerplate of what it should roughly look like:
![image](https://user-images.githubusercontent.com/117836548/228001774-4010eaea-2fb9-4fd7-acbe-1e7162b28cde.png)

The sidebar with the dropdowns is working fine:
![image](https://user-images.githubusercontent.com/117836548/228001591-f7800d7b-5cd8-4105-aa9f-2f95bc719a1a.png)

**Comment by shashankawasthi88** [comment]
@clmpi let us look into it and revert shortly.

**Comment by VShingala** [comment]
@clmpi It seems the definition is not correctly defined. i.e. In mentioned definition take a look at line no. 9643. `$ref` mentioned here should be a valid schema object but we have `response` object linked here.

We're working on improving the experience such that such issues are reported on App better. Meanwhile, as a workaround you can fix this by any of the following.

1. Mention any valid schema object here instead of response. For example, replacing this `$ref` value from `'#/components/responses/ResultUrl'` to `'#/components/schemas/SubAccountApiKeys'` should provide correct documentation.
2. Remove `items` property here as it seems type is already `string` and `items` should usually be defined for type `array`.

**Comment by clmpi** [comment]
I can confirm that commenting out lines 9642 and 9643 has the documentation displaying as desired. For whatever reason my other editor also wasn't informing me of the error, though the online SwaggerEditor seemed to catch it. Thank you for your assistance
