### ISSUE TITLE
GraphQL - Subscription return "Server sent no subprotocol" because request header `Sec-WebSocket-Protocol` is unchanged

### ISSUE THREAD

**Issue by Zgore14** [a85/POSTMan-Chrome-Extension#11874]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm trying to use a GraphQL Subcription with Postman on my private API and i'm facing a problem with the request headers in the GraphQL query editor.

The `Sec-WebSocket-Protocol` header as well as other headers are not visible in the headers section when showing hidden headers.
And if I want to change the `Sec-WebSocket-Protocol` header value, the value I put isn't take in account (cf screenshot).

This issue cause the request to be marked as failed by Postman, because "Server sent no subprotocol".
Note that on the server side of my API, I can see that the Postman client subscribed without any error, and for information, I don't use any subprotocols (maybe I will need to change that, but I think there is still the issue with the unchanged header).

### Steps To Reproduce

1. Open a new GraphQL Request Tab
2. Select Headers section
3. Try to modify `Sec-WebSocket-Protocol` header's value
4. See the Header's value unmodified in the Request

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/21169263/228919662-ad22381c-30e9-4f79-aad9-fa3ee0bc6508.png)

### Operating System

Windows 11

### Postman Version

10.12.9 (UI Version 10.12.9-ui-230328-1030)

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

The same Subscription is working with the WebSocket request.

**Comment by yesmanmx** [comment]
Have the same issue.
Header `Sec-WebSocket-Protocol` setted explicitly shouldn't be overridden by Postman's default values

**Comment by Zgore14** [comment]
@codenirvana is this a big issue to solve on your side ? Is there a chance the fix could be part of a near futur release ?

**Comment by codenirvana** [comment]
@Zgore14 We are looking into this, and it will be fixed soon.

**Comment by Leepro1234** [comment]
is clear ?

**Comment by Droni** [comment]
postman RIP

**Comment by timhall** [comment]
Hi all, sorry for the delay in updating this issue, we fixed this in April 2023. I looked into why this may still be occurring and `graphql-ws` does have some validation around the expected protocol, https://github.com/enisdenjo/graphql-ws/blob/63881c3372a3564bf42040e3f572dd74e41b2e49/src/server.ts#L566, so that may be causing the issue if the server is expecting a different protocol. I tested it with an echo server that sends back the protocol specified in the `sec-websocket-protocol` header and the GraphQL client is successfully sending the given header.

<img width="428" alt="image" src="https://github.com/user-attachments/assets/2ef5ce23-9d77-4510-b002-f2f57137598b">
