### ISSUE TITLE
Run results time duration

### ISSUE THREAD

**Issue by dhruv0206** [a85/POSTMan-Chrome-Extension#11877]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Here duration shows as 1h 107m. But if it already represents in hours then 107 min should also be converted into hours. Then it should be like 2h 47 min and not 1h 107 min.

### Steps To Reproduce

Make an api that takes a pretty high time to generate response and run 100 iterations or more. 

### Screenshots or Videos

![Screenshot 2023-03-31 032231](https://user-images.githubusercontent.com/53010251/229053112-3fca49a7-8575-477f-9f9e-3bc29d23b6ad.png)

### Operating System

Windows

### Postman Version

10.12.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by malvikach** [comment]
@dhruv0206 👋 

Thanks for sharing the feedback on this! We are fixing this and a fix should be available in the upcoming release. 

Let us know if you see any other issues.

Regards
Malvika

**Comment by malvikach** [comment]
Hi @dhruv0206 

This issue has been fixed in the latest Postman release 10.13. Please let us know if you still face any problems with it. 

Please Note: The Postman version update is being rolled out, you will get it in the next 1-2 days if you haven't already.

I will be closing this issue, thanks again for sharing your feedback. 

Cheers,
Malvika
