### ISSUE TITLE
Header with special character "]" will be missing when import as CURL

### ISSUE THREAD

**Issue by coolalexhuang** [a85/POSTMan-Chrome-Extension#11888]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I import the CURL to postman, the header with value of "]" will be missing.

### Steps To Reproduce

1. Import below CURL to postman:
curl -X GET "https://alextest.com" -H "5f005074: [jKanrLih$!]SooCV5u)aI!pt9"
2. The character "]" is missing.

### Screenshots or Videos

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/2528449/229479512-201cfdb6-806d-4cf2-aa36-a97d8bd41aff.png">

### Operating System

macOS

### Postman Version

10.12.10

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by dhwaneetbhatt** [comment]
Hey @coolalexhuang, thanks for reporting this issue. We will update this thread when it is fixed.

**Comment by aman-v-singh** [comment]
Hey @coolalexhuang,
This issue is caused because the string has an unescaped `$`, this needs to be `\$`.
So, doing something like:-
`curl -X GET "https://alextest.com/" -H "5f005074: [jKanrLih\$!]SooCV5u)aI!pt9"`
or using single quotes:- 
`curl -X GET "https://alextest.com/" -H '5f005074: [jKanrLih$!]SooCV5u)aI!pt9'`
would solve the problem.

Let me know if this helps.
I am closing this issue for now, if you don't find this solution satisfactory, you can reopen the issue.
