### ISSUE TITLE
Postman Flows should support group blocks for easily to move the blocks

### ISSUE THREAD

**Issue by giangdo11** [a85/POSTMan-Chrome-Extension#11903]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Hi Team
There is an issue in this ticket
https://community.postman.com/t/postman-flows-should-support-group-blocks-for-easily-to-move-the-blocks/46058

### Describe the solution you'd like

Postman flows should have a function to group the blocks.

### Describe alternatives you've considered

There is no alternative solutions

### Additional context

![image](https://user-images.githubusercontent.com/29271066/230776532-071c455d-9e85-4ca4-a872-3e5853289b57.png)

**Comment by shamasis** [comment]
Yes. Happening. 🎉

**Comment by chrisjpatty** [comment]
<img width="1114" alt="Screenshot 2023-06-22 at 4 17 23 PM" src="https://github.com/postmanlabs/postman-app-support/assets/14916515/36f1b996-12b4-4e8e-9436-6d0bdc58c7fd">

Happy to report that grouping is now available in Postman. To create a group, hold shift and select several nodes and use the toolbar that pops up to create your group. If you don't see the grouping feature make sure to update your desktop app or refresh your browser.

**Comment by Romasato** [comment]
Does each Group execute automatically in sequence? Asking because when I click RUN, my both Groups execute associated Requests in each of them - but they have no connected lines from one group to another, just some variables. Which was really confusing and corrupted data on our CMS..... 

There is too much "magic" happening and really unexpected behavior.
