### ISSUE TITLE
Please allow the app to be used w/o sign in, as we can't store organization data on outside cloud

### ISSUE THREAD

**Issue by mkp246** [a85/POSTMan-Chrome-Extension#12054]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

can't use while singed in as no control of data
also large collections which exceed free tier limit

### Steps To Reproduce

.

### Operating System

win

### Postman Version

10.14.5

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by ChristopherSnay** [comment]
I came here to say the same thing. The cloud functionality has caused my organization to ban Postman altogether. Please consider releasing a version that does not include this.

**Comment by preethammavin** [comment]
Hey, we do not have a limit on the number of collections in the free tier on the cloud.  You can read more about why we had to deprecate scratchpad [here](https://blog.postman.com/announcing-new-lightweight-postman-api-client/). If you have any concerns or questions about migrating to the cloud, write to us at migrate@postman.com so that we can help you better.

**Comment by ChristopherSnay** [comment]
> Hey, we do not have a limit on the number of collections in the free tier on the cloud. You can read more about why we had to deprecate scratchpad [here](https://blog.postman.com/announcing-new-lightweight-postman-api-client/). If you have any concerns or questions about migrating to the cloud, write to us at [migrate@postman.com](mailto:migrate@postman.com) so that we can help you better.

This response did not acknowledge the issue
