### ISSUE TITLE
Unable to Launch Scratchpad

### ISSUE THREAD

**Issue by dbesade** [a85/POSTMan-Chrome-Extension#12064]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am unable to access scratchpad on a new install of Postman 10.14 on the Windows Platform. Existing Installations upgraded to 10.14 are able to access scratchpad

### Steps To Reproduce

1. Download Client
2. Install Client
3. Click Cog
4. No Scratchpad!

### Operating System

Windows 10 22H2

### Postman Version

10.14

### Postman Platform

Postman App

### User Account Type

Signed Out User

### Additional Context?

Data protection rules prevent us from exposing our internal APIs to Cloud

**Comment by preethammavin** [comment]
We have deprecated the scratchpad with the release of V10.14, and you can read more about it [here](https://blog.postman.com/announcing-new-lightweight-postman-api-client/).

We recommend using Workspaces for better organization of your requests using Collections. Workspaces lets you to collaborate with your teammates better. If you are not able to use or need help in moving to Postman workspaces, drop us an email at [migrate@postman.com](mailto:migrate@postman.com)

**Comment by JoergSiebahn** [comment]
In read-only #12114 many users complain about their company policies that make it impossible to use the service in the cloud. We use the Postman Collections for automated end2end tests in our GitOps repositories. In my opinion it is really bad practice to store the tests for a piece of software somewhere else than the software itself. Is there any developer who would create a separate repository or a workspace in a completely unrelated cloud service to implement the unit tests for their software? Why should that be different when testing how deployed software works?

**Comment by nvinchhi-extron** [comment]
I wish I could express how angry I am at postman for deprecating a feature like scratchpad in a minor version. Such an absolute asshole move on their part. Our company is moving away from postman because of this whole fiasco. I hope their 'vision' of screwing their users over comes to fruition. Thankfully we won't be there to see it.

**Comment by mamraz** [comment]
This is precisely why I turn off auto-updating in pretty much all software I run.   I don't want breaking changes, whether intentional or unintentional, to be installed on my system without my having a chance to decline it.  Saving my API data to a cloud service is not acceptable, and the new lightweight API client looks pretty pathetic, so I am thankful I am running an older version of the app that still can save collections locally.  I should probably start looking for a new tool for any new work I do so that I don't have to rely on an old tool continuing to work forever.
