### ISSUE TITLE
Folder tabs no longer stay open/visible

### ISSUE THREAD

**Issue by tylersouthard** [a85/POSTMan-Chrome-Extension#12075]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Opening a folder to a tab and then opening a request consumes the folder's tab, making it impossible to keep a folder tab open. I use folders to hold some authentication settings, so I like to keep the parent folder open so I can quickly refresh tokens, etc.

For requests, there is an "Open in Tab" option, but not for folders.

### Steps To Reproduce

1. Open a folder (creates a new tab)
2. Open a request (consumes the folder tab instead of making a new tab)

### Operating System

Windows

### Postman Version

10.14.8

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by giridharvc7** [comment]
Hope this video helps. 
You can change this behaviour in the settings or double click on the tab so that its not a `preview` tab. 
A preview tab is to quickly preview items on your collections without opening a new tab everytime. 
https://github.com/postmanlabs/postman-app-support/assets/1040583/8f926408-a950-428d-a57a-414aedea3bf7
