### ISSUE TITLE
Variable resolution is unreliable during performance test

### ISSUE THREAD

**Issue by postfrzero** [a85/POSTMan-Chrome-Extension#12083]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

This ticket is being created to track and issue reported via comments[1][2] on #11980.

Performance test runs using collections which have environment or collection variables show 100% error rate. This is difficult, if not impossible, to debug due to #11980, but the underlying problem is likely different since removing the variables and using hard coded values resolve the problem.

[1] https://github.com/postmanlabs/postman-app-support/issues/11980#issuecomment-1576779842
[2] https://github.com/postmanlabs/postman-app-support/issues/11980#issuecomment-1580776894

### Steps To Reproduce

1. Start a performance test using a collection that has environment or collection variables.
2. Note that the reported error rate is non-zero while the test is running.
3. Edit the collection to remove variables and use hard coded values instead.
4. Note that the reported error rate has dropped, possibly to zero.

### Operating System

Windows

### Postman Version

10.13.9-canary01

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by postfrzero** [comment]
We haven't been able to recreate the problem yet, using Postman for Mac 10.13.9-canary01. We've tried comparing global, collection, and environment variables across the collection runner and performance tests. Having additional information specific to the failure will help and it'll help us discount the usual suspects:

- Is the environment selected when the test is configured and started?
- Is the environment using just initial values, or both current and initial values?
- Does running the same collection with variables work as expected within the collection runner?
- Do global variables work as expected?

@Octobeast999 Would you mind sharing the collection ID and run number? We can move to an internal ticket as well if there are additional details to be shared.

**Comment by nhsJim** [comment]
Hi, I can answer some of these questions: 
I am using a Mac M1 13.3.1 (a) - Ventura
For me:
* I only have environmental variables set and configured when running the performance test
* All of the values are initial 
* Running the collection in functional mode works fine
* My Workspace has no global variables set, so I can not answer the last question.

**Comment by aprokopenko** [comment]
Not sure, this is related to this bug or not. If needed - I can create a separate issue.

I'm using Ubuntu 22.04, Postman Canary to try performance testing.

I did a quick test on a simple endpoint available on the internet - and it was fine.

Then I created small collection, which has several scripts and variables sets inside as well. It works fine when I run the collection as usual in several iterations. I use my local dev server, with address like myproject.test:8080.
All URLs I have in environment variables.
(Also I have my own certificates for local domains, which I added to Postman settings and usual requests do not generate any errors or warnings)

Then I tried to run performance testing and got 100% error rate. I tried to set URLs directly inside requests without using vars and the result was the same - 100% error rate. No any requests were send to the server, because all logs were clear on my server.

Then I tried to replace environment variables to the client staging URL, which is available on internet - and it works!

So for some reason new Performance testing doesn't work with local URLs (don't have opportunity to check is the problem with ports or no).

**Comment by shreyas-panduranga** [comment]
All, we're now aware of an issue in performance testing feature where when we fetch a value that is stored in the environment, it is truncated to 140 characters. If the values you have been testing with exceeds this limit you will be affected by this issue. Any values shorter than this limit won't be affected and you can continue to keep them in the environment.

We are looking to fix this very soon. Collection variables don't suffer from this issue.

**Comment by malvikach** [comment]
Hi All,

Variable Resolution issues have now been resolved in the latest release of Postman (version 10.16.0). Please take a look and let us know if you are still facing any challenges with it. (@aprokopenko) 

Thanks for your feedback. 

Cheers!
Malvika
