### ISSUE TITLE
Postman editor removes content in tag format

### ISSUE THREAD

**Issue by ru4ert** [a85/POSTMan-Chrome-Extension#12172]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The postman editor removes content when the content looks like a html tag.

### Steps To Reproduce

1. Open postman editor
2. Write something between those tags: <>
3. Close the editor
4. The content (Tag) is removed

### Screenshots or Videos

This "\<help\>" will get removed on close:
<img width="796" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/47078678/ada91821-429c-4aee-9f26-449ed9dddbaa">

### Operating System

macOS

### Postman Version

10.16.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Also encapsulation is not working like \\<help\\>

**Comment by ekansh-001** [comment]
Hello @ru4ert,

It would be better if you could explain your use case for adding tags directly in content 🙇 .
It is recommended to include tags within the codeblock as they will not be removed, which may be useful for your particular use case.

**Comment by ru4ert** [comment]
If i remember back, i wanted to add a description. Inside the description i wanted to use something like 
`http://localhost/api=<APIKEY>` but i am not sure anymore

**Comment by ekansh-001** [comment]
Hello @ru4ert,

Postman editor doesn't support tags inside codeSpan. If you want to use tags in codeSpan we recommend you to use markdown editor that supports this use case. Also if you choose to use the markdown editor then you would also need to change the default editor (Settings → General → Default documentation editor) to the markdown editor to prevent the loss of data.

Since this is not an issue but instead an intentional design choice, I am closing off the issue.
Please feel free to open up the other issue on the board if you face any other problem 🙇
