### ISSUE TITLE
Override `Content-Type` header field.

### ISSUE THREAD

**Issue by bartoszj** [a85/POSTMan-Chrome-Extension#1221]
When I set body type to `x-www-form-urlencoded` Postman automatically adds `Content-Type` with value `application/x-www-form-urlencoded`. It is not possible to override value of this header from **Heades** section. In my case I've to use `application/x-www-form-urlencoded; charset=utf-8` and I'm unable to set it without setting body type to `raw.`

In my opinion **Headers** values should override values from **Body**.

**Comment by grongor** [comment]
The problem is even if you don't want to use `x-www-form-urlencoded`. If I use `raw` in the body section and then add header `Content-Type: application/json;charset=windows-1250` and send the request, server receives `Content-Type: application/json;charset=UTF-8` ... which really sucks.

I would expect no alteration of headers at all from a tool which is used to test API endpoints and such. It's not possible to test exact problematic headers, which is essential for a tool like that.

**Comment by SamvelRaja** [comment]
@grongor @bartoszj  Overriding the content-type is available in our latest app. Can you guys check the same and let me know if i missed any?
![screen shot 2017-01-03 at 2 59 52 pm](https://cloud.githubusercontent.com/assets/5114052/21603833/f9499eb2-d1c5-11e6-98e7-a2e2e2e87a4b.png)

**Comment by grongor** [comment]
Sorry to reply so late ... I can confirm that in the new app (not the Chrome one) it works just fine. Thank you!
