### ISSUE TITLE
Publish VSCode Extension to open-vsx.org

### ISSUE THREAD

**Issue by milesje** [a85/POSTMan-Chrome-Extension#12299]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Extension not is not available to VSCodium or VSCode that uses the open-vsx.org repository.

### Describe the solution you'd like

Publish extension to open-vsx.org repository

**Comment by Siddhant-K-code** [comment]
More context & details on this:

## Context

Unfortunately, as Microsoft prohibits usage of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor-neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io/), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by joelapatatechaude** [comment]
Seems like a no-brainer, and a great way to get this extension available to a much wider audience.

**Comment by pozil** [comment]
On behalf of the Salesforce community, I will add that we would love Open VSX support for the Postman extension.
Having the extension on the Open VSX registry is a requirement for our Code Builder product (our Web IDE).

**Comment by Siddhant-K-code** [comment]
@pankajk07 any updates to this? Anything else we can help out with?

**Comment by pankajk07** [comment]
@milesje @Siddhant-K-code @joelapatatechaude @pozil 

Folks, we have some good news. [Postman's VS Code extension](https://open-vsx.org/extension/Postman/postman-for-vscode) has been published to the Open VSX marketplace. Please try it out and share your important feedback.
