### ISSUE TITLE
Postman API and Postman Client out of sync

### ISSUE THREAD

**Issue by icodev-space** [a85/POSTMan-Chrome-Extension#12350]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Cannot delete mock collection items.

### Steps To Reproduce

1. Create a mock server with an empty collection (via Postman Client)
2. Add request items with example responses (via Postman Api)
- POST to /collections/collectionId/requests
- POST to /collections/collectionId/responses?request=requestId
3. Reset the collection
- PUT to /collections/collectionId
4. Repeat 1 (here is when the items compound)
5. Verify the collection state 
- GET /collections/collectionId
6. Observing the items returned for the call at 5. they seem what they should be per the last POST requests
7. Observing the items in Postman Client, they just compound and if I attempt to delete any of them I get on the UI the following pair of messages:
- requestName was deleted successfully.
- Unable to delete request

https://pasteboard.co/PH9mMNO2BT5x.png

### Screenshots or Videos

https://pasteboard.co/PH9mMNO2BT5x.png

### Operating System

Windows

### Postman Version

10.17.4

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by icodev-space** [comment]
So this whole thing is getting a bit absurd.

When I navigate to the collection it appears empty. When I click on it to add a request all requests are "loaded" from somewhere and it's not empty anymore. Calling an example response from the collection via POST mockserver/item I receive the response, calling GET collections/collectionId returns a collection with empty Item array?! All this has worked alright a week or two ago?

**Comment by icodev-space** [comment]
Hello @davidespihernandez,

Thanks for taking my call last Monday, have you managed to reproduce the problem at your end? Will appreciate any updates.

Thank you!

**Comment by davidespihernandez** [comment]
Hi! @icodev-space!
I'm going to start working on this now (I was busy with other important tasks the last week). 
In our talk, we noticed you were using a Postman API key that was not your API key. We changed the code to use your key, but the error persisted. I believe we have a permissions problem here, but I'm not sure where it is. I wonder if the workspace you are using has some limitations for your API key... If you can create a new workspace and test with your API key there, that would be great.
I'll reproduce the steps on my own and will come back to you soon.
Thanks for your patience.

**Comment by icodev-space** [comment]
Hi David,

Thank you for your assistance, I will test this and let you know!

**Comment by davidespihernandez** [comment]
Hi, @icodev-space!
I've created a repository with code to test your issue here:

https://github.com/davidespihernandez/create-request-github-issue

I've reproduced all the steps, using a workspace that I created, and my Postman API key, and I can't get the same results. 

* I created an empty collection.
* I created a mock server (though this should not affect this).
* I added a request and a response programmatically using the command created in the repository.
* The request and the response are visible and I can manage them.
* I performed a PUT with an empty list of items on the collection ```"item": []```
* The collection request is deleted properly.
* I execute the command to create a request again, and the request and the response are properly created again.

I've gone through the process several times and it works. If you can test in a collection created in a workspace that you own, that should work. So I guess the issue is related to the permissions of the existing workspace or collection that you are working on.
If you test it in another workspace and you have the chance to change the workspace, that would work.

Summary: The Postman API is working well, apparently, so the problem may be something related to permissions. If we need to check the weird behavior with that specific Postman API key, collection, and workspace, we will need specific and private information from the customer, and collaboration from other internal teams.

@DannyDainton passing this back to you, as I can't do anything else to fix the problem.

**Comment by icodev-space** [comment]
Thank you @davidespihernandez for your help.

I will test that and get back to you!

**Comment by icodev-space** [comment]
Hi @davidespihernandez and @DannyDainton 

I have removed the creator of the workspace and added my user to it as Admin but the problem persisted.
I then created a workspace where I am the owner and things suddendly started working as they should.

Could you please provide some guidance/documentation as to why we are seeing this behavior?

Can the owner be changed? We would like to have the workspace under a domain system user not a particular person. What would be a correct setup to workspace owner, admin rights etc. So the app behaves as it should withouth the current permissions issues. How can this be configured and tested?

Ideally I just need the workspace/collection to work as expected regardles of the user, if we have it under a given person's account and he leaves the org tomorrow we'd end up in the same predicament.

Thank you!

**Comment by davidespihernandez** [comment]
Hi, @icodev-space!
From the Postman API perspective, everything should work the same way in both workspaces, as long as the API key owner has the right permissions on the objects. My guess is that there's something internal related to permissions that we are missing and we can't see on the old workspace. @DannyDainton We will need help from other squads (runtime) to check why this odd behavior happens.

**Comment by davidespihernandez** [comment]
Closing this ticket, as it's not reproducible.
