### ISSUE TITLE
Postman GitHub Integration does not show any repository branches for Postman version v10.18.11

### ISSUE THREAD

**Issue by Purvi-30** [a85/POSTMan-Chrome-Extension#12397]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

It is similar to #8284 however issue is not resolved there.
If there is any resolution, can it be share din Postman learning docs? 

Steps to reproduce - 
Postman version V10.18.11

There are 2 ways to reproduce this
A) 1. Click on Import
2. Select GitHub option
3. Authorize it
4. Select Organization in the Import from GitHub pop-up (It by default shows your user ID as organization)
5. Repository - Error No repositories found under selected organization.

B) 1. Click on Home
2. Select Integrations
3. Browse all Integrations
4. Click Backup a Collection option Add Integration button
5. Enter PAT
6. Authenticate PAT
7. Enter Nickname
8. Choose Workspace
9. Choose Collection
10. Choose Repository is disabled as no repositories are being shown to select.

### Steps To Reproduce

Steps to reproduce - 
Postman version V10.18.11

There are 2 ways to reproduce this
A) 1. Click on Import
2. Select GitHub option
3. Authorize it
4. Select Organization in the Import from GitHub pop-up (It by default shows your user ID as organization)
5. Repository - Error No repositories found under selected organization.

B) 1. Click on Home
2. Select Integrations
3. Browse all Integrations
4. Click Backup a Collection option Add Integration button
5. Enter PAT
6. Authenticate PAT
7. Enter Nickname
8. Choose Workspace
9. Choose Collection
10. Choose Repository is disabled as no repositories are being shown to select.

### Operating System

Windows

### Postman Version

10.18.11

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by piyush-daga** [comment]
While authorizing OAuth or selecting PAT, Github shows which organizations you have access to and it shows the `authorize` button near organizations that haven't been authorized yet.

<img width="713" alt="Screenshot 2023-10-12 at 3 55 00 PM" src="https://github.com/postmanlabs/postman-app-support/assets/9255130/c6f70e0b-89bb-42c0-8860-ae07c11b9edd">

Do authorize if you are planning to select the repos from those organizations that are not authorized yet. As only the repos of authorized organisations can be listed.

If above steps doesn't work for you, please attach the screenshots where you are seeing the issue and do share the logs for us to debug further.

Thank you!

**Comment by SbhalalaJHA** [comment]
Observing same issue and I do have SSO
![image](https://github.com/postmanlabs/postman-app-support/assets/103943687/c3d085e4-a73e-4606-a760-bed567cddd4b)

**Comment by Purvi-30** [comment]
After following steps mentioned in Steps !), I am seeing this option instead of SSO . so it doesn't have an authorize button but a request button. Are both same?
![image](https://github.com/postmanlabs/postman-app-support/assets/75479203/11c948ca-700e-4aab-adfe-ad013fa2e357)

**Comment by piyush-daga** [comment]
If the repositories (to be accessed) are in one of the organizations mentioned above, `Requesting Access` and completing the workflow should solve the listing issue.

**Comment by piyush-daga** [comment]
Hi @Purvi-30 is this issue resolved for you as well? If yes, I'll go ahead and close this issue.

**Comment by Purvi-30** [comment]
> If the repositories (to be accessed) are in one of the organizations mentioned above, `Requesting Access` and completing the workflow should solve the listing issue.

What do you mean by Requesting Access here? As I am clicking  Request button, it says access request pending as it will go for approval. So should I click authorize postman labs now and proceed or otherwise also how will I be notified that this access is given to postman? Should I expect an email? AND what do you mean by the workflow here? The process of approval and further authorizing or something else?

**Comment by SbhalalaJHA** [comment]
Yes thanks

**Comment by piyush-daga** [comment]
Closing this issue, as after requesting access to the required organizations the reporter was able to list the repositories and complete the workflow.

**Comment by piyush-daga** [comment]
Hi @Purvi-30 detailing the complete workflow where we have to request access from an organization.
I have created 2 organizations:
- testing-for-testing (where I am the owner)
- the-25-th-of-october (where I do not have access to grant permissions)

When I start the OAuth workflow from postman. This is the screen I land on:
<img width="579" alt="Screenshot 2023-10-25 at 11 49 24 AM" src="https://github.com/postmanlabs/postman-app-support/assets/9255130/7caf2f8f-a31e-4f73-9e9a-5e6c97eeb872">

Since these are not the organizations I want to authenticate against, I'll click on `Continue`. After that I am presented with this screen:

![Screenshot 2023-10-25 at 11 24 16 AM](https://github.com/postmanlabs/postman-app-support/assets/9255130/4bdb2a7e-1782-4df8-b3f4-156036300d62)

Notice that for the `the-25-th-of-october` organization I do not have access, nor can I grant the access myself. So, I click on  `Request` access

![Screenshot 2023-10-25 at 11 24 28 AM](https://github.com/postmanlabs/postman-app-support/assets/9255130/c1eac049-89d9-4950-a9d4-2c65ef035d38)

After clicking on `Request approval from owners`

![Screenshot 2023-10-25 at 11 24 41 AM](https://github.com/postmanlabs/postman-app-support/assets/9255130/e12a5c3d-f04c-4ffe-a022-533b58be7644)

**At this point, we can close this screen, as we need to wait for the `administrator/owner` to provide us relevant access.**

After requesting access the `administrator/owner` of the organization gets an email and can approve `postmanlabs` access to the organization and its repositories.

Email:
![Screenshot 2023-10-25 at 11 25 44 AM](https://github.com/postmanlabs/postman-app-support/assets/9255130/3c4a766b-d62a-4842-8823-704270e1e361)

Before access is granted:

![Screenshot 2023-10-25 at 11 26 16 AM](https://github.com/postmanlabs/postman-app-support/assets/9255130/c4e42e5b-fbc8-4a96-ad9c-ac45a0e6f8da)

After access is granted:

![Screenshot 2023-10-25 at 11 26 32 AM](https://github.com/postmanlabs/postman-app-support/assets/9255130/0cffe88e-a1a1-4240-9896-d2d004b889af)

Once the access is granted we can start the flow again from postman (re-authenticating with Github). Now when we approach the `Authorize Postman` screen, this is what it looks like:

![Screenshot 2023-10-25 at 11 26 57 AM](https://github.com/postmanlabs/postman-app-support/assets/9255130/27bc4501-1618-498a-9c3a-5e3ebc83c579)

As we can see, we now have access to the organization and can `Authorize postmanlabs`. After authorizaton, we can can close the window and now we can, see the organization listed:

![Screenshot 2023-10-25 at 11 28 03 AM](https://github.com/postmanlabs/postman-app-support/assets/9255130/044f0698-8570-43fb-917a-1bda1b826946)

Can list the repositories inside the organization:
![Screenshot 2023-10-25 at 11 28 49 AM](https://github.com/postmanlabs/postman-app-support/assets/9255130/53cc0996-0bff-46e4-afff-5a213ea5cd82)

Let me know if this helps, if there are still some doubts, we can always get on a call to address them.

Thank You.

**Comment by piyush-daga** [comment]
Closing this issue as reporter has not replied back for 2+ weeks. Feel free to re-open this or file another issue as required.
