### ISSUE TITLE
Runner fails to upload a file for a key parameter, although Builder works.

### ISSUE THREAD

**Issue by spiroskgr** [a85/POSTMan-Chrome-Extension#1243]
Hello! I am using Postman to perform smoke testing of my API. I have set up the environment and all the keys with their values in the Body and I am checking if the body in a response to a POST contains a specific string. One of the key parameters is a file that I always select before I run the test. BUt, when I run the test through a collection in the Runner, the (.jpg file) file is not uploaded and the test fails, although when i run the test in the builder the testing is successful. Can you please let me know how to fix the runner, as I am trying to find a way to automate the test cases. Thank you.

**Comment by abhijitkane** [comment]
Due to limitations of the Chrome platform, we are unable to save files as part of a collection. This makes it impossible to upload files when using the collection runner.

However, this is possible using Newman (http://npmjs.org/package/newman). You'll have to edit the exported collection a bit, but you'll be able to upload files as part of the collection run - http://blog.getpostman.com/2014/11/15/using-newman-to-run-collections-with-file-post-requests/

**Comment by spiroskgr** [comment]
I downloaded Newman in order to be able to download files using the collection runner. However, after trying to run a collection I always receive the following error:

Iteration 1 of 1
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: EISDIR, read
    at Error (native)
spyros@spyros-SZ77:~/npm-global/lib/node_modules/newman/bin$ 

Can you help me on how to proceed? I have not managed to solve it for the last two days.
