### ISSUE TITLE
When deleting from a Collection, please keep scrollbar where it was before the delete

### ISSUE THREAD

**Issue by ryanhalley** [a85/POSTMan-Chrome-Extension#12553]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

We have many collections so the scrollbar is visible. I reviewed a collection that was at the bottom of the list, so was near the end of the scrollbar and off the first, visible page' worth of collections. I needed to prune a number of endpoints from that collection. After each deletion, the scrollbar is reset to the top of the collections list, so I had to keep scrolling back down to find the collection, just to continue my review to remove the next in a series of endpoints.

### Describe the solution you'd like

Before deleting an endpoint, store the scrollbar position so that after the deletion, the scrollbar can be set to that previous position, then the UX won't be disrupted and can just continue on with their next task.

### Describe alternatives you've considered

N/A, other than manually dragging the scrollbar back down to where you just were.

**Comment by ryanhalley** [comment]
This must have been a bug - today the issue is not occurring.

**Comment by vedkribhu** [comment]
Thanks for reporting this. It's likely that you experienced this issue due to the activation of a different tab following the deletion of a request. Deleting an entity results in the closure of its tab, causing the previous tab to become the active focus in both the workbench and sidebar. 

https://github.com/postmanlabs/postman-app-support/assets/37595282/a4431259-c851-4077-bb20-dd335b7f3744
