### ISSUE TITLE
Forked Environment Name Disappears - UI Bug 

### ISSUE THREAD

**Issue by matthewstmartin** [a85/POSTMan-Chrome-Extension#12566]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Forked environment name disappears after selecting the environment. 

I have only two environments, one named 'LE' and one named 'PROD', every other environment is a fork of either of these two. I have forked these environments many times and named them accordingly. For ONLY ONE of my forked environments, specifically named 'admin-oauth-mgmt', when selecting this environment, the name of the fork disappears. This only occurs when selecting the forked environment 'admin-oauth-mgmt' for either the 'LE' or 'PROD' environment.

### Steps To Reproduce

1. Go to environments tab
2. Find either the 'LE' or 'PROD' forks named 'admin-oauth-mgmt'
3. Select either said forked environment
4. The name of the fork will disappear, this causes confusion as it looks the same as the original environment

### Screenshots or Videos

![before](https://github.com/postmanlabs/postman-app-support/assets/155463815/e188d994-f627-4dbc-8a3e-7717298d3afa)
![after](https://github.com/postmanlabs/postman-app-support/assets/155463815/5a99fd50-d462-4508-9fbb-7a8e4908d22a)

### Operating System

Windows

### Postman Version

10.21.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

OS platform
win32 10.0.19045

**Comment by matthewstmartin** [comment]
Correction: This issue also is occurring with my forked environment 'admin-notifications', perhaps the issue is with the word 'admin' within the fork name? Why would this be an issue?

**Comment by coditva** [comment]
@matthewstmartin Thanks for reporting. I can replicate this issue. It doesn't depend on the name "admin" but happens when the base of the fork is deleted.

Steps to replicate:
1. Have an environment `E1`.
2. Fork the environment `E1 (my-fork-name)`.
3. Delete the environment `E1`.
4. Ensure no environment is selected. Close the app.
5. Re-open the app and select `E1 (my-fork-name)` as the active environment.
6. The fork label `my-fork-name` disappears.

I'll track this as a bug and let you know once it is fixed. In the meantime, I would suggested to either rename the environment, or create another fork.

**Comment by matthewstmartin** [comment]
Interesting, thank you for the help with this. The only thing I will reply with in regards to your steps is that I do not do step 3, delete the original environment.

**Comment by kartikjain26** [comment]
Closing this issue as fix is out in production.
