### ISSUE TITLE
Postman is using high memory in idle state

### ISSUE THREAD

**Issue by ashik-e-rabbani** [a85/POSTMan-Chrome-Extension#12588]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have kept my postman window minimized for more than 2 hours but suddenly laptop began to laggy after observing the system monitor found that postman itself using 6GB of memory when it is not even in use.

### Steps To Reproduce

1. Open postman
2. send some requests
3. Now minimize it

### Screenshots or Videos

![2024-01-17_14-12](https://github.com/postmanlabs/postman-app-support/assets/27617851/8da68327-154a-452c-ae72-7f6ab7350db0)

### Operating System

Linux

### Postman Version

v9.31.30

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by danekszy** [comment]
Hey Ashik, thanks for reaching out! 🙏 
Could you share some more details about the situation when you can observe this issue?
Specifically it would help us to know:
- which features of the app you've used prior to observing such memory consumption (eg. making requests/which protocol, APIs, mock servers, monitoring)
- how many postman tabs do you keep open (approximately)
- if you're dealing with big data sizes (many or big collections, big request responses, many collaborators etc)

Would you be comfortable sharing any more information?

On another note, is there a reason for you to use Postman v9? We're currently at v10.22, with v9 reaching end of support soon and there's a good chance that the issue was already solved in the meantime, since we've put a huge effort into making Postman even faster and more efficient. 😉
Definitely give it a go if you don't mind upgrading to the newer version!

Thanks for helping us improve Postman!
Daniel

**Comment by ashik-e-rabbani** [comment]
Hey @danekszy 

Thanks for your response. I had been using Postman to send HTTP GET/POST requests, and had 6 tabs open. I wasn't dealing with large amounts of data - the payload was pretty small, not exceeding 200 characters in length. 

Today, I updated my Postman to the latest version. Let's see how it works now.

best,
Ashik
