### ISSUE TITLE
Cannot maximize postman window on a secondary screen

### ISSUE THREAD

**Issue by georgerezk** [a85/POSTMan-Chrome-Extension#12683]
https://github.com/postmanlabs/postman-app-support/assets/39593408/e65d1737-a5fe-4b29-b6ad-e7d73870a686

### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If I minimize postman on a secondary monitor, it won't maximize "open" when clicking on the icon. This behavior doesn't happen if the postman is not maximized. 

### Steps To Reproduce

1. Windows 11 version 23H2 22631.3155
2. Open postman maximized on a secondary screen 
3. Click the postman icon on the taskbar or the minimize button on postman
4. Click the postman icon on the taskbar
5. Postman doesn't maximize nor open. The only option is to close it and open a new instance. 
6. Also, postman doesn't have context menu when right click on the icon on the taskbar. All other applications has maximize, minimize, restore, etc. 

### Operating System

Windows

### Postman Version

23H2 build 22631.3155

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by thundron** [comment]
Hi, I'm not able to reproduce with the most recent version of the application and Windows build 22631 on a 3 monitor setup, so my first thought leans more towards a driver issue; we'll investigate a bit more and get back to you.
Could you please share more information regarding your hardware too? In particular at least CPU model, GPU model and driver version

**Comment by georgerezk** [comment]
- 12th Gen Intel(R) Core i7-12800H   2.40 GHz
- NVidia T600 driver version 551.61 "latest production"
- Please note, it doesn't happen using the main monitor

**Comment by thundron** [comment]
Thank you! When did you notice this happening? Can you perhaps try an older version of the application to see if it shares the same behaviour?

**Comment by georgerezk** [comment]
Did you try it on one of your secondary monitors? Not the main monitor.

**Comment by thundron** [comment]
Yes, I tried on the second and third monitor, multiple times; doesn't reproduce on my end unfortunately

**Comment by georgerezk** [comment]
This only happens with postman. All other apps function correctly. I will reinstall postnam, reinstall the GPU drivers later on. I will use the web version for now.

**Comment by digitalstraw** [comment]
I've got similar problem. Postman after minimization cannot be restored back to visible state. I attach the video. 

Windows 11, 16 core AMD Ryzen, 64 GB RAM, 2T ssd hdd, ATI Radeon RX6600.
Does not matter if it'primary or secondary monitor in my case. Postman does this even after restarting the computer.

Postman version label: "You are up to date! Postman v10.23.8 is the latest version."

https://github.com/postmanlabs/postman-app-support/assets/38976574/fa6b9773-4747-4d98-898e-2560e23069d9

**Comment by lmejias9** [comment]
I had the same issue last week and looking for an answer I get to this post. Exactly the same issue with the last Postman update happens to me. I had to install an oldest Postman version to keep working, but today after restarting my PC Postman download again the last update and the issue appears again:

Successfully updated to version 10.23.5
Version: 10.23.8
UI version: 10.23.8-ui-240226-0504
Desktop platform version: 10.23.5
Architecture: x64
OS platform: win32 10.0.22631
Windows 11 Pro 23H2
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   1.69 GHz

**Comment by sdsoldi** [comment]
Same here. After a few minutes of use, I can't maximize. 

Closing from right mouse click is not finishing process. CPU usage about 10-20% after minimize "crash"

Windows 11
AMD Ryzen 5 3400G
Nvidia Geforce GTX 650 Ti
3 screens

**Comment by Giullianogp** [comment]
Same here! When minimize on second screen, can't maximize.

Postman: 10.23.8
windows 11
11th Gen Intel(R) Core(TM) i7-1165G7
2 Screens

**Comment by carlos-regis** [comment]
This same issue has been happening here for the last 2-3 weeks on both the regular and canary versions. I have just upgraded the regular version and still the same behavior.

**Comment by seb-bau** [comment]
I have the same problem.

Postman v10.23.8
Windows 11 (22H2 22621.3155)
2 screens

**Comment by thundron** [comment]
We're working on it and are almost ready to publish a fix, but just so that everyone is aware of what is causing this issue in the current build: in Windows 10/11, there is an unseen margin surrounding each window side (except the top one); it appears to consistently have a width of -7, regardless of scaling adjustments, at least on the tests we performed. The Postman application code was previously ignoring this unseen margin, resulting in numerous user complaints at the time regarding window positioning when altering their dual-monitor setups. This was exacerbated when users found that the application window relocated off-screen, making it inaccessible.
The initial resolution involved implementing a fix - which is the current Postman application code - that took into account the invisible border, resolving the previously reported issues. However, the Electron.JS version we recently upgraded to contains a fix that we had not anticipated - specifically, the restore event was previously not activating when a maximized window was reverted to its previous size, and now it is - which is now creating the current issue we see. This is because the _previous_ iteration didn't consider the unique window bounds for maximized windows (-8,-8 instead of -7,0).

Just to reiterate, we're already working on a fix; for now you can find the window in a corner of your screen if it disappears, but you can expect a fix for that very soon.

**Comment by ahawary92** [comment]
I have the same thing here, when minimize on second screen, can't restore

Postman v10.23.8
Windows 11 (23H2 22631.3155 )
2 Screens

**Comment by thundron** [comment]
We're rolling out the fix to this issue so expect this to go away with the newest versions of the application; please report back if possible when you're able to re-maximize the application correctly with the new versions

**Comment by georgerezk** [comment]
> We're rolling out the fix to this issue so expect this to go away with the newest versions of the application; please report back if possible when you're able to re-maximize the application correctly with the new versions

Tested and confirmed fixed.

**Comment by polnicki** [comment]
@thundron 
Seems that FIX works. 
Good job guys!

**Comment by seb-bau** [comment]
I can confirm this is fixed for me.
THANK YOU!!

**Comment by rdanklof** [comment]
The fix is working for me, thanks!

**Comment by ahawary92** [comment]
Worked for me too, thank you guys!

**Comment by carlos-regis** [comment]
I just upgraded to Postman v10.24.11 and the bug is confirmed dead. Thanks @thundron!

**Comment by gauravjantwal** [comment]
It is happening again on latest version `v11.23.3`

There is a twak to enable it again using F11
