### ISSUE TITLE
Incorrect Templating of Nested JSON Values in Postman Mock Server

### ISSUE THREAD

**Issue by adinath-nikam** [a85/POSTMan-Chrome-Extension#12711]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using Postman's mock server to simulate API responses, I encountered an issue with data templating when dealing with nested JSON structures. Specifically, the values from nested objects are not correctly populated in the response template using the {{$body '...'}} syntax.

### Steps To Reproduce

•	Create a mock server in Postman.
•	Set up a request with a nested JSON structure in the request body.
•	Create a response template that references the nested values using {{$body '...'}}.
•	Send a request to the mock server and observe the response.

### Screenshots or Videos

Expected Behavior:
The response template should correctly populate the nested values from the request body using the {{$body '...'}} syntax.
 
Actual Behavior:
Instead of correctly populating the nested values, the response template contains placeholders for the nested keys, and the values are not populated as expected.

Example:
Request Body:
{
    "name":"Jhon",
    "extras":[
        {"skill": "Programming"},
        {"hobby": "travelling"}
    ]
}

Response Template:
{
    "greet":"Hello, {{$body 'name'}} Nice to Meet You!.",
    "Extras": "{{$body 'name'}} likes {{$body 'extras[1].hobby'}}"
}

Expected Response:
{
    "greet": "Hello, Jhon Nice to Meet You!.",
    "Extras": "Jhon likes travelling"
}
 
Actual Response:
{
    "greet": "Hello, Jhon Nice to Meet You!.",
    "Extras": "Jhon likes "
}
![Screenshot 2024-03-12 124125](https://github.com/postmanlabs/postman-app-support/assets/44538759/55f00d34-5c18-4c15-8ba2-9a3ee50477ea)
![Screenshot 2024-03-12 124211](https://github.com/postmanlabs/postman-app-support/assets/44538759/64cffaa5-e9fa-4f0c-8abc-ebda689a242b)

### Operating System

Windows

### Postman Version

10.24.1

### Postman Platform

Both

### User Account Type

Signed In User

### Additional Context?

**Workaround:**
As a workaround, users can manually construct the response body without relying on data templating for nested JSON values. However, this is not a scalable solution and may lead to maintenance issues.
 
**Proposed Solution:**
I suggest investigating and addressing the underlying cause of the issue with data templating for nested JSON structures in Postman's mock server. This may involve enhancing the data templating functionality to support nested object traversal or resolving any underlying parsing issues.
 
**Conclusion:**
The incorrect templating of nested JSON values in Postman's mock server poses a usability issue for users attempting to simulate API responses accurately. Addressing this bug would improve the reliability and effectiveness of Postman's mock server feature.

**Comment by sony-mathew** [comment]
Hi @adinath-nikam, 

The way that you specify path to a nested JSON value inside a body in dynamic mocks is slightly different. Here in this example you have mentioned, this is the payload you have given:
```
{
    "name": "Jhon",
    "extras": [
        {
            "skill": "Programming"
        },
        {
            "hobby": "travelling"
        }
    ]
}
```

In order to use this in mock's dynamic response, you can access the value of `hobby` object with this notation `$body 'extras.1.hobby'` instead of `$body 'extras[1]hobby'`.

If you save the example response below, you could get the response you require.
```
{
    "greet":"Hello, {{$body 'name'}} Nice to Meet You!.",
    "Extras": "{{$body 'name'}} likes {{$body 'extras.1.hobby'}}"
}
```

Here is the saved example:
![Screenshot 2024-09-02 at 12 11 45 AM](https://github.com/user-attachments/assets/c068cc60-8111-40d3-8621-321442ca8bb9)

Here is the request and corresponding response from the mock server:
![Screenshot 2024-09-02 at 12 11 22 AM](https://github.com/user-attachments/assets/b1be2467-9f42-4e82-b7ca-6f715bfd5a5f)



I think there is a usability and UX gap on how to use nested JSON with dynamic mocks. We will add this going forward. With the above answer we hope, we have addressed your concerns. If you have any further questions, please feel to reopen this ticket.

**Comment by adinath-nikam** [comment]
Hey @sony-mathew 
Thank You for Letting me know about this method of accessing the values
i was not knowing this method and also i think there is no any documentation on this same.

Thank You!
