### ISSUE TITLE
Does the latest version being hacked?

### ISSUE THREAD

**Issue by cexopgy** [a85/POSTMan-Chrome-Extension#12715]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when i nmap my server ,postman started a port 15611, run a websocket service ( ogar [agar.io](http://agar.io/) server)(game server?)
http:// IP:15611 display upgrade required
is this OK? previous version no this .
![20240315114620](https://github.com/postmanlabs/postman-app-support/assets/49268079/bb3e49f9-e567-4c37-b2ff-1cb813384a3a)
![20240315114651](https://github.com/postmanlabs/postman-app-support/assets/49268079/29dba9d8-ebe0-45ac-92cb-6df761e54214)
![20240315114833](https://github.com/postmanlabs/postman-app-support/assets/49268079/20bdd896-300c-458e-a7e1-fa57b77b0398)

### Steps To Reproduce

1.open postman
2.check the port and service

### Operating System

Windows

### Postman Version

10.24.3

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by VShingala** [comment]
Hey @cexopgy, Thanks for reporting the issue. This websocket server is being created by Postman for usecases related to [Postman Interceptor](https://chromewebstore.google.com/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo). It can be used to capture requests from browser to Postman app via this WebSocket server. This is also a local interface with encrypted messages and communication on this server should not be happening until Postman Interceptor extension is installed.

ATM, this websocket server is created upon Postman App start. We'll make changes in future version so that users can disable this server from setting if they do not wish to use the Interceptor feature. And also, provide more details around what this server does.

**Comment by cexopgy** [comment]
OK
