### ISSUE TITLE
Package Library works on web but not on desktop app

### ISSUE THREAD

**Issue by dmturn364** [a85/POSTMan-Chrome-Extension#12835]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I created a simple package library following the steps in the documentation (https://learning.postman.com/docs/writing-scripts/package-library/#write-code-in-a-package). While I am able to import and use this package on through the web, I am unable to get the external package to work from the desktop app. I keep getting a response back stating `There was an error in evaluating the Pre-request Script:Error: Cannot find package '@<teamName>/<packageName>'`

I have upgraded to the most recent Postman version 11.0.6 but the "Desktop Platform Version" is showing 11.0.4.

### Steps To Reproduce

1. Create a new package library and save for the team
2. Import your package in a pre-request or post-response script
3. Call the exported function from the package library.
4. Send request to trigger script.
5. From the web, the package library works. Through the desktop app, it returns the error.

### Operating System

Windows

### Postman Version

11.0.6

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by postfrzero** [comment]
Hey folks -- We've released v11.0.7 with a fix. This issue affected users running Windows, and was causing package resolution to fail during execution. Sending requests, running collections, and executing flows should all work correctly now.

**Comment by jgarciadelanoceda** [comment]
Hello @postfrzero.

I have implemented through a shared collection of our collection the Package Library and I like it very much.

But there are some members of my team that find that pm.require is not a function.

In fact if they go to the section of scripts they do not find the Package Library there.

The web works for them.

If you need another issue I can create it, but I found it very similar to this Closed issue

**Comment by postfrzero** [comment]
Hey @jgarciadelanoceda -- Packages and the Package Library were introduced in v11 of the Postman app, and older versions of the app will not be able to execute requests which use this capability. I suspect that the members on your team who are running into the `pm.require is not a function` error may be on older versions. If so, then resolving the issue is only a matter of upgrading the app. If that's not the case, then yes, another ticket with all of the meta information (app version, platform, etc.) and available details would be super helpful!

**Comment by exc304** [comment]
I have a use case where my package library was working when on the free version of Postman, so I am familiar with creating and using the packages.
Now that I'm on an Enterprise version where I created a package library, I'm seeing that it cannot find package when running a collection. 
![image](https://github.com/user-attachments/assets/b05bc03c-64b8-4550-b311-31aa0b463592)
![image](https://github.com/user-attachments/assets/a50cc6cb-1a3e-4eb0-8281-9a06aed132b8)

Running a request individually results in the package being found and test results are good.
![image](https://github.com/user-attachments/assets/dffc5220-35b3-4257-9f55-e635f2a686fe)

It's also weird because if I search packages, it finds it but I cannot select it (like it's hidden). 
![image](https://github.com/user-attachments/assets/52880461-af74-4a01-a11d-521091ad0697)

any guidance here would be appreciated. 🙇🏻‍♀️
