### ISSUE TITLE
Display tabs in multiple rows

### ISSUE THREAD

**Issue by guitar-freq** [a85/POSTMan-Chrome-Extension#12849]
### Is there an existing request for this feature?

- [x] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

I have many tabs open and it would a great help to view the tabs in multiple rows (like in my text editor) instead of scrolling a very long single row of tabs. Doing this would allow for considerably easier navigation.

**Comment by guitar-freq** [comment]
Something like my editor does:
![image](https://github.com/postmanlabs/postman-app-support/assets/8649513/1cb5f325-b462-4f5f-9b59-589f563b2ca4)

**Comment by gzhegow1991** [comment]
Not sure its a good thing to open tonns of tabs, you're need only few tabs at a time, others its just opened accidentally/old.
As a personal point - could be.
Instead i'd recommend to implement to separate `column` with opened tabs limit feature and autoclose "unchanged"/"untouched" (mode toggle)... Just dive Jetbrains experience for understand what i mean.
By clicking RMB on tab you can open "Configure editor tabs" dialogue and all of these features is important.

**Comment by Harsh1796** [comment]
Hey @guitar-freq thanks for your feedback! 

While a multi-row tab view is currently unavailable, our tab search feature offers a powerful alternative for simplifying navigation and streamlining tab management.

Tab search provides:
- **Vertical tab list**: Easy scanning through all open tabs.
- **Search function**: Quickly find tabs by keywords.
- **One-click access & close**: Switch and close tabs directly from search results.


https://github.com/postmanlabs/postman-app-support/assets/25709855/bd5d5106-dd30-485d-9411-b33701d28acb

Let me know if this suggestion works for you. Thanks!

**Comment by gzhegow1991** [comment]
@Harsh1796 

let me explain you something.
if you ask people to use mouse instead of hotkey - you do UI worse than it could be
if you ask people to use mouse to open field that requires using keyboard with - you do UI worse than it could be
if you forcing user to wait 0.5 seconds on close every tab - you do UI worse than it could be

Let me display an example. The Windows OS has internal search inside "start menu" in old versions. people NEVER use that stuff. nobody, nowhen. But.... Once same feature could be enabled by simple keypress "Win" key or single click "Start" button and you already can WRITE text without more clicks, and see results just in time - it becomes must have to use. Same feature. Different UI.

its not just idealistic speaking. beeing a programmer every mind and idea i've catched is trying to get away from my brain. i try do it as much faster until it exists. any external action increases posibility to forget what i want from it. Thats the main reason.

the point - create as much small count of buttons that is enough clever to do required actions instead of create button and field for each possibility in the app

its like dialogue about "do you need pagination for pages 1-2-3? yes". do you need pagination for pages 10001-10002-10003? no, user never click it.

just think about why REST-api is bad but RPC-api is better. REST tries to create tonns of useless features, RPC is focused on one complex required feature. REST is died. RPC alive was, and alive now.

**Comment by guitar-freq** [comment]
> Not sure its a good thing to open tonns of tabs, you're need only few tabs at a time 

Thanks for your reply but it's what I want to make my work style more efficient.

**Comment by guitar-freq** [comment]
> Hey @guitar-freq thanks for your feedback!
> 
> While a multi-row tab view is currently unavailable, our tab search feature offers a powerful alternative for simplifying navigation and streamlining tab management.
> 
> Tab search provides:
> 
> * **Vertical tab list**: Easy scanning through all open tabs.
> * **Search function**: Quickly find tabs by keywords.
> * **One-click access & close**: Switch and close tabs directly from search results.
> 
>  TabSearch.mp4 
> Let me know if this suggestion works for you. Thanks!

Thanks for your reply. It's just how my visual brain works that I'd like to see tab rows. The vertical tab list is an improvement for sure.

**Comment by rhyssleary** [comment]
An alternative feature that would be just as good for me would be to allow multiple instances of Postman to launch.
