### ISSUE TITLE
Vault messing with Jwt Token

### ISSUE THREAD

**Issue by tylndemirci** [a85/POSTMan-Chrome-Extension#12912]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello, I'm using a script to automatically get the "token" from the response of an endpoint and set it as environment value. Normally, I would just send request to the login endpoint and get my token, after that i can easily send request to other endpoint.

The problem started after I saved some of my username and passwords into the Vault. Since then, I couldn't send request to any of our endpoints because the token was always seen masked in some parts.

After many trials, I figured out that what Vault was doing is just looking for everything that contains the value I saved, whether it is plain or base64 encoded, and masking it. In my case, it is email that Vault finds in token as base64 format and masking it.

I believe it is a problem because token is being unusable and if the problem is with the security, I can already see the data from the body of the response, so there is no point this data is being masked in environment.

### Steps To Reproduce

1. Save some value to the Vault.
2. Get base64 encoded version of the value from the response of an endpoint.
3. Save it to the environment.
4. See the data is not masked in response body, but in environment.

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/60180444/966b5cee-fc05-4aed-815d-a58d920fd201)

You can also see the same things when logging.
![image](https://github.com/postmanlabs/postman-app-support/assets/60180444/ff46c61d-c7e7-4ee6-bfff-7f097e0cde23)
![image](https://github.com/postmanlabs/postman-app-support/assets/60180444/056af144-b093-4c24-83aa-6ac00aa6b761)

### Operating System

Windows

### Postman Version

11.1.14

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

During my tests, i realized variable names in the environment is also being masked, but I don't believe it is a problem.

**Comment by theonly1me** [comment]
Hi @tylndemirci, thanks for creating this issue, the vault secrets are not masked in the response on purpose, since the response would depend on the users' server and users also may be using an Echo API that echos whatever is sent to it etc. 

As for the secrets getting masked in the scripts, we are currently working on a fix. In the meanwhile, you can disable masking of vault secrets via the `Settings` in your Postman Vault.

1. Click on the `Settings` button from your Postman Vault
![Screenshot 2024-06-03 at 3 54 44 PM](https://github.com/postmanlabs/postman-app-support/assets/19223383/66b924a4-2ccf-495e-a426-22f56cadae5f)

2. Disable the `Mask vault secrets` option
![Screenshot 2024-06-03 at 3 57 06 PM](https://github.com/postmanlabs/postman-app-support/assets/19223383/11b1abac-2701-4d99-868b-75d05dc11ae0)

**Comment by tylndemirci** [comment]
Hello @theonly1me, that option also fixes my problem with the environment. Thanks for help. 💯

**Comment by theonly1me** [comment]
Hey @tylndemirci, the fix for this is out with v11.2 of Postman. Once you update your app, you will no longer need disable `Mask vault secrets` option to prevent masking of values & base64 representations of vault secrets in scripts.
