### ISSUE TITLE
Later versions than 11.2.34 causes "There was an error in evaluating the Pre-request Script:Error: sandbox: execution interrupted, bridge disconnecting." error

### ISSUE THREAD

**Issue by Buyukcaglar** [a85/POSTMan-Chrome-Extension#13030]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Any later version other than 11.2.34 (regardless of OS) causes "There was an error in evaluating the Pre-request Script:Error: sandbox: execution interrupted, bridge disconnecting." on every single request, in our collection. 
When we revert to 11.2.34 our collection runs as usual.

### Steps To Reproduce

This happens on our currently working private collection and we are willing to open it to postman support team to track and find the issue.

### Operating System

Windows

### Postman Version

11.5.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by codenirvana** [comment]
@Buyukcaglar can you share a scaled-down collection (or email us at [support@postman.com](mailto:support@postman.com)) that we can use to reproduce this issue locally?

**Comment by designbymind** [comment]
Hey guys, I am experiencing the exact same error. None of my environments, collections, or requests use Pre-request script(s) but every single request (around 80 in total) in the entire collection is producing the error below. Just updated to Postman `11.6.2` and PostmanCanary `11.2.14-canary01` today with the same result. This has been happening for a few releases now. **Note:** this error also happens when using the web-based Postman but not when using the Postman VS Code extension. — Going to attempt to rollback to `11.2.34` as @Buyukcaglar suggested. I just really want my Postman desktop client back. **Thank you** for looking into this 🙂

macOS `14.5` (M1)
**Error:** "`There was an error in evaluating the Pre-request Script:Error: sandbox: execution interrupted, bridge disconnecting.`"

**Comment by designbymind** [comment]
**Update:** this may sound strange, but I have no idea when Postman updated to `11.7.0` on my machine as I updated to `11.6.2` like an hour ago, but magically I am now running `11.7.0` and the error is gone, all is working as it should. — Thanks to whomever fixed it and to the invisible force that installed it on my machine 🪄

**Comment by Buyukcaglar** [comment]
Hi,
Yes I can confirm that the problem has been solved with the release of version 11.7.0 and our collection works fine as is before.
Thanks for the support for taking their time to investigate and solve the issue.
Cheers,
