### ISSUE TITLE
When will HTTP2 and HTTP3 be supported in Postman?

### ISSUE THREAD

**Issue by Soundman32** [a85/POSTMan-Chrome-Extension#13061]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Related to this question in the help: https://community.postman.com/t/http2-support-for-rest-endpoints/11365

HTTP/2 has been around since 2015, and HTTP/3 since 2022.

When will Postman support these newer protocols?

### Describe the solution you'd like

I'd like Postman to support the newer protocols.

**Comment by DSchau** [comment]
Hey @Soundman32! Thanks for opening this. Without revealing too much... 🔜 (very!).

Since this is somewhat duplicative of an already open issue (#2701), I'm going to close in favor of that open issue so we can consolidate discussion.

I will note that we don't have plans to support HTTP/3 as of this time but please use the HTTP/2 issue above in order to add any additional context as to what you'd like to see in HTTP/2 and potentially HTTP/3 support.

Thanks!
