### ISSUE TITLE
windows 11 postman v11.16.1 not capture Coockies or sync cookies when tests with interceptor on both Firefox Or Chrome (last updates) when extension is full Enabled

### ISSUE THREAD

**Issue by wwwbarnamehadotnet** [a85/POSTMan-Chrome-Extension#13201]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi, i am doing try to capture requests,cookies and etc  with postman last version desktop version and interceptor installed enabled on chrome and firefox(downloaded from postman website)  but still sync cookies or get coockies in capture not work yet.
I did try for follow instructions about how it works but still not work.

i guess there is a bug on windows 11 and this last version.

### Steps To Reproduce

-

### Screenshots or Videos

![001002](https://github.com/user-attachments/assets/4483dca9-2820-4064-9f4a-f768ed350ea9)

### Operating System

Windows

### Postman Version

11.16.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by wwwbarnamehadotnet** [comment]
?

**Comment by aman-v-singh** [comment]
Hey @wwwbarnamehadotnet,
I have some suggestions for you:-
- Please make sure that the "Capture Cookies" configuration is enabled in the Postman App on the Interceptor Debug Session tab.

<img width="1135" alt="Screenshot 2024-10-24 at 11 53 31 AM" src="https://github.com/user-attachments/assets/f9dcd9ef-0429-4105-855a-c665270b69f8">

- Check if "Syncing to Postman Cookie Jar" is showing on the "Sync Cookies" tab of the Postman Interceptor after you click the "Sync Cookies" Button.
<img width="467" alt="Screenshot 2024-10-24 at 11 57 13 AM" src="https://github.com/user-attachments/assets/0fc5af22-f7a9-4379-b771-2305175dbfd1">

- Ensure the Requests are intercepted in the Postman app's Interceptor Debug Session tab.

- Ensure that the Postman App shows your Interceptor as connected in the Sync Cookies tab in the Cookie Jar.

<img width="1288" alt="Screenshot 2024-10-24 at 12 17 58 PM" src="https://github.com/user-attachments/assets/4f04abbe-62ed-426f-b73e-714ae14fa19a">

Please read this for further [reference](https://learning.postman.com/docs/sending-requests/capturing-request-data/syncing-cookies/#sync-cookies-from-the-interceptor-extension).


If these steps don't fix the problem, please inform us so that we can further look into the issue.

**Comment by aman-v-singh** [comment]
@wwwbarnamehadotnet, I am closing this issue as the issue could not be reproduced, and I have suggested solutions to help you with your problems.
Please feel free to comment/reopen the issue if you face further problems.
