### ISSUE TITLE
How to improve JSON formatting in Postman extension for VS Code?

### ISSUE THREAD

**Issue by SaidAlHendi** [a85/POSTMan-Chrome-Extension#13259]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm using the Postman extension in Visual Studio Code to test my API endpoints. When I send a request and receive a JSON response, the data is displayed in an unformatted, "ugly" structure, making it hard to read (see screenshot below).

I've tried switching to the "Pretty" view, but it doesn’t seem to improve the formatting. 

### Steps To Reproduce

Are there any settings in the Postman extension for VS Code to improve JSON formatting? Or are there alternative ways to display the response in a readable, structured format directly within Visual Studio Code?

Any help would be appreciated!

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/6731a6db-eab9-48b9-bbcd-d7471b6e7065)

### Operating System

Windows

### Postman Version

idk

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by indraneel-postman** [comment]
@said96dev 
This issue is happening due to an internal change in VSCode from v1.95.1 onwards. There is already an issue for tracking this and we have raised a bug with Microsoft team as well. Refer to this comment for more info-
https://github.com/postmanlabs/postman-app-support/issues/13230#issuecomment-2458788661

Closing this as duplicate.
