### ISSUE TITLE
Response Body not 'prettified'

### ISSUE THREAD

**Issue by NRP7** [a85/POSTMan-Chrome-Extension#13264]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

My Postman user interface is having formatting issues. The JSON response body I receive displays non-formatted text despite being set to the "Pretty" option.

### Steps To Reproduce

1. Open the Postman VSCode extension.
2. Create a dummy request with a JSON response body.

### Operating System

Windows

### Postman Version

1.4.1

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by agas0077** [comment]
Same issue. Downgrading down to 1.0.0 doesn't help.

**Comment by admin-lafarga** [comment]
It's happening to me also with version 1.4.1 & to my coworker

**Comment by indraneel-postman** [comment]
Hi,
This issue is happening due to an internal change in VSCode from v1.95.1 onwards. There is already an issue: https://github.com/postmanlabs/postman-app-support/issues/13230 for tracking this and we have raised a bug with Microsoft team as well. Refer to this comment for more info-
https://github.com/postmanlabs/postman-app-support/issues/13230#issuecomment-2458788661
