### ISSUE TITLE
Uploading collections not working

### ISSUE THREAD

**Issue by jrichard0725** [a85/POSTMan-Chrome-Extension#1369]
When clicking the share icon, then clicking on upload and get link, nothing happens.

Logging in to getpostman.com does not show my uploaded collection either.

Going to "My Collections" then clicking upload all does nothing either. No action/spinner nothing.
![screen shot 2015-08-24 at 1 59 20 pm](https://cloud.githubusercontent.com/assets/5215492/9450863/6215d956-4a68-11e5-8a9d-7a002aa9331e.png)
![screen shot 2015-08-24 at 2 00 07 pm](https://cloud.githubusercontent.com/assets/5215492/9450878/73310d82-4a68-11e5-949d-a279fb38aef2.png)

**Comment by abhijitkane** [comment]
Can you try signing out and signing in? There's an issue with the refresh token which we'll be fixing in the next release.

**Comment by jrichard0725** [comment]
That fixed it! Thanks. Can't wait for the update. :)

**Comment by Mahesh49** [comment]
I'm still facing this issue, last successful update was couple of days ago. Since then nothing gets updated. I even removed the collection from 'Uploaded' tab on website. 
I tried using 'Upload all' and 'Upload and get a Link', nothing seems to be working. 
I am using the link for my automation tests, the previous link is not working as I have deleted it and I am unable to upload to get new link. 
Any help would be appreciated.

**Comment by abhijitkane** [comment]
@Mahesh49 Are there any errors in the console (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/) when you click the 'Upload and get link' button?
Can you try signing out and signing in?

**Comment by Mahesh49** [comment]
@abhijitkane 
I can see there is console error after clicking 'upload and get Link'
and also 'Upload All' . 
![upload error](https://cloud.githubusercontent.com/assets/8543532/10537160/d6404746-73e7-11e5-8e69-cba05e7ca4bd.PNG)
I tried signing out and signing in too, and it didn't  help. 

If it helps for you , Sync functionality works fine., the problem is with Upload.  
Any help would be appreciated.

**Comment by abhijitkane** [comment]
How many requests do you have in your collection? Can you try splitting it up into 2 or more collections?

**Comment by Mahesh49** [comment]
I have around 130 requests and will be growing. 
If I split them in in two, then i guess I've have problem maintaining automation build as i need to run two collection urls and it generates two reports. 
It it helps the collection i have is 2.5 MB in size. 
I like to keep it in single collection ideally.
