### ISSUE TITLE
Slight major issue

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1410]
I've been in Postman since 8am. A little while ago, the Connecting icon was spinning endlessly so I quit then restarted Postman. When I clicked on Collections, all of my folders are gone! I've restarted Postman to no avail.

There are only 36 requests but I'd like to get my folders back and have the requests put back into those folders.

**Comment by sobtiankit** [comment]
@A570343 You can verify the state of your collection on the website. If you're on the team sync beta, you'll find it at https://beta.getpostman.com/profile/collections, otherwise at https://getpostman.com/profile/collections under the Synced section in the collection.

One you verify your collection is in the expected state, hover over your collection in the Postman app, click on the 3 dots, click on share and click on Resync Collection. This should restore all your folders.

**Comment by A570343** [comment]
My Collections are on the dashboard but I don't see the 3 dots when I hover over the collections; I've tried using Chrome and IE.

![collections](https://cloud.githubusercontent.com/assets/13588309/9635080/8fa437c2-5162-11e5-836a-10516ca541bd.PNG)

**Comment by sobtiankit** [comment]
Ah sorry I wasn't more clear. Return to the Postman app and hover over the collection in the left sidebar to see the 3 dots.
<img width="2304" alt="screen shot 2015-09-02 at 8 47 43 pm" src="https://cloud.githubusercontent.com/assets/547061/9635421/0741c500-51b4-11e5-8fa4-e09c770f3df0.png">
<img width="2304" alt="screen shot 2015-09-02 at 8 47 48 pm" src="https://cloud.githubusercontent.com/assets/547061/9635422/077445a2-51b4-11e5-9e84-19ccb6f83a5c.png">

**Comment by A570343** [comment]
Ahh, that worked thx.

My other main concern is the fact that when the app couldn't establish a connection, it lost the folders. Is this something you're working on and if not, can you plz mark this as a bug.

**Comment by sobtiankit** [comment]
Happy to help.

Actually it doesn't have anything to do with the lack of connectivity. Unfortunately, sometimes, the app fails to load some content from the local app db. What you just did, also rerenders the content after comparing it with the server. 

We are already looking into this and will fix it very soon.
