### ISSUE TITLE
Non-Querystring URL param that is not the whole /segment/

### ISSUE THREAD

**Issue by anuith** [a85/POSTMan-Chrome-Extension#1420]
About the URL segment feature. Which we can set non-querystring parameter like this
`http://{{host}}/api/:key/:id`

I would like to suggest a change. To make it be able to set parameter that is not the whole segment (enclosed with `/`). Since there are some framework/service that allows using parameters that way.

example an api that accepts : `http://{{host}}/api/key-keyhere/id123456`
which inside Postman could be like this : `http://{{host}}/api/key-:key/id:id`

**Comment by shamasis** [comment]
IMHO: You should be using normal variables instead.

URL variables should remain in segments. We have plans to actually merge the concept of these variables with our normal variables.

**Comment by mtwomey** [comment]
@shamasis I don't fully understand the answer here - this seems like a good  sensible enhancement. I also have vendor APIs for which I can't use segment variables because of this limitation. I don't want to go through the steps to update an env variable each time when I want to test several IDs in a row (this segment functionality is perfect for that).

In addition - the code output already does this. I can grab the curl statement from Postman and the segment variable substitution is correct - even for variables that are "not the whole /segment/". So why not make it consistent and add the feature?
