### ISSUE TITLE
Auto generate PostMan request names from swagger?

### ISSUE THREAD

**Issue by tforster** [a85/POSTMan-Chrome-Extension#1434]
I'm relying heavily on PostMan and Swagger, both amazing tools for rapid API development. My workflow typically sees me writing new API endpoints in Swagger then importing the JSON file into PostMan for testing. However, the default import behaviour is to name the request in the left column the same as the request itself. I could manually rename but every time I re-import my latest iteration everything gets reset (as expected). 

Would it be possible to support a swagger x-param that could be used to define both the PostMan request name as well as its description?

**Comment by abhijitkane** [comment]
Absolutely! We're working on providing Postman-specific attributes "x-postman-meta" or something similar that will allow overriding auto-generated attributes like name/description etc. This will be common across Swagger, RAML, WADL files that are imported into Postman.

I'll update this thread when we have something more concrete.

**Comment by jackrk** [comment]
Any docs on x-postman-meta extension?

**Comment by bruno-lopes** [comment]
Very interesting. Waiting for it.

**Comment by mikeder** [comment]
@abhijitkane is there any update on this? I would like to leverage an "x-postman-meta" key to embed Postman related test data.

**Comment by StefNewton** [comment]
The x-postman-meta extension is included in the Swagger document that is generated when exporting with Postman extensions from the AWS APIGateway. I can't for the life of me find documentation or any mention of this extension outside of this one feature request. Is there documentation out there that I am missing or any other updates regarding this feature?

**Comment by rathodamol** [comment]
any updates on this issue?

**Comment by okachobi** [comment]
I tried a swagger v2 import, and this is still an issue.  Had to use a third party converter to properly get labels for the various routes.

**Comment by chrisgl** [comment]
I have the same Problem. I want to use Postman to use a Swagger File, but the missing names for the requests make the created collection hard to use.

Instead of using a special parameter, I would suggest to use things already there.
By default I think it would be a good idea to use the path:
"http://petstore.swagger.io/api/pets?tags={{tags}}&limit={{limit}}" -> Name: "/api/pets"
Or even include the Query string.
That alone would help a lot.

Additionaly there is the "operationId" per Operation which should be a good fit
The current script uses "summary" as the name for the request, as I found out.

I would suggest using the "operationId" as the name, if available. Else the "summary", if available. And as a general fallback the path.

I think this would be a good first attempt, because no names is not helpful.

A link to an example with operationId available:
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-expanded.json

Edit:
Looking at the source of this: https://github.com/postmanlabs/swagger2-postman2-lambda
The script currently uses the field "summary" for the name.
Not the best choice in my opinion, but I successfully changed my swagger generation to produce this field and now I have names. Although I think "operationId" is a better fit.
I edited the suggestion to include this field.

**Comment by a85** [comment]
Postman will adopt a plugin based approach to import/exports. We are decoupling importers and code-generators from the main Postman app so these can be shipped independently. Plug-ins can cater to individual tastes or preferences. All plug-ins that Postman has authored are open-source and are available on GitHub. For example here: https://github.com/postmanlabs/openapi-to-postman

**Comment by DuGites** [comment]
> I tried a swagger v2 import, and this is still an issue. Had to use a third party converter to properly get labels for the various routes.

What third party converter did you use?
