### ISSUE TITLE
Breakpoints in collection runner

### ISSUE THREAD

**Issue by AdrianAulbach** [a85/POSTMan-Chrome-Extension#1460]
It would be nice to be able to set a breakpoint in a collection so you can run the remaining requests manually while debugging.

**Comment by nildowjunior** [comment]
This would be great.
Any chance of it happens soon?

**Comment by a85** [comment]
Pausing a collection run has been supported for a while now. Closing this.

**Comment by maxp-edcast** [comment]
Does this apply to the standalone OSX app or just the Chrome app? If there is a way to set breakpoints in the standalone app the same way as it's possible to do in the browser (e.g. the `debugger` keyword), can anyone please advise on how to do it?

The reason we use the standalone app as opposed to the Chrome app is because the Chrome app does not support the [test scripts library](https://www.getpostman.com/docs/postman/scripts/test_scripts)

If I am wrong about any of this please let me know. I am not a QA engineer myself but am asking on behalf of my colleague with the information he's given me.

Best regards!
