### ISSUE TITLE
Do not save (authentication) headers

### ISSUE THREAD

**Issue by Mattie112** [a85/POSTMan-Chrome-Extension#1463]
We use HTTP Basic Auth for (most of) our webservices, we'd like to share our collections with other people (either colleagues or 3rd parties). However we do not want to share credentials in all cases (because the 3rd party needs to use his own login for example)

So:
I found out I can use {{var}} in the "Authorization" section, this is also saved by the helper data. However when saving the basic auth header will also be saved and because this is base64 it can be converted back.

Is there a way to "not save basic auth header"? So I can have the other people simply use {{user}} and {{pass}} without having the authentication saved in the collection?

**Comment by abhijitkane** [comment]
@Mattie112 You can save the request to the collection before generating the signature.
Remove the Authorization headers from the request, make sure the 'Save helper to request' checkbox is selected in the Auth tab, and then save the request. You'll need to ensure that you remove the header before you save the request.

**Comment by Mattie112** [comment]
Hi,

Thanks for your reply. That is exactly what I am doing now, however when having like 100 requests it is a pain-in-the ass to remove all the headers. For instance: I've updated some code and 25 requests need to be updated. To be sure I run the entire collection. All my 100 requests will now have a basic auth header. If I want to share the collection I'll need to manually (or at least I did not find an auto-way) remove the authentication header again.

So that is why I'm asking: is there a way to not save the (authorization) headers but regenerate them for every request?

**Comment by abhijitkane** [comment]
There's currently no way to not save headers in the requests you save. (URL, Headers, Request Body are always saved)

To remove headers from requests you've saved earlier - you have two options:
1. manually delete the headers from each request and then save the request
2. export the collection file, and use a regex to remove all instances of "Authorization: xyz"

**Comment by Mattie112** [comment]
Yes that is also a possibility. But if that is the case consider this issue as a feature request :)

**Comment by hasmanyguitars** [comment]
I would love this feature as well.

**Comment by mawalu** [comment]
I know this is an old issue but I just found it because I was looking for exactly this feature. Would absolutely love it as well :)

**Comment by percyhanna** [comment]
This is a serious security bug. I just discovered that exporting the collection will export the `Authorization` headers that were loaded from the environment file. I am using "Basic Auth" in the "Authorization" tab, and the "generated" Base64 username/password header is saved to the request itself. Upon export, my actual user credentials are exposed in plain Base64 text in JSON. This is an insane security risk and makes sharing collections extremely tedious.

**Comment by shamasis** [comment]
@percyhanna that is the reason why we recommend using environment variables to store sensitive info and refer to it from your requests. 

1. You could save username password and use it in auth helper (take care to not accidentally save the header back in the request!)

2. Alternatively, store the value of authorisation header in environment variable and refer to it directly from saved header.

**Comment by percyhanna** [comment]
I _am_ using environment variables to store sensitive information, however my `Authorization` header is being saved to the request.

**Authorization configuration:**
<img width="1348" alt="screen shot 2016-12-14 at 1 51 51 pm" src="https://cloud.githubusercontent.com/assets/125077/21200500/b2f17ab4-c204-11e6-9b2d-d735e140452c.png">

**Request headers:**
<img width="1344" alt="screen shot 2016-12-14 at 1 51 56 pm" src="https://cloud.githubusercontent.com/assets/125077/21200511/bf095ad8-c204-11e6-8fe7-26779351964c.png">

Every time I send the request, it adds the `Authorization` header if it doesn't exist. It's also adding it with the encoded/serialized values, thus exposing my credentials. If I don't check off the "Save helper data to request" box, then I can't save my configured `{{user}}` and `{{password}}` entries that load from my environment.

As a user, I would like to be able to use the Authorization "helpers" in combination with environment variables, without exposing/saving my credentials to the request itself, so that my user credentials are not exposed unexpectedly.

**Comment by percyhanna** [comment]
If the "Authorization" tab can't "extend" the request without saving credentials to the actual request, then I would strongly suggest removing the tab altogether given the massive security risk it exposes.

Another option would be to force an **_opt-in_** to include `Authorization` headers when exporting a collection to JSON.

**Comment by slchorne** [comment]
yes, add another request to strip these headers from the export.
it is a messy security risk and means we can't share collections anymore.

**Comment by sdnts** [comment]
Guys, we're working on streamlining this workflow so problems like these do not occur.

The workflow I have in mind meanwhile is:
1. Populate the auth helper in question with environment variables instead of actual values.
2. Save your request (Do not hit `Update Request`, or else an Authorization header would be generated)

This way, the auth header isn't ever saved with the request, so exporting the collection should not (indirectly) expose any secrets.

As I said though, work on streamlining this is underway.

**Comment by percyhanna** [comment]
I'm not sure I completely follow the proposed flow, but to me the acceptance criteria would be:

1. I can use the authentication tab to easily configure authentication for my requests.
2. I can use environment variables in the authentication tab.
3. The generated authentication header value is _NEVER_ saved to the request. It is calculated at run-time and injected as part of the request delivery process, not added to the original request object.

**Comment by shamasis** [comment]
Yes. That's in line with our views. Presently the the first two points are exactly what @madebysid suggested. The deviation is in third point and to avoid that, ensure that you remove the authorisation header before saving the request.

**Comment by jamesyarrington** [comment]
I agree with @percyhanna 's 3rd point.  For me, the auth header is generated whenever I make the request, even if I do not click the "Update Request" button.
This means that if I've used a request and saved it, it will have the generated auth header when I export it.
This is annoying to deal with.  I would appreciate a workflow that offers an option to opt-in/out of saving auth headers (or never), rather than having to remember to remove it for each request before exporting.

**Comment by shamasis** [comment]
+1 we hear you.

**Comment by percyhanna** [comment]
> The deviation is in third point and to avoid that, ensure that you remove the authorisation header before saving the request.

I just want to clarify this point you made. This is what we _currently_ have to do in order to prevent exposing authorization headers. I hope the solution will not require us to do this in the future?

**Comment by xhdong-umd** [comment]
I tried to remove the header, update the request then export the collection. However there are still some basic header saved in the json. I have the original collection with header, and a duplicate collection that removed headers. I suspected that it was caused by the same name api calls in the original collection, so I removed the headers in the original collection too. Then I still found some header in the exported collection.

At last I gave up and just replaced them.

**Comment by andrewfraley** [comment]
Another vote to at least warn about this or provide a pop-up asking if you want to include the credentials when exporting.  I almost shared pretty sensitive credentials and thought to look at the exported json first.

**Comment by kimsaabyepedersen** [comment]
+1 for this

**Comment by Dunmail** [comment]
+1

**Comment by madrian** [comment]
A workaround is to save the whole Authorization value in the environment variable. So your saved collection would look like **Authorization**: {{myauth}} and in your environment **myauth** = "Basic xxx".

**Comment by Dunmail** [comment]
@madrian: Agreed - this is what we're doing.

However, when we share a Postman collection with third-parties, it would be more satisfactory to share a username/password, rather than the whole header

**Comment by mikob** [comment]
I feel the authorization shouldn't be a tab in the requests, next to headers, body etc. Alternatively, Authorization could be set on the collection level -- "Authorize collection"? From there the user could decide what variables to store the output of authorization into -- bearer token, or username, password etc.  In my case I would store the bearer token generated via oauth2 into a `bearer_token` variable that I in turn could use in the headers field of my requests. I agree on the points above that is shouldn't be included in a collection's json. If the section was separated as I've described it would be clearer from UX perspective that it's not a normal part of the collection json that gets shared and rather a helper that lets you populate variables that you in turn use in the collection safely.

**Comment by harryi3t** [comment]
The fix will be released with Postman 5.3 in the next couple of days
From now on, sending a request will not add any header to the request. It will be shown as temporary headers in the App.
It will look something like this
![image](https://user-images.githubusercontent.com/5207331/31214615-9a8e69fc-a9c9-11e7-95ed-f9135d6a94ec.png)
![image](https://user-images.githubusercontent.com/5207331/31214625-a1207a62-a9c9-11e7-9881-1e729b308b63.png)

**Comment by kamalaknn** [comment]
Hi all,

This enhancement is out in `5.3.0` version of Postman. In this version `Authorization` headers generated by Postman are not saved with the request. Also, all the data in the `Authorization` tab is saved by default with the request.

For requests saved in the older versions, you may have to manually remove the `Authorization` headers or any headers/params added by Postman. Rest assured Postman will not add these headers/params starting from `5.3.0`.

Have a good day.

**Comment by rafiron** [comment]
Wouldn't it be better to have a configurability somewhere in the app for this feature. For a lot of folks definitely this feature will be useful. But I many times also use postman to quickly compose curl requests which also require to add auth headers.

Forcing it as temporary header prevents it from coming in the curl request body being composed by postman. 

It would be much better to have a configurability for the same (with default being set to using this feature for better security). So that folks who want to add the headers as part of their requests can do so (maybe for documenting with a dummy auth header or any other use case).

**Comment by rafiron** [comment]
Wouldn't it be better to have a configurability somewhere in the app for this feature. For a lot of folks definitely this feature will be useful. But I many times also use postman to quickly compose curl requests which also require to add auth headers.

Forcing it as temporary header prevents it from coming in the curl request body being composed by postman. 

It would be much better to have a configurability for the same (with default being set to using this feature for better security). So that folks who want to add the headers as part of their requests can do so (maybe for documenting with a dummy auth header or any other use case).

**Comment by rafiron** [comment]
Wouldn't it be better to have a configurability somewhere in the app for this feature. For a lot of folks definitely this feature will be useful. But I many times also use postman to quickly compose curl requests which also require to add auth headers.

Forcing it as temporary header prevents it from coming in the curl request body being composed by postman. 

It would be much better to have a configurability for the same (with default being set to using this feature for better security). So that folks who want to add the headers as part of their requests can do so (maybe for documenting with a dummy auth header or any other use case).
