### ISSUE TITLE
POSTMAN beta keeps crashing

### ISSUE THREAD

**Issue by gaurish** [a85/POSTMan-Chrome-Extension#1523]
Using [POSTMAN Beta](https://chrome.google.com/webstore/detail/postman/loddepljkabcghihdkbkfknabkinanff), it crashes as soon as I launch. I know this is not full information for you to debug. so let me know what/how I can more information.

**Comment by abhijitkane** [comment]
Can you provide your OS version, Chrome version, and the version of the Postman app you are using (you can find this in chrome://extensions).

Can you try reinstalling the app?

**Comment by gaurish** [comment]
Postman 3.0.25.1
Mac os 10.11(el capitan)
Chrome Version 46.0.2490.80 (64-bit)

Here are steps to reproduce:
1. Open POSTMAN, POST to any URL
2. In body enter a variable `{{output}}`
3. In Pre-request script enter `postman.setEnvironmentVariable('output',JSON.stringify(request));`
4. Click SEND
5. Wait for few seconds & watch it crash. 

is this a bug or I am using this tool wrong? need a way so I can print the objects to write my scripts.

**Comment by abhijitkane** [comment]
This is caused due to an infinite loop in the variable replacement.
Your request JSON has {{output}} in the body, and you're setting the stringified request in the request body again.
So the replacement of {{output}} with the stringified request continues infinitely. 

What's your use case?

To print objects, use `console.log(JSON.stringify(request));`
You can view the console - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by gaurish** [comment]
I am writing Pre-request scripts. in this current one, trying to hmacsha256 digest using `cryptoJS`. so need a way to print out variables, objects for debugging(`console.log` or `alert`) didn't show anyoutput. so trying to sent the output to server to view.

**Comment by abhijitkane** [comment]
You can view the console - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by gaurish** [comment]
Thank you :heart:
