### ISSUE TITLE
want to add Moment Timezone libery to postman to use it in my JS code

### ISSUE THREAD

**Issue by hanyghazal** [a85/POSTMan-Chrome-Extension#1525]
I need to use the Moment Timezone in Jave Script  test code but i can't able to add it or use it . can you tel me how we can use this in JS code

**Comment by abhijitkane** [comment]
The Moment library isn't part of the testing sandbox (https://www.getpostman.com/docs/jetpacks_sandbox).

For now, you can use the workaround posted here - https://github.com/postmanlabs/postman-app-support/issues/1180#issuecomment-115375864
You'll have to repeat this process every time the app updates.

**Comment by blowsie** [comment]
+1, id like to see this lib in the sandbox

**Comment by p00j4** [comment]
Is it in the roadmap to come as part of app?
Would be great to have a import mechanism so any library could be imported in tests

**Comment by vkaegis** [comment]
Hey, the Sandbox API supports the Moment library now. You can refer to: https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference

Closing this issue for now since the original request is resolved. Feel free to open another if you have more feedback around this.

@p00j4 We're tracking support for external libraries in #1180

**Comment by felipeseger** [comment]
I need to use the Moment Timezone in Jave Script test code, at moment we only can use the library from moment and i need the moment-timezone library.
