### ISSUE TITLE
Please add 'Save As...'

### ISSUE THREAD

**Issue by nrogoff** [a85/POSTMan-Chrome-Extension#1578]
This will allow new definitions to be created easily from existing ones.
Thanks

**Comment by jimonthebarn** [comment]
A similar feature already existst. You can open a request and use the dropdown button next to the save icon to "Add to collection". Add it using a different name and you will end up with a duplicated request. The only drawback is that you still have to select the request in the tree view on the left side. Otherwise the "old" request will still be active in the details pane. I've already raised an issue concerning the latter problem here: https://github.com/postmanlabs/postman-app-support/issues/1569

Greets,
Ben
