### ISSUE TITLE
Feature Request: env variables need to be more flexible - collections should have their own vars

### ISSUE THREAD

**Issue by vicholz** [a85/POSTMan-Chrome-Extension#1601]
Local/Global vars don't make sense. There should be a tab/page/setting for global vars which are global to everything including environments, and collections. On top of this environment should be able to set their own vars which can override global vars. Each collection should have an option of adding or pointing to vars or var folders as well which can override environment and global vars.

**Comment by a85** [comment]
This is coming in an update soon.

**Comment by ericnewton76** [comment]
coming soon? +1 this feature.  variables really should be per collection, and you can use the globals if you dont create a collection

**Comment by eric-newton** [comment]
leaving comment as this account too.  this is a neccesary feature.  any word on release of this?

basically you couple the variables to a particular collection, instead of them being "postman global environments".  You could preserve this feature and add the collection features, and the priority should be variables within the collection supersede any global variables.

**Comment by aupp** [comment]
+1

**Comment by shamasis** [comment]
We've already started working and laying foundation for this. Will post updates when we have more to tell. 😊

**Comment by a85** [comment]
Collection variables are available now in the latest versions of the app!
