### ISSUE TITLE
JavaScript error on start, OSX 10.11.2

### ISSUE THREAD

**Issue by haroldfredshort** [a85/POSTMan-Chrome-Extension#1618]
This error dialog appeared when I launched Postman today from the Dock, the app then appeared behind it. After dismissing the dialog I was able to use the app as if nothing had happened.
![screen shot 2015-12-16 at 3 48 41 pm](https://cloud.githubusercontent.com/assets/441624/11857478/64449c0e-a40d-11e5-9ca9-3d1845a27463.png)

**Comment by shamasis** [comment]
Seems like some sort of race condition during the app startup. Could you also let us know the system configuration on which this happened?

**Comment by haroldfredshort** [comment]
Is this the type of information you are looking for?
OSX El Capitan
MacBook Pro (Retina, 15-inch, Mid 2014)
2.5 GHz Intel Core i7
16 GB 1600 MHz DDR3
Intel Iris Pro 1536 MB

**Comment by shamasis** [comment]
Yes. I guess we can rule out performance related race conditions since your system is more than powerful. :-) Are you still frequently seeing this error? Is your Postman Mac app updated to latest?

**Comment by haroldfredshort** [comment]
I only got the error the one time, and I was on the latest (as far as I
know).

**Comment by shamasis** [comment]
Thank you for reporting this. We have added this to our lists of things to keep looking out for. Since we couldn't replicate it at our end yet, would it be okay if we close this for now? We suspect that one of our other fixes might have unknowingly fixed this issue in our internal builds. If we encounter this again or if you do the same, we can reopen.

**Comment by haroldfredshort** [comment]
Yes, feel free to close. Thanks for looking into it.
