### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by oillio** [a85/POSTMan-Chrome-Extension#1634]
It would be nice to have an offline mode in the app.
I seem to get into a state where the app can't connect to the server on occasion.
When this happens, the status icon keeps cycling between "Connecting" and "Offline."
Due to the position, size, and colors, this is rather annoying.
I'd like to be able to stop this cycle without logging out.

**Comment by sobtiankit** [comment]
Noted. We are working on a redesign of the app, which should make the reconnection a lot more subtle. In the meantime, can you share your user id/email? You can mail us at help@getpostman.com. 
I would like to investigate why this might be happening for your account, since we haven't heard otherwise.

**Comment by sobtiankit** [comment]
Closing the issue, post resolution of the reconnections.
