### ISSUE TITLE
Refused to load the script

### ISSUE THREAD

**Issue by mokkrb** [a85/POSTMan-Chrome-Extension#1675]
Hello,
First, apologise if my post does not belong here,
I am trying to make request to my API, including a pre-request script (I used this as a starting point: http://sqa.stackexchange.com/questions/11777/testing-rest-api-with-sha1-hmac-authentication)

I basically have an issue when loading external JS files:
$.when(
    $.getScript( "https://cdnjs.cloudflare.com/ajax/libs/jsSHA/2.0.1/sha256.js" ),
    $.getScript( "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/components/md5.js" ),
    $.getScript( "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/components/enc-base64-min.js" ),
    $.Deferred(function( deferred ){
        $( deferred.resolve );
    })...

But when I run my test, that is what I have in the console:
Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/jsSHA/2.0.1/sha256.js?_=1453378312739' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://ssl.google-analytics.com/ga.js".

Would you have any idea what I am doing wrong, or how to fix this ?

If that helps, I am running:
Postman Version 3.2.11 (packaged)
OS: linux
Architecture: x86-64
Native client architecture: x86-64
Chrome: Version 47.0.2526.111 (64-bit)

Thanks !

**Comment by czardoz** [comment]
Hi,

Postman Sandbox is not asynchronous in nature, so using `$.getScript` will lead to race conditions, and weird errors.

The error that you see however, is Chrome blocking the javascript because of its Content Security Policy for Chrome apps. To view a list of functions available inside the sandbox, you can visit this link: https://www.getpostman.com/docs/sandbox

Also, usage of jQuery in the sandbox will soon be deprecated, so I would suggest you don't use it.

CryptoJS is included as a part of the sandbox, so you should be able to use those functions directly.

**Comment by mokkrb** [comment]
Hi,

Thanks a lot for your answer, and for pointing the right direction to go to !
I will keep working with my script until I get it working :)

Thanks again for your advice !
