### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by zarubto4** [a85/POSTMan-Chrome-Extension#1718]
Hi, 

I want uploud file to server. 

I set in headers: 
Content-Type : multipart/form-data

in body (form-data) 
key: file  value: (my txt file) 

And -> never ending Loading.. and message from postman: Error while sending request: $ is not defined

![snimek obrazovky 2016-02-12 v 19 03 59](https://cloud.githubusercontent.com/assets/16296782/13015806/6cd6eb7a-d1bb-11e5-9108-7f8f77a8012b.png)

Any idea pleas? Its bug or my mistake? 

Thanks

**Comment by abhijitkane** [comment]
@zarubto4 Thanks for reporting this. We'll fix this with the next beta release.

**Comment by abhijitkane** [comment]
Also, if you select form-data, the header is set automatically. There's no need to add a custom header yourself- this will interfere with the correct header.

**Comment by moisesrodriguez** [comment]
> Also, if you select form-data, the header is set automatically. There's no need to add a custom header yourself- this will interfere with the correct header.

@abhijitkane I spent bunch of time with that issue, I gave up at some point and started using Advance REST extension in Chrome because I wasn't able to upload an image using POSTMAN. It should probably give you some kind of warning that setting the header is interfering with the correct header. Or if you select form-data it should autofill the header, so we don't add custom headers that interfere with the correct header.
