### ISSUE TITLE
Preview doesn't work properly in PM APP MAC

### ISSUE THREAD

**Issue by benallamar** [a85/POSTMan-Chrome-Extension#1732]
When I try to see the preview of the response of my localhost server, I tried to click on Preview, but I get a white screen instead of a HTML PAGE.
Could some one helps me ?

**Comment by gunjanpatidar** [comment]
I'm having a similar issue and its quite irritating to have to go through unformatted raw response

This happens because the app does not replace environment variables in the iframe that is created to preview. Also if you're behind a Basic Authorization, these are also not set correctly. In my case I have to keep the dev tools open all the time

<img width="1280" alt="screen shot 2016-02-22 at 8 09 22 pm" src="https://cloud.githubusercontent.com/assets/1112141/13221494/b9f580f4-d9a1-11e5-9161-7a1cd36fd3c3.png">

**Comment by abhijitkane** [comment]
@gunjanpatidar Can you mention the version of the app you are using? (Choose settings from the menu on the top-right)

**Comment by gunjanpatidar** [comment]
@abhijitkane I'm on Postman for Mac v4.0.0-beta.3

**Comment by SamvelRaja** [comment]
Seems like the issue related to #1722,  It has been fixed in the stable `v4.0.0 version`

**Comment by gunjanpatidar** [comment]
@SamvelRaja updated, that solved it :) But I only got the update for beta.4 and no further
