### ISSUE TITLE
UI: How to open a saved request in new tab

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1783]
This is a usability concern, not necessarily a bug.

Only to say it took me 10 minutes to discover how to open a saved request into a new tab.

I kept clicking, alt-clicking, control-clicking, shift-clicking, right clicking, ellipsis button clicking (everything!) to open a sidebar item in a new tab. Then I went to Google and found nothing. Searched the documentation, nothing. The solution was not obvious to me.  Apparently, if I want to open an item into a new tab I have to first click the new tab button at the top, then click on the sidebar item.

As a matter of convenience, it would be nice to follow the conventions used in other popular windowing  environments. In Nautilus its shift-click, in Windows Explorer its control-click.

If anything, this post may help someone else doing a Google search.

**Comment by mstaalesen** [comment]
+1 on this.

In 3.2.20 (and earlier), there was a setting called "Open history/collection requests in a new tab" & "Track unsaved requests in tab"
They are now missing, and it's really messing up my way of working (only have 1 request open at once).

Hopefully this is a bug and they will bring back the possibility of doing it the "old fashioned way".

**Comment by johnhenderson** [comment]
+1

**Comment by xxldoctor** [comment]
+1
middle mouse button for new tab will bi nice

**Comment by gogonutsss** [comment]
I cannot believeit that this setting has been removed,  together with fact that collection runner does not give a way to see the responses it gives the impression we have to memorize responses or smell our nails!  Come on guysss!

**Comment by hernandcb** [comment]
+1

**Comment by a85** [comment]
Cmd+Shift+click on mac, ctrl+shift+click on win/linux works as a shortcut now for opening a request in a new tab from the sidebar.

**Comment by ghost** [comment]
Verified and thank you.  Can this key combination be documented somewhere?

**Comment by a85** [comment]
Yeah. Going in the next version.

**Comment by nscherer** [comment]
> If anything, this post may help someone else doing a Google search.

It did.  :-)

**Comment by StevenElwell** [comment]
Dr Mr/Mrs Postman
I can duplicate this with 20 people.   So before suggesting that I may be a bit challenged, please first try my steps shown below.
Step-1: A user new to Postman saves 4 requests in a collection
Step-2: User closes Postman, goes to lunch, or bed
Step-3: User comes back and tries to open one of the 4 previously saved requests
It doesn't matter how high the IQ of the user is, this can not be determined on their own.  The docs for Postman skip this topic entirely - this is rather interesting as Open and Close are basic concepts in an app that manipulates data.
This can all be proven over and over again - and it takes just a few minutes for each proof to play out.  Simply grab any developer (10+ years of experience) and watch the results play out.  This test is extremely easy to conduct.
My strong suggestion is that the basic features of an app should be able to figured out rather quickly.  When this doesn't happen, users will flee - because if a basic operation is not intuitive, normal user behavior will be to assume (correctly or incorrectly) that more-complex operation will be even more, complex, or frustrating.
Please feel free to try my reproduction steps listed above.  Something is wrong in the UI.  Version:  v7.2.2
PS:  It is also interesting that the Help Menubar option does not list the version of the executing product.  This is not a good practice with respect to UI apps.  The concept of Help->About has been around for 35 years now.
Best Wishes

**Comment by StevenElwell** [comment]
Update:

There is a splitter and pane on the left side of the UI (that may have to be expanded) and then to the right of the "History" option seen is a "Collections" option. Drilling down into the selected Collection shows the requests. For whatever reason this does not stand out to new users so perhaps a traditional menu item could assist new users. 

The opening modal window/wizard could also offer this option (even if it just simply stated what to do) as this is such an important task.   [New] [Import] and [Runner] buttons are very dominant in the UI, but [Open] doesn't seem to stand out and Open would be performed way more often than [Import] would be performed.

Creating, Send, Save and opening requests are probably going to be the first tasks that a new user performs and opening just wasn't intuitive to me and others I tested with.  Just noting the experiences here.

**Comment by arjuna-dev** [comment]
Yes, that tiny splitter pane button, greyed-out, in the always-neglected bottom-left corner...
