### ISSUE TITLE
When running collection in newman using -d option, how does it know the location of data file in my system? Do I have to specify the location or have data file in a particular folder?

### ISSUE THREAD

**Issue by akapoor47** [a85/POSTMan-Chrome-Extension#1927]

**Comment by mstaalesen** [comment]
If you don't give a path, but just the filename it will look in the current folder. I would recommend always adding full path to the file, so that it won't matter where you are executing newman from. The same should be said about other input files (environment, globals etc), and output files (reports).

Just a tip: Newman issues should be posted here: https://github.com/postmanlabs/newman

**Comment by akapoor47** [comment]
Thanks for the info and tip. It is helpful.
