### ISSUE TITLE
Tiny font issue

### ISSUE THREAD

**Issue by a85** [a85/POSTMan-Chrome-Extension#1977]
Creating a new issue because of unnecessary spamming on #979.

**Comment by sharpedavid** [comment]
For me the problem is that I routinely increase the font size of _all_ my applications to about 125%, sometimes more. Here a side-by-side screenshot comparing Google Chrome to the Postman Chrome app. In it, I've increased Chrome's font size to 125% and the Postman "Response Font Size" to 18. I can easily read Postman's response window, but I have to squint and lean to read the rest of the font, especially when my request is long.

![image](https://cloud.githubusercontent.com/assets/1767127/14362235/75bd0a12-fcb3-11e5-814c-a534d2364ac5.png)

For me this is a feature request to be able to change the app's font size, not a bug. Maybe this ticket is for a different issue?

**Comment by a85** [comment]
@sharpedavid Thanks. This is what I wanted to know. Will get back here with comments.

**Comment by herbertpimentel** [comment]
+1

**Comment by zigacernigoj** [comment]
Everything in Postman is tiny on my FullHD 15" display and I'm getting headaches about this. Why would I need to change "default" font size in Chrome if it's made so that Postman is running in "independent" window? For me it's not bug, it's a FAIL.

**Comment by ghost** [comment]
+1

**Comment by mboveiri** [comment]
+1

**Comment by mvrkljan** [comment]
+1

Any news on ETA for Request font size setting?

**Comment by myoss** [comment]
+1

**Comment by a85** [comment]
You can now scale up the entire UI. Check out Settings > Shortcuts to see how:

<img width="701" alt="screenshot 2016-09-10 14 04 34" src="https://cloud.githubusercontent.com/assets/653409/18413544/be2ec070-775f-11e6-8d7a-a35abdd85de4.png">

**Comment by ghost** [comment]
Thank you!   The scaling works on my PC using the CTRL +   or CTRL -  when I use the + and - signs that are above my keyboard.  
Just an FYI only the CTRL -   shortcut seems to work, when I use the (minus sign) - that are is my on my numeric keypad.   CTRL + and CTRL0 do not work from my numeric keypad.

**Comment by stepcha** [comment]
Hi all,

To improve the font size forever, you just open the file "4.7.2_0/html/requester.html" with your text editor and add this code at the end of the file before the close of the tag "</body>"

`
    <style>
        .editor.ace_editor {
            font-size: 18px !important;
        }
    </style>
`

In my case: C:\Users\Stepan\AppData\Local\Google\Chrome\User Data\Default\Extensions\fhbjgbiflinjbdggehcddcbncdddomop\4.7.2_0

Reopen the app/extension and enjoy :P

**Comment by microcipcip** [comment]
Anyone unable to change the font size on windows: you need to click `ctrl++` from the **plus key next to the backspace button**, not the one where there is the numeric keypad 

![keyboard](https://user-images.githubusercontent.com/585402/29494172-3e7a9cd6-859c-11e7-9a31-0403e5b1286e.png)
