### ISSUE TITLE
Undefined Bearer token when saving oauth2 tokens from fitbit

### ISSUE THREAD

**Issue by Bachmann1234** [a85/POSTMan-Chrome-Extension#1980]
This sound similar to https://github.com/postmanlabs/postman-app-support/issues/1449 but the behavior is slightly different and its been a while so I figured I would post it separately.

When I authenticate with Fitbit's oauth2 apis Postman Stores the token, but when I use it the token is saved as "undefined"
<img width="579" alt="screen shot 2016-04-07 at 9 02 36 pm" src="https://cloud.githubusercontent.com/assets/1521093/14371291/16923d0e-fd04-11e5-82e6-b197ea47391e.png">

<img width="654" alt="screen shot 2016-04-07 at 8 58 53 pm" src="https://cloud.githubusercontent.com/assets/1521093/14371258/e3c76f20-fd03-11e5-8898-05e0eb547402.png">

<img width="799" alt="screen shot 2016-04-07 at 8 58 14 pm" src="https://cloud.githubusercontent.com/assets/1521093/14371294/21d63242-fd04-11e5-8bcc-0c4584f0bab2.png">

<img width="325" alt="screen shot 2016-04-07 at 9 03 36 pm" src="https://cloud.githubusercontent.com/assets/1521093/14371306/38bbb838-fd04-11e5-96df-86b9aa3f2861.png">

<img width="845" alt="screen shot 2016-04-07 at 8 58 42 pm" src="https://cloud.githubusercontent.com/assets/1521093/14371302/2e3b763c-fd04-11e5-9562-95e8f38be300.png">

**Comment by Bachmann1234** [comment]
I understand that this is likely because fitbit is doing something slightly unexpected with the oauth response. But can you give me a sense of what is different about Fitbit's flow?

Any suggestions for a workaround?

**Comment by abhijitkane** [comment]
@Bachmann1234 It seems that the second call (to the access token URL exchanging the Authorization code for the access token) needs an Authorization header. We've patched this, and this should be available in the next release.

**Comment by Bachmann1234** [comment]
@abhijitkane score! thanks

**Comment by Bachmann1234** [comment]
@abhijitkane This seems to work for me after downloading the newest version. Thank you. I am still poking it but just wanted to send a thumbs up 👍

**Comment by abhijitkane** [comment]
@Bachmann1234 Great!

**Comment by Spulface** [comment]
@abhijitkane 
Could you clarify if this has been resolved **only** for Fitbits auth chain? 
I am asking because I am facing pretty much the same issue for eBay's OAuth 2.0 chain at the moment:

![image](https://cloud.githubusercontent.com/assets/16802919/25702654/53e48718-30d2-11e7-8cb9-4d5b035b6dc8.png)

![image](https://cloud.githubusercontent.com/assets/16802919/25702690/7421a1e6-30d2-11e7-87de-70748f4561e8.png)

![image](https://cloud.githubusercontent.com/assets/16802919/25702761/cbf95aa8-30d2-11e7-92a1-6df98d1fbb15.png)

![image](https://cloud.githubusercontent.com/assets/16802919/25702836/1ea582d6-30d3-11e7-93a0-93e5fd47a48f.png)

According to eBay's docs they're expecting a base64 encoded client_id:client_secret Authorization header when exchanging the auth code for the user/access token:
http://developer.ebay.com/Devzone/rest/ebay-rest/content/oauth-gen-user-token.html#Exchangi


Am I getting something wrong here or is it a similar behavior as with Fitbit's API but not covered with this ticket?

**Comment by Busterz** [comment]
i am getting the same issue as above while trying to access the google calendar api. The bearer token is saved as undefined.
