### ISSUE TITLE
How to set Body with Get ?

### ISSUE THREAD

**Issue by yanpeipan** [a85/POSTMan-Chrome-Extension#2004]
curl -X GET \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
  -G \
  --data-urlencode 'where={"playerName":"Sean Plott","cheatMode":false}' \
  https://api.parse.com/1/classes/GameScore

**Comment by Macoshark** [comment]
I have a similar request. Currently Postman doesn't allow you to send a body in a GET request. This is not commonly done, but as I've understood it isn't forbidden by the HTTP spec. 

I ran into this issue when trying to test Elastic Search queries. Elastic Search queries can contain a body in a GET request and because I can't test them with Postman I've had to look elsewhere.

**Comment by abhijitkane** [comment]
@Macoshark This is currently blocked by the XHR object. Most Elasticsearch APIs should work if you just change the GET to POST and keep the URL the same.

**Comment by yanpeipan** [comment]
The params left send button solved my problem.

**Comment by xiaodin1** [comment]
https://github.com/postmanlabs/postman-app-support/issues/131
Reiterating: For people posting about Elastic: You can replace GET with POST and ElasticSearch will work as expected. We are replacing the underlying networking stack in Postman so that we can have more control than XHR. This is still some time away.

A new Node.js based networking stack will be available soon that will help us add bodies for GET calls.

**Comment by bpamiri** [comment]
The Elasticsearch API is not the only API that expects a body with a GET verb. The Magento API does as well. Unfortunately the Magento API doesn't allow you to simply replace a GET verb with a POST verb. IF you try to do that you get a route not found error from them.
