### ISSUE TITLE
Project Folder or Working Directory Support

### ISSUE THREAD

**Issue by keeper3000** [a85/POSTMan-Chrome-Extension#2027]
We have a web project with a Postman module where everyone checks in their postman scripts and postman test cases.  If anyone checks in changes into this directory than we have to be mindful and "re-import" the directory into our postman application.  

Instead we would like our Working Directory to be the directory of truth so any changes made there are reflected into our Postman application. In addition, any "Saves" are propogated down to our Working Directory. Due to compliance, we our not allowed to use your features where these scripts are hosted offsite.

**Comment by abhijitkane** [comment]
@keeper3000 Due to the restrictions Chrome apps have w.r.t the filesystem, Postman can't read and write files in custom locations w/o user consent each time.

You can try exporting the collection in the v2 format (this should reduce merge conflicts in your version control system).

Closing as non-actionable.

**Comment by vkaegis** [comment]
Hey @keeper3000! We've made an RFC to document our ideas on version control in Postman and it could be relevant to this discussion. Would love your thoughts and feedback on it:

https://community.getpostman.com/t/version-control/2715
