### ISSUE TITLE
SignOut button beside Request Token button in OAuth2.0

### ISSUE THREAD

**Issue by RonakThakkar** [a85/POSTMan-Chrome-Extension#2049]
I have scenario where I would like to test my API using 2 users in OAuth2.0 flow.

I clicked "Request Token" button which opens login screen where I entered login credentials which returns token back. This works well.

Now I would like to test same API using another user. I again click the "Request Token" but this does not open login windows instead gets token for previous user.

It would be better to provide SingOut button beside "Request Token" button so that I can click on "SignOut" and then click "Request Token" button again to open login window and enter login credentials for another user.

**Comment by abhijitkane** [comment]
@RonakThakkar We agree. However, most OAuth2 "logouts" function differently - Github, for example, needs a POST to `github.com/logout`, Google needs a GET to a different URL. We're looking at ways to consistently do this across OAuth2 providers. 

We might be able to do this in our native Mac app, though (by clearing the cache). Will look into this.

**Comment by samakshjain** [comment]
If logout button is an issue, can we have a button to clear the log-in session/cookies.
I have been breaking my head trying to log out postman and log-in from a different account.

**Comment by ghost** [comment]
+1

I really need to be able to test as multiple users

**Comment by rms81** [comment]
+1

**Comment by theythinkimmexican** [comment]
spent a while looking at this yesterday. clearing the cookies would be nice.

**Comment by aggieben** [comment]
Is there any update on this?  Is there a way to manually remove the cookies?

**Comment by schanzen** [comment]
+1

**Comment by Ustimov** [comment]
There is any way to log out?

**Comment by harryi3t** [comment]
This is very much possible and we are considering this for Postman 5.4
Let me know which adds more usability:
1. A single button to clear session/cookies for all the sites
2. A button which will only clear the session/cookie for the domain of the Auth URL

**Comment by samakshjain** [comment]
In my opinion option 2 should be the way to go. I wouldn't like to have to go with the OAuth2 process again for all other domains.

**Comment by ejntaylor** [comment]
Is there a way to do this now? Logout and auth with a different user. Cheers

**Comment by ejntaylor** [comment]
Update: If you log out of Postman that clears the auth  👍

**Comment by harryi3t** [comment]
@raisonon Could you try clearing the cookies and see if that works?

**Comment by RotterAxel** [comment]
I think the best option would be to implement this on the Postman Testing API. So pm.login / request authentication token and pm.logout in order to automatically test each scenario.

**Comment by vikiCoder** [comment]
Hi everyone,

Cookies for all the requests sent while OAuth2.0 token generation are stored in [Cookie manager](https://learning.postman.com/docs/postman/sending-api-requests/cookies/#getting-to-the-cookie-manager). You can log out from the auth website by manually deleting relevant cookie for particular auth domain from [cookie manager](https://learning.postman.com/docs/postman/sending-api-requests/cookies/#getting-to-the-cookie-manager).

You can also do this programmatically via pre-request/test scripts. Refer out [programmatic cookie access](https://learning.postman.com/docs/postman/sending-api-requests/cookies/#creating-a-cookie-jar) guide for more details.

However, we've recently added an option in OAuth2 that allows you to authenticate using your system's default browser while generating OAuth 2.0 token. That will solve the problem since you can easily log out in your browser. Check out [my comment](https://github.com/postmanlabs/postman-app-support/issues/7700#issuecomment-626273229) on [that thread](https://github.com/postmanlabs/postman-app-support/issues/7700) for more details. Please update to the latest Postman app (v7.24.0) to try it out.

**Comment by LaurelGerman** [comment]
Clearing cookies in Postman didn't work for me, but here's a low-tech solution that did (Only tested in Chrome):
After you click Get Access Token and the login screen appears in your browser,

1. Copy the url
2. Open an incognito tab and paste the url
3. Log in via that incognito window

This way, cookies are never saved, and you'll be prompted to log in every time you generate a new token. As long as you never log in thru a non-incognito window, this works!

**Comment by ADTC** [comment]
Clearing cookies in Postman didn't work for me too, but here's a high-tech solution that worked for **Auth0**:

1. Set up a Next.js project with the Auth0 Next.js SDK. _(You can choose any framework, even plain HTML, but I already had a Next.js project with all the required functionality.)_
2. Create a page that checks whether you're logged in, and shows a Logout option.
    1. If it looks like you're not logged in, login first. (For this, the page should show a Login option.)
3. Click the Logout option, and make sure the page shows you're logged out.
4. In Postman, click "Get New Access Token". Viola! You're asked to choose an account.

So I believe it's a matter of knowing which service and then hitting the logout API for it. Would be nice if Postman can automate it with a list of known services, and for a custom service, allow saving a custom logout URL.
