### ISSUE TITLE
cannot access to DB

### ISSUE THREAD

**Issue by dimalusa** [a85/POSTMan-Chrome-Extension#2092]
Postman - REST Client shortcut 0.8.4.8
On chrome ==> Version 51.0.2704.63 (64-bit)
Log 
requester.js:112 Uncaught TypeError: Cannot assign to read only property 'indexedDB' of object '#<Window>'(anonymous function) @ requester.js:112
window.webkitIndexedDB

![image](https://cloud.githubusercontent.com/assets/6318802/15651544/9d22962a-2680-11e6-912b-20a3a165a616.png)

**Comment by abhijitkane** [comment]
@rdierickx Can you try upgrading (chrome://extensions > Enable developer mode > Upgrade extensions now). This was fixed in the latest version.

Also, this version isn't supported anymore. You should try the Postman app (https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en)
