### ISSUE TITLE
Feature Request : Run database queries(SQL) from postman

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#2185]
I have been looking into building up an end 2 end solution for API testing. Postman is the way to go but currently I have no way to run database queries to build by test data as part of my automation through Jenkins. **If postman can support running server side database queries (SQL) that will make it an end to end solution for API test automation.**

Version/App Information:
1. Postman Version: v4.4.2
2. App (Chrome app or Mac app): Chrome App
3. OS details: Windows 7 Professional
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: This feature is currently not available in Out of box package
6. Expected behaviour: Run database queries from within postman scripts
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Steps to reproduce the problem:
This is a new feature request

**Comment by abhijitkane** [comment]
@tariqghalib Unless the DB exposes an HTTP API, Postman cannot make DB queries. It's meant to be HTTP API management tool. We're looking at Websockets as a potential area of expansion, but not direct DB queries. You can look at http://blog.ulf-wendel.de/2014/mysql-5-7-http-plugin-mysql/ for a mysql-http plugin.

Closing as non-actionable.

**Comment by huyq119** [comment]
@abhijitkane  why close this subject？

**Comment by ywforever** [comment]
second @huyq119

**Comment by ShivaniGaba1** [comment]
Does this problem has some solution now? I want to connect to postgres db and get parameters for post request from db

**Comment by sdnts** [comment]
Guys, this was closed since Postman is a REST client. Databases have different protocols that they use to communicate. What I'm trying to say is, this is something that Postman was not designed to do.

However, as @abhijitkane said, if you do have a REST API for your database, the app can talk to the API and indirectly interact with your database.

**Comment by paulhilliar** [comment]
Agree that Postman is a REST client not a DB client.  But sometimes you just have to get at the data....

My suggested workaround is to write a small REST service, running locally, that has DB access.  
It would expose an API for DB queries and return results as JSON.

**Comment by joelcolucci** [comment]
The main inhibitor to using Postman is lack of support to execute local scripts. A local script could be used to seed a database. From there tests can be run.

Creating an HTTP service to seed the database is not an option because that's another layer of complexity/abstraction that could fail just the same as the API.

How are people testing READ (/widget/<id>) resource endpoints without relying on the API to CREATE a resource?

**Comment by a85** [comment]
@joelcolucci While this seems logical to do, it introduces a level of coupling with databases that will make tests harder to replicate and execute. You CAN use local scripts if you use newman (postman's command line tool). I'd recommend writing a separate script to set up your database structure and then using newman purely for tests. Within Postman, we plan to introduce the ability to write plug-ins that will let you do this within the Collection Runner too. However, this will still mean that the script is logically separated from the test suite.

**Comment by joelcolucci** [comment]
@a85 Thank you for your thorough reply. I'll dig into Newman a bit more. I appreciate your time and assistance.

**Comment by podfish** [comment]
I'm digging into postman, and from a CI/CT perspective, i see this is a tool primarily for development of test suites that are then deployed in another environment that has richer toolchains.I too would love to be able to build queries in postman based on other results facilitated by js includes and access to external libraries, because in my environment, we're not just testing APIs, we're testing a full business path flowing through a suite of APIs. These are often our only reasonable way to interact and provide inputs at volume to headless systems. And API responses aren't always rich enough to show that system changes are implemented correctly. Seems I need a richer toolset, of which postman and newman should be a part. ...am I on the right path as far as my thinking?

**Comment by joelcolucci** [comment]
@podfish

In terms of integration testing it takes a change of mindset. I came from a background of TDD where you'd set up `beforeEach` and `afterEach` calls for each test in a suite. Each test would be a call to an endpoint in isolation.

With Postman the approach has changed to testing full business paths with a chain of API calls. For example, chaining together CREATE, READ, UPDATE, DELETE calls for a resource.

Based on your description the Postman approach seems to align well with where you are at. Postman will handle defining your endpoints and testing them. You'll need other parts of your pipeline to boot the app, run cleanup etc.

**Comment by aniopn** [comment]
Please, integrate the possibility to query sql database, take some parameters and pass those parameters to "GET" or "POST" or "DELETE" requests in Postman. 
Regards
Angelo

**Comment by annedemata** [comment]
Hi, 

I know that this thread is already closed but I'm wondering if there have been any more push on making this feature available - allowing Postman to run DB queries. 

When I do a POST to one of our APIs, it would store the parameters I gave to a table and to confirm that the POST actually did it's thing, it would be great to be able to query that table. 

I second @paulhilliar, "Agree that Postman is a REST client not a DB client. But sometimes you just have to get at the data...."

Thanks!

**Comment by andyherd** [comment]
"When I do a POST to one of our APIs, it would store the parameters I gave to a table and to confirm that the POST actually did it's thing, it would be great to be able to query that table."

Exaclty what I came here to say. Agreed with @annedemata and @paulhilliar that this would be very helpful.

**Comment by ZedoAditi** [comment]
Yes @annendemata, I think this would help us integrating database testing(at least query) and  API testing without any separate tool for database testing.

**Comment by BhanuDash007** [comment]
Any update on above request for #5199

**Comment by marioabbey** [comment]
Any update on this issue #5199 ?

**Comment by DineshKumar1705** [comment]
Any update on #5199 ? There is a desperate demand for accessing the Database with Postman to make it end-to-end testing environment.

**Comment by kthulsidoss** [comment]
@dineshkumar1705 are u not rest enabling the database ? then you can try make queries to POSTMAN

**Comment by JakimLi** [comment]
Postman should not be responsible for database interaction if you're using postman from as a node-js application, you can write other scripts, and make it work with postman. I had the same requirement previously, we ended up with creating a new api testing automation tool that takes database interaction as the first-class citizen. 

https://github.com/JakimLi/pandaria

Hope it helps
