### ISSUE TITLE
Failing to render response due to unknown character

### ISSUE THREAD

**Issue by sidharth016** [a85/POSTMan-Chrome-Extension#2271]
Using the latest version

curl -X POST -H "REV-API-KEY: mgmsYvv0O3A97Rv0k72nnhOBTBajsBbUJ3FN" -H "REV-APP-ID: com.time.now" -H "Content-Type: application/json" -d '{ "data": [
    "speed thrills me super"
  ]
  }' "http://beta.auth.revup.reverieinc.com/apiman-gateway/mynewapp/transliteration/1.0?target_lang=hindi&source_lang=english"

The curl request shows response whereas the postman response screen shows
Unexpected '�'

**Comment by sdnts** [comment]
Hey @sidharth016, I sent a request to your URL with the appropriate headers like you did. I saw that in the response, I receive a full response but our JSON parser fails to parse the response because of those Unicode characters. If you switch to the `Text` option for the response (screenshot attached), or just switch over to the `Raw` tab in the response, you should see your entire response albeit with weird (unicode) characters.

Thanks for reporting this. We'll get on a fix.

**Comment by sdnts** [comment]
The response view should render Unicode characters correctly now. Closing. Please let me know if you're still seeing issues, and I'll reopen.
