### ISSUE TITLE
Postman Echo Cookies -> Delete Cookie test doesn't work correctly.

### ISSUE THREAD

**Issue by zet4** [a85/POSTMan-Chrome-Extension#2279]
1. Postman Version: 4.6.2
2. App (Chrome app or Mac app): Win App
3. OS details: win32 10.0.10586 / x64
4. Is the Interceptor on and enabled in the app: No interceptor required in Win App
5. Did you encounter this recently, or has this bug always been there:
6. Expected behaviour: Running tests for cookies will return all 4 pass.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable) http://i.imgur.com/CUlLhrb.png

**Comment by elssar** [comment]
Hi @ZetaHunter, thanks for reporting this.

That is a bug in the collection - the request is deleting the cookie `foo1`, but the tests are checking that `foo1` exists. If you update the request to delete `foo2` instead of `foo1` all tests will pass.

EDIT:
The bug has been fixed in the latest version of the collection. You can just fetch it from `https://echo.getpostman.com`.

**Comment by zet4** [comment]
Yes I figured as much, but I believe this is something you guys should fix on your end as you own the collection.

EDIT:
Was replying to what I saw in the email, didn't see your edit, I guess I will close this now.
