### ISSUE TITLE
Difference in using url variables between Windows/Chrome app

### ISSUE THREAD

**Issue by xxldoctor** [a85/POSTMan-Chrome-Extension#2284]
Postman Version: 4.6.2
win32 10.0.10586 / x64
App (Chrome app or Mac app): Windows App
 Bug appear only in standalone apps (winx/osx). url like `{{baseurl}}/:id{{format}}?someparemeters` parsed correctly in chrome app (eg `/102.json/someparameters`), when in win/osx app it cause error "Could not get any response
There was an error connecting to  https://mybaseurl:port/:id.json?someparameters". Funny, but if I click "Generate code" button - I can see that postman can parse this request correctly - `{{baseurl}}/102.json/someparameters`
Bug appear only when I use environment/gloabal variable in url just after url variable. If I replace {{format}} variable from request it will be work correctly.

**Comment by numaanashraf** [comment]
@xxldoctor Thanks for reporting this. We'll let you know when we have a fix ready.

**Comment by SamvelRaja** [comment]
@xxldoctor This should be fixed in the Windows app `4.6.3` , Kindly ensure from your end and close the issue.

**Comment by xxldoctor** [comment]
Hmm, for now (version 4.7 on windows) I still have troubles in such requests, but it show the responce now:
{
  "status": 400,
  "code": "CONVERSION_NOT_SUPPORTED",
  "message": "Failed to convert value of type 'java.lang.String' to required type 'long'; nested exception is java.lang.NumberFormatException: For input string: \":orderId\""
}

In chrome extension same request work correctly.

**Comment by SamvelRaja** [comment]
This is a known change and would arrive in chrome app soon. This is in order to better disambiguate path variables and possible future amalgamation of path variables and other postman variables. It also helps us add better features such as static variable name parsing and syntax highlighting.

`{{baseurl}}/:id{{format}}/` will take `:id` will be resolved as if it was `:id` and `{{format}}` as a composite function. (1) `{{format}}` is resolved first (say it resolves to `abc`) and then `:idabc` is resolved.

The workaround is to use two separate variables and not use path variables in this case.
