### ISSUE TITLE
Function xml2Json may not preserve XML element order?

### ISSUE THREAD

**Issue by stormposse** [a85/POSTMan-Chrome-Extension#2307]
1. Postman Version: 4.6.3
2. App (Chrome app or Mac app): Mac app
3. OS details: OS X Yosemite 10.10.5 (14F1909)
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: always
6. Expected behaviour: object produced by xml2Json retains the ordering of XML elements
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Input XML:
<img width="372" alt="screen shot 2016-09-01 at 15 45 51" src="https://cloud.githubusercontent.com/assets/17124925/18171900/72cf2a80-705b-11e6-8e2d-b9f5b4dbbabd.png">

Output object:
![screen shot 2016-09-01 at 15 38 35](https://cloud.githubusercontent.com/assets/17124925/18171523/3eeb03ca-705a-11e6-9813-596eac11957a.png)

1. Unzip this sample XML and stick it on a server or somewhere:
   [mapStructure.xml.zip](https://github.com/postmanlabs/postman-app-support/files/449941/mapStructure.xml.zip)
2. Retrieve the sample XML using a GET in Postman and process it with this test script:
   
   if (postman.getResponseHeader("content-type")) {
       var responseObject = xml2Json(responseBody);
       console.log(responseObject);
   }
3. Compare the ordering of the _itemArray_ elements with the elements in the xml2Json output object shown in Postman Console. Note that the _itemArray_ elements appear to be grouped instead of retaining their original order in the XML.

**Comment by a85** [comment]
@stormposse Thanks for reporting this. Looking into the issue.

**Comment by vegetableman** [comment]
@stormposse The app supports `xml2json` through https://github.com/Leonidas-from-XIV/node-xml2js. In order to support the JSON formatting you described, a `validator` would have to be passed to `xml2json` as an option which isn't supported currently on the sandbox, but we will add support for it in a future release. cc @czardoz.

**Comment by stormposse** [comment]
Cool! Thank you @czardoz.

**Comment by codenirvana** [comment]
@stormposse As mentioned above, the app is using [xml2js](https://github.com/Leonidas-from-XIV/node-xml2js) and even though `xml2json` don't support additional options to customize the conversion behavior since its legacy api and newer way is to directly `require` the library, so you can directly require the `xml2js` in your script and use options mentioned in its documentaion. 

Example:

```javascript
// Documentation: https://github.com/Leonidas-from-XIV/node-xml2js#node-xml2js

var xml2js = require('xml2js'),

    validator = function (xpath, currentValue, newValue) {
        return newValue.toUpperCase();
    },
    
    x2js = new xml2js.Parser({validator: validator});

x2js.parseString('<xml>postman</xml>', function (err, result) {
    console.log(JSON.stringify(result)); // {"xml":"POSTMAN"}
});
```
