### ISSUE TITLE
File select through the "form-data" option does not save.

### ISSUE THREAD

**Issue by daniellemoreira1** [a85/POSTMan-Chrome-Extension#2331]
**Identified problems:** selected file saved does not appear after you close the tab. Also, you can not hold two requests using different files.

**Version Chrome: 53.0.2785.116 m (64-bit)**

**Steps to Reproduce:**
1. Access Postman;
2. Create a new request;
3. Change the method to "POST" and inform the service;
4. Select the "form-data" and change the "text" to "file";
5. Choose a file;
6. Select the "Save";
7. Close tab request;
8. Open the tab again and see that the file is not showing up.
9. Carry out steps 1 to 6;
10. Open another request that also uses file;
11. Note that the file appears in the two repeated requests.

**Expected results:** the file should appear after you close the tab. And it should be possible to choose different files for each request.

**Comment by a85** [comment]
@daniellemoreira1 Postman does not store file references right now. We are working on improving this behavior.

**Comment by xmeng1** [comment]
By using the App, I found that when I add a file, the file will be made a copy to a folder of Postman.
`~/.config/Postman/IndexedDB/file__0.indexeddb.blob/1/00` So next time, If I don't choose the file, the request will use this file. Is it the improvement by Postman? Where I can find the related document.
I only see [the document](https://www.getpostman.com/docs/requests) said:

> multipart/form-data is the default encoding a web form uses to transfer data. This simulates filling a form on a website, and submitting it. The form-data editor lets you set key/value pairs (using the key-value editor) for your data. You can attach files to a key as well. Do note that due to restrictions of the HTML5 spec, files are not stored in history or collections. You would have to select the file again at the time of sending a request.

**Comment by xmeng1** [comment]
According to my research on the JSON of the collection, I found that the collection JSON download by my API key (JSON-Remote) is different with the JSON export from the Packaged App (JSON-Local). 

Apart from the size of files (JSON-Remote > JSON-Local, such as my collection: 6M>1M), the value of `file` key is also different. In JSON-Remote, the value of `src` of type `file` is an object which contains the path. However, the Newman cannot parse this object. Actually, the `src` should be the string of path.

JSON-Local,
```
{
"key": "Data",
"type": "file",
"enabled": true,
"warning": "",
"src": "mx2.png"
}
```

JSON-Remote
```
{"key":"data",
"type":"file",
"enabled":true,
"warning":"",
"src":{"0":{"name":"mx1.png",
"path":"xxxxx/xxxx/mx1.png",
"lastModified":1485878813982,
"lastModifiedDate":"2017-01-31T16:06:53.982Z",
"webkitRelativePath":"",
"size":223419,
"type":"image/png"},
"length":1}}
```

I am doing some work to convert the object of "src" to "path" automatically by Linux shell script. Meanwhile, I want to keep the JSON as small as possible. So I prepare to use the JSON-Local and copy the path value in JSON-Remote to the JSON-Local.
 
**So if the Postman can export the JSON-Remote format collection (also import), and then let the Newman recognise this format of the file data (I think it is not very hard, just recognise the src file of the object). I think this function will be perfect.**

**Comment by ppaulocm** [comment]
"Identified problems: selected file saved does not appear after you close the tab. Also, you can not hold two requests using different files."

Is There any target for this? In my case, I have a collection that is exported to be ran by newman on Teamcity environment. Everytime that I need to change some test, I have to open all tabs that has some "file upload test" and put the files again. In a suite with about 50 tests and some enginners, it's impossible to handle this and use the fully power of pstman. 

I put the files on root project folder and when uses Teamcity, I had no problem. The point is, if the filename can be saved and loaded from a collection file in a form data, it will be a fantastic thing.  I don't know the impact of this but I believe that can be useful to many people.

**Comment by Rocking80** [comment]
Hi Guys,

It has been more than 1 year since daniellemoreira1 raised this issue. Just wonder is there any progress on this enhancement? If we cannot save attached file in collections, actually we cannot automate the collections by postman runner, because every time we need to specify the file in the form data manually. Otherwise the post request will fail because of missing file data.

**Comment by ravikiran1988** [comment]
hi guys,

any news here? i have been using gitlab, newman, jenkins combination for scheduled builds.
i also have a pro version.

each time i export the collection i have to change the formdata section to include file paths and it's a very tedious process.

I want to move away from this and used postman runners...but this feature holds me up from running my entire collection in the runner.

**Comment by bgaillard** [comment]
Hi, we also encounter problems with this. 

For now we've commented all the tests which fail because of file upload problems in our development machines, for example using the URL of our API on localhost.

```javascript
// For now all Postman requests which uses file form data parameters cannot keep a reference to the configured file
// So we cannot test file uploads automatically in development and we ignore the expected result for now
//
// In staging a trick has been implemented to dynamically update the Postman collection JSON using Unix text replacement
// tools.
//
// A Github issue has been opened for this.
// @see https://github.com/postmanlabs/postman-app-support/issues/2331
if(environment['url'].indexOf('localhost') === -1) {
    // Tests enable only if Postman collection is executed on a development machine
}
```

Then in our Jenkins Continuous Build we dynamically update the path to the paths to make the tests pass.

We use something like that in our Jenkins build (assuming we use Newmane and `fileUploaded` corresponds to a file parameter).

```javascript
wget ${POSTMAN_COLLECTION_URL} -O collection.json
cat collection.json | tr -d '\n' > collec.json  
sed -i 's#\("image\[fileUploaded\]",\)[^}]*\(}\)#\1 "type": "file", "src": "'$WORKSPACE'/postman/files/image.jpg" \2#g' collec.json
```

It works but this is not perfect because it cannot be done automatically in Postman and some assertions are by-passed on our development machines.

It would be great to add a feature to provide something like `{{upload_files_folder}}/my_file.png` as the value of a file input parameter.

With this a Postman / Newman environment could change the value of the `upload_files_folder` environment variable and developers could be free to change their paths locally. 

@a85 Is this feature in the roadmap ? 

Thanks, 

Baptiste

**Comment by santhoshTpixler** [comment]
I have tried[ Insomnia REST Client](https://github.com/getinsomnia/insomnia) which is capable of storing the file path in the form data. I assume both postman and insomnia are built with web technology and shipped as native applications. Why is it not possible in such a good app like the postman? It's been a long time since this feature was requested.

**Comment by harryi3t** [comment]
This is being tracked here https://github.com/postmanlabs/postman-app-support/issues/4320
