### ISSUE TITLE
use of Auth-Token in response body causes ReferenceError Token is not defined

### ISSUE THREAD

**Issue by mmothers** [a85/POSTMan-Chrome-Extension#2338]
Using Windows (win7) Postman client 4.7.1

When setting up test variables the following will cause a postman error "There was an error in evaluating the test script: ReferenceError Token is not defined":

var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("Auth-Token", jsonData.Auth-Token);

If I change my code such to return 'AuthToken' in the body (removing the hyphen) and the arg above to jsonData.AuthToken  then all is well.

It is very common to use hypen's.  Why is this an issue?

**Comment by sdnts** [comment]
@mmothers What you've shared above is invalid JavaScript. Since `Auth-Token` uses characters that have special meaning, the correct way to do what you want would be this:

var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("Auth-Token", jsonData["Auth-Token"]);

Closing this, feel free to reopen if I misunderstood.

**Comment by mmothers** [comment]
Thanks!  that did the trick.
