### ISSUE TITLE
Latest Interceptor/Postman Chrome add-ins don't have Proxy

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2349]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Chrome
3. OS details: Win X
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Recent
6. Expected behaviour: Clicking the Interceptor icon should show a toggle for turning on Interceptor AND a toggle for turning on proxy settings (for testing mobile over same wi-fi)
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by sdnts** [comment]
@geoffnco The Postman chrome app has the interceptor, and the standalone app has the proxy.

The native Postman App does not have the interceptor icon because it cannot intercept requests made through Chrome. 
This is why we have the proxy on the standalone app.

Closing this, feel free to reopen if you have questions.
