### ISSUE TITLE
PM does not send cookies if Origin is set 

### ISSUE THREAD

**Issue by c3cris** [a85/POSTMan-Chrome-Extension#2431]
1. Postman Version: 4.8
2. App (Chrome app or Mac app): Chrome APP 
3. OS details: OSX 10.12
4. Is the Interceptor on and enabled in the app: On and Enabled
5. Did you encounter this recently, or has this bug always been there: Since 4.4+
6. Expected behaviour:  Cookie header should always be sent
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): None
8. Screenshots (if applicable)

If `Send Postman Token Header` is turned on in postman Settings:
Send a Get request with the following headers.
- User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
- Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
- Accept-Encoding:gzip, deflate, sdch, br
- Accept-Language:en-US,en;q=0.8
- Cookie:session={{session}} //some random cookie

**Update** I found out that if i don't send `Accept` header the `Cookie` will send. Any value added to `Accept` header will stop `Cookie` header even if i send Origin.

Screenshots: Hitting an endpoint that has the following code `var_dump($_SESSION);die;`

Without Origin: (works)
![0bbb6432-9421-11e6-92b6-f0d56239166d](https://cloud.githubusercontent.com/assets/1042198/19667272/c98e4f4a-9a04-11e6-84cb-194e56057bde.png)

With Origin ( does not work, no cookie sent)
![0bd01486-9421-11e6-9cc7-ec27ccfcdc5e](https://cloud.githubusercontent.com/assets/1042198/19667284/d68b4536-9a04-11e6-9077-9fdd01d8f5c7.png)

**NOTE:** This will be inversed if If `Send Postman Token Header` is turned **Off**
Now it won't send cookies if Origin isn't provided.

**Comment by vegetableman** [comment]
@c3cris The cookies will be sent irrespective of the headers you mentioned. Could you try sending the same headers to `https://httpbin.org/cookies/` and verify the response? (the response will have the cookie details)

**Comment by c3cris** [comment]
It seems that if a request has an origin and a referer cookies don't send ... Is this part of the HTTP specification?  

![screen shot 2016-10-27 at 10 53 28 am](https://cloud.githubusercontent.com/assets/1042198/19778923/b649b7fe-9c33-11e6-8e9f-d74d5239044f.png)
![screen shot 2016-10-27 at 10 53 21 am](https://cloud.githubusercontent.com/assets/1042198/19778925/b65dd6d0-9c33-11e6-9639-5e698a4d49a1.png)
Send both and cookies don't work
![screen shot 2016-10-27 at 10 53 14 am](https://cloud.githubusercontent.com/assets/1042198/19778924/b65cce34-9c33-11e6-91a7-4f6e1dde4d8f.png)

**Comment by sdnts** [comment]
@c3cris I tried to isolate the bug, sending only the Referer, Origin & Cookie headers. These three headers behave independently, your issue lies with the User-Agent & Accept headers.
Allow me to explain why this won't work on the Chrome App:

The Postman Chrome App with the Interceptor sends your request through the Chrome browser, which means it uses XHR. Your use case seems to be a limitation with XHR itself.

This will not be a problem on our native apps, because we use a NodeJS based runtime (Details [here](http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/)) to send your requests. This means that you have control over what is actually passed to the server. I encourage you to try out the native apps for use cases like yours. You can download them for Mac, Windows or Linux [here](https://getpostman.com/apps).

Let me know if I misunderstood, I will reopen this in that case.
