### ISSUE TITLE
[Hawk Authorization] Support Payload hash

### ISSUE THREAD

**Issue by sebastien-cote** [a85/POSTMan-Chrome-Extension#2458]
1. Postman Version: 4.8.1
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: OSX 10.12.1
 4. Is the Interceptor on and enabled in the app: yes
 5. Did you encounter this recently, or has this bug always been there: ~recently~ always
 6. Expected behaviour: Authorization: Hawk id="x1yz3", [...] hash="Yi9LfIIFRtBEPt74PVmbTF/xVAwPn7ub15ePICfgnuY=" [...]

Any request (ex.: POST request) that you can set a Body content, with Hawk Authentication selected.

**Comment by vegetableman** [comment]
@sebastien-cote Not a recent bug, as payload hash calculation is not supported on the app as of yet. Tagging it as feature, will keep you posted in this thread.

**Comment by stepanbokoc** [comment]
+1

**Comment by donald-jackson** [comment]
+1 please fix.

I see the Hawk library used (app/libs/hawk.js) has correctly implemented this unfortunately just not the payload passed in from Postman caller.

**Comment by LKI** [comment]
+1 as a thirsty user.

**Comment by ajwarren** [comment]
Additional +1, this fix would seriously help my team. Thank you.

**Comment by davidpanofsky** [comment]
+1 please!

**Comment by jcwilson** [comment]
Without this payload hash functionality, the Hawk Authentication feature can't be used for much of anything beyond `GET` requests.

As mentioned above, this isn't new functionality in the underlying hawk library js implemention. In fact, it was present at the time the Hawk Authentication feature was originally added to Postman, so its absence is curious. It should be fairly easy to pass in the payload to the underlying hawk js implementation in order to populate the `hash` attribute in the auth header.

**Comment by WillTaylor22** [comment]
+1

**Comment by liepieshov** [comment]
+1, when will you finish this?

**Comment by codenirvana** [comment]
We've added support for this in the latest Postman App (v7.1.0).

**Comment by donald-jackson** [comment]
@codenirvana is it possible to make this a configuration option? all legacy collections using Hawk are breaking now because they were implemented without payload hashing.
