### ISSUE TITLE
get access token but CONNECTION_FAILED

### ISSUE THREAD

**Issue by huixiaoao** [a85/POSTMan-Chrome-Extension#2473]
Hi,guys
 I`m using postman chrome app version 4.8.3
 There is some problems when I try to get access token OAthu2.0 like this.

![880b7350-ad81-11e6-9ea8-bb5855358479](https://cloud.githubusercontent.com/assets/7689783/20422130/6e43541c-ad8e-11e6-98ad-9f78f264f4eb.png)

I`m very sure about Internet Connection is ok.
and I can see proxy setting is the key point 
![image](https://cloud.githubusercontent.com/assets/23544730/20416385/08a5aae4-ad82-11e6-9949-86b0d23d9f2f.png)
How can I set the proxy server on app?

Thank you !

**Comment by sdnts** [comment]
@huixiaoao I see you're using the Chrome App. In that case, the App will use Chrome's proxy settings to make requests. Since Chrome uses the system settings, setting your system proxy to the one you want to use should get rid of your error.

From your other errors, it looks like Postman is not able to connect to the network at all. Could you set system proxy settings and check if you can make a simple request? (You can use `http://echo.getpostman.com.get`)

**Comment by abhijitkane** [comment]
@huixiaoao Feel free to re-open if you see this again.
