### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by fereshteee** [a85/POSTMan-Chrome-Extension#2477]
1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by fereshteee** [comment]
hey
i have a problem about postman
postman cant response my resquest GET or POST
when i want to get request,it replies me: could not get any response
i dont know what to do
my code in chrome replies correct but in postman i want to get request or curl,i cant.
version:4.8.3
win / x86-32
Chrome  54.0.2840.99
my os is windows 7 64 bit
![untitled](https://cloud.githubusercontent.com/assets/23580394/20455992/1618dea0-ae7f-11e6-8528-ac6cc4198e2a.jpg)
please help me
im python programmer
and this subject takes 1 week for me and i cant slove it alone

**Comment by seppestas** [comment]
I suppose you don't have any web server running on port 5000... Whatever you are trying to do, I'm pretty sure the issue is not caused by Postman.

Did you do the request using your browser on the same computer as the one that is running Postman?

Try to make the titles and the content of your issues a bit more clear by the way. "hey" is not very descriptive, neither is "i have a problem about postman".

**Comment by sdnts** [comment]
@fereshteee I think @seppestas is correct. Could you check your server to see if your endpoints work as expected?
To check if the problem does not indeed lie in Postman, you can use `echo.getpostman.com`, which is a test service.
