### ISSUE TITLE
Local disk form-data binary files are cached undesirably

### ISSUE THREAD

**Issue by ayancey** [a85/POSTMan-Chrome-Extension#2498]
1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: OS X 10.12.1 (Sierra)
 4. Is the Interceptor on and enabled in the app: Yes.
 5. Did you encounter this recently, or has this bug always been there: Encountered it recently, but not sure how long it has existed.
 6. Expected behaviour: When specifying binary files in POST requests, I expect the request to reflect the current state of the file when I press send. Instead, Postman seems to cache the contents of the file and will keep sending those contents, until I select another file, and then reselect the first file.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 8. Screenshots (if applicable): N/A

To reproduce:

1. Setup a basic POST request, with a binary file in the Body tab
2. Send request, make note of the contents of the file
3. Change contents of file on local disk, send request again (contents should be the same, before changes were made)

This may be a desired feature for some people, but I would like to at least have an option for Postman to not cache the files.

Thank you.

**Comment by sdnts** [comment]
@ayancey This is a limitation of the Chrome platform, or in fact, of any modern browser. The browser does not supply us the complete path of a file when it is uploaded. In fact, the client gets only a reference to the file (with a fake path) which is supposed to be read. This is for security purposes.

This means that when you send a request, there is no way for the app to re-read the file since it does not know where it is on your file system. Hence, it resorts to the cached version.

This, however, is not a limitation of our native apps. On our native apps, we can re-read the file because, well, they are not dependent on a browser. You can download them for OSX / Windows / Linux [here](http://getpostman.com/apps).

Closing this as there is unfortunately nothing we can do about this. Feel free to reopen if shifting to the native apps does not work for you either :)

**Comment by ayancey** [comment]
Sorry about that, I should have done more research before I submitted an
issue.
