### ISSUE TITLE
'#' is not encoded properly in param values

### ISSUE THREAD

**Issue by smmathews-cision-us** [a85/POSTMan-Chrome-Extension#2508]
1. Postman Version:4.8.3
 2. App (Chrome app or Mac app):Chrome
 3. OS details:MacOS 10.12.1
 4. Is the Interceptor on and enabled in the app:Unkown
 5. Did you encounter this recently, or has this bug always been there:Unkown
 6. Expected behaviour: supplying '#' in a param key should encode to '%23' similar to how '&' correctly encodes to '%26'
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Add a param in the builder, make the value 'ThisContainsAHash'. now insert a '#' character after 'A'. You'll notice the param value now cuts off the part of the value at '#' and past it (so the value becomes 'ThisContainsA'), and the url becomes something like 'localhost:8080/results?key=ThisContainsA#Hash'
<img width="874" alt="screen shot 2016-11-30 at 4 36 54 pm" src="https://cloud.githubusercontent.com/assets/21181346/20772388/3b65c7a0-b71b-11e6-9417-01a7f2e68906.png">
<img width="872" alt="screen shot 2016-11-30 at 4 34 16 pm" src="https://cloud.githubusercontent.com/assets/21181346/20772389/3b65fbd0-b71b-11e6-9b2c-3fd9f0facc18.png">

**Comment by sdnts** [comment]
@smmathews-ch Thanks for reporting this, we'll get on a fix for this.

**Comment by SamvelRaja** [comment]
@smmathews-ch  According to [RFC 1738](https://tools.ietf.org/html/rfc1738), '#' is represented as unsafe in query params as this is been widely used for fragments. 

But if you need to use it in your request, you can very well select the params -> Right click -> encode URI component.

![ecoding](https://user-images.githubusercontent.com/5114052/42077879-037a2744-7b98-11e8-8059-e2995fac37e5.gif)


Closing this now, as this is the expected behavior.
