### ISSUE TITLE
url encoding

### ISSUE THREAD

**Issue by sburtonctr** [a85/POSTMan-Chrome-Extension#2529]
1. Postman Version:  4.9.1
 2. App (Chrome app or Mac app): Windows app
 3. OS details:  Windows 10 Enterprise
 4. Is the Interceptor on and enabled in the app:  No
 5. Did you encounter this recently, or has this bug always been there: Recently - Last update.
 6. Expected behaviour:  Validate request

    1.  Open Postman
    2.  Execute URL with OData query + encoded text
         GET: [url]?$filter=(name eq 'AT%26T')&$orderby=created desc

     Result:
        There is an unterminated string literal at position 12 in '(name eq 'AT'.

     FYI:  I switched to the Chrome app where it works (4.9.0).

**Comment by dubiousdavid** [comment]
I noticed the same thing. I'm using 4.9.1 Mac App.

**Comment by SamvelRaja** [comment]
@sburtonctr @dubiousdavid This issue has been fixed in out latest canary build can you guys check the same.

OSX: https://dl.pstmn.io/download/channel/canary/osx_64
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64
Linux 32-bit: https://dl.pstmn.io/download/channel/canary/linux_32
Linux 64-bit: https://dl.pstmn.io/download/channel/canary/linux_64

**Comment by SamvelRaja** [comment]
@sburtonctr  @dubiousdavid This has been released with our 4.10.2 release, can you guys check the same from your end 😄

**Comment by sburtonctr** [comment]
@SamvelRaja Everything is working for me on my end.  Thanks
