### ISSUE TITLE
"SSL certificate verification" setting is missing in 4.9.2

### ISSUE THREAD

**Issue by mitursakoda** [a85/POSTMan-Chrome-Extension#2555]
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Mac App
 3. OS details: Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64 (macOS 10.12.2)
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: found it today
 6. Expected behaviour: setting mentioned in docs (https://www.getpostman.com/docs/ignoring_ssl) is not present in my app, hence I cannot disable SSL certificate verification.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by sdnts** [comment]
@mitursakoda I think you are on the Chrome App. If you go to Settings > About do you see a Chrome version listed there? If so, you're on the Chrome app, where the setting isn't present because we cannot control it. I'm on the native app, and I can see the setting on 4.9.2.
We're looking into making the native app and the Chrome app more differentiable.

Feel free to reopen if not.
