### ISSUE TITLE
Request headers are cached

### ISSUE THREAD

**Issue by rvdfox** [a85/POSTMan-Chrome-Extension#2611]
Recently i needed to check a set of api which uses authorization from request headers, and for first request it worked , but for subsequent request i was getting error, on further inquiry we got to know that 
the postman is sending same headers as was sent in first request.on the counter part SoapUI client worked every time.please have a look into this issue

 1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome 55.0.2883.87
 3. OS details: Windows 10 x64 pro
 4. Is the Interceptor on and enabled in the app: not enabled
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: successfull request always
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by sdnts** [comment]
@rvdfox If I understand correctly, you are generating an auth signature using parameters of your request right? What kind of authorization are you using?
Also, a little more detail about the actual request you are making would help us get to the bottom of this. No need for actual parameter values, just placeholders would do.

**Comment by mikey923** [comment]
Hi, I think I stumbled upon the same issue.  I was testing an API that required Basic Auth for some requests and No Auth for other requests.  I had 2 tabs open, both with an auth header.  On one, I started testing an unauthed service so I went to the Authorization tab and selected No Auth and made sure the header was removed under the Headers tab.

None of the code snippets (like generating the curl script) showed the auth header.  Upon sending the request the API complained I was an authorized user trying to use an unauth service.  Further investigation showed it was definitely getting the old auth info I had used from the previous test.

Once I figured it out I just opened a new window, instead of a tab, and it worked fine.

The API I was testing is fairly simple, just a JSON body and the JSON content-type header.

**Comment by talonx** [comment]
I encountered this too. Btw, why was this closed without any reason being given?

**Comment by prashantagarwal** [comment]
@talonx Can you download our native app and see if you are facing the issue there as well.

**Comment by rvdfox** [comment]
I tried that too, didn't worked, and even in the latest version its not working, switched to SoapUI

**Comment by kpashov** [comment]
Hello, I tried both the Chrome and the standalone apps and I am getting the same issue. Seems like this has been an issue since at least 2015...

https://stackoverflow.com/questions/31015522/cookies-are-being-cached-when-i-send-a-new-get-request

**Comment by drbuys** [comment]
Hi, I am having the same issues as above (in both the Chrome and the standalone apps). Would be great if someone could look into this please!

**Comment by kpashov** [comment]
@prashantagarwal Do you know if someone is looking into this?

**Comment by omaric** [comment]
I have also experienced this.

I've sent the same request twice in quick succession with and then without the authorization header, getting the same successful response. When I do the same thing in curl from the terminal, my credentials are rejected without the auth header. Unless our server is caching responses when it detects the user is using Postman, something is wrong.

Upon further inspection, it seems our server is setting cookies, something I didn't know Postman even had.

**Comment by steam0** [comment]
Can we reopen this issue? @a85

**Comment by Hibbem** [comment]
Please reopen, have the same issue on Version 6.0.10 (6.0.10)

**Comment by denebgarza** [comment]
Also running into this issue on 6.4.4 (6.4.4)

**Comment by tinhltdev** [comment]
me too, issue still happening, why close this post while don't have any answer
