### ISSUE TITLE
Authorization tab should trim key values

### ISSUE THREAD

**Issue by nlwillia** [a85/POSTMan-Chrome-Extension#2619]
Postman 4.9.2 in Chrome 55.0.2883.87 on win / x86-32

The Authorization tab should trim the input fields for values like OAuth keys, tokens and secrets.  These are almost always going to be pasted from somewhere else which makes it easy to pick up stray whitespace.  If trailing whitespace is treated verbatim, it creates an obscure and frustrating failure point when the request doesn't authenticate.

**Comment by sdnts** [comment]
@nlwillia That's a great idea. Adding this as an enhancement, will keep you updated here!

**Comment by shamasis** [comment]
We should not actually trim it since it may interfere with testing.

- We could show one-time warning when pasting in such input boxes.
- Furthermore, we could start showing whitespaces like most editors do
- We should make issues like this easy to debug, but definitely not trim inout automatically.

**Comment by a85** [comment]
We have decided against trimming values automatically and in general not modifying user input unless there is an explicit direction. Closing this.
