### ISSUE TITLE
Postman Collection Runner - subsequent iterations only execute 1st request in the collection

### ISSUE THREAD

**Issue by cunc01** [a85/POSTMan-Chrome-Extension#2634]
Good morning.  I've been running into an issue when using the Postman Collection Runner.  When setting the Iteration value so that the collection runs multiple times, I'm finding that after the 1st iteration, the subsequent runs are only executing the 1st request in the collection.  

Version/App Information:
 1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome 55.0.2883.87
 3. OS details: win / x86-32
 4. Is the Interceptor on and enabled in the app: N
 5. Did you encounter this recently, or has this bug always been there: Recent; but never attempted prior to
 6. Expected behaviour: if iteration set = 5, the collection in its entirety would be executed 5x
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): console logs dont immediately display any error
 8. Screenshots (if applicable): N/A

Steps to reproduce the problem:
1. configure a Postman collection with 6 Post requests, that execute sequentially
2. open the Collection Runner
3. ensure the new collection is expected
4. set environment
5. set iteration = 5
6. set delay = 5
7. no data file
8. set Persist Variables tp false
9. click Start Test
10. let Runner execute

* i'd like to note that I have a conditional loop on the 5th and 6th requests.  on the 6th request, when the condition is met, i no longer set the next request (which would be go back to the 5th request).  the loops ends, and i have an if statement that clears out all temporary variables.

exepected result: 
the collection, and all requests within, is run 5x

actual result:
the collection runs through all requests successfully on the first run through, then on iterations 2-5, the Runner only executes the 1st Post request in the collection

**Comment by sdnts** [comment]
Hey @cunc01! Am I correct in assuming that you have a conditional loop in the 5th & 6th requests, and it loops over these two for some number of times, until it exits?
I set up a simple collection that does something similar [here](https://documenter.getpostman.com/view/214062/gh2634/2SLWzG). You can import this to your app. This collection behaves similarly.

I might be wrong here, but are you depending on the UI to judge how many times a request is run? The Chrome Collection Runner only displays each request once. In successive iterations, the test count below it increases to indicate that the test / request ran.

Could you open up the Collection Runner DevTools ([Instructions](http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/)), switch over to the Network tab, and check if your requests are sent correctly? You can filter out only XHR requests to make this easier to track.

Note that you'll have to open the DevTools for the Runner window (runner.html in `chrome://extensions`, under Postman)

In any case, we recently pushed a major update to the Runner on our [native apps](https://getpostman.com/apps), and you should be able to see each request separately there. I'd recommend switching, since Google will end support for Chrome apps later this year.

**Comment by cunc01** [comment]
hi @madebysid !

you are correct, the conditional loop is in the 5th and 6th requests. 

basically it behaves as such,
- the request (eg. CreateEntity) increments a string value (eg. name = "entity X") on each successive run
-- when complete, sets next request (eg. UpdateEntity)
- then the next request (eg. UpdateEntity) updates other values on the entity, and after the request completes, a test checks if the aforementioned string name = "entity 30"
-- IF name !== "entity 30", then go back to CreateEntity, ELSE exit loop

I had previously run through devtools as well, and it didn't reveal anything obvious as to why its behaving as such.  After the 1st iteration, the 2-5 iteration only executed the first call of the collection.

As you suggested, I installed the native app, and when running the same exact collection, the runner executed everything within on each successive iteration.  its great!   

On that note, I had a follow-up question.  With the Chrome App, when the Collection Runner was executing, I could still view the Builder window, and within it, view the environment variables (eyeball icon/button) change as the runner is executing.  On the native app, it doesn't behave the same way.  Because of that, I wanted to ask if there was a way to view variables (and their values) from the Runner window.  

Please let me know.

Thanks!

**Comment by sdnts** [comment]
The `Persist Variable` option in both Runners is used to configure this behaviour. Basically, when you have it set to ON, any variable changes you make are propagated to the main window (they are persisted) at the end of the run. On the other hand, if it is OFF, variable changes take place during the run only in the Runner window, but as soon as the run completes, variables are back where they were before the run started (they aren't persisted).

I'm guessing you had the `Persist Variables` option checked in the Chrome app, but not in the native app. Could you try doing this and check if this solves your issue?

**Comment by cunc01** [comment]
the Persist Variable option is definitely enabled on the Runner window, but the environment variables as they are displayed in the Builder window are not updated as the Collection runs.

Alternatively, I can grab the response value from the Runner window by clicking the Request>ResponseBody option.

I just found it odd that the variables as they're set in the Runner window, aren't in sync with the Builder window.  I wasn't sure if this was by design for the native app.

**Comment by sdnts** [comment]
Ah, the native app runs your collection in a completely separate NodeJS sandbox. You won't see your environment update in real time on the main window, but they'll be updated once the run is completed. You can verify this by logging out (console.log) your environment variable at the end of each request.

Is the final state of your environment correct?

We're looking into making handling this a little more intuitive.
