### ISSUE TITLE
CSV values aren't running in Collections

### ISSUE THREAD

**Issue by proverbguy** [a85/POSTMan-Chrome-Extension#2641]
1. Postman Version:4.9.2 win / x86-32
 2. App (Chrome app or Mac app):Chrome 55.0.2883.87
 3. OS details:
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: not a bug -- probably operator error
 6. Expected behaviour: trying to use a csv file to run a collection of upc codes  -- csv, and upc codes, seem to preview correctly (see screenshot) but when i start a test in the collection runner the results are 0 passed 0 failed.  I'm not at all a programmer so i'm stumbling through this.  just trying to find a quicker way of accomplishing a very mundane task.
![screenshot 2017-01-17 12 10 25](https://cloud.githubusercontent.com/assets/25180078/22031512/d2663780-dcae-11e6-8723-4051d199d1b4.png)
![screenshot 2017-01-17 12 09 12](https://cloud.githubusercontent.com/assets/25180078/22031542/e7eccf9c-dcae-11e6-9c75-5052a46a6fbf.png)
![screenshot 2017-01-17 12 09 45](https://cloud.githubusercontent.com/assets/25180078/22031554/f19524ae-dcae-11e6-9243-f73f33e1a225.png)
![screenshot 2017-01-17 12 09 24](https://cloud.githubusercontent.com/assets/25180078/22031553/f1944dea-dcae-11e6-8753-a27ba745626f.png)

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
see attached

**Comment by sdnts** [comment]
Hey @proverbguy, the counts in the Runner window are actually the number of tests passed / failed. Since I see you do not have any tests written, these counts aren't updated.
You write tests to verify if the response received from your server is as you expected. You can test stuff like the presence of a value in the response body, the response status code, etc.

[Here](https://www.getpostman.com/docs/writing_tests) are docs to help you get started with Postman tests. There are also some examples [here](https://www.getpostman.com/docs/testing_examples)

In your case, what is happening is, the requests are being sent correctly, with the variable `vUPCCode` substituted correctly, but the lack of tests elicits the 0 passed / 0 failed state.

**Comment by proverbguy** [comment]
Thanks @madebysid.  I'm not meaning to test for anything.  I'm trying to use an api get request and UPC code to capture product data.  Is there a way to run a csv containing upc codes with individual get requests and then, export the result?

**Comment by sdnts** [comment]
Ah, so you just want the request & responses, while reading variables from a file? In that case, the Postman App wouldn't be the correct tool to use. You should look into [Newman](https://github.com/postmanlabs/newman). Newman is a command line collection runner.
Newman's reporters should be helpful. Since Newman does not log out any responses, what you can do is keep logging out the responses from your requests, and pipe Newman's output to a file.
