### ISSUE TITLE
How to open postman in chrome

### ISSUE THREAD

**Issue by prolificcoder** [a85/POSTMan-Chrome-Extension#266]
Probably I don't know a simple trick but I am seeing blank in the url and there is no button option for postman, so wondering how do I open this after closing the tab.

**Comment by NargisP** [comment]
Very simple answer enter " chrome://apps " in your chrome browser

**Comment by ghost** [comment]
Hi all,

So am I right in thinking there basically is no way to launch Postman at all in Chrome other than enter the raw chrome://apps Url.

Why?

Didn't people feel it was worth a button on the toolbar like all other extensions?

**Comment by sdnts** [comment]
@thefraj Actually, Postman is a Chrome App, not a Chrome Extension. As such, Chrome does not allow us to pin the app to your toolbar like other extensions (since it isn't one). It is supposed to show up in Chrome's App Launcher (`chrome://apps`)

With regard to Google's recent [announcement](http://blog.getpostman.com/2016/08/23/using-the-postman-chrome-app-implications-from-the-recent-google-announcement/) though, I'd recommend switching to the native apps to make sure you don't miss out on future developments.

**Comment by AmazonTest01** [comment]
I found one solution..it works for windows7, 8 and 10.

Open Postman
right click on footer bar and set "Pin to progress to task bar"
