### ISSUE TITLE
Cookies are listed twice in auto-generated cURL docs

### ISSUE THREAD

**Issue by bripkens** [a85/POSTMan-Chrome-Extension#2675]
Cookie headers explicitly set via the headers menu point are listed twice in the auto-generated cURL docs:

<img width="374" alt="screen shot 2017-02-04 at 07 39 45" src="https://cloud.githubusercontent.com/assets/596443/22616433/4f07999e-eaad-11e6-9e11-31015d337366.png">

 1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Mac
 3. OS details: MacOS Sierra
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Always been there
 6. Expected behaviour: Be consistent with the other language / tool docs: Just show the `--header` argument
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Not applicable
 8. Screenshots:

<img width="374" alt="screen shot 2017-02-04 at 07 39 45" src="https://cloud.githubusercontent.com/assets/596443/22616433/4f07999e-eaad-11e6-9e11-31015d337366.png">

<img width="1374" alt="screen shot 2017-02-04 at 07 43 05" src="https://cloud.githubusercontent.com/assets/596443/22616445/99b7db5c-eaad-11e6-8ea1-2dbeb00c9cd0.png">

**Comment by vegetableman** [comment]
@bripkens Thanks for letting us know about this issue 👍 . Will keep you posted ^_^.

**Comment by shreys7** [comment]
Hey @bripkens This seems to be a problem with the underlying library which we used to generate code snippets.This bug has been fixed in the documenter view of collection. If you are signed in to postman, can you open the documenter view of your collection to verify if this is solved ?
Steps:
1. Save your above request in a collection
2. Open the arrow button menu that appears besides the collection name.
3. Click on `View in web` button
4. See the generated code snippet for cURL.

**Comment by bripkens** [comment]
Yes, seems to work fine now. Thank you!
