### ISSUE TITLE
Add configuration to disable temporary headers

### ISSUE THREAD

**Issue by adkathuria** [a85/POSTMan-Chrome-Extension#2689]
I see the response headers as Content-Encoding: gzip even without specifying the Accept-Encoding: gzip as the input. Is it the Chrome code that inserts the header "Accept-Encoding: gzip" during the request?

**Comment by prashantagarwal** [comment]
@adkathuria are you on Postman native app or Chrome app. Also can you provide me with the version number of your Postman app.

**Comment by ddecesare** [comment]
I know this issue was closed but I'm seeing the same issue. I'm using Postman native app (version Postman for Windows  Version 6.0.10  win32 10.0.16299 / x64). 

It appears Postman is automatically sending the header "accept-encoding: gzip, deflate". I noticed this because while that worked for Wildfly 8, it does not work for Wildfly 11. Wildfly 11 needs the header to look like "Accept-Encoding: application/gzip".

When I manually add "Accept-Encoding: application/gzip" to the header, the default Postman header is no longer sent.

**Comment by MaxRev-Dev** [comment]
![image](https://user-images.githubusercontent.com/24393967/41810398-4213e0ee-7706-11e8-86ed-cb3de9170aab.png)
+1 Same issue. Postman handles decoding only in chrome app

**Comment by cabrinoob** [comment]
Have the same pb here with postman native app 6.3.0. 
Postman seems to send `Accept-Encoding: application/gzinp, deflate` and I have an error message "Could not get any response".

The same request works fine with fiddler because fiddler does not add any accept-encoding header silently.

**Comment by IanKemp** [comment]
How is this incredibly important bug not addressed yet? If I send a request I expect it to have the headers I explicitly set or allowed to be sent via the program's options, I do NOT expect additional headers like `accept-encoding` (name is a violation of the HTTP spec BTW) to be appended! Doing so breaks the whole point of an app that is supposed to allow for testing of HTTP requests!

Postman for Windows
Version 6.6.1
win32 10.0.17134 / x64

**Comment by IanKemp** [comment]
To get around this and essentially "unset" the unwanted `accept-encoding` header, manually specify `Accept-Encoding: identity` (see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding)).

**Comment by Luthien-in-edhil** [comment]
That's a big +1 from me. 

I was unaware that Postman added this header, which had me stumped for quite some time while trying to figure out how to enable HTTP gzip compression on a Solr connection. 

I know, I only have myself to blame for missing this cause for the weird behaviour that I saw, but still ... as IanKemp also says: it's not something that you would expect from an application that is specifically intended to test HTTP connections with. 

So, just that you are aware that there actually _exist_ use cases that are about the effect of adding the Accept-Encoding header ;)

Until it is fixed, at least add a message to the startup screen, for instance "WARNING! Postman adds hidden headers to your request!" instead of that "enabling warp engines" waggery (although I haven't seen that in a while).

**Comment by codenirvana** [comment]
@Luthien-in-edhil In the latest version of the Postman app, all these headers are visible under the "Temporary Headers" section.

**Comment by codenirvana** [comment]
> Doing so breaks the whole point of an app that is supposed to allow for testing of HTTP requests!

@IanKemp Agree, we are planning to add a configuration which turns off all the auto header injection.

Updated the issue title.

**Comment by lovelock** [comment]
most important is, because postman sends a request with that header, when the request code is copied from postman and then paste to terminal to run with curl, it would crash and I have to remove the gzip header manually.

**Comment by VicKetchup** [comment]
Linking the discussion from community forums, as that is what comes up on Google first for the issue: https://community.getpostman.com/t/disable-temporary-headers/5271

**Comment by PylotLight** [comment]
This was still being considered in mid 2019 is that right?
Is this setting still being worked on?
Look at this mess generated by the temporary headers:
 sessionid=e798ac6bbb62db95b9f3bc4a69e338f0; sessionid=7dbd00b00a4b418b5ab3c4555a93835c

**Comment by arlemi** [comment]
Hi everyone! 

We've released [Live Preview](https://community.postman.com/t/live-preview-is-out/11497) in the latest version of the app (7.21.0), this gives you the ability to see all the auto-generated headers as you build the request. You can also disable/override them before sending your request (including the `Accept-Encoding` one). Read more about this on [our Learning Center](https://learning.postman.com/docs/postman/sending-api-requests/requests/#auto-generated-headers) and let us know if you have any questions!
