### ISSUE TITLE
Not able to SSL Cert in Chrome App on Fedora

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2704]
1. Postman Version: 4.10.0
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: Fedora 25
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: First seen on 14 Feb 2017
 6. Expected behaviour: I expect to see a Certificates tab in the settings as per https://www.getpostman.com/docs/working_with_client_certificates
 7. Screenshots (if applicable)

![screenshot from 2017-02-14 17-26-55](https://cloud.githubusercontent.com/assets/24298159/22952613/a9f0cc6e-f2db-11e6-922c-1944ba781c87.png)

1. Submit a post to a URL that requires a client certificate
2. Select certificate from certificate store
3. Go into settings to update client cert for domain
4. No tab is present to edit client cert

**Comment by sdnts** [comment]
Hi @bkimbrou, the `Certificates` tab is only available in the native apps. This is because all Chrome apps will automatically use any certificates saved with Chrome.
If you want to send a certificate with the Chrome App, you'll need to add your certificate to Chrome, and then select it when you send your request.
On the native apps, you can add it from the `Certificates` tab. Feel free to reopen if I misunderstood.

**Comment by ghost** [comment]
Hi @madebysid, thank you for explaining why I cannot see the Certificates tab. However my main issue is that I cannot modify the certificate I selected for a particular domain once one has been selected, or if there is a way, I do not know how.

**Comment by sdnts** [comment]
@bkimbrou Are you talking about Chrome? Chrome caches certificates once you use them, so clearing this cache should help. I found [this](http://stackoverflow.com/questions/27848786/chrome-certificate-selection-appears-multiple-times/27859775#27859775), which might be able to help.
