### ISSUE TITLE
Feature Request: Ability to change favicon in postman docs

### ISSUE THREAD

**Issue by jaskarangump** [a85/POSTMan-Chrome-Extension#2719]
We have a pro account and planning to use postman docs. We have already changed the logo and domain. 
Can you add the ability to change the favicon as well.

**Comment by cmohs** [comment]
Hi, is this feature released already or is it in progress?
May be, it would be another issue, but from the user point of view it's the same issue:
It would be preferable, if the rich snippets would also provide a custom icon. Probably the bigger favicon?

**Comment by Radnet** [comment]
Is this feature going to be available soon? We also have a "Postman Pro" account and the release of our product documentation depends on this feature.
Thanks!

**Comment by godfrzero** [comment]
We've started working on this feature. As a first step, we're planning on having the the documentation automatically pick up the favicon from your custom domain. Favicon upload and whatnot will come in soon after that.

I'll post an update here again as we make progress.

**Comment by godfrzero** [comment]
Public docs using a custom domain will now display a custom favicon if available. For example, if your custom doc is hosted at `api.example.com`, the favicon at `https://example.com/favicon.ico` will be used. Redirects are followed (unless the browser is configured otherwise). HTTPS is required, to avoid serving mixed content.

The ability to upload a different favicon is still a work in progress, and I'll post an update here when it's out.

**Comment by a85** [comment]
This should be available now.

**Comment by phamnamlong** [comment]
I think this feature is broken now. Not sure if it can be fixed soon.

Right now there is still a link to Postman Favicon and somehow it takes precedence.


```
<link rel="shortcut icon" href="https://res.cloudinary.com/postman/image/upload/v1590399973/team/kgpvzzrhyabmcimcvkbd.ico" />
<link rel="shortcut icon" href="/favicon.ico" />
<link rel="shortcut icon" href="https://res.cloudinary.com/postman/image/upload/v1590399973/team/kgpvzzrhyabmcimcvkbd.ico" />
```

Thanks,
Long
