### ISSUE TITLE
Feature request: allow GET requests to have a body

### ISSUE THREAD

**Issue by sergionalin** [a85/POSTMan-Chrome-Extension#2729]
While this is a tad controversial, some pretty widespread services do work with GET requests w/ a JSON body (elasticsearch to name one). One of the reasons is to bypass the max header length restrictions imposed by many servers/proxies/loadbalancers.

See also:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html
http://stackoverflow.com/questions/978061/http-get-with-request-body

**Comment by Dareen** [comment]
+1

**Comment by sdnts** [comment]
@sergionalin @Dareen This is on our immediate roadmap. Will keep you guys posted!

**Comment by antoine-pous** [comment]
I don't understand why this feature is not yet implemented, the standard don't reject explicitly it.

**Comment by bfan1256** [comment]
Any updates on the implementation of this?

**Comment by ghost** [comment]
+1

**Comment by przemo098** [comment]
+1

**Comment by daveh-maShop** [comment]
Just installed latest Postman v6.0.9 .  Body still not allowed for GET operation.  Really needed to work with ElasticSearch.  This feature request has been around for years.  Can it be that difficult?  Forced to use another REST Client app to work with Elastic GETters that need a body.  Please advise on roadmap for this.

Thanks.

**Comment by Pac0o** [comment]
+1

**Comment by drjasonharrison** [comment]
Possible workaround discovered by duplicating a POST request with data in the Body tab, and changing the new request to a GET request.
While the Body tab is disabled, the body will be sent and included in the code output. This is also described in #2794

**Comment by daveh-maShop** [comment]
Jason,  Ok…  Thanks for the workaround.

**Comment by TheSHEEEP** [comment]
The workaround is fine, but why not implement this simple change in the main app?

**Comment by drjasonharrison** [comment]
#2794 is the issue to follow regarding a code fix.

**Comment by WhoSayIn** [comment]
+1

**Comment by unlucio** [comment]
+1

**Comment by iisdan** [comment]
+1

**Comment by twilco** [comment]
This seems like a pretty big oversight...

For anyone struggling with this, use https://insomnia.rest/ instead.

**Comment by pcals90** [comment]
+1

**Comment by bidiu** [comment]
+1

**Comment by adityavikasd** [comment]
+1

**Comment by frainmeng** [comment]
+1

**Comment by jlurena** [comment]
+1

**Comment by rodmaz** [comment]
+1

**Comment by misiekofski** [comment]
+1

**Comment by joeyJsonar** [comment]
+1

**Comment by Zoheb-hassan** [comment]
+1

**Comment by dan101ways** [comment]
+1

**Comment by imtrobin** [comment]
+1

**Comment by sankalp0o** [comment]
We're working towards making body/no body as a request level configuration rather than depending on the method. This will enable GET methods to have a body.

This is what it might look like:
![get with body](https://user-images.githubusercontent.com/7601762/43394439-62518314-9418-11e8-859a-9c60184904fd.png)

One question that arises here is should we discard the body data when someone toggles this off? Or should we keep the data but disregard it while sending the request? 
It seems some people expect this data to be discarded completely based on issues like https://github.com/postmanlabs/postman-app-support/issues/4502 and https://github.com/postmanlabs/postman-app-support/issues/2794

Thoughts? @a85 @shamasis @kamalaknn

**Comment by andystroz** [comment]
+1

**Comment by imtrobin** [comment]
discard, with error/warning

**Comment by tomstoreysn** [comment]
@sankalp0o I would keep the data, and simply not send it, perhaps disabling/greying out the body to indicate that it isnt in use. Personally, I would find it incredibly annoying if I turned the option off and it all disappeared and had to fill it back in.

**Comment by thomasazdon** [comment]
Has this been fixed?  I do not see in my postman where to enable body in a get request?

**Comment by numaanashraf** [comment]
@thomasazdon This feature is not out yet. We are working on this now and would post updates here when this feature is available in our Canary and stable apps.

**Comment by JTBlum** [comment]
> @thomasazdon This feature is not out yet. We are working on this now and would post updates here when this feature is available in our Canary and stable apps.

Thank you! The work-around isn't working for me, and I'd like to not have to switch products.

**Comment by a85** [comment]
Everyone: this is going to be out in 6.5 soon releasing over the next 2 weeks!

**Comment by a85** [comment]
GET methods can have a body now. The feature is out in production with 6.5+
<img width="543" alt="screenshot 2018-11-08 07 11 59" src="https://user-images.githubusercontent.com/653409/48207528-abc66080-e325-11e8-9467-4e291607b99d.png">

**Comment by jijiechen** [comment]
This feature confused me a lot. Can you add a switch to turn this feature off? Ideally, this feature should be default to off, since it's not following typical HTTP practice. 
People send payload through GET requests by mistake sometimes (they just change URL on a past POST tab) and get 417 or 400 responses from servers. It spend us an hour to questioning the Postman could be the source of the issue.
