### ISSUE TITLE
POSTMAN is rounding long integer values where it shouldn't

### ISSUE THREAD

**Issue by jbnok** [a85/POSTMan-Chrome-Extension#2736]
1. Postman Version: **4.10.2**
 2. App (Chrome app or Mac app): **Chrome App**
 3. OS details: **Windows 7 Professional x64**
 4. Is the Interceptor on and enabled in the app: **No**
 5. Did you encounter this recently, or has this bug always been there: **Unclear, I have only discovered it recently**
 6. Expected behaviour: **I should be able to have the number I want as it is a resourceId from another call**
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): **N/A**
 8. Screenshots (if applicable)

_Steps to reproduce the problem:_

1. Retrieve an ID of 1003200000000001759
2. Put it into the environment (either manually or passing it in via the request) 
**_OBSERVE:_** it gets rounded to 1003200000000001760

**Comment by efenderbosch** [comment]
This is likely because javascript numbers are 64 bit, with 53 bits reserved for the integer part.

You can duplicate this in Chrome and Firefox by opening the console and simply using `alert(1003200000000001759)` it will echo back 1003200000000001780. For large integers you need to treat them like strings.

http://www.2ality.com/2012/07/large-integers.html

**Comment by jbnok** [comment]
@efenderbosch Thanks for the quick response to this. I was hoping to avoid having to do additional parsing and have support out of the box..

Thanks again

**Comment by efenderbosch** [comment]
No, problem. I just came to check on an issue I was interested in and happened to know what was causing yours!

**Comment by joelpresence** [comment]
See also https://github.com/postmanlabs/postman-app-support/issues/3368 .  This is holding us up from buying a bunch of Postman Pro seats since we use int64 ids extensively and we don't have the bandwidth to start sending back a bunch of "id_str" type hacks.  Otherwise we're just going to buy more units of PAW for Mac.  Thanks!

**Comment by joelpresence** [comment]
Hi @prashantagarwal - I noticed that you closed https://github.com/postmanlabs/postman-app-support/issues/3368 ... The reason I created *that* issue in favor of this issue is that it seems like *this* issue hasn't gotten any updates or attention since February 21, almost 7 months ago.  That worries me because we need to make a decision very soon about whether to pay for Postman or pay for Paw for Mac or another competing solution.  We cannot choose Postman if 64-bit integers are going to be rounded since we use them for Ids, and we're not going to start sending `"id_str": "int64 as a string"` just to accommodate Postman since we often have many ids per JSON response and we can't afford to bloat the payload size.

Can you give an ETA for when this will be fixed please?

Thanks!  :-)

**Comment by prashantagarwal** [comment]
@joelpresence . Pre request script and Test scripts inside Postman are written in Javascript. And as of yet Javascript does not support integers greater than 2^53. But this is under serious consideration by TC39 (https://github.com/tc39/proposal-bigint). So until it is supported by node, it is not possible for us to support this by default. That being said I can suggest you a work around that might solve your use case.

You can use some library like https://github.com/sidorares/json-bigint to parse your response rather than using JSON.parse(). Now to use this external library save the library code inside a variable and eval it in the first line of your test script. Refer [this](http://blog.getpostman.com/2015/09/29/writing-a-behaviour-driven-api-testing-environment-within-postman/) for some idea on how to use external libraries in Postman.

Let me know if this works for you.

**Comment by joelpresence** [comment]
Thanks @prashantagarwal !  I will try the json-bigint and let you know how it works.  :-)

**Comment by sureshnath** [comment]
Thanks to - https://mahasak.com/hacking-bigint-in-api-testing-with-postman-runner-newman-in-ci-environment-eb69961d16fc - working fine in postman 6.7.2
