### ISSUE TITLE
{{GUID}} can not be used as a GLOBAL VARIABLE as an INT

### ISSUE THREAD

**Issue by ManishaUni** [a85/POSTMan-Chrome-Extension#2741]
Hi Guys,

I am trying to do a test for creation of a product, wherein for one of the variable i am using the {{GUID}} value. For Example : A={{GUID}}. The response returns a value for the {{GUID}}. I want to store this value as a GLOBAL variable so that the value can be used in other tests as well. I want to store the value as a INT value because in the other requests (Get requests), i would be just putting the {{GUID}} value in the URL and run the request by calling that variable name.

But the value is getting stored as a CHAR and my tests are failing because of this.
Please help.

**Comment by vegetableman** [comment]
@ManishaUni Since the `guid` value is returned as part of the response. You could do `JSON.parse(responseBody)` and then set the value as a global variable using `postman.setGlobalVariable(variableName, variableValue)`. You could refer the doc: https://www.getpostman.com/docs/sandbox for more info on the api supported.
