### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by hlubovac** [a85/POSTMan-Chrome-Extension#2753]
- Close all tabs; close tabs to the left/right of current; close all but this - it's very frustrating to close them individually, especially after the "feature" of restoring them after the app is restarted has been added.

- Renaming variables so that all **available** occurrences are replaced (I do understand that some request items may not even be loaded within Postman and easily updatable). Even when those outdated request-items are loaded at a later time, those old variables can be deleted simply by recreating one temporarily by old name, then renaming it to desired (you want to be careful in making assumption related to what **looks** like a variable, as it perhaps isn't).

- Subfolders would be nice (without level limits)

Thank you!

**Comment by vegetableman** [comment]
@hlubovac The native app allows close all tabs, close all but this. You just need to right click on the tab name. 

Subfolder support is being tracked here: https://github.com/postmanlabs/postman-app-support/issues/907 and is being worked on.

Could you create two issues for : Close tabs to the left/right and rename variable occurrences?, so that it's easy for us to keep track of.

**Comment by a85** [comment]
All of these feature requests are covered in other issues. Closing as a duplicate.
