### ISSUE TITLE
Tests- JSON.parse(responseBody) extracted value doesn't correspond with the value in the response body

### ISSUE THREAD

**Issue by yelena1** [a85/POSTMan-Chrome-Extension#2772]
Hello, I have 2 variables for the environment. 
token
accountId

I have 2 APIs. API1 generates token in Tests:
var data = JSON.parse(responseBody);
postman.setEnvironmentVariable("token", data.token);

API2 generates accountId in Tests and uses the token from API1:
var data = JSON.parse(responseBody);
postman.setEnvironmentVariable("accountId", data.accountId);

I checked  The dynamically generated values in my environment after executing the APIs:
The token has been updated. But the accountId has an incorrect value. It doesn't correspond with the value in response body.
I think data.accountId comes from the other place not from the response body.
Could you please help me resolve the issue?

 1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): MAC app
 3. OS details: OS X 14.5.0 / x64
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hi @yelena1, are you using this in the Collection Runner or Newman with a data file? The variable name `data` is also used to refer to the data file in the test scripts. In your case, the local `data` would take precedence over the global `data`.

Can you also try doing a `console.log` right after API2's `JSON.parse` and check if this is what you expected? The logs would appear in the Postman Console (Cmd+Alt+C or View menu > Postman Console)

It would also be helpful if you could attach some screenshots here to help me better understand what the issue is. Be sure to redact any confidential info.

**Comment by mpereira-dev** [comment]
There is something off about responseBody. It doesn't work as expected.

```
console.log(responseBody); //{........."jobs":[],"status":"active"}
console.log(responseBody.status); //null
```

**Comment by prashantagarwal** [comment]
@yelena1 Can you update to the latest postman app and verify if you are still seeing this issue.

@mpereira-dev responseBody is string. You need to parse it and than you can access status property.
