### ISSUE TITLE
[FEATURE REQUEST] Postman Cloud Documentation - Please add the tests into the documentation

### ISSUE THREAD

**Issue by scenage** [a85/POSTMan-Chrome-Extension#2796]
Be good to have something like below. Just somewhere we can see the tests for each request.

NOTE: I'm by no means a UX'er so please don't judge me :P

![image](https://cloud.githubusercontent.com/assets/8476191/23774957/6636785a-057a-11e7-9dca-88b0b24c7e75.png)

**Comment by sdnts** [comment]
@scenage The Documenter is supposed to generate a publicly visible page that describes your API, and so it is generally not required (or wise) to show the tests (since tests are supposed to be an internal testing entity).

Think of it this way: You wouldn't want to expose what tests you run on a website, on it's landing page.

Have you looked into Newman's HTML reports? Maybe they'll fit your needs?
