### ISSUE TITLE
Can't run a collection using runner or newman

### ISSUE THREAD

**Issue by eko55** [a85/POSTMan-Chrome-Extension#2822]
Version/App Information:
 1. Postman Version:4.9.3
 2. App (Chrome app or Mac app): Chrome app
 3. OS details:Win 7
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there:Always(using postman for a several days)
 6. Expected behaviour: To be able to Export correctly the whole collection and to be able to run it using newman  in console or Collection Runner in Postman.

There is a problem when exporting collection from Postman.
For some of the requests there is not "event" attribute which normally contain the tests for the request.
That statement was proved after I imported the earlier exported configuration.(Some of the requests had no tests.)

Because of this reason,executing a "collection.json" file using newman fails miserably.The same thing is when using collection Runner in the Postman.

If you fix the json file by hand you can run the collection normally,but manually editing big numbers of tests is not really cool and productive.

Exporting as Collection v1 or v2 does not matter.The problem is present in both ways.

There is NO problem when executing the requests one by one.

**Comment by sdnts** [comment]
Hi @eko55, Does this happen for all collections in your case or only some of them? Do you have a collection I can verify this with? You can remove private data, I'm only interested in the overall structure.

**Comment by eko55** [comment]
Some of the tests show the same behavior no matter the collection.I made a collection with one of the test
and when I run it through the collection runner it shows 0 passed 0 failed.

![notestrequest](https://cloud.githubusercontent.com/assets/26481427/24047268/da58119a-0b2d-11e7-8aa6-5827f2d5f491.png)

![pic2](https://cloud.githubusercontent.com/assets/26481427/24047387/2d627aec-0b2e-11e7-81af-6ec97a8d9521.png)

**Comment by eko55** [comment]
The main question in my mind is why when exporting configuration in json format some of the information is lost,specifically the "event" attribute?Any ideas?

**Comment by sdnts** [comment]
@eko55 The collection runner's export format doesn't actually reflect the collection. It is a static structure that may be used to share collection runs. Are you expecting the `event` key in here?

Also, looking at your screenshots, it looks like different requests run in the Runner and the main window (the request names are different). Are you sure you're running the same collection in both places? The Collection Runner on Chrome does not update collections in real time right now. If you change a collection, you'll have to restart the runner. Maybe that's why you're not seeing any tests?

When you say `exported configuration`, do you mean a run export or a collection export?

**Comment by eko55** [comment]
The problem was that the requests(and tests in them) were not saved.I thought that when I close Postman all request are saved automatically,because after open it again all tests seem to be there.But obviously you should explicitly save your request before export.

**Comment by sdnts** [comment]
@eko55 Ah, indeed, nothing is saved to your collections unless you explicitly do it. This is to prevent accidental overwrites.
