### ISSUE TITLE
Difference in HTTPS response behaviour between Native and Chrome v4.10.5

### ISSUE THREAD

**Issue by kunagpal** [a85/POSTMan-Chrome-Extension#2874]
> Https calls returns empty results in windows Postman version 4.10.5, but same when we hit from Chrome app - postman version 4.10.5, response is displayed for the Https call.

Originally posted by @srpramod here: https://github.com/postmanlabs/newman/issues/944#issuecomment-290313838

 1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Chrome, native
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
Hi @srpramod, could you share more info about this issue? Are you facing this with all https calls? You could try sending a request to our echo service - `https://postman-echo.com/get`. Also, could you share a screenshot of the issue on native app along with any errors or output you see in the apps devtools and console? you can open them via `View->Show DevTools` & `View->Show Postman Console`

**Comment by srpramod** [comment]
Hi @numaanashraf, @kunagpal  , the issue i can explain. Below are the details: 
1. I have tried to run the link 'https://postman-echo.com/get' in the Postman windows,, response is displayed. 
2. Similarly I have multiple https request with Post and Get Method for which no response is getting displayed. 
3. But when same when proceed in the Chrome app - postman, i am getting the response for both Post and Get method. This is been tested in critix environment - chrome browser - postman app.
4. When same is been carried out in Postman windows, no response.
5. For the same https request post/get i have placed the cert file in the setting, then also no response.
6. From the console for the https request call - the error message is 'Error: SSL Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE'.

**Comment by srpramod** [comment]
Hi @numaanashraf , @kunagpal , The above information helped you?. Please let me know.

**Comment by mbniehues** [comment]
My team is facing an issue that I believe is the same thing. We're using Postman Windows native client 5.3.2. I get ```Error: SSL Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE``` when using HTTPS to POST to our production REST API. However, this works for other team members.

One of our team members gets the error when using HTTPS to POST to our staging REST API. However, I'm able to do that just fine. All of that is with "SSL certificate verification" turned on. Turning off "SSL certificate verification" is the only solution for everyone to be able to use HTTPS to POST to both our production and staging API's. I like the idea of having that on, though, since we want to catch any real problems with our certificates.

The only explanation I can think of is that for myself and the other person having the problems, we previously ran some requests when the servers were misconfigured. Could it be that while the servers were misconfigured bad certificates got cached somehow? I can't find any way to get them to refresh. We don't have any custom Client Certificates set up.

As a final note, the SSL certs on our production and staging API's are fine. They're not self-signed. No cert issues in browsers or with other 3rd parties using them via HTTPS. That combined with the fact that only some users get the problem, makes it pretty certain Postman has an issue here. It would seem there has to be some problem with Postman either holding onto bad certificates and being unwilling to accept good ones after that or randomly giving the ```UNABLE_TO_VERIFY_LEAF_SIGNATURE``` error.

**Comment by philipstratford** [comment]
I'm just trying to migrate to using the Native app in Windows 10 (64-bit) and think I might be encountering this same issue. In the Chrome app I get a `400 Bad Request` response and my custom error message is displayed, but in the Native app with the exact same request I get a `401 Unauthorized` response. Screenshots below.

![chrome 2](https://user-images.githubusercontent.com/7631595/42879785-ca23ea7e-8a89-11e8-9156-f932e2dcb118.png)
![chrome](https://user-images.githubusercontent.com/7631595/42879786-ca3bfb32-8a89-11e8-88d6-5dbba59b1e95.png)
![native 2](https://user-images.githubusercontent.com/7631595/42879787-ca54778e-8a89-11e8-991a-7f4401097eae.png)
![native](https://user-images.githubusercontent.com/7631595/42879788-ca733caa-8a89-11e8-8690-2bb567f0334f.png)

**Comment by mbniehues** [comment]
As an update to my previous comment, our issue was a missing intermediate certificate in the chain. Web browsers didn't have a problem with it, but Postman and some other applications seem to be more picky. After we resolved the certificate issue, all of our team is able to run with `SSL certificate verification` enabled.

**Comment by codenirvana** [comment]
We are tracking this issue here: #4726
