### ISSUE TITLE
Body content for GET request still set in pre-request script request.data

### ISSUE THREAD

**Issue by mattdeluco** [a85/POSTMan-Chrome-Extension#2921]
If a request has content set in the body and the method is changed to GET, the body tab is no longer active or available to be selected.  However, in a pre-request script the content from the body tab is still available in request.data.

Given that the body tab is disabled my expectation would be that there is no body content at all.

Version Info
 1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Chrome
 3. OS details: macOS 10.12.3
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Encountered recently, only started using Postman recently.
 6. Expected behaviour: request.data is empty
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): n/a
 8. Screenshots (if applicable): n/a

Steps to reproduce the problem
 1. Create new request whose method is POST
 2. Add content to body
 3. Change request to GET
 4. Create pre-request script logging request.data to console
 5. Make request
 6. console should have log with body content set in step 2

**Comment by antonlva** [comment]
In addition to this bug: duplication of POST request and changing it to GET works within preserving request body as well. 

We've just got some fabulous moments investigating why our backends are reporting xss-attacks without any visible payload sent to them (it were just a duplicates of previous POST Postman duplicates with sampled XSSs).

**Comment by kamalaknn** [comment]
Hy @mattdeluco @antonlva 

Postman Collections have always treated request body independent of the request method. That means technically you could still have a request body for a `GET` method but they're not used while sending the request.

We've been getting [requests](https://github.com/postmanlabs/postman-app-support/issues/2729) to enable adding body for `GET` requests. 

Postman as a tool will continue to support adding body irrespective of the body. We'll work on adding more UI indicators that a body is present so that you don't trip over things like this.

**Comment by mattdeluco** [comment]
The body isn't quite independent of the request - if the request is set to GET, the UI disables the body tab.

And while some parts of Postman may not use the body content in a GET request, request.data in the pre-request script will not be empty, which was really the issue here.
