### ISSUE TITLE
[Feature request] - show response in the generated API doc

### ISSUE THREAD

**Issue by NikitaSavik** [a85/POSTMan-Chrome-Extension#2936]
While the docs are very nice and useful, most of the developers would like to see what kind of response they get on the given request.  E.g. this type of information is required by 3rd party developers right now and this is the reason I can't use postman as a doc-generator.

**Comment by albertkurnia** [comment]
is this already developed?

**Comment by numaanashraf** [comment]
@albertkurnia Yep. You can save responses as 'Examples' and they show up in the generated documentation.

Docs: https://www.getpostman.com/docs/v6/postman/sending_api_requests/responses

**Comment by albertkurnia** [comment]
oh my bad. thank you @numaanashraf

**Comment by miraclebg** [comment]
@numaanashraf Yes, there are examples but what is lacking here is the ability to actually describe and define a response schema - much like with RAML.

Why is it important?

Because an example is just an example.

First - it will not explain what the response and its properties are about.
Secondly - yes, it does hint the types of the returned data but it is not clear which of them are required to exist and which not.

I've been fighting to find a tool which would somehow compliment Postman usage and allow me to define the schema but so far without any luck.

This feature to me is a must and you should think of adding it in - along with the examples :)

**Comment by godfrzero** [comment]
The request description is markdown, and this sounds like something that can be added there. Have you experienced any problems or shortcomings with this approach?

**Comment by miraclebg** [comment]
I saw some information about this but i can't seem to be able to find out how to do it? Where do you define this? In the examples themselves? Or in the generic API call description?

Best thing would be to be able to define this per response type (200, 500, etc).

With a schema definition much more can be accomplished in terms of automation, testing and code generation.

Describing the api with text / markdown / other method only allows this information to be looked up by a human - and not by automation tools.

A schema on the other end would allow to verify / test the API based on it with various tools (and the Postman monitoring for example). An automated monitor can verify against the schema if all the required properties of the response are actually there and they are with the correct type / contain the correct data.

I understand we can code a test for each api which verifies the same but it is a lot manual work which can be automated to something like 99% based on a simple schema.

Sorry if i am not explaining this properly :))

**Comment by godfrzero** [comment]
Right now, it'll be in the request description. We're looking at adding descriptions to the example responses as well, so that's where this would be added in the future.

Testing against a schema as a built-in feature is something we're not tracking yet. Could you create a new feature request ticket for this, along with an example use-case?

**Comment by ratpik** [comment]
@miraclebg - You could save your schema as an example response and use that to validate your responses.

I often use something like the code snippet below to validate my response from API against a JSON schema. You can do that with a RAML schema definition too.

```
pm.test("response should match schema", function() {
  let response = pm.response.json();
        
  pm.expect(response).to.be.an('object');

  // Use the schema hosted on Postman Mock Service (private or public)
  pm.sendRequest("https://1234.mock.pstmn.io/json/myservice/v1.0.0/myschema.json", function(err, schema) {
    pm.expect(err).to.be.a('null');
    pm.expect(tv4.validate(response, schema)).to.be.true;
  });
});
```
