### ISSUE TITLE
Mark 'Status: 401 Unauthorized' in a bigger font and/or with red text

### ISSUE THREAD

**Issue by HaraldNordgren** [a85/POSTMan-Chrome-Extension#2945]
When sending a request I would like problematic error codes to be displayed more clearly.

I feel like the small text at the top right corner is too easy to miss.

**Comment by vkaegis** [comment]
Hey @HaraldNordgren, we intentionally keep the status codes neutral since some users intentionally test their requests for erroneous response codes, where an implementation like this could cause false positives.

I'm keeping this as a feature request for being able to configure how you want to represent the codes though.
