### ISSUE TITLE
Generated code snippets incorrectly escapes quotes

### ISSUE THREAD

**Issue by marr** [a85/POSTMan-Chrome-Extension#2947]
1. Postman Version:
 2. App (Chrome app or Mac app):
Mac App
 3. OS details:
OSX El Capitan
 4. Is the Interceptor on and enabled in the app:
?
 5. Did you encounter this recently, or has this bug always been there:
Not sure, I assume it's always been there.
 6. Expected behaviour:
When I click _Code_ to copy a request, I expect the Headers to be properly escaped to pass into a shell for execution.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

1. Create a request which includes a header value containing a string. For example,
Key: if-none-match
Value: W/"1234"

2. Click the _Code_ link and observe the snippet generated:
```
if-none-match:'W/\"1234\"'
```
This is incorrect, as the values do not need escaping when wrapped in single quotes. The correct output would be:
```
if-none-match:'W/"1234"'
```

**Comment by q42jaap** [comment]
Hi, this issue is still present, not only in shell command, but all versions of `generate code snippets`. strings with " are escaped twice, when you use NodeJS Request, a value of
```
headerWith"
```
is escaped to
```
  headers: 
   { myHeader: 'headerWith\\"'},
```
while `"` quotes don't need to be escaped in a `'`-quoted string, the `\` needs to be. So it would seem that the general layer of sharing data is escaping and the particular format is also escaping.

Another example, NodeJS Native, uses `"`-quoted string:
```
"headers": {
    "myHeader": "headerWith\\\"",
```

**Comment by abhijitkane** [comment]
<img width="514" alt="Screen Shot 2019-04-19 at 09 06 32" src="https://user-images.githubusercontent.com/681190/56404106-72a1fd00-6282-11e9-9bae-6f2b99f7c68c.png">

@marr @q42jaap Not able to reproduce this anymore. Feel free to add a comment if you're still seeing this on Postman 7.x.
