### ISSUE TITLE
POSTMan requests blocked by ZSCALER

### ISSUE THREAD

**Issue by junejosheeraz** [a85/POSTMan-Chrome-Extension#3001]
1. Postman Version: 4.10.7
 2. Chrome app
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Always been there
 6. Expected behaviour: It should work like Chrome Browser do
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): None
 8. Screenshots (if applicable) 
![image](https://cloud.githubusercontent.com/assets/1990207/25743395/0e15e9d8-318c-11e7-96b1-baf627266aaa.png)

I am trying to access a [Northwind Service] (http://services.odata.org/V4/Northwind/Northwind.svc/Categories) but my request is getting intercepted by Zscaler.

I access the same link from Chrome or IE it works fine. I am expecting POSTMan to do the same..!

**Comment by taschana** [comment]
Same issue here. Hope for a fix/way to authenticate Postman with the zscaler.
Version 4.10.7
Win7, win / x86-64
Chrome 58.0.3029.110
Interseptor-Status doesn't matter (tried before and after installation)
Screenshot would show the exact same message as the reporter.

Inner-network calls on Postman work just fine, anything else (for example: google) can't be processed, as the postman does try to show the Website of Zscaler, but obviously can't show it completely and cannot allow authentication. 
Chrome itself already is authenticated.

As far as I understood, Zscaler is placing one (or more) cookies which signal the browser is authenticated. In Chrome I could find these cookies:
![image](https://cloud.githubusercontent.com/assets/17772497/26162189/5b29cad4-3b26-11e7-9013-4950580f9f72.png)
If one were to delete all cookies, Zscaler would force an authentication by the company's method before allowing calls to the internet again. Maybe that's happening with Postman.

**Comment by harryi3t** [comment]
Postman does not support opening dilog boxes like browsers
But it does support cookies!

### Postman Chrome App
It can use cookies from the chrome browser. You need to use [postman-interceptor](https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo/related) (install the extension in chrome and then turn it on in the Postman app)
![image](https://user-images.githubusercontent.com/5207331/30853437-6b8b4304-a2cc-11e7-8625-a25493fc6743.png)
@junejosheeraz @taschana  Since this will automatically use cookies from the browser, no extra action is needed. This should fix it.

### Postman native Apps
For those you are using native apps, they can copy their cookies from the browser to the Postman app
1. click on `cookies`
![image](https://user-images.githubusercontent.com/5207331/30853316-13af59a4-a2cc-11e7-9964-dbf8cd8620b2.png)
2. edit an existing cookie
![image](https://user-images.githubusercontent.com/5207331/30853330-1d54851a-a2cc-11e7-9ee8-a807835016c7.png)

**Comment by harryi3t** [comment]
let me know if this works

**Comment by junejosheeraz** [comment]
Postman-Interceptor extension was missing. Once installed and enabled in PostMan (as described above for extensions) it works like a charm. Thanks.
