### ISSUE TITLE
Feature request: Save access token to Environment variable

### ISSUE THREAD

**Issue by lbj** [a85/POSTMan-Chrome-Extension#3007]
It would be very useful to have a way/test snippet to automatically save the access_token I get back from using "Get New Access Token" and oAuth2 to a variable in Environment. 
"Use Token" overwrites the {{access_token}} part of Authorization : Bearer {{access_token}} which means its too easy to accidentally save the token to documentation.

**Comment by a85** [comment]
We have updates coming up on authorization flows soon. For now, I'd suggest copy/pasting manually or using a test script.

**Comment by lbj** [comment]
@a85 So there exist a test script to pick up the returned token? Could you please share an example for how to do this?

**Comment by sdnts** [comment]
As @a85 said, we're working towards making this possible in a clean way. In the mean time, you can select the token and right-click on it. If you have an environment selected, you'll see an option there to set the token as a value to a pre-defined environment variable.

**Comment by Saibobba** [comment]
@a85 Hi ABhinav,
Did you figure out the way to save the returned token and use across all the API calls?
I get the Oauth2 token and it's pain to update every call with new token before I run them.
Please share me an example in case if this can be done.

Thanks.
--Sai

**Comment by pburgr** [comment]
using right click will copy not just access_token_value, but additionaly with text "token_type"; same as manual copying
Use Token button works fine, but as Saibobba mentioned, it must be done every time
Does somebody have a test script to set obtained token(s) as Env. variable(s) automaticaly?

thx
pbu

**Comment by any626** [comment]
If you want to set the token to your env variables then you'll have to hit the api directly. Don't use the Authorization tab.
Under the Tests tab use
```
var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("token", jsonData.token_type + " " + jsonData.access_token);
```
Under your other end points you'll need to add the header
`Authorization: {{token}}`
Adjust as needed.

**Comment by watsonix** [comment]
Note here's the modern way to do this inside tests:
`jsonData = pm.response.json();`
`pm.environment.set("token",  jsonData.access_token);`

Make sure you have your environment set (top right of screen). Automatically any other requests you employ will use the same environment. If you need token type, modify as necessary. Tests, by the way, are run automatically at the end of a request.

**Comment by bargar** [comment]
> Note here's the modern way to do this inside tests:...

@watsonix this would definitely be useful in some cases but not what's being asked for, I believe. The desire here is to be able to automatically set an environment variable from an access token coming back not from a manual Postman call to the access token URL, but from the otherwise quite powerful and streamlined [Postman Oauth 2.0 Auth UI](https://www.getpostman.com/docs/v6/postman/sending_api_requests/authorization).

![image](https://user-images.githubusercontent.com/1666818/48156196-d919fc80-e29a-11e8-8422-5bd8cc83cb6b.png)

Big thanks to @madebysid for this comment:

>  In the mean time, you can select the token and right-click on it...

I didn't realize at first what this meant, but it actually shows a context menu allowing you to set an env variable from the current value in the input field. 

![image](https://user-images.githubusercontent.com/1666818/48156026-5db84b00-e29a-11e8-970b-d9e1d31c94df.png)

That's not 100% automatic (which I maintain should be added as a feature!) but is sure better than copying and pasting it into an env variable by hand.

**Comment by dmillman** [comment]
That Set item doesn't seem to exist in 6,.6.1:

![image](https://user-images.githubusercontent.com/12037325/50645970-ed990f00-0f42-11e9-8445-af53f79d84df.png)

**Comment by ghost** [comment]
I solved this issue using a **dummy** request to the api after getting a new access token the token.

On the test for the dummy request you can access:
`pm.request.getHeaders()`
to get the headers used for the request and store them in any environment Variable. 

My final solution looks like (We are using OAuth2):
`auth_token=pm.request.getHeaders()['Authorization'];`
`auth_token=auth_token.replace('Bearer ','');`
`postman.setEnvironmentVariable("ACCESS_TOKEN", auth_token);`

**Comment by slishnevsky** [comment]
From what I understand Authorization OAuth 2.0 feature belongs to the request. However "Get New Access Token" is not really a part of this request, this is something Postman can do to get an access token behind the scenes as absolutely independent action. Therefore using Tests script to grab a token from "Get New Access Token" is not possible. Technically you must call "Get New Access Token" each time you want to make a request to an API. So, each API request turns into 2 actions: Get New Access Token and then Send a request. When you press "Get New Access Token" a new Token is generated and added to the list of previously generated tokens that you can see on Manage Access Tokens window.
As was mentioned previously, if you don't want to call "Get New Access Token" for every request, you can manually copy the generated token and set it to some variable and use it in next request (until it expires of course) with is bothersome. I wonder however if it is possible to emulate this "Get New Access Token" action in a form of a standard Postman request, but not sure if Postman is capable of handling Authorization grant (when a user clicks that he agrees) to grant access. I understand in existing "Get new Access Token" this is somehow implemented behind the scenes by Postman (something like Postman clicks on my behalf to agree) and then makes a call to get an access token, so behind the scenes there are actually 2 actions happening when clicking on "Get New Access Token" button. Please correct me if I am wrong. To Mr dmillman: you need to select the token, nut just put a cursor in it to get the proper menu.
![image](https://user-images.githubusercontent.com/2932739/61892577-1fbb8f80-aeda-11e9-8671-8c14ac3d2b6e.png)

**Comment by alanwill** [comment]
Can we re-open this? I  don't see a solution provided and it's still a valid feature request imho.

@a85 any update? It's been 2 years since you mentioned "We have updates coming up on authorization flows soon".

**Comment by kyletolle** [comment]
I wanted to say thanks to the Postman team for making such an awesome tool!

Also wondering if there's a 2019 update to this feature request?

I'd love an automated way to handle changing the OAuth token per env. I've got the `Get New Access Token` screen all populated with variables that are set per env
![image](https://user-images.githubusercontent.com/260869/69461497-eaae3500-0d33-11ea-81a3-af9745be4f23.png)

And this makes it easy to request a token based on the env I've selected.
I can see them in the available tokens with names that I've defined in the env vars like `OAuth Prod Token`, `OAuth Local Token`, `OAuth Dev Token`.
![image](https://user-images.githubusercontent.com/260869/69461676-56909d80-0d34-11ea-8db6-661a84d63fb0.png)

What I don't see, and what I believe this feature request is after, is a way to toggle between those saved access tokens automatically when I change the env. As far as I can tell, it still requires manual effort to change OAuth tokens when I change the env.

I'd like to automate this completely for not only myself but as well as my team at large. It'd be ideal to have the Collection specify the Authorization (using OAuth 2.0 with Request Headers), so that each request could inherit auth from the collection. And then the per-env OAuth access token would tie in somewhere here.

I'd understand the need for a one-time manual setup of the per-env OAuth access tokens, but then after that, when I change envs, the access token would change automatically to the applicable one for that env.

I've found some articles detailing approaches to set these access tokens by adding the OAauth auth endpoint to the collection, adding a test script to it, and then manually hitting the endpoint. Perhaps that's the preferred approach here? This still feels like a workaround for what could hopefully be handled natively within Postman.

Thanks for the assistance!

**Comment by LogansUA** [comment]
Still, badly need this feature

**Comment by ThisNoName** [comment]
And if possible, make the OAuth2 process local to each collection.  Now it's not only global but also does not require save, so touch it you lose it.

**Comment by Zawad** [comment]
I would also love this feature.

**Comment by rufreakde** [comment]
> I solved this issue using a **dummy** request to the api after getting a new access token the token.
> 
> On the test for the dummy request you can access: `pm.request.getHeaders()` to get the headers used for the request and store them in any environment Variable.
> 
> My final solution looks like (We are using OAuth2): `auth_token=pm.request.getHeaders()['Authorization'];` `auth_token=auth_token.replace('Bearer ','');` `postman.setEnvironmentVariable("ACCESS_TOKEN", auth_token);`

This actually is a valid solution you need more upvotes! I have this setup just on an dummy oAuth request and populate my environment {{JWT}} variable with this GET call. It works like a charm.
<img width="619" alt="Screenshot 2022-08-10 at 13 11 59" src="https://user-images.githubusercontent.com/28104368/183887357-5665bce9-1088-4707-b5bf-8eee97cf5ffc.png">
