### ISSUE TITLE
how do I import a collection to Linux native Postman?

### ISSUE THREAD

**Issue by heatherita** [a85/POSTMan-Chrome-Extension#3011]
1. Postman Version:
 2. App (Chrome app or Mac app): Linux
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by heatherita** [comment]
Trying to import collection from developer.okta.com to postman. Buttons on okta.com take me to Chrome postman but I want to import to native Linux postman. How can I do this? Thanks.

**Comment by prashantagarwal** [comment]
@heatherita are you using `Run in postman` button on this [page](https://developer.okta.com/docs/api/getting_started/api_test_client.html) . I just tried importing the collection and it redirected me to page where it asks if I want to import this to chrome app or native app. Can you let me know what scenario you are facing.

**Comment by ddfabbro** [comment]
@prashantagarwal Did you reproduce this issue on Linux? I'm facing the same problem. When I click on `Run in postman` button on this [page](https://docs.saffe.co/), it doesn't show the option to import in native app (Linux), as opposed to when you click it on OSX.

![screenshot from 2018-08-07 14-44-17](https://user-images.githubusercontent.com/17279638/43792913-6d7e5a08-9a50-11e8-8283-9adbbdf2a0cd.png)

This happens because postman for linux is a portable app you download via tarball.

Any workaround would be appreciated, as I need to import collections from a doc website.

**Comment by SamvelRaja** [comment]
Tracking it in https://github.com/postmanlabs/postman-app-support/issues/3798
