### ISSUE TITLE
[Feature] possibility to programatically write to a file

### ISSUE THREAD

**Issue by mpluta-airhelp** [a85/POSTMan-Chrome-Extension#3033]
Recently I was challenged by a task to copy certain objects from prod database to staging. I managed to finish it using API calls. At the end, I had to inspect the response of the last request to collect ID of the newly created object. It worked fine for 5-10 object but when I am dealing with thousands of objects to copy I would love to create a file on my disk and make Postman append IDs to this file (and possibly other data along the way). It could be also a great way to create a file which I could then use in another collection. 
Is it possible currently in Postman to have this reporting functionality?

**Comment by kunagpal** [comment]
@mpluta-airhelp This is best accomplished within Postman's CLI companion, [Newman](https://github.com/postmanlabs/newman). You would then write a script to generate your custom reports via the following steps:

1. Ensure that you have `node` and `npm` installed.
2. Install newman with: `npm install newman`.
3. Create a file with the following contents:
```js
var fs = require('fs'),
    newman = require('newman'),

    results = [];

newman.run({
    reporters: 'cli',
    collection: '/path/to/collection.json',
    environment: '/path/to/environment.json' // This is not necessary
})
.on('request', function (err, args) {
    if (!err) {
        // here, args.response represents the entire response object
        var rawBody = args.response.stream, // this is a buffer
            body = rawBody.toString(); // stringified JSON

        results.push(JSON.parse(body)); // this is just to aggregate all responses into one object
    }
})
// a second argument is also passed to this handler, if more details are needed.
.on('done', function (err, summary) {
    // write the details to any file of your choice. The format may vary depending on your use case
    fs.writeFileSync('migration-report.json', JSON.stringify(results, null, 4));
});
```

4. Run the file with:
```bash
node script.js # Here, script.js is the file created in the previous step
```

PS: If this is a recurring use case, then you could also turn the above script into a custom reporter (https://github.com/postmanlabs/newman#creating-and-using-custom-reporters)

**Comment by mpluta-airhelp** [comment]
I will use this to prepare a script for my use. Totally missed this functionality. However, I strongly suggest it would be a great function in your desktop app too. 
But in the end great tip, thanks a lot!

**Comment by kunagpal** [comment]
@mpluta-airhelp Thanks for your suggestion, we're marking this issue as resolved. 😄

**Comment by p00j4** [comment]
@mpluta-airhelp while using postman app, in some of my requests, I want to write some of the key information. What changes I need to make to the approach you described above?
Basically, I want to be able to save
- environment variable value(s)
- variables generated in pre-reqeust scripts/test scripts [random id generated and used to make request]

because **args.response** and **args.request** both won't give me those

**Comment by hari411** [comment]
Hi All,
I am running the collection in postman by passing multiple inputs from .csv file, after completion of test i want to write the results in the same .csv file, How to handle this can any one let me know.
Thanks in advance

**Comment by georgesunil81** [comment]
Similar requirement to the above, I have a response from prior API requests that I want to pass in as form-data/files into subsequent API requests when running using the Collection Runner. Could we have an ability for Postman to save responses into the "Working Directory"? This way we control where Postman writes to and it be less of a security issue. The idea is that the subsequent API requests will then read in the files from the "Working Directory" when run through the Collection Runner. Could someone look into this please since we need this ability, or if someone can suggest a workaround for now when running through the Collection runner. Thanks.
