### ISSUE TITLE
How To Programamtically Set Authorization Details?

### ISSUE THREAD

**Issue by jkentreynes** [a85/POSTMan-Chrome-Extension#3042]
How can I programmatically set AWS Signature authorization details in postman?

**Comment by vegetableman** [comment]
Currently, there is no way to programmatically set it. Tagging this as a feature request ^_^. To know more about the supported api on the sandbox, checkout https://www.getpostman.com/docs/sandbox

**Comment by a85** [comment]
@jkentreynes What exactly is your use case? You can set environment variables and use them as AWS Signature inputs.

**Comment by cbarrerah** [comment]
And any hopes for environment variables to be used in the Authorization->AWS Signature tab fields?
That would simplify the proccess of authorizing a lot. Instead of copying and pasting from the environment variables to the fields, we could simply put the environment variables in the fields, and press "Update Request" with string substitution done before the update of the auth headers.

Just an idea :)

**Comment by shamasis** [comment]
> And any hopes for environment variables to be used in the Authorization->AWS Signature tab fields?
> That would simplify the proccess of authorizing a lot. Instead of copying and pasting from the environment variables to the fields, we could simply put the environment variables in the fields, and press "Update Request" with string substitution done before the update of the auth headers.
> 
> Just an idea :)

That should already work for you. Is it not working?
