### ISSUE TITLE
Postman Mobile app

### ISSUE THREAD

**Issue by d-insig** [a85/POSTMan-Chrome-Extension#3060]
Its high time postman get a mobile/tablet app. It could be a read/execute only for the MVP where collections added on the product can be shared across mobile and requests can be sent across.

**Comment by kamalaknn** [comment]
@d-insig Hey!

Thank you for your feedback.

For now the postman [web app](https://app.getpostman.com) should offer a very basic feature set like viewing your private/team collections, subscribing to collections, view/publish docs. 

We will see if we can add other team and sharing related features to the web app so that it becomes available on all platforms/devices. 

But the sending of requests might be tricky. @a85 can clarify on that.

I am tagging this as a feature request.

**Comment by abhijitkane** [comment]
@d-insig Not part of our immediate roadmap. We're working on making our web-app responsive and more capable - that should solve this to an extent.

Closing this for now.
