### ISSUE TITLE
Postman interceptor missing in win10 app

### ISSUE THREAD

**Issue by daniele-pintus** [a85/POSTMan-Chrome-Extension#3082]
I just installed the latest version of Chrome (58.0.3029.110 - 64-bit) and Postman ( 4.10.7), then I installed the chrome interceptor extension, but it does not appear on postman. there is a "proxy settings" instead.
the interceptor is not working anyway with the embedded chrome extension.
OS version Windows 10
![postman_interceptor](https://cloud.githubusercontent.com/assets/28985036/26550354/a75750e2-447d-11e7-87a6-69476a60385d.PNG)

**Comment by sdnts** [comment]
Hi @daniele-pintus, Postman Interceptor is available only on the [Chrome apps](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop), since cookie handling flows are built into the native apps.

I'd recommend sticking to the native apps though, since Google will end support for Chrome apps soon.
