### ISSUE TITLE
Response Body not loading

### ISSUE THREAD

**Issue by mjkraner** [a85/POSTMan-Chrome-Extension#3087]
1. Postman Version: 4.11.0
 2. App (Chrome app or Mac app): NA - desktop version
 3. OS details: Win 8
 4. Is the Interceptor on and enabled in the app: postman console is up
 5. Did you encounter this recently, or has this bug always been there: recently with new upgrade
 6. Expected behaviour: I could see the response body
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/16242234/26640393/38de3790-45ed-11e7-9048-fd133662aa9b.png)

![image](https://cloud.githubusercontent.com/assets/16242234/26640406/41638258-45ed-11e7-9a5a-8c8142a56033.png)

**Comment by kamalaknn** [comment]
@mjkraner Thanks for reporting the issue.

We are seeing this too. We will roll out a fix for this soon.

I will keep this thread updated.

**Comment by serkand** [comment]
+1

**Comment by kamalaknn** [comment]
Hey @mjkraner @serkand,

The fix for this issue is now out as part of the latest version - `4.11.1` of our app. Could you update apps to the latest version and check if this is fixed on your side?

I am closing this issue. Feel free to comment/reopen this if you are still seeing this. 

Thanks, have a nice day!
