### ISSUE TITLE
Sort requests in folder

### ISSUE THREAD

**Issue by brad-pds** [a85/POSTMan-Chrome-Extension#3089]
I would like to have a button to sort the requests in a collection folder. The current sort button only supports sorting the collections, not their subfolders.

**Comment by SamvelRaja** [comment]
Thanks for raising your request to us. We shall let you know the progress in the same thread.

**Comment by d1820** [comment]
I have a request folder with 100+ requests in it. There does not seem to be a way to sort those requests, but i can sort the folders. Any plans to be able to sort the requests inside a folder. It forces me to search all the time, but if i have to run many requests in a row that also becomes a hassle.

this feature work I'd be great

**Comment by tomershay** [comment]
+1 on this idea. Will be great to have a way to sort requests inside a collection.

**Comment by nogorilla** [comment]
👍

**Comment by tomershay** [comment]
+1

**Comment by chiragpurohit71085** [comment]
Is there way to drag and drop multiple requests?

**Comment by fschai89** [comment]
+1

**Comment by frauss** [comment]
+1

**Comment by vkaegis** [comment]
Hey guys! Been a while since this issue has been updated. As you all probably know, you can now order requests in folders whichever way you like. 

@chiragpurohit71085 There isn't a way to select multiple requests in the Collections tab of the sidebar just yet. Bunch of technical limitations blocking us from releasing that as of now. But rest assured this is in our plans for the immediate future.

I'll be closing this issue for now since the original request is solved. That said, we'd love to hear more feedback around working with requests in the sidebar, so feel free to raise any new feature requests!

**Comment by chiragpurohit71085** [comment]
Hi

In which version this feature has been introduced. I am having postmam
6.1.3 and not able to find any feature of sorting. I checked setttings for
collection i.e 3 dots on right side of collection...

**Comment by vkaegis** [comment]
@chiragpurohit71085 I meant that you can manually drag requests and sort them in any order you prefer.

**Comment by chiragpurohit71085** [comment]
Oh , okay.

**Comment by SMarconetto** [comment]
+1 Will be great!

**Comment by karlmacklin** [comment]
An alphabetical sort would be **very** useful.
Even if you have a small amount, say 30 requests, in a collection.

Sure, you could sit there and drag and drop if you're billing hourly and be happy about it. But if you have a set budget it would save you much anguish and tedium to just click once and have it sorted alphabetically.

**Comment by adampatterson** [comment]
I guess this isn't a thing yet, you can drag them around but that's not going to cut it.

**Comment by PunkSage** [comment]
@vkaegis What an elegant way of showing a middle finger, obviously Postman needs an automated name sorting mechanism. Do you ever want to provide it?
