### ISSUE TITLE
Data of last row, last column loaded from CSV ending with CRLF in runner is appended with "\n"

### ISSUE THREAD

**Issue by everuler** [a85/POSTMan-Chrome-Extension#3115]
Version/App Information:
 1. Postman Version: 4.11
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 10 (x64)
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Always
 6. Expected behaviour: No trailing newline.

Steps to reproduce the problem:
1. Launch runner.
2. Load data .csv file ending with CRLF.
3. Preview loaded data.
4. Data of last row, last column is appended with "\n".

Remarks: Not visible with Chrome app but visible with Windows Desktop app.

**Comment by numaanashraf** [comment]
@everuler Thanks for reporting. We are looking into this.

**Comment by numaanashraf** [comment]
@everuler We were to replicate this. We'll roll out the fix in an upcoming release as soon as its ready.

**Comment by nehemiahjason9** [comment]
![image](https://user-images.githubusercontent.com/31903889/30349496-ccc4a66e-97d8-11e7-964e-cbd2530e8f79.png)

I'm having this problem, is there any solution to this? let me know

**Comment by KatrinaC** [comment]
@numaanashraf do you have an ETA for this fix?

**Comment by vikiCoder** [comment]
Hi everyone,

I would like to inform that we have made some changes related to CSV file parsing under the hoods in the Postman App. This issue is fixed as part of those changes. It is available on the [latest canary](https://www.getpostman.com/downloads/canary) version (Version 7.1.1-canary07) of the app. You can checkout [canary](https://www.getpostman.com/downloads/canary) and let us know if you are still facing this issue in it.

**Comment by vikiCoder** [comment]
Fix for this is out in [latest Postman App](https://www.getpostman.com/downloads/) (v7.2.1) as well.
