### ISSUE TITLE
In postman pro Monitoring is failing

### ISSUE THREAD

**Issue by malyalal** [a85/POSTMan-Chrome-Extension#3128]
1. Postman Version: Postman for Chrome
Version 4.11.0
 2. App (Chrome app or Mac app):
Chrome 58.0.3029.110
 3. OS details: OS X / x86-64
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Since I started using postman pro, I am trying to test monitoring for a sample collection, which is successfully running in Runner.
 6. Expected behaviour: Monitoring result is passed
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
ostman Monitoring started
2	17:02:48	Login
3	17:02:48	POST https://
4	17:02:48	Error: certificate has expired
5	17:02:48	JSONError: Unexpected token u in JSON at position 0
6	17:02:48	JSONError: Unexpected token u in JSON at position 0

12	17:02:49	Error: certificate has expired
13	17:02:49	JSONError: Unexpected token u in JSON at position 0
14	17:02:49	JSONError: Unexpected token u in JSON at position 0

24	17:02:50	Postman Monitoring finished
 8. Screenshots (if applicable)
![screen shot 2017-06-06 at 22 42 38](https://user-images.githubusercontent.com/13729866/26853352-80dbb2ea-4b09-11e7-8ef3-b535f67159fa.png)

1. Create a postman collection
   2. add a monitor
   3.  When the run happens, check the results.

**Comment by numaanashraf** [comment]
@malyalal Thanks for reporting. We are looking into this.

**Comment by JamesMessinger** [comment]
Hi @malyalal 
It looks like there are a few errors in your monitor.  Here are explanations of each...

```
2	17:02:48	Login
3	17:02:48	POST https://
```

Notice that most of the URL is missing.  I assume this is because you're using a variable to fill-in parts of the URL (e.g. `https://{{my_server}}`) and the variable is either missing or empty.  Please ensure that you've attached an [environment](https://www.getpostman.com/docs/postman/environments_and_globals/manage_environments) to your monitor and that the environment contains the necessary variable(s).


```
4	17:02:48	Error: certificate has expired
```

This is an SSL error . I assume this is just due to the missing domain name in the URL.  So once you fix the first error, this one will probably be fixed too.


```
5	17:02:48	JSONError: Unexpected token u in JSON at position 0
6	17:02:48	JSONError: Unexpected token u in JSON at position 0
```

These are JavaScript errors that occur when attempting to parse invalid JSON data.  I assume this is also because of the invalid URL, which is causing an HTTP error response to be returned. The error response body is probably a string like "_unknown domain name_" or something like that, which is obviously not a valid JSON string.  So, if in your test script you are doing something like `JSON.parse(responseBody)`, then that will cause these errors.  I suggest that you check the response's status code or `Content-Type` header first before calling `JSON.parse(responseBody)`.

**Comment by malyalal** [comment]
hi @BigstickCarpet thanks for the investigation. 
intentionally I deleted the remaining part of the url from the evidence bcoz it was our test environment ID and endpoints. I am not sure it is safe to expose these ip & api calls outside my organisation. 
However, I can share you the original logs which come like below
3	17:02:48	POST https://193.67.XX.XX/uaa/oauth/token
4	17:02:48	Error: certificate has expired
5	17:02:48	JSONError: Unexpected token u in JSON at position 0
6	17:02:48	JSONError: Unexpected token u in JSON at position 0
7	17:02:48	Customers
8	17:02:48	GET https://193.67.XX.XX/customers
9	17:02:48	Error: certificate has expired
10	17:02:48	Premises

And I always chose the environment where I want the test to run. 
![screen shot 2017-06-07 at 17 13 32](https://user-images.githubusercontent.com/13729866/26889148-0f45b472-4ba5-11e7-8dc7-24a14c484e25.png)

Yes, I use json.parse(responseBody) in the test sandbox. I'll try to run the test by removing this.

**Comment by JamesMessinger** [comment]
Ah, ok @malyalal.  Sorry, I didn't realize that you had intentionally removed part of the URL from your original issue description.

Since the URL is not the problem, then the SSL certificate appears to be the cause.  The `certificate has expired` error message in the log means that the request to your server failed due to an expired SSL cert.  Then the subsequent JSON errors are just caused by trying to parse the error response as JSON.

**Comment by malyalal** [comment]
I verified with my config team. All certificates are active and fine. 
The above test runs successfully in the Postman runner also. 

Please help me if I have to add any cert. to postman or make any changes to get this worked.
I am using the trial version of Pro and I (my team) will be charged additional cost for Pro from 17th. If this is not going to work, that's a loss. 

Can you also provide me with a sample monitoring result log/file, please?

**Comment by JamesMessinger** [comment]
@malyalal - Try disabling SSL validation for your monitor.  That may solve the problem.

<img width="506" alt="disable ssl" src="https://user-images.githubusercontent.com/3453903/26934013-0009fef0-4c1d-11e7-94ca-9d388533b76d.png">

**Comment by malyalal** [comment]
Hi again @BigstickCarpet, I tried it and it worked. Thanks a lot for your support. 
The evidence below - 
![screen shot 2017-06-08 at 16 13 59](https://user-images.githubusercontent.com/13729866/26936158-b803e230-4c65-11e7-850c-599380dab7e6.png)

**Comment by JamesMessinger** [comment]
Great!  Glad to hear it!

**Comment by vmarkova** [comment]
Hi there, 

Have exactly same issue described above, but disabling SSL didn't help :( 
All tests are successful in Postman API Runner, monitor keeps being failed thou. Exact same errors in console log, but all advices above don't help (tried disabling SSL, checked url, checked enviroment). 

Attaching 2 screenshots - postman runner successful results and monitors failure. (URLs and collection names are erased for security reasons)

Thank you in advance! 

<img width="1712" alt="screen shot 2019-01-29 at 1 53 53 pm" src="https://user-images.githubusercontent.com/42750244/51944226-5bb0e480-23d0-11e9-8e7d-6fa2cee1ece2.png">
<img width="1190" alt="screen shot 2019-01-29 at 1 54 27 pm" src="https://user-images.githubusercontent.com/42750244/51944227-5bb0e480-23d0-11e9-8ca2-bc02e3e29536.png">
