### ISSUE TITLE
Issue with duplicating a tab

### ISSUE THREAD

**Issue by renderit** [a85/POSTMan-Chrome-Extension#3130]
1. Postman Version: Version 4.11.1 (4.11.1)
 2. App (Chrome app or Mac app): Mac app
 3. OS details: OSX Sierra

Great product :) There might be a bug with the newest version of postman(which I am using). 
When you try to "duplicate" a tab for example, which lets say contains a GET request, it doesn't truly duplicate but maintains a reference to the original tab. This means when I try to "edit" the duplicated tab, the original tab also automatically changes unfortunately. 
Let me know if I got something wrong.

**Comment by numaanashraf** [comment]
@renderit If you open a request from collection in a tab and duplicate this tab, both these tabs are linked. So, if you save the duplicated tab, it will overwrite the original request. The behavior is similar to opening the same file in two tabs in a text editor. If you wanna create a copy of the request, I suggest duplicating the request from the sidebar, instead of the tab.

**Comment by renderit** [comment]
@numaanashraf you're right! Although I still feel this should be corrected as its not intuitive from a UX/UI aspect. Also if I use the sidebar to "duplicate" then it works fine. Duplicate should be a copy not a reference I thought. Nonetheless, thanks! :)

**Comment by caddac** [comment]
While I see this is closed, it is extremely confusing that duplicating behaves differently depending on where you choose to duplicate from (side bar vs header).

**Comment by edesdan** [comment]
I'm having this issue duplicating a request, it is very annoying.

**Comment by Nickwwest** [comment]
As of 6.1.2:
* "Duplicate" in the list on the left doesn't actually duplicate.  For some it fails to copy the URL and the Headers
* Right clicking on a tab should present the option "Clone" (like in chrome) instead of duplicate so we aren't calling two different things by the same name in a very similar context.

**Comment by RedDeathGitHub** [comment]
Any fix for the above? I duplicate/copy a request and it's empty...

**Comment by sujayvenaik** [comment]
@RedDeathGitHub 
Can you provide more information? Which app version and if you see any error logs.
You can get the error logs from  "View -> Developer -> View Logs in Finder" and send us the logs.

**Comment by RedDeathGitHub** [comment]
Sure, v6.6.1, update says it is the latest version.
[logs.zip](https://github.com/postmanlabs/postman-app-support/files/2726652/logs.zip)
I hope I attached the logs correctly ^ :)

When I duplicate/copy only the name is copied, no url/parameters etc.

**Comment by budajeff** [comment]
I'm having this problem as well in v6.6.1 on Windows 7. The duplicated request does not have any of parameters, headers, or body copied from the original request.

**Comment by lemaral** [comment]
Any news about duplicate request creating empty copy? Issue is present on 7.34.0/MacOS.
