### ISSUE TITLE
Self-signed certificates for localhost not working with Postman

### ISSUE THREAD

**Issue by TehWardy** [a85/POSTMan-Chrome-Extension#3136]
## App Details:
Postman for Chrome
Version 4.11.1
win / x86-64
Chrome 58.0.3029.110

## Issue Report:
I am unable to get access to apps running on https locally with visual studio 2017 and iis express 10.0
I have reproduced the problem on other machines.

The problem is not seen on remote servers only localhost.

From chrome ...
![image](https://user-images.githubusercontent.com/6891030/26882543-96814428-4b92-11e7-9450-e20dbfdec7a3.png)

From postman ...
![image](https://user-images.githubusercontent.com/6891030/26882561-a5710798-4b92-11e7-8f9b-ecb96fba44cb.png)

Postman can't seem to find localhost when SSL is enabled, but chrome can.
I thought it might be a cert issue so I added the cert for my iis express (dev server) running on the local machine to the trusted root cert authorities section in the cert store but no luck.

**Comment by numaanashraf** [comment]
@TehWardy Could you head to Settings > General, turn off 'SSL cerificate verification' and try again?

**Comment by TehWardy** [comment]
Doesn't work :(
I also tried exporting the cert using firefox then importing in to postman under settings => certs.
This used to only affect localhost, with each new update to postman it makes less and less servers work.

I did manage to get it working once on a machine not on the business windows domain by forcing the cert in to the root store on the local machine and restarting the machine but I think there's a bigger issue here as everything works except for postman and that fix doesn't seem to work for a domain connected machine.

Random question ...
Why does a tool designed to test endpoints really care if the SSL cert is valid?
Why not just the user and carry on any way, seems overly aggressive to have this "i refuse to talk to the server" type behaviour.

**Comment by TehWardy** [comment]
I have done some further testing on it, for the app in question when launched from visual studio and run on IIS Express locally when SSL is enabled it actually hosts the apps on 2 ports, one is a standard non SSL based port.

I can't get postman to talk to either of these ports for the given app and there doesn't seem to be any logic as to why it works on some apps vs others.

What's even stranger is that the apps are all sub parts of a single website in IIS Express and it can't contact the root but it can contact "some" of it's children.

**Comment by TehWardy** [comment]
Postman for Windows
Version 5.0.2
win32 10.0.15063 / x64

Also has this issue ... on that it appears worse, it seems to affect more than just localhost.

**Comment by TehWardy** [comment]
Interesting ... having added the cert to the root cert authority store on my domain managed machine, if I then uninstall postman for windows and install the latest postman for chrome (no reboot, just remove => add) it seems to be working again.

now i'm really confused!!!

**Comment by sdnts** [comment]
@TehWardy When you use the Chrome app, it uses the certificate from Chrome, which in turn takes it from your system's keychain, which is why everything falls into place. Is the certificate you're using a `.cert` type file? The native app currently only supports the `.cert` format.

**Comment by TehWardy** [comment]
I think it was a .cer file ... It seems to have worked from randomly flailing around trying stuff out ... Would be nice to have some clear instructions on how to get the cert from within chrome though as I couldn't find a way at all and ended up having to use firefox

**Comment by TehWardy** [comment]
Nope ... gone again.
How frustrating this is!

Loaded chrome, visited the API url it gave the message "your connection is not secure", I clicked the proceed link, then hit send in postman again and it's worked.

... eh?

**Comment by another-guy** [comment]
@TehWardy ~I'm getting a similar issue here. Would be nice to get the official right way setup documented.~

My own stupidity. I was not even making calls via *httpS* protocol.

**Comment by TehWardy** [comment]
And this morning I load up one of my applications and the same problem ... chrome takes me straight to my auth message (the expected result) and in postman, the usual "could not get a response".

Is anyone working on this problem?

**Comment by TehWardy** [comment]
Ok did some digging (after yet another postman reinstall ...
I opened up the postman dev tools and console to see if I could figure out more about what was going on.

First up I get this error in the console ...

![image](https://user-images.githubusercontent.com/6891030/29068738-f3c64f70-7c2f-11e7-9e86-94bff12ba275.png)

So I took a look in my certs list under settings and found this ...
![image](https://user-images.githubusercontent.com/6891030/29068756-03fd78b4-7c30-11e7-9cb1-e6f0a6eec314.png)

Straight up weird, no idea how to solve that.

After that I was getting this ...
![image](https://user-images.githubusercontent.com/6891030/29068786-22772736-7c30-11e7-9e6c-71722cddb44d.png)

Turns out that space after token was actually a newline char (odd that postman didn't trim that as it's never valid to have newline in all the headers i've come across so far (is this ever valid?) ... that said the "bulk edit option" should take newline to mean "ok new header".

Having removed that odd char I came across this error ...

![image](https://user-images.githubusercontent.com/6891030/29068887-76f6e7f6-7c30-11e7-8305-39b03faad6e9.png)

Which I assume is related to the first error and thus the root of my problem.

So ...
As Postman seems to not have access to a cert that it should be getting from the server.
I thought I would try another approach.
I took my "cer" file (that I had to extract using firefox as I couldn't find any option in either chrome or postman to extract this) ... and dropped it in to a new folder in the root of my hard drive.
I granted "everyone" full control rights to the directory, and then added the cert to postman.

So I now have ...
![image](https://user-images.githubusercontent.com/6891030/29069010-fdef7fa2-7c30-11e7-9912-5655ac56da5d.png)

... still no luck ... Every new request is met with ...
![image](https://user-images.githubusercontent.com/6891030/29069042-24964546-7c31-11e7-854f-5defbbd8e0be.png)

... where do I go from here?

**Comment by TehWardy** [comment]
As per the advice above I have also turned off the setting "SSL Certificate Verification" under settings > General.

In short ... post man seems to have problems no other application on my computer has and I'm still none the wiser.

**Comment by gnchiesa** [comment]
Hi All. Has a solution for this ever been found? Postman simply cannot talk to apis hosted on https servers. I cannot do anything with the certificate as the server is managed by some external company and won't give it to me under any circumstance. 
For now, I'm using a plain rest client that's no match for postman, but for this, it just works.
Would you fix this guys? pretty please?

**Comment by TehWardy** [comment]
I found that after doing all of the above I rebooted my machine and some versions of postman are happy others aren't ... it seems to come and go with each new update to postman.

I also think that windows does some weird profile loading of cert stores so any time you add or remove a cert fro mthe "personal" store on the machine, reboot just in case.

With all this in mind I got to a point where I basically just built a "postman like" UI on a web page and now I just use that ... it works, flawlessly, every time.
No idea why postman can't just be the same ... it's a dev / testing tool after all, it shouldn't care if something is secure unless you tell it "be uber strict as that is the test i'm trying to perform".

good luck though!

**Comment by numaanashraf** [comment]
@TehWardy I'm condensing this discussion and adding our thoughts here.

The original [comment](https://github.com/postmanlabs/postman-app-support/issues/3136#issue-234222426) is related to working with untrusted SSL certificates in `Postman for Chrome`. `Postman for Chrome` apps rely on Chrome to send and receive requests and `Postman app` has no control over SSL certificate verification performed by Chrome as part of sending the request. Chrome will honor untrusted certificates you have added to your OS as trusted (hence [this](https://github.com/postmanlabs/postman-app-support/issues/3136#issuecomment-312432480) behavior) and there is also a way to whitelist certificates on a case to case basis by opening the link in Chrome and clicking "proceed" in at the "Your connection is not secure" (which is why you are seeing [this](https://github.com/postmanlabs/postman-app-support/issues/3136#issuecomment-317420518) behavior). Since you seem to be working with IIS Express and VS, which I believe generates self-signed certificates on demand, you are required to do these steps again and again to keep your API working with `Postman for Chrome`.

Having said this, we completely agree with your sentiment that Postman is a testing tool and should not be strict about SSL verification, which is why we have exposed `SSL cerificate verification` [setting](https://github.com/postmanlabs/postman-app-support/issues/3136#issuecomment-306812672) in our native apps - to completely turn off SSL verification. (this is not available in Postman for Chrome as we have no control over SSL verification in Chrome apps). 

Note: There seem to be some confusion [here](https://github.com/postmanlabs/postman-app-support/issues/3136#issuecomment-320922837) regarding Client Certificates. These are *client* certificates that Postman sends to your server and does not affect the server certificate verification behavior.

Do let us know if we have missed anything and if you are still facing issues with SSL verification in our native apps after you have turned the setting off.

**Comment by numaanashraf** [comment]
@gnchiesa Could you give us more info regarding your issue? Are you working with a self-signed certificate? Have you tried turning the SSL verification setting off in our native apps?

**Comment by TehWardy** [comment]
Sooooo ... I totally forgot about this issue then ...
After a while i ended up with a broken install of windows on my home machine (you know "reasons", windows update, ect) ... That led me to get some more insight on this problem which I logged in ticket #4726 

I've come to the conclusion that postman does support this scenario, it just doesn't want to by default like somehow a local dev environment is a sub standard service because I didn't go to the effort of signing my IIS express instance with a cert from say ... go daddy (go figure ... right?). 

I really love that postman is trying to push standards. 
That said, I genuinely think that this scenario is crazy simple and a norm for many. 
Postman should have some sort of exception to just "behave like chrome" and report that the cert is not valid but still talk to the API and return a response regardless.

Maybe have a means to "turn ON strict mode" which then gets this aggressive instead of enforcing it by default would be better (reccommendation)?

Kudos to the Postman team though for getting involved and actively trying to understand the frustration here, it's much appreciated!

**Comment by numaanashraf** [comment]
@TehWardy We are working on multiple changes to improve the overall experience of working with secure endpoints, including setting sane defaults to avoid common pitfalls and frustrations and also providing better error info for faster troubleshooting. We are going to track this change at #4726 and let's continue this discussion over at that thread.

**Comment by FlorianPfisterer** [comment]
@TehWardy As a temporary workaround, I have used `https://127.0.0.1:port` instead of `https://localhost:port`, which did the trick for me.

**Comment by laitnee** [comment]
@techwardy just go to setting > general and turn off ssl certificate.

**Comment by sensoeurn** [comment]
Go to File menu -> Settings > General, turn off 'SSL cerificate verification' and try again.
It works for me.

**Comment by TehWardy** [comment]
@FlorianPfisterer
I get where you're coming from ... kinda odd that I would need to "work around localhost" in a tool designed for testing endpoints though.

@LightningINC @sensoeurn 
The key thing you're missing is that I've already done that (literally stated it in the first line of my second post on this thread) and something is going on that causes this setting not to work on what seems to be an intermittent basis.

It's also worth noting that my confusion here is that postman being a dev tool doesn't trust self signing / localhost by default regardless of how strict you want your testing of production environments to be.

@numaanashraf 
Thanks for sticking with this one, it's much appreciated.

**Comment by dewelloper** [comment]
unfortunately I can't agree to this solution
There's nothing I haven't tried since morning.
I am adding client certificate authentification to the project that I wrote with asp.net core. My application is running and the client is waiting. I'm sending a request via Postman to the application running in local. I've added the certificate to the exact specifications and tried all possible combinations. (subject localhost etc that numaan defined) I log the result via both fiddler and postman console. I even observe it with visual studio output. I observe that both the fiddler and the postman console, the certificate cannot be sent or even the postman is not aware of its existence. But someone writing about a solution (like this). Can it be corrupted?

**Comment by TehWardy** [comment]
@dewelloper Fiddler is a proxy, that will only make the situation more complex and likely cause you more issues. I use to use it a long time ago but dropped it when it started causing more problems than it solved.

I'm logging information on the server (my web app) and on the client (browser / postman console) running on the same machine, the UI above was just something I threw together to show difference between postman and chrome when handling self signed certs.

It sounds like you're talking about client certs though. 
The issue here is postman's lack of trust of server certs signed by the server and not a trusted authority. Client certs are a different scenario but loosely related I would think.

We are purely talking about localhost trust for simple debugging scenarios, SSL still works the way it works in all cases.

**Comment by dewelloper** [comment]
You are right. Naw i can sending certificate however :)
But handler getting always null

**Comment by OG1NSystems** [comment]
Is there any valid resolution for this? 
As I get the same issue when I am trying to debug my application when using Visual Studio 2019, however if I use Visual Studio Code I do not get the errors.

I using a self signed certificate from visual studio so it goes to port 44316, but I should still be able to access port 5001 which I can't, nor can I get access to 5000 which I can when running it through VS Code

**Comment by TehWardy** [comment]
As above #4726 <-- the conversion is being tracked there

**Comment by dewelloper** [comment]
Yes i have resolved my problem long time ago. In my case reason is server certificate and client certificate has different private keys. That is not interested with fiddler. @TehWardy right.
@OG1NSystems  use the same certificate from the path. Even don't install it to the store. But if you need to install them to the store then check they have the same private key!
Also postman works on perfect just not tell you private keys are diffrent, its normal because it is not its job
