### ISSUE TITLE
[Feature Request] Access Globals and Data Files from Postman Cloud/API

### ISSUE THREAD

**Issue by Heydiddly** [a85/POSTMan-Chrome-Extension#3151]
Would be very useful if Globals and Data Files could be stored on the Postman Cloud and retrieved via the API the same way collections and environments can currently. i.e. new endpoints:

https://api.getpostman.com/globals?apikey={{Key}}
and
https://api.getpostman.com/globals/{{GlobalUID}}?apikey={{Key}}

https://api.getpostman.com/datafiles?apikey={{Key}}
and
https://api.getpostman.com/datafiles/{{DataFileUID}}?apikey={{Key}}

**Comment by sdnts** [comment]
@Heydiddly Thanks for the suggestion! We'll look into this :)

**Comment by davidespihernandez** [comment]
@Heydiddly I know it's been more than 5 years since you created this issue, but I'm currently reviewing pending GitHub issues related to Postman API, and I found this one.

I have some questions for you: 
- Is this still a valid feature requirement for you?
- Which use case do you want to solve by exposing that information in the Postman API? Why do you need this?
If you're not interested anymore in this ticket, please let me know and I'll close it.

Apologies for the "late" response.

**Comment by davidespihernandez** [comment]
For future reference, the Postman API now exposes a way to CRUD global variables in a workspace. The documentation can be found here: https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-a75846bd-c1c7-43e3-88f6-a0c752db83c5
