### ISSUE TITLE
Wordpress.com POST not wroking via Postman

### ISSUE THREAD

**Issue by Jaymin3190** [a85/POSTMan-Chrome-Extension#3206]
Hi Team,

I am trying to expose wordpress.com rest api for operation like update and create, but i am getting error with status 405 as 
{
    "error": "unauthorized",
    "message": "You cannot make requests from this origin."
}
Headers I am using are:
Authorization --> with my token ID
Access-Control-Allow-Origin --> *

Although GET operation is working perfectly fine.

Can anyone please help me to resolve this.

**Comment by Jaymin3190** [comment]
I am using POSTMAN client with interceptor plugin already enabled.

**Comment by kamalaknn** [comment]
Hey @Jaymin3190,

From the error message you've given, it looks like the endpoint is imposing restrictions on which `origin` can make API requests. Requests from Postman app use a different `Origin`. 

Could you check the documentation for `wordpress` Rest API on origin control?

I am closing this as it doesn't look related to the Postman App itself. Please reopen the issue if you find this breaking because of something Postman is doing wrong.

Thanks.
