### ISSUE TITLE
cURL code for PUT request with file upload

### ISSUE THREAD

**Issue by neilghosh** [a85/POSTMan-Chrome-Extension#3213]
## App Details:

```
Postman for Mac
Version 5.0.0 (5.0.0)
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always there
 2. Expected behaviour: see --upload-file <path_to_file> option in cURL code
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 4. Screenshots (if applicable)

1. Select method as PUT and given an URL. 
2. Select Binary in the request body type
3. Select a file from your computer using the browse button.
4. Click on code and select cURL option 
5. Observer that curl has every thing in the command except the file. i.e. --upload-file <path_to_file>
6. The curl command copied does not upload the file (due to missing --upload-file option.)

**Comment by a85** [comment]
File paths are not supported with the curl code generation option.

**Comment by science695** [comment]
Is adding file paths to curl code generation something coming in the future?

Multi-part uploads are complicated and many of the code generation languages just ignore it.

**Comment by shreys7** [comment]
Hey @neilghosh In Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'New Code Generation Mode' flag enabled in Postman's global settings
This particular bug is fixed in the new code generation mode. It supports file upload via multipart/form-data.
![Screenshot 2020-01-02 at 5 33 47 PM](https://user-images.githubusercontent.com/20665864/71666257-2e11af80-2d86-11ea-9e24-dc114aa8f571.png)

**Comment by DannyDainton** [comment]
Closing due to a fix in the product. If this is still an issue we can look to reopen this issue again.
