### ISSUE TITLE
Postman prompts me to save the file instead of downloading automatically

### ISSUE THREAD

**Issue by saiudayakella** [a85/POSTMan-Chrome-Extension#3269]
## App Details:
Postman for Windows
Version 5.0.2
win32 10.0.15063 / x64

Issue:
We have an API that generates PDFs  as the response. Currently when I test the respective endpoint, postman/collection runner opens the "Save File" dialog instead of downloading the PDF automatically. 

I tried the option "Send and Download" assuming that downloads the file without prompting to save but that too doesn't work. I'm aware that it's  a browser thing but **I expect the dialog to not display.**

When I run the collection/folder from newman, it doesn't prompt me to save the file which is almost what I expect but I'm not able to confirm whether the file is downloaded or not.

**Comment by sdnts** [comment]
@saiudayakella I agree that the download dialog should be suppressed in the Runner at least.
@a85 What are your thoughts on this?

**Comment by steven-bailey** [comment]
+1

We also have a similar route, which allows fetching a previously generated document off of file storage.  Would be great if this response didn't trigger a save dialog in Runner (at least).  Interrupts flow if you're trying to test a large API.

**Comment by vkaegis** [comment]
@saiudayakella @steven-bailey The response section in the builder has been updated so that you can download the response retrospectively once the response has been received. In this case and in the runner, we don't throw a save dialogue anymore. Closing this issue for now, feel free to open another if you have more feedback on this.

P.S. This doesn't automatically download the PDF though, if that was your expected result, you can reopen this issue and ill treat it as a feature request for a configuration.
