### ISSUE TITLE
Feature request: Change collection owner to another team member

### ISSUE THREAD

**Issue by stianlagstad** [a85/POSTMan-Chrome-Extension#3274]
I'd like the ability to transfer the ownership of a collection I've shared with my team to someone else on the team (we're Postman Pro users).

**Comment by sdnts** [comment]
@stianlagstad Thanks for the feature request! While this isn't part of our immediate [roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers), we'll dig deeper into this problem :)

**Comment by edininjas** [comment]
Plus 1 vote

**Comment by digicyc** [comment]
Plus 1 vote

**Comment by dhiren-mudgil-olx** [comment]
Plus 1 vote

**Comment by hendrys** [comment]
Plus 1 vote

**Comment by ckee83** [comment]
Plus 1 vote

**Comment by eastonharvey** [comment]
To append this request, it would be really useful to allow the "Team" entity to own collections instead of individual users. We have team members that come and go and it's scary to let them own anything, especially collections that will be used for a long time to come.

**Comment by stefanmoro** [comment]
Plus 1 vote

**Comment by lemex92** [comment]
Plus 1 vote

**Comment by pskrebe** [comment]
Plus 1 vote

**Comment by Strato** [comment]
Plus 1 vote

**Comment by chenkirk** [comment]
I am hoping this can get a bit more attention.

Restricting one owner/admin per collection means multiple admins in a team need to share the login to perform their admin tasks. Sharing login is not good, both from the team's perspective and Postman's revenue model.

**Comment by brihulse** [comment]
Plus 1 vote

**Comment by jamesmehorter** [comment]
+1

> To append this request, it would be really useful to allow the "Team" entity to own collections instead of individual users. We have team members that come and go and it's scary to let them own anything, especially collections that will be used for a long time to come.

**Comment by sankalp0o** [comment]
@stianlagstad @chenkirk @eastonharvey 
We're working on a more elaborate role based access control system. As part of this, we're moving away from users having "ownership" of team resources. Users will be able to have roles on the collection instead. I think this will fit in with everything I've read in this thread.
I'll post updates when we have them. While we're working on this, I'd be interested in knowing about the kind of roles/permissions (on collections) that you guys would want to use.

**Comment by eastonharvey** [comment]
@sankalp0o 
Great to know, thank you for the update. My feedback would be to have standard yet robust roles. This would include:
- The owner can make others owners (Owners have read/write access to the shared resources)
- Owners can add users and give users (read only or read/write access to the shared resources)

This would be very useful for the teams I'm on

Thank you again!

**Comment by Edward006** [comment]
+1
If it's predefined roles, then 3 roles: Owner/Admin, Editor, Readonly.
Otherwise you can leave role definitions open, and we can manage roles in each team.
Currently it's very problematic when the owner leaves the team/business

**Comment by brihulse** [comment]
I would agree with @Edward006 
Owner/Admin that can manage permissions on the collection as well as Editor and Readonly
Editor which can CRUD everything except collection name and doesn't have access to change user access.
Readonly which can use collections, but can't make any changes.

**Comment by mheyder1** [comment]
Is there a way for the Team Admin to see which collections a user owns when they leave the organization? If so, how can we transfer ownership to their manager?

**Comment by ryanshores** [comment]
Is there a way to transfer ownership of the collection within the team? Our admin role owns the team, but my account owns the collection. Ideally I would like the role to be transfered.

**Comment by a85** [comment]
The new role based access control system in Postman is rolling out now that does away with the concept of an owner. Collections and other entities can now be transferred easily by assigning roles instead of owners being moved around. Thank you everyone for your feedback! We will continue improving this and will also support custom roles.

**Comment by a85** [comment]
Role Based Access Control is now available for all teams in versions 7.0+

**Comment by mikesigs** [comment]
It seems there is rbac now, but still no way to transfer ownership of a collection. I am a Team Admin, and yet I have no ability to modify the roles of collections created by people who have left the organization. This essentially locks down the collection, which isn't great. Can this be re-opened to support this feature fully?

**Comment by sankalp0o** [comment]
@mikesigs thanks for the feedback!
- A Team Admin doesn't have any special privileges in Postman as far as resources like Collections are concerned. We have plans on introducing another role for this and it's tracked in #6102 .
- Like @a85 mentioned, shared collections belong to the team and removing the creator from the team won't affect them at all for the rest of the team.
- Someone will always have the Collection Editor role on a shared collection. When the last person to have an Editor role on a collection leaves the team, the Editor role is assigned to the whole team so that the collection remains unlocked.

Thus my recommendation would be to remove people who have left your organisation from your Postman team. This should still leave you with someone **in** the team who can manage the collection. If this isn't the case, please let us know and we'll fix this asap.

**Comment by lehman** [comment]
+1

**Comment by mwyld** [comment]
+1
