### ISSUE TITLE
express.js server don't send data back to Postman

### ISSUE THREAD

**Issue by RaziMailk** [a85/POSTMan-Chrome-Extension#3319]
when i make post request from postman, the request data was shown server but server response i.e status code and json object was not send to postman, postman was loading...

here is my server.js class

var bodyParser = require('body-parser');
var express = require('express');

var {mongoose} = require('./db/mongoose');
var {Todo} = require('./models/todo');
var {Users} = require('./models/Users');

var app = express();
app.use(bodyParser.json());

app.post('/todos', (req, res) =>{
  var todo = new Todo({
    text: req.body.text
  });

todo.save().then((doc) => {
  res.send(doc);
}, (e) => {
  res.status(400).send(e);
});

});

app.listen(3000, () =>{
  console.log('started at port 3000');
});

**Comment by sdnts** [comment]
Hi @RaziMailk, this doesn't look like a problem with Postman itself, so Im closing this.

Also, as far as I know, mongoose does not use Promises, which is why code inside your `then` blocks doesn't execute, so the response is never sent. StackOverflow would be more suited for this question, as this might be an issue with the way your server is set up :)
