### ISSUE TITLE
Postman update no longer retains sessions with Laravel 5.4

### ISSUE THREAD

**Issue by emackie9** [a85/POSTMan-Chrome-Extension#3320]
## App Details:

```
Postman for Mac
Version 5.1.2
OS X 16.7.0 / x64
```

## Issue Report:
 1. After installing the Postman update v5.1.2, Postman no longer retains the same session with my Laravel API. A new token is generated with each request. This does not happen in v5.0.2 nor does it happen on other client apps consuming the API. 
 2. Expected behaviour:
 - Run a login endpoint that authenticates (using basic auth) and initiates a session with the server
 - Access other endpoints utilizing the cached data on the session  
 3. Not sure what I should post from the console, this seems to be an issue with the cookies. On server side session is generated and the cookie is created in the Postman MANAGE COOKIE window, but the next call on an internal endpoint is rejected. Server side I note that the session id has changed and the cached data gone with it, likely because it couldn't recognize the cookie, and created a new session.  

Clearing cookies does not help. I'm no expert on sessions and cookies but I'm only having this issue with the Postman 5.1.2 update.

Steps to reproduce the problem
It's a local server, but let me know and I'll post what I can. 

Thanks in advance

**Comment by sdnts** [comment]
Hi @emackie9, can you check if this is happening because the cookie is expired? We've fixed an issue internally where cookies get expired before they're supposed to, so I just want to make sure this isn't another instance of the same problem.

If this is indeed happening because the cookie is expired, can you try this out on our Canary channel and see if this is fixed?

You can download canaries using these links:
OSX: https://dl.pstmn.io/download/channel/canary/osx_64
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64
Linux 32-bit: https://dl.pstmn.io/download/channel/canary/linux_32
Linux 64-bit: https://dl.pstmn.io/download/channel/canary/linux_64

**Comment by davehorn** [comment]
FYI - Experienced same problem on same OSX build.  Canary build working fine.

**Comment by emackie9** [comment]
Thanks for the responses guys,

So I ran on Canary and it worked fine, had a peek at the cookies for both new Postman build and Canary. It looks like an issue with the expiration date. The server has the cookie set to expire in 2 hours, the difference is in Canary gives me the cookie with expires in GMT time, as my server delivers it in the header. Postman build converts it to an EDT time (a correct one of course -4 hours behind but still 2 hours ahead of my current time). 

The strange thing is Postman v5.0.2 gives me an “offset” time as well, it says it in EDT but it was actually the proper GMT time of the cookie expiration!

Its looking like that EDT time maybe the culprit, the time is correct of course but its not how my server is delivering it in the header. I checked the dates before but I must of been mixed up because the old build of Postman says EDT time, but never realized it was actually GMT. Likely the server is processing it as a GMT time regardless, which already “elapsed”.

Eric

**Comment by scottclayton** [comment]
I also had this issue with `5.1.2` (on MacOS) using a session cookie. I'm happy to report that Postman `5.1.3`, released yesterday, does not have this issue for me.

Thanks!

**Comment by prashantagarwal** [comment]
@scottclayton , Thanks for confirming this. @emackie9 This should also work for you. If it still does not work for you, feel free to reopen the issue.

**Comment by kamalaknn** [comment]
Hey @emackie9,

Your description has nailed the exact problem. The older versions of the Postman App(up until `5.0.2`) would offset the cookie expiration time with the user timezone. Which is why it used to work for you earlier, but not ideal for everyone. It would also mean your cookie expired at a different time than what the server intended to.

We've fixed that in `5.1` where we treat all `expires` in cookie headers in GMT(according to the spec). This is why in the newer versions your cookies expire at the exact time the server intended to. However, we missed that the Postman App while resending cookies, has always been sending the cookie expiration in user timezone instead of GMT. Which is also wrong but did not surface earlier because of the timezone offset. This is why in the newer versions, some servers think the cookie has already expired. This fix is now out in the stable channel as well.

For any future passers by, this behavior should be fixed in versions above `5.1.3`.

Thanks.
