### ISSUE TITLE
Paste OAuth token

### ISSUE THREAD

**Issue by maxima120** [a85/POSTMan-Chrome-Extension#3353]
## App Details:
Postman for Windows
Version 5.1.3
win32 10.0.15063 / x64

## Issue Report:
1. Expected behaviour:
be able to paste a token as is for OAuth 2

2. what I get:
clicking on Authorization tab and selecting OAuth 2 gives no editable fields.. only way is to use Get New Access Token. Which I cannot use because we use grant type "password" and Postman has no such thing (or at least I cant find it).

![image](https://user-images.githubusercontent.com/10121753/29034330-4d2afd56-7b98-11e7-9bf1-66957ba0da54.png)

**Comment by prashantagarwal** [comment]
@maxima120 Thanks for suggesting this. We are already working on some improvements around authorization flows. We will try to incorporate this suggestion as well.

**Comment by maxima120** [comment]
thank you... are you planning to add grant type "password" (or to similar effect) for "get new token"? it would be very useful too (as tokens expire, you know :) )

**Comment by kamalaknn** [comment]
@maxima120 could you update to our latest version `5.3.1`?

From this version, we have added an input where you can enter your "Access Token". Also we've added the `Password` grant type to the `Get New Token` flows.

I am closing this issue since this has shipped out. Feel free to leave a comment if you are facing any issues. Hope this helps.

Note: The new features are only available on our Native apps. You can find the download link [here](getpostman.com/apps)
