### ISSUE TITLE
2FA authentication for Postman APP 

### ISSUE THREAD

**Issue by appraveen** [a85/POSTMan-Chrome-Extension#3367]
## App Details:

```
Version 5.1.3 (5.1.3)
MAC 10.12.6 Sierra
```

## Issue Report:
I am using MAC Postman APP. While sending requests from POSTMAN APP, some of the hosts require 2FA authentication. Since POSTMAN APP does not prompt for password and manage the session, my requests fails. 
I am able to achieve this through chrome postman app. Steps I follow for chrome app,
* Goto chrome and hit the host URL, chrome then prompts for 2FA authentication. 
* After signing in with 2FA, the session is preserved in cookies. 
* Having the interceptor on the chrome app version of postman uses the same cookie and authenticates to the hosts that require 2FA

Postman APP in MAC does not support 2FA and the absence of this feature is blocking our team to use the app. Please provide a solve for authentication.

Submitted a request 12310 from postman website and I've been asked to create this issue in GIT.

**Comment by prashantagarwal** [comment]
@appraveen We are already working on lots of improvements around Authentication flows. We will try to include this as well as a part of it. I will keep you updated about this here.

**Comment by harryi3t** [comment]
@appraveen 
I thought 2f2 is only for websites (e.g Google, FB, Amazon, etc) and not for APIs
Can you give me an example of the API that you are using which requires 2f2?

**Comment by npadhya** [comment]
@harryi3t  2FA are common for any sites, just like @appraveen  I also have some internal applications required 2FA and calling this application's API need me to pass the 2FA to get proper response.

**Comment by harryi3t** [comment]
@npadhya Exactly, 2FA is for __websites__. It can't be used directly on the APIs, although the result of the authentication could be used. For eg, after the 2FA is successful, the server might set a cookie or send a token or something else that could be used to make the further API calls.

I think you can authenticate yourself on a browser using 2FA, and then manually copy the cookies/token to Postman, and it should work just fine.

Also if you can give me an example of publicly accessible API which needs this, I could help by sharing the steps needed.

**Comment by shamasis** [comment]
I was going through older issues and noticed this. The discussion on the issue was around MFA on API calls. I see that we are disambiguating the original submission. The question was, are we discussing MFA on a website or on an API.

MFA on a website is an end-to-end feature and as such is not something that can be built as a feature within Postman. MFA on APIs is something that we are seeing getting popular to add parity with websites. NPM APIs and AWS APIs are some popular examples of the same. Having said that, there does not seem to be any standard around the same (correct me if I am wrong here.) Every API provider has their own way of doing it and consequently, it is documented how to do the same using standard HTTP APIs. Which, in turn, implies that most MFA on APIs can be executed using Postman.

Closing this issue based on above inferences. Please comment on this to reopen.

**Comment by jkewley** [comment]
I think you guys should reconsider this. Enterprise APIs for LOB applications commonly use Active Directory accounts and OAuth endpoints provided by AAD or ADFS. Your current OAuth 2.0 option for authorization is very opinionated in that it requires a client id / secret approach which is application-centric rather than user-centric. As an example, we have some APIs which only allow users in specific AD groups to invoke them.

There are other Electron applications which offer user-based auth with MFA support using the code grant flow. See [Azure Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/), [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is?view=sql-server-ver15) or [VS Code](https://github.com/Microsoft/vscode/). One guy wrote an article on [how to add code grant flow in Electron](https://medium.com/@jmsessink/azure-ad-oauth-2-0-authorization-code-grant-flow-in-electron-4f58d6d5eaa0).

Please consider the needs of your enterprise customer base - those who are likely paying for your pro and enterprise licenses.
