### ISSUE TITLE
Postman tests problem with header Content-Type

### ISSUE THREAD

**Issue by mairo744** [a85/POSTMan-Chrome-Extension#3394]
My many tests crash on "Content-Type" because it was changed on "content-type" (lowercase).
Is it bug or new feature?
Can i simple rewrite this for all tests?

Postman fails:
tests["Content-Type is present"] = responseHeaders.hasOwnProperty("Content-Type");

Postman passes:
tests["Content-Type is present"] = responseHeaders.hasOwnProperty("content-type");

Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 60.0.3112.90

**Comment by prashantagarwal** [comment]
@mairo744 Thanks for reporting this. We will investigate this issue and get back to you.

**Comment by kamalaknn** [comment]
Hey @mairo744 

We've seen that the newer version of Chrome has been lower casing response headers in XHRs. We understand that this could be annoying to you, but this is something out of our control since it is coming out of Chrome.

You can try out our native apps where this would not happen(since we have more control over requests than the Chrome app) and we have a lot of other features as well. You'll find the download link suitable for your platform here - https://www.getpostman.com/apps. To read more about our native apps check out our blog - http://blog.getpostman.com/2017/03/14/going-native/

Please let us know if you are still facing the same issue in our native apps.

Thanks!

**Comment by mairo744** [comment]
Thanks for answer in native apps Content-Type works fine but is more difficult to manage cookies. 
Is any way to share PHPSESSID between chrome and postman?
I can manage manual but it is complicated.

**Comment by kamalaknn** [comment]
@mairo744 umm actually no. The only possible option now is to manually add the cookies to the native app. We are looking into ways we can make cookies easier in the native apps n the long term.

I'm closing this issue. Feel free to continue any discussion here.
