### ISSUE TITLE
[Bug] Collection Runner: Strange reading behavior of CSV-file

### ISSUE THREAD

**Issue by milancheck** [a85/POSTMan-Chrome-Extension#3427]
## App Details:
Postman for Windows
Version 5.1.3
win32 10.0.14393 / x64

## Issue Report:
 **1. I encountered this bug recently**
 **2. Expected behaviour:**

According to:
https://www.getpostman.com/docs/postman/collection_runs/working_with_data_files

Having the files in the following format (delimiter between columns as ", ")
column1, column2
data1, value1
data2, value2

The data-file should be previewed/read without blank character

 **3. Actual behaviour:**
The data-file are being previewed/read with blank character
OR
The last line of the file has different data type(?)

 **4. Screenshots**
http://imgur.com/a/dGOMw

##

**Comment by sdnts** [comment]
@MilanD93 The app does not attempt to change any data provided. Since the delimiter for a CSV file is `,`, the space counts as the next column's first character. 
I believe this behaviour is correct, as treating `, ` as a delimiter may break other use cases. I'm closing this, but please reopen if you feel differently :)

**Comment by milancheck** [comment]
@madebysid You didn't check my screenshots right? And what Postman document-site says about working data files? The provided CSV-file itself has blank characters! Please chceck my screenshots and reconsider the closing of my ticket... I believe I provided an adequate reasons, why this behaviour should be taken into consideration as an error. Thanks

**Comment by milancheck** [comment]
@madebysid Check out the Screenshot Number 2. The last line behaves as a number and all the previous ones as a string.

**Comment by sdnts** [comment]
@MilanD93 You're right, this does seem odd that only the last row behaves differently. Are you using the exact same file from our docs in your Runner as well?

On that note, we'll update our documentation to reflect the same.

**Comment by milancheck** [comment]
@madebysid Yes. The last screenshot refers to the file from your docs. On the first screenshot/file (which originates from your file) I did scome changes, deleted blanks respectively.

**Comment by vikiCoder** [comment]
Hi everyone,

I would like to inform that we have made some changes related to CSV file parsing under the hoods in the Postman App. This issue is fixed as part of those changes, postman now trims extra spaces before and after the `,` while parsing CSV file. It is available on the [latest canary](https://www.getpostman.com/downloads/canary) version (Version 7.1.1-canary07) of the app. You can check out [canary](https://www.getpostman.com/downloads/canary) and let us know if you are still facing this issue in it.

However, for the users who don't want this behavior or want to have more control over parsing, we are planning to provide options related to CSV file parsing behavior in our long term roadmap. Suggestions are always welcome regarding what options you would like to have when we add them.

**Comment by vikiCoder** [comment]
Fix for this is out in [latest Postman App](https://www.getpostman.com/downloads/) (v7.2.1) as well.
