### ISSUE TITLE
[Suggestion/Feature] Custom Snippets/Code Library

### ISSUE THREAD

**Issue by milancheck** [a85/POSTMan-Chrome-Extension#3432]
## Suggestions:
 1. Edit/Delete/Reorder default snippets
 2. Add custom code snippets
 3. Code Library interface for functions etc.
 4. Sharing of the custom code snippes and functions within my team

**Comment by sdnts** [comment]
@MilanD93 Thanks for the feature request! I suppose this will be possible when Plugins are introduced in the app. #3321 addressed this. You can also follow our [roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers) to track progress.

I'm closing this in favour of #3321, please reopen if you feel otherwise :)
