### ISSUE TITLE
Update postman collection from swagger specification file

### ISSUE THREAD

**Issue by tarunairvm** [a85/POSTMan-Chrome-Extension#3444]
App Details:

Postman for Mac
Version 5.1.3 (5.1.3)
MacOS Sierra

## Issue Report:
I'm importing a swagger specification file into postman to create a collection, at this point, works as expected and the collection is generated with all requests & sub-folders, fine!!. But when the api is updated, I need update the postman to update all requests based on the new specification. I can't find a action like "update" or something else. I'm trying import the new specification into postman and he say:

A collection APIName already exists. What would you like to do?
Replace or Import as copy

a copy its a not feasible option, then I use replace and the existent collection is updated, but all tests, parameters, pre-req scripts are remove and I need reconfigure all again.

I'm missing something, exist a way to import & update a existent collection from a specification file, without losing existent tests & configuration?

**Comment by sdnts** [comment]
@tarunairvm Currently, Swagger imports are designed to be a one way transform. When you re-import a changed swagger spec, there's no way for us to correlate your swagger requests with Postman requests, so updating requests wouldn't be possible.

May I suggest updating your API in Postman directly so that you don't lose your tests?

**Comment by steveardis** [comment]
I was hoping for the same type of functionality.  Wouldn't an update be possible if you used the endpoint URL and HTTP verb?  For example, "GET" and "/v1/someEntity/".  You would need to ignore the protocol, hostname and port I believe.

**Comment by jpambulo** [comment]
Do you already have the functionality for this?

**Comment by lorengreenfield** [comment]
@madebysid Sorry to comment on a closed issue! 
I'd pay extra on the monthly membership fees to have this functionality. Our swagger file is generated from our application with hapi-swagger, which we then import into postman. Being able to re-import and merge (so that tests are not lost), would be awesome. Using the endpoint as a key for merging seems reasonable, no?

**Comment by dvetal** [comment]
Just to pile on after the fact here. This is pretty critical for us as well and would be a fantastic feature.

**Comment by a85** [comment]
People, this issue is being tracked in multiple places #3390. We have some big improvements here planned. Stay tuned. We'll post details on how we are going to address this and other related items soon.

**Comment by hellboy81** [comment]
As I mentionied all changes should be integrated manually?
