### ISSUE TITLE
Feature request: encodeURIComponent URL params automatically

### ISSUE THREAD

**Issue by will-beta** [a85/POSTMan-Chrome-Extension#3471]
do
``` javascript
encodeURIComponent("2017-04-10 00:00:00.0000000 +08:00")
```
get
``` javascript
"2017-04-10%2000%3A00%3A00.0000000%20%2B08%3A00"
```

Thanks!

**Comment by sdnts** [comment]
@will-beta On native apps, this automatically happens in the background, when you send a request. Are you seeing any inconsistencies here?

**Comment by will-beta** [comment]
@madebysid 
Thanks for the reply!
But it didn't happen to me. Here's the screenshots:
![qq 20170904102401](https://user-images.githubusercontent.com/14272334/30009583-0a09daae-915c-11e7-9663-45887f7017c1.png)

I gave two params in this case. 
The param 'wrongDateTimeOffset' took the original value, whereas the '+' symbol in it got lost when been appended to the URL.
The param 'correctDateTimeOffset' took the converted value produced by 'encodeURIComponent' Javascript function manually, and it's been handled in the right way.

**Comment by sdnts** [comment]
@will-beta The symbol gets "lost" because it is treated as a space, since `+` is reserved for that. We've visited this multiple times, the problem is, there's no way for us to determine if a `+` symbol was added as a space or the actual symbol. So, the app imitates browser behaviour, and treats it as a space.

Unfortunately, I'd have to suggest you manually encode it to make sure it gets sent correctly. You can select text in the URL bar, and right click > EncodeURIComponent to do this quickly.

Please reopen if you disagree :)

**Comment by will-beta** [comment]
@madebysid
It seems like the Postman just simply combined the params entered into the URL.
I think it would be more appropriate to encodeURIComponent the params first, and then combine the result value into the URL.
