### ISSUE TITLE
Do not see POSTMAN enable interceptor button

### ISSUE THREAD

**Issue by chiragverma** [a85/POSTMan-Chrome-Extension#3477]
1) I have installed chrome postman interceptor extension(https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en)

2) Now when I open POSTMAN, i do not see the interceptor icon on the postman app.

**Comment by sdnts** [comment]
@Chiragverma Are you on the native app? The native apps do not need the Interceptor, so the button isn't there. You'll need the Chrome app to work with the Interceptor.

I'd advise against that though, since Chrome apps will be deprecated by Google later this year. Native apps have the ability to handle cookies on their own, and should be able to replace Interceptor + Chrome app for most use cases.

Please reopen if I misunderstood

**Comment by RalphSu** [comment]
Does native app Postman 2 support autoconfig proxy like chrome plugin?
