### ISSUE TITLE
Archive Folders/Requests in Collections

### ISSUE THREAD

**Issue by abhidp** [a85/POSTMan-Chrome-Extension#3485]
## App Details:

```
Postman for Mac
Version 5.2.0 (5.2.0)
OS X 10.12.6 (16G29) / x64
```

## Issue Report:
 Please add an option to Archive Folders or Requests from the Collections tab. Some folders which I don't use frequently need not be sitting in the working panel. 
As of now I can only delete them which makes them vanish forever and not hide/archive them. 
If there is an option where I can archive the unused Folders/Request and pull them back to view when I need them later, it will be a very good enhancement and remove clutter from the working folder.
<img width="314" alt="screenshot at sep 05 11-42-47" src="https://user-images.githubusercontent.com/30851622/30041682-68ec0dac-922f-11e7-9caf-c7033df718cb.png">

**Comment by sdnts** [comment]
@abhimassive This is an interesting idea! We'll investigate.

**Comment by adiworkoholic** [comment]
This is an absolute necessity. Please address this sooner.

**Comment by ferronrsmith** [comment]
this is needed.

**Comment by andmill** [comment]
Agreed!! The only way I'm working it now is to Export them and save the collection files, then delete from Postman. Not a neat solution though but sufficient for keeping the workspace clean.

**Comment by adiworkoholic** [comment]
If not archive, you can provide a UI (client side) way to hide them. Hopefully that is quick and easy way to address this in the interim.

**Comment by ChuckkNorris** [comment]
Potential quick fix -> Allow users to drag and drop collections into other collections to become subfolders.

Then we can create an archive folder ourselves.

**Comment by brianbellon** [comment]
I just submitted the same idea of Hide/Unhide above that seems to work great in JMeter.  I also wonder if Postman should prompt to Export when calling delete with a folder or full collection since a lot of information could disappear with no chance of recovery (that I know of).   I also have to work with a few  copies of a collection to work around this issue - one for the "full" version, and another that I can strip out any unnecessary call to get to my debugs quicker.  After it's fixed, I have to move the fix back to the full collection.   And I'm always afraid I could lose something in this process.

**Comment by a85** [comment]
You can use Workspaces to manage your collections along with other things more effectively.
