### ISSUE TITLE
Regular Syncing Issues

### ISSUE THREAD

**Issue by cajund** [a85/POSTMan-Chrome-Extension#3504]
## App Details:
```
Postman for Mac
Version 5.2.0 (5.2.0)
OS X 10.12.6
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:

This has started recently - any changes made to the collection (either with creating a new endpoint, saving, or simply reordering the endpoints) results in the "sync issue" dialog.

 2. Expected behaviour:

No errors, of course! ;-)

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Additionally, I am syncing with GitHub, and I am approaching 1000 commits all being driven by Postman. Can this automatic syncing be switched to manual? Trying to find my manual commits in the list is getting difficult. I suspect that the growing number of commits is slowing the process down and causing the syncing issues.

Thanks!

**Comment by sdnts** [comment]
Hi @cajund, Do you have a set of steps that I can take to reproduce this?

When you say you use GitHub, do you mean you're using the GitHub integration?

**Comment by chrisron95** [comment]
I have also been having this issue. Anytime I rename or reorder a call, I have to wait for the sync conflict dialog to pop up. The majority of the time there's not even any difference between the local and server values, but I always select local values. Also, a lot of times when I go to reorder any of my calls, I have to start to move it by clicking and dragging, then I have to wait for the app to unfreeze after a good minute or two, then I can go back and move it.

Most recently (about two hours ago), I simply moved one call, the sync conflict dialog popped up, and when I selected local values and let it resync, 15 of my calls were removed from their folders and placed at the very end of the collection in a random order that took me a good half hour to figure out and put them all back where they belonged.

This issue has been going on consistently for me for the past month or two, and through multiple updates.

```
Postman for Mac
Version 5.3.0
OS X 17.2.0 / x64
```

**Comment by nchaluse** [comment]
I couldn't agree more on the very last comment. If sync in enabled, it takes ages to just move a request from one folder to another. The app freezes, then the sync pops up, I choose local values without even taking a look at everything, then the app freezes again for a solid 1-2 minutes and I'm back to being able to use it. On the other hand, if sync is disabled, all goes smoothly.

Is there a way to not sync every second or so, or to manually push a kind of commit for the team collection to be updated (or even my own personnal collection to be updated). That'd be great. I find the team collection update and overall process to be off and ineffective. One can't know the recent changes, who made them (without going to the website, unnecessary use of the browser here), and what one's own changes are going to mess things up if changes have already been made.

We desperately need something clear and usable, a real versionning control tool to be honest. We 'my team and I) are really considering switching back to SoapUI because of this.

BTW, Postman is great, but the team collection really is flawed (or we don't know how to make it work)

**Comment by kamalaknn** [comment]
Hi @cajund @nchaluse @chrisron95 

We've pushed some major improvements to the Sync layer in our latest version. Please update to the latest version. Let us know if you're still seeing issues related to this.

**Comment by numediaweb** [comment]
I have [the latest](https://prnt.sc/iwgw70) Postman version 6.0.10 for Mac 10.13.3 and starting from last week or so I continuously have this syncing issue. 
The Syncing[ button is always blue](https://prnt.sc/iwgw38) and the sync conflict pops up every 10 minutes or so: kind of frustrating.
Also in the settings I cannot click on the Re-sync button as it is [grayed out](https://prnt.sc/iwgwam).

**Comment by kamalaknn** [comment]
Hi @numediaweb 

If you can provide us more data to reproduce it will be helpful. Could you export the logs for the sync process when you face the issue?

You can `View -> Developer -> Show DevTools (Shared)` and `Right Click -> Save as...`. Please send the log file to `help[at]getpostman.com` from your registered email id. This might contain sensitive data, please send them through email.

Thanks.

**Comment by numediaweb** [comment]
Hi @kamalaknn 

Somehow the sync is working again: I didn't do anything special (maybe I have chosen to use server settings instead of client).
Now the Blue sync icon turns to orange IN SYNC.
Strange though: I have sent the log file.

Thanks

**Comment by erkib** [comment]
I have also the issue that the connection to sync service is failing. From shared console:
WebSocket connection to 'wss://sync-xi.getpostman.com/socket.io/?__sails_io_sdk_version=0.11.0&__sai…tform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 202
Postman version: 6.0.10
I can assure the same problem exists for Windows version app as well. Tested on my Windows 10 installation.

**Comment by kamalaknn** [comment]
Hey @erkib 

Are you still seeing this on the latest version of Postman?

**Comment by erkib** [comment]
No, everything is OK with this feature now

**Comment by kamalaknn** [comment]
@erkib 

Thanks for your confirmation.
