### ISSUE TITLE
postman.setNextRequest function searching request from bottom to top instead of looking backward from current request

### ISSUE THREAD

**Issue by amnoman** [a85/POSTMan-Chrome-Extension#3570]
[setNextRequest.zip](https://github.com/postmanlabs/postman-app-support/files/1341614/setNextRequest.zip)

## App Details:

```
Postman for Windows
Version 5.2.1
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: recently after update.

 2. Expected behaviour: Previously it searched and matched the request from current request to backward but right now searching started from end of the request list. If there is 8 request and from request 3 I used setNextRequest() and it tried to match from 8, 7, 6, 5 .... this sequence instead of 2,1 like before.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

1. download the collection and environment 
2. Runner run it
3. You will see it skipping request 3,4,5 and 6

**Comment by numaanashraf** [comment]
Thanks for reporting this @amnoman. We are looking into this.

**Comment by kamalaknn** [comment]
@amnoman the order of match for `postman.setNextRequest` for multiple requests with the same name is not documented and guaranteed. If you are unable to rename your requests to unique ids, I would recommend using request id for `postman.setNextRequest` instead of the request name. 

Also, I could see in your collection you are using the `setNextRequest` request as a delay, you can try out our delay option in the runner if it helps.

**Comment by amnoman** [comment]
Thanks for the reply. I will go for unique ids. 
For delay I have a special scenario where need to wait 10 sec to 180 sec to get updated status. Instead of waiting 180 sec I just check the status and call for more delay if required.  Moreover, currently there is no way to put delay like SoapUI between two request without exhausting CPU.
