### ISSUE TITLE
OAuth2.0 token error

### ISSUE THREAD

**Issue by aidanhb** [a85/POSTMan-Chrome-Extension#3573]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
I'm trying to make requests to my BigQuery project. In order to do so I need an OAuth2.0 access token, which I've been trying to obtain with Get New Access Token. I filled out the form with all the information I have. A screenshot of the information I entered is below.
<img width="493" alt="screen shot 2017-09-28 at 10 49 31 am" src="https://user-images.githubusercontent.com/17099108/30982256-af3040a8-a43b-11e7-9265-cb08d2ee7f5d.png">
The sign in screen popped up and I allowed postman to access my project when it asked. Then, when the token appeared, it looked weird:
<img width="547" alt="screen shot 2017-09-28 at 10 49 48 am" src="https://user-images.githubusercontent.com/17099108/30982311-da71a252-a43b-11e7-88c7-3536143fdd9f.png">
And, thinking it might just be a display issue, I added it to my request header, I clearly didn't actually have the token:
<img width="653" alt="screen shot 2017-09-28 at 10 51 09 am" src="https://user-images.githubusercontent.com/17099108/30982383-0f828b1e-a43c-11e7-8377-c28b75ea455c.png">
Do you have any idea what caused the successful creation of a token that doesn't appear to actually work? Thanks for the help.

**Comment by numaanashraf** [comment]
Thanks for reporting this @aidanhb. We are looking into this.

**Comment by harryi3t** [comment]
@aidanhb I have few quentions

1. Which variant of OAuth-2 are you using? If `Client Credentials` grant then you need to pick this from the dropdown and second, you need to put that URL in the `access token URL` and not `auth URL`
2. If you are using `Authorization Code` grant then you need an `Access Token URL` also. But in the screenshot, I see that the `Access Token URL` is empty. Is it just in the screenshot and not in the actual flow or otherwise? If you are putting a valid URL in there, then can you post the screenshot and the contents of the call made to the access token endpoint (Open developer console -> network panel). Search for token. In your case there must be an error there.
   ![image](https://user-images.githubusercontent.com/5207331/31046909-e8eda10c-a61e-11e7-9e34-d268cc1389a2.png)
