### ISSUE TITLE
Collection Runner Doesn't Parse Negative Number and Bool Columns in CSV Data Files Correctly

### ISSUE THREAD

**Issue by gqy117** [a85/POSTMan-Chrome-Extension#3576]
## App Details:
```
Postman for Windows
Version 5.2.1
win32 10.0.14393 / x64
```

## Issue Report:
 1. I encounter this recently
 2. Expected behaviour: 
 When using a CSV data file in Collection Runner, it should parse the **negative number** and **bool** columns correctly.
 3. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/5887800/31007332-bdd8db7a-a55c-11e7-872c-ea63d792af15.png)
![image](https://user-images.githubusercontent.com/5887800/31007349-d224600e-a55c-11e7-8e4e-43047dcff0a9.png)

Steps to reproduce the problem:
1. Create a CSV file like below:

stringCol,positiveNumCol,negativeNumCol,boolCol
"1",1,-1,true

2. Open Collection Runner, find Data section and click **Select File**

3. Choose the CSV file we just created

4. Click **Preview**

5. As shown in the screenshots, both **negativeNumCol** and **boolCol** columns are treated as **String**. They shouldn't have double quotes.

**Comment by numaanashraf** [comment]
@gqy117 Thanks for reporting this

**Comment by abhijitkane** [comment]
@numaanashraf We should define the intended behavior here. Either we treat every item in the data row as a JSON primitive or treat everything as a string.

**Comment by vikiCoder** [comment]
Hi @gqy117,

I would like to inform that we have made some changes related to CSV file parsing under the hoods in the Postman App. We haven't changed the behavior of parsing boolean values but negative numbers are now being parsed correctly as Number instead of String. It is available on the [latest canary](https://www.getpostman.com/downloads/canary) version (Version 7.1.1-canary07) of the app. You can check out [canary](https://www.getpostman.com/downloads/canary) and let us know if you are still facing this issue in it.

However, for the users who don't want this behavior or want to have more control over parsing, we are planning to provide options related to CSV file parsing behavior in our long term roadmap. Suggestions are always welcome regarding what options you would like to have when we add them.

**Comment by vikiCoder** [comment]
The changes that I mentioned in my previous comment are out in [latest Postman App](https://www.getpostman.com/downloads/) (v7.2.1) as well.
