### ISSUE TITLE
Username and password not reset after changing Authorization Type to 'No Auth'

### ISSUE THREAD

**Issue by hungapl** [a85/POSTMan-Chrome-Extension#3606]
## App Details:

```
Postman for Linux
Version 5.3.0
Linux 16.04
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
_Encountered recently_

 2. Expected behaviour:
_Change Authorization Type to 'Basic'
Enter username and password
Click Send, username and password are sent with the request
Change Authorization Type to 'No Auth'
Click Send, no credential should be sent with the request_

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 
_None_

**Comment by kamalaknn** [comment]
Hi @hungapl 

Could you verify if this is because `Authorization` header is saved with your request?

If the header is saved with your request, you should see a warning like this,

![screen shot 2017-10-09 at 1 25 45 pm](https://user-images.githubusercontent.com/8401064/31328999-913aa38c-acf5-11e7-8de4-e7c6e4a455db.png)

If you see a warning like 

![screen shot 2017-10-09 at 1 26 26 pm](https://user-images.githubusercontent.com/8401064/31329007-a00932c0-acf5-11e7-9062-22c40b19ebc0.png)

Postman will reset it when you change the Authorization to `No Auth`. You can refer [this issue](https://github.com/postmanlabs/postman-app-support/issues/1463#issuecomment-335087182) for reasoning of this behaviour.

Thanks.

**Comment by hungapl** [comment]
Thanks for the quick reply.  After sending a request with basic authentication, I can see a Authorization header added to the request like the screenshot shown above.  Then I go back to Authorization tab, change to 'No Auth', click Send again.  I go back to the Headers tab, the Authorization field is still there with Value 'Basic XXXXX'.  So changing the Authorization to 'No Auth' does not seem to reset it.

**Comment by kamalaknn** [comment]
@hungapl 

Could you clarify if the header you are seeing is similar to the first screenshot(a yellow warning saying 'This is a duplicate header') or the second one(a black warning saying 'This is a temporary header')?

Temporary headers should be reset on changing auth, not the user entered headers(the duplicate header).

**Comment by hungapl** [comment]
I am not getting either a yellow or black bar on the side of Authorization:
![image](https://user-images.githubusercontent.com/30487789/31371418-faa15f94-add3-11e7-9ea1-78da656c8843.png)

**Comment by kamalaknn** [comment]
@hungapl could you join our [community slack](https://github.com/postmanlabs/postman-app-support#the-community) so I can get on a chat for more details, and avoid the back and forth comments on GH issue?

**Comment by hungapl** [comment]
@kamalaknn I would love to chat, but I wouldn't be online for the rest of the week due to family commitment.  I have request for a slack invite.  I am about to head off now, should be back online and testing with postman again next Monday.

**Comment by hungapl** [comment]
@kamalaknn I have joined the postman slack community

**Comment by kamalaknn** [comment]
@hungapl you can find me at `@kamalaknn` on the community slack, feel free to reach out to me.

**Comment by prashantagarwal** [comment]
@hungapl Was this issue resolved ? If not feel free to reopen this issue.

**Comment by typelogic** [comment]
I seem to be experiencing this issue now. My system is Ubuntu 20.04, and I installed postman the other day. I have to restart my 'spring boot server' just to make POST request fail due to a 'basic auth' wrong password test case. Scenario is, I select-run the wrong password test case and request failed as expected. Next, I select-run the correct password test case and request succeeds as expected. Then, i select-run again the wrong password test case, and request succeeds.  

Updates: Another way I had to deal with it which does not involved restarting the 'spring boot server' is to delete JSESSIONID in Cookies Manager in Postman. It seems, this cookies are being shared across differerent postman reuqests. Secondly, 'spring boot server' does not even check the provided 'Authorization' header if there is a matching 'cookie' header.
