### ISSUE TITLE
Disabling SSL certificate validation doesn't seem to work in native

### ISSUE THREAD

**Issue by JacksonBailey** [a85/POSTMan-Chrome-Extension#3631]
## App Details:

```
Postman for Windows
Version 5.3.0
win32 6.1.7601 / x64
```

## Issue Report:
 1. When I used the Chrome App, if I set a page and got the general error about SSL issues, but visited it in Chrome and added a security exception, then I would still be able to hit it
 2. In the native app, I can't seem to disable SSL certificate validation, even when the option is off in the settings.
3. In the Chrome App it seems to work when I disable this option.

Some of my coworkers seem to have the same problem, but others don't. I'm not sure how to troubleshoot this further, any help would be appreciated. I can provide more details if needed.

**Comment by miluoalbert** [comment]
you can fix this by turning off 'SSL certificate verification' in **Settings > General**

**Comment by jeubank12** [comment]
@miluoalbert he says in 2. above that the setting is not working. I have experienced the same

**Comment by JacksonBailey** [comment]
To give more details on this, my company has a proxy we must use (BlueCoat, I believe), and I believe it is terminating the connection.

In the postman console I see this error in red: `Error: read ECONNRESET`. After googling this it seems to be a Node error that happens when the other side of the TCP connection resets the TCP connection unexpectedly.

I ran wireshark and sure enough the proxy seems to be doing it. I'm not really well versed in this sort of thing, so I don't really know where to go from here.

Unfortunately, I found out that a lot of the severs we use now require SSL client authentication, but I distinctly remember this happening for a few months, only recently did I begin to look deeper.

**Comment by kallekarlberg** [comment]
We have services with self issued certs and when we point "standalone" postman towards these the connection fails. Not sure on how to get more logging out of it.

Pointing a browser to the same endpoint givea a warning on "self-issued" cert that can be "avoided".

Using the "chrome app" and allowing these self issued certs in chrome makes the crome app work. 

To add some more detail.
Hitting our https services works with curl -k, browsers that you can add own trusted certs work to and java works if, certs are either "all trusted" or if you add specific trust.

There are two ways of fixing this:
* Either fix the "skip ssl-cert validation" switch
* Allow users to add certificates into postman trust.

Right now postman is not working which really makes me sad.

Is the code for postman avaliable somewhere?

**Comment by EricPSU** [comment]
I'm having the same issue in v5.5.0 for Linux.  I'm attempting to use a self-signed certificate to make my API call.  With the `SSL Certificate Verification` setting `ON`, I get an error `SSL Error: SELF_SIGNED_CERT_IN_CHAIN`.  When I turn the `SSL Certificate Verification` setting `OFF`, it doesn't send my certificate with the API call.  

It appears the `SSL Certification Verification` setting does not work as intended.

**Comment by AndriiStepura** [comment]
Does anybody know some workarounds for this?

**Comment by dwrz** [comment]
I'm having the opposite issue. With ```SSL certificate verification``` on, I got no errors, even though browser and native apps were reporting invalid certificates. This was with both Linux and Mac versions of Postman.

**Comment by lahirugmg** [comment]
@dwrz Yes, I have SSL certificate verification on and no imported certs in 'Certificates'. Still works. Mac OS, Postman Version 6.0.10 (6.0.10).

**Comment by bensooraj** [comment]
I have the exact same problem. I have tried all possible combos. None work. I am using Version 6.1.3 (6.1.3)

**Comment by kxm187** [comment]
I think my issue is also related, and I think this is related to the enforcement of the Subject Alternative Name.  Details for further investigation:

When I attempt to use the Postman Windows application to make an HTTP-GET (or POST) to certain sites, I get the "Could not get any response" message, and Postman Console shows "Error: tunneling socket could not be established, statuscode=302".   However I am able to connect to the same service deployed on another server.  

The "SSL certificate validation" switch is turned "OFF", and the "Use System Proxy" is turned "On".  Both endpoints (the one that works, and the one that does not) go through our company proxy, so I know the proxy setting is correct.  

When I browse to the those URLs using Chrome, the one that works in Postman has a valid Certificate, while the one that does not shows a certificate issue due to the fact that it does not specify the "Subject Alternate Name".

I tried upgrading, uninstalling, and reinstalling a number of versions of the Windows application

However, if I use the Chrome Postman Extension, both endpoints work!

Versions tried:
Postman for Chrome - Version 5.5.2 - win / x86-64 - Chrome 67.0.3396.87  (Works)
Postman for Windows - Version 5.5.2 - win32 6.1.7601 / x64 (Does NOT Work)
Postman for Windows - Version 6.0.10 - win32 6.1.7601 / x64 (Does NOT Work)
Postman for Windows - Version 6.1.3 - win32 6.1.7601 / x64 (Does NOT Work)

**Comment by agrawald** [comment]
+1

**Comment by adithyaonline** [comment]
+1
this issue has been open for more than a year, pls prioritize and get it fixed !!

**Comment by numaanashraf** [comment]
@adithyaonline Could you share with us any steps we can follow to replicate the issue you are facing?

**Comment by madokadev1003** [comment]
@numaanashraf I think this is related to #3942 - I've been running into this issue (with the SSL setting not solving it on Windows 8.1 the latest Postman version) - I was able to get a workaround by following this: https://github.com/postmanlabs/postman-app-support/issues/3942#issuecomment-350680981

**Comment by codenirvana** [comment]
We've added support for custom CA certificate. Refer: https://github.com/postmanlabs/postman-app-support/issues/3290#issuecomment-477468406

cc. @kallekarlberg @EricPSU

**Comment by JacksonBailey** [comment]
@codenirvana I have long forgotten the exact scenario I encountered this in and for all I know that feature may have fixed my error. Please feel free to close this issue.

**Comment by vovasosnove** [comment]
I run into the same issue when doing get to https://192.168.99.102:8443/api
Problem was that request was going via corporate proxy even when proxy was off in postman settings. 

Adding 192.168.99.102 to no_proxy environment variable, turning off "SSL certificate validation" and restarting postman helped for me.

**Comment by fgustovo** [comment]
Removing HTTP_PROXY and HTTPS_PROXY environment variables was solved my issue.
