### ISSUE TITLE
Pretty View hiding HTML in application/json responses.

### ISSUE THREAD

**Issue by dotancohen** [a85/POSTMan-Chrome-Extension#3635]
## App Details:
```
Postman Chrome Extension
Version 5.3.0
There is no About section in the Settings menu!
```

## Issue Report:
 1. I'm not sure how long the bug has been in Postman, I just noticed it now.
 2. Expected behaviour:
When there is HTML in an application/json response, it is not show in the Pretty view. This makes debugging difficult. Common server side technologies, such as PHP with xDebug, will output errors in HTML.
For instance:
```
<br />
<b>Notice</b>
{
    "resource": "article_lobby",
...
```
The Pretty view will show the following with no hint that there is HTML that is not being displayed:
```
{
    "resource": "article_lobby",

```
 3. Expected behaviour:
Even Pretty View should let me know if there is HTML that is not being displayed, so that one could develop and know when errors are occurring.

I can provide fuller example output files with the HTML in them if needed. Thank you.

**Comment by sdnts** [comment]
Hi @dotancohen, if I understand correctly, your server is returning HTML with an `application/json` Content-Type, correct? We usually look at the content type header to determine how to parse the response, which is why you're seeing this. Can you show me an example response that does this? I'm only interested in the structure, you can remove any sensitive values from there.

Also, can you try doing this on our [native apps](https://getpostman.com/apps) as well?.Chrome apps are being deprecated by Google, so I'd recommend switching as soon as you can.

**Comment by dotancohen** [comment]
Thank you.
Yes, the server is responding with Content-Type application/JSON because that is what the response _should_ be. However, due to whatever bug I coded at the moment the server is outputting an HTML error message.

Postman is in fact being very helpful by ignoring this HTML. Too helpful, as in fact while debugging I need to see these error messages. It would be nice if Pretty View hiding of HTML could be suppressed.

I am using Postman for Linux now, and of course the issue affects that version as well. Thank you.

**Comment by torasike** [comment]
@dotancohen use Postman console to see full information of responses.

**Comment by dotancohen** [comment]
@torasike That is not a solution as I have no way of knowing that there was additional output that needs to be addressed. That's the problem: when using Pretty Print there is no indication that some output has been hidden.

**Comment by torasike** [comment]
@dotancohen you can add a simple test script for your collection or request, to identify if something was wrong.

**Comment by OldStarchy** [comment]
If the content type in the response is marked as "application/json" and for some reason, the content of the response has non-JSON in it, postman should show a syntax error on the "pretty" tab rather than just silently eating it up.
I'm using postman (windows app) to test if my endpoints are returning the correct response, but as it is I'm false positives, leading me on a wild goose hunt at the other end of my project.

This should be marked as a bug, or at the very least an important enhancement.

**Comment by prashantagarwal** [comment]
Tracking in #4758

**Comment by kamalaknn** [comment]
Hey folks, this is fixed now.

<img width="1440" alt="Screenshot 2020-03-18 at 11 44 36 AM" src="https://user-images.githubusercontent.com/8401064/76931154-0efad680-690e-11ea-8e8e-e1292efc41c4.png">
