### ISSUE TITLE
client secret not included in oauth2 token request

### ISSUE THREAD

**Issue by wichert** [a85/POSTMan-Chrome-Extension#3655]
## App Details:

```
Postman for Mac
Version 5.3.1
OS X 17.0.0 / x64
 ```

## Issue Report:

I am trying to request on Oauth2 token from HubSpot. This is failing on the last step: HubSpot [requires the client secret to be in the token request](https://developers.hubspot.com/docs/methods/oauth2/get-access-and-refresh-tokens). Postman does not include that, which is causing the token request to fail.

```
POST
https://api.hubapi.com/oauth/v1/token
11:29:09.334
Pretty
Raw
POST /oauth/v1/token
content-type: application/x-www-form-urlencoded
authorization: Basic *****
user-agent: PostmanRuntime/6.4.1
accept: */*
host: api.hubapi.com
accept-encoding: gzip, deflate
content-length: 183

grant_type=authorization_codecode=*****redirect_uri=https://crm.curvetips.net/oauth2/callbackclient_id=****

HTTP/1.1 400
status: 400
access-control-allow-credentials: false
content-type: application/json; charset=UTF-8
content-length: 177
date: Thu, 19 Oct 2017 09:29:09 GMT
connection: close

{"status":"BAD_CLIENT_SECRET","message":"missing or invalid client secret","correlationId":"c7237df4-6bc6-4cdd-879b-066308cc3b59","requestId":"1b22c8aa42b09296e73135b3b4560444"}

Could not complete OAuth 2.0 token request

missing or invalid client secret
```

(On a side-note: the `&`-separator between fields is missing in the raw response output in the Postman console).

**Comment by harryi3t** [comment]
@wichert This is most likely happening because the server only supports the client credentials in the request body while you are sending it in the header.

Could you try with `Client Authentication` set to `Send client credentials in body`?
![image](https://user-images.githubusercontent.com/5207331/31765497-33899438-b4e2-11e7-819f-30374f6f25f8.png)

Before 5.3.0 we were sending the credentials in both the places which was [not spec compliant](https://tools.ietf.org/html/rfc6749#section-2.3).
Let me know if this does not work for you.

### Update
In the documentation page that you linked, it mentions that the credentials should be used in request body

> Client Secret | client_secret=x <br>Used in the request body | The Client Secret of your app.
> -- | -- | --

**Comment by harryi3t** [comment]
@wichert Also thanks for reporting the `&-separator` bug in postman console.
We will fix it in the next version.

**Comment by wichert** [comment]
Thanks for the quick response! Switching to credentials in the body indeed fixes it.
