### ISSUE TITLE
Load collection from file system on app load

### ISSUE THREAD

**Issue by codewithtyler** [a85/POSTMan-Chrome-Extension#3656]
## App Details:
```
Postman for Windows
Version 5.3.1
win32 10.0.14393 / x64
```

## Feature Request:

I work on multiple **open source** web app projects and we use Postman to test our endpoints as we build them. Unfortunately this causes our team to have to export and share our collections back and forth a lot as we build new endpoints. It would be really helpful if Postman had a setting we could enable that would let us point it at a file on the file system and anytime Postman is opened (or a refresh button is clicked) the app would go out and read that collection file and reload the collection in the app. 

This would simplify our ability to keep things in sync between our team because we could just add our collection's JSON file into our source code and just have Postman pointed at that file on our file system.

**Comment by deepakpathania-zz** [comment]
Hey @tylerbhughes. Collection exports actually reflect the collection as a snapshot in time, and therefore must be updated to refresh the changes to the collection. Your point of pointing to a single file that can be synced seems valid but collection links kinda already do the same as far as my understanding goes. 

I mean if you generate a collection link or embed or share collections via the embed button, you basically get a unique identifier for your collection that remains consistent even if you update the collection by adding more requests to it.  So rather than exporting and sharing your collections, you can share the collection link among the team, update the collection itself in the future and then update the link through your app which will be equivalent to the refresh button you suggested. 

I hope this makes sense. Image attached for reference of updating link.

![selection_009](https://user-images.githubusercontent.com/15071438/31781309-c1ec6b14-b515-11e7-9e89-b4d733799ce1.png)

More on this here:  https://www.getpostman.com/docs/postman/collections/sharing_collections

**Comment by codewithtyler** [comment]
@deepakpathania I tried that out with a team member on the project and I was able to make a change and save it but we didn't see a way for him to be able to sync and see my changes. Do you know how to do that without him having to delete the collection and repull from the link? Also what if he has an endpoint to add and I want to see his change? How would that work?

**Comment by deepakpathania-zz** [comment]
@tylerbhughes Hey, what you are asking for is available in the Postman Pro version. As you can see at the bottom of the modal in the image I shared earlier, it says that 

> This link does not update automatically when changes are made to the collection. Check out the Postman Pro API to access your synced collections.

Check the following links out for more information. https://www.getpostman.com/docs/postman/team_library/sharing#sharing-collections
https://www.getpostman.com/docs/postman/collections/sharing_collections

**Comment by prashantagarwal** [comment]
@tylerbhughes Like @deepakpathania suggested, your use case very well qualifies for a Postman Pro account. Using Postman Pro you will get seamless Collections and Environment sharing across your team. Also in future we are planning to include many more features which fill further enhance the collaboration experience in Postman. For any further information you can write to us at help@getpostman.com
