### ISSUE TITLE
Monitor performance dashboard doesn't reflect all failed tests

### ISSUE THREAD

**Issue by 7omasz** [a85/POSTMan-Chrome-Extension#3741]
Periodically our monitors fail with a cryptic error message in the `Console Log - Error: Anomalous test`, e.g.:

```
1 18:02:14 Error: Anomalous test failure: Response time is less
than 1s
2 18:04:02 Error: Anomalous test failure: Response time is less
than 1s
3 18:05:39 DDS Health started
```

The collection monitor then reruns and only the last run is recorded on the dashboard and no notification is generated that the original test failed.

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice 👍  we will investigate and update the status here.

**Comment by godfrzero** [comment]
If a monitor runs successfully for a while and then it fails, the monitoring platform will automatically rerun the monitor to avoid false alarms due to transient network conditions. The error message "Anomalous test failure" is logged when this happens. We've pushed out a fix which updates the error message here to be more clear.

The error message update should remove any confusion. Some users have requested that the automatic retry behavior be configurable. This is being tracked in a feature request [here](https://github.com/postmanlabs/postman-app-support/issues/5900). Since the message now clearly communicates the error, and the failing assertion or condition is being logged directly, I'm closing this ticket.
