### ISSUE TITLE
I can't get the access token

### ISSUE THREAD

**Issue by chenxizhang** [a85/POSTMan-Chrome-Extension#3784]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.16299 / x64
```

## Issue Report:
I am always can not get the access token for Microsoft Graph
![image](https://user-images.githubusercontent.com/1996954/32700802-2b028db6-c805-11e7-9d6e-10b9dd933b16.png)

and the error message is below
![image](https://user-images.githubusercontent.com/1996954/32700803-3090bdd4-c805-11e7-91fb-c2d3c90b8887.png)

**Comment by harryi3t** [comment]
@chenxizhang Since the error message is `The request body must contain .....` 
I would suggest you to once try changing the `Client Authentication`dropdown value to `Send client credentials in body`

![image](https://user-images.githubusercontent.com/5207331/32830582-a8bcda96-ca1b-11e7-8450-eb19e73bdb4f.png)
