### ISSUE TITLE
Visual problems

### ISSUE THREAD

**Issue by chimit** [a85/POSTMan-Chrome-Extension#3786]
## App Details:
```
Postman for Mac
Version 5.3.2
OS X 17.2.0 / x64
```

## Issue Report:
Some time ago my desktop Postman got visual problems:

![2017-11-13 10 32 01](https://user-images.githubusercontent.com/839349/32707370-564db6ae-c85e-11e7-877a-c02be3c69751.png)

Apparently, it's related to hardware acceleration, but I can't disable GPU in Postman.

**Comment by sdnts** [comment]
Hi @chimit, which version of macOS are you on? We've seen this resolve with a restart of the app, but we will investigate this.

**Comment by chimit** [comment]
macOS Sierra 10.13.1

**Comment by cae5ar** [comment]
I have the same problem after update and I can't disable gpu acceleration. Chrome, Visual Code, Atom and the other applications which use Electron Framework have alike artefacts when use gpu acceleration.
macOS Sierra 10.12

**Comment by cae5ar** [comment]
I have stared Postman via terminal `Postman.app/Contents/MacOS/Postman --disable-gpu`, but I couldn't find "gpu disable" item in the application preferences

**Comment by TheDauthi** [comment]
Chromium's GPU acceleration can also cause problems inside linux-based VMWare virtual machines, up to and including (though rarely, thankfully) causing the video driver to lock up if hardware acceleration is also enabled for the VM itself. The bug goes back at least to late 2015.

I'm not sure if you need to expose the --disable-gpu equivalent option somewhere, but you should be aware that there are cases where this problem is more severe than the graphical glitches shown.

**Comment by benoitolbrechts** [comment]
I also have the same issue with macOS HighSierra running as guestOS in parallels running on a host macOS.
The only way I have to make it work is to do as @cae5ar mentioned: `Postman.app/Contents/MacOS/Postman --disable-gpu` :(

**Comment by SamvelRaja** [comment]
Closing in-favor of https://github.com/postmanlabs/postman-app-support/issues/4594
