### ISSUE TITLE
Feature Request: Hiding resource

### ISSUE THREAD

**Issue by mits87** [a85/POSTMan-Chrome-Extension#3795]
## App Details:
```
Postman for Mac
Version 5.3.2
OS X 16.7.0 / x64
```

## Feature:
Hi, a few days ago I bought `Postman Pro`.
This is really great product but...

I created many resources in POSTMAN and I would like use API documentation feature but I can't, because all of my resources will be displayed on api doc page and I can't show all of my resources. 
What do you think to create "hide from doc" feature for resource and all directories?

Now I can't use 100% of your product from which I paid.

**Comment by SamvelRaja** [comment]
Thanks for bringing to our notice.
At present, I would recommend you to create a separate collection out the one you need to publish the documentation. In the meantime, we shall think of the solution for the above use case/ scenario

**Comment by mits87** [comment]
Thank you for your response. 
Now I can't create a separate collection because is too big.
I'd appreciate it if you add the feature.

**Comment by Michalfsn** [comment]
This functionality is crucial for my company and is keeping us from moving our documentation to postman service. 

It's no option for us to create two different "folders" that will keep public/private requests.

It would be good thing to be able to set scope in request/folder context to be able to show only "public" scoped ones in the public documentation, but keep "private" in documentation dedicated for the developers.

Cheers!

**Comment by pawlox** [comment]
Is there any update on that? Can we expect some feature to cover above use case? It would be nice to have it.

**Comment by headwinds** [comment]
We'd also like this feature. For now, I right-clicked and duplicated the entire collection, renamed it API Public and simply removed the end points I didn't want to make public. It was super easy once I knew what to do. Then our developers can keep working in the private version and I can manage the public release version. 

Still I think I would like both options to really protect experimental & insecure end points and be able to mark them private to prevent them from being accidentally published.

**Comment by vkaegis** [comment]
Hey guys, you can now fork collections and merge changes back between them (as of v6.7.1). 

What this means in the context of this particular use case is that you can now maintain the collection which has published documentation as a fork of your main collection, and pull changes from the master as and when required. Or you can create your own workflows around this.

Closing this issue for now, feel free to open another if you have any feedback on this implementation.

**Comment by phcoliveira** [comment]
@vkaegis, while I appreciate having version control on Postman, I would like to point out that it is not as straightforward as using GIT.

Pulling changes from origin seems to be some sort of accident which is recommended to comply, rather than actively choosing to pull.

You see, this can not be seen as having a master and a develop branch, because public branch (develop) is not supposed to be merged into origin (master), but quite the opposite: the public branch should pull from the origin.

This might not sound like a big deal, but consider this. Have some requests deleted on the public branch, then have some changes on other requests from origin. Before merging, Postman tell us about the recent changes on origin and advises to pull them. Not as straightforward, but it gets the job done.

Now, have some changes on the same requests which were deleted on the public branch. This time, Postman will not try to pull the changes from origin, but rather resolve the conflicts in order to merge de public branch into the origin, which is not what we want.

If we could have a dedicated button for "pull from origin", we could always get the job done, but, still, how difficult it would be to have an extra boolean property for rendering on the published docs? This should be so much easier than to implement version control management.

**Comment by sankalp0o** [comment]
@phcoliveira thanks for the detailed explanation! Version control management is definitely difficult to implement than a simple boolean property but it allows for a much greater flexibility in what you want to show/omit or change for public view. Your rationale about an explicit "pull from origin" action sounds good and we will definitely consider this.

**Comment by phcoliveira** [comment]
@sankalp0o, thank you for your readiness, but let me comment on your business rather than on your software.

Hiding requests or entire folders on the published docs is a feature that has been requested for a long time, and yet you keep saying that it will be considered or something better is yet to come.

Having version control management to filter what should or should not be displayed to the public is far from ideal because it is not the right tool for the job. Again, we, paying consumers, are telling you this, and your response to our needs is something like "no, you actually don't want that, I have something better for you".

The reason I picked Postman over Insomnia is its publishing capabilities, but I already regret paying for a full year upfront rather than monthly.

For some reason, Postman fails to acknowledge the differences between developing, consuming, documenting and releasing an API. Please have a look on this issue I wrote and, until now, was completely ignored by the core team.

https://github.com/postmanlabs/postman-docs/issues/1470
