### ISSUE TITLE
Lost the "Get new access token" settings for OAuth2 after upgrading to v5.3.2

### ISSUE THREAD

**Issue by butlnor** [a85/POSTMan-Chrome-Extension#3842]
## App Details:
```
Version 5.3.2
win32 6.1.7601 / x64
```

## Issue Report:
I resisted the updating for a long time, but now I accidentally clicked to update. So now I have lost my settings in the "Get new access token" dialog for OAuth2. 
This is not cool! I had troubles finding those values in the first place, and now I will have to find them again!

Why are those settings not preserved during the version upgrade? Like the other things (requests, ...) which are preserved.

**Comment by butlnor** [comment]
Btw, I don't remember, which version of Postman I used before. Is it possible to downgrade and get those settings back?

**Comment by butlnor** [comment]
Also, it's not cool for postman, to popup the "upgrade" dialog after I already wanted to make some request, I wanted to click some other button, but unfortunately just at the exact same time, the "upgrade" button displayed in the same place, so I mistakenly clicked it...

**Comment by kamalaknn** [comment]
Hi @butlnor,

Sorry that you lost your data in the OAuth 2.0 settings. This happened because we changed the internal storage format of the OAuth 2.0 settings in `5.3`. This is a one time change and any further update would preserve your settings in your OAuth 2.0 settings. Unfortunately, there is no option to get the saved data in the old version. 

For your update concern, you can open up the update section settings to configure Postman to silently download updates without bringing up the dialog.
