### ISSUE TITLE
Following the 5.4.0 update, there appear to be problems with setting tests as false.

### ISSUE THREAD

**Issue by VictorHarris** [a85/POSTMan-Chrome-Extension#3888]
Postman for Windows
Version 5.4.0
win32 10.0.15063 / x64

Following an update to 5.4, there is a change in the behaviour of tests. 

I would have expected that setting tests["criteria"]=true will pass and tests["criteria"]=false will fail.

What I see is that the false state registers as a FAIL but the summary (in the tab) shows it as a pass. Also, the FAIL description claims that there is an an AssertionError: expected false to be truthy.

I have include an example of this in the attached screenshot.

![postman issue screenshot](https://user-images.githubusercontent.com/26603230/33478412-187f1b16-d681-11e7-8a0a-ac538504baba.png)

**Comment by kamalaknn** [comment]
@VictorHarris  thanks for reporting this.

The test failure count on the Tests tab should be `(1/2)`. We'll get a patch out with a fix for this.

The `AssertionError: expected false to be truthy` is just additional information we have added to help you debug your assertions.

**Comment by AndriiStepura** [comment]
Same problem, "You are up to date! Postman v5.4.0-canary04 is the latest version."

**Comment by kamalaknn** [comment]
Hey @VictorHarris  @AndriiStepura 

We've rolled out a fix for this in our Canary channel. You can find the download link here - https://www.getpostman.com/canary

Could you try out the Canary build and let us know if this is fixed?

**Comment by AndriiStepura** [comment]
@kamalaknn hi, I update to Postman v5.4.1-canary02. but issue not resolved:
![image](https://user-images.githubusercontent.com/30338636/33538613-aeceb750-d8c2-11e7-89b8-be72b8b3ac73.png)

**Comment by VictorHarris** [comment]
I concur with @AndriiStepura. I have the following version installed now...

Postman for Windows
Version 5.4.1-canary02
win32 10.0.15063 / x64

And I see the following results...

![image](https://user-images.githubusercontent.com/26603230/33544983-b1b4184a-d8d4-11e7-8bac-39506fb0b6a2.png)

**Comment by SamvelRaja** [comment]
The fix had been released in PostmanCanary-5.4.1-canary03 version. I would request you guys to update the app to the latest and test it out.

**Comment by AndriiStepura** [comment]
@SamvelRaja, hi, with PostmanCanary-5.4.1-canary03 version works fine.

**Comment by VictorHarris** [comment]
@SamvelRaja, I also have been able to test this and it is working fine. Many Thanks.

**Comment by efrenette11** [comment]
I've tested this on MAC with version Version 5.6.0-canary01 (5.6.0-canary01) and those always failed. How can I solve this issue ? how could I update to canary03 ?

**Comment by TheCoderGuyVlad** [comment]
Hi @kamalaknn, can you please remove the "AssertionError: expected false to be truthy" feature. Instead of helping to debug, it makes our clean outputs messy and hard to read.

It doesn't really help debugging but only hurts it.

Thank you for understanding! :)

**Comment by gregarrayent** [comment]
I am seeing the problem in v6.0.10 -- anyone else?

**Comment by TheCoderGuyVlad** [comment]
Hi Postman team, could you please add an option to disable printing assertions to Dev Tools? Logging the assertions makes our Dev Tools output very illegible. All the effort we put into adding clear human-readable logging to our collections gets entirely wiped out by this.

Take for example this snippet (which is borderline unreadable, but representative of a typical use case)
`Assertion Skipping gateway test because URL is invalid failed: expected false to be truthy`

In really all we're trying to say here is:
`Skipping gateway test because URL is invalid`

The extra text completely changes the meeting and makes it very hard to figure out what the message is actually saying.

Furthermore, there's really no point to add the "expected false to be truthy" part at the end. It adds no value to the user. On the one hand, it doesn't make semantic sense, and on the other, it's redundant since you're already saying "Assertion ... failed".

**Comment by kamalaknn** [comment]
Hye @TheCoderGuyVlad 

I can understand the global `tests` object is not very configurable. For that very reason we have introduced a newer API for writing tests in Postman - the `pm.*` API. Here's a full documentation of the API - https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference

The newer API allows better control over messaging, skipping and much more. I hope that helps you.

Thanks

**Comment by kamalaknn** [comment]
I've closed this issue because the original issue reported with the count mismatch has been fixed.

You can continue any discussion on our [community forum](https://community.getpostman.com/) for better solutions from our user community. 

If the new `pm.*` APIs are insufficient please create a new feature request issue so we can better track it.

**Comment by TheCoderGuyVlad** [comment]
The new pm.* apis look promising, Thank you!

**Comment by 1989JmTan** [comment]
@kamalaknn  I  aslo met the same problem！
Postman for Windows
Version 6.7.4
win64

![image](https://user-images.githubusercontent.com/39816275/54737055-14352080-4be9-11e9-9b98-7962e03ef18a.png)
