### ISSUE TITLE
Poor performance when editing or deleting collections or folders

### ISSUE THREAD

**Issue by polydoreplasden** [a85/POSTMan-Chrome-Extension#3915]
## App Details:

```
Postman helps you develop APIs faster
Postman for Windows
Version 5.4.1
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
This bug has been present for several months
 2. Expected behaviour:
Expect copying or deletions of folders/collections to be done in a timely manner
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

When deleting or copying collections Postman often hangs for several minutes during which nothing else can be done. Checking Task manager I can see CPU at >25% and Physical Memory> 75%
![image](https://user-images.githubusercontent.com/33625396/33658835-fd0543bc-da75-11e7-9903-64ad1b1cdae3.png)
![image](https://user-images.githubusercontent.com/33625396/33658879-296be708-da76-11e7-8ce4-9fe18bbef0c9.png)

**Comment by sdnts** [comment]
@polydoreplasden Thanks for reporting this. How many collections, folders and environments do you have?

**Comment by polydoreplasden** [comment]
Hi @madebysid I have around 19 environments, 95 collections and >500 folders. However a colleague who has the same issue has reduced the number of collections to around 15 with 150 folders with some improvement in performance. Thanks for looking at this - it's having a real impact on productivity!
Note: we see the same issue when we Import collections.

**Comment by nchaluse** [comment]
Hello, I have somehow the same issue, it's becoming tough to move folders and request from one folder to another or from one collection to another. I have 10 collections and more than 1700 requests.

BTW, it also takes ages for synchronization... Maybe it's all because of synchronization, because once disabled, it's way better...

Might be related to [#2949](https://github.com/postmanlabs/postman-app-support/issues/2949)

![2018-02-07 14_55_36-gestionnaire des taches de windows](https://user-images.githubusercontent.com/26596660/35920116-42d3596a-0c17-11e8-9cde-e965b5141c3d.png)
