### ISSUE TITLE
pm.sendRequest to return promise instead of pm object

### ISSUE THREAD

**Issue by skyboyer** [a85/POSTMan-Chrome-Extension#3927]
Currently pm.sendRequest returns pm object itself(btw it is not described into documentation - 'sendRequest' is described as 'pm.sendRequest:Function' and that's it).

So far it allows us to write 
`pm.sendRequest(firstUrl).sendRequest(anotherUrl)`.
This way requests will be sent in parallel. 

But it does not make a lot of sense:
1. in comparison with two separated lines it does not save time(`pm.` is really small difference in texting)
2. chaining itself is not handful since there is just single method on `pm` object
3. making nested calls would be a pain(besides I agree it's bad thing in general)

If `.sendRequest` returned Promise as standard `fetch()` does it would be much flexible without loosing anything.

**Comment by thecuriousdev** [comment]
@skyboyer thanks for reaching out! Since postman core is used in multiple platforms (Postman app, Newman, Monitors) we cannot use JavaScript promises at this point. So for now we have to stick with callbacks. Once node v4 support is completely dropped we'll consider moving to promises.

https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference
