### ISSUE TITLE
Duplicate a folder generates the Requests twice under the duplicated folder

### ISSUE THREAD

**Issue by hujunhaorobert** [a85/POSTMan-Chrome-Extension#3934]
## App Details:

```
Postman app for Windows
Version 5.4.1
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: recently found this error
 2. Expected behaviour: Should only duplicate 1 time of the Requests under the newly created folder
 3. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/10079887/33766891-a4ea082a-dc73-11e7-9f81-a4ecd07d0662.png)

**Comment by hujunhaorobert** [comment]
Just updated to latest POSTMAN desktop app version V5.5.0 (11/12/2017), the issue is still there and reproducible.

**Comment by kamalaknn** [comment]
@hujunhaorobert Thanks for reporting the issue. We'll look into this.

**Comment by gototester** [comment]
Hi,

I'm seeing the same issue as @hujunhaorobert while duplication folders as shown in the example above. 

Currently I'm using the latest windows version 5.5.0. (win32 10.0.16299 / x64)

Is this a sync Issue?

**Comment by gototester** [comment]
I just logged out of the postman and imported the same collection locally and duplicated folder and I works as expected. When I signed back into postman and all my data was in sync I duplicated the same folder and all requests were duplicated.

This seems to be a sync issue, because when it first duplicated the folder it was fine and then a few seconds later the dupes appeared.

![image](https://user-images.githubusercontent.com/31238264/34517867-b80ec002-f074-11e7-96f0-88944f0b0d94.png)

**Comment by realpratiknikam** [comment]
Any update on this? Having exact same issue @kamalaknn

**Comment by kamalaknn** [comment]
@pratiknikam  We're working on a major revamp of our data structures. Issues like this should be fixed in the next couple of releases.

**Comment by realpratiknikam** [comment]
Thanks for update @kamalaknn . Any timeline for upcoming release?

**Comment by gototester** [comment]
@pratiknikam Good news,  Looking forward to the fix.

**Comment by DiegoRBaquero** [comment]
Any update on this? Is super annoying.

**Comment by prashantagarwal** [comment]
@DiegoRBaquero What is your app version ?

**Comment by prashantagarwal** [comment]
@DiegoRBaquero This fixed in latest version of Postman native app.
