### ISSUE TITLE
Can't read tab descriptions when more than a few are open

### ISSUE THREAD

**Issue by sixeyes** [a85/POSTMan-Chrome-Extension#3939]
Can the tab position be changed from Top (as it is currently) to Left (appear next to History / Collections)?

Once you open a few tabs it's impossible to read the descriptions, even on a large monitor.

If they could be placed down the left hand side (next to History / Collections), all the tabs would be readable, even if 20+ were open.

Alternatively can tooltips be enabled, so that hovering over a tab would show its description?

**Comment by vkaegis** [comment]
@sixeyes We haven't yet explored a vertical arrangement for tabs yet, and we're pretty cautious about changing the main interface since a lot of our users have expressed concerns about the limited real estate. It's definitely a great idea though, and going forward we'll be looking at how users can customize the interface to their own needs.

For now, we're gonna be adding tooltips for all truncated tab names. No ETA just yet, but stay tuned for updates!

**Comment by chris-torruella** [comment]
Hey everyone, after some time I bring you exciting news! ⭐
We've just introduced **Tab Search**, a new step in our journey to improve tabs UX and management at Postman. Now, you can easily read the entire name of all your opened tabs, regardless of their number.

**What's New:**
1. Dropdown display with all of your tabs.
2. Recently closed section for easy recovery.
3. Search bar for quick tab access.
4. Moved "Close all tabs" options to right-click tab menu to gain more tab bar space.

On the other hand @sixeyes, tooltips have been already present on tab hover for quite some time now. Hope this helped you!

![demo](https://github.com/postmanlabs/postman-app-support/assets/120389184/1c4e980c-01cf-42b2-aa97-78e82f48fa72)

Give it a try and let us know what you think. Your feedback is key to help us taking Postman to the next level! 🚀
