### ISSUE TITLE
Pass data to POST request from JSON file 

### ISSUE THREAD

**Issue by AlexanderTunick** [a85/POSTMan-Chrome-Extension#3945]
Hi! Briefly.
I have **POST** request. (here is url.)

In body:
Key: **targetingCriteriaId** ( I pass only one number, but i want to pass 1 out of 4 number ( 1 || 2 || 3 || 4) randomly.

I created json file:
```
[
    {
        "targetingCriteriaId": "1"
    },
    {
        "targetingCriteriaId": "2"
    },
    {
        "targetingCriteriaId": "3"
    },
    {
        "targetingCriteriaId": "4"
    }
]
```
and want to pass one of these numbers to Value of **targetingCriteriaId**

How to do that or maybe exists an easier way to do something like that, I'm aware that possibly it is "amateur" question but I need a tip to resolve it.

Thanks in advance.

**Comment by Faz540** [comment]
Hi, if these values are always the same - so if it's always 1 - 4 then I would just write Javascript in the pre-request script to randomly select 1 - 4.

Example:
In the 'Pre-request Script' tab in Postman I'd write the following Javascript:
```
pm.environment.set("randomNumber", _.random(0, 5));
```
This is creating an environment variable called 'randomNumber' and it's using the random function from Lodash to select a number between 0 and 5.

https://lodash.com/docs/3.10.1#random

Since this function is performed BEFORE the request is made we can have this in the POST body using double curly bracers.
```
{
   "name": "Paul",
   "age": 28,
   "id": {{randomNumber}}
}
```

This will post a random number in the ID field everytime the request is made.

Hope this helps?

Consider joing the Postman community forum:
https://community.getpostman.com/

**Comment by sdnts** [comment]
Hi @Alextunchii, what @Faz540 said should work perfectly. I'm closing this for now, but if his suggestion does not work in your case, please reopen so we can take another look.

**Comment by AlexanderTunick** [comment]
@Faz540 Thanks for your response and suggestion, it looks more convenient to use and more logical. 
But I would like to point out something:
Initially, I tried to use your code sample, but it didn't work, then I just replaced it with:

`postman.setEnvironmentVariable("randomNumber", _.random(1, 4));`
and then it started working fine.
I understand that the point is the same and thank you one more time for help, but if somebody has the same obstacle thus he will be aware

@madebysid thanks!
