### ISSUE TITLE
Client certificate authentication not working

### ISSUE THREAD

**Issue by saurav28** [a85/POSTMan-Chrome-Extension#3946]
i am trying to simulate client certificate based authentication for my APIs in postman.

https://www.getpostman.com/docs/postman/sending_api_requests/certificates

I have followed this document and was able to send the certificate (as shown in postman console).

In server side i look for ssl_client_cert header name to check if it is a certificate based authentication (as i have other modes of authentication too).

But it seems the header is not being sent by postman.

Is there anything else i need to activate in postman. What is hitting me is that i have kept the authorization mode in postman as no auth. I don't find any cert auth mode to select. Am i missing anything.

Version used 5.4.0

best Regards,

Saurav

**Comment by sdnts** [comment]
Hi @saurav28 while this may be obvious, are you sending your request to an HTTPS endpoint? @kamalaknn @harryi3t Can you guys take a look at this please?

**Comment by saurav28** [comment]
@madebysid thanks for the response...yes i am sending against an HTTPS endpoint...any update on the issue meanwhile ?

**Comment by harryi3t** [comment]
@saurav28 you mean __HTTPS__ right, not __HTTP__?
Also, we do not set the certificate related headers. The way certificates are used in these scenarios is that it is set in the TLS socket and is used during the TLS handshake.

Are you using any proxy (Apache, Nginx, etc) in front of your server? If yes, I think it's usually the job of the proxy to set the header that you are looking for. Can you make sure that your proxy is working correctly?
If you don't use a proxy, your assumption is wrong. You should be looking at the TLS socket instead of the HTTP request.

**Comment by saurav28** [comment]
@harryi3t ..thanks for the response...i don't have any proxy in front of our server..
same certificate when i am sending through Java's  javax.net.ssl.HttpsURLConnection in my java program is working fine..

**Comment by codenirvana** [comment]
@saurav28 `ssl_client_cert` header is added via Tomcat.
Refer: https://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/valves/SSLValve.html
