### ISSUE TITLE
Collection Runner does not show assertion error details when a test fails.

### ISSUE THREAD

**Issue by mgroeneweg** [a85/POSTMan-Chrome-Extension#3960]
## App Details:
Postman for Windows
Version 5.5.0
win32 10.0.16299 / x64

## Issue Report:
I pass a descriptive string to pm.expect so I have detailed information in the assertion error.
When I run a separate request from Postman, the test result shows the assertion errors:
FAIL Check response data | AssertionError: **reservationFeePP not found in class**: expected undefined to exist

When I run from Collection Runner, I see only that Check response data failed.

Getting the assertion error details in the result is really necessary to interpret the error. Now I need to take the request body, paste in in a separate request with the test script included and run that to get the assertion error details.

Please add the assertion details to the failed step info in Collection Runner.

**Comment by numaanashraf** [comment]
@mgroeneweg Thanks for reporting this.

**Comment by azharmdk** [comment]
Any update on this? It has been very difficult to identify errors especially when you are using test data from a data file.

**Comment by alexandraburnete** [comment]
+1 for this to be implemented

**Comment by ghost** [comment]
+1

**Comment by donbarthel** [comment]
+1

I'm running Postman-linux-x64-6.0.10.tar.gz (v1.6.16).

Running a separate request from the GUI doesn't show the pm.test() name, just the Chai assertion failure.

Test Results tab: "There was an error in evaluating the test script:  AssertionError: expected true to be false"

Postman Console: "AssertionError | expected true to be false"

**Comment by donbarthel** [comment]
Suggested workaround until this issue is addressed: use the second parameter to .expect() which is a "custom error message to show when the assertion fails".

This old code:
`pm.test('Name is a minimum of 3 characters', pm.expect(name).to.have.lengthOf.above(2));`
...fails with cryptic error message "AssertionError: expected 'NA' to have a length above 2 but got 2".

This new code:
`td = 'Name is a minimum of 3 characters';`
`pm.test(td, pm.expect(name, 'FAILED:['+td+']').to.have.lengthOf.above(2));`
...fails with "AssertionError: FAILED:[Name is a minimum of 3 characters]: expected 'NA' to have a length above 2 but got 2".

The failure is much more descriptive now. Does this not (temporarily) solve the issue?

**Comment by azharmdk** [comment]
yes, but I think the thread here is for the case in collection runner which does NOT give any information on the failed test case. It just gives information that the test is failed. Do we have a workaround for this to get some information on what caused the failure when running in collection runner? Thanks!

**Comment by simoami** [comment]
Any updates on this? This makes Collection Runner unusable to some degree. How are we supposed to know what failed when you have multiple assertions per test?

**Comment by numaanashraf** [comment]
@simoami We are working on this and would share an update here when this is available on our Canary channel.

**Comment by simoami** [comment]
Thanks @numaanashraf !

**Comment by numaanashraf** [comment]
This is fixed and released as part of Postman v6.6.0
