### ISSUE TITLE
Can't access console API

### ISSUE THREAD

**Issue by kghost** [a85/POSTMan-Chrome-Extension#3989]
## App Details:
```
Postman for Linux
Version 5.3.0
linux 4.13.0-1-amd64 / x64
```

## Issue Report:
Chrome Console API:
https://developers.google.com/web/tools/chrome-devtools/console/console-reference

Only console.log work, All others doesn't exist.
Error running scripts: TypeError | console.table is not a function

**Comment by sdnts** [comment]
Hi @kghost, this isn't supported by postman-runtime yet, but I'll add this as a feature request :)

**Comment by shamasis** [comment]
At the moment, console is intended to be a logging target and as such the functions by design only reflect the "severity level" of the log, such as console.log, .warn, .info, etc. Postman Chrome app was essentially powered by Chrome browser and as such inherited these console aspects, which are not scalable in more non visual use cases such as on CLI and Postman Monitors.

In the short to mid term, we don't plan to add visual layout level aspects to the console. But we could definitely add `.time` feature for getting additional debugability.
