### ISSUE TITLE
Sync issues when moving requests/folders inside collection

### ISSUE THREAD

**Issue by dennisslavid** [a85/POSTMan-Chrome-Extension#4005]
I get sync issues, sometimes resulting in disappearing requests, when moving around requests within the same collection.

When it occurs you get a popup saying the are syncing issues with the option to choose local or remote state to keep. I always choose local, as that is where I made the most recent changes.

It seems to occur most often when I try to move a request within the same folder to the first or last position in that folder.

App Details:
Postman for Windows
Version 5.5.0
win32 10.0.15063 / x64

 1. Did you encounter this recently, or has this bug always been there:
It's not the first time I have encountered this issue, it seems it has always been there (I have just started reorganizing some collections, causing a more regular interval of encountering this issue)
 
2. Expected behaviour:
The request should move to the indicated location without any nasty side-effects.

**Comment by prashantagarwal** [comment]
@dennisslavid Thanks for reporting this.

**Comment by jpSimkins** [comment]
I too am having some serious syncing issues. I have always noticed syncing issues with Postman.

My issues are: 
- Missing folders in a collection
- Missing requests 
- Collection name changes and new requests are missing

To give more insight, these issues happened when I had Postman opened on multiple devices. It seems syncing is not aware that one device should override the other device. For example, when adding requests to folders in a collection, I would create some folders and add some requests. Then when I go to my other computer a few hours later, the new endpoints and folders do not exist. 

I can see them on the website but not the app. Also, when I renamed a collection, it did not show updated on the website. When looking through the sessions on the website. Luckily, this did not break the app in the computer I made the changes, otherwise that would be a severe issue.

It seems that Postman is updating the Collections from the old version of the App. This is causing the issues I am experiencing. This is unexpected especially since the website even points out the Postman app was an older session. I can also see that the old version of the app updated the system due to the activity log.

To clarify, when you go back to a computer that has Postman opened but its outdated due to you updating it from another computer, Postman syncs the older content and seems to ignore the latest... This seems to be the whole problem for me. I would expect the syncing to be aware of the age of the App being opened and prevent the older app from syncing their content (considering it was deleted and moved around) over the most recent Postman client.

Hope this helps narrow down the issue.

**Comment by pww22** [comment]
I just had this issue occur myself:

1. Created a Folder in an existing collection
2. Dragged items into it
3. Received the sync error, I accepted all local changes
4. Folder disappeared, along with all requests

I can see the missing folder in the Web, and on a colleagues postman instance, when subscribing for the first time, the folder also appears there.

Resolved the issue by Signing Out and Signing In again

**Comment by jpSimkins** [comment]
Also noticing numerous duplicates... I have 6 duplicates of the same endpoint. I only added it once. This happens on numerous endpoints and the duplicate number varies

**Comment by serkand** [comment]
+1

Please fix, this is causing our CI jobs to fail as our collection in the postman cloud is getting corrupted !

**Comment by Iliev88** [comment]
+1

When requests are moved to a folder synching issues appears.

**Comment by vapomalov** [comment]
+1

**Comment by cjlotz** [comment]
+100

**Comment by rstander** [comment]
+200

**Comment by slhrkc** [comment]
+300

**Comment by kamalaknn** [comment]
Hi everyone,

We've pushed a lot of improvements to our data storage and sync layers in the latest version of the app. Could you update your app to the latest version and let us know if you're facing similar issues?

**Comment by dennisslavid** [comment]
@kamalaknn 

It seems the problem has been solved, haven't had any issues anymore in a while now.

Thanks for your intervention.
