### ISSUE TITLE
PUT method does not work.

### ISSUE THREAD

**Issue by akoSalman** [a85/POSTMan-Chrome-Extension#4012]
## App Details:

```
Postman for Windows
Version 5.4.1
win32 10.0.14393 / x64
```

## Issue Report:
When sending `PUT` request through POSTMAN to my `localhost` Laravel-5.4 project, everything works fine and i can catch data with `PUT` request in my project, But when sending same request to the api in the `Production ENV` , server catches the request as a `GET` request, and so i can not catch the data with the request.

**Comment by prashantagarwal** [comment]
@akoSalman I am not totally sure but my guess is your API is pointing to an endpoint which is redirecting this request to your actual server. In such scenario PUT request is being redirected as get. Can you verify once that the request that you are making is to the actual server and that it is not being redirected to that. Thanks.

**Comment by akoSalman** [comment]
@prashantagarwal Thank you for your response.
I don't know what you mean from another endpoint, but i make the `PUT` requests directly to where my API is located.
I think maybe `apache`  redirects (or converts) the `PUT` requests to a `GET` one.
I check it and report it here ASAP.

**Comment by prashantagarwal** [comment]
@akoSalman Were you able to figure that out. I don't think Postman is causing this issue. If you feel otherwise feel free to reopen this issue.

**Comment by daverickdunn** [comment]
I'm running v6.2.5 x64 on Windows and experiencing this exact issue.

I ran wireshark and it appears to be happening when the server redirects (301) from htttp to https. Postman is sending a PUT _initally_, but when it redirects it opens a new encrypted connection and I cannot see what method it sends thereafter. 

This does not happen with any other client, including SoapUI and the Postman Chrome App, so it _appears to be_ Postman that is changing the method after a redirect. I'd hazard a guess that this issue is specific to http to https redirects.
