### ISSUE TITLE
[macOS] Postman is always opened in fullscreen after split view last time

### ISSUE THREAD

**Issue by chimit** [a85/POSTMan-Chrome-Extension#4069]
## App Details:

```
Postman for Mac
Version 5.5.0
OS X 17.3.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: always
 2. Expected behaviour: Postman should not be opened in fullscreen
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

I always put Postman in [Split view](https://support.apple.com/en-us/HT204948) with Sequel Pro. Next time when I start my computer Sequel Pro is opened in a small window, but Postman is opened in fullscreen, so I should exit fullscreen for Postman first and make Split view after that. It's a little bit annoying to do it every day.

**Comment by sivcan** [comment]
@chimit - It's a behaviour that it remembers your last window config. 
Since one app is always needed in full-screen mode for the macOS to get another app into split mode with it, you can simply just swipe up on your mac and drag sequel pro to the postman fullscreen window.
Your apps will enter the Split View. It's something you'll naturally always do to get into split view. 
You wouldn't need to exit the fullscreen mode and then put both into Split View.
