### ISSUE TITLE
Windows: Shortcut with AltGr key work not correctly

### ISSUE THREAD

**Issue by GrzegorzPi** [a85/POSTMan-Chrome-Extension#4083]
I constantly invoke shortcut when i'm typing some utf-8 symbols like ć (AltGr + c).

### App Details:
Postman for Windows
Version 5.5.0
win32 10.0.16299 / x64

### Issue Report:
 1. Recently behaviour
 
 2. Reproduction: 100%

 3. Expected behaviour:
pressing 'AltGr + letter' key combination will not work as shortcut

### Scenario:
1) press Ctrl + Alt + C
2) Console window is open
3) close console window
4) press Ctrl + AltGr + C 
5) console window is open
6) close console window
7) press AltGr + C
8) console window is also open

### Same corrupted shortcut:
AltGr + E  == Ctrl + AltGr + E
AltGr + V  == Ctrl + AltGr + V
AltGr + W  == Ctrl + AltGr + W
AltGr + arrowup/down == Ctrl + AltGr + arrowup/down

**Comment by elDan3k** [comment]
same issue
Postman for Windows
Version 5.5.0
win32 6.1.7601 / x64

**Comment by thecuriousdev** [comment]
@GrzegorzPi thanks for reporting this issue, we'll look into this and keep you posted in the following thread, https://github.com/postmanlabs/postman-app-support/issues/2707

**Comment by Magador** [comment]
Postman v6.4.2
Windows 7 (6.1.7601) x64
`AltGr` + `e` triggers `Ctrl` + `Alt` + `e`, rendering impossible to type `é` with US-International keyboard.

Since many AltGr-modified keys are to type extra characters, an idea would be to trigger the shortcut only when no input field are focused, allowing to write those characters in these fields
