### ISSUE TITLE
Cannot create monitor, possibly because can't sync either

### ISSUE THREAD

**Issue by zoboomafoo57** [a85/POSTMan-Chrome-Extension#4100]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

Hey there I can't create monitor in Postman, when I submit a request to monitor a collection I'm getting "problem in creating the monitor" error without additional details. Using dev tools I can see the error returned i.e. 

{"error":{"name":"instanceNotFoundError","message":"Instance not found in the database.","details":{"model":"collection","model_id":"3579022-c92a571f-7422-64eb-58cd-858444d10ca4","owner":"3579021"}}}

I noticed that the Sync does not work either, it keeps saying "Syncing" but it's been hours now and I only have 1 request to sync. I'm not behind a corporate firewall so Socket connections should go through. I tried dev tools to troubleshoot sync here's what I see after I re-enable sync through preferences"

Request:
https://app.getpostman.com/api/sync-eula-accept?user_id=3579021&access_token=
Response: null

Request:
https://app.getpostman.com/api/users/3579022/organizations?user_id=3579021&access_token=
Response: 
{"organizations":[]}

Any idea how to fix the sync?

Thanks

**Comment by sdnts** [comment]
Hi @zoboomafoo57, can you head over to your [dashboard](https://app.getpostman.com), click on the user icon at the top > Profile and make sure all your collections are intact? You can do so by clicking on a collection's name, and verifying requests and folders in there. Since you say you have only one request, this should be easy to do.

If they are, you should be able to safely sign out + sign back in to restart the Sync process, which should resolve this issue.
Let me know if the request hasn't been synced at all, and I'll investigate further.

**Comment by zoboomafoo57** [comment]
Hi @madebysid, not sure exactly what happened here but after checking my profile online and starting postman afterwards, the sync miraculously started to work! I can now not only see my collection but also create a monitor. Note that I had tried to sign out and back in before w/o success. I had also tried to stop sync and restarting it

Thanks for your reply

**Comment by sivcan** [comment]
Kindly update to the latest Postman app - [Download Postman 6](https://www.getpostman.com/apps) and let us know if you're experiencing the same issue.
