### ISSUE TITLE
URL Segment parameters and documentation

### ISSUE THREAD

**Issue by sschocke** [a85/POSTMan-Chrome-Extension#4103]
## App Details:
Postman for Windows
Version 5.5.0
win32 10.0.17074 / x64

## Issue Report:
I noticed that URL segment parameters work perfectly in the app itself, with a section in the **Params** area to fill in the value and a description. And this has been in place since 2015 from the issues I found surrounding URL segment parameters. Thanks for that and awesome work.

My problem is that those parameters don't feature at all in the generated documentation. I found a blog post from June 2017 saying that this was still coming, but it's not working.

Example GET request: `{{server-url}}/api/user/:userID`
Gives a section under **Params**, filled in `Value` of _5_ and `Description` of _"Unique User ID"_

Generated documentation says:
> ### GET User by ID
> ```http://my.server.org/api/user/5```
> Get User details

No mention of the parameter in either the URL or the parameters list, but query parameters are shown if they are present. As our API uses URL segment parameters almost exclusively, the documentation doesn't really help much without this.

Has this still not been implemented, or am I doing something wrong?

**Comment by sdnts** [comment]
Hi @sschocke, Path variables like you're using are still not parsed by our documentation. These parameters are being deprecated in favor of environment variables, which offer the same functionality, and are more robust. Can you try using environment variables instead? These will also show up in the documentation correctly.

I'm closing this for now, but please reopen if I misunderstood :)

**Comment by nfearnley** [comment]
@madebysid, I'm having a similar issue. You mention using environmental variables instead. I assume you mean as follows:
https://myapi.com/getThing/{{thingId}}
In that case, where do I document the usage of {{thingId}}? There is no Description field available for it in the Params list, and in the Documenter output, it doesn't show up in the list of params.

**Comment by gagangupt16** [comment]
Hi @madebysid,
Not sure if environment variables are a good idea.
As the name suggests, it is a variable for the environment, not a request.

Also,
Assuming that I have 10 different API.
In an API, there are 5 entities which can be manipulated.

There would be 50 environment variables all at the same place, which would create confusion instead of clarifying it.

We should have request specific variable, which can be documented.

Let me know if I have misunderstood anything.

**Comment by gdfSheldon** [comment]
Following the comments here, I agree that an environment variable doesn't fix this. Having the params in the route instead of query string is common but I don't see that it's supported. And by creating an environment variable it simply replaces the value, but provides no documentation unless I'm not understand this correctly.

**Comment by ardevd** [comment]
I'm curious about this as well. The API documentation produced by Postman looks a bit iffy when you are unable to describe the environment variables.

**Comment by tkantonio76** [comment]
Any reason this topic is closed? Any solution for it yet?

**Comment by anuj9196** [comment]
Since there are thousands of open issues and this issue has been closed earlier. The team may not be looking at closed issues. It will be better to open a new issue.

BTW I checked it by adding `:id` in place of value in the URL and it got automatically converted to **Params**.
```
Ex: https://{{url}}user/:id/setting
```
Will generated `id` params where you can place the value to use and also the description.
