### ISSUE TITLE
Feature request for console

### ISSUE THREAD

**Issue by dbkaynor** [a85/POSTMan-Chrome-Extension#4111]
1. Add a command which can run from pre-request scripts to clear the window.
2. Add a tail like feature to keep newest data visible.
3. Add debug line numbers that reference the Body or test editor lines.

**Comment by sdnts** [comment]
Hi @dbkaynor, thanks for the feature requests! We'll take these into consideration!

**Comment by shamasis** [comment]
It's been a while since we got around to this. Nevertheless, we are rounding up aspects that can be built in short to mid term.

Tracking console clear here https://github.com/postmanlabs/postman-app-support/issues/4690 with initial thoughts in https://github.com/postmanlabs/postman-app-support/issues/4690#issuecomment-522313322

Debug line number request is tracked at: https://github.com/postmanlabs/postman-app-support/issues/3950

@dbkaynor can you expand on "Add a tail like feature to keep newest data visible." and create a new issue? We would love to understand your use case and correlate to the upcoming console improvements.

Closing this issue since it is broken down and independently being tracked over multiple places.
