### ISSUE TITLE
Must use double quotes in JSON data

### ISSUE THREAD

**Issue by CrisLi** [a85/POSTMan-Chrome-Extension#412]
When I send a request with JSON data. The data format must be like 
`{ "username" : "user", "password" : "secret" }`

When I change the data format to 
`{ 'username' : 'user', 'password' : 'secret' }`

it does not work. I get 400 error.

We must use double quotes in the JSON data.

**Comment by zomby22** [comment]
I also need an answer: when loading data from a database, this does not load correctly using the datatable (json). `<a href="sdfdsfdas">` because of the double quotes. I get invalid json when from data contains double quotes. Do I try to escape the double quotes in my ASP code or in the datatable jquery code? if so, How.

**Comment by exisz** [comment]
could we have a feature that allows *automatic* transformation from single quotes / no quotes to double?

**Comment by zomby22** [comment]
I cant remember why I post my previous comment, but double quotes works. In my case I am using adodb.command to write my columns with html and using the json array.

example: Select CASE WHEN dblang='e' THEN '<a href=""a

```
response.write("{""draw"":"& sEcho &",""recordsTotal"":"& rs(0) &",""recordsFiltered"":"& rs(0) &",""data"":")
response.write( server.HTMLEncode(trim(a.Flush)) )
response.write("}")
```
