### ISSUE TITLE
Show request names in History panel

### ISSUE THREAD

**Issue by andreypolyak** [a85/POSTMan-Chrome-Extension#4121]
## App Details:
```
Postman for Windows
Version 5.5.2
win32 6.1.7601 / x64
```

## Issue Report:
I use Postman mostly to send SOAP requests where all requests have one endpoint URL. This makes Histoty panel totally useless because it only shows endpoints of the requests and not their names.

Screenshot:
![image](https://user-images.githubusercontent.com/7446762/35475294-c7404992-03ac-11e8-8774-26d4bb28ebb7.png)

It would be nice to have both endpoint and request name.

**Comment by sdnts** [comment]
Hi @andreypolyak, history requests, since they aren't saved anywhere, do not have a name. For security purposes, we do not resolve the variables in history requests (to avoid accidental data leaks when using sensitive data).

What I'd recommend you do is use collections to organize your requests. You can then give them names. The request names will still not show up in the history, but if I understand correctly, you wouldn't have to depend on the history to find your requests.

I'm closing this, but please let me know if I misunderstood, and I'll reopen.
