### ISSUE TITLE
Run sequence in runner not maintained in monitor

### ISSUE THREAD

**Issue by zoboomafoo57** [a85/POSTMan-Chrome-Extension#4134]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: New issue
 2. Expected behaviour: I have a collection with 2 requests, the 2nd collection is depending on the first one. When I run the collection in runner the sequence is preserved, however if I run the same sequence in monitor the 2nd request always runs first (confirmed by console logs), which breaks my dependency. I've tried to redeploy the collection several times but no luck. I've also looked into using setNextRequest but since the 2nd request is always called first it does not help. Is there a way to set the very first sequence to run? Thanks for your insights

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hi @zoboomafoo57, this is super weird, since we use the same underlying library (postman-runtime) to run your collection in the app as well as on Monitors. This leads me to believe this might be a Sync issue. I think your app's order of requests has gone out of Sync with our server's order of requests. This is easy to verify.

Can you open your collection's documentation by clicking on the arrow icon on the right side of your collection, and then click on `View in web`? You should see the order your requests actually are on our servers. If it isn't the same as the app, signing out + signing back into the app should fix this.
<img width="1392" alt="screenshot 2018-02-20 12 53 11" src="https://user-images.githubusercontent.com/7689783/36411738-10876c8c-163d-11e8-8cfe-210bf8b4aed7.png">

Let me know if this doesn't solve your issue and I'll investigate further :)

As a side note, we've made major improvements to the way the app syncs so issues like these don't occur. These fixes will land on our stable channels soon. You can try this out on our Canary channel right now, though: https://www.getpostman.com/canary
