### ISSUE TITLE
postman's DNS not change immediately

### ISSUE THREAD

**Issue by DullCat-c** [a85/POSTMan-Chrome-Extension#4135]
First thanks for the team of postman ,  this is a very good tool , but why postman not like Curl and HTTPie change hosts's DNS immediately .This makes me very disturbing.

**Comment by numaanashraf** [comment]
@DullCat-c Thanks for reporting this. Could you provide us with steps you followed in cURL/HTTPie and Postman to better understand your use case?

**Comment by DullCat-c** [comment]
Please excuse my poor English.
First,i add a domain of local server to hosts file,then via postman send a request ,it  access to the local server.After that ,I commented out that record,send a request again ,it access to online server
.But,when i add that record again,it will always access to online server . It bothers me.Although HTTPie/cURL can do it ,but it much more trouble than postman.I like postman's convenience very much

**Comment by sdnts** [comment]
Hi @DullCat-c, does this only happen when you use the `hosts` file? If you directly use the server's URL, this does not happen, I assume. Can you check this out?

There are known issues around the `hosts` file, as reported in #2369. I'm closing this right now because the two issues are similar, but please let me know if they are not, and I will reopen :)
