### ISSUE TITLE
Feature Request: Display Request URL

### ISSUE THREAD

**Issue by fabianerni** [a85/POSTMan-Chrome-Extension#4153]
## App Details:
```
Postman for Windows
Version 5.5.2
win32 10.0.16299 / x64
```
**Feature**
Display the request URL with the response.

**Problem**
Normaly, you have the full request URL in the URL box of the request form. But we use environment variables for the hosts to switch between local, dev, test and production systems. So the URL input looks like this:

```
{{host_streaming_service}}/stream/23423434
```
The real URL called in the requeset is only available as tooltip when hovering over the variable.

**Request**
Display the full request URL on the response side again, so it's absolutely clear what URL was requested.

**Comment by David-A-Phillips** [comment]
I was just about to post a request similar to this as I would like to copy a fully realized url with variables to share with coworkers this approach would work aswell.

+1

**Comment by JamesMGreene** [comment]
:-1:

I just get them (and variable-based request bodies) out of the Postman Console.

**Comment by sdnts** [comment]
@fabianerni @earthmonkey0 Thanks for the suggestion. We don't resolve the full URL when listing endpoints in the history sidebar (or anywhere else) anymore for security reasons; this was removed to avoid accidental data leaking.

Have you taken a look at the environment preview button (eye icon) on the top right? It is a quick way to view the current state of the environment. For checking the complete URL (and other info about the request), I'd also recommend using the Postman Console (Cmd/Ctrl + Alt + C), because this was what the Console was built for :)

@earthmonkey0 For sharing requests with your teammates, how about sharing a collection (and environment) with them?

I'm closing this for now, but please feel free to let me know if I misunderstood, and I'll reopen.

**Comment by kinekt4** [comment]
I've only just discovered the console which does seem to resolve this issue.

But as is standard practice with devtools on most browsers, the request URL is displayed in the "Headers" tab just before any header information is displayed. Eg.

    Request URL: https://base-uri.com/stream/23423434
    Request method: GET
    Remote address: 192.168.128.1
    Status code: 200
    Version: HTTP/1.1
    
    ...
    Content-Type: application/json
    ...

I think it would be good to see it there too.
