### ISSUE TITLE
Call a collection level function from a request level test in postman

### ISSUE THREAD

**Issue by eloyucu** [a85/POSTMan-Chrome-Extension#4157]
In order to improve the tests, and its usability... is there anyway to call a function declared on the collection test/pre-request level from the request test/pre-request level??

I mean, I have (at the moment of post this issue) 10 folder and each of them 5-6 request. These requests are very similar between folders. This looks like:
```
Collection
    Folder_1
        request_1_1
        request_1_2
    Folder_2
        request_2_1
        request_2_2
```
Where the requests `request_X_1` use the same pre-requests and tests (the same happens for `request_X_2`, `request_X_3`, etc...).

The thing is that copy manually everytime that I make an update is a **madness**. I have seen this [issue](https://github.com/postmanlabs/postman-app-support/issues/2247) where @shamasis sais:

> There are two things we think we should do:
> 
> 1) Common scripts in folders
> 2) A global scripts section that can be referred from any folder or request.
> 
> These two combined should address script re use issue.

But I didn´t find **how to call a function from the request level to the collection level**.

Finally I found a solution BUT only works for the test (not for pre-request). The idea is set a variable in the pre-request of each request that indicates which request is running. And after use this variable to determinate which functions should run in the collection level test. Something like:

Pre-request of each request:
```javascript
pm.globals.set("testHelper", "request_1")
```
Collection level test:
```javascript
eval(pm.globals.get("testHelper")+"()")

function request_1(){
      //do_something
}

```
But, it doesn´t work for the pre-request.

**Comment by eloyucu** [comment]
Other thing I tried was (on the collection level):

```javascript
testHelper = {
    hello: function(){
        console.log("hello")
    }
}
console.log(testHelper);
pm.globals.set("testHelper", testHelper);
```
But this `console.log(testHelper);` shows an empty object.

**Comment by eloyucu** [comment]
Do you know what could be great for the testing???
The possibility of using external files:
```
resquest_1.js
resquest_2.js
etc...
```
and call to functions with something like `resquest_1.test()`.
It's just an idea.

**Comment by tmdude9586** [comment]
I would also really like something like this. It would be great to be able to either attach custom functions to the 'pm' instance, or just declare javascript funcs/variables in the "test" script section for a collection, and still have reference to them in the request's "test" script section, so that there can be reuse of common testing code.

For the time being I use global variables, and put a string version of my functions into global variables, and then eval them in the tests to get them usable.

**Comment by a85** [comment]
@shamasis We need to solve this generally in the runtime. Both with respect to re-usability within a collection and across collections.

**Comment by S-Tasker** [comment]
Is this possible within Postman/Newman yet? We would love to define simple functions we can use throughout our tests.
For example, we always want to check we match a specific date/time format, it would be great to call a function "isValidDateFormat(string)" rather than copy/pasting into every test the same boilerplate each time.

**Comment by BrambleRamble** [comment]
@S-Tasker For tests, I follow the pattern shown in this sample collection: https://documenter.getpostman.com/view/33232/RWaNPmBa?version=latest
It's the same pattern that's mentioned briefly at the bottom of this issue's description, and from what's said there, I wouldn't expect it to work for pre-request scripts, only tests.
It's a clumsy and fragile solution, and it's not a replacement for functions being properly supported, but it's better than copying/pasting tests everywhere IMO.

**Comment by adamkerz** [comment]
It is unbelievable that functions or scripts are not supported!

I have worked around it by adding an object to `pm`. In collection level tests:
```
postman.setGlobalVariable("adamPm", () => {
    pm.adam=function(t){console.log(t);};
});
```

Then, in a test's script:
```
eval(globals.adamPm)();
pm.adam("foo");
```

I haven't tried this for pre-requests, it's the same general principal as @eloyucu said didn't work for him, so it probably won't work.

**Comment by vicker** [comment]
Support this feature request.

There are often times that we organise our requests by folders in a way just to minimise the repetition of test scripts, instead of the structure of the actual request.

e.g.

Module A
- Valid req.
- 401 req.

Module B
- Valid req.
- 401 req.

To avoid repeating test scripts for 401 calls, we have to create a separate folder. It works, but it kind of breaking the original structure as follows.

Module A
- Valid req.

Module B
- Valid req.

401 folder
- 401 req. (Module A)
- 401 req. (Module B)

**Comment by molteninjabob** [comment]
Disappointing to see that almost 3 years later, this still is not supported.

**Comment by adamkerz** [comment]
I gave up on Postman and use python tests instead. At least you can write reusable code and tests are easy to understand, even if the UX experience is different.

**Comment by florianpasquereau** [comment]
Still not supporting ?

Regarding the amount of comments, it's can be a good feature I guess  ....

**Comment by tainmar** [comment]
Too bad this is still unsupported.. 😢

**Comment by postfrzero** [comment]
Hey folks -- Postman v11 rolled out a few weeks ago with support for the new Package Library, which enables you to reuse code by creating and requiring packages within your scripts. Learn more about the Package Library [here](https://blog.postman.com/postman-v11-plans-packaging-updates-2024/#what-is-the-package-library-for-reusable-scripts) or [here](https://learning.postman.com/docs/tests-and-scripts/write-scripts/package-library/).

**Comment by vanipatel91** [comment]
@postfrzero Is it possible to access Package Library with Newman? I guess this is available only with Postman app or Postman CLI.

**Comment by postfrzero** [comment]
That's correct -- `newman` doesn't support Packages. Postman CLI, the Postman App, Monitors, Scheduled Runs, and other means of execution requests/collections all support Packages.
