### ISSUE TITLE
Automatic url encoding

### ISSUE THREAD

**Issue by shtrip** [a85/POSTMan-Chrome-Extension#4171]
## App Details:
```
Postman for Windows
Version 5.5.2
win32 10.0.15063 / x64
```
## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **Always been there**
 2. Expected behaviour: I expect Postman to send the request I am asking it to send.

In Postman I do a GET to http://foo.com?x={123}
Postman actually sends a GET to http://foo.com/?id=%7B123%7D
Postman console shows http://foo.com?x={123}

I understand some people want automatic url encoding but there are times when you have to investigate issues that depend on Postman sending the url without modifying it. Right now I'm dealing with such an issue and I can't use Postman. In my opinion it should be possible to disable automatic url encoding through a setting or button.

**Comment by thecuriousdev** [comment]
@shtrip thanks for reporting this, we'll keep you posted here.

**Comment by terrypacker** [comment]
I have just run into this issue and can no longer use Postman to test our REST api.  Being able to optionally disable the auto-encoding would fix this.

**Comment by DeyLak** [comment]
Same problem leaded me here. In my case, we are using rql queries in our requests, and the server does not accept encoded bracket symbols. Would be nice to have this opportunity to disable auto-encoding.

**Comment by jonathanhuet** [comment]
Me too using RQL, it takes the RQL sentence as the name of the GET property and then re-take the RQL sentence as the value of the GET parameter urlenconding it.
Example:

_Expected_
`https://foo.bar/resources?eq(a,2)`

_Result_
`https://foo.bar/resources?eq(a,2)=&eq%28a,2%29=`

_How to reproduce:_
Just put `https://foo.bar/resources?eq(a,2)`  in the URL part of the UI

**Comment by SeaDude** [comment]
Would love a way to view the FULL CONCATENATED URL that PostMan is sending. I can't seem to find it anywhere in the app. 

I'm NOT looking for a view that shows base URL with a list of key:value pairs below. I AM looking for the full concatenated URL. 

Am I missing it somewhere in the app?

Thanks

**Comment by AuriR** [comment]
Will this be fixed anytime soon? It seems like an obvious setting feature to me.

**Comment by AuriR** [comment]
Important: This is NOT an issue in the Chrome app. Only the desktop app appears to have this issue.

**Comment by tylerpalmerdev** [comment]
+1, this makes the desktop app virtually unusable for our use case. There are various scenarios where we need certain characters to _not_ be encoded in the URL. Agree this could be a simple setting flag, e.g. "Do not auto-encode requests" .

Is there a workaround for this in the desktop app until the Postman team offers it as a setting?

**Comment by tylerpalmerdev** [comment]
Chrome apps are deprecated so using it in lieu of the desktop app is not a viable solution.

**Comment by allicanseenow** [comment]
Has this been fixed? It seems I can still meet this bug now and then

**Comment by filipkratochvil** [comment]
Guys, please fix it...

**Comment by AuriR** [comment]
Can you just open source it and I'll fix it? :)

**Comment by numerical25** [comment]
Same Issue. Great Program. But Postman is encapable of testing JSON:API specification. Something like this... 

`filter=(:or,(:and,(events.end_date,:gte,1549745450224),(events.start_date,:lte,1549745450224)))`

Turns into this...

`filter=%28:or,%28:and,%28events.end_date,:gte,1549745450224%29,%28events.start_date,:lte,1549745450224%29%29%29`

I am using Postman Version 6.7.3 (6.7.3) for Mac

**Comment by mamraz** [comment]
I must be missing something.  I have the exact opposite problem from what is being described here.  I am looking to have it auto-encode the URL, but it does not.  When I send http://foo.bar/abc?param[0]=1, this is precisely what gets sent according to the Postman console, and this results in a 400 error because the "[" and "]" were not encoded.  If I encode them myself, the call works.

Furthermore, the page https://learning.getpostman.com/docs/postman/sending_api_requests/requests/ has the statement, "Note: Parameters you enter in the URL bar or in the data editor will not automatically be URL-encoded. Right click a piece of selected text, and select "EncodeURIComponent" to manually encode the parameter value."  This confirms the behavior I am seeing but contradicts what is being stated here.

In any case, I do agree that, no matter which way it is currently working, a setting should be added so that either behavior is possible.

**Comment by andreacab** [comment]
Same problem here, is anyone aware of a fix?

**Comment by srikanthonl** [comment]
Any update on this please? Any workaround please? Anyone? Im using version 7. And its been more than an year since people have been asking this basic requirement.

**Comment by vkaegis** [comment]
No updates or an ETA just yet. We are assessing some possible configurations to be introduced, will be taking this up then.

**Comment by DodecaDev-LLC** [comment]
This is the biggest thing holding me back on the desktop client. Up until recently I have gotten around it using the chrome plugin but that now won't sync with my desktop environment. It's a hassle. This absolutely needs to be fixed soon.

**Comment by AuriR** [comment]
I don’t think they care anymore. At least, it sure feels that way for as long as this has been out there. Or maybe this issue is too old?

---
“Never confuse motion with action.” -Ben Franklin
Blog: https://auri.net<http://www.auri.net> / Twitter: @Auri

________________________________

**Comment by shamasis** [comment]
If this thread is followed, one would notice that, even with best efforts from the standardisation systems as a whole, there is no one correct way of encoding URLs. Postman has been encoding URLs to match Chrome and over the years even Chrome has tweaked its encoding logic and we now see deviations. The catch-22 here is that any change to the logic (even if that were to match Chrome), would start breaking existing collections for a considerable chunk of users.

There are three to four variants of encoding which apply on different parts of URL - such as query, domain, path and headers. On top of it, there are different ways to handle extended character sets in each of these URI components. We are trying to work a UX that retains the simplicity of current behaviour and also allow to configure these at individual request / collection / app level. 

Our next release will come out with some internal changes that fixes encoding issues for authentication helpers, followed by these configurations in near to mid term.

**Comment by AuriR** [comment]
Thanks, @shamasis. I think people will feel better knowing there's a reply and a reason :) Is there any way we can help as a community? I'm guessing Postman isn't going open source, although I imagine we'd love to contribute if it did.

**Comment by AuriR** [comment]
@shamasis To be fair, the original issue with this task is more of a bugfix + feature request. The way I see it, it's not a complex question of choosing only one encoding technique - it's providing an option for how the encoding is handled.

**Comment by nirajgup** [comment]
+1 for this feature

**Comment by umbrella-yaroslav-graboveckiy** [comment]
Why not add something like this? 
https://d.pr/free/i/T3o5y4
With false (unchecked) state by default

**Comment by xaviergm** [comment]
+1
Just stumbled onto this issue.
Our API management platform does not encode the URLs to the backend while Postman does. This was leading to strange test results when a direct call to the backend would fail while calling through our API Manager would work.
In our case the URL seems to be encoded by Postman only when we use http requests.
When using https, everything works fine. 
It would be good to be able to see in the Postman Console the actual URL that Postman is sending and be able to disable URL encoding by means of an option in the Settings.

**Comment by AuriR** [comment]
Have you tried right-clicking the parameter fields? There are features “hidden in plain sight” that control encoding… I learned about this at our Indy .NET Consoritum meetup a couple months ago :)

---
“Never confuse motion with action.” -Ben Franklin
Blog: https://auri.net<http://www.auri.net> / Twitter: @Auri

________________________________

**Comment by mamraz** [comment]
Those options don't control encoding.  They give you the option to manually encode or decode a specific value.  While better than nothing, that is not really the ideal solution.  One of my requests can have 50 parameters in a format similar to param[23][field]=foo4.  However, since I need to encode it before sending it to the service, they look like param%5B23%5D%5Bfield%5D=foo4.  Looking through lists of such parameters trying to find the one having index 23 is very painful.

I am still baffled on how most people on this post are saying their problem is that Postman is encoding when they don't want it to, whereas my problem is that it doesn't encode when I want it to.  I have tried both http and https requests with unencoded values, and in both cases, my web server pukes and throws a 400 response.

**Comment by litao09h** [comment]
+1 for this feature

**Comment by xaviergm** [comment]
@AuriR 
FYI - These options do not change how the request is made...

> Have you tried right-clicking the parameter fields? There are features “hidden in plain sight” that control encoding… I learned about this at our Indy .NET Consoritum meetup a couple months ago :)

**Comment by xyh1** [comment]
+1

**Comment by ashwin24aug** [comment]
I am sending POST request from postman with below URL 
`https://[2405:200:1413:100:0:0:7:44]:6050/ERM/eventHandler/`

and getting below response from postman

Could not get any response
There was an error connecting to `https://%5B2405:200:1413:100:0:0:7:44%5D:6050/ERM/eventHandler/`

Can anyone please let me know how to fix this?

Note: when I use http in the URL, it works perfectly fine. Issue occurs when I use https.

**Comment by gabrielsperezz** [comment]
+1

**Comment by jhicksrowmark** [comment]
+1 Need this option as well! I use a Pre-request Script that needs the exact URL that will be sent. For now I was able to get by with a workaround:
```javascript
//shortcuts
const collection = require('postman-collection');
const subvars = collection.Property.replaceSubstitutions;
const vars = pm.variables.toObject();

//build the url the way postman actually sends it
let url = subvars(pm.request.url.host.toString(), vars) + '/' + subvars(pm.request.url.path.join('/'), vars);
const query = [];
pm.request.url.query.each(obj => {
    if(!obj.disabled){
        let encodedValue = encodeURIComponent(subvars(obj.value, vars));
        //might have to fix some things to match what postman sends:
        encodedValue = encodedValue.replace(/%3A/g, ':');
        query.push(subvars(obj.key, vars) + '=' + encodedValue);
    }
});
if(query.length) url += '?' + query.join('&');

console.log(url);//compare to the actual logged url
```

**Comment by FabianSawatzki1234** [comment]
+1

**Comment by gosua** [comment]
+1

**Comment by jeffabailey** [comment]
+1

**Comment by shamasis** [comment]
Hello everyone, latest Postman Canary onwards, you’d be able to observe a more consistent URL encoding and ... best of all ... turn off encoding completely for most parts of the URL using a setting. More details at https://github.com/postmanlabs/postman-app-support/issues/8154

**Comment by codenirvana** [comment]
Hey everyone 👋 
It took us a while but, we finally fixed most of the issues related to URL encoding. Check #8154 for more details.

The new URL processor is available in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting.
<img width="1552" alt="postman-settings" src="https://user-images.githubusercontent.com/4865836/76349728-8ccc4a00-6330-11ea-97ae-b1c2ff6c7980.png">

As mentioned in https://github.com/postmanlabs/postman-app-support/issues/4171#issuecomment-596051018, the new URL processor also gives you the ability to turn off encoding completely using a request setting.
<img width="968" alt="disabled-encoding" src="https://user-images.githubusercontent.com/4865836/76072995-ee05bd80-5fbe-11ea-8398-2615c17715e1.png">

Feel free to leave your feedback at #8154. Closing this thread now.

**Comment by mamraz** [comment]
I enabled "Use next generation URL processing".  I verified my request has the "Encode URL automatically" set to on.  Sent my request to the server.  I got a 400, bad request, back.  According to the Postman console, my parameters that had the form of "param[23][field]=foo" were sent unencoded, so the Tomcat server rejected it.  :-(

**Comment by codenirvana** [comment]
@mamraz Thanks for the feedback. I see `=` will be encoded. 
Can you check if disabling the `Encode URL automatically` request setting to turn off the encoding completely fixes your issue?

**Comment by mamraz** [comment]
You say "=" will be encoded?  I am not seeing that behavior, and I would not think that is appropriate behavior.  "=" is a basic component of the key-value pairs in URLs.  My issue is with the square brackets.  The Tomcat web server that is embedded in Spring Boot rejects requests containing those characters.  Turning off "Encode URL automatically" on the request did not change the behavior.  Tomcat still rejected my request with a 400 error.

**Comment by codenirvana** [comment]
@mamraz What I meant was, `=` in the param value will be encoded. e.g, `?key=foo=bar` will be sent as `?key=foo%3Dbar`.

As you mentioned, you are getting encoded `[` and `]` which I don't feel is because of Postman since these characters are not encoded. As seen in the raw HTTP packet response:
<img width="1128" alt="Screenshot 2020-03-11 at 6 57 44 PM" src="https://user-images.githubusercontent.com/4865836/76421905-5e9b4880-63ca-11ea-92f8-35ea51d72283.png">

Maybe your server is re-encoding the received params while parsing.

**Comment by mamraz** [comment]
It seems like we are not on the same page here.  I am using a URL like:

http://myhost.com/foo?param[1][field]=bar

It looks like Postman is not encoding any of this, so Tomcat is receiving a request that contains square brackets, which it rejects with a 400 error.  If I instead manually encode the square brackets using %5B and %5D so that the request looks like:

http://myhost.com/foo?param%5B1%5D%5Bfield%5D=bar

Tomcat accepts the request.

**Comment by codenirvana** [comment]
@mamraz I understand your concern but the new URL processor follows the [WHATWG (URL) standard](https://url.spec.whatwg.org/) like the majority of the browsers and other clients and has a consistent URL encoding behavior.

In your case, you can either manually encode the additional characters which are not encoded automatically or add the following script as part of your `Pre-request Script`:
```js
pm.request.url.query.each((q) => {
     q.update(encodeURI(q.toString()))
});
```
This script mutates (encodes the additional characters) the request URL before sending it.

**Comment by mamraz** [comment]
Thanks for the suggestion.  I have been doing something comparable to what you suggested with the pre-request script.  I was just hoping it would no longer be necessary.

Incidentally, your suggested script does not actually meet my needs, although it did get rid of the 400 server response.  I have Postman variables for some of my parameter values, such as "{{myVariable}}".  I am thinking what you suggested is encoding the brace characters, which results in the variables not being substituted with the actual value when the request is sent, and so my service received parameter values like "{{myVariable}}" rather than the actual value of the variable.  I have a solution that meets my needs, so I am not looking for another alternative.  I am just mentioning it in case someone else stumbling on this thread tries to use it.

**Comment by itsAnuga** [comment]
Enabled the "Use next generation URL processing".
Enabled "Encode URL automatically" on a GET Request, containing: ?filter={"compare":1} as a URL Query.
Got 400 Bad Request.
Disabled "Use next generation URL processing".
Run the Request again, worked...
URL Encoding isn't encoding Query's?

**Comment by brunodaga** [comment]
Why was this closed ? The problem is still there on version 7.32, isn't ?

**Comment by dbcto** [comment]
The problem still exists in v7.36.0!
"Use next generation URL processing" makes no difference in behaviour.
Using a Pre-request Script makes no difference in behaviour.
"Encode URL automatically" on this tab is off.

For example the String "%2Fexample%2F" is always converted to "/example/".

Any ideas?

**Comment by nelkon** [comment]
Is there any way to disable encoding at the header level? or how can I send accented letters along with headers?
Ex: inheader-BarbàPapù
Any ideas?
