### ISSUE TITLE
Feature Request: Command + / should toggle Settings Modal

### ISSUE THREAD

**Issue by govindrai** [a85/POSTMan-Chrome-Extension#4184]
Using 5.2.2. Currently Command + / brings up the Settings Modal but doesn't toggle itself out of view when invoking the command again. Even better, I would like to be able to invoke a shortcut I just learned without needing to exit out of the setting menu. For example, hitting Command + \ could autoexit the Settings modal and toggle my sidebar.

**Comment by kamalaknn** [comment]
@govindrai Thanks for your feedback. We will look into this.

**Comment by vkaegis** [comment]
@govindrai Thanks for writing in! Seems like this could be a specific improvement just for shortcuts. However, we've kept this different from a toggle interaction to be able to allow customizable shortcuts in the near future. In general, we use Esc as a dismiss shortcut for any modal views. Closing this since we won't be implementing this specific solution, but we'll look at how to provide a more consistent experience around these shortcuts.
