### ISSUE TITLE
execute request in parallel using the Runner

### ISSUE THREAD

**Issue by vbikash** [a85/POSTMan-Chrome-Extension#4198]
Is there any option to run a request in parallel(with x thread) using the Runner ?

**Comment by sivcan** [comment]
@vbikash - Runner as of now does synchronous execution of requests.
You can use multiple runner windows for multiple runs (run them in parallel).

**Comment by sivcan** [comment]
@vbikash - Runner as of now does synchronous execution of requests in a run.
You can run multiple runs on a folder or collection in parallel with different configurations (suppose environment, persist variables, delay etc.)

**Comment by vbikash** [comment]
@sivcan in the collection runner i see "iteration" and "delay" which is basically consecutive request not in parallel. am i  missing any other option?

**Comment by sivcan** [comment]
@vbikash - You can run multiple run's of a collection / folder in parallel.
Just keep selecting the targets and keep running them.
That's what the runner supports right now.
You probably knew this, if not then this will help you.

![image](https://user-images.githubusercontent.com/12631777/36342714-4699a5d6-1428-11e8-850f-1f715f2bb4c5.png)

**Comment by sivcan** [comment]
@vbikash - I hope this solved your problem.
If you need any further assistance, let me know.

**Comment by aynacisevda** [comment]
Hi sivcan,

I could not multiple run's of a collection / folder in parallel.
<img width="950" alt="potman" src="https://user-images.githubusercontent.com/44896069/48259011-b5d08800-e427-11e8-9a0a-b4bf07922d62.PNG">
What is the problem,could you help me please?
Could you give some details about the parallel execution steps?
Postman for Windows
Version 6.5.2

**Comment by sivcan** [comment]
Hi @aynacisevda, 
As explained above here: https://github.com/postmanlabs/postman-app-support/issues/4198#issuecomment-366191980
You cannot have runner execute the requests of a collection in parallel during a SINGLE RUN.
Runner always executes 1 REQUEST PER RUN at any given point of time.

However,
You can run multiple 'runs' of each collection parallely.
As mentioned here https://github.com/postmanlabs/postman-app-support/issues/4198#issuecomment-366449993
You can start a run, click on 'Collection Runner' and hit 'Run' again and again.
That'll be the only way out right now through UI.
So these will be parallel 'runs', that is possible.

Also, another solution would be to use [Newman](https://github.com/postmanlabs/newman)
You can actually run multiple instances of newman.

Since newman run's are executed asynchronously, you can run mutliple instance's of runs of a collection or folder faster using code.

**Comment by aynacisevda** [comment]
Thanks for your help Sivcan.

**Comment by roberto-t92** [comment]
Any updates on this topic? is postman still not multithread?

**Comment by Sancher17** [comment]
> @vbikash - I hope this solved your problem.
> If you need any further assistance, let me know.

Yes, that is works, but will be better to create a special option for this purpose ) .

**Comment by malpower** [comment]
i've got some work to help my self to run the collections simultaneously. see if it can help any one seeing this page
https://github.com/malpower/newnewman

and u are welcome to clone and modify.

**Comment by uday-bachu** [comment]
Posting in case it helps anyone landing here from search. Newman and the Collection Runner run a collection's requests sequentially, and most of the "parallel" workarounds just launch multiple Newman instances (each still sequential inside). I wanted a fast parallel smoke-test, so I wrote a small, dependency-free .NET CLI that flattens a collection (nested folders included) and fires every request concurrently with a configurable worker cap, then prints a pass/fail summary: https://github.com/uday-bachu/postman-parallel-runner
Cherry on cake: it does variable substitution, Postman environment/globals files, bearer auth, and JSON output.
