### ISSUE TITLE
Application crash on the opening since last software update 

### ISSUE THREAD

**Issue by rgazelot** [a85/POSTMan-Chrome-Extension#4224]
## App Details:
```
Postman for Mac
Version 6.0.2 (6.0.2)
OS X 10.12.3 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 Since the last software update
 2. Expected behaviour:
 See the application open :)
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
<img width="797" alt="screen shot 2018-02-21 at 3 54 31 pm" src="https://user-images.githubusercontent.com/1488251/36486752-915aa4a4-171f-11e8-8a7b-eee84ff4dbbd.png">

**Comment by rgazelot** [comment]
Works well after downloading and replacing my current application.

**Comment by SamvelRaja** [comment]
@rgazelot 

Sorry to hear that you are having trouble with Postman 6.0.

This is a major release that includes, among other things, changes to the format we store data locally for more stability. We are slowly rolling this version out to select users at the moment and we are tracking some issues in v6.0.2 that might prevent the app from starting due to discrepancies in the local data.

We have fixed these issues in our Canary channel, and we highly recommend using the Canary version for faster updates. (https://www.getpostman.com/canary)

Apologies for the inconvenience and thank you for your continued support.

**Comment by rgazelot** [comment]
Thanks for your answer and for the advices. Good job 👍
