### ISSUE TITLE
Large request payload crashes Postman

### ISSUE THREAD

**Issue by janAtcontinia** [a85/POSTMan-Chrome-Extension#4230]
## App Details:

I am making a put request
The body is raw xml
I try to post an xml document of 430.000 lines
It works well.
Before I click Send button I can switch between postman and Visual Studio.
As soon as I click Send Postman becomes completely black, with only the  menu and windows close/maximize buttons having another color.
Even when the request is done I cannot switch back to Postman. It is just a black square.
I have to restart it.
And funny enough, I always have to click twice on the close button for Postman to close.

**Comment by bmoyer240** [comment]
+1 - I just started a new project which has an api call that returns a large dataset and the window goes black within a second or two after the response is received. 

Windows
the response is 17mb

**Comment by sebnukem** [comment]
I'm experiencing the same symptom (standalone app window goes black) when I am getting a large XML response from a SOAP request. Postman v6.0.8

**Comment by janAtcontinia** [comment]
The error seems to have disappeared with the latest update of postman

**Comment by janAtcontinia** [comment]
But now it is back. I send the 430.000 lines request. Some time (ie 30 seconds) goes by. the screen becomes black, so I cannot see when the response is received. 
I just updated the postman app this morning to latest version.
Also, I cannot open the Postman Console when the body is 430.000 lines.  It just hangs with the orange dots and circles. And continues to write the small "initializing" texts.

**Comment by LeslieMurphy** [comment]
This happened to me, too.  Postman was no longer working at all for me.  It came up with a white (empty screen), then after a long while loaded my folders of requests, then showed a black screen of "death".  I have a few POST reqests with Json payload that is Base64 of  large files.  Spelunking into the DevTools (Shared), I see a Console message "Migration bailed out due to: EXCEEDED_ATTEMPT".  
(anonymous) @ shared.js:346516

This is horrible!  I think I am on 6.0.10 (EXE stamp was 1.16.16.0).  I  tried installing 6.0.9 and got the same issue.  There are no earlier versions listed for download :-(  

I figured out where the underlying datastore is located, and was about to back it up and start hacking away to remove the large objects (assuming I could find them).  But I tried one more time to open with 6.0.9 and that time it worked.  I then deleted the 2 posts with large Base64 Json in the request, and now things are working again.  

(Sigh).  

My Postman files are at %userprofile%\AppData\Roaming\Postman\IndexedDB

**Comment by lydiaralph** [comment]
+1 I get this even when not posting any requests. Postman screen goes black after about 3 seconds. Nearly unusable. 

OS: Mac 10.13.6
Postman: 7.8.0

**Comment by NylonDiamond** [comment]
Been having the above issue for many months. Our company is debating on using an alternative.

**Comment by stcalica** [comment]
user reports an issue with responses larger than 1GB

**Comment by saswatds** [comment]
Hi everyone 👋 . Over the past few released, he had made a lot of progress in handling really large request and response bodies. Currently we have pushed it to around ~700MB size. This comment https://github.com/postmanlabs/postman-app-support/issues/8288#issuecomment-691500931 has more information. Would like everyone to update to version >= 7.32.0 to see the difference and give us your feedback.

This new limit is going to be hard limit of how large of a data postman can handle because of fundamental language and runtime limitations. As we are not changing our platform any time soon, this new limit is going to hold for the time being.
Thanks a lot everyone for you patience and giving us the time to figure it out. I shall close this issue now with this positive note.
