### ISSUE TITLE
When restarted, the global environment variable will be reset

### ISSUE THREAD

**Issue by wuxinwei1** [a85/POSTMan-Chrome-Extension#4232]
> First execute：
> Pre-request scripts:
`var outBizNo_suffix = pm.globals.get("outBizNo_suffix");`
`outBizNo_suffix = parseInt(outBizNo_suffix)+1;`
`pm.globals.set("outBizNo_suffix", outBizNo_suffix);`

> Then reboot postman:
the global environment variable will be reset. What do I need to do?

**Comment by sivcan** [comment]
Hi @wuxinwei1 
I tried to reproduce this issue but wasn't able to.

Steps I did - trying to reproduce this issue:
1). Set a global variable `outBizNo_suffix = 1`.
![image](https://user-images.githubusercontent.com/12631777/36626141-16d703cc-1953-11e8-8e6a-ac09b87726ea.png)

2). Ran your pre-request script.

3). Restarted the app.
Result: 
![image](https://user-images.githubusercontent.com/12631777/36626170-88b82a34-1953-11e8-8bc7-873f61f34a3a.png)

4). Did `steps 2 - 3` for a couple of times. 
![image](https://user-images.githubusercontent.com/12631777/36626171-95f236c2-1953-11e8-989a-b60a60c33568.png)

What version of Postman are you using ?
Can you try updating to the latest version and check if the issue is still there for you ?

Let me know.

**Comment by wuxinwei1** [comment]
Thank you. The latest v6.0.6 version has fixed that problem.
