### ISSUE TITLE
Postman 6.0.9 canary2 on Windows 10: in collection form-data file value gets lost

### ISSUE THREAD

**Issue by aprixon01112017** [a85/POSTMan-Chrome-Extension#4293]
1. 

![pm_img1](https://user-images.githubusercontent.com/33280703/37087168-cbd9f992-21f9-11e8-9103-155b931f3680.png)

2. Select another request

3. go back to this request

4.

![pm_img2](https://user-images.githubusercontent.com/33280703/37087187-dd04e754-21f9-11e8-8417-fbce21a96573.png)

**Comment by harryi3t** [comment]
@aprixon01112017 Would it be possible to share a gif or video describing the issue? A similar issue was fixed in 6.0.8
in which sending a request again was not sending the attached file.

**Comment by aprixon01112017** [comment]
Same in Postman 6.0.9.

It seems that the value is not saved when exporting the collection. And the value is set in other requests as well  when it is set in one request.

I set  it (or remove it) in request 1 in folder 1 and in request 2 in folder 1 the same change appears.

**Comment by harryi3t** [comment]
@aprixon01112017 yes the values (file paths) are not exported/synced intentionally because of security concerns. So until the tab is open sending the same request, again and again, should send the file also. But once you close the tab and reopen the request, you need to re-select the file.

Also, when you set the file path in request 1 of folder 1 and then open request 2 of folder 2
1. does the request 2 opens in same tab or a different tab?
2. does sending the request 2 actually sends that file?

I have made a small video demonstrating this flow, which seems to be working fine.
https://drive.google.com/file/d/1xmUDgpWWDITTNdY-I5NORkOLXBXKk0x5/view?usp=sharing
Please check this and let me know what am I missing.

**Comment by aprixon01112017** [comment]
I cannot reproduce it: I have a request with property image and a second request with property image, but deactivated. When I selected a file for the first request the property was also set in the second request.

So when the file name is not saved und let's say I have a test collection containing 10 requests that POST files I would have to set a file name 10 times manually. I don't like that!

**Comment by harryi3t** [comment]
Related to https://github.com/postmanlabs/postman-app-support/issues/4320
