### ISSUE TITLE
Query params with no value are exported as empty string instead of null

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#4298]
When a collection is exported having a request with URL in which there is a query param with no value, it is exported as an empty string. 
```
http://postman-echo.com/get?a
```
is exported to
```
...
"query": [
    {
        "key": "a",
        "value": "",
        "equals": false
    }
]
...
```

When this exported collection is run using Newman, it reconstructs the URL and adds a `=`  at the end
So the URL becomes
```
http://postman-echo.com/get?a=
```

**Comment by shamasis** [comment]
The issue is pertaining to `http://postman-echo.com/get?{{my-params-in-variable}}` getting converted to a data structure where there is not enough information to decide between empty string and null value. The change for this might become subjective for those who want an empty equals to be appended. We had been going back and forth on this since a fix here leads to issues elsewhere.

We might be able to circumvent the data structure of URL temporarily and embed additional information to retain the UI input (with some possible incompatibilities in future). v6 of Postman addressed one "subjective" issue (albeit causing extremely minor edge-case side-effects) and we intend to solve this too.

@willybill since you understand the complexity of the situation here, I request you to bear with us for a while. We will have to be super duper careful not to disturb common URL parsing use-cases in any way.

PS: If you look at the [URL parser we have here ](https://github.com/postmanlabs/postman-collection/blob/develop/lib/collection/url.js), you will notice that we cannot simply get away with standard URL parsing. Being an HTTP client where all sorts of combinations of standard and non-standard URLs can be used (along with error cases to debug servers and variable substitutions), our parser has to try and be a superset of almost all parsers being used worldwide.

**Comment by harryi3t** [comment]
This is fixed

**Comment by thellamgowtham** [comment]
How did you fix it??
