### ISSUE TITLE
Collection runner - Persist variables not working

### ISSUE THREAD

**Issue by alexisml** [a85/POSTMan-Chrome-Extension#4299]
## App Details:
Postman for Windows
Version 6.0.9
win32 10.0.16299 / x64

## Issue Report:
This is a new issue (possibly associated with the new environments thing?).
There are 2 things:

1. Every time I access the collection runner, the "Persist variables" checkbox is unchecked, no matter if the last time it was checked.
2. The collection runner IS NOT PERSISTING THE VALUES (at least the environment ones) no matter the checkbox value. This is a big problem for me, as I run several data generation scripts before running my proper tests (1500+ data generation scripts). Environment values are hold for the execution of the folder selected in the collection runner, but they aren't saved to the environment variables (not even to the collection runner running instance). 

Note that this wasn't happening for me previous to the introduction of workspaces.

**Comment by sivcan** [comment]
@alexisml - I have not been able to reproduce this.
I have tested with pre-request scripts and test scripts but the persist variables in the collection-runner is working fine.
Can you share an example with me where you can reproduce this issue so that it'll help us to triage this issue quickly?

Thanks.

**Comment by alexisml** [comment]
I tried this out in other computer and it worked, so I reinstalled postman in the one that wasn't working and now it works. This is weird.
