### ISSUE TITLE
PostMan GET request with large data hangs, loading... forever without respond

### ISSUE THREAD

**Issue by BenCao2018** [a85/POSTMan-Chrome-Extension#4308]
## App Details:

```
Postman for Windows
Version 6.0.9
win32 10.0.15063 / x64
```

## Issue Report:
 1. This issue happens recently.
 2. Expected behaviour: Reponse with large JSON data
 3. Console logs: 
Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41849
There was a fatal error when sending the request! Object
done @ requester.js:130221

 4. Screenshots 

![console logs](https://user-images.githubusercontent.com/37190725/37171318-557a4f1c-22c2-11e8-8b1d-b87a00f99e93.PNG)

**Comment by sivcan** [comment]
Hi @BenCao2018 - As I can see in the console logs that there was a fatal error when sending the request.
Can you expand that error and share the image here ? 
Feel free to blur out any sensitive information. 

Also, how much is the size of the JSON data ? 
So that we can try to reproduce this on our end.

**Comment by numaanashraf** [comment]
@BenCao2018 We have created a master thread #4751 to track all issues related to large responses. Please follow that issue for updates.
