### ISSUE TITLE
Debug output not being printed in Console

### ISSUE THREAD

**Issue by trivial-search** [a85/POSTMan-Chrome-Extension#4332]
## App Details:

```
Postman for Windows
Version 5.5.0
win32 10.0.15063 / x64

```

## Issue Report:
 1. In the native windows app--> Under tests--> write a simple console.log statement - console.log("test123");
Nothing gets printed in the Postman console or the develop tools ( when invoked through View --> Show Dev tools
 2. Expected behaviour:
 Debug message should be output to console

 4. Screenshots (if applicable)
The test script...

![image](https://user-images.githubusercontent.com/15244739/37368769-0d38e1a6-276c-11e8-9c50-fd476a7ad2f7.png)

No debug output in the Postman console

![image](https://user-images.githubusercontent.com/15244739/37368813-2a81b33c-276c-11e8-8977-9f336f8de27e.png)

No debug output in dev tools

![image](https://user-images.githubusercontent.com/15244739/37368838-3f3a74ee-276c-11e8-9aa5-f656a50e90ad.png)

**Comment by sivcan** [comment]
Hi @sunjeet-khokhar - That's simple because an error has been thrown and the execution of the code will stop right there (JavaScript) because there's no handling done for that error.

However, if you move your test lines inside a test function like so:
```
pm.test('testing', function () {
    pm.expect(123).to.eql(12);    
});

console.log('123');
```

Then the test will fail obviously because it has caught the assertion error and now the execution will continue after that test.

You can try out the code that I shared and that'll clear your doubt.
