### ISSUE TITLE
0 is not added as value to envoroment variable from pre-script

### ISSUE THREAD

**Issue by Paychokxxx** [a85/POSTMan-Chrome-Extension#4333]
Postman Version: Version 6.0.9
App (Chrome app or Mac app): Windows App
OS details: Windows 10 64 Bit

in pre-script, if I try to set 0 to variable

let steps_to_add = 0;
pm.environment.set("steps_to_add", steps_to_add);

in quick look 0 will be displayed but really
environment variable will have empty space (if you open environments with edit button or in test you use this value)

**Comment by ghost** [comment]
Hey,
Thanks for reporting the issue. The value is being set to zero successfully in the database but is not getting rendered in the view correctly.
Since it is being set correctly, this won't interfere with your scripts (you can continue to use the variable.). In the meanwhile, we will fix the rendering issue.
Cheers !

**Comment by Paychokxxx** [comment]
when I run my tests with Newman and use this set variable in POST request body - 0 is also missing

**Comment by prashantagarwal** [comment]
Related to #3463
