### ISSUE TITLE
Feature request: ability to continue runner when error arrises

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#4341]
## App Details:

```
Postman for Mac
Version 6.0.9
OS X 17.4.0 / x64
```

## Feature:
I wrote an issue a while back about the runner stopping every time an error arrises and that it shouldn't stop the runner. Well along those lines, I think there should be an option to continue where it left off. For example, I have a collection that creates a consumer, links accounts, creates orders, etc. Well, a lot of times when there's an error, it happens about halfway through or towards the end of the run. A lot of times it's just something like a 502 error or something which generally means it just has to be hit again (in our system, at least). Validations could be added to make it automatically check for that, but I still think it would be useful to have the ability to have continue after it fails and stops.

**Comment by sivcan** [comment]
Hi @chrisron95 - I'll be marking this as a feature request.

**Comment by Bhudeb** [comment]
Any update on this feature...

**Comment by m3dbedb** [comment]
Also wanted runner mode "halt on errors".

**Comment by salutcava** [comment]
Hi, 
Any update on the feature ?

**Comment by boris-simeonov-swi** [comment]
Hello, any update on this? This should be a basic feature and still is not implemented :/

**Comment by reinaldorossetti** [comment]
I have the same problem, I consider it as a bug critical because it stops my tests from running.

**Comment by stcalica** [comment]
hey team! also an issue for me, any request returning an error status code halts the entire test suite. 
Could we get an option in the collection runner AND monitors to continue if an error status code returns.

**Comment by malvikach** [comment]
@stcalica I understand this could be a problem. This issue has been on our radar. 

Wanted to understand the error status a bit more though. What kind of errors do you usually face (if you could give 2-3 examples). 

Another point to think about here is that if a request failed due to an error and none of its tests got executed- We will need to indicate that the attached tests were neither skipped nor failed- they were not executed due to request error. This might warrant a separate state for the tests (currently we have passed/failed/skipped states for tests). 
Let me know your thoughts as well. Happy to brainstorm further.

**Comment by malvikach** [comment]
Hi @chrisron95 
I am closing the issue as it was resolved some time back. 
See [here](https://github.com/postmanlabs/postman-app-support/issues/3360) for more details. 

Cheers!
Malvika
