### ISSUE TITLE
Body lines silently truncated after 4096 characters

### ISSUE THREAD

**Issue by jadengeller-asana** [a85/POSTMan-Chrome-Extension#4349]
## App Details:

```
Postman for Chrome
Version 5.5.2
OS X / x86-64
Chrome 64.0.3282.186
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I've encountered this recently as well as a few months ago. It may have always been there.
 2. Expected behaviour:
Don't silently truncate.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
N/A
 4. Screenshots (if applicable)
N/A

Receive payload that's over 4096 characters on a single line in the body of response .

**Comment by kamalaknn** [comment]
Hi @jadengeller-asana 

I just tried the same with our latest Native Postman App. I wasn't seeing any issues with truncation. Could you try downloading the latest version of our Native App from https://www.getpostman.com/apps and check if this still exists? Also, could you verify if the API is not truncating request bodies?

I'm closing this because the issue report is in the deprecated Chrome app. Please reopen if you're seeing this in the latest native apps as well.
