### ISSUE TITLE
Error during JSON.parse Unexpected token u in JSON at position 0 

### ISSUE THREAD

**Issue by AlexanderTunick** [a85/POSTMan-Chrome-Extension#4350]
Hi, successfully using newman tests in TeamCity, and now want a bit to upgrade it by adding console.log for everything that !==200
Want to notice that we receive JSON format response (I asked developers to change it from html)
but this issue still present (but only in Postman):
**Error during JSON.parse Unexpected token u in JSON at position 0** 
In newman console.log() successfully outputting.

I use this construction:
```
let responseJSON = JSON.parse(responseBody.message);
tests["Status code is 200"] = responseCode.code === 200;

if (responseCode.code !== 200) {
    console.log(responseJSON)
    return;
}
```
Console log, a part of code of respone (very begining):
```
{ message: 'Trying to get property of non-object',
  │   exception: 'ErrorException',
  │   file: '/var/www/build-a-list/vendor/tymon/jwt-auth/src/JWTAuth.php',
  │   line: 93,
  │   trace:
```

## App Details:

```
Mac mini (Late 2014)
2.6 GHz Intel Core i5
8 GB 1600 MHz DDR3
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
yes

**Comment by sivcan** [comment]
Hi @Alextunchii  - I think you're trying to parse `undefined` or something that's a `string` maybe ?
Can you give me a sample of the response you're trying to parse ?

Try : 
1. Open Postman Console (Click on View > Postman Console)
2. Write this : `console.log(responseBody.message)` as a test script in the request 
3. Hit send and check if you're getting the correct responseBody.message being logged in the postman console.

Also, are you on the latest version of the Postman app - Postman 6 ?

Another thing, if you simply want to test the status code if it's 200 or not you can write the following code in the test script. 
Also, you can use the same format for testing purposes. 
```
pm.test("Status code is 200", function () {
    pm.response.to.have.status(200);
});
```
as for your use case may try rewriting the code like so:

```
let responseJSON;
tests["Status code is 200"] = responseCode.code === 200;

if (responseCode.code !== 200) {
    try {
        responseJSON = JSON.parse(responseBody.message);
        console.log(responseJSON);
    }
    catch(e) {
        console.log(e);
    }
    return;
}
```

Let me know if the issue is there - do give me a sample of what you're trying to parse that is throwing this error so that I can try to reproduce this issue.

**Comment by AlexanderTunick** [comment]
Hello! Thanks for response @sivcan 
I'm still using Chrome Postman, but I see I need to take a step forward to Postman app

I use almost the same structure you have shown me:
```
var adminToken = JSON.parse(responseBody);
tests["Status code is 200"] = responseCode.code === 200;
if( responseCode.code !== 200 )
{
    console.log(adminToken); 
    return;
}
```

Everything I need, using newman in TeamCity to see console log right in Build log while Error occurs (500, 400 etc) with explanation of body response in order not to go to postman and watching the result with the question "Why this command didn't work out?".

Maybe this old postman is the reason on this issue, I'm closing this issue currently, and will try to do it in the latest Postman version, if still be getting it, I will reopen it.

Thanks
