### ISSUE TITLE
Dashed selection-square appears when selecting text

### ISSUE THREAD

**Issue by mmans** [a85/POSTMan-Chrome-Extension#4370]
## App Details:
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64

![postman-bug](https://user-images.githubusercontent.com/201741/37766952-d7ae26a0-2dc8-11e8-9073-96ec62ca8989.png)

```
## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always
 2. Expected behaviour: Text selection like in every application
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)


<!--
Steps to reproduce the problem
-->

1. Start selecting text in a textbox
2. While dragging the cursor over the text leave the textbox
3. The wild dashed square appears
4. Now it is not possible to select the text

**Comment by callmeaatrey** [comment]
@mmans , so this is an expected behaviour. If you move out of the text-box it selects rows instead of values and that helps in moving them around. I would suggest you should restrict the selection within the text-box. I am closing the issue for now. If you have any other queries regarding this feel free to open it again.

**Comment by ghost** [comment]
It is very inconvinient behaviour. After selection of many rows are finished no selected rows are appeared, all selection is being cancelled.
How can I turn off this selection behaviour?
