### ISSUE TITLE
Deleting a request in the sidebar keeps the tab and changes its state to "unsaved"

### ISSUE THREAD

**Issue by mr-newell** [a85/POSTMan-Chrome-Extension#4388]
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 17.3.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
**Started after upgrading to 6.0.10; not sure what my previous version was but it was within the last few.**
 2. Expected behaviour:
**Deleting a request in the sidebar removes the tab as well. Delete means delete.**

Deleting a request from the sidebar should remove the tab containing the request. Instead, the request remains, and the tab is set to an unsaved state. This means that the process of deleting a request is:
- Right click request
- Click delete
- Confirm delete
- Click to close tab
- Click to discard "unsaved changes"

**Comment by sujayvenaik** [comment]
@mr-newell 
When you delete the request from the sidebar in version 6.0.10, the request gets deleted.
But if the request is open in one of the tabs, then it reaches the unsaved state.
If it isn't open in one of the tabs, it will simply get deleted.

**Comment by mr-newell** [comment]
What part of having to confirm my deletion through a popup suggests that I don't actually want to delete the request but instead want to have all the deleted requests pile up in the tab bar? If I have other unsaved requests, this means I now have to guess whether I'm discarding real changes or that-request-I-deleted-but-didn't-really, unless I check the sidebar.

Maybe it would be a good idea to instead update the "History" pane with a way to retrieve deleted requests.

**Comment by preethammavin** [comment]
@mr-newell agree that this is tedious, the reason why we do this is ensure if there any changes on the requests tabs we do not close the tabs and loose users data.

But you do have a valuable feedback, we will look at how we can address this in a better way.

**Comment by brianbellon** [comment]
The frustrating part about all of this is that you can't just click on a side-bar item and delete without having a TAB pop-up for that item.  So these tabs breed like rabbits if you are doing much editing.  The better way to do this is to prompt the user about what they're about to remove.  For instance:
In Scenario #1 - I just click on a side bar item, then having the tab show up, there's no edit red dot on the tab - so it's not been edited unknowingly, and thus when I say delete - delete the side bar item and the associated tab.
In Scenario #2 - If an item is showing on the tabs as edited - with the red dot, then if I were to go and try to delete the item in the side bar, warn the user that there are unsaved changes on that tab and deleting the item will also delete the changes.  Still have both the side item and the tab disappear because the user will have been warned about what's happening.  The current functionality makes no sense in usability.  
If you can't do the above ideas, when you are deleting a side item, have a check box item in the delete prompt that also says to also remove the tab item as well.  Like Mr. Newell said - delete means delete.

**Comment by vkaegis** [comment]
@brianbellon Could you tell me which version of the app you're using and on which OS? AFAIK, you should be able to right click on a request OR open it's context menu without selecting it / having it open in a tab.

@mr-newell Automatically deleting these tabs might cause unintended loss of data which we usually try to avoid. That said, I understand your use case. What we'll definitely be doing over the coming versions is giving you more information about why a tab is dirty (the request got deleted / someone else changed the underlying request in another workspace. Stay tuned for updates!

**Comment by brianbellon** [comment]
I am up to date with 6.1.4.  I see what you are referring to – but I don’t think that would be normal way of deleting something.  Normally you’ll have an open tab to show you what you’re deleting.
What’s broken is like I mentioned.  Clicking on a side item – having the tab show up on top – without a red edited dot.  Clicking to delete the side item and having it disappear – and the top item remaining and changing to have a red edit dot.  This makes no sense at all.  I’m looking at the item, know it’s not edited, want to get rid of it, but in choosing to delete it, it goes to edited and remains on a top tab?  Removing from the side shouldn’t set it to edited.  Even changing the name of a side item doesn’t change it to edited, which I would consider more of an edit than a delete would be.

The frustrating result of this, is that I have to click on each red edit tab and determine if it still exists or not – because I don’t want to close one that is associated with an real item on the side list.  It makes a frustrating job to clean up after you are done editing and deleting what you’re working on.

Like I mentioned, I understand totally, if an item on the top shows edited, then I go to delete it on the side and it remains on top.  This would call my attention that I have an edited item.  This could be handled with a Delete Anyway checkbox in the delete prompt – and still remove the upper tab.

All this is pretty much like editing documents in Word or something.  For really important collections I’m working on, I have many backup exports of my data just in case something happens to them in Postman – which has happened in the past many times, when 2 people are editing the same collection and it chokes on Syncing issues.  My fall back now is frequent exports to ensure I have my work saved to a file.

Thanks for your questions and suggestions.

**Comment by vkaegis** [comment]
@brianbellon Thanks again for taking the time to explain this! Your point about showing the red dot for edited tabs of requests which might have been deleted is great. As I mentioned, we're working on a whole bunch of improvements on how we handle tab states that should be out in the coming versions. I'll keep this open until your use case is solved.

**Comment by vkaegis** [comment]
@mr-newell @brianbellon With v6.4, we've added a [DELETED] prefix to tabs whose base request has been deleted. This should help you identify any such requests open in tabs. I'm keeping this feature request open as we're considering adding a configuration which will automatically remove these tabs.

**Comment by DannyDainton** [comment]
In the latest versions of the platform, the deleted request tabs are removed when the deletion is confirmed.
