### ISSUE TITLE
postman not able to connect and Sync

### ISSUE THREAD

**Issue by chandu478** [a85/POSTMan-Chrome-Extension#4419]
## App Details:

Postman helps you develop APIs faster
Postman for Windows
Version 6.0.10
win32 10.0.14393 / x64
Website
Twitter
Licences
Changelog
Documentation
Report an issue
```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: was able to sync before
 2. Expected behaviour: should be able to connect and sync
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

[postmanSync.docx](https://github.com/postmanlabs/postman-app-support/files/1881244/postmanSync.docx)

**Comment by kamalaknn** [comment]
Hi @chandu478 

From your configuration, I could see that you are on an older version of Postman `4.11.0`. The latest version is `6.0.10` now.

Could you download the latest version of Postman from `https://www.getpostman.com/apps` and give it a try?

I'm closing this issue because this is on a really old version of Postman. Please get back to use if you feel the same issue exists on the latest version as well.

Thanks for understanding
