### ISSUE TITLE
Variable are not interpolated into strings.

### ISSUE THREAD

**Issue by dbkaynor** [a85/POSTMan-Chrome-Extension#4425]
In the following code samples the environmental variable {{Code}} is not interpolated:
The variable Code may be either global, environmental, or private.

For example 
var Code = "Hello"

console.log("Test {{Code}} string")
tests["**** If test fails,  {{Code}} is wrong ****"] = false

I would expect the console to display  "Test Hello string" but it displays "Test {{Code}} string" instead.

**Comment by kunagpal** [comment]
@dbkaynor If the variable in question is a non-local environment variable, you'll have to use `pm.variables.get('Code')` to fetch the value of the variable. For the example above,

```js
var Code = "Hello";

console.log(`Test ${Code} string`);
tests[`**** If test fails, ${Code} is wrong ****`] = false;
```

**Comment by kamalaknn** [comment]
Hi @dbkaynor 

As @kunagpal mentioned you can use the `pm.variables.get('Code')` to use your variables in test names.

I've closed this issue because this is not a bug/issue with the Postman app itself. You can find more help and discussion with using the Postman app on [our community forum](https://community.getpostman.com/)

Thanks.
