### ISSUE TITLE
Special Characters from CSV and JSON data files are not displayed or sent in the Body correctly

### ISSUE THREAD

**Issue by jobidocs** [a85/POSTMan-Chrome-Extension#4437]
Postman for Chrome
Version 5.5.2
win / x86-64
Chrome 65.0.3325.181

When i try and load in a CSV/JSON file encoded in UTF-8 with special characters in the string Postman does not recognize the special characters: for example "Bodhráns" appears as below

![image](https://user-images.githubusercontent.com/38262716/38586805-21eab9ba-3d17-11e8-807a-b8b621c008d4.png)

Do you have any ideas of how i can get postman to recognize these?
Thanks

**Comment by jobidocs** [comment]
Also, when i try to send the variable through in the body text, it will send the corrupted character in the string.

**Comment by sdnts** [comment]
Hi @jobidocs, Is this just an issue with preview or are these characters actually sent incorrectly with the body?

**Comment by jobidocs** [comment]
Hi madebysid, 
Yes, they are being sent incorrectly with the Body. I can't work out for the life of me why postman isn't loading the characters correctly. The files i'm using are saved in UTF-8 format, so it should be all ok.
Any help would be very much appreciated
Thanks

**Comment by sivcan** [comment]
@jobidocs - I copied the same string as you've mentioned and tried in both the Chrome App and the [Native App](https://www.getpostman.com/apps) but wasn't able to reproduce this issue.

As you can see the preview here: 
![image](https://user-images.githubusercontent.com/12631777/38638445-e48eb186-3deb-11e8-8c5c-722c167cf8d3.png)

Can you download the [Native Postman App](https://www.getpostman.com/apps) and try with it once ? 
Let me know if the issue still persists for you.

Also, let me know what editor are you using for editing this file so that I'll try it with the same editor.

**Comment by jobidocs** [comment]
Ah great - thanks, it was an encoding error from this end. I've got it working now!
Thanks for your time!

**Comment by rahulprinjay** [comment]
Hi,
It not working for me too. I have the data read from the .csv file even though the expected and actual results displays as same but still the Assert is failing. Please advice
For Eg. Actual "3-ABC Test" Expected: "3-ABC Test". Still the Assert fails.

**Comment by SirishaManne** [comment]
Try to save the file the CSV file in UTF-8 
![image](https://user-images.githubusercontent.com/8956064/160926681-7955aa1f-22ce-48b7-a18f-704fb3f4e767.png)

Alternate way is you can import JSON file
