### ISSUE TITLE
Paste Raw Text with URL-encoded query string does not work properly

### ISSUE THREAD

**Issue by roukmoute** [a85/POSTMan-Chrome-Extension#4440]
## App Details:
```
Postman for Linux
Version 6.0.10
linux 4.4.0-119-generic / x64
```

## Issue Report:
 1. I encounter this recently.
This happends when we paste a cURL in `Import` → `Paste Raw Text`.

 2. Expected behaviour: Decodes any %## encoding in the given string

Paste this text in:

```
curl -X POST \
  http://localhost \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Postman-Token: 09499b09-4381-492c-bf4b-fa29044fd6fd' \
  -d foo%5Bbar%5D=baz
```

Instead of having: 
![image](https://user-images.githubusercontent.com/2140469/38619221-f8839486-3d9b-11e8-8944-ea34d89f1357.png)

We have this trouble:
![image](https://user-images.githubusercontent.com/2140469/38619265-14f276fa-3d9c-11e8-8262-28ed8bcfe61d.png)

**Comment by SamvelRaja** [comment]
@roukmoute  We try not changing any data provided by the user, 
As the expected behavior from you will be a conflicting behavior for other users. Postman tries to be neutral and spec-compliant as much as possible about these.
To solve your problem, you can select the text to decode -> Right Click -> EncodeURIComponent
