### ISSUE TITLE
Feature Request - Seperate Environment for each Workspace tab

### ISSUE THREAD

**Issue by scott-davidjones** [a85/POSTMan-Chrome-Extension#4441]
```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

Hi, 

I work with various environments in one postman window. It would be highly beneficial to me to be abel to have 1 tab open connected to my local environment and anther tab open connected to a different environment (say development). At present i have to keep switching tabs and then environments to compare results. 

Not a major hassel but would speed up my workflow.

**Comment by preethammavin** [comment]
Hi @autumndev 
You can open two windows, with the one tab and one environment set in each. This will let you compare results side by side.

**Comment by simonds** [comment]
@prashantagarwal I would like to see this feature without having to open a second (or third, or fourth, etc.) window. Any chance this request can be re-opened?

**Comment by tauinger-de** [comment]
I would welcome a single-window solution as well. The concept seems to be like a "sticky" environment selection per tab. Could be a simple enable/disable icon that remembers the current environment when leaving the tab and reselects it when entering the tab again.

**Comment by cebaa** [comment]
+1 for this.

It actually would be good to add a per-tab environment override, so that there's one global environment that is a default when a new tab is opened, but that can be overridden if needed.

I.e. current variable scopes are:

Global -> Collection -> Environment -> Data -> Local

and what I'm proposing is:

Global -> Collection -> Environment -> Tab -> Data -> Local

where the new Tab can probably work in the same way as Environment, except it would be a combo box that's applicable to this tab only.

@preethammavin This is more useful than the proposed workaround of opening two windows as then the environment is consistent. E.g. if I changed things in one window, then I'd have to change in another window as well.
