### ISSUE TITLE
Failed to import collection APItude 

### ISSUE THREAD

**Issue by slim-hmidi** [a85/POSTMan-Chrome-Extension#4460]
## App Details:

```
Postman for Ubuntu
Version 6.0.10
OS 17.10
Chromium 65.0.3325.181
```

I'm trying to import APItude in postman so I clicked import from link and I enter this link:
```
<redacted>
```
I got this error : 
```
Failed to import collection APItude 
```

I deleted all the environments and everything in postman, however when I import I got this popup:
```
collection APItude already exists
```

How can I fix that?

**Comment by sdnts** [comment]
Hi @slim-hmidi, I've removed the link you posted here because I saw that it had sensitive information in one of its saved responses. I'd advise against that since you might accidentally leak internal data.

I was able to reproduce this, though. It looks like the collection itself is malformed. Do you have access to the original collection (or do you know who the author is?). If so, can you ask them to update to the latest version of the app, and then re-export the collection? That should sanitize this collection so you'll be able to import it. Let me know if you're able to do that.

As a side note, if you're getting the `collection APItude already exists` error, you can try clicking on `Import As Copy` to import.

**Comment by rimKtari** [comment]
You have just to update postman version
