### ISSUE TITLE
Accessing elements inside an array for a global variable

### ISSUE THREAD

**Issue by saripr** [a85/POSTMan-Chrome-Extension#4464]
When I run tests from collection runner some tests fails and those pass in newman 3.9.1

App Details:

Version 6.0.10
newman 3.9.1

Postman for Ubuntu
Version 6.0.10
ubuntu 16.04 LTS

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:yes
 2. Expected behaviour:Display the first element of the array
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Steps to reproduce the problem

I have these lines of code:
pm.globals.set('my_var', JSON.stringify('["50_1", "50_999"]'));
var b = JSON.parse(pm.globals.get('my_var'));
console.log(b);
console.log(postman.getGlobalVariable('my_var')[0]);

variable b displays the parsed output of 'my_var'
But postman.getGlobalVariable('my_var')[0] just displays the first character and not the whole string 50_1

**Comment by saripr** [comment]
![selection_085](https://user-images.githubusercontent.com/10835735/38875276-4febae1c-425a-11e8-8d01-3a4697ecb2f7.jpg)

**Comment by saripr** [comment]
![selection_085](https://user-images.githubusercontent.com/10835735/38875411-975101a8-425a-11e8-801b-8620dcc34cdb.jpg)

**Comment by sivcan** [comment]
@saripr - This is because the globals are stored as string in the app.

You're parsing them in the variable b thus it's converted to an array and checking the index - [0] is giving you the actual value at index 0 whereas when you're directly trying to access the value it's returning a string and the `"` is at the 0th index of the string thus you're getting the first character being printed.

The support for types in the app is on the roadmap.
You can follow this thread for updates: https://github.com/postmanlabs/postman-app-support/issues/4130
