### ISSUE TITLE
sync conflicts cannot resolve

### ISSUE THREAD

**Issue by yangxikun** [a85/POSTMan-Chrome-Extension#4471]
## App Details:

```
Postman for Mac
Version  6.0.10 (6.0.10)
High Sierra 10.13.4
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/3364160/38980746-39cafd3a-43f0-11e8-99c9-4a010e30cfd1.png">

 2. Expected behaviour:

click resync, then resolve. But the conflicts always show after a while .

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by S33G** [comment]
I am also experiencing this on a Mac on High Sierra.
It seems to happen randomly. I can't consistently reproduce it in order to provide steps

But sometimes I will alt-tab back to posman and it'll present me with the Resolve Sync Conflicts window.

This is happening on a local collection which I found rather strange.

**Comment by sdnts** [comment]
Hi guys, I believe this is the same as #4360, we're investigating that as we speak. I'll let you know there when we make progress

**Comment by bitcoder** [comment]
this problem still happens and is quite annoying. please reopen the bug.
this happens with latest version (7.25.2) on MacOS 10.15.4

![image](https://user-images.githubusercontent.com/553801/83867891-0bfbcf00-a722-11ea-936a-ba77a867896f.png)


The conflicts make no sense. I'm a signgle and only user editing the collection. More, as you can see Postman thinks there are conflicts in all requests even though there are no differences.
Besides fixing this issue, I kindly ask a slight UI improvement.
To have a possibility of choosing to "Use all local changes", as with the default behaviour users have to go over all the requests and opt for the local changes (otherwise, information is lost as it happened to me)

Makes sense to reopen this or create a new ticket?

**Comment by arlemi** [comment]
@bitcoder Please open a new ticket and mention #4360. 🙂
