### ISSUE TITLE
OAuth2 flow missing name attribute in console

### ISSUE THREAD

**Issue by mrshawn191** [a85/POSTMan-Chrome-Extension#4490]
When finalizing the token extraction from /oauth/token somehow name is not displayed in the window... However bringing up the console, I could see that indeed it was returned from the api.

Image of the console proving the name is returned

<img width="1103" alt="postmanconsole" src="https://user-images.githubusercontent.com/5851638/39248489-83e58a1a-489c-11e8-9781-cfc204b035d9.png">

Image of the Manage Access Tokens window, where name is missing

<img width="1440" alt="postman managing token" src="https://user-images.githubusercontent.com/5851638/39248516-96fb5bde-489c-11e8-98d3-512f7aba6d5b.png">

It's very strange, seems to only happen if attribute name is name

**Comment by sdnts** [comment]
Hi @mrshawn191, thanks for reporting this. @harryi3t, can you take a look?

**Comment by harryi3t** [comment]
@mrshawn191 
As per the [rfc-6749#4.2.2](https://tools.ietf.org/html/rfc6749#section-4.2.2), there is no standard field for specifying the name of the token. That's why Postman has a dedicated field for specifying the token name.

Let me know if I have missed any point in the above RFC regarding this.

![image](https://user-images.githubusercontent.com/5207331/39416869-e490952e-4c6d-11e8-841b-34ebef43d241.png)
