### ISSUE TITLE
Query: Does Postman/Newman support running Collections/Jsons from another Master Collection/Json?

### ISSUE THREAD

**Issue by saratrajan** [a85/POSTMan-Chrome-Extension#4492]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

## Query:
Is there a way to run Collections from a master level?
e.g: I have module-wise collections for each APIs. I need to be able to run all of them (or some of them) by mentioning the items/order from another Collection (like a Master).

I am not sure if this was a Postman or Newman question. So posting on both the forums.

**Comment by sdnts** [comment]
Hi @saratrajan, currently, there is no way to reference one collection from another collection. We treat each collection as separate entities.
You can, however, use folders in a collection to achieve this. That way, you will have one collection, and each folder will be you "module". You can create folders inside folders, so that should not be an organizational problem :)
