### ISSUE TITLE
Postman-AWS4 Signature Does Not Match

### ISSUE THREAD

**Issue by Shambler13** [a85/POSTMan-Chrome-Extension#4531]
Hello,

I want to send a GET request to an Amazon server.
I have the credential, Key and the Secret key.

I have followed the way to build a signature as Amazon suggest , see link below (https://docs.aws.amazon.com/fr_fr/AmazonS3/latest/API/sig-v4-header-based-auth.html)

Using their parameters, i found the same signature they provided in example.

I changed the parameters to use mine, the key, secret key, region , host and date ofc and i always get an error of signature does not match.

I doubted that postman add the cach and token, so i disabled sending them.
Are they any other tips? i'm stuck in this problem since a week and i dont know where to begin

**Comment by dhineshwiz** [comment]
Hey @Shambler13, Can you try using AWS signature under authentication type, 
please refer this docs, https://www.getpostman.com/docs/v6/postman/sending_api_requests/authorization

**Comment by harryi3t** [comment]
@dhineshwiz Can you share a screenshot of the data you enter and the error that you see.
You can blur-out the sensitive information.

Also, since you obviously can't share your credentials, can you try generating the signature outside of postman and confirm that Postman is not generating the correct signature? There are libraries available for many languages.

Check this https://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html
It has examples to generate the signature in many languages.

**Comment by Shambler13** [comment]
Hello, All,

Sorry to keep this topic open,

I used POSTMAN just to simulate my request.

I, now since a good moment , was able to send authentified request using STM32 crypto library + my own code to create canonical request + string to sign.

BR
