### ISSUE TITLE
Using a variable with undefined value causes the request to error

### ISSUE THREAD

**Issue by AlexanderTunick** [a85/POSTMan-Chrome-Extension#4536]
Hi. Encountered an issue.
I have this script in Pre-request Script tab

> var institutions = ["School", "District", "Library", "Daycare"];
> pm.environment.set("arrayInstitutions", institutions[_.random(institutions.length)]);
And added "arrayInstitutions" to Environment

When I hitting "Send" button several times after 3rd or 4,5th time it(The "Send" button) just holds in "Sending..." status 
And in request point:
`{{api_base_url}}targeting/job-functions/jobs?segmentCriteriaId={{job_seg_crit_id}}&institutionType={{arrayInstitutions}}`
{{arrayInstitutions}}- becomes Unresolved variable and disappeared from ENVIRONMENT
I don't know why, other examples for another endpoints work ok, what's wrong?

MAC 10.12.6
Postman 6.0.10

**Comment by dhineshwiz** [comment]
hey @Alextunchii thanks for reporting the issue, we will fix it soon

**Comment by dhineshwiz** [comment]
hey @Alextunchii there is an issue with your pre-request script  `_.random` with single argument will return a random number between 0 and given number, and when you try access array index with given number you will get undefined, which is set to environment. 

You can use this updated script 

`var institutions = ["School", "District", "Library", "Daycare"];
pm.environment.set("arrayInstitutions", institutions[_.random(institutions.length-1)]);`

The fix for this would be handling undefined to empty string while setting environments, we would be releasing this fix in next version of the app

**Comment by AlexanderTunick** [comment]
@dhineshwiz yeaah, so obvious, I forgot that the last index is not considered here, of cause it's undefined.

Ok, thanks for the comment!

**Comment by harryi3t** [comment]
Hey @Alextunchii,
There is already an open issue for this here https://github.com/postmanlabs/postman-app-support/issues/4199
I am closing this in favor it, please subscribe to that issue for updates.
