### ISSUE TITLE
Collection runner missing response body: 'Data unavailable'

### ISSUE THREAD

**Issue by orestes** [a85/POSTMan-Chrome-Extension#4556]
**Describe the bug**
Response body is not displayed after running tests for a collection.

**To Reproduce**
1. Open the Collection Runner
2. Select a collection that contains tests
3. Make sure `Log Responses` is set to `For all requests`
4. Run the collection
5. Check the details for any of the tests
6. Response body is not displayed, but the following message is displayed: `Data unavailable (only data about the top 10 historical runs is stored)`

**Expected behavior**
The response body should be displayed

**Screenshots**
![screen shot 2018-03-14 at 01 28 17](https://user-images.githubusercontent.com/618107/37376903-00aff40a-2727-11e8-88ca-0762b08be772.png)

**App information (please complete the following information):**
 - Affects Chrome App and Native App
 - Postman Version 6.0.9
 - OS: Mac OS X High Sierra 10.13.2

**Comment by sivcan** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4296

**Comment by christhomas** [comment]
Yeah it's nice that you know it's a duplicate. So since you're aware of the problem, why don't you hussle on over there and actually provide support for it. Just a thought. It's over a year since the issue was reported and people are reporting since then the problem exists and nothing has been done about it.
