### ISSUE TITLE
use Global variables in URL

### ISSUE THREAD

**Issue by samreenadil** [a85/POSTMan-Chrome-Extension#4615]
Hi Everyone,

I have a GET request /project/{project_id}, {project_id} here is the ID created in other POST request which created project.

My requirement is that once the ID is created in POST request(create project) response - that ID can be used in the URL of the GET request.

I have set the global env variable as 
var jsonRespStore = JSON.parse(responseBody);
postman.setGlobalVariable("id", jsonRespStore.id);

but how to use this variable in the URL?

Please help

**Comment by ccaran** [comment]
If I understand what you're asking, you set the JSON response of the POST as "id" in your environment. So your GET request should be `/project/{{id}}` since that's the variable name you set it to globally. 

The syntax I use normally is `pm.environment.set("id", jsonRespStore.id); `

But if that works for you, great.

**Comment by ccaran** [comment]
Ah, the variable should work the same way as the environment set.

**Comment by samreenadil** [comment]
@ccaran it worked, Thanks so much!
