### ISSUE TITLE
Collection Runner with json data file send incorrect Request Body

### ISSUE THREAD

**Issue by kaprolitik** [a85/POSTMan-Chrome-Extension#4623]
I am use Collection Runner with JSON data file. When i run my test, it is fail. It happens because Collection Runner send my JSON data in wrong format - add quotes at the beginning and at the end.

**Steps to reproduce the behavior:**
1. Go to Collection Runner
2. Select  collection
3. Select json data file
4. Run you collection
5. Look at the Request Body in Postman Console

**Expected behavior**
Correct JSON format. 
For example:
```
{
     "password": "123",
     "login_name": "login1",
     "email": "login1@mail.com"
 }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/39767040/40720885-d30b1a98-6420-11e8-83cd-0107c741a0c9.png)

**App information (please complete the following information):**
 - Native App
 - Postman 6.1.3
 - Windown 10 x64

**Additional context**
When I send request without Collection Runner, in Request Body I see correct JSON:
![image](https://user-images.githubusercontent.com/39767040/40720968-eb8cd98a-6420-11e8-8c08-c8f5e13a0f3b.png)

It is my JSON data file:
```
[{
     "password": "123",
     "login_name": "login1",
     "email": "login1@mail.ru"
    }, 
	{
     "password": "123",
     "login_name": "login2",
     "email": "login2@mail.ru"
    }, 
	{
     "password": "123",
     "login_name": "login3",
     "email": "login3@mail.ru"
    }, 
	{
     "password": "123",
     "login_name": "login4",
     "email": "login1@mail.ru"
    }]
```

It is my request Body:
```
 {
     "password": {{password}},
     "login_name": {{login_name}},
     "email": {{email}}
 }
```

**Comment by thecuriousdev** [comment]
@kaprolitik thanks for reporting this issue, We'll look into this.

**Comment by sivcan** [comment]
@kaprolitik Kindly surround the values which are text in double quotes like so in the request body, because the JSON is invalid otherwise.

```
{
     "password": {{password}},
     "login_name": "{{login_name}}",
     "email": "{{email}}"
}
```

**Reason why it's invalid:**
Head over to: https://jsonlint.com/
Paste the following code and test it out:
```
 {
 	"password": 123,
 	"login_name": login,
 	"email": blah
 }
```

It needs to be a string or some valid type but not plain text thus the underlying parsing logic converts the whole invalid JSON to a string and sends it.

**Comment by kaprolitik** [comment]
@sivcan Look at my JSON data file! It has values in double quotes! It is correct format!
Once again I add the my JSON data file:
```
[{
     "password": "123",
     "login_name": "login1",
     "email": "login1@mail.ru"
    }, 
	{
     "password": "123",
     "login_name": "login2",
     "email": "login2@mail.ru"
    }, 
	{
     "password": "123",
     "login_name": "login3",
     "email": "login3@mail.ru"
    }, 
	{
     "password": "123",
     "login_name": "login4",
     "email": "login1@mail.ru"
    }]
```

But when Postman Collection Runner uses this data file, it removes double quotes. It is issue!

@sivcan please read my issue report carefully and completely. Your previous comment does not have any information relating to the issue.

Thank you!

**Comment by sivcan** [comment]
@kaprolitik Collection Runner is not removing any quotes from the data file.
Also, I know that your data file is correct and has the correct types.

However, 
Using '**raw**' format won't provide you with the string type when the variables are being resolved and sent to it.

Raw text = no types nothing.

Writing the following in console prints so:
![image](https://user-images.githubusercontent.com/12631777/41157514-98ca7f02-6b43-11e8-8121-92510ac21c09.png)
It's all text there, thus the **RAW FORMAT** and that's how it's going to the JSON validator.

What you need to make sure in raw format is this:
![image](https://user-images.githubusercontent.com/12631777/41157532-a9728304-6b43-11e8-9a78-a2caebcb29ba.png)

The text needs to be converted to strings and other types as required to have the JSON as valid.

Now, 
Instead of using **RAW Format** if you switch to **form-data**
Then this will work properly with your data-file without any additional work required:
![image](https://user-images.githubusercontent.com/12631777/41157961-f3a9334a-6b44-11e8-9fd7-0b6684140fc3.png)

I hope this clarifies your doubt.  🙂

**Comment by kaprolitik** [comment]
Now it's everything clear! Thank you, @sivcan

**Comment by scottdillon1** [comment]
> @kaprolitik Kindly surround the values which are text in double quotes like so in the request body, because the JSON is invalid otherwise.
> 
> ```
> {
>      "password": {{password}},
>      "login_name": "{{login_name}}",
>      "email": "{{email}}"
> }
> ```
> 
> **Reason why it's invalid:**
> Head over to: https://jsonlint.com/
> Paste the following code and test it out:
> 
> ```
>  {
>  	"password": 123,
>  	"login_name": login,
>  	"email": blah
>  }
> ```
> 
> It needs to be a string or some valid type but not plain text thus the underlying parsing logic converts the whole invalid JSON to a string and sends it.

Hmmm...I'm seeing the exact behavior as outlined above but I already have my double quotes surrounding my environment variables. Anyone have any thoughts on other things to try?
