### ISSUE TITLE
blank black screen Mac OS 10.13.4

### ISSUE THREAD

**Issue by WRCarlile** [a85/POSTMan-Chrome-Extension#4634]
After updating to Mac os 10.13.4, I am getting a blank / black screen. Postman loads but when I try and do anything else the screen goes black.

**Comment by thecuriousdev** [comment]
@WRCarlile thanks for reporting this issue. Can you help us by providing your computer spec (model, gpu, etc)?

This may be related to a known issue where Postman doesn’t launch with certain GPUs. But so far only windows users reported this issue.

- https://github.com/postmanlabs/postman-app-support/issues/4594

**Comment by WRCarlile** [comment]
![screen shot 2018-06-04 at 8 33 00 am](https://user-images.githubusercontent.com/17822226/40926799-feed3a24-67d1-11e8-9e63-c0f2f58542a4.png)

**Comment by harryi3t** [comment]
Can you try the solution posted on https://github.com/postmanlabs/postman-app-support/issues/4594

Since you are on the mac, instead of setting the variable from the UI you can just use it directly from the command line
```shell
POSTMAN_DISABLE_GPU=true /Applications/Postman.app/Contents/MacOS/Postman 
```

This will start the app with GPU turned off. For confirmation, you can look for the first line `Disabling hardware acceleration` in the console logs

If this fixes the issue then we are sure that it's a GPU issue. For a more permanent workaround, you can add the environment variable in your `~/bashrc`

**Comment by WRCarlile** [comment]
Thanks for the response. This did not seem to work for me. I can share privately what it is saying in the log if you would like.

**Comment by WRCarlile** [comment]
This could be part of the problem:
Postman Helper[] Couldn't set selectedTextBackgroundColor from default ()

**Comment by harryi3t** [comment]
@WRCarlile Sure, you can share the complete logs at harendra[at]getpostman.com
Also, if you are able to open dev tools, you can share the screenshot of that too.
It can be opened via `view -> Developer -> Show DevTools (Shared)`

**Comment by WRCarlile** [comment]
Postman is working again. Just restarted my machine and it started working again. Sorry. Thanks for the help.

**Comment by kedarnag138** [comment]
> Can you try the solution posted on #4594
> 
> Since you are on the mac, instead of setting the variable from the UI you can just use it directly from the command line
> 
> ```shell
> POSTMAN_DISABLE_GPU=true /Applications/Postman.app/Contents/MacOS/Postman 
> ```
> 
> This will start the app with GPU turned off. For confirmation, you can look for the first line `Disabling hardware acceleration` in the console logs
> 
> If this fixes the issue then we are sure that it's a GPU issue. For a more permanent workaround, you can add the environment variable in your `~/bashrc`

I have tried the above and it's the same, Postman starts and after a few seconds goes blank.
<img width="572" alt="Screenshot 2020-01-08 at 10 01 02 PM" src="https://user-images.githubusercontent.com/5475397/71983788-86532080-3262-11ea-85dd-fb85b198c14a.png">

The postman version is
<img width="264" alt="Screenshot 2020-01-08 at 10 06 49 PM" src="https://user-images.githubusercontent.com/5475397/71984133-39bc1500-3263-11ea-8a16-899172f4ae47.png">

The issue seems to be closed, was not sure to open a new one or not, if this is the wrong place, do let me know and I'll create a new issue. 
I appreciate the help.

**Comment by harryi3t** [comment]
@kedarnag138 
There is a separate GitHub ticket where the Postman UI goes blank because of the high memory usage.
Just to confirm whether you are facing the same issue, try opening the app using the following command (make sure you quit any already running Postman application)
```
/Applications/Postman.app/Contents/MacOS/Postman --user-data-path=/tmp/user1
```
This would create a new fresh directory for the user data and act as a fresh installation. If this does not work, I think we can reopen this ticket itself.

**Comment by kedarnag138** [comment]
@harryi3t Thanks. That worked. But the older instance of Postman still has the issue, so I should run the following command, every time I want to use it?

**Comment by harryi3t** [comment]
@kedarnag138 This command only changes the directory where the user data is stored (collections, requests, etc). The default location is `~/Library/Application\ Support/Postman/`

If the app is working fine with a newer location, try logging into the same account. If this recreates the issue again then it the performance issue I was talking about earlier otherwise, you can delete the original directory and then login into the original App again.
To clear the data, delete the default user data directory`~/Library/Application\ Support/Postman/`

Note: **Please make sure that all the data is already synced before doing this or just take a backup before deleting the default user data directory.**
