### ISSUE TITLE
Blank screen on Windows 10 with Postman 6.1.5

### ISSUE THREAD

**Issue by shirasuwanum** [a85/POSTMan-Chrome-Extension#4635]
After a new install of the Postman application (version 6.1.5), whenever I launch the app I get a blank screen

Steps to reproduce:

1) From a Windows 10 PC with Postman not installed, go to the Postman website and download/install the latest version of the 64-bit application (6.1.3).

Result: When the installation completes and the postman UI opens, it displays a blank screen (see the screen shot). This blank screen can be white, orange, or black, with or without the menu bar. Also, when I check Postman in Windows Task Manager, I see Postman "toggle" between 4 and 5 processes every second (4 processes, 5 processes, 4 processes, 5 processes, etc.). 

If I close Postman and re-launch using the desktop shortcut or the start-menu, the same behavior occurs. I also tried re-booting my PC before launching Postman. Same behavior.

![postman screen shot](https://user-images.githubusercontent.com/39838383/40856054-6aff649c-65a4-11e8-958c-6c26ce796920.jpg)

Expected: Postman should open it's full UI.

Application Details:
- Native App
- Postman Version 6.1.3
- OS: Windows 10

**Comment by fquirin** [comment]
same here. Happened after the latest update. Sometimes I can see the menu bar and when I can click "check for updates" and wait a while the whole screen might or might not recover when the "no new updates" pop-up appears. 

Edit: Windows 8.1 btw

Edit2: Now I've downgraded to 6.0.10, app works again but all my collections are gone :-1: :-1: :-1:

**Comment by johannesschobel** [comment]
same here with windows 8.1.x

**Comment by thecuriousdev** [comment]
This may be related to a known issue where Postman doesn’t launch with certain GPUs. A workaround for this issue involves disabling your GPU, and detailed instructions on how to do that can be found via the link below.

- https://github.com/postmanlabs/postman-app-support/issues/4594

**Comment by microcipcip** [comment]
@thecuriousdev thank you, I was having problems for two weeks! Definitely a gpu issue.

**Comment by johannesschobel** [comment]
Hey @prashantagarwal , this issue is not resolved.. The mentioned "solution" is just a workaround!

**Comment by thecuriousdev** [comment]
@johannesschobel we'll track the progress of this issue in https://github.com/postmanlabs/postman-app-support/issues/4594

**Comment by johannesschobel** [comment]
thanks for the clarification :+1:

**Comment by tid3840** [comment]
I downgraded to 5.5.3...shame on Postman team...shame shame shame

**Comment by tid3840** [comment]
I' can't believe it! I've had to downgrade to 5.5.3

**Comment by johannesschobel** [comment]
Hey @tid3840 

> tid3840
> I downgraded to 5.5.3...shame on Postman team...shame shame shame

You realize, that you got an **awesome** REST client basically **for free** and you are complaining like this? Come on.. These guys are working hard on a really awesome product, giving it away for free for the community.

Furthermore, you could provide some details / insights into how to solve this issue, how this issue emerge on your system, what your system configuration is, and so on.. This would help in - a positive way - to resolve this behaviour. However, you are criticising and attacking the team. If I were you, I would highly consider rethinking your statements, as this is not fair...

However, if you don't like the application (any more), you may still switch to another application, there are plenty other REST clients out there. Feel free to switch..

**Edit 01**
wow, you removed your comment and added a new one, so others are not able to track your statement in the "edit" feature..

**Comment by tid3840** [comment]
...and they are not testing on windows 10 or 8?

**Comment by johannesschobel** [comment]
you realize that this is a GPU problem, right? So this is not specifically bound to a particular OS, but rather to a hardware configuration.. 

Again, there are a few options for you:
1) help finding / dealing with the bug <-- this is the preferred option
2) do nothing and wait till it is fixed and continue with a version that works for you
3) search for another REST client and move on

**Comment by tid3840** [comment]
Yes i realize that...i think it’s a very common scenario anyway

 

Also difficult to find the version to downgrade to, at least for me..

 

It would have been enough clearly indicate to downgrade among the options available instead of pointing out only the workaround and nobody would have lost hours on this

 

Are you accusing me of exploiting the fact its’ free….you get the wrong guy: all my software is licensed and the fact that is free doesn’t justify anything.

 

I will stick to 5.5.3 for a lot before taking any chance to update again

 

If I can contribute with money to any improvement I would be happy to do so

 

My best regards

**Comment by microcipcip** [comment]
@tid3840 it takes 5 minutes to apply the fix. Basically less time than complaining in this thread.

**Comment by tid3840** [comment]
Oh you are very intelligent indeed...

I’m nothing compared with you

I deeply regret to have bumped into this bug and the community is always on the right

Thank you again very much

My best regards and wished of good luck

**Comment by microcipcip** [comment]
@tid3840 is a 4 steps process. [Here are the steps](https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621). Apply it and you'll be able to use the new version of Postman. Happy coding :)

**Comment by tid3840** [comment]
Thank you very much

 

But once i’ve found the old version i downgraded and sorted out immediately

 

I took more that 1 hour because just approach the idea of workaround  because before finding the post with the workaround I tried many times to disinstall/install…

 

So it took far more than few minutes.

 

I’m happy now with the solution I’ve found

 

I see also there are guys that reply instantly to comments and have posted the original comment (on the spur of the moment) that I’ve changed BEFORE receiving any mail..the comment suggests that I would have changed it to avoid others to comment…no it’s not like that.



I wonder how fair (and LEGAL?)it is..that comment was changed and I think quoting previous version  is not properly correct. On what right do you do that?

 

Regards

 

Best luck to everybody

**Comment by microcipcip** [comment]
@tid3840 I'd apply the fix anyway because from time to time postman asks you to upgrade and if you upgrade by mistake you get the error back, also, is [just 4 easy steps](https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621).

**Comment by michaelmpschubert** [comment]
Same issue for me with Postman Postman-win64-6.2.2 on Windows 10 Pro.
Running the app with Windows 8 Compatibility under Win 10 Pro 64 Bit helped for me.

**Comment by m3dbedb** [comment]
Same issue with postman 32 bit 6.3.5 on windows 7 32bit and intel hd 2000 (driver version 9.17.10.4229), the workout with systen parameter doesn't help.
