### ISSUE TITLE
Ability to remove all collections/environments

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#4660]
It would be great to have the ability to delete all collections or environments at once

**Comment by dhineshwiz** [comment]
hey @zhak thanks for feature request, will add it as feature request.

**Comment by a85** [comment]
Why exactly is this needed?

**Comment by ghost** [comment]
@a85 the list of collections and environments can grow over time making it difficult to navigate among them. Having a project with dozens of different collections (over 1500 test cases at the moment) it may sometimes be useful to import them all for debugging and maintenance or import one-by-one or only a couple of them. So, cleaning postman fast is a great speed-up for work activities rather than scrolling collections up and down or keep pressing [Backspace], [Enter] to get rid of them

**Comment by a85** [comment]
@zhak Have you tried using Workspaces? You can segment your collections or just create a new workspace when you want to create new collections.

**Comment by ghost** [comment]
@a85 several people are working on Postman automation scripts and all collections and environments are stored in a bitbucket repository, so need to re-import collections from time to time. Workspaces don't seem to be helpful with this

**Comment by ahakanbaba** [comment]
see #1014

**Comment by a85** [comment]
There are no plans for this feature now or in the near future.

**Comment by gunters63** [comment]
We need to do that very often, out of the same reasons as zhak.

A quick and dirty solution seems to be to delete this folder: 
`%APPDATA%\Postman\IndexedDB `

**Comment by brandonforster** [comment]
Anyone know where this data is stored on macOS since the devs don't like us?

**Comment by atljoseph** [comment]
i made a golang program that generates env config files on the fly and i import these with the folder import feature. why would you make me (or other avid users) go through and remove obsolete env files that have been regenerated one by one? there are hundreds - for support

**Comment by atljoseph** [comment]
Better yet, why in the world do you guys allow multiple envs with the same ID? What is even the point of the ID? If I import an env with the same ID, as a developer, I would expect you product to overwrite (or at least prompt for an overwrite) the previous env version.

**Comment by atljoseph** [comment]
Furthermore, why does it not import the envs with modified names, like "cupcake", then "cupcake (1)"?

**Comment by a13a** [comment]
> Anyone know where this data is stored on macOS since the devs don't like us?

It's in ~/Library/Application Support/Postman/IndexedDB

**Comment by theon** [comment]
> > Anyone know where this data is stored on macOS since the devs don't like us?
> 
> It's in ~/Library/Application Support/Postman/IndexedDB

Not sure if this has moved recently, but mine was under `/Partitions` in a UUID directory. E.g.

```
~/Library/Application Support/Postman/Partitions/db212a2d-ab2d-7d49-ca21-c2ca337a7aa9a/IndexedDB
```

**Comment by floriankraemer** [comment]
We have several huge collections and I would like to clean all of them up from Postman *without* having to click over 100 times the confirm dialogue... This is horribly annoying and I don't understand why this is not getting implemented. Several people request this feature for years. Maybe someone can recommend a similar tool that can do that?

**Comment by shanujha** [comment]
Just to let new viewer's know, If you have a Cloud/Synced account, deleting the IndexedDB route may not delete your collections permanently...

**Comment by tpiecora** [comment]
You should fix this.  If you do frequent imports/exports with a bunch of environments, this is pretty obnoxious.  I spend more time doing cleanup than actual work in postman.  Having to blow away some directory is not a real solution.  This is an old issue.  "There are no plans for this feature now or in the near future." - over 2 years ago.  Please put this on the roadmap. 🙏

**Comment by caligo-erik** [comment]
I bumped into this.
I have plenty of collections and environments in My Workspace. I tried adding a new workspace and deleting the old one, action not permitted.
Please add a way to multi-select and delete collections and environments.

**Comment by atljoseph** [comment]
I have over 100 envs in postman, and the UI is super slow to search them in hopes of deleting one in preparation for importing another. This is required because postman does not replace a env, but makes a duplicate, even with an identical uuid defined in the file. 

Have also ran into the issue of not being able to delete an env, usually because using the Teams function in coordination with synced envs, which is also annoying. 

It is just an all around annoying product that works just ok for my purposes (and others apparently), and I cannot understand why the postman team would not just allow you to nuke all envs and reimport them. I guess they are happy the software is being used…?

Having a reliable folder in which the envs reside is also useful, but nothing has been provided for this either. Not even a link from the app to open such folder in Finder, etc.

**Comment by a13a** [comment]
A workaround could be to make a script that would connect to Postman DB and delete specific collections/environments.

**Comment by tcartwright** [comment]
+1 on this. I know this is old, but I have a need for this as well. I dont even need it added to the UI, if I could just script it. 

Or damn, just being able to multi select in the environments tab to delete. PLEASE.

**Comment by tcartwright** [comment]
I would love for the devs to try deleting a couple hundred environments, and tell me this feature is not needed. Clicking confirm on each one, and then the scroll bar bounces around and you lose your spot each time? It is pretty infuriating.

**Comment by tcartwright** [comment]
My workaround since I am on a cloud account: 

- Export EVERYTHING (collections / globals / mock servers / flows / etc,,, )
- Create new workspace
- Import everything exported before
- Import new / updated environments
- After verifying new workspace is good, then delete old workspace and rename new one

**Comment by atljoseph** [comment]
I think they want us to use a different product. Like reverse advertising.

Sep 7, 2022 5:14:51 PM Tim Cartwright ***@***.***>:

> My workaround since I am on a cloud account:
> 
* > Export EVERYTHING (collections / globals / mock servers / flows / etc,,, )
* > Create new workspace
* > Import everything exported before
* > Import new / updated environments
* > After verifying new workspace is good, then delete old workspace and rename new one

**Comment by sprive** [comment]
**+1**.  The ability to multi-delete objects is standard (completely expected by end users).  

An enterprise's Compliance dept. is not going to grant a Compliance exception (to store their company data in your cloud).

Your stance of requiring Workspaces be used will just fuel interest in migration to Hopscotch or standard Python scripts. I'm not suggesting you can't charge money, just that you shouldn't try to make people use a feature that stores data in your cloud.

(**Related: **  The issue  _"Switch to a Workspace"_ startup banner, that could not be permanently dismissed... you give the same answer: _"You can get rid of the banner if you just used Workspaces"_. No... we... _can't_.)

**Comment by xchopin** [comment]
Companies don't want the workspace due to data leaks. Importing environments doesn't ask you to replace the existing ones therefore you get a ton of environments and have to click everything to delete worse UX ever fr

**Comment by simonevratogna-cpu** [comment]
@a85, after so many years, is there any hope that the team has changed its mind? 👼 
Apparently, it's something that's pretty demanded :)

**Comment by sprive** [comment]
The way Postman handles feature requests and issues should tell you all you need to know.  You made Postman popular, now they got your company to purchase site licensing. That means users aren't the customer anymore. The real customer is your management.

So now when you ask your company to use an alternative to Postman, they may at first say _"We're already paying for Postman"_.  Pushing back on that relationship is uphill.

If you want approval to use "something else", try this:
1. show your Compliance/Security team that Postman **requires** cloud login, and (by default) it will **automatically sync all your passwords and secrets into their cloud.**  
2. **_Now_** there will be serious interest in Postman alternatives, because your company policy does not want secrets handled so carelessly..
3.  ...just TRY to choose a tool that's Open Source, it doesn't have to be perfect, it just has to have a lot of GH stars and users, so you know it will always get better. 
5.  (if you focus on finding something that's merely "free as in cost", but not open source, that will just set you up for a repeat experience what happened to Postman.  Take a look at Restfox or Insomnia).
