### ISSUE TITLE
Have the console window show up a tab with in the Postman App

### ISSUE THREAD

**Issue by angamardhana** [a85/POSTMan-Chrome-Extension#4667]
Problem : 
When testing my scripts, it is frustrating to have to switch to a new window to look at the console every time I run scripts. 
I have other apps open at the same time that need to be on (like Slack, Web browser etc).

It would be great to have the console show up as a tab right next to the "Tests" tab or before the "Authorization" tab  (right below the where the URL of the Request is) 
This is similar to how the Dev Tools work in the Chrome browser where the console is integrated into the main window.

**Comment by prashantagarwal** [comment]
@angamardhana We are doing a lot of refactoring around tabs which should make this a possibility in future.

**Comment by angamardhana** [comment]
Awesome.

Thanks.

- jay

**Comment by matheusmota** [comment]
Any update on this? It would be great to have it all in multiple tabs. 
It is really frustrating to have to keep switching windows while debugging.

Thanks

**Comment by just-Bri** [comment]
+1 for this idea. Just have it open up in the side bar, or a 3 pane view.
Having it in a separate window is a frustrating design.

**Comment by reloxx13** [comment]
nevermind , canary works fine, thank you!

**Comment by coditva** [comment]
Hey @reloxx13 you're in luck because we just pushed an experimental UI change to [Postman Canary](https://www.postman.com/downloads/canary/) which we hope will help you navigate in between different panes. Please try it out and let us know what you think either here or on [our community forum](https://community.postman.com/t/new-layout-in-postman-canary/13450).

Here's a quick preview:

![84889240-77ce2800-b090-11ea-9fd5-7a0bb38a094e](https://user-images.githubusercontent.com/8445768/86112194-49673880-bae5-11ea-81bc-1c5c031508eb.gif)

**Comment by coditva** [comment]
This change is now available in Postman 7.28.0 as well 🎉
