### ISSUE TITLE
Need a function like console.clear() in the Postman App

### ISSUE THREAD

**Issue by angamardhana** [a85/POSTMan-Chrome-Extension#4690]
I almost always clear the console when running a new script otherwise I'm having to scroll past a lot of old output to find mine.

It would be great if I could have a command to clear the console. That way I could add that at the beginning of my scripts so that I clear the console before even starting up any of the tests.

**Comment by vkaegis** [comment]
@angamardhana Thanks for the input! This would be a nifty feature to have while we work on usability improvements around the console. No ETA on this just yet, but we'll keep you updated.

**Comment by leonsegal** [comment]
I would love to see this feature!

**Comment by gototester** [comment]
I would love this feature too,

**Comment by yuvalevr** [comment]
I would love to see this feature!

**Comment by Tom-spec113** [comment]
would love to see this feature too..

**Comment by ghost** [comment]
This would be a great addition. 👍

**Comment by karlitos** [comment]
Please add this feature!

**Comment by mamuesp** [comment]
Oh yes ... stumbled upon "console.clear() is not a function ..." ;-)

**Comment by ygorats** [comment]
Would be so hard to create a console function that executes the same job of an existing button?

**Comment by shamasis** [comment]
@vkaegis this needs to be addressed via better filtering and scoping of console output. The clear philosophy does not apply to Postman Console since independent components output to same console.

**Comment by hyperclick** [comment]
I also vote for this feature

**Comment by YemYigit** [comment]
Sometimes previous logs can be pain in the ass. Please define console.clear() function. Thanks

**Comment by xaviergm** [comment]
Upvoted! I think this would be super useful.

**Comment by a85** [comment]
There is a clear button on the top now to clear existing messages.

**Comment by xaviergm** [comment]
> There is a clear button on the top now to clear existing messages.

Indeed... however, when starting a test script that includes multiple requests, it would be nice to have the possibility to call console.clear() on the pre-request script of the first request so that the console is clean for that test run and one does not have to manually clear the console every time...

**Comment by mohanadElmaghrby1** [comment]
I think this would be a great feature.

**Comment by Aeroverra** [comment]
Definitely need this QOL update!

**Comment by mcmessina** [comment]
In the interim, duplicating the tab and deleting the original tab is another way to clear your console.

Just right-click your tab and select "Duplicate Tab"

**Comment by xaviergm** [comment]
> In the interim, duplicating the tab and deleting the original tab is another way to clear your console.
> 
> Just right-click your tab and select "Duplicate Tab"

How is this simpler than the existing clear button?

**Comment by ritwijsinha** [comment]
> In the interim, duplicating the tab and deleting the original tab is another way to clear your console.
> 
> Just right-click your tab and select "Duplicate Tab"

I'm unable to reproduce this on my system. Could you help me with the exact steps you're following to clear your Postman Console this way?

**Comment by pherold0923** [comment]
As an alternative to clear the console, it would be nice to just programatically suppress console logging. For example, authentication requests that require a password (OAuth2) to get a token--the password shows up in the console (in the clear). This can't be that hard.

**Comment by sabuncu** [comment]
> 
> 
> > In the interim, duplicating the tab and deleting the original tab is another way to clear your console.
> > Just right-click your tab and select "Duplicate Tab"
> 
> I'm unable to reproduce this on my system. Could you help me with the exact steps you're following to clear your Postman Console this way?

Right click on a tab and select "Duplicate Tab".  The new tab will only have the request, and the response panel will be empty.

![2020-06-04 15_14_09-Postman](https://user-images.githubusercontent.com/6242253/83755657-8ec75000-a676-11ea-8d1f-ef3ce4704f34.png)

**Comment by xaviergm** [comment]
> Right click on a tab and select "Duplicate Tab". The new tab will only have the request, and the response panel will be empty.

The response panel is not the console. The console we are discussing in this thread is the additional window that comes up if you go to View >> Show Postman Console or press CTRL+ALT+C.

**Comment by jbh999** [comment]
### **`UPVOTE`**

**Comment by milost1982** [comment]
Is this implemented yet?

**Comment by georgetfeghali** [comment]
Hi, this would be really useful if implemented.
Any updates on its status?

**Comment by lflucasferreira** [comment]
It looks like nobody cares... so simple to create a method `.clear()`.

**Comment by giridharvc7** [comment]
We are not implementing this for now, we will be taking this later in the future. 
Please use the Keyboard shortcut - Cmd + Shift + K or the clear button in the console for now.

**Comment by spacentime** [comment]
I would love to have that feature too.

**Comment by leonsegal** [comment]
> We are not implementing this for now, we will be taking this later in the future.
> Please use the Keyboard shortcut - Cmd + Shift + K or the clear button in the console for now.

could l make a request that the keyboard shortcut be ctrl + L, the same as in bash terminals and the browser?

**Comment by Jagadeesh19** [comment]
I would love to have this feature too.

**Comment by rmushfiqur2** [comment]
I would love to have this feature too.

**Comment by noskcaja-gmail** [comment]
Hi there, I just found that I'd love this feature too please.

**Comment by mbraidy** [comment]
console.clear() should be great

**Comment by hnariman** [comment]
support for console.clear() would be perfect.

**Comment by martinsbrn** [comment]
still waiting...

**Comment by ashutosh049** [comment]
Dead silence... Any update on `console.clear()` ?

**Comment by vieiraes** [comment]
happy 4 years of a super-useful feature required without updates!
congrats Postman community team!

**Comment by Kos-UlpiaTech** [comment]
I also need the feature.

**Comment by ferryarman** [comment]
Vote +1 for `console.clear()`

**Comment by 27shutterclicks** [comment]
Vote +1 for console.clear()

**Comment by vdespa** [comment]
@vkaegis

It seems that this feature has a relatively high user support and "appears" to be easy to implement. Could you maybe share more details on why this has not been considered yet? Maybe it is a great idea that has just been forgotten since 2018. Thanks.

**Comment by 27shutterclicks** [comment]
To add a few more details:

Right now, my time in Postman is spent between coding tests, running collections and clearing the console.

Scenario (where I usually have the console in a separate window on my second screen):

- Type some code that outputs to console.
- Alt Tab to console window
- Press Clear or use Ctrl+Shift+K hotkey
- Alt Tab again to Postman window
- Run Collection or Send request
- Repeat all the window switching and clearing for next changes in code and console output

This is needed because often the console contains many errors and it's hard to distinguish the errors of one send or run from those of the next, even when using a console separator for some visual help: `console.log('--'.repeat('25'));`

If anything, it would be useful if the default Ctrl+Shift+K hotkey for clearing the console would clear the only console open, which is the one open in a window on my second screen. Right now, it doesn't do anything if the console of my main Postman windows is closed/hidden.

I don't know the considerations for which this hasn't been implemented yet, but as an idea, the `console.clear();` feature could be implemented similarly to how **Terminal** and **Test Summary** work in Flows, where a _group_ can be specified (and consequently filtered).

So if you have a console setup where:

- Main console in the main Postman window is used/filtered to show only `console.log` and `console.error` output
- The secondary window console is filtered only for `console.info` 

Then you could control which console should be cleared using something like `console.clear("main")` or `console.clear("secondary")` (since you can't seem to have more than one windowed console anyway).

I'd be happy to create mockups for this, if needed.

**Comment by bwen1** [comment]
+1 for console.clear()

**Comment by bobmixon** [comment]
+1 for console.clear();

**Comment by 27shutterclicks** [comment]
IS 

> > In the interim, duplicating the tab and deleting the original tab is another way to clear your console.
> > Just right-click your tab and select "Duplicate Tab"
> 
> How is this simpler than the existing clear button?

It is simpler since you wouldn't have to click the clear button. Less clicks = simpler. Is that simple enough to understand?

**Comment by sclavijo93** [comment]
+1 for console.clear();

**Comment by AlexDubel** [comment]
+1 for consoile.clear();

**Comment by EzeGmnz** [comment]
+1 for console.clear() 🧹

**Comment by kranthirokula** [comment]
This would be very helpful!

**Comment by Mds92** [comment]
It would be great
`console.clear()`

**Comment by semioz** [comment]
+1 for console.clear() this would be really useful.

**Comment by sathishkumar-thangavel11** [comment]
Thank you everyone for your patience, **console.clear()** is now available in postman from v10.6. With this new method Postman console can be cleared in pre-request & test scripts programatically. Do let us know your feedback ! 

![console-clear](https://user-images.githubusercontent.com/111063699/207233925-d9a07164-f465-46ca-b90b-267d13f81b30.png)

**PS** : Postman app v10.6 is being rolled out will be available for everyone in couple of days

**Comment by gototester** [comment]
Thanks so much for this.  I’ve been waiting a long time for it, I thought it wasn’t going to happen.  So glad it has though. Thanks again.
