### ISSUE TITLE
Post - form-data - Need to be able to programatically disable Key pairs during "Pre-request Script"

### ISSUE THREAD

**Issue by BrianKilby** [a85/POSTMan-Chrome-Extension#4693]
When using "Postman v6.1.3" (the latest version), we need to be able to programmatically disable Key pairs during "Pre-request Script" for Post - form-data - requests.  Further, we would like to be able to add/delete Key pairs during the "Pre-request Script".

![key fields for a post form-data request](https://user-images.githubusercontent.com/31317573/41385840-194d7cfe-6f4c-11e8-9654-f9d2f17b894e.png)

**Comment by shamasis** [comment]
Closing this and tracking it here https://github.com/postmanlabs/postman-app-support/issues/4808

We added mutating URLs and headers for requests ... mutating other parts like auth and body (to some extent) would follow in short to mid term. :-) Meanwhile, in UI we need to have ways to see what exactly was sent (since programmatic changes are hard to spot.)

**Comment by codenirvana** [comment]
**Postman v8.3.0** added support for programmatically mutating the request body.

The following `pre-request` script will  remove/disable a form-param programmatically:
```js
pm.request.body.formdata.remove('FirstName');
```

**Comment by jshearin01** [comment]
When I call "pm.request.body.formdata.remove(key);" I get "TypeError: Cannot read properties of undefined (reading 'remove')
"

**Comment by shubhbhargav** [comment]
@jshearin01 Can you please share the request / collection with us to help debug this further? You can share the same via email: help@postman.com
