### ISSUE TITLE
HTTP method dropdown stuck

### ISSUE THREAD

**Issue by shalvah** [a85/POSTMan-Chrome-Extension#4712]
The dropdown for selecting HTTP method for the request unfurls upwards and stops at the window title bar, so only a few options are shown. It isn't scrollable with mouse or arrow keys.

**To Reproduce**
1. Open Postman
2. Click on the dropdown to select a method

**Screenshot**
![image](https://user-images.githubusercontent.com/14361073/41500301-beea4048-7186-11e8-87b5-f2aa151be385.png)

**App information (please complete the following information):**
 - App Type: native app
 - Postman Version: 6.1.3
 - OS: Windows 10

**Comment by prashantagarwal** [comment]
@shalvah Thanks for reporting this. We have already fixed this internally and will release it sometime next week. This dropdown was behaving this way if it doesn't have enough space at the bottom to open. By any chance are you zoomed in or have small window height. One thing you can do right now to unblock your self is zoom out  so that this dropdown fits in the window.

**Comment by shalvah** [comment]
@prashantagarwal Thanks. I'm not zoomed in. My screen scaling is at 125% though, so it has a similar effect to zooming. Zooming out manually fixes things for now.

**Comment by sunjayaali** [comment]
temporary workround, just hit f11 for full screen,

**Comment by prashantagarwal** [comment]
Hey guys we have released the fix on our canary apps. You can download it from https://www.getpostman.com/canary
