### ISSUE TITLE
Environment Variable Quick look does not show the current variable

### ISSUE THREAD

**Issue by schellem** [a85/POSTMan-Chrome-Extension#4732]
I have a a 'local' environment variable defined but when I click the eye, 'Environment quick look', button it does not show the variable defined, see attachment. I can click edit and it opens the current environment variable in the list for editing and after this the 'eye' lists variables as expected. 

Closing Postman and reopening does not reproduce but I have seen this multiple times now and am thinking it happens after a restart.

Running latest Win 10

![image](https://user-images.githubusercontent.com/5617425/41851908-7661a212-7857-11e8-8233-01934483fc31.png)

**Comment by sivcan** [comment]
@schellem Thanks for reporting this.
We apologize for the inconvenience caused. 
We're aware of this issue and have fixed this internally.

It happens once you restart the app, you've to manually select the environment again from the dropdown and then it'll work as expected.

I'll update this thread once the fix is released.

**Comment by sivcan** [comment]
@schellem Follow this thread for updates regarding this issue https://github.com/postmanlabs/postman-app-support/issues/4696

Closing this.
