### ISSUE TITLE
Collection runner goes blank on 6.1.4

### ISSUE THREAD

**Issue by tlair123** [a85/POSTMan-Chrome-Extension#4747]
When I open collection runner, the screen shows about 10 seconds and then go blank.
when I close and reopen it, it starts blank.

My software just upgraded itself to 6.1.4.
On 6.1.3 it would take a minute to load, but then be stable.  I preferred slow and stable to fast and unstable.

I had this on postman itself, but I found 4595 and followed the instructions to add a variable.

**Comment by science695** [comment]
On linux (ubuntu 18.04) Postman just updated to 6.1.4 and now will not sync.

I looked at the dev console, and saw "Migration bailed out due to: EXCEEDED_ATTEMPT"

<details>
<summary>
Click to expand Full log.
</summary>
vendor-shared.js:79265 Initializing the global config
vendor-shared.js:84988 Initializing settings
vendor-shared.js:79324 Booting waterline models
vendor-shared.js:137754 Object "Successful ORM initialization"
shared.js:353 Migration bailed out due to: EXCEEDED_ATTEMPT
(anonymous) @ shared.js:353
sails.io.js:142 🌏 sync service connectivity initiated
shared.js:5657 authenticating socket for 2675370 true
shared.js:5673 sign in bailed. force connect.
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 connected to sync service.
shared.js:5657 authenticating socket for 2675370 true
shared.js:5711 session create
sails.io.js:142 🌏 connected to sync service.
sails.io.js:759 socket replaying queued commands
shared.js:5657 authenticating socket for 2675370 true
shared.js:5698 sign in bailed. in progress.
vendor-shared.js:97421 Sync Request: /v2/session/create
vendor-shared.js:97425 Sync Request: Object
vendor-shared.js:97426 Sync Response: Object
shared.js:5951 already bootstrapped for this user. skipping bootstrap.
vendor-shared.js:97421 Sync Request: /v2/session/sync?since_id=4192330349&sync_timestamp=1530198423629&changeset=false
vendor-shared.js:97425 Sync Request: Object
vendor-shared.js:97426 Sync Response: Object
shared.js:5017 Sync manager listening to bootstrapUser event Object
modelEvents.subscribe.payload @ shared.js:5017
shared.js:5657 authenticating socket for 2675370 true
shared.js:5673 sign in bailed. force connect.
sails.io.js:142 🌏 force disconnecting from sync service.
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 connected to sync service.
sails.io.js:759 socket replaying queued commands
shared.js:5657 authenticating socket for 2675370 true
shared.js:5711 session create
shared.js:11115 populated workspace Object
shared.js:6258 history:import:0b615388-9308-4e5d-b2d3-6fd56b7ca6c4
vendor-shared.js:97421 Sync Request: /v2/session/create
vendor-shared.js:97425 Sync Request: Object
vendor-shared.js:97426 Sync Response: Object
shared.js:5951 already bootstrapped for this user. skipping bootstrap.
vendor-shared.js:97421 Sync Request: /v2/history?workspace=f7ad1b1a-52c4-4c17-8a8a-2dc8efb0d8b4
vendor-shared.js:97425 Sync Request: Object
vendor-shared.js:97426 Sync Response: Object
shared.js:7264 removing changesets from sync client Array(1)
vendor-shared.js:97421 Sync Request: /v2/session/sync?since_id=4192330349&sync_timestamp=1530198613&changeset=false
vendor-shared.js:97425 Sync Request: Object
vendor-shared.js:97426 Sync Response: Object
shared.js:6258 history:import:50dd8998-26fc-4603-81ca-5ca94ac36b8f
shared.js:11115 populated workspace Object
shared.js:6258 history:import:50dd8998-26fc-4603-81ca-5ca94ac36b8f
vendor-shared.js:97421 Sync Request: /v2/history?workspace=f7ad1b1a-52c4-4c17-8a8a-2dc8efb0d8b4
vendor-shared.js:97425 Sync Request: Object
vendor-shared.js:97426 Sync Response: Object
shared.js:7264 removing changesets from sync client Array(1)
shared.js:6258 request:import:71751991-976a-47c9-8854-3ee695c4aabe
vendor-shared.js:97421 Sync Request: /v2/history?workspace=f7ad1b1a-52c4-4c17-8a8a-2dc8efb0d8b4
vendor-shared.js:97425 Sync Request: Object
vendor-shared.js:97426 Sync Response: Object
shared.js:7011 retryable changeset failed. dropping changeset Object
__WEBPACK_IMPORTED_MODULE_5_async___default.a.retry @ shared.js:7011
shared.js:7264 removing changesets from sync client Array(1)
vendor-shared.js:97421 Sync Request: /v2/request/import?owner=2675370
vendor-shared.js:97425 Sync Request: Object
vendor-shared.js:97426 Sync Response: Object
shared.js:7011 retryable changeset failed. dropping changeset Object
__WEBPACK_IMPORTED_MODULE_5_async___default.a.retry @ shared.js:7011
shared.js:7264 removing changesets from sync client Array(1)
vendor-shared.js:97421 Sync Request: /v2/notification?count=10
vendor-shared.js:97425 Sync Request: Object
vendor-shared.js:97426 Sync Response: Object
vendor-shared.js:97421 Sync Request: /v2/workspace
vendor-shared.js:97425 Sync Request: Object
vendor-shared.js:97426 Sync Response: Array(3)
</details>

**Comment by science695** [comment]
It will now sync, looks like you fixed something serverside. Thanks!

@tlair123, is your issue still happening?

**Comment by tlair123** [comment]
It is working now.  I uninstalled the software and reinstalled from 2 versions ago.  I lost everything because the sync wouldn’t work.  And it still went blank.
And then an hour later everything showed up, and the screen doesn’t go blank anymore.  I wish I could take credit.

Thanks

Tom Lair
Senior Business Systems Analyst, Buyer Management
708-492-7918

Insurance Auto Auctions  IAAI.COM
Two Westbrook Corporate Center, Suite 500
Westchester, IL 60154

**Comment by prashantagarwal** [comment]
@science695 @tlair123 I am closing this issue. Let me know if you encounter this again.
