### ISSUE TITLE
Postman crashes or hangs while handling large responses.

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#4751]
This is a master issue to collate and track multiple issues with handling large responses in Postman. Known symptoms are from sluggish performance, app windows turning white/black/blank, or the app quitting or crashing.

This is a known issue and we are looking into making core changes in the app to support large responses.

**Comment by Postman-Gabriel** [comment]
I have found reports of this problem specifically pertaining to requests running with NULL values for parameters or headers. One of our users has devised the following work-around. It isn't super useful, as it removes Null values but it still causes runner to lag less if this is your issue.

MyGlobalFunc = {

NullEmpty: function (desc, jsonValue) {

if (jsonValue === null){

cleanValue = "";

}

else {

cleanValue = jsonValue;

}

console.log(desc, jsonValue, cleanValue);

return cleanValue;

}

};

**Comment by Postman-Gabriel** [comment]
I have heard more reports from large request bodies causing the entire app to freeze with a CPU loop

![](https://postman.zendesk.com/attachments/token/TyQcQU8phizci8eToveeO9app/?name=image005.jpg)

The response comes out looking like this

This occurs on the most updated Canary build

**Comment by pegknell** [comment]
Postman app v6.3.0 is very slow to respond to simple copy/paste into Body. When actually send the call, it is also very slow (approximately 30-60 seconds before response is returned). Almost unusable at this point.

**Comment by schlingding** [comment]
Is there a workaround for this issue? I have a 250MB response which does not need to be parsed and displayed. Is there a way to toggle off response parsing?

**Comment by florton** [comment]
Switching to the 'Headers' tab in the response before sending seems to avoid some of the slowdown. As long you you don't open the response 'Body' tab it shouldn't be quite as bad.

**Comment by TehBakker** [comment]
Same issue with setting up global variable with base64 large value.
I can't even browse my variable anymore ...
But if I put the very large base64 in my body, it make the json unreadable ...

**Comment by cmac3333** [comment]
Is there any update on the progress of this issue with large responses even without parsing the results?  This is limiting our use.  Thanks.

**Comment by gctmadhumitha** [comment]
Same here... I can no longer use it... it  just froze.. Any updates?

**Comment by ericflynn67** [comment]
I've narrowed down this problem further. It seems that if the HTTP response has a really long line in it that wraps over hundreds display lines in the scrolling view, the app gets sluggish once the start of this wrapping line is scrolled up some distance past the top of the scrolling view.

**Comment by jzabroski** [comment]
@ericflynn67 I don't think that is the issue.  See #3216 - the issue is the fact they appear to be using Facebook's Immutable.js collection library viz a viz React.js, which keeps creating copies every time an item is appended to a collection.  Eventually, the application runs out of memory and crashes.

I'm not an expert in React or Immutable.js, but most data binding libraries have this kind of snowball performance issue and side-step it by turning off change tracking or allowing batch update to collections.  I've been programming for 20 years and those are always the 2 solutions to this problem, so @kamalaknn  please advise on when this can get fixed.

**Comment by jzabroski** [comment]
As I've posted previously and now been waiting for over 2 months for a fix or some direction on this-

Here is a quick C# repro for ASP.NET MVC Core, which demonstrates the performance issue *trivially* - if you cannot figure out what the problem is given this simple example, then I think I need to look for a different tool:

```csharp
var months = 12;
var daysPerMonth = 30;
var minutesPerHour = 60;
var hoursPerDay = 24;
var totalMinutes = months * daysPerMonth * minutesPerHour * hoursPerDay;

Ok(
	Enumerable.Range(0, totalMinutes)
		.Select(i =>
			new
			{
				StartDate = new DateTimeOffset(2017, 1, 1, 0, 0, 0, TimeSpan.Zero).AddMinutes(i),
				EndDate = new DateTimeOffset(2017, 1, 1, 0, 0, 0, TimeSpan.Zero).AddMinutes(i + 1)
			})
);
```

**Comment by jzabroski** [comment]
Any update on this?

**Comment by ddarren** [comment]
Not sure how Postman prioritizes it's features/bugs, but just thought I throw my vote in here to get this fixed. I'm a paying customer and use Postman almost on a daily basis. Great product, and this has been the only limiting factor for me. Would love to get some feedback on the timeline for this.

**Comment by jzabroski** [comment]
@numaanashraf  I've been waiting on a fix for this SINCE NOVEMBER.  Not only that, but I told you EXACTLY how to reproduce the issue and a (guess as to) EXACTLY THE ROOT CAUSE - you're almost certainly using React.js and Facebook's Immutable.js and adding collections to a library and redrawing the React scene DOM on every Add operation - this should be TRIVIAL for any engineer to fix.  Not trying to be a jerk, but what exactly do you need from us to solve this issue?

**Comment by schwarcu** [comment]
Same issue here. Is there any fix coming?

**Comment by raphokafor** [comment]
having this issue now, any fix in the pipeline? PR?

**Comment by schwarcu** [comment]
Nope

**Comment by koreem** [comment]
Same issue

**Comment by hinkjus32** [comment]
+1 for same issue, looking for ETA on fixes or workarounds?

**Comment by Rob-DeRosia** [comment]
This is blocking the scripting for our larger response endpoints. I would really like to be able to automate some of them, but this issue is in our way.

**Comment by shamasis** [comment]
Like the rest of our product, we are working hard to support features that enable our community be able to use Postman to send any and every request.

As a fellow developer, I can understand the pain of building something and when it becomes big, having to deal with its design and architecture quirks that are unique to the project you’re working on. Let me put down my own thoughts having worked on the project myself around some aspects that are unique to the codebase of Postman App. This is a bit long, so please bear with me. 😊

1. Server responds using a stream in chunks and the chunks are accumulated in a buffer and then the buffer is converted to a string.

2. This part of reconstitution of stream is not done by us using any third party tool, but instead done using our own code and assisting open source libraries within our postman-runtime project. We need to do this so that we can get low level control on the response to extract details from the response and also to not be limited by opinionated implementation of HTTP clients (we are still limited by NodeJS to some extent though.)

3. There are aspects of character decoding and other aspects while composing the response string. 

4. Since Postman’s early days, the response is sent to the scripting sandbox (test scripts) as a string. Which means, unless the entire response string is reconstituted, we cannot start executing the script without breaking behaviour.

5. Now, since decoding and reconstitution has happened at such an early stage, it is no longer straightforward to transfer this huge response through IPC boundaries and into the view layer (react and others like mentioned in this thread.)


This is what I’m thinking as a solution, but it is yet to be properly vetted through product teams and hence the caution that ETA isn’t clear. 

- Send raw stream in chunks to view. It will give a perceived feeling of early response, but would not be fully usable response until full response downloads.

- Use disk storage to store large response in a temporary buffer for the view so that scrolling works and view loads only partial data. That requires quite a bit of decoupling work needed in our response view component and rest of UI.

- Optionally, if user opts in, run test script without response body and instead expose the underlying stream in test script to access body. (This definitely makes it very non intuitive for maximum use cases and that’s why the opt-in step.)

- Restructure entire codebase around collections to be able to set these large responses to not be eligible for saving in collection. 

Hope I was able to help express what’s adding to the delay of this feature from a technical standpoint. Having said that, we are slowly inching towards decoupling appropriate parts of our response view code areas so that it is made significantly easier when we allot this in roadmap.

**Comment by jzabroski** [comment]
Hi @shamasis 
Thanks for the thoughtful reply - but that doesn't really explain the snowball behavior of response time proportional to size of response.  Did you look at / understand my repro?  I guess I also don't really understand how I can intercept the response in Fiddler2 by Telerik and it renders immediately there, but takes forever in Postman.  Based on your response, it feels like you're over-complicating the problem.  A simple fix would be to add an Inspectors abstraction similar to Telerik Fiddler2 and have a RawViewInspector (tab called Raw View) that materializes the response as ... raw data.

> * Use disk storage to store large response in a temporary buffer for the view so that scrolling works and view loads only partial data. That requires quite a bit of decoupling work needed in our response view component and rest of UI.

Dude, my example is NOT that huge.  You do NOT need disk storage... that's just crazy.  It's one year of minutely data.   You're WAY over-complicating the problem here.  Maybe for really large responses this is required, but you can't even render 40MB of data right now.  That should show you you CLEARLY have a very simple data binding/grid refresh issue.

**Comment by MerivaIe** [comment]
Hi team, I am also facing the same issue with a large response crashing Postman.

**Comment by Poltergeisen** [comment]
I'm facing this issue when pasting a large request into the box. Postman is completely unresponsive and my cpu is at 100%

**Comment by shawhu** [comment]
I also have the same problem. from what I've seen, this issue has been there since June 2018?

If there's a underlying lib/layers of libs needs to be upgraded and that surely takes time. However,
May I present a simpler solution here?

Talk about the the front-end tool design, if next step is going to take a lot of time to render, just split the step. Show the user what's going on like "We got your response, it's 24 MB in size, so it's probably going to take some time to Load" and let them choose if they want to spend minutes to see the pretty response, or simply give them option to download the blob/text

And btw, the loading time is ridiculously long. My HTML (Vue) client can consume and render it in 2.2 seconds. while postman need 10 minutes. But nevertheless, if it take some time to do it right, do it right.

**Comment by shawhu** [comment]
Also, I should argue first that this is high priority.

Because of the low cost and high bandwidth, people use web api more and more for streaming and gaming. the response chunk will be at least several MBs in the future if you really care about the future.

some treads
TextEncoder and TextDecoder for file minipulation
WebCrypto for near realtime AES data encryption
WebRTC for cam/video feed streaming...

Web apis will handle more and more data in the future and my opinion is that it's inevitable.

**Comment by a85** [comment]
@jzabroski The issue is not just about rendering as one of our engineers explained. If I had a dollar every time somebody tells me that "it-is-a-simple-fix" then I'd be a millionaire already. I appreciate your comments and showing the ways to reproduce it is enough for now. Outlining how the team is stupid is not needed and if you feel you are smarter, send me an open-source library that I can plug right into Postman that works for 5 million people and I'd be happy to do that. Otherwise, you are not helping.

**Comment by a85** [comment]
@jzabroski Also, reproducing the issue is trivial. I am not sure why writing a piece of elementary level ASP code was illuminating anything. If you do not know, then this issue created by OUR OWN engineer to keep reports in one place because otherwise we have people crapping all over the tracker on how THEIR OWN issue and solution is the sure fire fix for everything. Postman does a hundred things before and after it shows the response and we are tracking all of them. Smart-ass comments are not needed here.

**Comment by jzabroski** [comment]
@a85 I just won't use your product on the next project I work on.

However, might I suggest:

1. Not trying to track all issues in one issue.  Track focused issues and hold your developers accountable to fixing specific problems that add incremental minimum viable products.
2. Responding to customers when they explicitly ask for an update on a BLOCKER.  It can be as simple as, "I have reproduced your issue. Thank you for reporting it. I will go back to the R&D team and see I can find out."

> I am not sure why writing a piece of elementary level ASP code was illuminating anything.

It was illuminating because:
a) The file encoding was trivial - this allows you to see that the dominating factor in performance is likely not related to file encoding
b) The amount of data per line was trivially small - this allows you to see that the dominating factor in performance is likely not related to the amount of data in a single line of text
c) Based on a real world example dataset which not all customers can easily give out

Now, I can envision may different reasons for performance issues, but what I *hate* seeing as an engineer is waterfall development where *everything* needs to be fixed before *anything* can be fixed.

> Postman does a hundred things before and after it shows the response and we are tracking all of them.

It seems you closed a variety of different issues, and, rather than training your QA and customer service team to follow up with customers and ask for more detailed steps to triage and determine if they are the same issue, as well as collect GOLDEN test reproduction steps, you have allowed your team to create one all-encompassing feature.

Let me ask you: How will you know when you are done?  Do you internally have dozens of failing performance tests based on examples such as mine?  How are you tracking your team's progress?

**Comment by jzabroski** [comment]
@a85 
I don't know why after you insulted me I am being so nice and giving you further clarity into your product, but here I am:

I took my "elementary level ASP code" and the fact your application is an Electron app with access to Chrome Developer Tools and did the following:

a) I reduced my months of minutely data sample data from 12 months to 1.  No crash.
b) I then fired up the Performance logger inside Electron to see what takes the most time.
c) clicked into the flame graph where I saw on one month of data you were spending 332ms starting with Modernizr.js 3.0.0pre (Custom Build) library calling some cryptic minified tc() function

See this screenshot:
![image](https://user-images.githubusercontent.com/447485/55444356-12be0d80-5584-11e9-8bea-111d4536cc41.png)


I then looked up and saw on Modernizr website that they are now on https://modernizr.com/news/modernizr-3-5-0 since on April 13, 2017...

d) I confirmed that in the same webpack there are references to React v16.2.0 (which was released in November 2017...) https://github.com/facebook/react/blob/master/CHANGELOG.md#1620-november-28-2017

![image](https://user-images.githubusercontent.com/447485/55444380-29fcfb00-5584-11e9-973a-0e796133becf.png)

e) I went through the changelog of these two core libraries, after I had already told you (and was laughed out of the room by you for "smart-ass comments") that when I see "snowball" issues like these, typically there are hidden for loops caused by data binding or similar issues with redrawing scene graphs too many times.

I increased my months variable to 3 months.  I then saw that there were four main rendering loops, both at 1 months and 3 months, and that as I increased my months by 3x, there was some static overhead but some loops started sticking out more painfully, like parsing raw JSON arrays and appears to be from a module written by the famous Douglas Crockford called json_parse.js:

![image](https://user-images.githubusercontent.com/447485/55444825-45690580-5586-11e9-87c3-65cc6d6ea372.png)

I then searched github for "json parse benchmark" and found the following benchmark repository on GitHub for pure JS json parsing: https://github.com/ahmadnassri/benchmark-node-json-parse

Based on that, you are probably better off calling `JSON.parse`, and if you need to emit a stream of JSON objects as events to your application, doing so after calling JSON.parse.  JSON.parse is so much faster than other methods that you can probably call it and then walk its output faster than doing anything else. Just a hunch.

...I did all of this in about 30 minutes....

**Comment by AbrahamLopez10** [comment]
@a85 

> If I had a dollar every time somebody tells me that "it-is-a-simple-fix" then I'd be a millionaire already.

I'm not sure if you can get any more opinionated than this.

> then this issue created by OUR OWN engineer to keep reports in one place because otherwise we have people crapping all over the tracker on how THEIR OWN issue and solution is the sure fire fix for everything

So users are "crapping" when filing bug reports and making genuine suggestions on how to improve your own product?

> Smart-ass comments are not needed here.

Sorry, but your self-righteous attitude isn't helping either, and frankly is quite childish and unprofessional coming from a CEO. Next time I'd recommend letting your emotions settle down for a bit before typing away your unfiltered thoughts without realizing the impact this has on your personal image, your brand, and the reflection of your company's values.

@jzabroski 's concerns and observations are valid and you shouldn't just dismiss them as "smart-ass comments" instead of actually assigning a more appropriate amount of resources (specially from more experienced developers than the ones currently working on this) to investigate such a widespread and obvious issue with such a popular and great product as Postman.

**Comment by shamasis** [comment]
Hello all. Like you've identified and discussed, there are a number of contributing factors to the large response loading slow or crashing. But none of the vectors would solve it to a point where it will not grow back again... any fix on what is happening now in the app, by virtue of its synchronous nature, will crash the app.

There is no end to localised performance optimisation that can be done and maybe even a few of them could be useful in short term. As a team, we know that any performance optimisation that seems apparent from the chrome devtools (for example `json_parse` is used to support BigInt as a product feature and that factor is not apparent when one looks at the trace,) would be superficial in nature and the time spent on it will start having diminishing returns. 

So, as a first step (which is not an all out fix) we would attempt a change that would ensure that the user experience does not involve a "crash" by converting the synchronous user experience flow to an asynchronous one. (I'm sure JS developers on this thread understands what I'm trying to say.) Once that is achieved, any time investment on performance optimisation would have a positive return. The difficult part is that this first step involves changes in product behaviour (like test script execution point on first data vs on full response) and that leads to additional work that we would first complete before hitting this.

Summary: Large response would be tackled. Definitely. But, expecting that it is trivial and that the team building this is not aware of the fallouts and complications is something that we would like to refrain from being brought up in this thread since it is misleading for the greater community. I will update this thread when we have something for others to try on Postman Canary.

**Comment by shamasis** [comment]
> I'm facing this issue when pasting a large request into the box. Postman is completely unresponsive and my cpu is at 100%

Large request related issue is being tracked at: https://github.com/postmanlabs/postman-app-support/issues/4230

**Comment by jzabroski** [comment]
Hi @shamasis 

First, let me reiterate - I am not trying to make you look bad or give you grief.  I've been in situations as an engineer where people think because I've solved hundreds of performance problems in my career, that the next one is just as easy as the last ten. - In fact, just November through March I dealt with such an issue dealing with billions of rows of temporal data (and I was ultimately baled out by someone else who had a unique insight that made an algorithm _n*(n^(1/2))_).  So, I'm not trying to be that guy putting undue pressure on you like some pointy-haired boss.

What I'm trying to do is caution against, as an engineer, thinking everything needs to be re-written before material progress can be made.  For example, when you started talking about local storage, I got thinking, because you could introduce more performance/stability problems by adding local storage.

>  As a team, we know that any performance optimisation that seems apparent from the chrome devtools (for example `json_parse` is used to support BigInt as a product feature and that factor is not apparent when one looks at the trace,) would be superficial in nature and the time spent on it will start having diminishing returns.

But that's where I'm trying to come in and shake things up and give you an outsider's perspective by asking, "Why do it this way?"  Even the guy who built a SAX-based JSON parser, clarinet, says [JSON.parse is better in terms of raw speed](http://writings.nunojob.com/2011/12/clarinet-sax-based-evented-streaming-json-parser-in-javascript-for-the-browser-and-nodejs.html).  What he didn't benchmark was whether you could literally call `JSON.parse`, walk the object hierarchy and emit SAX-style events.  This would also give you your asynchronous event model you want.

As for BigInt, well, [it's not even part of EcmaScript 2019](https://golb.hplar.ch/2019/01/js-bigint-json.html), so maybe have an option to turn this off and just use JSON.parse for the rest of us that don't need BigInt.  You might not like this idea because it's not the most elegant, but if it makes your product more stable for 80% of customers, why not give it a try?  Just add a dropdown in settings for JSON parser and let people pick JSON.parse or json_parse.js for starters.

**Comment by neawasthi** [comment]
Postman desktop app  v7.0.7 is crashing for some mediocre  response (<20mb) and is pretty unusable at this moment.
I  happen to have the postman extension in chrome (v5.5.4) installed and it seems to work ok at least for the case mentioned above.

So, As a workaround see if downgrading to an old version help to get around the issue. Though I have not compared any features i may be missing by downgrading yet.

**Comment by jzabroski** [comment]
@shamasis Not sure if helpful, but I've been going through PowerPoint slides and blog posts of a CarGurus.com ReactJS developer named Tommy Parnell.  He seems to really know what he is talking about when it comes to web browser performance.

**Comment by jzabroski** [comment]
@a85 Here is another example where your company closed issues despite not really validating a solution has been reached: https://github.com/postmanlabs/postman-app-support/issues/3216#issuecomment-482469151

The reason given was lack of inactivity, which is unfair considering we're the ones waiting on updates from your team.

**Comment by jzabroski** [comment]
@a85 Just saw @vikiCoder  update on #3216 - thank you VERY much.

**Comment by spatil-scandilabs** [comment]
Hi, 
While testing APIs I am facing an issue for the response which has a huge string as a part of it. Basically, we transfer file contents via API by converting the file to string using Base64 encoding. 
The complete length of the received JSON response is around 1288818 characters.  
After receiving the response the POSTMAN stops responding. This is happening each time I receive such kind of big response. 
Is there any setting or configuration I can make to POSTMAN and successfully test the APIs which returns huge JSON as a response. 

Thanks!

**Comment by samsam321** [comment]
Happen in v7.0.9 
same as @spatil-scandilabs  last reply 
the response string is long base64 string, but size only 7xxKB

**Comment by Poltergeisen** [comment]
My postman crashes with a 10MB base64 encoded string as a response (or a request). I haven't actually been able to find a good client that can return that large of a file outside of just using curl.

**Comment by jzabroski** [comment]
@Poltergeisen I've used PowerShell 6 to good effect.  A backburner project idea of mine is to write a Swagger Swashbuckle extension that customizes the curl output to do PowerShell v6 curl instead of cmd curl. Note, you have to use PowerShell v6 because earlier PowerShell versions had unpredictable character encoding behavior.  What I usually do is translate the curl Swashbuckle spits out into PowerShell when I want to quickly load test something

**Comment by Poltergeisen** [comment]
@jzabroski I was able to get it to return pretty easily using the git bash shell and piping the output to a file. 

But it is difficult to share sample requests with real files to other developers on the team with this size limitation. Unfortunately even VSCode slows down and becomes close to unusable with the size of the files that I'm loading. I think it's just a limitation of electron.

**Comment by jzabroski** [comment]
If you're using VSCode, are you familiar with the httptests add-in.  you literally just define tests in API Blueprint style markdown.   It's super elegant and low tech for basic smoke tests.  The nice value add with Postman is all the goodies around debugging stuff.  John Papa and Jon Galloway did a VSCode break-out session last year where I learned a ton of VSCode tricks.

**Comment by tparikka** [comment]
I run into the same issue on this with a SOAP response of about 3.2 MB. The response body is a SOAP envelope wrapping an encoded SOAP message body that is about 3.1 MB, in a single line, coming from a WCF service.

**Comment by sebAtos** [comment]
Same issue. An API returning a json response of 725 KB takes less 1 second whit Chrome but 4 seconds with Postman. Moreover, time events popup is not correct at all. This one indicates response time is of 573ms but it's not the case at all. 
When do you think solve that ? I have just paid for a priced version and I have some doubt about reliability of this tool.

**Comment by c0desurfer** [comment]
Same here. My response is about 100MB small. Please fix this issue.

**Comment by Raj-postman** [comment]
Performance issue:

- Number of Requests in Collection - Above 100 and 3000 for some requests.
- Number of collections in the workspace ~35
- Number of collections across all workspaces ~35 ( one workspaece)
- open request tabs - 1
- number of environments 8
- number of variables across environments ~40
- Specific request that causes the system lag? :
    The collection with the issue has two loops, each ~1500 iterations over a ~200-300 character request and 600-700 character response.

**Comment by a85** [comment]
We are making some fundamental improvements to Postman's response rendering including using the Monaco editor for better memory optimization and rendering speeds. You can try out these updates in the Canary channel here: https://www.getpostman.com/downloads/canary

<img width="1790" alt="Screenshot 2019-06-12 12 19 53" src="https://user-images.githubusercontent.com/653409/59379813-72ffc700-8d0c-11e9-9da4-5c9ce0492dc4.png">

You can test it out with an API that we have created on the Postman Echo service. Examples here: https://documenter.getpostman.com/view/55577/S1ZudWWm?version=latest

**Comment by jzabroski** [comment]
First of all, thanks for making this a completely separate exe and not replacing the old one.  It makes it easy for me to do side-by-side comparison to see if things are better or not.  I don't know if that was deliberate or not, but it's nice.  I also like that the canary icon is blue, whereas the regular postman is orange/red.  We follow similar practices on my team.

I just tested on 10,000 data fields collection, and it came back almost instantaneously.  In Postman, this was rendered with Pretty on, and so there was a momentary "hiccup" effect where it first displayed all the results un-prettified (not sure if this is a bug internal to Monaco or Postman), then prettified them.

Hope this is helpful feedback, @a85

**Comment by jzabroski** [comment]
@a85 - it looks like the Auto dropdown for selecting the file content type is broken.  Not a huge deal, since I literally never used this feature, but thought I'd mention it. - I was more curious to see if I could break the new speed gains somehow.

**Comment by sebAtos** [comment]
For me, the problem is the same.
As above, I continue my tests with a response size of 725kb.

The loading of the response body is really too long even though with Canary I have a gain of one second, measured by myself, because by watching your response time, it's exaclty the same in both Postman and Canary (732ms). 

But be vigilant, about the body loading, taking close to 4 seconds...
Really strange. With Chrome, I am under 1 second (loading included) for the same API with same response size.

Maybe, it's an issue config on my workstation with Postman, I don't know but please, could you confirm that there is an issue on body loading response time ?

**Comment by a85** [comment]
@jzabroski Thanks! That is very helpful. Glad to know the response is loading quickly. We have some more improvements on the way like streaming responses but we'll go ahead with the current set of changes in the production build. We are switching to a new editor so there will be some differences in behavior that the team is fixing. I appreciate your patience and helping test this out.

@sebAtos Can you test with postman-echo.com and let me know if you are seeing the same thing?

**Comment by sebAtos** [comment]
@a85 Which API with a size of over 700kb can I test, with postman-echo.com ?

**Comment by a85** [comment]
Try sending these requests: https://documenter.getpostman.com/view/55577/S1ZudWWm?version=latest

**Comment by sebAtos** [comment]
With these request, hard to explain behaviours because time response are not consistent. It probably mays depend on the load, I don't know.
For instance with postman-echo.com/bytes/1200/kb?type=json, sometimes I have a response time with Chrome, Postman or Canary of less than 3 seconds and sometimes a response time of more than 60 seconds...

**Comment by aLooseGoose** [comment]
IMO Postman shouldn't bother handling anything with a `application/octet-stream` response content-type. If I request binary data, don't parse it, just show me headers and allow me to download it.

Edit: I am currently using 7.3.4 and when requesting a ~15MB binary file, it takes a good minute with the cpu spinning and the GUI hung before it will finish and show the garbage ascii from the binary in the body tab. Switching to headers doesn't prevent this.

**Comment by jzabroski** [comment]
@domosapien Zach, that's valid default behavior, but the way Fiddler handles this is it lets you create an Inspector that deserializes the octet stream as a structured view of some kind.

Classical example is [WCF Binary Message Inspector](https://github.com/waf/WCF-Binary-Message-Inspector) plug-in:

> WCF Binary Message Inspector provides two notable enhancements:
>
> 1. Uses a collapsible tree view instead of a textarea to display the decoded WCF binary message.
> 2. Allows editing and reissuing of captured WCF binary messages

So, while I agree with your "just let me download it" suggestion, the general Postman architecture should be powerful enough to allow Fiddler-like extensions.

**Comment by shamasis** [comment]
Continuing from the positive feedback we received on the [Postman Canary](https://www.getpostman.com/downloads/canary), I would like to update this thread with the news that the latest performance improvements around rendering large responses have landed in production. You would now be able render relatively large responses in app without crashing the app.

There is still a configurable [upper limit of response size](https://learning.getpostman.com/docs/postman/launching_postman/settings/), which can be changed from the settings section of the app. You can try out the latest v7 Postman app and fetch a 10mb response using the URL `https://postman-echo.com/bytes/10/mb?type=json` to see it in action.

![image](https://user-images.githubusercontent.com/232373/62479822-f947ff00-b7cb-11e9-8445-a2a4300c87bc.png)

It will still crash if you set it to an exorbitantly high value. Please let me know how far you could push the max response size. ;-)

**Comment by shamasis** [comment]
Since there are many on this thread with whom we were discussing the intricacies of handling large responses, here is a summary of things we did under the hood:

1. Added "taps" in every Buffer that streams response to the view. With this, we can now effectively track how much data we are downloading as it happens and stop on a threshold.

2. Replaced AceEditor with Monaco to prevent parsing of entire text. Monaco's internal architecture is conducive for rendering larger amounts of data.

3. Stopped any intermediate parsing (such as JSON.parse), which in-turn enabled us to retain a lot of cool features such as big-number handling without JSON parsing. This in turn required us to rebuild some of the goodies of JSON.parse ourselves and get rid of the ones that are problematic.

**Comment by xmaska** [comment]
My latest postman release, the canary release, the latest newman crashes when receiving big json response in the following format:
{"records":[{valid_json_document1},{valid_json_document2},{valid_json_documentn}]}
The response comes in a single line and the amount of json documents in the array can reach 10 000. The problem is clearly when postman processes the response without running any tests. 

For me this is clearly a blocker and I have to switch to back to Jmeter. Please let me know if there are any improvements done on this.

**Comment by lenichols** [comment]
Sadly i downloaded the latest Postman on my mac running MacOS Mojave and no bueno. It wouldn't even start.

<img width="445" alt="Screen Shot 2019-09-10 at 4 33 30 PM" src="https://user-images.githubusercontent.com/5247113/64657549-d6bb8e00-d3e8-11e9-90d9-f3f8338b97cc.png">

**Comment by xk0der** [comment]
@lenichols looks like you ran into some other issue (and looks like it isn't related to the original issue being tracked here). Do try the steps listed here https://support.getpostman.com/hc/en-us/articles/360008601954 and if things still do not work shoot us an email at help@getpostman.com

**Comment by deshpandepramod** [comment]
I have set 100 MB as max response size then also its crashing and blacking out...

**Comment by jzabroski** [comment]
@deshpandepramod Can you share your version info?

**Comment by barb1223** [comment]
Having the same problem with postman crashing and getting a black screen.  Any updates on this?

**Comment by jzabroski** [comment]
@barb1223  YOu need to specify your version info

**Comment by barb1223** [comment]
We're running Postman V7.11.0.

**Comment by AncAinu** [comment]
Same problem here

**Comment by jzabroski** [comment]
@AncAinu Are you on the same version?

**Comment by barb1223** [comment]
I reinstalled Postman and I'm at V7.12.0 and still having this issue.

**Comment by arpst0rm** [comment]
im on the mac running 7.13.0.  

I am getting the same problem with a response file that is ~45M.  API returns, I see some data int eh response window but when I try to interact with the response the UI hangs.  If I try to have the response dump to a file that seems to hang in the background, but the file is never saved.

**Comment by kds-snyder** [comment]
Having the same problems as @arpst0rm on Windows 10, with Postman V7.14.0, with a response body ~35M.

**Comment by Exitare** [comment]
Postman is just crashing after clicking send to get the response. The response body is ~32MB.

Postman installed:
> Postman for Mac
Version 7.16.0
 OS X 19.2.0 / x64

**Comment by ghost** [comment]
I'm trying to figure out how to test some SOAP services with POSTMAN and seem to be running into this issue.  Say part is SOAPUI has the same problems.

My response is about 70mb and when I make the request I end up with a black screen, even if I try to use the Send and Download response I end up with no file and the same black screen results.

**Comment by samuelvenzi** [comment]
I am having this problem on version v7.20.0

**Comment by dylanh724** [comment]
Still happening. Getting black screens (that don't recover) or crashing without error. Workarounds? Hmm, why is this topic **closed**?

**Comment by akhsiM** [comment]
This issue is still happening so I have raised #8288.

**Comment by sarbajitdutta** [comment]
Same here with a json payload of 27mb.

![image](https://user-images.githubusercontent.com/16959056/82355672-87dee300-99d0-11ea-9583-c71227396087.png)

**Comment by d-j-kendall** [comment]
Same here this should be fixed. It would be nice if one could clear out past responses as well...

**Comment by saswatds** [comment]
Hi @sarbajitdutta @dkendall100  as I have mentioned in https://github.com/postmanlabs/postman-app-support/issues/8288#issuecomment-691500931 . Your issue should be resolved now if you update to the latest version of postman app  `7.32.0`.

**Comment by dsschapira** [comment]
I'm on Postman v `7.32.0` on a 2019 MacBook Pro running Mojave (10.14.6) and while I'm able to get my response back, I cannot download to file without the app totally freezing.

Here is my response, with ~175MB payload:
<img width="1295" alt="Screen Shot 2020-09-16 at 7 05 37 PM" src="https://user-images.githubusercontent.com/28044482/93401222-b5894b00-f84f-11ea-8c7f-b1e46c3f7251.png">


After selecting "Save Response > Save to File" I'm stuck on this screen indefinitely:
<img width="1294" alt="Screen Shot 2020-09-16 at 7 05 51 PM" src="https://user-images.githubusercontent.com/28044482/93401271-d05bbf80-f84f-11ea-953b-dc873102aa26.png">

**Comment by richardgroves** [comment]
Getting the same exact thing happening as @dsschapira - my payload response is in the 110-140MB of JSON range: Save to File -> Grey dead window.  (Version 7.34.0 (7.34.0) on 2020 iMac with 72GB RAM, 3.8 GHz 8-Core Intel Core i7)

**Comment by marthinch** [comment]
I also have this issue. My payload data size 30MB and the postman gets blank.

**Comment by aamirencodes** [comment]
Facing the same issue @dsschapira , I'm not sure if its the issue with the postman or my large byteArray response.

**Comment by vdkhvb** [comment]
With a response payload of about 540MB my app keeps crashing.

**Comment by christian-fischer-trinidat** [comment]
I have the same problem here with a response payload of 110 MB. The app turns gray when I click on the response data.
