### ISSUE TITLE
Postman shows black window when defocused while a edit field is active

### ISSUE THREAD

**Issue by gitterrost4** [a85/POSTMan-Chrome-Extension#4764]
**Describe the bug**
Since the last update postman's window will go black whenever the window is defocused while an input field is active. The environment variable POSTMAN_DISABLE_GPU does not influence this behavior.

**To Reproduce**
1. Open any postman request
2. Click inside the URL input box (or any other text input box)
3. Defocus the window by opening another window

**Expected behavior**
Postman not going black

**App information**
 - Native App
 - Postman Version 6.1.4
 - OS: Linux (Arch Linux)
 - Window Manager: i3wm

**Additional Information**
 - When started from a terminal, there is no error output whatsoever.
 - The blackout is not instant. Notice that it takes a second in the screencapture after defocusing.

**Screenshots**
![output](https://user-images.githubusercontent.com/976654/42202908-70433638-7e9d-11e8-9695-98cc520d5e41.gif)

**Comment by numaanashraf** [comment]
@gitterrost4 Thanks for reporting this. Could you open the Postman app from the shell/terminal and reproduce this case and let us know if you see any terminal errors when the screen goes blank?

**Comment by gitterrost4** [comment]
As I stated:
> When started from a terminal, there is no error output whatsoever.

**Comment by numaanashraf** [comment]
@gitterrost4 My bad. We are trying to replicate this issue in a similar environment. We've seen similar issues due to `i3wm` window manager.

**Comment by gitterrost4** [comment]
@numaanashraf If I can provide anything else to help replicating it, I'm glad to do so.

**Comment by coffeeneer** [comment]
I'm having the same issue. Also Arch, but a different WM. I'm using deepin DDE, which uses deepin-wm which is a fork of mutter (GNOME) if I'm not mistaken.

It seems the issue is not with every field, it seems only text-area's are triggering this issue. When a non-resizable text field is selected it does not go black on lost app focus.

**Comment by richbowen** [comment]
App window goes black for me as well on Arch using the Plasma desktop environment.

Prior to crash:
![before_crash](https://user-images.githubusercontent.com/5672238/42425062-a2345b20-82dc-11e8-8ece-e34114a943f0.png)

After crash:
![after_crash](https://user-images.githubusercontent.com/5672238/42425028-19859758-82dc-11e8-971e-c90751ed44a3.png)

The active input field is the one with the 'New key' placeholder. When the app loses focus and is refocused, the app window goes black (minus the application menu options). 

This could be an Arch specific issue.
The packager of https://aur.archlinux.org/packages/postman mentions that:
> Postman doesn't work with electron>=2.0.0. The package temporarily includes electron 1.8.4 from Arch Linux archive.

The  issue is however that the latest version of electron is a dependency in the `postman` `PKGBUILD`, so it is being used by the application.


**Fellow Arch users:**
Use `postman-bin`, it doesn't seem to have this issue.

**Comment by gitterrost4** [comment]
> Use `postman-bin`, it doesn't seem to have this issue.

Thank you! That functions as a workaround.

**Comment by adrianmarino** [comment]
> Use postman-bin, it doesn't seem to have this issue.

@rgb-one `local/postman-bin 6.5.2-1` doesn't have this issue.

Thank you!

**Comment by m3dbedb** [comment]
The issue is still present in postman 7.3.5 (under windows 7 32 bit), app launched with  

> --disable-gpu

**Comment by harryi3t** [comment]
@gitterrost4 @dodedodo33 @rgb-one 
It looks like you have downloaded the Postman app from an unsupported distribution https://aur.archlinux.org/packages/postman

This might be unrelated but just to confirm that this issue is not because of the distribution variant, could you try installing Postman either from our website or using snap?

 - Postman Download page for Linux - https://getpostman.com/downloads/ 
 - Official Snap for Postman -  https://snapcraft.io/postman

**Comment by richbowen** [comment]
The package that uses the upstream Postman (linux64) as opposed to building it from scratch is [postman-bin](https://aur.archlinux.org/packages/postman-bin) ([see here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=postman-bin#n10)). It works fine. I haven't tried packages/postman since the issue but I think the reason for the black screen was an electron version mismatch.

**Comment by m3dbedb** [comment]
Since Postman 7.3.5 have released it looks like maximizing/demaximizing screen solves the issue. In other words the issue is still present, but you don't have to close Postman window to make it work again. Now, when Postman gets gray (not black as in previous versions), just maximize/demaximize Postman window and it works again. (tested in windows 7 32 bit) ![gray](https://user-images.githubusercontent.com/25632818/62706543-7061db00-b9f8-11e9-8564-3e3fa007d0fb.jpg)

**Comment by m3dbedb** [comment]
Sadly, sometimes Postman 7.3.6 in windows 7 32 bit still goes to black screen as mentioned above and maximizing window does not help.
![bla](https://user-images.githubusercontent.com/25632818/62922568-618e7600-bdb4-11e9-9278-22f2e87b6b57.png)

**Comment by m3dbedb** [comment]
The issue is still actual for Postman 7.5.0 and 7.11.0 and postman 7.16.1 for windows 7 32 bit

**Comment by miyconst** [comment]
PostMan `6.7.1` on Ubuntu 18.04, the same behavior.

**Comment by eminks** [comment]
#7767 @kamalaknn
-When do you see this issue? Does it happen always?
When i start application getting black screen

The size of data you are working with: I think 20 or 25 kb
the number of history or requests: I think 10-15
the size of the response you are working with: I don't exactly size but maximum 20 kb

**Comment by twitharshil** [comment]
Hi,
We've pushed an update on our early access canary channel. Do try it out and let us know if the issue is still reproducible on it.

You can get the canary app from https://www.getpostman.com/downloads/canary

**Comment by numaanashraf** [comment]
Postman v7.25.1 and above uses Electron v7.2.x which should help with this issue. Do let us know if you are still facing this.
