### ISSUE TITLE
Script Id should be unique for a duplicated request

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4802]
**Describe the bug**
Duplicating a request with pre/post request scripts does not update the script.id field. This can be observed by checking the v2.1 export for the collection.

**To Reproduce**
1. Create a collection c1
2. Add a request to the collection, with the pre-request and test scripts populated
3. Duplicate the request
4. Export the collection as v2.1

**Expected behavior**
Unique IDs should be updated on duplication of a parent entity

**Screenshots**
The prerequest script ID is the same in both requests:

<img width="376" alt="screen shot 2018-07-10 at 23 55 29" src="https://user-images.githubusercontent.com/681190/42529663-c006371a-849c-11e8-836e-dde7e3539e58.png">
.

**App information (please complete the following information):**
 - Native app, 6.1.4, OSX

**Comment by grimsa** [comment]
The current fix for this in 7.23 has made https://github.com/postmanlabs/postman-app-support/issues/2906 much, much worse.

Our situation:
- We are keeping a committed postman collection in git repo.
- It is used both in CI pipeline and by developers (workflow is: pull develop, import latest postman collection, make some fix, commit fix + updated postman collection)

Previously we every collection export only regenerated `/info/_postman_id` property. Now every prerequest and test script ID is being updated **on every collection export**.
A developer then has to manually revert every ID change in order to not pollute Git logs/make code reviews easier. This is very painful for large collections.

@arlemi I would kindly ask to consider a different fix, that regenerates IDs **only** if a duplicate exists.

**Comment by shamasis** [comment]
That’s not good. Upon export the IDs shouldn’t change. If it is, it’s a bug and we will fix it on the double. Hang tight.

Also, we are working on the ID-less export improvement.

**Comment by arlemi** [comment]
Hey @grimsa 👋 

I wasn't able to replicate your issue, exporting the same collection doesn't update `_postman_id` nor the script IDs. 
If your developers are importing the collection to their own accounts then that is when the IDs are updated - importing a collection creates a new entity (along with new IDs). I understand this wasn't the case prior to 7.23 but that was part of the issue mentioned here.

If you'd like to share the collection in a team setting I would recommend that you look at how you can [collaborate within Postman](https://learning.postman.com/docs/postman/collaboration/collaboration-intro/), a collection shared from a personal workspace to a team workspace will not update the IDs (see: [Sharing collections](https://learning.postman.com/docs/postman/collections/sharing-collections/#sharing-collections-in-the-app)).

Let me know if you have any other question!

**Comment by grimsa** [comment]
@arlemi You are correct - it is indeed the import that is replacing these IDs, not the export.

> If your developers are importing the collection to their own accounts then that is when the IDs are updated - importing a collection creates a new entity (along with new IDs). I understand this wasn't the case prior to 7.23 [...].

Yes, our workflow is such that "the single source of truth" of Postman collection is committed in version control system (Git) along with the implementation of the APIs under test. Then every developer regularly imports it locally (possibly even without signing in to Postman), makes changes to both API implementation code and the Postman collection, and then commits both together.
To my knowledge, this is the easiest (only?) way to make every branch in version control have a Postman collection testing that branch of the API, which we then run with Newman as part of our CI process (to check if the whole API works before merging the branch).

> [...] but that was part of the issue mentioned here.

It seems to me that the original issue was only that IDs should be regenerated when duplicating a request, not every time a collection is imported. But maybe I'm missing some context.

I guess my expectation is that if Postman can detect that I'm importing an existing collection:
![image](https://user-images.githubusercontent.com/8446128/80344096-b3f2c280-886f-11ea-90e3-7bd8ede200cb.png)
, and I choose to **replace** it, the IDs should be retained.

> If you'd like to share the collection in a team setting I would recommend that you look at how you can collaborate within Postman, a collection shared from a personal workspace to a team workspace will not update the IDs (see: Sharing collections).

Unfortunately, none of the options seem to cover the need to branch out into multiple versions of the same Postman collection (as multiple developers are working on their own features at the same time) and then merge them back into one, after changes in API implementation are being merged in.

**Comment by arlemi** [comment]
Thanks for the detailed answer @grimsa ! I also tried the scenario you had described (without going into branching, [see here](https://github.com/arlemi/postman-test/commits/master)) and noticed that the scriptID was updated, though in the case where the collection is imported it is expected. 

> It seems to me that the original issue was only that IDs should be regenerated when duplicating a request, not every time a collection is imported. But maybe I'm missing some context.

Yep, while this issue only mentions script ID not being updated in the case of duplicating a request, it should have also mentioned that the script ID needed to be updated when importing it as a new collection. We've fixed two things at once but could have done a better job at communicating it apparently. 😅 

> I guess my expectation is that if Postman can detect that I'm importing an existing collection 

Postman detects that you're importing a collection with the same name, which isn't enough to conclude that this is the same collection, that's why we're considering any entity imported as a new entity and are updating the IDs. 

![import](https://user-images.githubusercontent.com/5029719/80374083-02af5500-888e-11ea-854b-7172d6ef8200.gif)

Though I understand the title of that pop-up may be misleading, we'll raise that to the team and see if we can improve the copy in the title!

> Unfortunately, none of the options seem to cover the need to branch out into multiple versions of the same Postman collection (as multiple developers are working on their own features at the same time) and then merge them back into one, after changes in API implementation are being merged in.

You may want to have a look at [postman-cli](https://github.com/matt-ball/postman-cli), sounds like it could help you with versioning your Postman scripts. 🙂 

In the meantime we'll still be working on the ID-less export improvement, should be available over the next couple of months!

**Comment by arlemi** [comment]
@grimsa One thing to mention before closing this issue though, we do offer Version Control for collections (forking/merging/pull requests), you can read more about it here: https://learning.postman.com/docs/postman/collections/version-control-for-collections/

It does not (yet! see #7841) support changes within the same file (e.g. changes in tests from two different forks) but it may still be worth checking it out!
