### ISSUE TITLE
The collection fails even if each test works

### ISSUE THREAD

**Issue by dionescu10** [a85/POSTMan-Chrome-Extension#4865]
Hello,

I have created a collection with tests in Postman. I can run every test and it works in order, but when I try to run the whole collection, I receive 406. I found some pieces of information but nothing useful for me.

I have attached the log file.
![headers](https://user-images.githubusercontent.com/35342107/43066736-1af36e4c-8e6e-11e8-8c35-8344d88b8e09.PNG)
![test_result](https://user-images.githubusercontent.com/35342107/43066737-1b103cfc-8e6e-11e8-8c07-c34b9d9a9c36.PNG)

[ThingWorx.postman_test_run.txt](https://github.com/postmanlabs/postman-app-support/files/2218576/ThingWorx.postman_test_run.txt)

**Comment by sivcan** [comment]
Hey @dionescu10, 
Can you open the Postman Console (View > Postman Console) and run the requests.
Can you verify that the data being sent is correct or not? (specifically HEADERS and AUTH)

Finally, is there any environment that you might be using and that's not selected in the runner but in the main request builder view it is selected?

**Comment by dionescu10** [comment]
Hey @sivcan,

This is what I have in the console when I run the collection:
![console_postman](https://user-images.githubusercontent.com/35342107/43068877-2f6e039a-8e5b-11e8-907c-cfb3a7a5f706.PNG)
![fails](https://user-images.githubusercontent.com/35342107/43069308-4893d75e-8e5c-11e8-814a-dcb3d6a2accb.PNG)

The authentication details have to be correct because the tests run in order. I also set these details in edit section of the collection. Do you think that I have to check these details in another place?

I run these tests on AWS virtual machine, but I have postman installed right on this vm so I do not think that I would need to fill in this section.

**Comment by dionescu10** [comment]
Is it possible to have this problem due to the format of the response? Maybe, I have to add a new header. I also tried with Content-type : application/json and Accept: application/json but I still have this issue.

**Comment by sivcan** [comment]
@dionescu10 As I can see that you're making post requests through the runner and in the body's form data you're uploading a file.

Files / File paths are never saved in Postman environment and thus the error that's coming up in the console shows that it is unable to upload the form data file.

If the issue is not related to the file data then let me know

**Comment by dionescu10** [comment]
Hello,

And how can I solve this issue? Is it possible to work if I change the the type of the variable from “file” to “text” and use the file path?
I already tried this but it doesn’t work. I received an error something like “ You have to select a zip file” but I hope that I have to write the file path in a different way.


Kind regards,
Daniel

**Comment by sivcan** [comment]
These values (file paths) are not saved/exported/synced intentionally because of security concerns.
As of now, you cannot use that in the runner.

Follow this issue for an update on file paths since it's related: https://github.com/postmanlabs/postman-app-support/issues/4320

You can dig more into [Newman](https://www.getpostman.com/docs/v6/postman/collection_runs/command_line_integration_with_newman) and [reach out to the community](https://community.getpostman.com/latest) for help regarding this. 

We'll be actively tracking this issue here https://github.com/postmanlabs/postman-app-support/issues/4320
