### ISSUE TITLE
After Editing and Environment return directly to the App 

### ISSUE THREAD

**Issue by schellem** [a85/POSTMan-Chrome-Extension#4932]
When choosing the 'eye' (environment quick look) to edit an environment and then editing an environment when you click cancel or update you are not returned to the application, the manage environments dialog pops up. There is no reason to pass back thru the manage environments dialog. Making it a bit worse is that the manage environments dialog does not have a close\cancel button and you must use the X in top right corner.

**Describe the solution you'd like**
After editing the environment via the 'eye' doing a cancel or update should return user directly to the application. Do not pass back thru the manage environments dialog since manage environments was not used to get here. This avoids unnecessary steps to get back to working..

**Describe alternatives you've considered**
I see no other paths to get back to the app quickly

**Comment by giridharvc7** [comment]
This is now fixed in v8. Clicking on edit in the quick view `eye` icon takes you to a new tab with environments. 
You can edit and save here and switch back to your request tab. 
<img width="1101" alt="Screenshot 2021-02-22 at 7 16 38 PM" src="https://user-images.githubusercontent.com/1040583/108716733-7ec40900-7542-11eb-9a42-4676384b572f.png">
