### ISSUE TITLE
Double brace syntax doesn't support object/array type value.

### ISSUE THREAD

**Issue by kirkcola** [a85/POSTMan-Chrome-Extension#4975]
## App Details:
```
Postman for Mac
Version 6.2.2
OS X 18.0.0 / x64
```

## Need Help:
   Hey guys, I met a problem when I tried to run the `Collection Runner` with a JSON data file like this: 
```json
{
    "namespace": "test",
    "fields": [
        "test",
        "test"
    ],
    "props": {
        "test1": 1,
        "test2": 2
    }
}
```

When I tried to send a JSON request using the value from the data file in this way: 
```
// raw body
{
    "namespace": "{{namespace}}",
    "fields": {{fields}},
    "props": {{props}}
}
```
And I expect the keys `fields` and the `props` can be replaced with corresponding object/array in the file.
  
But the console showed these two keys' values in the request body are `[object object]`, which means the double brace syntax doesn't support object/array type value.

How should I do?

**Comment by sivcan** [comment]
@kirkcola Yes, currently only string data type is supported.
Here's the issue raised for the same: https://github.com/postmanlabs/postman-app-support/issues/4173

As for now for a workaround - you can use variables in stringified format in the data file.
Or store these as environment variables and use them in your body.

```
[{
    "namespace": "test",
    "fields":"[\"test\",\"test\"]",
    "props": "{\"test1\":1,\"test2\":2}"
}]
```

Closing this issue since we'll be tracking all issue related to variable types in the same thread.
Follow the same for further updates.
