### ISSUE TITLE
More Documentation details on use of certain specific scripting functions

### ISSUE THREAD

**Issue by raghav19** [a85/POSTMan-Chrome-Extension#4999]
I am trying a few scenarios as a part of my tests in postman

1) Check presence of key and print status of key existence in  json response.
     check presence:  `pm.expect(pm.response.json()).to.have.property("id");`
     print status: `pm.response.text().has('id)
I couldn't find a way to print the status using `pm.response.json()` , how should I?

2) Get value from headers, Get value from response JSON
    Value from headers: `pm.response.headers.get("Content-Type")`
     Value from response JSON: `pm.response.json().value[0]["id"]`
I tried to fetch value from JSON as `pm.response.json().get("id")` because the `pm.response.headers` also gives me `ArrayList` just like the json, but i couldnt get the value from the json and had to use the above method. Where can i find more details on parsing this? 

I tried looking into PostMan SDK as well, but couldnt get anything much.

Please suggest.

**Comment by sivcan** [comment]
@raghav19 - 
You can import this collection in the native apps and I've documented some things to help you out  in the Test Scripts.
https://www.getpostman.com/collections/c370afaf5ffbb9008168

You can definitely do the testing in better ways but this was just to give you the jist of how things can be worked around in the test scripts.

Also, we maintain this repository for bug reports or feature requests.
I suggest that any queries related to how-to's or usage of feature be taken up on our community page.
Since the community will be able to help you better with answering them and faster 😄
Reach out to Postman Community here: https://community.getpostman.com/latest
