### ISSUE TITLE
Environment variables are not getting replaced with the value while sending requests after the update

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5039]
**Describe the bug**
The Environment variables are not getting replaced with its value when sending the request & resulting in the error "couldn't get any response". Wherein, it used to work as expected before the update.

**Note**: If the environment variable is replaced with the exact value in the endpoint URL & the call the API, it works fine

**Expected behavior**
The corresponding environment variable values should be used while running the request

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/44266852-c23ead80-a249-11e8-99c3-64239c75e180.png)

**App information (please complete the following information):**
 - App Type : Native app
 - Postman Version: 6.2.4.tar.gz
 - OS: linux-x64

**Comment by gitterrost4** [comment]
I can confirm this behavior on the native app for linux-x64 and it makes working with my collections impossible.

**Comment by harryi3t** [comment]
Hi @gitterrost4,
Were you able to reproduce this issue? Does this happen randomly or consistently?
If you are able to reproduce it consistently, could you post a screen recording? That will be very helpful.
Thanks

**Comment by gitterrost4** [comment]
I **was** able to reproduce this issue. After downgrading postman to 6.2.3, the issue was not present anymore. After upgrading again, everything works fine. Very strange indeed.

The effect was that if you have a variable "host" lets say set to "https://github.com", if you have a request with the URL {{host}}/test, it would show the error "There was an error connecting to %7B%7Bhost%7D%7D/test". Expected would have been a request to https://github.com/test.

But since downgrading and upgrading again worked, it might have been a migration issue when going from 6.2.2 directly to 6.2.4.

**Comment by harryi3t** [comment]
@gitterrost4 Thanks for the quick reply. Glad that it worked out for you.
Would you mind sharing some more information regarding this?
 1. What was the type of variable? (environment, collection or global variable)
 2. While upgrading from 6.2.3 to 6.2.4, was this tab with the variable already open?

**Comment by gitterrost4** [comment]
For me it was two variables one global and one environment. Both failed to be replaced. 

For both upgrades (the one that broke it and the one that fixed it) I tried it with requests that were already open and with some that weren't. Both gave the same result.

I must add that I am not sure what the initial version before upgrading to 6.2.4 the first time was. But I last upgraded about a month or so ago.

**Comment by senj-z** [comment]
I updated the version from 6.2.4 to 6.2.5 and now everything works for me.

**Comment by sourcesmith** [comment]
Upgraded from 6.1.2 to 6.2.5 which is broken. Then downgraded to 6.2.3 which is also broken.  Downgraded back to 6.1.2 which now does not start.

I have found a workaround: exporting a collection and re-importing it seems to resolve the problem.  [Turns out this was not a permanent fix]

Downgrading to 6.1.4, removing the postman config dir and re-importing the collections and environments works.

**Comment by Vodek2** [comment]
Can confirm same problem in Ubuntu 18.04-x64 with both version of Postman (6.2.4 and 6.2.5) Downgrading to 6.1.4 resolved problem.
Please fix.

**Comment by harryi3t** [comment]
@Vodek2 Is there a way to reproduce this issue? I wasn't able to do so.
If you still have the 6.2.4/6.2.5 app in your system and are still able to reproduce this, could you kindly share the error logs (if any) from the `View -> Developer -> Show DevTools (Current View)`?

**Comment by senj-z** [comment]
run 
`sudo rm -rf /opt/Postman`
and install 
https://blog.bluematador.com/posts/postman-how-to-install-on-ubuntu-1604/

**Comment by sourcesmith** [comment]
@harryi3t Nothing much going on in the logs.  Last line of the shared log looks like it might be of interest:

`vendor-shared.js:76728 Initializing the global config
vendor-shared.js:83475 Initializing settings
shared.js:13538 Skipping migrations. No migrations to apply.
vendor-shared.js:76788 Booting waterline models
vendor-shared.js:144334 db name postman-app
vendor-shared.js:144362 Objectinitialize: function initialize(options, done)loadCollection: function heyThatsDeprecated()registerModel: function registerModel(wmd)teardown: function teardown(done)collections: Objectdatastores: Object__proto__: Object "Successful ORM initialization"
shared.js:1220 Migration bailed out due to: EXCEEDED_ATTEMPT
(anonymous) @ shared.js:1220`

**Comment by harryi3t** [comment]
@sourcesmith @senj-gold @Vodek2 @gitterrost4 
We are not able to reproduce this on our end. I would really appreciate if you guys can help us debug this. I will be more than happy to jump on a Google meet call or a TeamViewer session to remote debug this issue.
If this is not feasible for some reasons, you can also debug the app using the following steps and share the information with us.
 - Open the Postman app where this issue is reproducible
 - Open the DevTools
    - Using shortcut: `Cmd/Ctrl + Shift + i` 
    - or using the menu (`View -> Developer -> Show DevTools (Current View)`)
 - Goto the `Sources` tab and press `Cmd/Ctrl + p`  and search for `requester.js`. Open the first file

![image](https://user-images.githubusercontent.com/5207331/44581149-359c6e00-a7ba-11e8-8a4a-a1605f023caf.png)

 - Search the string `let runMetaData = {` and place a breakpoint on this line. This should be around line number 14571.

![image](https://user-images.githubusercontent.com/5207331/44581184-51077900-a7ba-11e8-89b0-d81108c8fbe0.png)

 - Select the environment in the app and send a request (you should remove any sensitive variable from the environment and globals). The request sending will be paused because of the debugger.

![image](https://user-images.githubusercontent.com/5207331/44581205-68466680-a7ba-11e8-8bfd-8dd0b2e4608b.png)


 - Go to the `console` tab run the following script
```js
JSON.stringify({ activeEnvironmentId, environment, envSessionId, envSession })
``` 
 - Copy the output of this script and share it here
![image](https://user-images.githubusercontent.com/5207331/44581104-11d92800-a7ba-11e8-98e6-64ede4798a34.png)

**Comment by sourcesmith** [comment]
@harryi3t 

[env-json.txt](https://github.com/postmanlabs/postman-app-support/files/2318158/env-json.txt)

**Comment by harryi3t** [comment]
@sourcesmith Thanks for the data that you shared. 
I can see that while sending the request all the necessary information required was there. Was this data taken on the app which __still has this issue__ (the request sent did not have resolved variables)?

**Comment by sourcesmith** [comment]
@harryi3t Yes, no variables are resolved.

**Comment by harryi3t** [comment]
@sourcesmith Sorry for the late followup. 
Are you on linux and is your app unzipped in `/opt/Postman` directory?  We have seen people having permission issues in this directory.
To rule out this possibility could you try unzipping the app in home or desktop directory and try it again?
If it works there then we know that it is indeed a permission issue. For a more permanent fix, you can change the permission of this directory.
As a user mentioned [here](https://github.com/postmanlabs/postman-app-support/issues/4374#issuecomment-412824163) you can try using `sudo chown -R user:user /opt/Postman /home/user/.config/Postman`

**Comment by Vodek2** [comment]
Yes, i did unzipped postman into /opt/Postman, but unfortunately changing
ownership to both dirs did not help.
The only pattern I've noticed: it's only happen for requests with 'Pre-request Script'. With those without script, variable values are resolved correctly
My script is very straight forward, just to get token:

![image](https://user-images.githubusercontent.com/18397962/44719521-739bd980-aabb-11e8-9239-42a1c45e9aa3.png)

**Comment by harryi3t** [comment]
@Vodek2 Could you share the output after following the steps mentioned in my [earlier comment](https://github.com/postmanlabs/postman-app-support/issues/5039#issuecomment-415727976)?
Also, if possible can we schedule a remote debugging session with you? Our team can sit with you on a video call to debug this issue.

**Comment by IevgenSobko** [comment]
+1 having the same issue on Linux for a few weeks.
Have updated application for a few times with no result.
Also changed permissions which had no effect.
![2018-09-09__21-57-23](https://user-images.githubusercontent.com/14232100/45267750-65ff3000-b47b-11e8-9b55-fbac3847e467.png)

**Comment by harryi3t** [comment]
@IevgenSobko 
 1. Could you share the output after following the steps mentioned in my [earlier comment](https://github.com/postmanlabs/postman-app-support/issues/5039#issuecomment-415727976)?
2. Please share the output of `ls -lha /opt/Postman`
3. If possible can we schedule a remote debugging session with you? Our team can sit with you on a video call to debug this issue.
4. Also, could you try unzipping the app in home or desktop directory and try it again?

**Comment by IevgenSobko** [comment]
@harryi3t thx for tips.
1. Tried yesterday and ULR variables were present.
2. 
![2018-09-10__13-10-25](https://user-images.githubusercontent.com/14232100/45291496-08aac380-b4fb-11e8-9372-001b44cfbea5.png)
3. If you need that there is no problem from my side to have a sharing session to help you.
4. and this option finally resolved the issue.

**Comment by Discipe** [comment]
Postman reinstall helped me to fix the issue on Windows (I've also installed old Canary build I already had downloaded and used it for couple days before reinstalling). So I couldn't reproduce the issue.
It's very disturbing that you only have couple of previous versions (and all of them are minor versions, no major ones) available to download on official site.

**Comment by harryi3t** [comment]
@IevgenSobko 
I am hoping that you haven't deleted the original installation of Postman in the `/opt/Postman` directory. If that is the case and the bug is still present in that, could you share your email and time slots when you will be available for this? You can drop a mail at help@getpostman.com. Please mention the Github issue number in the mail.
Thanks

**Comment by IevgenSobko** [comment]
@harryi3t old installation is also present and still showing the same issue persists for it, so we will be able to debug it.

**Comment by harryi3t** [comment]
@IevgenSobko Thanks for giving us your time to help us debug this issue.

@sourcesmith @gitterrost4 @senj-gold @Vodek2 We have found the root cause for this. Here's a short post-mortem.

#### What is the bug?
Some Postman users on Linux are not able to send saved requests which have environment variables. Sending other requests works fine.

#### Who all are affected?
The users who have installed their application in a directory in which they don't have write permission (mostly `/opt/Postman`) and who have manually updated their app by downloading the latest version and then copying the contents to that directory.

#### Why it happened?
This issue was actually two fold. 
First, because these users installed Postman in a directory where there was no write permissions, Postman could not auto-update itself which would have not caused this issue.
Second, since auto-update was not working for them they were manually downloading the latest version and then copying the files. This process does not delete the old files, some of which are not compatible with the latest version. This ends up the new app in an in-consistent state.

#### What is the fix?
Doing a fresh install in a directory where you have write permissions (like home directory) should solve the issue. Also, if the auto-update does not work for some reason, and you want to manully update the app yourself, you should first delete the old app before copying the new files.

#### What we could have done better?
When auto-update was failing because of permission issue, we should have informed the user about this. Currently all the errors are logged only in the DevTools
![harryi3t___postman_slack](https://user-images.githubusercontent.com/5207331/45360246-9f0ae200-b5ec-11e8-99bd-0521b49d424a.png)
![harryi3t___postman_slack](https://user-images.githubusercontent.com/5207331/45360265-aa5e0d80-b5ec-11e8-9723-5c79b0d09009.png)
![harryi3t___postman_slack](https://user-images.githubusercontent.com/5207331/45360300-c06bce00-b5ec-11e8-928a-97317665b4c3.png)

**Comment by gitterrost4** [comment]
All people installing postman through their package manager will have this problem. Auto-Update is also not a very good solution for this, because in these cases, the package manager should handle the versioning.

However, I am on Arch and installed postman through AUR. The PKGBUILD could probably be modified to first clear the installation directory. That would move this issue to the AUR.

**Comment by harryi3t** [comment]
@gitterrost4 We don't have an official package manager as of now. We stronly recommend downloading all the apps from our official website http://getpostman.com/apps
We can't support applications downloaded from unofficial package managers. If there is any issue with the auto-update, please do report it here as a seprate ticket.

**Comment by wadtech** [comment]
The above has solved it for me, I was overwriting the /opt/Postman directory with the latest version through a little script since there's no apt package, not realising that would be an issue.

I've fixed my directory permissions instead now so auto update should work

**Comment by fatestapestry** [comment]
If installing  on Ubuntu 18.04 with `snap`, you  will face the same problem... also permissons issue as installed with root under `/snap/`

**Comment by JanaGiovanna** [comment]
I've just migrated from Chrome-plugin to the latest Postman app v.7 on Windows-64 and I face the same issue...searching for solution here...

**Comment by lazabazsa** [comment]
I'm facing the same issue. Windows 10 with the latest v7.0.6. Tried to fallback to v6.7.4 (which as I remember worked correctly) has the same issue. What else should I check?

**Comment by apraka2** [comment]
Facing the same issue after installing Postman-win64-7.0.6-Setup on windows 10. Any pointers for solving this?

**Comment by harryi3t** [comment]
@lazabazsa @apraka2 Try switching to some other environment and see if the problem is with one or all environments.
Also, check for any errors in the console (View -> Developer -> Show DevTools (Current View))

If you are able to consistently reproduce this, please let us know. If you can take a screen recording, that would be very helpful.

**Comment by HoLengZai** [comment]
I got the same issue.. I'm using the version 7.0.7
I have reinstalled the app completely and i got the same issue.
My workaround is to copy the Initial value column value to the Current Value column value in the Environment variable and then it works.

So it seems that when i create a new environment variable and you set value in the initial value column only (current value is empty since you have , you will get the issue.. When you press the Send button, Postman app don't read (skip?) the initial value column value... So on my understanding is the app should check if current value column value is empty, it should read the initial value column value as specified on the tooltips. On the other hand, what's happen if we want to have the current value to be empty for a specific request?.. Postman will automatically read initial value column value then?

**Comment by whithang** [comment]
i'm getting the same issue on macOS Mojave. the app is installed in the applications folder

**Comment by harryi3t** [comment]
@whithang Is the issue happening on the `My workspace` or all workspaces?
Can you try doing the same on a new workspace? If that works just sign-out and sign-in back.

**Comment by bgaprogrammer** [comment]
@harryi3t I'm facing the same error on Mac OS Mojave (10.14.5), the postman version is: 7.2.2, no variables are replaced for any environment, I'm working on my workspace.

Edit: After sign out from postman and sign in back, it's working now

**Comment by codigoalvo** [comment]
Same problem here. I tried with 32 and 64 bits 7.2.2 version for Windows and with the Canary version. When the environment variable IS EMPTY the value is displayed as %7B%7Bvariablename%7D%7D . I tried to move from the account and relogin user, tried different folders in the system. Nothing seems to solve the problem.

**Comment by DallasO** [comment]
Same issue on first install, Debian Buster, not signed in to postman.
Collection variables work fine. Global and Environment say they are valid when you hover over them in the URL bar, but sending the request sends `%7B%7Bvariablename%7D%7D`.

Will try downgrading and then updating like others suggest.
postman v7.2.2

**Edit**: I closed and reopened the app and it started to work.
It also gives me errors about the default Postman.desktop file being incorrect, but that started to work by itself - so maybe a Gnome issue?

**Comment by brandonw** [comment]
> So it seems that when i create a new environment variable and you set value in the initial value column only (current value is empty since you have , you will get the issue.. When you press the Send button, Postman app don't read (skip?) the initial value column value

I have experienced this issue as well. Removing everything from the install dir and installing a new version had no effect-- only setting current value mitigated the issue.

**Comment by denitsa-md** [comment]
Encountering the same issue on v7.6.0-canary02. I am setting some Referer and Origin headers via environment variables and they're not being updated after changing the environment variables.

**Comment by gofydo** [comment]
i'm running Version 7.8.0 (7.8.0) and running in the same issue.

**Comment by michaelhamel-vertex** [comment]
I appear to be having this issue on Version 7.8.0 (7.8.0). Restarting the desktop app did not resolve.

Desktop App. MacOS 10.14.6.

Environment variables appear ineffective. Collection variables work ok.

Using app while not signed in.

**Comment by holmesjr** [comment]
I'm having the same issue on version 7.9.0 on a Mac.

**Comment by HichamOUAHIDI** [comment]
Hi I have the same issue 
![image](https://user-images.githubusercontent.com/18144576/67272721-58f5a280-f4bd-11e9-876f-f4bdb2863488.png)

**Comment by HichamOUAHIDI** [comment]
I'm having the same issue on version 7.9.0 on a windows 
![image](https://user-images.githubusercontent.com/18144576/67272973-dcaf8f00-f4bd-11e9-9cb5-71f8e8a108ee.png)

**Comment by Mujaddadi** [comment]
Having the same issue in version 7.9.0 on Windows 64 bit.

**Comment by Mujaddadi** [comment]
Ok now for me the collection variables worked but not the global and environment

**Comment by mburke05** [comment]
this is still an issue on windows 10, has there been any update?

**Comment by eliasaj92** [comment]
My environment variables aren't being read either on Windows 10 on 7.18.1

Collection variables work fine however

**Comment by melt7777** [comment]
Same here, added one variable and it doesn't resolve, but the existing ones can be changed. Win10
v7.20.0 is the latest version.

**Comment by glrnz** [comment]
+1 Got the same problem on Windows 10
![image](https://user-images.githubusercontent.com/61217782/77746083-5e03e280-7057-11ea-95e4-1064903869fc.png)

**Comment by ErikVanDenHoorn** [comment]
Signing out and signing in again solved the issue for me.

**Comment by Martin-Suska** [comment]
Thanks @ErikVanDenHoorn , worked for me.

And for all not being able to logout (as me) - https://community.postman.com/t/where-is-the-logout-button/1763

**Comment by githugt** [comment]
I think I found out at least one possible way this happens.
In my case, I had a part where I was cleaning up at the start. Here I would try to clear cookies for the 127.0.0.1, but since the whitelisted domain wasn't right, scripts past that would actually run, but the context of it was not available.

What does mean?
Basically, After the cookie clearing script, I was setting a few collection variables.
I had logs and tests for all of them. Both in that script itself and in other requests as well, which would validate that the collection variables existed.
But the same values would somehow still not be propagated to the actual request itself.

Here's a collection that can explain the problem.
[Postman variable propagation error.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/5856015/Postman.variable.propagation.error.postman_collection.json.zip)


![error screenshot](https://user-images.githubusercontent.com/8955849/105494845-65306700-5ce1-11eb-9568-96b971ea5444.png)

As can be seen from the above picture.
The first variable executes just fine.
Then the cookie deletion part fails because it does not have access due to improper whitelisting.
Then the other bit executes as per the test and the console logs at least, but in reality, it actually does not (as can be seen from the test in the next request).

Seeing as this particular bug is already closed, I'll go ahead and create another bug so this can be addressed properly.

**Comment by Outwise** [comment]
Had this same problem, my env variable wasn't recognized, though I could use the pre-made variables in postman.
When I explicitly set the "current value" and re-saved the Env [as first mentioned here](https://github.com/postmanlabs/postman-app-support/issues/5039#issuecomment-479398872), it works!
This should probably automatically happen since it auto-populates, and wouldn't be expected to need the user to explicitly filling out again.

**Comment by marciobarcellos** [comment]
Postman v8.7.0 client on Ubuntu. Collection variable partially working: don't know why, but only my 'refresh_token' variable is not being replaced. If I replace it with it's content, it works. But I'm using 4 more variables at the same call, and they are working properly. Maybe because refresh_token is a really loooong string.

**Comment by oyeraghib** [comment]
I was having the similar issue till the time I saw that I was not saving it. Saving it solved the issue.

**Comment by murtazakhussain** [comment]
This is still the issue, I am using mac big sur and postman version v9.1.3

**Comment by Mds92** [comment]
I have the same issue, version 9.18.2

**Comment by malvikach** [comment]
@Mds92 Please provide more details about the issue you are seeing, possibly with a screenshot. 

You can also use console.log(pm.environment.get()) to log your variable and view the values on the [console](https://github.com/postmanlabs/postman-app-support/issues/9590). This will help clarify if the variables have some problem.

**Comment by Mds92** [comment]
It takes me around 2 hours :)) 
finally I found the problem:
I was using the following template:
```js
{{ jsonObj }}
```
I changed it to 
```js
{{jsonObj}}
```
I mean, removing the spaces.
It worked

**Comment by malvikach** [comment]
@Mds92 Oh, I see! 

A variable that is not replaced would be present like this:
<img width="565" alt="Screenshot 2022-05-16 at 11 23 18 AM" src="https://user-images.githubusercontent.com/89449769/168528047-40d5fb4b-8b8f-42f2-8e3c-bd300ca9ea4f.png">

I wanted to check if you were not seeing this variable as unresolved. Read more about this [here](https://learning.postman.com/docs/sending-requests/variables/#fixing-unresolved-variables)

Nevertheless, I think Postman could help identify problems like this so you do not spend that much time debugging errors like above. I have logged this as a feature request [here](https://github.com/postmanlabs/postman-app-support/issues/10912). 

Please feel free to add your thoughts to it. And thanks for your feedback.
