### ISSUE TITLE
Allow Collection-scoped variables to be modified in test scripts

### ISSUE THREAD

**Issue by bjohnso5** [a85/POSTMan-Chrome-Extension#5053]
**Is your feature request related to a problem? Please describe.**
Not being able to modify collection variables in a dynamic way.

**Describe the solution you'd like**
A `pm.collection.set(...)` function would be very helpful for some collection-specific work that I'd like to be able to accomplish (for example, setting a `next` query string parameter that is specific to the collection the tests are running in).

**Describe alternatives you've considered**
I am currently using `pm.globals.set(...)` to accomplish my goal, but it makes using semantic names like `next` challenging because that is a strange thing to throw into the global scope, but namespacing variables is also a clunky solution.

**Comment by vgosai86** [comment]
+1
This will be definitely a good feature to have.

**Comment by shamasis** [comment]
- to make entire collection available in sandbox??
- then allow update of session variables of collection

**Comment by jvretamero** [comment]
+1
This will avoid collection-only variables being created within the environment

**Comment by AndraSafe** [comment]
+1!

What is the point of calling them variables if they can't be set?! Might as well call them collection constants... and they are mostly useless that way... It makes no sense to have to set environment variables that are only used for one collection. For instance if i use my first request to dynamically load the values i need as parameters in the next requests. Not to mention that i haven't found any way of programmatically coupling an environment to a collection, so i have to make sure all my team pays attention when i tell them to use this environment with that collection. Too much manual input, and thus errorprone. I am thinking there must be a way to do this via newman, but since newman isn't working either that's hardly a solution for me (i get "newman is not a command" no matter what i do and i am past frustrated with trying to make it work). 

Ideally, there should be variables (aka they can be accessed and set via script) at collection level, and at folder level. That matches the concept of variables from OOP, and it makes sense. Now you are basically forcing us to either use a variant of global variables (globals or environment, they are still global to all collections) or the most basic local variable (destroyed at the end of the request).

**Comment by janimationd** [comment]
This would make our testing so much easier and more modular!

**Comment by shamasis** [comment]
These are great pointers for us to start. Updating collection variables from scripts was waiting for some related aspects to first finish. You’ll be glad to hear that we have started work on patching this up.

**Comment by codenirvana** [comment]
Postman v7.9.0 added support for new **pm.collectionVariables** API which gives you more control over interacting with the collection scoped variables.

Just like `pm.environment`, it's an instance of [VariableScope](https://www.postmanlabs.com/postman-collection/VariableScope.html) and has all the methods available like:
```js
pm.collectionVariables.set
pm.collectionVariables.has
pm.collectionVariables.get
pm.collectionVariables.unset
```

**Comment by AndraSafe** [comment]
that's great that we can now use collection variables this way! It would be great if we could see them easily as well... like we have the eye icon to see environment and globals, could we also have the collection variables listed there? it could be more of a variables quick view, i guess

**Comment by mpern** [comment]
Please add `pm.collectionVariables` to the docs 🙇 

https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/

**Comment by Yon2068** [comment]
I found a bug in collectionVariables,
Variables in the "runner" window cannot synchronize with those in the main window.

**Comment by william-wallace-simplisafe** [comment]
Since this is a duplicate of 6610, could a doc change be made to the description of collectionVariables? collectionVariables are **_NOT_** "available throughout the requests" within a collection.

'Collection variables are available throughout the requests in a collection and are independent of environments. Collection variables don't change based on the selected environment. Collection variables are suitable if you're using a single environment, for example for auth or URL details.'

**Comment by mandar-lad** [comment]
> I found a bug in collectionVariables, Variables in the "runner" window cannot synchronize with those in the main window.

I have encountered same issue while running performance tests using the postman runner
