### ISSUE TITLE
Transfer variables between endpoints

### ISSUE THREAD

**Issue by mp222** [a85/POSTMan-Chrome-Extension#5059]
Hi,
for a long time I was looking for a solution to my problem. We've been trying a lot of different solutions. I wonder if you can help me.
There is such a thing.
I have two endpoints in which I want to use the same randomly generated reference numbers (as parameters). 
E.g. 
1st endpoint
Parameters:

<img width="767" alt="sc 2018-08-21 15 11 37" src="https://user-images.githubusercontent.com/38833999/44403395-9c205280-a554-11e8-843b-6c8c4724110c.png">

2nd endpoint
the same parameters from the firs endpoint.

In environment I define them for example like this:

![image](https://user-images.githubusercontent.com/38833999/44403568-1bae2180-a555-11e8-9860-28d7f033ec33.png)

The problem is that the reference and subreference doesn't occure in response (json).
So I have to initialize them, put into parameters, transfer to second endpoint.

Every time we were trying to do that, new random reference was generated in every endpoint.

What should I put in pre-request script and test fields to make it work?

Help! :)

**Comment by sivcan** [comment]
@mp222 
I couldn't exactly get what your use-case is and I might be wrong with the following answer.
But just in case it helps you out I'll explain some ways you can work around with dynamically generated variables.

Also, if it didn't quite help you then could you share a collection explaning your use case? 

Here are two methods you can use to work around with dynamically generated query params.
<hr />

**_Method 1:_**
There's no way you can access these since these variables generate a value only at the runtime of the request.
But surely, you can write a small script to do exactly the same tasks.

In the pre-request script of your first request:
```javascript
let randomInt = _.random(1, 1000),
    timeStamp = Math.floor(Date.now() / 1000);

pm.globals.set('randomInt', randomInt);
pm.globals.set('timeStamp', timeStamp);
```

![image](https://user-images.githubusercontent.com/12631777/44445680-93388b00-a5ff-11e8-943e-d1b1dce28f76.png)


Also, in the second end point just put the same parameters as of the first request.
After the execution of the first request, the globals will be set and on running the second request the params will be resolved from the globals which were used previously.

<hr />

**_Method 2:_**
In your **Test script** (not Pre-request) of the 1st request you can do the following to access the query params that were sent in the request like so:

```javascript
let queryParams = pm.request.url.query;

console.log(queryParams);

queryParams.map((p) => {
    pm.globals.set(p.key, p.value);
});
```

So now you've the globals set with the variables generated at runtime and you can use this same globals in the next request.

![image](https://user-images.githubusercontent.com/12631777/44446227-bb28ee00-a601-11e8-8ec9-2df65693b65d.png)

**Comment by mp222** [comment]
Thank you so much! :) First method works, later I will check the second one :)

**Comment by sivcan** [comment]
@mp222 Awesome!
I'll be closing this issue.

Feel free to reach out to the [Postman Community ](https://community.getpostman.com/latest) for help and how-to's.
