### ISSUE TITLE
UI text selection issue, focus changing while clicking and dragging in order to select text

### ISSUE THREAD

**Issue by DaliborTakac** [a85/POSTMan-Chrome-Extension#5078]
When trying to select text in text box (for instance http request headers or environment quick look popup)
 and when dragging out of the bounding box of the input ui element selection changes to some weird rectangle and sopy / paste operations do not work on the text as is expected. This makes it pretty difficult to work with long inputs (jwt tokens etc)

Expected behaviour:
input focus remain in the input element and text remain selected, no switching to the rectangle selection

Incorrect behaviour can be observed in the attched gif.

OS: Windows 10 build 1803, 64bit
postman version 6.2.5 (latest at the time), standalone (not chrome extension)

![2018-08-22_10-22-24](https://user-images.githubusercontent.com/18527233/44526241-b3da1100-a6e3-11e8-9445-c2e04207738a.gif)

**Comment by DrJacobHolden** [comment]
This is incredibly frustrating. I've always spent at least 5 minutes of every working day cursing Postman for it's terrible UX but this has increased that to 15 minutes and added a new step: Googling Postman related vitriol to find others who share my pain.

**Comment by kaustavdm** [comment]
Also reported on the Postman community forum: [How do I disable the dragable selection box?](https://community.getpostman.com/t/how-do-i-disable-the-dragable-selection-box/6435)

**Comment by katlimruiz** [comment]
+1, it seems this has not been resolved yet :(

**Comment by johnengstrom** [comment]
I would like to pile onto this request.  The fix is super simple—a checkbox in the preferences for "disable drag to select"

A nicer option would be a keypress that enable the drag function.  

Why is this a problem? When you go to edit a value and you are not careful you end up dragging and selecting the line item, then you click "delete" as you want to delete a value but you end up deleting the row—and there is no undo—because the fussy interface switched to select mode.

How about you need to hold the "alt" key when you drag and that enables the drag selection on multiple rows.

If a "feature" results in losing data and there is no undo then that likely breaks about a dozen rules and best practices of UI design.

If a feature causes teeth gnashing and vitriolic comments, well, in my opinion—for whatever that's worth—that seems to warrant a priority fix!

**Comment by katlimruiz** [comment]
> A nicer option would be a keypress that enable the drag function.

nice suggestion

**Comment by pankajk07** [comment]
Fixed in Version app 7.22.
