### ISSUE TITLE
Credentials for NTLM not refreshed when using variables.

### ISSUE THREAD

**Issue by Yawnder** [a85/POSTMan-Chrome-Extension#5111]
**Describe the bug**
If you set NTLM authentication at the collection level, using variables, and then change the variable values, the previous authentication result is used.

**To Reproduce**
1. Set the variable for {{Username}} and {{Password}} to whatever would work for a given api.
2. Create a collection, and set authenticaiton NTLM such as:
![image](https://user-images.githubusercontent.com/19433589/44808953-7d950980-ab9b-11e8-85d9-ce544a870411.png)
3. Create a request (get for example) in that folder, using inherited permissions.
4. Execute a request, and see that it succeeds.
5. Change the value of the variable {{Username}} to "Potato" (assuming that doens't match with the password...)
6. Run the request again (without restarting Postman) and see that the previous authentication still happens.

Workaround:
After the previous 6, close postman, re-open it, then do the previous 6.

**Expected behavior**
Implicit.

**App information (please complete the following information):**
 - App Type: Native Windows 10 64bit
 - Postman Version: 6.2.5

**Comment by harryi3t** [comment]
The issue is not with variables but around how NTLM works.  Once NTLM auth is used, it establishes a TCP session which is re-used. What this means is that once you pass correct credentials for NTLM and send a request, after that even if you remove the auth or use wrong credentials, it will still work.
The current workaround is to close the connection by sending a request with header `connection: close`
Can you try this and let us know if that works?

**Comment by codenirvana** [comment]
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.
