### ISSUE TITLE
JSON validator is passing test for wrong values

### ISSUE THREAD

**Issue by Muralinie** [a85/POSTMan-Chrome-Extension#5119]
I have the the code snippet to validate the JSON Data as given below :

         pm.test("Verify for AuthCode ", function () {
            var jsonData = pm.response.json();
             for(i=0 ; i<= jsonData.length;i++){
                     pm.expect(jsonData.docList[i].docMetadataMap.authLevelCde).to.eql("MY_DEFAULT");
                               
            }
           
            });
My response Body : 

{
  "totalDocCount": 2,
  "docCountInRes": 2,
  "docList": [
    {
      "docId": "1081800298",
      "docMetadataMap": {
        "docNum": "1081800298",
        "number": [
          {
            "number_num": "15712054",
            "number_type_cde": "2"
          }
        ],
        "docRecvdDateTime": "2016-04-05 05:00:00.000",
        "authLevelCde": "MY_DEFAULT",

      }
    },
    {
      "docId": "9455228",
      "docMetadataMap": {
        "caseId": "9455228",
        "number": [
          {
            "number_num": "15712054",
            "number_type_cde": "2"
          }
        ],
        "docRecvdDateTime": "2015-04-15 05:00:00.000",
        "authLevelCde": "NOT_MY_DEFAULT",

      }
    }
  ]
}

Code snippet always passes the values in the test even though i have the wrong value for authLevelCde in 2nd record.

**Expected behavior**
Test should fail for the second record  

**App information (please complete the following information):**
Postman for Windows
Version 6.2.5
win32 6.1.7601 / x64

**Comment by sivcan** [comment]
@Muralinie That's because you're trying to run the for loop on the JSON data and you're saying `jsonData.length` however, your jsonData is an object and not an array thus it doesn't have a length property, in your case it's being returned as undefined.

In the lines further below, you're asserting on the docList array which was what you wanted to achieve.
So, to fix that you've to iterate over the `jsonData.docList` and thus fix your for loop like so:

```javascript
pm.test("Verify for AuthCode ", function() {
    var jsonData = pm.response.json();
    for (i = 0; i <= jsonData.docList.length; i++) {
        pm.expect(jsonData.docList[i].docMetadataMap.authLevelCde).to.eql("MY_DEFAULT");
    }
});
```

Gives the following failure as expected:
![image](https://user-images.githubusercontent.com/12631777/44942979-339a6680-addb-11e8-9745-2c38071aec03.png)
