### ISSUE TITLE
Why POST Request from POSTMAN returns empty?

### ISSUE THREAD

**Issue by moschel26** [a85/POSTMan-Chrome-Extension#5157]
My header in the postman like this : 

[![enter image description here][1]][1]

My body like this : 

[![enter image description here][2]][2]

In the routes laravel lumen, I check like this :

    $router->group(['middleware' => 'auth'], function ($router) {
        ...
        $router->post('/sales-order', function (\Illuminate\Http\Request $request)
        {
            echo '<pre>';print_r($request->all());echo '</pre>';die();
        });
    });

The result in the postman return empty array like this :

[![enter image description here][3]][3]

How can I solve the error?

  [1]: https://i.stack.imgur.com/A6ji8.png
  [2]: https://i.stack.imgur.com/s92df.png
  [3]: https://i.stack.imgur.com/TNgjO.png

**Comment by raypanjaitan** [comment]
Don't you think that your request shows that you have an error on the line 4,? The double quotes.
Or is that intented?

**Comment by numaanashraf** [comment]
@moschel26 Please open the Postman Console (View > Show Postman Console) to check the request sent by Postman. Since your screenshot looks like an invalid JSON, it might affect how your server parses it and makes it available via the $request methods. Please feel free to reach out to the wider Postman community for further help with this issue - https://community.getpostman.com/
