### ISSUE TITLE
Collection sidebar filtering causes the app to go into unrecoverable state

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#5228]
**Describe the bug**
Filtering in the collection sidebar causes the app to go into unrecoverable state

**To Reproduce**
1. Go to a workspace
2. Type something in the collection sidebar
3. App goes into unrecoverable state with generic error message: Something Went Wrong. Postman has encountered an error. If this problem persists, contact us at help@getpostman.com

**Expected behavior**
Collections within the sidebar should be filtered based on my query

**Screenshots**
![image](https://user-images.githubusercontent.com/2700229/45923446-beb2dc00-bf03-11e8-8ce1-9f7ddd5cf11e.png)

**App information (please complete the following information):**
- Postman for Windows
- Version 6.3.0
- win32 10.0.17134 / x64

**Additional context**
No errors in the shared console. One error in the current console.

![image](https://user-images.githubusercontent.com/2700229/45923459-3d0f7e00-bf04-11e8-9ee5-423bdd62ff88.png)

**Comment by kamalaknn** [comment]
Looks like some of the components were assuming method to always be present. With a recent change in one of the pre-production channels when a request is created without a method(the rest of the systems would work assuming GET), these components seem to be crashing. We'll add a fix to make sure the components do not crash in the next versions.

We'll also plug the source that was creating the request without method for time being to support current versions out there.

**Note:** This only happens when you are using the pre-production channels.

**Comment by sujayvenaik** [comment]
Hi, we have addressed this issue as part of various improvements we have made to how tabs work in Postman. These changes are up available on our canary channel (https://www.getpostman.com/canary) today and would soon be available on the stable channel. Do try these out in the canary and let us know.

**Comment by sujayvenaik** [comment]
This issue has been fixed and is available on the stable channel (v6.4.x).
You can update the app to the latest version.

Thanks again for writing in and reporting this issue.
