### ISSUE TITLE
Collection Runner, no env vars resolving

### ISSUE THREAD

**Issue by Pazns** [a85/POSTMan-Chrome-Extension#5267]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
By the Collection Runner,
the first request is correct, with `{{url}}` being resolved to `http://something.something.com/` as expected.
The second one fails miserably with the actual url being... `{{url}}`.

Yet, when using the collection manually everything is working perfectly.

**To Reproduce**
1. Have a collection with a bunch of simple GET requests.
2. Have all those requests containing one Env var within the url.
3. Launch Collection Runner for this collection
4. Run it with a specified environment.

Additional : the base url of my requests is `{{url}}`, which for each environment resolves to a different global env var.
For example, when using the Dev env, `{{url}}` is resolved to `{{url_dev}}`, which contains `http://dev.app.example` .
As I have dozens of services which are evolving rapidly, times 7 environments, it's easier to manage that way.

**Expected behavior**
Env var is resolved in each request, the request passes with the right url.

**Screenshots**
https://i.imgur.com/EfXhRoM.png
Obviously the url `{{sf_host}}/s?q=truc` is wrong.
The first request is working as expected, though. There, the `{{sf_host}}` was resolved correctly to `{{sf_host_dev}}` and then to `https://ftm-core.vpod0.....`.

**App information :**
 - App Type : Native App
 - Postman Version : 6.3.0
 - OS: Fedora 28 with kernel 4.18.9-200 64b

**Comment by harryi3t** [comment]
Hi @Pazns 
Do you have Postman installed in `/opt/Postman` directory and do you update the app manually by download, unzipping and moving files using the command line? If yes, the application files could be in inconsistent state. For this, you can quickly try out installing (unzipping) a fresh app in your home directory and see if that works.
Otherwise, could you share more screenshots or even a gif/screen-cast showing the whole process?
For this, you can use a dummy collection with dummy variables.

**Comment by Pazns** [comment]
Hello @harryi3t ,

indeed I proceed the way you write it.
I tried with a real new install instead of the old copypaste-after-copypaste way and, surprise, the collection runner doesn't do crazy things anymore.

I should have thought of this ! Lesson learned 😄
