### ISSUE TITLE
Unicode dramatically skews cursor position (among other strange happenings)

### ISSUE THREAD

**Issue by dylanh724** [a85/POSTMan-Chrome-Extension#5309]
When I insert unicode, for example, a crown (👑):
https://i.imgur.com/TQU1WwD.png

It causes cursor position to be dramatically messed up. Even when the unicode isn't detected and makes the "� " question mark, it offsets the rest of the cursor being in a strange position.

In the example screenshot above, do you see that \nt on the end? Well, that "t" doesn't actually exist. If I focus my cursor there, it'll actually focus on \n. If I backspace, it'll erase the "n" (NOT the "t"). If I delete, it'll bring the next line break up to the same line: The "t" is a ghost character.

If you delete the unicode, things return back to normal.

1. Paste unicode
2. Try typing after the unicode: The cursor is forever messed up and weird things happen, similar weirdness to if you zoom in on an "supposed-to-be-unzoomable" website.

Since Unicode is widely accepted everywhere now as a standard, it's probably a good idea to remember  to give some Unicode love ~

**Comment by myylow** [comment]
I have a similar problem when typing using unicode in Postman (for me, it happens when typing in Thai language). Something strange happens with the cursor, it skews way out of position and you can not accurately position it where you want to type. The problem gets worse the more you type, and makes Postman basically unusable to type in if using Unicode. It would be massively helpful if this can be fixed. 

Using Postman version 6.5.3 on MacOS Mojave. It happens consistently and is easy to reproduce, for instance type "พิมพ์ภาษาไทยไม่ได้" in the Postman textarea, and try to type more afterwards. It's not a new issue, it's been a problem for as long as I can remember.

**Comment by ninyawee** [comment]
Hello 👋 , any progress on this issue.

**Comment by dylanh724** [comment]
Just wanted to follow up on this issue - any progress? � ( << That's a wave emoji through POSTman)

**Comment by ninyawee** [comment]
> Just wanted to follow up on this issue - any progress? � ( << That's a wave emoji through POSTman)

A support guy told me via email that she reassign this to the dev team, but we can't expect the fix in the next release or any time soon.

**Comment by pankajk07** [comment]
Fixed as part of v7.24
