### ISSUE TITLE
UI ruined during saving examples

### ISSUE THREAD

**Issue by nikitasius** [a85/POSTMan-Chrome-Extension#5347]
**Describe the bug**
When you save output as an example. UI goes crazy.

**To Reproduce**
* Send a request
* get 404 error (or probably any data)
* save as example

**Expected behavior**
* as in previous version, guess it happends because:
  * you changed method how we swappend examples: before it was arrows, now there are droplist.
  * before it was in same window, now it's in separated

**Screenshots**
* before saving:
![image](https://user-images.githubusercontent.com/3670331/46812829-d4365b80-cd75-11e8-8cb7-cb946eb9a333.png)
* after saving
![image](https://user-images.githubusercontent.com/3670331/46812855-e31d0e00-cd75-11e8-959b-e1731a047f0c.png)

**App information (please complete the following information):**
 - native app
 - Postman Version 6.4.2
 - OS: Linux pentagon 4.9.0-0.bpo.5-amd64 #1 SMP Debian 4.9.65-3+deb9u2~bpo8+1 (2017-01-05) x86_64 GNU/Linux

**Comment by sujayvenaik** [comment]
Hey @nikitasius 

We have made certain changes to the way tabs behave with the new v6.4.2 so that user's don't lose data.

If you have a dirty tab, and you are trying to open another request/example then it will now open in a new tab.

Also, I noticed in the screenshots that the test in the Save Example button is a bit off, we will get a fix for that.

**Comment by sujayvenaik** [comment]
@nikitasius 
Closing this issue and will track the UI changes in the example view in a separate issue.

Thanks for writing in and reporting this.
