### ISSUE TITLE
pm.sendrequest() function is not verifying json response key and values 

### ISSUE THREAD

**Issue by nileshyeole** [a85/POSTMan-Chrome-Extension#5349]
I was trying to verifying specific values from JSON response for request which is triggered by pm.sendrequest() function. However below are my two observations:
1. I am not able to verify the values from json response. I can verify only status code and its text.
2. I cannot use that response (i.e. json) outside pm.sendrequest() function.

Postman version - 6.4.x 

Below is complete scenario step wise
1. Send Post request which will add a student.
2. To check student is added or not send Get request using pm.sendRequest() 
3. Response will have list of all students.
3. Verifying that “firstName should the same as POST request firstName”, but this verification is not working at all.

Snippet from Tests Tab:
```javascript
var jsonResponse = JSON.parse(responseBody);


pm.test("Status code is 200", function () {
    pm.response.to.have.status(201);
});


var url = postman.getGlobalVariable("baseUrl")+"/"+postman.getGlobalVariable("basePath")+"/list";
console.log("url: "+url);

pm.sendRequest(url, function (error, response){
    
    if(error){
        console.log("Error: "+error);
    }else{
        pm.expect(response).to.have.property('code', 200);

        getResponse = response.json();
        postman.setEnvironmentVariable("studentId",getResponse[getResponse.length-1].id);
        
        //This is not working
        tests["verify that firstName should the same as POST request firstName"] = 
        getResponse[getResponse.length-1].firstName === postman.getEnvironmentVariable("firstName");

    }
});
```

**Comment by sivcan** [comment]
Hey @nileshyeole ,
Couple of things I'd like to point out:

1. The `tests['some test'] = Boolean` format is an old format and I wouldn't recommend you using that. The only reason it still works in the latest apps is legacy support.
Since you're using the powerful feature `pm.sendRequest`, you'll have to use the `pm.test` API to get your verification working.
I advise you to always use `pm.test` from now on for any sort of tests that you'll be writing.

2. `postman.getEnvironmentVariable` also has a better alias called as `pm.environment.get` and similarly for globals it is `pm.globals.get`. To set a variable, you can just change get -> set.
Again, I'd advise you to use these. 
 
3. To access the response from `pm.sendRequest` outside the scope of the function, you'll have to store the response in a variable.

Following is the script that'll get you going:
```javascript
var jsonResponse = JSON.parse(responseBody),
  studentVerificationResponse = null;

pm.test("Status code is 200", function () {
    pm.response.to.have.status(201);
});


var url = pm.globals.get("baseUrl")+"/"+ pm.globals.get("basePath")+"/list";
console.log("url: "+url);

pm.sendRequest(url, function (error, response){
    if(error){
        console.log("Error: "+error);
    }else{
        pm.expect(response).to.have.property('code', 200);

        getResponse = response.json();
        
        // Instead of doing this, you can even move `getResponse` above pm.sendRequest
       // basically replacing studentVerificationResponse with getResponse
        studentVerificationResponse = getResponse; 
        pm.environment.get("studentId",getResponse[getResponse.length-1].id);
        
        //This will now work
        pm.test('verify that firstName should the same as POST request firstName', function () {
            expect(getResponse[getResponse.length-1].firstName).to.equal(pm.environment.get("firstName"));
        });
    }
});

console.log(studentVerificationResponse);
```

Further, you can always reach out to our [Postman Community](https://community.getpostman.com/latest) for questions related to how-to's and other queries related to postman.
We maintain this repository only for feature requests and bug reports.

I'll be closing this issue.
Let me know incase the above mentioned solution doesn't work for you.
