### ISSUE TITLE
Parameterised SOAP(xml) request

### ISSUE THREAD

**Issue by SDixit1** [a85/POSTMan-Chrome-Extension#5367]
Hi want to run my request multiple time with different data. Is it possible in POSTMAN?
For Example in below xml I want to sent request multiple time with different {{CPWN}}

soapenv:Header/
soapenv:Body
ipt:confirmOrder
ipt:in0
mes:CPWNRef{{CPWN}}</mes:CPWNRef>

**Comment by codenirvana** [comment]
@SDixit1 Can be done using the data files: https://www.getpostman.com/docs/v6/postman/collection_runs/working_with_data_files

Closing this issue since it doesn't follow our [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues).

Postman also has extensive documentation that you can refer to quickly unblock yourselves from issues such as this. Visit: https://learning.getpostman.com

Also, if your issue is more of an "how-to" help and not a product bug, we have an active user community forum that will help to solve them. Visit: https://community.getpostman.com
