### ISSUE TITLE
Dynamically Generate a Run in Postman Button

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5391]
**Is your feature request related to a problem? Please describe.**
It would be great if it were possible to generate a run in postman button dynamically. Leveraging the [API](https://docs.api.getpostman.com/) to create collections/environments is great but requires manual work to share via the RIP button.

**Describe the solution you'd like**
An API endpoint for generating a run in postman button. I'm not sure if generating the button by default and returning it in the response from the Create Collection endpoint would be feasible.

**Additional context**
[filed by Postman]

**Comment by Bauerna** [comment]
Hello!

This would be a really awesome addition for us, we have several use cases where we would like to generate that interactive button dynamically 👍

**Comment by prashantagarwal** [comment]
@Bauerna I would like to know about your use case. Postman's generated documentation already has one 'Run In Postman button' which is already upto date with you latest version of collection. Is there any other use case that can't be solved using this.

**Comment by Bauerna** [comment]
@prashantagarwal, we want to generate the button within the API. We are currently building an application that automatically generates a Postman collection. With this automatically generated collection, we want to expose the collection to users, specifically through the "Run in Postman" button. This is not currently possible explicitly through the API because the generated collection is not immediately exposed and the "Run in Postman" button uses a unique ID (not the collection ID) to expose the information to a user.

Does that make sense or is that not clear? I apologize for the late reply!

**Comment by prashantagarwal** [comment]
@Bauerna, this makes a lot of sense. Also, just out of curiosity, is there a particular reason that your application always generates a new collection rather than just updating the existing one. I would also love to know what objective you trying to solve using this. Is it being done as a workaround for versioning for that collection ?

I am just trying to better understand your use case here and try to evaluate the need of a much bigger feature request that would make your workflow seamless.

**Comment by Bauerna** [comment]
@prashantagarwal, we have a platform that allows users to identify "flows" within it. We plan on allowing the user to "record" a session within our system and have this be converted to a test suite. This test suite is a test that is run internally but can also be run externally using PostMan (since PostMan allows for scripts). This way, as the user updates the "flow," they are able to test both internally using our test framework and externally using PostMan, that everything is still working as intended. These tests will all be generated internally and then are converted to PostMan tests! A user can create a set of flows within their given environment and we have multiple users with their own sets of flows.

I'm trying to give enough information about our use case without disclosing more than necessary of course! Let me know if that makes sense :)

**Comment by lrobledo** [comment]
+1 for this issue. 

We use the Postman API to update our Postman collection. We have a RIP button on our docs page. When the collection gets updated via the API I can see the changes: 
- in the Postman App
- via the Run In Postman button through our [Postman docs page](https://learning.postman.com/docs/postman/api-documentation/documenting-your-api/),

But NOT through our Run in Postman link that I got from the 'Share' > 'Embed Link' tab from the Postman App. In order to get it to update _there_ I have to go to 'Share' > 'Get Public Link' then manually click the button that says 'Update Link'. 
(On that tab it specifically says, "This link does not update automatically when changes are made to the collection. Check out the Postman Pro API to access your synced collections.") But I am using the Pro API...

This is strange is because the _link itself doesn't change_. Clicking 'Update Link' doesn't provide me with a new link, it just updates the pointer on the backend somehow? 

Is there a reason for not automatically updating the RIP button links everywhere? And if so can we open up a way to be able to 'Update Link' via the API?

I don't mind adding the code for that, but considering all the work it's taken to get our docs updates completely automated it's slightly frustrating to have to go in and manually click a button as the final step.

**Comment by lrobledo** [comment]
Please let me know if there's any information you need from me to help resolve this issue. It would be a HUGE win for me and I'd be stoked to see it happen.

**Comment by mig8447** [comment]
I'd also love to see this happen

**Comment by dustinboss** [comment]
In case Google led you here, this is now possible: https://learning.postman.com/docs/publishing-your-api/run-in-postman/run-button-API/

**Comment by mig8447** [comment]
Maybe the link changed or I'm missing something but I don't see how to create them

**Comment by gitThingsDone** [comment]
For any collection in a public workspace, we can now programatically create a run in postman button by replacing `collection-id` and `workspace-id` in the code block below 
``` <div class="postman-run-button"
data-postman-action="collection/fork"
data-postman-var-1="<Collection-id-here>"
data-postman-collection-url="entityId=<Collection-id-here>&entityType=collection&workspaceId=<Workspace-id-here>"></div>
<script type="text/javascript">
  (function (p,o,s,t,m,a,n) {
    !p[s] && (p[s] = function () { (p[t] || (p[t] = [])).push(arguments); });
    !o.getElementById(s+t) && o.getElementsByTagName("head")[0].appendChild((
      (n = o.createElement("script")),
      (n.id = s+t), (n.async = 1), (n.src = m), n
    ));
  }(window, document, "_pm", "PostmanRunObject", "https://run.pstmn.io/button.js"));
</script> 
```
You can use the Postman API to [fork existing collections to a public workspace](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-214f4f93-cbb9-4b86-8a56-76a05eaab9fe), and to get the collection/workspace ids
