### ISSUE TITLE
imported numeric value different then the value being imported

### ISSUE THREAD

**Issue by dallyingllama** [a85/POSTMan-Chrome-Extension#5404]
## App Details:

```
Postman for Windows
Version 6.4.4
win32 6.1.7601 / x64
```
## Issue Report:
I have noticed the following problem when importing a specific value from a csv file to use in a data driven test.

### CSV File
The csv file is simple. The maximum valid value for my test is java long, which is
9223372036854775807 so this is what is in my csv file.

![csvdata](https://user-images.githubusercontent.com/10049458/47301910-66651c00-d620-11e8-905f-986ecff75d97.png)

I have converted 
[data.txt](https://github.com/postmanlabs/postman-app-support/files/2502019/data.txt)
the attached .csv to .txt so that I can upload it here since .csv seems to be prevented.
validId,invalidId
9223372036854775807,0

### Preview File & Run Collection
When I go to the collection runner and import this file and choose the preview data button it shows the following.

![previewdata](https://user-images.githubusercontent.com/10049458/47301832-2aca5200-d620-11e8-9273-30f52715e71c.png)

It imports the value as 9223372036854776000 also when running the test like this. 

https://myURL.com/{{validId}}/id
https://myURL.com/9223372036854776000/id

There is a workaround for this if you add quotes around the values, . It seems that postman assumes this is some sort of integer and then has trouble with the long integer. Adding quotes seems to force postman to treat it as a string.

I am reporting this as a bug because in the examples in the documentation and blog do not address this.

**Comment by gekonwi** [comment]
Similarly, the Collection Runner converts the CSV value `0001` to `1`. This caused false-negatives for us, where "0001" was a phone extension and our back-end couldn't find any contacts with the phone extension "1".

**Comment by vikiCoder** [comment]
Hi @dallyingllama @gekonwi 

We convert numbers without quotes in CSV file into JavaScript Number while parsing the CSV file in the Postman App. As a result, some numbers are changed because of the limitations related to how big number can be stored in JavaScript (learn more about it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#Properties)).

If you want to keep very large numbers or numbers with leading zeros as it is, you can specify them as a string in CSV file by wrapping the number in double quotes like below:
```
index,specialNumber
1,"000001"
2,"9223372036854775807"
```

However, for the users who don't want this behavior or want to have more control over parsing, we are planning to provide options related to CSV file parsing behavior in our long term roadmap. We will consider adding an option to parse specified columns as string by default. Other suggestions are always welcome regarding what options you would like to have when we add them.

**Comment by saswatds** [comment]
Closing this issue in favour of the options feature.
