### ISSUE TITLE
Environment variable not being resolved while sending the request

### ISSUE THREAD

**Issue by ansorensen** [a85/POSTMan-Chrome-Extension#5415]
I the same issue when i execute "{{endpoint}}/api/sequences/"

Could not get any response
There was an error connecting to %7B%7Bendpoint%7D%7D/api/sequences/.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

But it works if i pust the path "https://localhost:44323/api/sequences"

The "endpoint" is an env variable with "https://localhost:44323".

How can i fix this?

_Originally posted by @carodrigues in https://github.com/postmanlabs/postman-app-support/issues/3503#issuecomment-412030769_

**Comment by sivcan** [comment]
@ansorensen This issue looks similar to https://github.com/postmanlabs/postman-app-support/issues/5039 

Can you follow the [instructions](https://github.com/postmanlabs/postman-app-support/issues/5039#issuecomment-415727976) as mentioned by @harryi3t and you can read along  in the thread if your issue is the same.

Feel free to reopen incase your issue is different.
