### ISSUE TITLE
Setting to "Automatically persist variable values" does not do so

### ISSUE THREAD

**Issue by davidbeers** [a85/POSTMan-Chrome-Extension#5416]
**Describe the bug**
We are using Postman on Ubuntu 16.04 in a team environment. We have a very large suite of tests that were created with Postman version 5.3.2. Running with latest (6.4.4) the suite has problems with persisting environment variables from. Have tried toggling Persist Variables in the settings per [this support issue](https://github.com/postmanlabs/postman-app-support/issues/4357) but this doesn't help. 

Also having difficulties with 6.4.4 freezing up every 1-3 hours it is running. If I don't kill the app quickly enough when this occurs the entire system freezes and I have to reboot the whole machine.

For both these reasons it is important to me to be able to install the same version that my teammates are using the run our test suite.

**To Reproduce**
1. Go to https://www.getpostman.com/apps#changelog
2. Note that only newest two versions of Postman have download links
3. Try downloading directly, e.g. https://dl.pstmn.io/download/5.3.2/linux64 and get 404 status code

**Expected behavior**
Since Postman team says they cannot guarantee compatibility of old tests with never versions of Postman users need to be able to install any version of Postman.

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.6.4
 - OS: Ubuntu 16.04

**Comment by a85** [comment]
5.3.2 is not supported any more. However, all tests are backward compatible. So is the "Persist variable setting to make things backward compatible with people who rely on coupled tests across collections - which they ideally should not be doing but anyway. Execution of the test suite itself does not have to do anything with the setting. Please clarify what exactly is the problem what the persisting variables issue is. 

How exactly are your test suites structured and why is the persist variables setting important? 
Is it not persisting? 

Where are we saying that Postman team cannot guarantee compatibility of old tests? The Postman Runtime supports all tests written in all versions of Postman.

**Comment by davidbeers** [comment]
Sounds like I misunderstood and that the intention is to maintain 100% compatibility of old tests to new versions of the runtime. So, thank you for that! I don't remember where I read the comment that gave me this false impression.  But I do think I've found the problem with the new runtime that is giving us trouble.

Our application involves two services that share a database: one is write-only and used by network connected sensors, the other is a read/write API that powers our web app.  Because of this division our test suite involves POSTing to one service, then making GET requests to the API to verify that the posted data was rendered correctly.  For reasons I won't get into related to UI/API design each test case involves three requests. To communicate bits of state between the requests in Postman we rely on environment variables. Not ideal--I'd prefer to be able to chain requests up in a nicer way--but it has worked for us.

So what is the problem? Well.

I've discovered that in the older versions of Postman, setting an environment variable within a test automatically persisted the value to the environment, which seems normal to me: why would you set an environment variable if not to be able to use the value between different requests in a collection? In the new version the "Keep variable values" checkbox in the Collection Runner _defaults to unchecked every time the Runner is started_. I have verified that "Automatically persist variable values" is "On" in Settings and it seems to have no effect on the Runner.  I would expect that the switch in Settings would set the default for the corresponding switch in the Runner, but this is not the case.

It seems like this is the main problem I had in using our test suite after updating the runtime. I'd never had to fiddle with the "Keep variable values" checkbox while using the Collection Runner in the old runtime and now I have to select it every time I launch it.  That's a workaround, but a tedious one. If I forget and start doing a long run the data in the database gets way out of whack with the environment state and I have to do a cleanup operation before I can get tests to pass again. I'm updating the title of this issue to reflect that the persistence issue is the main problem.

The second problem, as I mentioned, is Postman freezing up the system. It doesn't seem to be a memory leak, more like a memory corruption that causes the screen to break up. In some cases I'm able to close the app, but most of the time the entire system is unresponsive and I have to do a forced reboot.  Extremely frustrating.  I can't be sure this is related to the 6.4.4 version or something else, but I didn't used to have this problem with 5.3.2.  I will make a separate issue for this problem.

**Comment by harryi3t** [comment]
@davidbeers You mentioned several (but related) issues. Let me answer your queries one by one


### 1. Problem with sharing state between requests
> To communicate bits of state between the requests in Postman we rely on environment variables. Not ideal--I'd prefer to be able to chain requests up in a nicer way--but it has worked for us.

If you would like to share some state between requests and do not want to persist it, I would recommend using local variables instead of environment variables.

So, Instead of 
```js
// Request 1 pre-request/test script
pm.environment.set('someDataRequiredByReq2', data);

// Request 2 pre-request/test script
let data = pm.environment.get('someDataRequiredByReq2');
```
You can use
```js
// Request 1 pre-request/test script
pm.variables.set('someDataRequiredByReq2', data);

// Request 2 pre-request/test script
let data = pm.variables.get('someDataRequiredByReq2');
```

### 2. The checkbox `Keep variables` in Runner has to be checked everytime
> I've discovered that in the older versions of Postman, setting an environment variable within a test automatically persisted the value to the environment, which seems normal to me: why would you set an environment variable if not to be able to use the value between different requests in a collection? In the new version the "Keep variable values" checkbox in the Collection Runner defaults to unchecked every time the Runner is started.

This looks like a bug. Earlier we used to store this state internally. We will fix this ASAP. Thanks for bringing this issue to our notice.

### 3. Relation between the global setting "Automatically persist variable values" with the setting in Runner "Keep variables values"
> I have verified that "Automatically persist variable values" is "On" in Settings and it seems to have no effect on the Runner. I would expect that the switch in Settings would set the default for the corresponding switch in the Runner, but this is not the case.

The global setting "Automatically persist variable values" is for persisting your `current values` to `initial values` whenever they are changed using scripts.
Whereas, the setting in Runner "Keep variables values" if for allowing any mutations made during the collection execution in Runner to persist back (to the current values). This setting was always present in Postman, but it used to remember the last setting. This will be fixed as mentioned in the point above.

For more information on this, you can check our documentations here https://www.getpostman.com/docs/v6/postman/collection_runs/using_environments_in_collection_runs
You will find a flow chart there which might help to understand the flow in which variables are updated.

### 4. Postman app freezing
> The second problem, as I mentioned, is Postman freezing up the system. It doesn't seem to be a memory leak, more like a memory corruption that causes the screen to break up. In some cases I'm able to close the app, but most of the time the entire system is unresponsive and I have to do a forced reboot.

I am not sure about this issue, we would need more data on this. Could you try opening the app from terminal while piping the output to a file. Keep using the app and if the app crashes, please share the log file with us.

**Comment by davidbeers** [comment]
Thanks for the thorough reply, @harryi3t. 

Question about local variables: what "container" are these local to? Requests in the same folder? Requests in the same collection? Requests in the same run executing multiple collections?  I can't find anything in the documentation about variable scope that explains this, only information about how variables that share a name override each other.

Thanks for working on that "Keep variable values" init bug. I'm not sure I understand the distinction you are making about the relationship between the global setting "Automatically persist variable values" and the Runner setting "Keep variables values".  Is it that the global setting will persist the modified values *between* runs and "Keep variable values" will persist them between tests (or collections) *within* the current run?  Again, the question of scope arises: do these settings apply only to global and environment variables, or local variables as well? 

I'll keep you posted about the issue of Postman freezing up, which I entered as a new issue here: https://github.com/postmanlabs/postman-app-support/issues/5431

**Comment by harryi3t** [comment]
@davidbeers 

> what "container" are these local to? Requests in the same folder? 

It's local to the collection being executed execution. So that would mean any request within the collection can access them. But, if you have multiple executions running of the same collection, they don't share the local variables.

> I can't find anything in the documentation about variable scope that explains this, only information about how variables that share a name override each other.

@ArifPMan Could you make sure that the above mentionedpoint is well explained in our docs?

> I'm not sure I understand the distinction you are making about the relationship between the global setting "Automatically persist variable values" and the Runner setting "Keep variables values". 

I think this is well explained on our docs here. I am attaching the flowchart from our docs page here for a better explanation
![image](https://user-images.githubusercontent.com/5207331/47635083-c3f5ed00-db79-11e8-8e1d-f176dd0b5122.png)
As you can see in the above chart, that the global setting is only applied after the current values of variables changes using scripts (either though sending a request in builder or running a collection in runner)
On the other hand the Runner setting applies after a collection run is finished. Is decides what to do with the modified variables (as a result of running the collection). If the setting is turned off the variables never get modified at all so the global setting never comes in the picture at all.

If you still have doubts/queries, please let us know. We want to make our docs as simple and clear as possible 🙂
