### ISSUE TITLE
Default Values in API when running in collection runner in Runner

### ISSUE THREAD

**Issue by mohit-sentieo** [a85/POSTMan-Chrome-Extension#5422]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When we are using a data file to run tests while in the collections runner, we use variables in our code like ` {{name}} `which come from the data file. However when running this api in the Build window there is no way to supply a default name value that can be used to run **only that one api** with data.
We tried using the pre-request scripts but it looks like the variables set in the pre-request script take precedence over the data file values.

**To Reproduce**
1. Create a simple api. Add a request param like name={{name}}
2. Create a simple data file.
3. Add a variable with pm.variables.set('name', 'MyNAME')
4. Run the collection runner - the name will be set as MyNAME not the one in the data file.

**Expected behavior**
Should be the name set in the data file.

**App information (please complete the following information):**
 - Mac Native App

**Additional context**
Is there any other way to be able to have this api use some default data when not running in a data file.

**Comment by sivcan** [comment]
@mohit-sentieo You can definitely work around with this.
You can access the data variables in the script using `data`.

So, in your request URL, you can refer to an environment variable instead of the data variable.
So instead of `name={{name}}` you can use `name={{correctName}}` where `correctName` is an environment variable.

Now,
in your pre-request script you do the following:
![image](https://user-images.githubusercontent.com/12631777/47601739-9af72000-d9f2-11e8-8f81-91a9cfb3cd87.png)
Code:
```javascript
let correctName = _.get(data, 'name'); // get the name from data variable
if (!correctName) { // if name doesn't exist, use a default value
    correctName = 'defaultValue';
}

pm.environment.set('correctName', correctName);
```

Sample JSON data to test this:
```JSON
[
  { "name": "Test" },
  { "randomValue": "123" },
  { "name": "Test" }
]
```
Result:
You can see the defaultValue was used for the second iteration when `name` was not defined in the data file.
![image](https://user-images.githubusercontent.com/12631777/47601773-0a6d0f80-d9f3-11e8-9584-87056e8e440a.png)

**Comment by sivcan** [comment]
@mohit-sentieo 
 The variables being set in the pre-request script are local variables and they definitely take precedence over the data file variables.

However, I am sure you'll be able to do this:
![image](https://user-images.githubusercontent.com/12631777/47601886-510f3980-d9f4-11e8-96cb-77c8d1102410.png)


```javascript
// Get the value from data file or use the default value
// We're using lodash here -  https://lodash.com/docs/4.17.10#get

let correctName = _.get(data, 'name', 'defaultValue');
pm.variables.set('correctName', correctName);
```

So you can check if the variable exists in the data file, it does then use that value otherwise use the default value.
You can't have the same name of both variables and since data variable would not overwrite the value of local variable as order of  precedence won't allow it. 

Reference for variables: https://www.getpostman.com/docs/v6/postman/environments_and_globals/variables

I'll be closing this issue.
Let me know in case you need further help with this issue.
