### ISSUE TITLE
Import with "schemes":["http","https"] always results in "https"

### ISSUE THREAD

**Issue by gintautassulskus** [a85/POSTMan-Chrome-Extension#5426]
**Is your feature request related to a problem? Please describe.**
Importing a swagger scheme with `"schemes":["http","https"]` always results in a hardcoded `https`, e.g. `GET https://localhost/endpoint`. There is no built-in option to switch from `https` to `http`. 

**Describe the solution you'd like**
Add protocol part as a variable, e.g.
`GET {{protocol}}://localhost/endpoint` which could then be configured accordingly.

**Describe alternatives you've considered**
Manually delete `https` from the swagger schema (`"schemes":["http"]`) and reimport.

**Comment by abhijitkane** [comment]
@gintautassulskus We'll expose this as an option in the UI (during the import). I wouldn't want to change the default to http.

There's no ETA on the update, though.

**Comment by localbubble** [comment]
@abhijitkane can you please allow it to be imported as a variable as well?
Because when imported schema as {{host}} for example, the variable is ignored and it's set to HTTP by default. 

This is pretty frustrating since it is the collection level and affecting all endpoints. 
Because it is not parameterized, each request needs modification before making an actual call, when you are working with two environments, which have different protocols (HTTP and HTTPS). before each request, you have to modify the protocol manually. 

If it was parameterized, I would have added this as an environment variable & whenever I change the environment, it would have been set automatically.

**Comment by abhijitkane** [comment]
@emre-yildirim Yep - that's what we're doing in the OpenAPI converter. The scheme gets added as a collection variable, which only requires you to make one change to switch b/w http and https.

**Comment by abhijitkane** [comment]
@emre-yildirim Yep - that's what we're doing with the OpenAPI importer. The scheme is added as a collection-level variable, and you only need to make one change to switch b/w http and https.

**Comment by localbubble** [comment]
> @emre-yildirim Yep - that's what we're doing with the OpenAPI importer. The scheme is added as a collection-level variable, and you only need to make one change to switch b/w http and https.

Perfect! Thanks for the clarification :)

**Comment by AngelLopezBellmont** [comment]
Superwe can not wait for it :)

**Comment by VShingala** [comment]
This issue should be fixed now. I have verified it, and is working in the latest Postman App v7.33. The new behaviour is exactly as mentioned in https://github.com/postmanlabs/postman-app-support/issues/5426#issuecomment-492974600.
