### ISSUE TITLE
eBay API Token Type of User Access Token not allowed

### ISSUE THREAD

**Issue by mcready85** [a85/POSTMan-Chrome-Extension#5434]
I've followed other threads on how to set up eBay API in Postman using OAuth 2.0 authentication type but upon clicking "Request Token" button a token is generated but I am unable to select "Use Token" button. Token Type is highlighted in red and reads "Only bearer token types are supported."

Does this mean Postman does not work with eBay's API? I am using Native App on Windows 10.

![capture](https://user-images.githubusercontent.com/44510698/47590721-30cf7400-d93b-11e8-8481-6339ba171e89.PNG)

**Comment by harryi3t** [comment]
@mcready85 The [RFC for Oauth2](https://tools.ietf.org/html/rfc6749#section-7.1) talks about two most commonly used `token_type`: `bearer` and `mac`
Since we do not support `mac`, we had put this check. But the issue here is that different providers are using a different non-standard token types but they behave like `bearer`.

But I think we can relax this requirement and allow using the `access_token` if it's present irrespective of the `token_type`

**Comment by mcready85** [comment]
Thanks @harryi3t Do you know when this bug will be resolved?

**Comment by vikiCoder** [comment]
Hi @mcready85,

This issue is fixed in the latest release of Postman App (v7.14.0). You can now use token returned by eBay API from the token manager window.
