### ISSUE TITLE
docs.postman-echo.com uses old API URL for some example requests

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5462]
Search "echo.getpostman.com" on [docs.postman-echo.com](https://docs.postman-echo.com/).

A few generated requests examples should show up that use this URL, instead of the current one: https://postman-echo.com/

**Comment by DannyMeister** [comment]
Just came to report this as an issue, since it led to erroneous results from copy/pasting from the documentation examples.  Still an issue, why was it closed? I presume if it was fixed that the updates would have been published to the public site between May 27 and Sept 11.

In the attached screenshot is one such example.  Correct url on the left, incorrect on the right.
![image](https://user-images.githubusercontent.com/7937829/64741264-7d715e80-d4bd-11e9-9090-130a2da32dba.png)
