### ISSUE TITLE
Postman's entry on Windows Control panel has Setup file's name

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5468]
### Describe the bug
Why **Postman** app installation details are so ugly on _Windows 10_? Is there a possibility to fix that in future release? Please take a look and compare **Postman** to other apps. Name should be just "Postman", company details should be added on the second row, there should be an icon also.

### Screenshots
![capture](https://user-images.githubusercontent.com/30025319/47848821-cd789280-ddcf-11e8-972d-32613145e182.PNG)

**Comment by jviotti** [comment]
This has been fixed in recent versions of Postman. The icon image is still broken, but we are tracking that separately (see https://github.com/Squirrel/Squirrel.Windows/issues/761).

![Screenshot 2022-01-19 132641](https://user-images.githubusercontent.com/2192773/150182853-f11ab6eb-c8ce-434c-9392-ca35c6f01a80.png)
