### ISSUE TITLE
Interceptor is not appending cookies to GET requests.

### ISSUE THREAD

**Issue by ngleav** [a85/POSTMan-Chrome-Extension#551]
It seems that every PUT, POST, DELETE request i make works fine, but every GET request fails to append the cookies from the browser.

I have recreated the issue on 3 different machines, You can clearly see whats up if you use developer tools to inspect the postman interceptor.

On a side note, I found no mention of the ability to use developer tools on the postman interceptor itself. If you're suing the interceptor, your API calls don't show up if you're inspecting the postman app itself. You have to be inspecting the interceptor app. This might be good information for some other people. I may have missed the mention of it though.

**Comment by existme** [comment]
I still have this issue.

**Comment by ginosian** [comment]
I have this issue too right now, on Friday I updated my Postman and this issue arise.

**Comment by sdnts** [comment]
Can you guys check if the cookie exists on Chrome? You'll have to head over to `chrome://settings/content/cookies?search=cookies`

Can you also try this on our native apps? These have an in-built cookie manager that will make this a lot easier. You can download native apps [here](https://getpostman.com/apps)

**Comment by ginosian** [comment]
I use native app for Windows. Yes, cookie exists in Chrome. I refreshed cookie several times and tried with both Chrome and Postman with Chrome request contains cookies, those same cookies in Postman doesn't work, coming null.

**Comment by sdnts** [comment]
@ginosian Ah, if you're on the native apps, then the cookie being set on Chrome won't matter. On native apps, the cookie will be visible in the app's Cookie manager. This can be opened using the `Cookies` button right below the URL bar.

I think you're confusing the Chrome app's cookie flow with the native app. The interceptor will not work with the native apps. You can either use the Chrome app + Interceptor or use the native app only.

To make sure you're on the native app, can you head over to Settings (Cmd+,) > About and make sure the modal says Postman for Windows?

**Comment by ginosian** [comment]
@madebysid 
I'm using Postman native Windows app, the interceptor is on. Cookies are set in Header this way 
Key - COOKIE   value -JSESSIONID=5679719368D4D1.........;  ROBOTSESSIONID=2C9853E062FB2BD..........

The same cookie is set in Chrome cookies, requests from chrome contain cookies, from Postman doesn't

**Comment by ginosian** [comment]
To just clarify I use native not the plugin for Chrome, like I use Postman as a separate software even when Chrome is not open.

**Comment by sdnts** [comment]
@ginosian If you're on the native apps, you don't need to use the interceptor. Cookies from the native apps are not related to Chrome in any way. You should not be seeing the Interceptor icon on the native apps. Can you send me a screenshot of your `About` screen?

**Comment by ginosian** [comment]
![postmanproblem](https://user-images.githubusercontent.com/9298142/29522272-b6f0d15a-8699-11e7-89bf-5c9003c4c472.png)

**Comment by ginosian** [comment]
Those cookies you see are not expired, absolutely the same request send from application from chrome contains cookies.

**Comment by sdnts** [comment]
@ginosian I see you're on the Chrome app. I can tell because I don't see the Cookies button right below the URL bar.
If your cookie is set in Chrome and the Interceptor is ON from the app (not from Chrome), you will need to remove the Cookie header from the request in your app. When the interceptor is ON, the request actually goes through Chrome, so the cookie WILL be attached from Chrome. It'll be like sending the request from the browser.

If you look at the screenshot I've attached, you'll see that my Interceptor is turned on, I have no headers, but a cookie is set (the Echo server returns whatever cookies are sent to it, which means the cookie is being sent correctly)

<img width="1577" alt="screenshot 2017-08-22 13 52 51" src="https://user-images.githubusercontent.com/7689783/29555755-3871d5f6-8741-11e7-9a29-7002de90946a.png">
