### ISSUE TITLE
Pre-Request Script Body Issues

### ISSUE THREAD

**Issue by g0rd** [a85/POSTMan-Chrome-Extension#5605]
.**Description**
I have a pre-request script body that has a nested structure as shown in snippet 1. With this kind of body I was getting a JSON parsing error. So, I tried Raw Data Mode as shown in snippet 2. This would mitigate the JSON parsing error but it will not resolve {{$guid}} to an actual value. It will send the request with the value of `id` being `{{$guid}}` and not some alphanumeric guid. 

This seems like a defeciency in parsing logic. 

```
'user': {
'id':"{{$guid}}",
'name':'sample_name',
'email': 'sample_email@sample.com'
}
```
```
mode: 'raw',
'raw': JSON.stringify(
{'user': {
'id':"{{$guid}}",
'name':'sample_name',
'email': 'sample_email@sample.com'
}})
```

**App information: **
Windows 64bit
Native app (version 6.5.3)

**Comment by matt-ball** [comment]
Dynamic variables like `$guid` can't be used in the sandbox environment right now:
https://learning.getpostman.com/docs/postman/scripts/postman_sandbox/#dynamic-variables

For what it's worth, all variables retrieved in sandbox environments need to use the programmatic methods rather than `{{myVar}}`
https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#accessing-variables-through-scripts

You can require the `uuid` module if you'd like to create your own GUID. More info on the modules you can require here:
https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/

**Comment by g0rd** [comment]
thanks @matt-ball! I will keep the issue open until I figure this out

**Comment by g0rd** [comment]
```
var uuidv1 = require('uuid')
....
'id' : uuidv1()
```

did the trick. Thanks once again

**Comment by ryanshores** [comment]
I am having similar issue, but I am not using the new dynamic variables. The API request has headers that also use the body of the request to authenticate. When I import `pm.request.body` I get the body but it doesn't get the variables. 

In body - raw I have
`{ "Url": "{{myVar}}" }`

In the pre-request script it shows up as 
`{ "Url": "{{myVar}}" }`
But I am expecting 
`{ "Url": "https://www.url.com" }`
