### ISSUE TITLE
Feature Request - TLS1.3 Support

### ISSUE THREAD

**Issue by jinliming2** [a85/POSTMan-Chrome-Extension#5628]
Is there a plan to support TLS 1.3?

TLS 1.3 Test: https://tls13.crypto.mozilla.org/

**Comment by slaman75** [comment]
We are still waiting for TLS v1.2 support:
https://github.com/postmanlabs/postman-app-support/issues/4677

No word at all...

**Comment by shamasis** [comment]
We are waiting for OpenSSL 1.1.1 update on NodeJS followed by migration to the same from our end. https://github.com/nodejs/node/issues/18770

**Comment by sam-github** [comment]
@slaman75 

> No word at all...

I may have missed your questions, can you point me to them?

@shamasis openssl 1.1.1a is on current, and on 11.x, and should come out in 10.x in the next LTS release that allows semver-minors, I believe that will be in April 2019.

As for TLS1.3 support, see https://github.com/nodejs/node/pull/26209

**Comment by sam-github** [comment]
I'm sorry, I didn't notice I'd followed a link out of the nodejs issue tracker and into postman. Please disregard above (unless there is something useful in it).

**Comment by cache-sk** [comment]
We are now in the middle of year 2020 and TLS 1.3 is still not supported. Since our security folks pushed our backend servers to use TLS 1.3 only, we can't use postman for development anymore.

I had to return to old deprecated chrome app, which is very sad, because it works...

Error: write EPROTO 4816:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:c:\users\administrator\buildkite-agent\builds\pm-electron\postman\electron-release\vendor\node\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1407:SSL alert number 70

**Comment by codenirvana** [comment]
@cache-sk We've added support for TLS 1.3 in Postman app v7.25.2 which will be available for everyone (_phased rollout_) soon. Till then you can use our [Canary app](https://www.postman.com/downloads/canary/) which already supports TLS 1.3.

**Comment by cache-sk** [comment]
@codenirvana That's very good news, thank you!

**Comment by saswatds** [comment]
Closing this issue.
