### ISSUE TITLE
Docs with custom domain not getting the favicon correctly

### ISSUE THREAD

**Issue by norchow** [a85/POSTMan-Chrome-Extension#5791]
**Describe the bug**
The favicon is not displayed in the documentation, even though it does exist.

**To Reproduce**
1. Publish a documentation in a custom domain (example: https://developers.bitex.la)
2. See favicon

**Expected behavior**
It should display the favicon loaded in https://bitex.la/favicon.ico

**Screenshots**
![image](https://user-images.githubusercontent.com/7334576/51343835-10b0dc00-1a76-11e9-8bbd-8985e5fb5152.png)

![image](https://user-images.githubusercontent.com/7334576/51343816-0393ed00-1a76-11e9-8dc1-90b1e42ea234.png)
 (i assume the line in the middle should not be there)

**App information (please complete the following information):**
 - Found it on Chrome 71.0.3578.98 (Official Build) (64-bit) for Mac OS (Mojave)

**Additional context**
It does not _always_ happen. Sometimes (less than 20% of the time) it renders the correct favicon.

Any fix and/or workaround is highly appreciated.
Thanks

**Comment by kartikjain26** [comment]
@norchow  Have you also setup a custom favicon in Postman Dashboard ( Team Settings page) ? 
If yes, then that will be loaded else it will be picked from your custom domain. I would suggest you to hard refresh your browser. The middle line `href=/favicon.ico` is needed to load postman default favicon from root incase there is no favicon on domain.
PS: you can also upload your favicon on postman dashboard's team settings page.

**Comment by norchow** [comment]
Hi @kartikjain26, thanks for your response.
I've just set up the favicon in the Team Settings page, republished the collection and hard-refreshed the browser, but no change has happened.

![image](https://user-images.githubusercontent.com/7334576/51391624-5078d180-1b11-11e9-8ba0-c2da2efed455.png)
![image](https://user-images.githubusercontent.com/7334576/51391654-638ba180-1b11-11e9-8b63-0d7bfa2c1a87.png)

Is there any more information i can provide to help you investigate this issue?
Thanks

**Comment by kartikjain26** [comment]
@norchow can you test this in multiple browsers just to make sure it isn't a chrome issue.

**Comment by norchow** [comment]
@kartikjain26 Well, in fact, it seems to be an issue with Chrome. It works fine in Firefox and Safari, at least for macOS.
Can you validate that and fix it for Chrome? 

Thanks

**Comment by godfrzero** [comment]
Multiple favicon tags have been added to maximize browser compatibility, since the behavior we're going for is to use the Postman icon as a fallback and the custom domain or uploaded favicon as the default. Since there's no standard way to do this within browsers, browsers allow multiple favicons to be specified, but their behavior varies when it comes to choosing the one to use. Some browsers use the first, others use the last, from the list of favicons which load. The "sandwich" arrangement you see here is meant to load the custom favicon if possible, in all browsers, and then fall back to the Postman icon if not available.

Bearing all of this in mind, there are other factors to consider as well: The favicon size. One interesting thing I noticed is that the favicon you've uploaded is 15x16 pixels. I can't be sure without diving into the browser codebase, but I'm guessing the non-standard (non-square) size here ends up being an issue. Would it be possible for you to try uploading a 16x16 or 32x32 icon?

We'll keep digging on our end in the meantime.

**Comment by norchow** [comment]
Hi @godfrzero, 
Thanks for the detailed explanation and for going deeper into this. You've been super helpful.

I've just tried resizing the icon and reuploading it. And it seems to work!  I've never imagined that was the cause of the unexpected behaviour, and even less given that Chrome is usually flexible and it was the only one with this bug.

I suggest that from your side, a validation can be included, to verify that the icon's dimensions are correct, that would have saved us some time.

In case i see again the issue, i will include more information here.
Thanks for the great support

**Comment by godfrzero** [comment]
Awesome, thanks for confirming that this was the problem! We'll work on streamlining the uploading experience. @vkaegis @sankalp0o

**Comment by Raja-Simha** [comment]
@norchow Thanks for reporting this issue. We now verify favicon size when it is uploaded and do not allow users to upload non-standard favicon sizes.

Closing this issue.

**Comment by icapuccio** [comment]
Hi @Raja-Simha,

I had the same problem but with a square favicon of 144x144. I changed it to 32x32 and then it worked in Chrome! 

It would be nice if there is a message beside the favicon's upload section that suggests using an image with a 16x16 or 32x32 resolution for better compatibility between browsers.

**Comment by vkaegis** [comment]
@icapuccio Thanks for the feedback! Could you make a separate Github issue for this so we can track it better? Having better instructions next to the upload section definitely makes sense.

**Comment by icapuccio** [comment]
@vkaegis Done! #6138

**Comment by vkaegis** [comment]
@icapuccio Thanks a lot! Will keep you updated on it's progress.
