### ISSUE TITLE
Get Collection name in Scripts

### ISSUE THREAD

**Issue by bugb** [a85/POSTMan-Chrome-Extension#5805]
I Google a lot about it but I cannot find out how to get Postman collection name from the current request (in test section).

Could you please give me some help?

Thank you a lot!

**Comment by numaanashraf** [comment]
@bugb Thanks for writing in. Could you help us understand your use case better? Why would you like to access the collection name in your scripts?

**Comment by bugb** [comment]
@numaanashraf The problem is suppose I have a collection, inside it I have 2 folders one is  for testing in  staging (for example the folder named: Staging) and one for testing production environment (for example the folder named: Production), the test scripts for each environment for each test case is almost the same except some scripts.
The different scripts is based on Staging or Production, if isInStaging then A else B.

I know I can set the name to determine Staging or Production in test case name and can get it with 
`request.name`  but I use a tool (this tool was not developed by me) to generate all test cases and because of this, all test cases in both Staging and Production folder has same name by order.

So I ask if we can have a feature that can get collection name or not.

**Comment by tix-arbi-setiawan** [comment]
possible for get collection name in script ?

**Comment by sajalshres** [comment]
Any update on this request?

**Comment by StrohmyerTR** [comment]
You can accomplish this by adding

`pm.variables.set('collection', 'collection_name');`

in the pre-request script of your collection.

**Comment by MichaelLeonardRavens** [comment]
The workaround `pm.variables.set('collection', 'collection_name');` is subject to copy-paste errors.  It would still be very helpful to be able to get collection name from a script.  My use case is that we create a correlation ID header for each request.  We need the correlation ID to be collection-specific so that we can narrow down requests to the collection they came from.

**Comment by william-wallace-simplisafe** [comment]
I'm looking for something like where `pm.info.requestName` can be used to print out the request name.  Is there an equivalent to print the collectionName?  Seems trivial.

**Comment by william-wallace-simplisafe** [comment]
Why might this be important?  An answer for Postman decision makers.  If implementing postman in conjunction with a reporting tool such as zephyrScale, The name of the test becomes critical.  I may have any number of API requests from different collections called "LOGIN".  When checking the results in the reporting tool, they will all look the same, and so differentiating these by naming the test with the collection name (`pm.test(${collectionName}_${pm.info.requestName} .  . .) distinguishes this request from others.

Because postman does not provide a simple way of doing this, collections need to set this, and all  test scripts need to have an extra step to fetch the collectionName. . . clunky

**Comment by likue** [comment]
You can use console.log(pm.execution.location), which gets you the name of the collection.

**Comment by vedkribhu** [comment]
Reference: https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#get-the-path-and-name-of-a-request
