### ISSUE TITLE
Cannot merge big collection (10k requests)

### ISSUE THREAD

**Issue by lhyla** [a85/POSTMan-Chrome-Extension#5830]
1. Forked a 'base' collection containing 200 requests, 
2. Added around 10k of requests to the forked collection. 
3. Clicked 'merge changes'
4. Received error 'Cannot merge changes' from Postman webapp

I exported the JSON and it has 600k lines. That`s an estimated size of collection when we will prepare all the tests which we want to prepare so basically I want to check how Postman will handle such a big collection. Currently, it cannot handle it.

**Comment by mccannt** [comment]
@lhyla Apologies for the late response. Are you still facing this issue? 
Our teams have not been able to replicate this, but we may be missing something as part of this. 

That being said we have made many improvements in the application since the time of this issue. Please try it on the most recent version and let us know.

**Comment by mccannt** [comment]
Closing this issue. If you are still experiencing this, please let us know.
