### ISSUE TITLE
Replace "failure" with "error" in Run a monitor API response

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5880]
It currently returns an empty array of failure while using Run a Monitor API even though when there are some failed tests - This is expected behavior as this is meant to show the results of errors in the monitor. However, at the same time, it is leading a confusion. Hence, request you to replace the term "**Failure**" in the response of **Run a Monitor API** with **Error** to avoid confusion.

![image](https://user-images.githubusercontent.com/40994626/52267428-faa08800-295e-11e9-9aa0-a19137bc9fee.png)

![image](https://user-images.githubusercontent.com/40994626/52267258-9a114b00-295e-11e9-8df0-712527204f63.png)

**Comment by deepakpathania-zz** [comment]
@Ramya-From-Postman I understand the concern here, I agree that it might lead to confusion in some cases, which can be dealt with by improving the documentation around the response structure. 

Since this is a public API, we cannot change the keys in the response body like this, a lot of people might be relying on the same for their use cases which would start breaking with this change.

**Comment by ArjunSingh-PM** [comment]
Since this is a public API, we will **not be changing** this key in the response body as lot of people might be relying on the same for their use cases which would start breaking with this change.
