### ISSUE TITLE
Team workspaces: Possible data loss when joining a new team

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#5948]
**Describe the bug**
When a Pro user is already part of a team with workspaces and is invited to join the new team, after joining, the old team is no longer displayed. Even after leaving the new team, the old team is not displayed.

**To Reproduce**
1. John has created Team A and the respective workspaces. 
2. Mike has created Team B and the respective workspaces.
3. John invites Mike to join Team A.
4. John accepts the invitation and is now part of Team A. He can no longer see Team B.
5. John leaves Team A but all workspaces from Team B are no longer visible. He is no longer part of any team.

**Expected behavior**
Mike should receive a warning that he cannot join Team A without leaving Team B first.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 6.7.3
 - OS: macOS

**Comment by preethammavin** [comment]
@vdespa, user is shown the following warning before he can accept the invitation to a new team if he already part of a team
'You are already part of a Pro team called "Team Name". Please leave the old team before accepting this invite.'

And he can only join once he has left the older team.

I am closing the issue as this is expected behaviour. You can write to us at help@getpostman.com so that can check for account specific issue if any
