### ISSUE TITLE
Clearing and unsetting values deletes it for everyone

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#5958]
**Is your feature request related to a problem? Please describe.**
We use globals to validate responses from different endpoints (one of our endpoints uses info from 5 other endpoints to validate the response), this means that we have checks to ensure that globals have been set (pm.globals.has("example")) that will inform the user of any other endpoints they need to run for proper validation. 
When switching between environments it's good to ensure that nothing from previous runs was set and therefore the first call in our collection clears all the globals. 
This works very well when one person is using the workspace, however clearing or unsetting variables deletes the entire entry for everyone! Meaning if someone else was running tests in parallel, all their values will be gone! (Everyone has "Automatically persist variable values" setting turned off).
This is not a major issue, as all the needed values will be set properly if all the requests are made (which is what we are doing currently), however as there is already functionality implemented for current and initial values, this in a way this can be seen as a bug. Ability to clear current values would also give confidence that nothing was missed and we are not using data from a different run to validate the response.

**Describe the solution you'd like**
When "Automatically persist variable values" setting is set to off, clearing and unsetting variables should only affect current values. On the UI this could be represented by having a red highlight over the value field.

**Describe alternatives you've considered**
We did consider checking if the value is an empty string or setting it to a value that we can check, however due to some value being generated randomly and empty strings could be a valid case, there is a slim chance of getting false positives.

**Comment by numaanashraf** [comment]
@VicKetchup Could you give us a sample collection to replicate this case at our end and help better understand your scenario?

**Comment by VicKetchup** [comment]
Sorry for late reply, please see attached Zip with a collection to test this issue with, as well as environment and globals files.
[Unset and Clear test.zip](https://github.com/postmanlabs/postman-app-support/files/3018452/Unset.and.Clear.test.zip)

**Comment by VicKetchup** [comment]
Any update on this?

**Comment by VicKetchup** [comment]
@numaanashraf can you please look into this, this is still causing issues for us, even with everything that we did to try to avoid it.

**Comment by codenirvana** [comment]
@VicKetchup I understand your use-case but the workflow with `unset` or `clear` can't be tied with the auto-persist values setting, at least with the current concept of variable sessions.

However, we are building RBAC for the environment (available in canary), and for viewer role, it works exactly like how you described i.e, update/delete current values without affecting other users in the team. This might not solve your problem completely but that's the closest solution/workaround I can think of.
Or, instead of unsetting the variable, you can try setting it to `undefined` and test for `undefined` with addition to the `has` check. 

Finally, I am not considering this as a bug... it's a feature request which requires a major revamp on the concept of the existing sessions, which we are already discussing internally.

Closing this issue here (tracking internally) as there are workarounds to unblock this and we haven't seen other users facing a similar problem.

**Comment by VicKetchup** [comment]
Hello, was wondering if this could be re-visited (or updated with any dicussions that happened internaly). 

Currently if viewer deletes (clears/unsets) variables by script, the current value of the variable will have a warning that it is deleted, however if an editor does same request, the variable will be deleted for everyone. Would love to have an option that would make deletion of variables by code by editor behave in the same way, where their current value is deleted, however does not affect others.
