### ISSUE TITLE
Unicode in get params causes missed redirect

### ISSUE THREAD

**Issue by roma-guru** [a85/POSTMan-Chrome-Extension#5974]
**The problem**
If server returns redirect (any 30x code), for example redirecting to "canonical" url with the same params (as it is in Django & Flask), then Postman behaviour depends on parameters data:
if it contains only ascii, redirect is followed correctly, otherwise no more requests are made and we "Could not get any response". Curl or any other http client doesn't show this behaviour.

**Steps to reproduce**
Here is simple flask app to reproduce the problem. It creates endpoint http://localhost:5000/test/.
```python
from flask import Flask
app = Flask(__name__)


@app.route("/test/")
def test():
    return "Good"
```
"Good" requests:
GET localhost:5000/test?q=Postman
GET localhost:5000/test/?q=Postman
GET localhost:5000/test/?q=🐨

"Bad" requests:
GET localhost:5000/test?q=Постман
GET localhost:5000/test?q=🦅

[Exported collection](https://www.dropbox.com/s/cmbhjukrh66f7sy/Postman%20Bug.postman_collection.json?dl=0)

**Expected behavior**
Redirect should be followed regardless of parameter content and encoding

**Screenshot**
![default](https://user-images.githubusercontent.com/1194340/53332863-65613580-3905-11e9-8a9b-e07dc2cd2a8a.png)

 - Native App for macOS 10.14.1
 - Postman Version 6.7.3

**Comment by codenirvana** [comment]
@roma-guru This is happening because the redirect is made with an addition of [Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) header which holds the URL of the original request and since the query param has Unicode characters it fails because headers can't have Unicode characters.

We are adding support to disable this behavior using an option, for updates follow this thread:  #5683

**Comment by roma-guru** [comment]
Thanks for explaining, it sounds sane.
Can't Referer Url be urlencoded to prevent this from happening?
It seems like other clients are coping with this situation..

**Comment by codenirvana** [comment]
@roma-guru You are right, encoding the URL will fix this issue.
But, Postman is a debugging tool and we avoid doing all those auto fixes which other clients are doing. We provide options to disable those behaviors if it's blocking your use case.

We definitely lack the reason why this request failed since not everyone is aware of this fact.
Thanks for reporting this we are working on improving the error message with more appropriate reasons.

**Comment by roma-guru** [comment]
Ok, got it.
