### ISSUE TITLE
Postman does not recognize array from data file

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6009]
**Describe the bug**
I need to pass an array to loop over it at one iteration

**To Reproduce**
1. Create a json data file: [{"array[0]":"12","array[1]":"34","array[2]":"56"}]
2. I pass it to collection runner to perform console.log(pm.iterationData.get(“array[1]”));
3. get an arror "SyntaxError: Invalid or unexpected token"

**Expected behavior**
It would be great to be able to pass an array in a data file

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 6.7.4
 - OS: Windows 7 32 bit

**Additional context**

**Comment by vikiCoder** [comment]
Hi @m3dbedb,

I tried to reproduce the issue in the current version of the Postman App (v7.2.0) but it seems to be working fine. You also can pass an array in JSON data file like shown in below example:

**DataFile.json**
```json
[
    {
        "array": ["string1", "string2", "string3"]
    }
]
```

And you can access elements of this array as shown in below code snippet
```javascript
var arr = pm.iterationData.get(“array”);

console.log(arr[0]); // => "string1"
console.log(arr[1]); // => "string2"
console.log(arr[2]); // => "string3"
```

However, judging by the error you are getting, I think the issue in your case is not related to JSON data. In your code `console.log(pm.iterationData.get(“array[1]”));`, you are using different characters for double quotes instead of standard ASCII characters (you are using `“` instead of `"` - notice that both are different characters). This seems to be causing the syntax error you are getting. Just use the regular double quotes and your code should work fine with the JSON data you provided.

I hope this comment solves your problem.
