### ISSUE TITLE
No response, when sending request using system or global proxy address

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6028]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
User receives **Could not get any response** error when try to send a request via a corporate proxy. Using either system, or global proxy settings yields the same result.

**Comment by harryi3t** [comment]
@JP-from-Postman Some more information that would help triage this issue:
1. Does the network requires a proxy?
2. If yes, is the proxy authenticated? What authentication does it use? Basic, NTLM or any other?
3. Share the output from the Postman Console. (open the console first then send the request, expand all views before taking screenshot)

**Comment by Zer0x00** [comment]
Similiar problem here. Happens using latest Postman 6 and also using 7 (Canary)
Tried also using a batch file with "set HTTP_PROXY=..."
1. Yes
2. Basic
3. Can't post any console because it does not load

![2019_03_07_15_49_24_postman](https://user-images.githubusercontent.com/32687653/53965502-a5889b00-40f1-11e9-98fd-cf7c4f72eadc.png)

**Comment by harryi3t** [comment]
@buenyamin-olgun This seems to be different issue where App is not even opening/loading and showing a black screen, if that right?
If yes, then it might because of non-compatible GPU. You can try disabling the GPU as mentioned here https://github.com/postmanlabs/postman-app-support/issues/4594

**Comment by numaanashraf** [comment]
Closing due to insufficient information
