### ISSUE TITLE
Method not showing up for older history in browse mode

### ISSUE THREAD

**Issue by sankalp0o** [a85/POSTMan-Chrome-Extension#6063]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Older history listings in the app are buggy for some items and behave differently in build and browse mode. In Build mode, it doesn't show my profile picture on hover (it does for other history items). In browse mode, it doesn't show the request method.

**Screenshots**
Build mode: 
<img width="420" alt="Screenshot 2019-03-13 12 29 30" src="https://user-images.githubusercontent.com/7601762/54259567-3fd25e00-458c-11e9-9d6d-437f7668f4bd.png">

Browse mode:
<img width="309" alt="Screenshot 2019-03-13 12 29 41" src="https://user-images.githubusercontent.com/7601762/54259571-41038b00-458c-11e9-8e78-1e99768d6f22.png">

**App information (please complete the following information):**
- Native app v 7.0.5

**Comment by numaanashraf** [comment]
@sankalp0o This is intended. Since the profile pic feature was introduced in the app on a later date, any history that was created or synced in the app before that date would not show the profile pic. Browse mode is an online flow and is API driven, and will show this profile pic for older histories also.

The methods not showing up on browse mode looks like a bug. Fixing that issue.

**Comment by numaanashraf** [comment]
Fixed in Postman v7.1.0
