### ISSUE TITLE
Whitespace at the end of the url (last parameter) is trimmed

### ISSUE THREAD

**Issue by ran-darillium** [a85/POSTMan-Chrome-Extension#6097]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
If I submit a parameter in params, and the parameter has a space in the end, it reaches my java spring server without it.

**To Reproduce**
1. create a parameter with a space in the end.
2. send the parameter to a server

**Expected behavior**
The parameter should have a space in the end

**App information (please complete the following information):**
 - Java
 - Postman Version 6.7.4
 - OS: macOS

**Comment by shamasis** [comment]
I think we trim the text on UI because we’ve had more cases where people didn’t notice trailing spaces and things failed. I will double check on that though. 

Maybe we could convert this to a warning ⚠️ icon instead of doing the trimming. But not sure until we assess what would be the impact. There might be hundreds and thousands of collections that are now working as a dependency on this behaviour. Changing this could break things across the board for them.

**Comment by ran-darillium** [comment]
What about having a small checkbox (disabled by default) asking you if the space in the end was intentional? 
Or, how about making the space not trimmed only on new versions of collections in postman (so collections made before would not be affected)?

**Comment by shamasis** [comment]
Yeah. I thought about those two as well. 

1. Yes, there’s already a setting for that. I assumed you’ve tried it already. It however makes the change from UI level and actually trims the value before saving or not. I’m not a 100% sure, but it may be in effect only when you edit that value. Or at least that’s how it should be since otherwise, based on your settings, a collection working fine in your system will not work on another person’s app. (Like what happens when you turn off SSL verification or follow-redirect and build a collection but it ends up failing when shared with someone who doesn’t have the same settings set.)

2. New versions of Postman can have collections that eventually get shared either team members having an older version of app. Hence, having endured the pain of creating issues like this earlier, we nowadays actively avoid designing features in that way. 

If point 1 above is not working for you already, that should be a bug. In fact, I do see a bug there. @numaanashraf

**Comment by shamasis** [comment]
@vkaegis @numaanashraf - we should also consider the following:

Show whitespace at the beginning and end of strings in data editor component like IDEs show for codes

**Comment by shamasis** [comment]
Just tested on latest canary with changes as described in https://github.com/postmanlabs/postman-app-support/issues/8154 ... it is fixed now!

![Screenshot 2020-03-08 at 02 08 11](https://user-images.githubusercontent.com/232373/76152127-ea1e8c00-60e1-11ea-8487-da266ab805ad.png)

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.

Feel free to leave your feedback at #8154 or reopen this thread if the issue persists.
