### ISSUE TITLE
Need Administrators to have special privileges for Postman Elements to administer teams

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6102]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
In v7, Team Admins do not have inherent admin rights to manage Collections, Workspaces, and possibly other content.

After migrating our test team to v7, my Team Admin account has the admin/editor role for some Workspaces/Collections, but not for others, and I'm unable to regain rights to manage either (by myself). Some Workspaces also have no admin.

Post migration, if a Team Admin:

a. doesn't already have the admin role for a Workspace, or Editor rights for a Collection
b. doesn't inherit admin or editor rights from the team default setting
c. isn't able to have another team member grant them admin or editor rights

...they will be unable to assign or reclaim admin rights for themselves. This means they may be blocked from administering team content.

**To Reproduce**
1. For an account with the Team Admin role
2. Add at least 1 other team member as:
  - Editor on a Collection
  - Admin on a Workspace
3. Change your own role to either:
  - Viewer for the Collection
  - Collaborator for the Workspace
4. Save
5. Notice you are now unable to administer the Collection, or Workspace
- Clicking `Manage Roles` for a Collection results in an error about not having permissions
- Editing a Workspace has options for changing team member roles greyed out.

**Expected behavior**
Team Admins are able to administer all team content, and cannot lose that ability depending on an entity specific role.

**Screenshots**
<img width="683" alt="Screen Shot 2019-03-19 at 12 00 36 PM" src="https://user-images.githubusercontent.com/43283131/54641620-d781f180-4a4f-11e9-9b35-505ec0467b99.png">
<img width="1028" alt="Screen Shot 2019-03-19 at 2 03 45 PM" src="https://user-images.githubusercontent.com/43283131/54641625-d9e44b80-4a4f-11e9-8eec-395b5920b234.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.0.6
 - OS: macOS High Sierra 10.13.6

**Additional context**

**Comment by sankalp0o** [comment]
@JP-from-Postman All the things that you described above are expected behaviour. The Team Admin role has no special privileges over team collections and workspaces. In fact, team admins do not have any access to team collections and workspaces. They'd need a "Developer" role and then like any other user, they'd need to be given explicit roles on the collection/workspace.

The idea here is that Team Admins do not "...administer all team content", they manage the team itself by adding/removing users, managing team-level roles and some team settings.

This being said, some of the things you mentioned aren't expected.
1. "Some Workspaces also have no admin."
2. "doesn't inherit admin or editor rights from the team default setting"

Can you give some more context here? If these are true, we'd definitely need to look into it.

**Comment by DonSkokie** [comment]
@sankalp0o I brought this issue up as we have run into issues where one developer created a collection and then another developer doesn't have access to edit it. As an Admin I would assume I should have rights to go into that collection and modify the permissions so whoever I chose has rights to the collection. 
I have Admin, Billing and Developer rights. As the person who setup and manages the team environments I should have the rights to unlock any of the collections. 

Thank you,]
Mick

**Comment by JP-from-Postman** [comment]
@sankalp0o Thanks for clarifying. Per your questions:

1. "Some Workspaces also have no admin."
An example of a post-migration Workspace without any admins was posted by @chrisdeso in https://github.com/postmanlabs/postman-app-support/issues/6101.

2. "doesn't inherit admin or editor rights from the team default setting"
Sorry if the way I wrote this is confusing. To clarify, the actual behavior of the team default role works fine (see screenshot at the bottom of this comment). I.E. if I set the `Everyone in team` role for a workspace to admin, then everyone on the team inherits that role (as expected).

To explain more clearly:

> Post migration, if a Team Admin:
> 
> a. doesn't already have the admin role for a Workspace, or Editor rights for a Collection
> b. doesn't inherit admin or editor rights from the team default setting
> c. isn't able to have another team member grant them admin or editor rights
> 
> ...they will be unable to assign or reclaim admin rights for themselves. This means they may be blocked from administering team content.

This is meant to highlight the need for a super-admin type role. A team may need to manage roles in specific workspaces or collections, without having to rely on a specific workspace admin or collection editor to do so. Right now, I don't believe there is an easy way to do this, without (for example) adding a single account to each workspace or collection with needed rights.


_Example of team default role (working)_
<img width="684" alt="Screen Shot 2019-03-20 at 10 20 03 AM" src="https://user-images.githubusercontent.com/43283131/54706740-dbb81880-4afc-11e9-979a-c04bdbd0b12e.png">

**Comment by preethammavin** [comment]
@DonSkokie I agree with your use case, one of the reasons we introduced Role Base Access Control was to give fine grain controls to the users to better manage the team.
The current behaviour of the product does not let Admin have special privileges on collections and workspaces as @sankalp0o mentioned

I am changing the Issue title to reflect the need for such a feature so that we may reference it when we include into our future roadmap.

**Comment by Millais** [comment]
Hey Postman Team,

This feature is critical for any large Enterprise rollout.

We're currently working with the Postman team to introduce the Enterpise license at PayPal. To expand the license across the company, we require more fine-grained controls than what the current permissions offer. 

Really as a minimum we need:
1) Superuser access (this ticket)
2) Ability to lock down who can create workspaces in the team. This inherently solves 1).

For our vision – of 1000+ people using the license – we will run into detrimental collaboration issues if we cannot control the workspace structure, particular as there's no ability to organise the list of workspaces into distinct teams yet (see _multi-team collaboration_ on the [Trello roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers)).

Thanks,
Patrick

**Comment by preethammavin** [comment]
@Millais thanks for giving a very insightful feedback, we are actively looking at enabling governance capabilities in Postman and adding a way to administer the data and configuration of your team at the top of the list. This is currently on our mid - long term roadmap , will keep everyone here and our trello roadmap posted on the progress .

**Comment by happycappie** [comment]
Hi Postman Team,

We also would like to have 'Super Admin' role be available.  In our case, the developer in charge of a particular Collection is out on a long holiday.  We are now unable to merge a fork into that Collection.  This is impacting our business.

What if the developer who has access were to suddenly resign or get hit by a bus?

Please consider making Super Admin access available as soon as possible.

Thank you

**Comment by happycappie** [comment]
@preethammavin is there an update on this?  would it be possible to advise what mid-long term roadmap represents timewise?  3-4 months?  6-9 months?

**Comment by sankalp0o** [comment]
Hey @conradpronto, time wise 6-9 months is when we're looking at it. Will keep you updated on this thread when there's more progress!

**Comment by harsh-reality** [comment]
@sankalp0o - Currently, admins do not have access to control naming of workspaces. In large teams, such an access to admins or super-admin is crucial to manage and govern the workspaces.  
Something to keep in mind as we work towards building such a feature!

**Comment by cyrielle-hada** [comment]
@sankalp0o a super admin role would also allow assigning a `billing` role to another user in the event that the team is left with only one billing team member - who is unable to perform the action (for example, if the billing user left the organization). 

This specific case-scenario was reported here: https://github.com/postmanlabs/postman-app-support/issues/6742

**Comment by dantench** [comment]
yes this... very very much need this! 

How has this been around since March 2019? for postman to become a tool that can be properly utilized by companies around the globe they need urgently to add in permissions and management of users, just like any other tool their users are likely using or their competitors offer.

**Comment by paulcruse-syn** [comment]
I too would like to see this implemented. 

It's kind of weird that this is not already implemented given how teams operate in real life.

How can I be an admin of a team and not be able to delete something from within that team? If a team member leaves my team I am unable to administer their workspace? Seems a bit odd...

**Comment by labifrancis** [comment]
Another user wants to have these rights as an admin.

Use case:
1. They have a master collection
2. Developer A has no write-access to this master collection
3. Developer A creates a fork and uses that one to add some new calls
4. Once finished, developer A creates a pull request
5. Developer B (who has full access to the master collection) accepts the pull request and merges the changes from the forked collection to the master collection
6. Now, developer B would like to delete the fork collection from developer A(without needing permission) as the changes have been successfully merged
This way, they want to avoid misunderstandings and keep their team workspace clean

Workaround: Developer A can give Developer B an "Editor" role on the collection so that Developer B can have the permission to delete.

**Comment by jonarmstrong** [comment]
My organization also needs this feature. The organization can't have governance of it's data without the ability to actually administrate and control that data from the top. We need a `super-user` role which will allow a user to add/remove members from any workspace. We need to be able to restrict the ability for new workspaces to be created.

**Comment by tbrownSpecialized** [comment]
We also need this role.  We were unable to modify a monitor so that we can run it manually.  During an outage, we had to create a brand new monitor off the collection to be able to manually re-run it and hope that we had the right environment etc...  This should be a standard feature of any tool that is going to allow teams and organizations to use it.  Someone has to have true admin privledges.  Also, the timeline was stated 6-9 months, approximately 15 months ago.

**Comment by acandylevey** [comment]
Having to go to postman support to gain access to a collection because a developer has now left the company is ridiculous.  I can't imagine the amount of time that must be wasted by having such a system

**Comment by orubel** [comment]
How are these 'ROLES' represented for each endpoint? For example, in the OpenAPI, how do you have separate endpoint request/response data for each ROLE?

**Comment by orubel** [comment]
You know what would fix this? ROLES in OpenAPI. Too bad the OpenAPI lead has stated he won't do it! https://flic.kr/p/2keNR8v

**Comment by danrich0** [comment]
> Having to go to postman support to gain access to a collection because a developer has now left the company is ridiculous. I can't imagine the amount of time that must be wasted by having such a system

Yep, agree this is madness. I manage paid licensing for my team at my company and not being able to change and assign workspace, collection and environment permissions and the default not being set to allow my whole team Editor is a headache.

**Comment by orubel** [comment]
@danrich0 yes but they do not understand that 'roles' are directly associated with endpoints; that an endpoint can have multiple roles associated with it to create the resource in different ways. And as a result, OpenApi directly violates OWASP API3:2019 and API6:2019

This creates HUGE security holes as a result of just USING OpenAPI.

My sugestion was something like this: 
```

			    "show": {
			     	"METHOD":"GET",
			    	"DESCRIPTION":"Get Person by ID",
				"BATCH":["ROLE_ADMIN"],
				"HOOK":["ROLE_ADMIN"]
			        "REQUEST": {
			            "permitAll":[],
				    "ROLE_ADMIN":["id"]
			        },
			        "RESPONSE": {
			        	"permitAll":["id","version","username","email","enabled","accountExpired"]
			        }
```

**Comment by kris-runzer** [comment]
I'd like to further advocate for this issue.  Currently we've onboarded 55 users into Postman.  We have plans to add hundreds more.  At this time, I would be hard pressed to say we continue onboarding with Postman due to this lack of control.

Not being able to "super admin" introduces a high degree of risk for our industry.  People will make mistakes.  We really need the abilities to swiftly delete and easily manage (aka cleanup).  The entire model of having to request access to Environments, Collections, etc. isn't really suitable for Enterprise.

On top of this, "super admin" will allow us to cleanup our workspace(s) where people have mistakenly made dozens of copies, etc.  Seeing as we can't really prevent people from creating these things in the first place via RBAC -- or similar -- we require the ability to administrate at a super level.

**Comment by orubel** [comment]
@kris-runzer Postman relies HEAVILY on #openapi and while I have advocated better security, the #openapi lead dev has stated they will not offer nor fix this issue : https://flic.kr/p/2keNR8v

Openapi will not allow for multiple roles per endpoint and thus only has one request/response dataset. As a result, if you have multiple roles, this data will be wrong 50% of the time or greater.

**Comment by tapsboy** [comment]
I have used ton of SaaS software and don't recall similar ownership mechanism elsewhere, where an individual's ownership of a shared resource trumps admin. This is extremely annoying & disruptive, when the owner of a collection is on a vacation or has left the company without transferring the ownership. Right on this platform, anyone in a github org with permissions can create repos, but an admin can always override any settings or change access on the repo

**Comment by ArjunSingh-PM** [comment]
We have made changes to the roles and permissions in Postman. To learn more, you can refer to the learning center documentation for [Roles in Postman](https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/#roles-in-postman) or [this blog](https://blog.postman.com/introducing-the-super-admin-role/)

**Comment by christhomas** [comment]
You didn't go far enough, super-admin needs to be something everybody with a paid account, not just limited for those super duper special customers paying you thousands of dollars a month. So with my smaller company, I'm still out of options cause we can't afford to pay that much money for a developer only product. 

We pay you thousands of euros a year and can't even administrate our own teams correctly cause you guys are too busy screwing people over for basic features.
