### ISSUE TITLE
Monitor usage discrepancy between usage overview monitoring usage details

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6132]
**Describe the bug**
In Usage Overview monitoring, calls made by monitor shows 1000+ while View detailed monitoring usage shows only 26 requests. 

**Expected behavior**
See the same usage in Usage Overview monitoring and View detailed monitoring usage. 

**Screenshots**

![2019-03-21_17-38-17](https://user-images.githubusercontent.com/47351631/54818600-924d0200-4c91-11e9-8b55-55ec929503cc.jpg)
![2019-03-21_17-38-01](https://user-images.githubusercontent.com/47351631/54818601-924d0200-4c91-11e9-8aac-ee52d1a09e1a.jpg)

**App information (please complete the following information):**
 - App Type: Native App 
 - Postman Version 6.7.4
 
**Additional context**

- 2 monitors have been created 
- One monitor was recently deleted

**Comment by godfrzero** [comment]
We've tracked this down to a bug which was up in production between March 12th 2019 - March 23rd 2019. Teams who had their monitoring billing cycles reset during this period would've seen incorrect usage on the overview page. We've updated the usage for these teams, and the usage displayed on the overview and details page should be closer to each other now. The values may not be *exactly* the same because deleted monitors are not included in the details view.

I'll leave this ticket open for a few more days in case more reports come in, and then close this.

**Comment by briangarofalo** [comment]
Thanks for the update. Our current usage period is March 1 2019 - April 1 2019, so I believe that means it was not reset between March 12th 2019 - March 23rd 2019. As of right now (9:00 PM Eastern time on March 27), our overview page is still significantly different than the details page (952 on overview vs. 673 on details). 
We have two monitors, one that runs daily and one that runs hourly.

**Comment by godfrzero** [comment]
@briangarofalo The update happens in batches, can you check if you're still seeing the discrepancy?

**Comment by briangarofalo** [comment]
Sorry for my delayed response. Our monitoring usage was reset, but so far for the current usage period the value appears to be accurate and is exactly the same between the overview and detail pages. Thank you.
