### ISSUE TITLE
Web Dashboard – Error when accessing collection

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6151]
**Describe the bug**
When attempting to access a collection via the web dashboard, an error stating `You don't have access` is thrown.

**To Reproduce**
1. Go to [https://go.postman.co/me/collections](https://go.postman.co/me/collections)
2. Attempt to access collection(s) listed
3. See Error

**Expected behavior**
The collection documentation is expected to populate.

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/54960233-ce01f900-4f29-11e9-84a4-2830f5ed30be.png)

**App information (please complete the following information):**
 - App Type Native
 - Postman Version 7.0.6
 - Browsers: Chrome | Safari | Edge

**Additional context**
User is not affiliated with a team. Collections are still accessible in-app.

[Filed by Postman]

**Comment by treolandix** [comment]
When I try it through above link [](https://go.postman.co/me/collections) it says no collections at all:

![tempsnip](https://user-images.githubusercontent.com/12352470/54981712-4a87ec80-4fa9-11e9-8642-a416e36aee8f.png)

When I press _Back to workspace_ at the top left my collection show's up properly. But I got still no access.

**Comment by preethammavin** [comment]
@treolandix Thanks for the information, will get back with a resolution for this soon.

**Comment by treolandix** [comment]
@preethammavin No problem! It is not urgent, as @chrisdeso described everything works fine in the app.

**Comment by timatiotas** [comment]
I am having this issue, but i'm also missing some of my collections in the desktop app that I can see on the web.  so this is a larger issue for me since my main and most used collection is gone and I cannot get access to it.

when i try to access the ones I don't see in the desktop app, I get the permission denied error on web.

EDIT: clarification

I can see the missing collections on my profile page but clicking them results in access denied error (same if I try to share):  https://web.postman.co/me/collections

but if I view my workspace page, a bunch of the collections on my profile page are missing:
https://web.postman.co/workspaces/{id}/collections

**Comment by preethammavin** [comment]
We have pushed multiple fixes around this issue , closing the thread for now. Do reopen the thread if the issue persists.
