### ISSUE TITLE
API requests showing under a collection are showing incorrect after editing and saving.

### ISSUE THREAD

**Issue by kksanil123** [a85/POSTMan-Chrome-Extension#6158]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
API requests showing under a collection are showing incorrect after editing and saving.

**To Reproduce**
1. Create a new collection and lets name it A for further reference.
2. Create a new request and lets name it request 1
3. Duplicate the newly created request, do some changes and save it. Let this be request 2.
4.Go to left menu, click on the collection A, 2 requests will pop-down.
5. **Issue :** Hover the mouse on second request and observe. it is same as the first request.

Note : If we open that request it is showing correctly, as we edited and saved it.

**Expected behavior**
It should show the edited request as we saved it.

**Screenshots**
![image](https://user-images.githubusercontent.com/28511117/55003573-a892ef00-4ffe-11e9-93b2-0ce1ef2240b8.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by preethammavin** [comment]
@kksanil143 When you hover we display the request name, which does not dynamically change based on the request itself. 

If the behaviour that you expect is that the request name changes based on the request, then that would not be the right assumption. Request name has to be changed by the user in the tab, and this is done to ensure we give the user the freedom to name the request in a human-readable format/any convention of his/her need.
for reference of editing the request:<img width="769" alt="Screenshot 2019-03-27 at 9 24 52 AM" src="https://user-images.githubusercontent.com/34742239/55049443-39ef7900-5072-11e9-824e-20420bcb2652.png">


When you duplicate a request we add the name of the original request+ copy for the user to find the request. 

I am closing this issue, as this is the expected behaviour of the product. Do feel free to reopen the issue, if your issue is different from what I have mentioned.

**Comment by kksanil123** [comment]
Hi @preethammavin 
Thanks for the response. Yes, i can see original request + copy when i duplicate a request in a collection. But lets say, i have a request R1 and i duplicated it 10 times. **i have modified all the requests (duplicated) by editing and saved them.** 
Now i want to run a particular request out of 10 duplicated requests. **For this i need to open each and every request, look for the specific request needed and run it.** 
Does this behavior Expected ? If this is really expected behavior, i don't think this is a good user experience.
Hope i conveyed it properly. 
Thanks.

**Comment by preethammavin** [comment]
@kksanil143 when you are editing the request, you can edit the request name for making it recognisable. For example, I have named my request as a test, whereas the URL is a variable URL. So when you have 10 different requests which are duplicated, then when you are editing the request then rename the request based on your need.

I would rename the request when I am editing to organise it better. At Postman, with the request being the entry point and users can build multiple use cases on the request with the test script, to assume a request name is a request itself would break a lot of users workflow.
