### ISSUE TITLE
Syncing issues - content not sycing to the app 

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6212]
**Describe the bug**
Team members making new collections or changes to collections that don't appear unless you log out and in again in the Postman app. 

**Additional context**

- All team members have migrated to version 7
- Removing the collection from the shared workspace and re-shared it worked but then the issue reoccurs. 

Note for engineering: logs have been shared.

**Comment by MichaelMFeldman** [comment]
I don't know if this is the same issue or not, because logging in/out has no effect, but after migrating I can't sync anymore. I can't access my team's workspace or anything... eek.

The email on my account is <redacted>
When I try to press an "Enable sync" button inside postman with the console open, I see a network request to `POST https://app.getpostman.com/api/sync-eula-accept?<redacted>` with an empty response that results in `SyntaxError: Unexpected end of JSON input`.

Happy to make a new issue.

**Comment by numaanashraf** [comment]
@MichaelMFeldman Could you write to us at help@getpostman.com? It'll help us verify the status of your account and your team and understand why sync has been disabled for you.

**Comment by MichaelMFeldman** [comment]
Hi @numaanashraf I did earlier today, subject "Syncing issue logs - github issue 6212". Apologies for including sensitive info in my previous comment and potentially clogging up this github issue.

**Comment by numaanashraf** [comment]
Thanks @MichaelMFeldman. We are looking into this issue at our end and we'll get back to you via email.

**Comment by numaanashraf** [comment]
Issue seems to be caused due to sync being disabled due to payment issues.
