### ISSUE TITLE
Guest accounts  

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6232]
**Is your feature request related to a problem? Please describe.**
Collaboration only works with members on the same team at the moment, there is no user role with a "view only" permission. 

**Describe the solution you'd like**
Invite users with restricted access to your Pro or Enterprise account to **view only** a workspace. 

The workspace would be client-facing workspace and controlled/presented to clients who can simply use what is within the workspace without being able to change it or its core elements.

**Comment by rhanton** [comment]
I have a similar use-case/need for granting read/execute only action to some users on our team who use postman simply as a http API client from time to time to check/test endpoints to provide client support. It is hard to justify the cost of paying for Postman Pro/Enterprise for these users when they only use it a few times a month, but they do need access to our organization's private collections.

**Use case:**
Allow users to use free or low-cost Postman accounts for viewing/executing private team collections without access to advanced features like documentation, team collection editing, mock servers, monitoring, etc. because they do not have a need to use those features.

**Solution I'd like:**
Either provide tiered pricing per-user for Pro/Enterprise plans where the #-of-users cap for Pro only applies to full-feature users (our team is probably 40-50 users needing full-feature access and 20-30 users needing read-only access) OR allow users with "Free" accounts to be granted read-only access to private organization collections (so they won't count toward pricing/tiers at all).

**Comment by francoisneron** [comment]
What's the status of this request? We also need this feature.
https://trello.com/c/GGBVNOcp/25-guest-accounts

A lot of people are asking for this.

**Comment by rafetdk** [comment]
What's the status of this feature?

According to this [Postman Help Center article](https://support.postman.com/hc/en-us/articles/115003330925-Can-I-join-multiple-teams-with-the-same-Postman-account-), this feature is on Postman's Roadmap, but I can't find it anywhere on the roadmap.

**Comment by ArjunSingh-PM** [comment]
We have enabled Collection Editors to allow external users who aren't in their Postman team to view a specific collection and send requests in that collection on the [Free, Basic, and Professional plans](https://www.postman.com/pricing/)

References: 
- Blog: [Introducing Postman's new guest role](https://blog.postman.com/introducing-postmans-new-guest-role-to-share-collections-instantly/)
- Postman's Learning Center document: [Allowing external users to view collections](https://learning.postman.com/docs/collaborating-in-postman/sharing/#allowing-external-users-to-view-collections)
