### ISSUE TITLE
Allow default Workspaces to be deleted or reassigned

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6236]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to delete default workspaces (personal/team) or to designate a different workspace as default

**Describe the solution you'd like**
A flow similar to the workspace deletion flow – an option in the UI that would allow the change/update.

**Additional context**
[Filed by Postman]

**Comment by TsLenMo** [comment]
Very good, I am looking forward to。

**Comment by mistryvipul2002** [comment]
When can we expect this? I am trying to delete the default Team workspace I only created, and I am not able to delete it.

**Comment by Filipe-Souza** [comment]
Hey Postman Team, still looking forward for this. This management option is GREAT.

**Comment by ghost** [comment]
There are people who really resent having things to spare, so please, I would like to delete "Team Workspace"

**Comment by sankalp0o** [comment]
Hey @TsLenMo @mistryvipul2002 @Filipe-Souza @dimacros !
Thanks for the feedback. I'd like to understand your use case better for deleting the default "Team Workspace". 

Do you want to do this because - 
1. You want to delete/leave the team itself.
2. You do not want ANY workspace which is shared
3. You have other team workspaces which your team uses and this "Team Workspace" is empty and not being used.

Or is there any other reason?

**Comment by ghost** [comment]
@sankalp0o It is for the number 3. At the moment you want to work in a team, you most likely already have a defined name for that team. So "Team Workspace" would only be empty and it bothers not being able to remove it.

**Comment by sankalp0o** [comment]
@dimacros I understand your use case better now, thanks! When workspaces were initially launched, there were some dependencies on "Team Workspace" for the transition. We will reevaluate whether this is still true or not, and possibly remove restrictions around deleting "Team Workspace".

Till then, feel free to rename it and use it like any other workspace.

Would love to hear if anyone has a different reason for deleting "Team Workspace".

**Comment by TsLenMo** [comment]
> @dimacros I understand your use case better now, thanks! When workspaces were initially launched, there were some dependencies on "Team Workspace" for the transition. We will reevaluate whether this is still true or not, and possibly remove restrictions around deleting "Team Workspace".
> 
> Till then, feel free to rename it and use it like any other workspace.
> 
> Would love to hear if anyone has a different reason for deleting "Team Workspace".

I agree with the statement of @dimacros

**Comment by brijesha** [comment]
@sankalp0o I created the team workspace sometime back. Later I realized that I have reached the shared requests limits for Team workspace and some of the collections were archived because of that. So team workspaces are no use to me and none of my team members are using it. I want to get rid of it but since delete feature is not there I am not able to.

Also when I switch back to Personal Workspace, I still keep seeing this message.

> Some collections were archived because you've reached the shared requests limits. Learn more.

See this image 
![image](https://user-images.githubusercontent.com/31380506/65069600-dfa7e480-d93f-11e9-8795-069160ee63aa.png)

Showing this message makes sense when I am in Shared Workspace. But when I have switched to Personal workspace, the annoying message should go away.

Even better I want to delete the team workspace and get rid of it completely.

**Comment by mistryvipul2002** [comment]
@sankalp0o I created the team workspace sometime back. Later I realized that I have reached the shared requests limits for Team workspace and some of the collections were archived because of that. So team workspaces are no use to me and none of my team members are using it. I want to get rid of it but since delete feature is not there I am not able to.

Also when I switch back to Personal Workspace, I still keep seeing this message.

> Some collections were archived because you've reached the shared requests limits. Learn more.

See this image 
![image](https://user-images.githubusercontent.com/2621870/65069926-8d1af800-d940-11e9-9776-0a3188c5be71.png)

Showing this message makes sense when I am in Shared Workspace. But when I have switched to Personal workspace, the annoying message should go away.

Even better I want to delete the team workspace and get rid of it completely.

**Comment by sankalp0o** [comment]
@mistryvipul2002 Thanks for sharing your requirements. Deleting the Team Workspace (even if it was allowed) would not delete your team.

To delete your team,
1. Go to https://go.postman.co/team. If you haven't already, sign in to your account.
2. Remove all users (except yourself) in your team. Click on the "Trash bin" icon which appears on hovering over a user's name.
3. After you've removed everyone else, remove yourself from the team (in the same way). Doing this will delete the team and all your shared resources will be transferred to your personal account.

**Comment by mistryvipul2002** [comment]
@sankalp0o Thanks for the instructions. It worked like a charm.

**Comment by John-Dormevil** [comment]
Hi, I'm waiting this feature to

**Comment by yukselaggoz** [comment]
Hi, I'm waiting this feature to. it's ridiculous not to be allowed.

**Comment by eduardrudko** [comment]
Hey guys, take it to your sprint, please! Cheers :)

**Comment by bproven** [comment]
Can't believe we have to ask for this

**Comment by RajatPawar** [comment]
My two cents on this! 

I created a team workspace, and have no need for a personal workspace anymore. I'd like to streamline my focus when I open the Postman app ideally & directly to the collaborative workspace that I am a part of, rather than make sure that I'm not working through the wrong workspace. 

I understand the need to have at least one default workspace. I feel that it would be better to rewire the condition as the user having **at least** one workspace without caring if it's a personal or a team workspace in order to use Postman. That makes more sense (ensuring at least one space for the user to log on to when they open the app) than having a rather arbitrary condition on which workspaces we can or cannot manage. 

Hope you guys pick this up soon!

**Comment by ThomaSchneid** [comment]
This issue is open now for over a year, hope you guys start working on it soon 👍

**Comment by vashchilo** [comment]
How it will be fixed soon

**Comment by VijitCoder** [comment]
This repo has over 1700 opened issues now. Trust me, this one is not the biggest problem of this software :)

**Comment by yobyot** [comment]
I would find the ability to control _all_ workspaces to be useful as well. I've sometimes renamed the default workpaces, used them, forgotten they are not deleteable and wasted time relearning that fact.

**Comment by davidmcl** [comment]
I also cannot delete the Team Workspace...created it out of curiosity and am now stuck with it.

I created it, there are no other members, there are no entries (collections, etc.) and yet I cannot "leave" it or "delete" it.

Simple rule applies, if I can create something, I should be able to delete it.

dbm

**Comment by bdbais** [comment]
**Looks like your team is full. To expand, organize, manage your team effortlessly, upgrade your plan.**

This message is present everytime I open Postman but we just tried team collection and we really don't need it. How to remove it? We really must to "hack it" to remove it ?

**Comment by davinderxav** [comment]
Bulk delete collection from default workspace will also do. If we do not get option to delete default workspace

**Comment by liflovs** [comment]
let us delete team workspace

**Comment by akshay-kulkarni-03** [comment]
Hi All, 

You should now be able to delete the default (team & personal workspace) even though it being the last workspace in both web-app & postman app. For the native app please ensure you use the latest version of the app.

Closing this issue, feel free to open this issue again if issue persists.
