### ISSUE TITLE
Lost Collections 

### ISSUE THREAD

**Issue by 14552516** [a85/POSTMan-Chrome-Extension#6281]
Describe the bug
When I sign in to my account, my previously saved collection disappears, how can I get it back?
These collections are saved locally when I am not logged in.

App information (please complete the following information):
 - App Type  Native App
 - Postman Version  7.0.7

**Comment by abhijitkane** [comment]
@14552516 Is this happening each time you sign in - 
1. Sign out
2. Create a collection
3. Sign in
4. Collection disappears?

If so, can you check View->Developer->View logs in Finder/Explorer, and attach the logs here, or email them to help@getpostman.com?

**Comment by ghost** [comment]
Just had the problem but it's maybe a different issue. I was using Postman without account for a long time, I have added a account because a coworker wanted to try shared workspace. Lost all my collections. Still see some of the request in the history pane...

**Comment by kamalaknn** [comment]
We have deployed the fixes that would have led to this experience. The fixes should be available from the Postman apps starting from 7.0.9. 

@14552516 @eric-gagnon  Unfortunately we cannot fix the state of the data from the previous versions. If you have not signed out you can try exporting all the collections from `Settings -> Data -> Export` and importing it again.

I'm closing this now since this doesn't affect new users. Please let us know if you are facing similar issues on Postman 7.0.9 and above.
