### ISSUE TITLE
Feature request for controlling URL encoding

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#6319]
**Describe the bug**
While making an API request if the query parameter contains a **plus (+)** symbol, it's being replaced with a **space** in the query string. This results in API failure when you pass an authentication token in the query parameter.

**To Reproduce**
1. Make an API call to the postman-echo endpoint
2. Pass any query parameter that contains the plus (+) symbol
3. You will see it being replaced by a space in the response. 

**Expected behavior**
The URL should get encoded & + symbol should remain the same 

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/56334964-2d18fd80-61b8-11e9-960d-abd81ac5d8f9.png)

**App information (please complete the following information):**
 - App Type: Native App]
 - Postman Version: 6.7.4 & 7.0.7
 - OS:  macOS High Sierra 10.14

**Comment by CarstenOtte** [comment]
Thanks a lot for considering this request.

This issue is urgent as it prevents REST API access on several of my environments, and also impacts some of my colleagues (all on the latest version of Postman). This issue seems not to impact earlier versions of Postman (6.7.3 and earlier). Unfortunately I was not able to install and leverage an earlier version in my environment.

A workaround proposed by Postman TS (encoding of the token prior to sending the request) did not resolve this issue.

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.

Also, the `+` is converted to space by the server's query processor since it's not supposed to be encoded as per the WHATWG URL standard.

A new request setting is also included to turn off the encoding completely.
<img width="968" alt="disabled-encoding" src="https://user-images.githubusercontent.com/4865836/76072995-ee05bd80-5fbe-11ea-8398-2615c17715e1.png">
