### ISSUE TITLE
Missing data when accepting a new team's invite

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6384]
**Is your feature request related to a problem? Please describe.**
Removed from my team when joining a new team. It would be great to be able to join more than one team at a time, to collaborate with multiple teams

**Describe the solution you'd like**
Something similar to joining multiple workspaces

**Additional context**
Until then : It would be better to have a pop-up message, "Joining the team would remove you from the existing team".

**Comment by bhargavkaranam** [comment]
@Kurmavathar If you're already part of a team, there's a warning shown when you accept the invite to join a new team. Could you tell us the flow where the warning was not shown?

**Comment by ngfk** [comment]
@bhargavkaranam Hi this issue was raised on my behalf. I did not receive a warning telling me that I would be kicked out of my previous team. I simply clicked the "Accept Invite" button from my mail (see below) which openend the installed postman client. The only message I got was the notification telling me that I was removed from my previous team.

In my case this is a real shame because I was the only member of that team and it is now disabled and inaccessible to me, meaning I lost everything stored within the team.

**Additional info:**
- Using the latest version of Postman v7.0.9.
- Button redirects to: https://app.getpostman.com/invite-signup?invite_code=...

<img width="665" alt="Untitled" src="https://user-images.githubusercontent.com/25618095/56905255-28015b80-6aa0-11e9-92ec-02f83f231f7c.png">

**Comment by abhijitkane** [comment]
@ngfk We only remove you from a team if you're the only member. In this state, all shared data should stay with your user account when you move to a different team.

If this wasn't the case, could you reply with details on the support ticket / email thread? Thanks!
