### ISSUE TITLE
Status Page - Segment notifications

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6411]
**Is your feature request related to a problem? Please describe.**
Organizations may rely on Postman's services to ensure that their services/infrastructure is working as expected – monitoring, mock servers, etc. 

Outages are extremely important to know about but planned maintenance may not be a priority. With the existing setup, it's difficult to distinguish when an alert is important or not

**Describe the solution you'd like**
The option to opt out of planned maintenance notifications.

**Describe alternatives you've considered**
Some other type of segmentation when it comes to service status

**Additional context**
[Filed by Postman]

**Comment by shamasis** [comment]
This has been put into effect from April 22nd. From now on, status page posts will happen for the following:

1. Maintenance that is likely to cause outage or degraded performance. This will be posted 5 days in advance, unless it’s an emergency.
2. Incidents occurring due to failures from internal or external causes
