### ISSUE TITLE
OAuth from JavaScript

### ISSUE THREAD

**Issue by stokito** [a85/POSTMan-Chrome-Extension#6415]
I wrote test cases with built in JavaScript but what I wanted is to perform OAuth authentication directly form test case.
It turned out that there is no such API in postman.
Could you expose such API?
Thank you in advance

**Comment by shamasis** [comment]
This does not seem to be something in roadmap. What is in Roadmap is revamping oAuth2 to have a variant that stays local to a collection (hence making the tokens portable.) at that time, such saved tokens could be used while using pm.sendRequest. Closing this since it is unlikely that we will expose oAuth2.0 as a Postman Sandbox API. And whenever we do the revamp, like I mentioned first, this will become available as a side effect workaround.
