### ISSUE TITLE
Exclude specific requests from documentation

### ISSUE THREAD

**Issue by RichardVoice-SynergyLogistics** [a85/POSTMan-Chrome-Extension#6441]
I have been wanting this feature for many years now and even though I have found a lot of discussion on the internet, in general the response I keep finding is not very satisfying.

I would like the ability to build a huge collection with tests and then be able to include or exclude particular requests from the documentation, this would remove the need to clone a collection and then maintain two or more collections to manage documentation and a complete test suite.

As I have said I currently maintain cloned collections with required alterations but as I have seen many people asking for the same feature this seems to be an odd thing not to have on your road-map.

**Comment by sankalp0o** [comment]
@RichardVoice-SynergyLogistics 
I would strongly advice having two different collections in general for public documentation and testing. There are a lot of things that you might not want other people to see publicly (requests, optional headers, scripts, secrets stored as variables) or just because people are more likely to accidentally modify published collections if they are also used for other purposes.

I understand your problem with altering two collections for any change that you'll have to make, hence I suggest that you take the `documentation` collection and create a fork of it for `testing`. You can freely use the `testing` collection without worrying about accidental changes or leaking internal data publicly. Whenever you make a change that you actually want to publish, you can selectively merge those changes from your `testing` collection into the `documentation` collection.

Let me know if you have any questions or feedback about this workflow. For now I'm closing this issue, feel free to reopen this if you feel that this doesn't work. Have a great day!
