### ISSUE TITLE
support prompt value feature while doing api call

### ISSUE THREAD

**Issue by parasuram-tanguturu** [a85/POSTMan-Chrome-Extension#6460]
please check below images.
![post man p1](https://user-images.githubusercontent.com/22343548/57505209-05c7d300-7315-11e9-955d-81aee6b1a7a3.PNG)
![post man p2](https://user-images.githubusercontent.com/22343548/57505210-06606980-7315-11e9-921b-12bc027d3344.PNG)

**Comment by shamasis** [comment]
Yes. This is a useful requirement and we are tracking it for a while at https://github.com/postmanlabs/postman-app-support/issues/285

From user experience perspective we are not inclined to prompt for anything as that breaks the flow. Instead, we would implement it by completing the request and then clearly show what was missing during making request so that those can be added and re-requested. We would also indicate somehow using warnings as to what variables are missing before sending the request. 

Marking this as duplicate.

cc @vkaegis @postmanlabs/runtime
