### ISSUE TITLE
pre request script for  grant_type=client_credentials returns error "grant type not set"

### ISSUE THREAD

**Issue by ravi-9288** [a85/POSTMan-Chrome-Extension#6464]
I have created a pre request script for a collection  for generating bearer token which has to be used for  url end point and below  is the script

let tokenUrl = 'https://*/oauth2/access_token';
let clientId = 'abcd-12xy-abcd1234';
let clientSecret = 'abcd1234abcd12434';
let scope = 'scope1 scope2 scope3'

let getTokenRequest = {
    method: 'POST',
    url: tokenUrl,
    auth: {
        type: "Basic",
        basic: [
            { key: "username", value: clientId },
            { key: "password", value: clientSecret }
        ]
    },
    body: {
        mode: 'formdata',
        formdata: [
            { key: 'grant_type', value: 'client_credentials' },
            { key: 'scope', value: scope }
        ]
    }
};

pm.sendRequest(getTokenRequest, (err, response) => {
    let jsonResponse = response.json(),
        newAccessToken = jsonResponse.access_token;

    console.log({ err, jsonResponse, newAccessToken })

    pm.environment.set('accessToken', newAccessToken);
    pm.variables.set('accessToken', newAccessToken);
     pm.environment.get('accessToken');
    pm.variables.get('accessToken');
});

I am ending up with  error 
error:"invalid_request"
error_description:"Grant type is not set"
Not sure where the issue is, i tried  sending details as json also but the same  result.
below is how i sent data as json but still ended up as same error

const echoPostRequest = {
  url: tokenUrl,
  method: 'POST',
  header: 'Content-Type:application/x-www-form-urlencoded',
  body: {
    mode: 'application/json',
    raw: JSON.stringify(
        {
        	scope:scope,
        	client_id:clientId,
        	client_secret:clientSecret,
        	grant_type:'client_credentials'

        	
        })
  }
};

**Comment by ravi-9288** [comment]
Hi team,
Any update on this?
i am stuck at this point because of the issue

**Comment by saswatds** [comment]
Hi @ravi-9288 

I have modified the request to be sent to our postman-echo test server
```
let tokenUrl = 'https://postman-echo.com/post';
let clientId = 'abcd-12xy-abcd1234';
let clientSecret = 'abcd1234abcd12434';
let scope = 'scope1 scope2 scope3'

let getTokenRequest = {
  method: 'POST',
  url: tokenUrl,
  auth: {
    type: "basic",
    basic: [
      { key: "username", value: clientId },
      { key: "password", value: clientSecret }
    ]
  },
  body: {
    mode: 'formdata',
    formdata: [
      { key: 'grant_type', value: 'client_credentials' },
      { key: 'scope', value: scope }
    ]
  }
};

pm.sendRequest(getTokenRequest, (err, response) => {
  let jsonResponse = response.json();

  console.log({ err, jsonResponse })

});
```
The only change I had to do was use `basic` instead of `Basic`.

The following is the response that I received
![Screenshot 2019-07-08 at 12 40 40 PM](https://user-images.githubusercontent.com/8796447/60789834-ae5fab00-a17d-11e9-84da-c0dd6472b7de.png)

The request payload for sending JSON also seems incorrect. Try using the following payload.
```
{
  method: 'POST',
  url: tokenUrl,
  header: 'Content-Type:application/json',
  body: {
    mode: 'raw',
    raw: JSON.stringify({
      scope:scope,
      client_id:clientId,
      client_secret:clientSecret,
      grant_type:'client_credentials'  
    })
  }
}
```
As this doesn't seem like a bug in sendRequest API, I would suggest that you take up this issue with the vibrant Postman community forum at https://community.getpostman.com/ 

Alternatively, you can use the natively supported Oauth2 helper available in the Authorization section
https://learning.getpostman.com/docs/postman/sending_api_requests/authorization/
![Screenshot 2019-07-08 at 12 51 36 PM](https://user-images.githubusercontent.com/8796447/60790474-34302600-a17f-11e9-872c-d11bfffb951a.png)


I will be closing this issue for now. Feel free to re-open this issue if you encounter a bug
Thanks.
