### ISSUE TITLE
Postman wont create a work space with an & in the name

### ISSUE THREAD

**Issue by joakimwennergren** [a85/POSTMan-Chrome-Extension#6474]
**Describe the bug**
It wont send the request if i input a "&" in the name. 

**To Reproduce**
1. click in workspaces
2. create new
3. input a "&" in the namefield

**Expected behavior**
It should handle "&" in the name.

**App information (please complete the following information):**
 - Postman
 - Postman Version 7.0.9 (7.0.9)

**Additional context**
I guess theres a problem with encoding the string.

**Comment by numaanashraf** [comment]
@joakimwennergren Would it be possible sending us a screenshot of what happens when you try to create a workspace with `&` in the name? We are having trouble reproducing this.

<img width="406" alt="Screenshot 2019-05-11 at 12 01 20 PM" src="https://user-images.githubusercontent.com/3295568/57565982-9caf9080-73e4-11e9-8386-d4fb006cefb1.png">

**Comment by joakimwennergren** [comment]
I was mistaken, it works like it should.
