### ISSUE TITLE
Collection tests appear jumbled when other is viewing it

### ISSUE THREAD

**Issue by daokrajaih** [a85/POSTMan-Chrome-Extension#6487]
**Describe the bug**
In my workspace, I created several steps within a folder inside a collections.  When I view them, I can see that the tests are saved in the order I want to execute.  I labeled each step with a number from 1 through 11.  This collection is linked to a Team Workspace.  When other team member views it, the steps appeared to be jumbled. 

**To Reproduce**
No clear steps to reproduce.  This happens to tests inside of my folder within a collection.  There is also no clear way to fix the appearance of the steps for other team member.  

**Expected behavior**
The tests should be saved in the order that they are arranged inside the folder.  

**Screenshots**
Screenshot view from my workspace
![created and saved in my workspace](https://user-images.githubusercontent.com/48604538/57643352-8988f600-7587-11e9-9b06-3ab7b3f3941a.png)

Screenshot view from my point of view Viewing Team Workspace 
![view by me via team workspace](https://user-images.githubusercontent.com/48604538/57643366-90b00400-7587-11e9-9552-bcad98683a3d.png)

Screenshot from team member
![view by my co-worker from shared workspace ](https://user-images.githubusercontent.com/48604538/57643370-94438b00-7587-11e9-8460-53981f7e9f72.png)

**App information (please complete the following information):**
 - App Type : postman app
 - Postman Version : 6.7.4
 - OS : window 10

**Additional context**

**Comment by kamalaknn** [comment]
Hey @daokrajaih 

Thanks for reporting this. This is definitely not an expected behaviour.

To help us investigate this better can you  give us some more information.

How did you create these requests? And which app are you seeing the wrong order - the app where you created the requests or the other app where it was synced.

**Comment by daokrajaih** [comment]
Hi Kamalaknn,
I don't know at which point the issue occurred.  I usually do the following.

1) At the beginning, I either create collection on Team workspace or in my workspace 
2) I then share that collection to Team workspace or to my workspace 
3) In my workspace, I started creating requests and run my tests.  
4) At some point after I finish, my teammate look at my test collection from Team Workspace.  That is where they observed the issue.

**Comment by kamalaknn** [comment]
@daokrajaih Hey can you view the same collection on the web dashboard and check the order shown there (you can click the "View in web") button on the collection details section.

Can you send the logs from `View -> Developer -> View logs in Finder` to `help@getpostman.com` from your registered email id so that we can take a deeper look?

**Comment by daokrajaih** [comment]
Hi Kamalaknn, 
My co-worker was able to share the collection from Team Workspace into personal workspace and can view the tests in the correct order now.

**Comment by sujayvenaik** [comment]
Hey @daokrajaih 
I'll go ahead and close this issue for now then if you face any other issues if related to this post it here else open a new issue.
