### ISSUE TITLE
Pre-request Script - environment variable referenced in raw json body does not update

### ISSUE THREAD

**Issue by JeFFBlanco** [a85/POSTMan-Chrome-Extension#649]
Loving the latest **POSTMan!**  Thanks for all the great additions! :)

I'm super excited about the _Pre-request Script_ feature.  I did notice one issue, when the  environment variable is referenced within a request's raw Json Body.  

While the value is properly set within the active Environment, it seems to only apply to the variable references within the request header, or form data; **not** areas directly within a raw Json Body.

Thanks!

**Comment by alliequintano** [comment]
Hello, I am still experiencing an issue with environment variables not being evaluated before the request is sent. 

I am using Postman Version 3.2.7 (packaged).

I am making a request with a raw JSON using the {{..}} delimiters. When I wrap the environment variable in a string, the variable is not evaluated. When I don't wrap it in a string, I get a bad request response because the value is not a string, and the value is still not evaluated. 

Please let me know what I can do to use environment variables in raw JSON body request. I love this feature!

**Comment by abhijitkane** [comment]
@alliequintano Are you facing the issue with global variables as well? Try adding a global variable (Manage environments > Globals). If added correctly, you should see the variable appear in the list when you click on the "x" icon near the environment menu.

**Comment by alliequintano** [comment]
@abhijitkane I just gave it a go, and did not experience any different behavior than I have described (variable is not being evaluated). I am seeing the global variable when clicking on the X icon. 

I had not tried it with global variables yet since I need the variable to be environment-specific for my purposes. 

Thank you for the quick reply.

**Comment by abhijitkane** [comment]
@alliequintano Can you contact us at help@getpostman.com?

**Comment by zmb5000** [comment]
I'm experiencing the same issue, as I am trying to get the variables within my raw JSON body to be evaluated for the POST request I am trying to send. I have the variables in my environment, and most are strings, but 2 are integers and they are not being evaluated. Is this an ongoing bug that is still being fixed?

**Comment by EMBuildEngineer** [comment]
@zmb5000 i too experience the same issue where a variable set in environment variable is not substituted in the raw body request. I tried within quotes and without quotes too still not working.
Let me know if you had got it working.

**Comment by zmb5000** [comment]
I definitely will. The more help, the merrier. :-)

**Comment by zmb5000** [comment]
Are you using the most recent version postman? I updated my version and it
worked now. I am able to evaluate variables without quotes around them now,
even though booleans and integer variables being referenced from the
environment will be highligthed red, as if they are not being evaluated.
After all of your variables are in place, run the request and see if it
returns a 200... if not then it may be something else. Let me know if I can
help anymore, I'll be more than glad to help!

**Comment by EMBuildEngineer** [comment]
![image](https://user-images.githubusercontent.com/35581860/35536264-3cc7bbb0-04fb-11e8-8c06-9b857fb78e7b.png)
@zmb500 thats the version i am using.

**Comment by EMBuildEngineer** [comment]
@zmb5000 when  i use the same variable in URL, it works fine. But its not evaluating itself when used in Body --> raw (i checked text, application/json formats)

**Comment by zmb5000** [comment]
Can you send what code you have so far?
