### ISSUE TITLE
Post method does not maintain uploaded file if changing any other parameter of API

### ISSUE THREAD

**Issue by mubashir3gca** [a85/POSTMan-Chrome-Extension#6516]
**Describe the bug**
I am using post request in postman. I am providing a text file as file input parameter in api parameter and there are other parameters as well but those are simple text input parameters.
In case, I am providing all parameters and sends the request and if api request gets failed due to input field validations of text input parameters. In such situation, when updating/modifying the invalid/faulty text input parameter value to valid value, then postman shows the name of file (that was previously provided as file input) along with its extension but when re-submits the same request then it gives error message related to file input parameter that the required file is missing.
I have observed that if on first attempt, if API request is failed due to any other invalid input parameter then on modifying that invalid parameter value, I must have to provide the file input every time even if it is showing the same file name in the file input field. This issue has been observed in the latest version of postman. In earlier version of postman, it was maintaining the provided input file.

**To Reproduce**
1. Go to New and create a new request with post method
2. Go to Body tab and select form-data
3. Add few parameters as text input along with their values in key value columns (provide any one parameter with invalid input value in order to make the API request failed due to data validation or leave any required parameter as empty)
4. Add one parameter as file input and provide a valid file for it (this is required)
5. Submit the request and API request should be failed due to missing required parameter or due to invalid value in any of the provided parameter
6. Now provide the missing value for required parameter or modify the invalid value of the parameter
7. Postman will be showing file name with its extension as provided earlier
8. Now re-submit the same request and this time API will fail again and it is due to file input parameter since it is missing

5. Screenshots are provided for reference

**Expected behavior**
It should maintain that provided file (as it was in previous version of postman).

**Screenshots**
See the attached screenshots for reference.

![postman version](https://user-images.githubusercontent.com/32706486/57809235-7be99100-777e-11e9-8a93-b96b8a4cbaa3.png)

![request first attempt](https://user-images.githubusercontent.com/32706486/57812109-83f8ff00-7785-11e9-8161-5fbdc6201fb2.png)

![request second attempt](https://user-images.githubusercontent.com/32706486/57812118-8bb8a380-7785-11e9-872e-841ee6f597c6.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.1.0]
 - OS: [Windows 10 (x64)]

**Comment by saswatds** [comment]
Hi @mubashir3gca, 
Recently we have made some changes to ensure that we can persist file references along with collection. I have given a more detailed explanation of the behaviour in this issue https://github.com/postmanlabs/postman-app-support/issues/4320#issuecomment-490749103

Having said that, I need some more information from you regarding this issue. 

1. Can you check your postman console and find if any error message is shown when you send the request?
ex: 
<img width="816" alt="Screenshot 2019-05-16 08 51 06" src="https://user-images.githubusercontent.com/8796447/57824183-da7f3100-77b7-11e9-8469-e494c698eb5c.png">

2. If you see the message `PPERM: insecure file access outside working directory`, Can you confirm that form data file was selected by you on the same computer you are trying to send the request?

3. Or do you see the message `no such file`?

**Comment by mubashir3gca** [comment]
Hi @saswatds,
1. It is showing "Form param `file`, file load error: PPERM: insecure file access outside working directory" in postman console.

![postman console](https://user-images.githubusercontent.com/32706486/57827755-161ef880-77c2-11e9-8890-186d40f45542.png)

2. Form data file was selected from my computer but i am sending that request to other server and not on the same computer from where form data file was selected.

**Comment by saswatds** [comment]
Hi @mubashir3gca, Thanks for the input. 
Prior to v7.1.0 postman did not sync file paths across different app. The current behaviour is as follows
1. If a file is selected inside of the working directory we save the relative path to file
2. If a file is selected outside of the working directory we save the absolute path to the file. 

By default postman does not trust absolute paths. You can already see that the app is already warning you of that. This is a security feature added so that when untrusted collection/request are executed on your system, they don't steal you data.

As you have stated that you are sending the request from a computer which is different from the one where you selected the file, the app by default doesn't trust the file and throws the `PPERM` error.

You have 2 ways to go about from here
1. You can copy/move the file to the working-directory on both your computers, and then select the file. The app should work seamlessly on both systems as the relative path will be synced. You can find the working-directory in the Settings -> General
2. You can turn on the setting `Allow reading files outside working directory` after verifying that the saved absolute is correct and the file exists on your system.

I think this should fix the problem. Feel free to respond back if this doesn't work.

**Comment by rubenmelcon** [comment]
Hi @saswatds 

I had the same issue and I tested your second solution but it doesn't seems to work. In my case, I'm executing a multipart upload with two files, but the tool only sends the last updated parameter. 

![image](https://user-images.githubusercontent.com/16529900/57857768-12a26600-77f0-11e9-8262-e4220f28db47.png)

If I update the var1, Postman will send the file "file.json" but not var2. If, in this point, I update the var2 parameter, then I will receive the file "file-schema.xml" but not the var1 parameter.

Hope that this information helps you in detecting the origin of the problem. 

Kind Regards

**Comment by saswatds** [comment]
Hi @rubenmelcon, this is not supposed to happen. 

The internal tests I have setup is able to send both the file properties.  This is the step by step detail of how I have done to replicate it and would request you to attempt it as well so that we are on the same page. 
1. Created 2 file called `file1.txt` and `file2.txt` and seeded some random string to both file
2. Created a POST request to `https://postman-echo.com/post` with body type `form-data`
3. Selected first file and sent a request (As you can see below)
<img width="849" alt="Screenshot 2019-05-16 19 36 21" src="https://user-images.githubusercontent.com/8796447/57860164-f7485280-7811-11e9-85b4-51cbb62d3ccd.png">
4. Selected the second file and sent a request (As seen below)
<img width="848" alt="Screenshot 2019-05-16 19 38 21" src="https://user-images.githubusercontent.com/8796447/57860249-2ced3b80-7812-11e9-90c5-fb5e411fb94a.png">

As you can see both the file we sent and the server responded with both the filenames. 

Can you confirm that you do not experience the same behaviour?

**Comment by rubenmelcon** [comment]
Hi @saswatds:

I just tested with the same URL that you used:

In my first case, I copied my original request and updated the datasource parameter to clean some information and the response was:

![image](https://user-images.githubusercontent.com/16529900/57861493-feae3280-77f6-11e9-80e2-66ec420b2add.png)

As you can see I don't have any of the files.

After that, I updated the var1 variable, and the response was:

![image](https://user-images.githubusercontent.com/16529900/57861588-22717880-77f7-11e9-95ef-c714ed462273.png)

As you can see, only the file "file1.json" was sent.

Now, changing the var2 parameter and resubmitting the request I can see how the file from the var1 parameter is not in the response but I have the var2 file:

![image](https://user-images.githubusercontent.com/16529900/57861744-75e3c680-77f7-11e9-800b-7d19d521d047.png)
 
Just to confirm that it's not related with my (original) request, I created a new one with only one parameter:

![image](https://user-images.githubusercontent.com/16529900/57862026-f30f3b80-77f7-11e9-8b13-3412d1d10ddc.png)


That's perfect, but if I add another parameter (it doesn't have to be a file) I will loose the information related with the file:

![image](https://user-images.githubusercontent.com/16529900/57862117-1f2abc80-77f8-11e9-943d-1619fda9356b.png)



Thank you very much

**Comment by saswatds** [comment]
@rubenmelcon Thanks for the input. We are really sorry this is happening. I will try to find the root cause of this problem in high priority and keep this thread updated with my findings

Thanks

**Comment by saswatds** [comment]
@rubenmelcon I would require one more key insight from you. When you selected the second file and the first file was not sent, are you seeing any errors in the postman console like the one I had shown in the above comment https://github.com/postmanlabs/postman-app-support/issues/6516#issuecomment-492903114 ?

**Comment by rubenmelcon** [comment]
Hi @saswatds 

I'm not at the office, but I can replicate the same problem from another computer. And "yes", from my (new) current installation when I try to replicate this issue I can see the error message in the console. Sorry to not  give you before this information. Let me put here all the steps and information.

The first request has only the parameter with the file:

![imagen](https://user-images.githubusercontent.com/16529900/57875118-6a51c900-7812-11e9-9587-b65666812596.png)

As you can see, everything is ok and the console doesn't show any error:

![imagen](https://user-images.githubusercontent.com/16529900/57875207-a4bb6600-7812-11e9-8ef0-4e31f6ac9d3f.png)

Now, I will include a normal (text) parameter "var2":

![imagen](https://user-images.githubusercontent.com/16529900/57875313-ea782e80-7812-11e9-9488-99dbc0c5df89.png)

We can't see the "var" parameter and looking at the console we have the message that it's not able to find the file:

![imagen](https://user-images.githubusercontent.com/16529900/57875368-0d0a4780-7813-11e9-9c6e-6b5fa2995bc5.png)

Maybe the problem is all the chars before "C" in the route "/////////C:/Users/ruben/Desktop/file1.txt". I'm not sure it this was also the previous error message because I was using another computer, but I think that it's very probable. If you want, I can confirm this on next monday.

Also, the console shows that the requests has only the var2 parameter:

![imagen](https://user-images.githubusercontent.com/16529900/57875582-928df780-7813-11e9-90ca-7a995e95970d.png)

Thank you very much

Kind Regards

**Comment by saswatds** [comment]
Thanks a lot @rubenmelcon 🎉 
I have been able to reproduce the issue internally. You are right the issue is with the extra `/` being added in front of every absolute path in windows os. The request shows only one file because of the runtime not being able to load the file.
We have already applied the patch with additional tests for windows to our builds, and it should be out within a few days.

**Comment by mubashir3gca** [comment]
> Hi @mubashir3gca, Thanks for the input.
> Prior to v7.1.0 postman did not sync file paths across different app. The current behaviour is as follows
> 
> 1. If a file is selected inside of the working directory we save the relative path to file
> 2. If a file is selected outside of the working directory we save the absolute path to the file.
> 
> By default postman does not trust absolute paths. You can already see that the app is already warning you of that. This is a security feature added so that when untrusted collection/request are executed on your system, they don't steal you data.
> 
> As you have stated that you are sending the request from a computer which is different from the one where you selected the file, the app by default doesn't trust the file and throws the `PPERM` error.
> 
> You have 2 ways to go about from here
> 
> 1. You can copy/move the file to the working-directory on both your computers, and then select the file. The app should work seamlessly on both systems as the relative path will be synced. You can find the working-directory in the Settings -> General
> 2. You can turn on the setting `Allow reading files outside working directory` after verifying that the saved absolute is correct and the file exists on your system.
> 
> I think this should fix the problem. Feel free to respond back if this doesn't work.

Hi @saswatds,

I have tried the first method suggested by you. I have placed the specific file in the working-directory path and it worked fine for me.

I have also tried the second method suggested by you. I have turned on the setting "Allow reading files outside working directory" and then I submitted request. It is giving error in console in case I have updated any other API parameter value.

There are multiple '`\`' at the start of the path which may be causing issue for file to be loaded.

I have provided the screenshots for reference.

![request 1](https://user-images.githubusercontent.com/32706486/57908503-88164100-7899-11e9-9448-01aff92c7110.png)

![request 1 console](https://user-images.githubusercontent.com/32706486/57908527-9c5a3e00-7899-11e9-8216-01ffbdd4fcd1.png)

**Comment by saswatds** [comment]
@mubashir3gca Thanks. This a high priority issue for us, the root cause has been identified and bug-fixes have been made. A patch release will be out soon.

**Comment by mubashir3gca** [comment]
> @mubashir3gca Thanks. This a high priority issue for us, the root cause has been identified and bug-fixes have been made. A patch release will be out soon.

@saswatds You're welcome. Looking forward for patch release.
Thanks

**Comment by saswatds** [comment]
@mubashir3gca @rubenmelcon The patch has been released as part of Postman App v7.1.1 
You can go ahead and test it out. I will close this issue once I get a confirmation on your end.

Thanks.

**Comment by rubenmelcon** [comment]
Hi @saswatds:

I just tested the new version and it's working for me

Thank you very much

Kind Regards

Ruben

**Comment by mubashir3gca** [comment]
Yes, it is working fine now

**Comment by frog9001** [comment]
Sorry to bring this up again, but i'm running v7.36.1 and this fix it's not working for me if i run the request in the Collection Runner.

The only solution i've found is to enable "Allow reading files outside working directory", but it's not ideal.

Any help?

Thank you very much

**Comment by smali-kazmi** [comment]
i got this error after updating my Postman to latest version reason behind was that i have to remove file and reselect it issue was resolved!

**Comment by chetanrudrakar** [comment]
Facing the same error "This file isn't in your working directory. Teammates you share this request with won't be able to use this file. To make collaboration easier you can setup your working directory in Settings." got frustrated with this error. I have installed the latest version facing the issue. Can u please resolve this 
![image](https://user-images.githubusercontent.com/84122372/118095024-2f78d080-b3ed-11eb-8ee0-e48afbce1e68.png)
![image](https://user-images.githubusercontent.com/84122372/118095150-5b945180-b3ed-11eb-959b-1741e55c73c8.png)
Also my location is correct

**Comment by TheProgrammer21** [comment]
> Facing the same error "This file isn't in your working directory. Teammates you share this request with won't be able to use this file. To make collaboration easier you can setup your working directory in Settings." got frustrated with this error. I have installed the latest version facing the issue. Can u please resolve this

Were you able to resolve this issue?

**Comment by ramonpaolo** [comment]
Same problem here, with the version `v9.21.2`
