### ISSUE TITLE
Issue with Keyboard shortcut - Switch tab

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6517]
**Describe the bug**
Unable to switch between tabs using shortcut keys

**To Reproduce**
1. Try switching tabs
2. Switch To Next Tab -  Ctrl+Shift+] or ⇧ ⌘ ]
    Switch To Previous Tab - Ctrl+Shift+[ or ⇧ ⌘ [

**Expected behavior**
To be able to switch between tabs

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.04
 - OS: Windows

**Additional context**
Switching to tab at position works.

**Comment by sujayvenaik** [comment]
Hey @Kurmavathar 
We have pushed certain stability improvements and fixes for shortcuts which is available on the latest Canary version. (https://www.getpostman.com/downloads/canary)
Try it out once and do let us know.

**Comment by MikeCongdon1** [comment]
on Ubuntu 18.04.3 LTS >
Postman for Linux
Version 7.5.0
linux 5.0.0-25-generic / x64

it appears that some shortcuts work, but they aren't what is documented in Settings/Shortcuts.
I can use Ctrl + Tab to switch between tabs.
After switching tabs, I need to click in the "body" section (Query Params, Response, etc)  (OR I can toggle the sidebar away Ctrl + \   then Ctrl + L and some other shortcuts will work.

I think some of the issue here is simply documentation:
"Ctrl + E will only work when the sidebar is in focus"
"Ctrl + L will only work when the tab body is in focus"

If I am typing in the "url" field Ctrl + \ requires 2 clicks. q to restore focus, and the other to complete the action (show/hide sidebar).

Hopefully this is helpful info.

**Comment by DannyDainton** [comment]
Closing this issue as it has now been resolved.

Please feel free to reopen with the steps to reproduce if the issue persists
