### ISSUE TITLE
Content-type

### ISSUE THREAD

**Issue by dkonyayev** [a85/POSTMan-Chrome-Extension#6523]
**Describe the bug**
With Postmanruntime/7.13.0 I started to have issue with content-type. My body is raw and content-type selected is JSON (application/json). However, postman is inserting another content-type header with value "text/plain", and that is what passed in request.

**To Reproduce**
1. Create POST request with JSON body and select JSON (application/json)
2. Submit request
3. In Postman Console I see content-type as "text/plain"
4. When vieweing headers for request I see my custom Content-Type = "application/json", and another auto-inserted header Content-Type = "text/plain"

**Expected behavior**
It should be using Content-Type that I selected when defining the body.

**Screenshots**
Attaching DOC file with screenshots

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version:  Postman v7.1.1-canary02
 - OS: Windows 10
[postman-content-type-issue.docx](https://github.com/postmanlabs/postman-app-support/files/3187952/postman-content-type-issue.docx)

**Additional context**

**Comment by dkonyayev** [comment]
I want to add that this started very recently. It has worked properly as recently as 5/10

**Comment by malwageddon** [comment]
Same issue on Ubuntu after upgrading to Postman v7.1.0. Did not have that issue on the previous version.

**Comment by codenirvana** [comment]
@dkonyayev @malwageddon Can you confirm that the requesting server receives multiple `content-type` headers or is it always getting replaced by`text/plain`?

One way to check this:
1. Select the `POST` method
2. Request `https://postman-echo.com/post`
3. Set body and `Content-Type` (say, `application/json`)
4. Check what's the `Content-Type` received in the response
5. Check if an extra header has been added under "Temporary Headers" section

Please share the result of step 4 and 5 because I am not able to reproduce this issue.
Also, If possible can you share a scaled-down collection with the specified behavior?

**Comment by dkonyayev** [comment]
So what I created 2 identical requests. In my current collection there is an automatic header added for Content-Type = "text/plain". HOwever, I duplicated this request to a brand new collection and I don't have that issue there. It correctly sends application/json content-type.

**Comment by codenirvana** [comment]
@dkonyayev For `raw` and `binary` mode if no `Content-Type` is set then it defaults to `text/plain`.
Are you still facing this issue with every newly created request or particular to your already saved requests in your collection?

**Comment by malwageddon** [comment]
@codenirvana I have this issue when using POST to send 'form-data' to my API server. The way it used to work before is that under 'Body' tab I set the KEY type to 'File' and select a file to upload, click 'Send'.

After looking closely at what's happening now, i noticed that 'content-length' header does not have a value(not sure if it's expected behavior), see below:
![image](https://user-images.githubusercontent.com/10896788/57914700-12a17500-7887-11e9-9bb9-3192dc1f59a8.png)

Setting 'Content-Type' manually to 'multipart/form-data' doesn't seem to change much.

Tried replaying the same type of request against 'https://postman-echo.com/post' - i get 'Internal Server Error'. Again, not sure this is the right URL to run this type of POST tests against of.

Hope this helps. Please let me know if you want me to try anything else.

Cheers,

**Comment by dkonyayev** [comment]
@codenirvana I figured out the issue on my end. In my collection script I issue "pm.request.headers.clear();", which I assume deletes the application/json header, and Postman then inserts the default text/plain. I could swear that this didn't happen before but it working now. Thanks!

**Comment by codenirvana** [comment]
@dkonyayev You are right, we've added support for this in v7.0.9. Refer: https://github.com/postmanlabs/postman-app-support/issues/4631#issuecomment-477766260

**Comment by Kshitij891** [comment]
In header add Content-type : application/json explicitly and untick the one which is already present
