### ISSUE TITLE
Postman v7.1.0 crashes when running collection via Runner (1k+ requests)

### ISSUE THREAD

**Issue by sl4m** [a85/POSTMan-Chrome-Extension#6525]
Crash log: https://gist.github.com/sl4m/451b4b9d0def197bf3bc576ada8594f1

v7.0.9 does not show this symptom

**Comment by saswatds** [comment]
Hi @sl4m thanks for reporting this issue
Can you provide a little bit more information on how this happened? 
1. Does the app crash on the selection screen or during the running of the collection
2. Does it crash on a particular request or just randomly on any request?
3. Was this happening on the app prior to 7.0.9?
4. Any other detail that could help us reproduce this issue?

**Comment by sl4m** [comment]
@saswatds,

Here's what I know:

1. Does the app crash on the selection screen or during the running of the collection
> During running of a collection.
2. Does it crash on a particular request or just randomly on any request?
> Not sure because my collection has about 1.3k requests
3. Was this happening on the app prior to 7.0.9?
> Not sure because I developed the collection on 7.0.9.
4. Any other detail that could help us reproduce this issue?
> I ran this collection twice and it crashed both times. I reverted back because I needed to continue working.

**Comment by sl4m** [comment]
v7.1.1 exhibits same crash behaviour

**Comment by psonoh** [comment]
I'm having the same problem. I'm running a collection that several of my colleagues can run with no issue - but for me it crashes when it's approximately 80% done :(

**Comment by ghost** [comment]
My collection has 193 requests.  Ran it fine on this same postman version just a few days ago.  Now it crashes every time on the same request maybe 10 requests in. 7.14.0.  That request runs fine from the regular app but the collection runner crashes every time now for some reason.

**Comment by saswatds** [comment]
@sl4m @psonoh @recordstuff  We have pushed all of our performance fixed to the stable version 7.18.0. The runner should be snappier and not crash. Can you update to the latest version and check if this issue is fixed for you?

**Comment by ghost** [comment]
@saswatds The runner no longer crashes for me, thank you.

**Comment by sl4m** [comment]
@saswatds Thanks for the fix. Unfortunately, I'm unable to run what crashed before since I left the company.

**Comment by saswatds** [comment]
Thanks for verifying. I am closing this issue as resolved.

**Comment by atom88888** [comment]
I have noticed the same thing when I only have 2-3 tabs open but a local "collection" of 150-300 requests.  I think perhaps a large number of collections is causing CPU / memory issues.  I have had to prune down my number of stored / saved requests in order to improve postman's performance.  At first I thought it was my computer or OS but when I closed POSTMAN my system resumed normal response times.

The app hasn't crashed for me though, so that's good.

Where can I find the setting that is preserving history so I can turn it off, to make sure that's not causing performance issues too?

**Comment by BEPEREZ** [comment]
I have the same issue while running a collection on Runner it crash and I have to start it all over again .
My csv is 1372 kb  with 3024 records . it just process 300 or 200 or 400 or even less records , 

in the attach screen you can see so many Runners because every time it crash I have to open another collection.

![Screenshot 2023-05-17 132228](https://github.com/postmanlabs/postman-app-support/assets/40614437/0a2ceaac-0fcb-4949-9797-a3f30d6734a2)


Is there a solution for this kind of behaviour
