### ISSUE TITLE
Monitor fails but collection runner does not

### ISSUE THREAD

**Issue by chrisj-ifs** [a85/POSTMan-Chrome-Extension#6526]
**Description**
I'm seeing an issue where some of my daily monitors are failing with:
**Error: Parse Error
9 | 16:04:38 | JSONError: Unexpected token u in JSON at position 0**
If I run this same exact collection in Newman or Collection Runner the complete collections passes without error. 

**To Reproduce**
1. Schedule Daily Monitors

**Expected behavior**
Monitors should pass if same collection passes locally in Postman or Newman

**Screenshots**
![image](https://user-images.githubusercontent.com/49196637/57884147-ff929480-77f5-11e9-9342-e73755f29f05.png)

**App information**
- Postman Version 7.0.0

**Additional context**
This issue is intermittent

**Comment by chrisdeso** [comment]
@chrisj-ifs The error appears to indicate that an unexpected response body is being returned. Would you add the snippet below to your request to see if any useful information is logged?

`console.log(JSON.stringify(responseBody, null, 2));`

Depending on how/if you're leveraging variables for the collection, the difference in behaviors may be expected. Before I make too many assumptions, are you leveraging any of the different types of Postman variables for the request(s) in question?

- https://learning.getpostman.com/docs/postman/environments_and_globals/variables/

**Comment by zrosenbauer** [comment]
We seem to be having this issue also.

**Comment by zrosenbauer** [comment]
> We seem to be having this issue also.

Actually, this looks slightly different. Will open new issue.

**Comment by chrisj-ifs** [comment]
> @chrisj-ifs The error appears to indicate that an unexpected response body is being returned. Would you add the snippet below to your request to see if any useful information is logged?
> 
> `console.log(JSON.stringify(responseBody, null, 2));`
> 
> Depending on how/if you're leveraging variables for the collection, the difference in behaviors may be expected. Before I make too many assumptions, are you leveraging any of the different types of Postman variables for the request(s) in question?
> 
> * https://learning.getpostman.com/docs/postman/environments_and_globals/variables/

I'm not thinking it's an variable issue most of my variables are set from the previous request. I followed your instructions adding the console output snippet to the first two POST's since it seems to be where the "JSONError: Unexpected token u in JSON at position 0" message is coming from and the Monitor Console displayed the access token info see pic. 

![image](https://user-images.githubusercontent.com/49196637/58096419-06792880-7ba3-11e9-834b-8fb847359fe4.png)

**Comment by godfrzero** [comment]
@chrisj-ifs Are you still experiencing this problem? All of the errors in the logs so far seem to stem from JSON parse errors, and not directly related to the platform.

We'll need more information specific to the collection in order to troubleshoot what's happening here. Could you open a ticket on [our support center](https://www.postman.com/support/)?

**Comment by godfrzero** [comment]
Closing this for now. Will reopen if additional reports/information comes in.

**Comment by q30** [comment]
I am seeing it the other way round. When/if the api response isn't correct, Postman monitors don't register it as a failure. (In the second screenshot you can see it as 0% failures)

<img width="1154" alt="Screenshot 2020-06-19 at 10 18 50 AM" src="https://user-images.githubusercontent.com/4234926/85100211-328b3100-b21d-11ea-8fde-9190c1992444.png">
![1](https://user-images.githubusercontent.com/4234926/85100220-37e87b80-b21d-11ea-9d79-0f09dfa4d87c.png)

![1](https://user-images.githubusercontent.com/4234926/85100242-40d94d00-b21d-11ea-999c-9da19c628100.png)

**Comment by godfrzero** [comment]
@q30 The logs you've attached show errors, but not failures. A monitor fails when it has failing test assertions. As far as I can tell from the logs, the execution runs into exceptions (possibly due to a non-JSON input being used in JSON.parse) before it reaches the test assertions.

If you're expecting a JSON response, you should add an assertion to test whether the API response is JSON parseable before actually parsing it and running additional tests.

**Comment by q30** [comment]
@godfrzero Thanks for the details.

Could you give an example of how to test that? Because in my case I test for status to be 200 as my first test case, and interestingly while the response of these apis was 500, the test never executed. 

Another reason to ask is, I am planning to use the below style of code at the beginning of the test:

```
let r = '';
try {
    r = JSON.stringify(pm.response.json());
} catch(e) {
    r = pm.response.text();
    console.warning(r);
}
```

So I'd love to know if there are any other patterns that are recommended for this use case.

**Comment by godfrzero** [comment]
The snippet you've attached should work. If you need to repeat this across multiple requests, I'd recommend placing this in the folder or collection pre-request script so that it executes before every request within that folder/collection.
