### ISSUE TITLE
Hope support for PathVariable in url

### ISSUE THREAD

**Issue by imic07** [a85/POSTMan-Chrome-Extension#6536]
**Is your feature request related to a problem? Please describe.**
My postman ver is v6.7.4, now I found that postman cant handle pathvariable in url, this is terriable when i want to build a doucument or test it.

for example, as fllows:
![image](https://user-images.githubusercontent.com/16321067/57917634-b0b52f80-78c7-11e9-8a28-a9052fc00ade.png)
My url is {{ipport}}/flow/task/complete/{pathvariable}?paramA=1&paramB=12

If i want to test it, i must replace {pathvariable} to f26cc46c-7872-11e9-b3e3-42f02f5cd884. this may make me or other dont know what f26cc46c-7872-11e9-b3e3-42f02f5cd884 means.

As the interface, the url should changeless.

**Describe the solution you'd like**
Hope postman can auto add params like {xxx}  in url to Params Area without add ?xxx to the end of the url or add {xxx} in a new Area such as Variables before Params:
![image](https://user-images.githubusercontent.com/16321067/57919089-afd1cd00-78ca-11e9-80bd-5e7b39eb5b37.png)

**Comment by saswatds** [comment]
Hi @imic07 
Postman already supports path-variables, just the notation to do so is slightly different
You can try `{{ipport}}/flow/task/complete/:pathvariable?paramA=1&paramB=12` activate the path variable support in params section. We use `:<variable>` notation instead of `{<variable>}`. 

![Screenshot 2019-05-17 15 34 39](https://user-images.githubusercontent.com/8796447/57920722-56ad6d80-78b9-11e9-9e1d-1acd51e338ee.png)

I hope this helps, I will be closing this issue, but feel free to reopen the issue if you desire. Thanks

**Comment by imic07** [comment]
> Hi @imic07
> Postman already supports path-variables, just the notation to do so is slightly different
> You can try `{{ipport}}/flow/task/complete/:pathvariable?paramA=1&paramB=12` activate the path variable support in params section. We use `:<variable>` notation instead of `{<variable>}`.
> 
> ![Screenshot 2019-05-17 15 34 39](https://user-images.githubusercontent.com/8796447/57920722-56ad6d80-78b9-11e9-9e1d-1acd51e338ee.png)
> 
> I hope this helps, I will be closing this issue, but feel free to reopen the issue if you desire. Thanks

@saswatds Most developers use Spring Framework, the springs  pathVariable style is {xxx} (RESTFUL), so hope support {xxx} this style. then we can use the api everywhere without changeto :<variable>
