### ISSUE TITLE
This file resides outside the working directory. Collaborators might not have the same file path.

### ISSUE THREAD

**Issue by xiandadaa** [a85/POSTMan-Chrome-Extension#6556]
After being updated to 7.x, you cannot upload files like an array。Unable to read files outside of working directory

![image](https://user-images.githubusercontent.com/27729133/58062530-3d543c00-7bad-11e9-8392-e5a5cf505c43.png)
![image](https://user-images.githubusercontent.com/27729133/58062543-4b09c180-7bad-11e9-8a7b-6e211ca612a6.png)

**Comment by saswatds** [comment]
Hi @xianda666 
Prior to v7.1.0 postman did not sync file paths across the different apps. The current behavior is as follows

If a file is selected inside of the working directory we save the relative path to file
If a file is selected outside of the working directory we save the absolute path to the file.
By default, postman does not trust absolute paths. You can already see that the app is already warning you of that. This is a security feature added so that when untrusted collection/request is executed on your system, they don't steal your data.

If you are sending the request from a computer which is different from the one where you selected the file, the app by default doesn't trust the file and throws the PPERM error.

You have 2 ways to go about from here

You can copy/move the file to the working-directory on both your computers and then select the file. The app should work seamlessly on both systems as the relative path will be synced. You can find the working-directory in the Settings -> General
You can turn on the setting Allow reading files outside the working directory after verifying that the saved absolute is correct and the file exists on your system.

Hope this clarifies the messaging. We will try and improve messaging in future iterations. For knowing more into the background of this change, you can check out https://github.com/postmanlabs/postman-app-support/issues/4320#issuecomment-490749103

**Comment by dahernandez** [comment]
@xianda666 put your files on your working directory and that's it

**Comment by Kjnrydr** [comment]
Turning On the Allow reading files outside the working directory does not work alone.  In the "KEY" column you have add some description basically along with selecting File from the dropdown.  If you don't add something in the KEY column the error still persist.  

I changed my working directory to where the file was and no longer received the message however the http request was still not uploading my file until I added something in the KEY column.  I even added a simple "a" and it worked fine.

Just thought I'd drop that info.

**Comment by saswatds** [comment]
This issue was kept open to track the task of change in messaging around the warning. 
In the latest version of app (v7.6.0) we have updated the messaging to reflect accurately what the warning is meant for i.e collaboration. Closing this issue now.

**Comment by pro-react233** [comment]
Hello,
I am using postman(v7.7.3) and I have got the following warning when I upload the file to send the body as a form-data.
"This file isn't in your working directory. Teammates you share this request with won't be able to use this file. To make collaboration easier you can set up your working directory in Settings."
How can I solve it?

![pathError](https://user-images.githubusercontent.com/56240288/73638816-13dd3100-46a6-11ea-97a4-1d388c44a0da.png)

**Comment by sabuncu** [comment]
@saswatds

> You can copy/move the file to the working-directory on both your computers and then select the file. The app should work seamlessly on both systems as the relative path will be synced. You can find the working-directory in the Settings -> General

Is a copy of the file saved under the Postman cloud account for the user?  That is, is it sync'ed to the user's Postman cloud account?  Is this a feature?  It would make running a request much easier for others.

Thank you.

**Comment by roger-king** [comment]
I am running into this issue still running on `Version 8.1.0-210401-0400` Desktop agent with web UI. I noticed the Workspace directory is different than the default one created when I installed the desktop agent. The desktop agent created `~/Postman Agent/files`. While the web ui settings has it set to `~/Postman/files`. Once I changed the path to `~/Postman` it worked fine.

Although I think there may still be an issue with allowing access to outside directories because with that checked on I still could not upload files.

**Comment by Andreagar28** [comment]
I have this issue..

**Comment by Novivy** [comment]
Same issue. Checked  `allow reading files outside...` but doesn't work either.

can't change the location the input is disabled..

**Comment by Juli-Bk** [comment]
Hello! I have the same problem.
Postman version 8.6.2 (8.6.2). I noticed that after I changed the working directory by Settings->General trying to configure Newman. It is impossible now to set it back to ~/Postman/files (with ~ sign), it shows the absolute path. I cant send files using form-data. Not one file, nor an array of them. In Postman console I can see "undefined" for the request body in "product-images" key.
I have copied sending files into the working directory.
Before I have changed the working directory path it works fine. Tried to reinstall Postman on Mac. Nothing helps. 
Any idea how to fix it? Seems like I cant test APIs with "form-data" files at all.


<img width="372" alt="Снимок экрана 2021-06-15 в 19 52 43" src="https://user-images.githubusercontent.com/56931989/122095233-c7ffd780-ce15-11eb-909f-2aa8deba7da0.png">

<img width="740" alt="Снимок экрана 2021-06-15 в 19 53 01" src="https://user-images.githubusercontent.com/56931989/122095259-d0581280-ce15-11eb-9056-1cb4837c1df2.png">

<img width="892" alt="Снимок экрана 2021-06-15 в 19 53 18" src="https://user-images.githubusercontent.com/56931989/122095285-d77f2080-ce15-11eb-9c65-fc7306805bf8.png">

<img width="706" alt="Снимок экрана 2021-06-15 в 20 04 38" src="https://user-images.githubusercontent.com/56931989/122095325-e665d300-ce15-11eb-8a4b-344975ed9c67.png">


Thanks!

**Comment by Juli-Bk** [comment]
**I fixed it this way for my project:**

<img width="1009" alt="Снимок экрана 2021-06-15 в 22 07 10" src="https://user-images.githubusercontent.com/56931989/122109514-22089900-ce26-11eb-9523-8a75e662fd84.png">

<img width="755" alt="Снимок экрана 2021-06-15 в 22 09 02" src="https://user-images.githubusercontent.com/56931989/122109758-672ccb00-ce26-11eb-8147-b5f2889e0f2f.png">

<img width="939" alt="Снимок экрана 2021-06-15 в 22 08 35" src="https://user-images.githubusercontent.com/56931989/122109790-6eec6f80-ce26-11eb-994a-77df47d86dec.png">

**Comment by basrodriguezr** [comment]
in your server.js you may add a middleware permiting the fileUpload use in your application
![image](https://user-images.githubusercontent.com/54077863/179645288-1c6898c1-c58e-407f-bb16-fd882e224b6b.png)

**Comment by Drunken72** [comment]
> **Reply : I fixed it this way for my project:**
> 
> <img alt="Снимок экрана 2021-06-15 в 22 07 10" width="1009" src="https://user-images.githubusercontent.com/56931989/122109514-22089900-ce26-11eb-9523-8a75e662fd84.png">
> 
> 
> 
> <img alt="Снимок экрана 2021-06-15 в 22 08 35" width="939" src="https://user-images.githubusercontent.com/56931989/122109790-6eec6f80-ce26-11eb-994a-77df47d86dec.png">

Thank's for saving me T_T . I also tried everything you've tried. Many many thanks
