### ISSUE TITLE
Application crashes/ quits itself running collections via Runner

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6602]
**Describe the bug**
Postman quits itself when the collections are run through the collection runner. The requests within the collections are lesser than 10.

**To Reproduce**
1. Run particular collection via collection runner ( requests < 10 )
2. Number of iteration is 5
3. After running for some time, the app crashes on its own

**Expected behavior**
Be able to run collections from collection runner for any number of requests/ iterations

**App information:**
 - App Type - Native App
 - Postman Version - v7.1.1
 - OS - mac 10.14.4

**Additional context**
Similar issue for more than 1k requests: https://github.com/postmanlabs/postman-app-support/issues/6525

**Comment by kaushikpatel1396** [comment]
**Describe the bug**
Postman quits itself when executing any API for a specific collection only. There are 123 requests in that particular collection.

**To Reproduce**
Steps to reproduce the behavior:
Pressing "Send" after selecting any API from the collection. the postman quits. 


**App information:**

App Type - Native App
Postman Version - v7.1.1
OS - mac 10.14.3

**Additional context:**
Works okay with order requests from other collection. 
Also, attached network/console logs from current view and shared view.
![Screenshot 2019-05-28 at 12 31 30 PM](https://user-images.githubusercontent.com/16894064/58465479-6d738000-8155-11e9-9ed6-e6d700bfe0a8.png)
![Screenshot 2019-05-28 at 12 53 22 PM](https://user-images.githubusercontent.com/16894064/58465491-72383400-8155-11e9-8996-3b4e47d5a8cb.png)
![Screenshot 2019-05-28 at 12 53 34 PM](https://user-images.githubusercontent.com/16894064/58465492-72d0ca80-8155-11e9-8660-f586b4e90b13.png)
![Screenshot 2019-05-28 at 12 53 50 PM](https://user-images.githubusercontent.com/16894064/58465495-73696100-8155-11e9-961c-f370e0cdc9a3.png)

**Comment by saswatds** [comment]
Hello @pareekkhushboo77 can you confirm that your issue is with runner and not the request builder? 
There is a possibility that your issue could be related to https://github.com/postmanlabs/postman-app-support/issues/6533

**Comment by kaushikpatel1396** [comment]
Hello @saswatds  ,
Issue is not with runner, just simply POST requests calls.

**Comment by saswatds** [comment]
Hi @Kurmavathar, we are aggressively tracking such performance issue across all components of postman. There is a lot of possible reason why this could be happening. 

It would be great if you could help us investigate this issue. Here are a few things that could help us.
* The logs from postman console (not devtools console) with all sensitive info redacted
* If there is any specific request on with the runner is crashing?
* What are is the possible response size that you might be receiving? (aggregate)
* What are kind of auth feature being used?
* Does any of your api's involve uploading files, if yes what is the approximate size? 
* What kind of hardward specification you are using, specifically the RAM? 

We would be able to replicate this issue faster and come to a better RCA. 

Thanks

**Comment by kaushikpatel1396** [comment]
Hi @saswatds , in order to get you required info to replicate the issue asap , can you please guide how to get logs from postman console.
What are is the possible response size that you might be receiving? (aggregate)
> well i found something, when i executed an API with merely any response hosted on different server, it executed properly, 
but the issue belonging API server is hosted in Russia. Also i tested on another machine, the API worked well in Postman, just the Postman crashes in my machine. Thats also weird as i have been using these API since 1+ year and this issue began 1 week back.

What are kind of auth feature being used?
> nothing

Does any of your api's involve uploading files, if yes what is the approximate size?
> No

What kind of hardware specification you are using, specifically the RAM?
> 16 GB

**Comment by saswatds** [comment]
Hi @pareekkhushboo77 this particular issue is for the crashing of the runner and not request builder. Leveraging this issue to discuss the request builder is leading to a bit of confusion. 

You can find the postman console by going to `View -> Show Postman Console`

There is another issue that we are tracing in the request builder where entering an invalid url in the editor is crashing the app. If your issue is similar to it, you can add a thumbs up to https://github.com/postmanlabs/postman-app-support/issues/6533 and continue the conversation there.

Thanks

**Comment by kaushikpatel1396** [comment]
Hi @saswatds , i am sure that the URL is correct, as it works in any other machine's Postman but mine, Also i have been working on it since more than 1 year, so i suppose that not the issue.
Also, Postman Console doesn't show anything , please view attached screenshot.
![Screenshot 2019-05-29 at 3 15 58 PM](https://user-images.githubusercontent.com/16894064/58547279-b5ada380-8224-11e9-9292-0ba37913ac3f.png)

Thanks

**Comment by kaushikpatel1396** [comment]
Hi ,

The issue is fixed, not sure how - but i guess its related to number of requests limits, as the new month began i tried to make the API calls again and they worked. 

Also, please also check if your using environments, remove them and just try with direct urls.

Thanks for regular support by the team :)

**Comment by Raj-postman** [comment]
@pareekkhushboo77 Sure, we will continue tracking this further on https://github.com/postmanlabs/postman-app-support/issues/6525
