### ISSUE TITLE
Web dashboard  inaccessible

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6619]
**Describe the bug**
Getting a blank page while trying to access web dashboard

**To Reproduce**
1. Go to https://app.getpostman.com/
2. Click on "Sign in" 
3. Navigates to the blank page

**Expected behavior**
Should show next page- Workspaces

**App information (please complete the following information):**
 - App Type [N/A]
 - Postman Version [N/A]
 - OS: [macOS ]

![image002](https://user-images.githubusercontent.com/41741228/58608672-57370280-82c2-11e9-9074-2db282595155.png)

**Comment by ankit-m** [comment]
Dashboard uses websocket to establish a connection to our servers. In this case, the websocket connection failed (both in native app and web). This can happen due to various network and corporate firewall issues.

Try using a home internet connection and see if the issue is resolved. If the issue persists, please write to us at help@getpostman.com for further assistance.

**Comment by ash007-postman** [comment]
@ankit-m Thank you!

**Comment by ash007-postman** [comment]
@ankit-m 
*User* - I tried connecting in my home network, the collections weren’t getting synced for a longer time and I was not able to export them. Kindly assist.

**Comment by ash007-postman** [comment]
@preethammavin Another user facing a similar issue, he can't access web dashboard, getting a spinning circle while opening the web-dashboard and the page never loads.

**Comment by preethammavin** [comment]
@ash007-postman we have fixed the underlying issue, can you confirm the issue still persists?
