### ISSUE TITLE
Feature Request: Encrypt local variables

### ISSUE THREAD

**Issue by CReich02** [a85/POSTMan-Chrome-Extension#6638]
### Is your feature request related to a problem? Please describe.
Local variable values are not encrypted like they are when they are when they get synced up to the Postman servers and Postman storage. Session variables and local variables. This is a pretty big security problem with the suggestions in the documentation that variables should be used for passwords and api keys.

### Describe the solution you'd like
Encrypt all variable values, even session variables and any other variable values stored on the local machine. These should only be de-crypted when they are used.

### Related posts
Variables stored at rest - https://community.getpostman.com/t/variables-stored-at-rest/5645
Feature Request: Secure variable option - https://github.com/postmanlabs/postman-app-support/issues/6639

### Similar requests that are closed
Feature Request: Hidden environment variables for passwords - https://github.com/postmanlabs/postman-app-support/issues/824
Feature Request: Secure environment variables - https://github.com/postmanlabs/postman-app-support/issues/4777

**Comment by shamasis** [comment]
Umm... aren’t the variables on your own computer? The only way this can be a problem if someone is on a shared computer or someone’s computer is compromised. For shared computer scenario, most OS provide protection that one can setup. 

Even if it’s encrypted, to decrypt one would either need to store the key in the same computer (defeats purpose) or ask to enter the key manually every time. 

I’m afraid, this is not something that we can do. 😞

For the remote encryption that we do for variables, that ensures nobody can read that data except you and that is important because you’re storing them on our servers.

**Comment by CReich02** [comment]
@shamasis If that is the issue then secure variables should either be stored on the users account and pulled down/decrypt as they are used. Or the decryption key should be stored in the users account and required them to be logged in to retrieve them.
There should be some way of securing Session variables, even if they are not stored in a plain text file secure passwords and/or api keys should not be stored on a local machine unless they are encrypted.

If password vaults can store the data encrypted locally, any other app that suggests using it to store passwords, api keys, and secrets should also be able to.

**Comment by neo00** [comment]
@shamasis , it looks like everyone keeps forgetting that postman collections often needs to be shared with other people. One common approach is to use version control. But do you want the secrets to be persisted in plaintext into source version control? People do stupid mistakes all the time, such as pushing private repos to public github repo, or sharing collections by email with the wrong audience, or placing files on non-secure file shares. If you work an enterprise setting you are likely to see requirements such as forbidding plaintext secrets from being stored in source control to minimize these risks.

I think giving people the ability to secure secret variables is critical for a lot of enterprises that have strict security requirements. 
Encrypting the secrets with a key derived from a user-provided password (KDF) is one simple way to do it. This way the encryption key doesn't have be stored. Another approach is to use OS-provided keystores (such as using windows DPAPI) to encrypt with a key local to the machine and/or the current user. 
Yes at the end of the day, if your local machine is compromised then there's no much you can do to protect those secrets because at some point the secrets have to be decrypted to be used. However this doesn't negate the need to secure the file in case the file is shared with potentially the wrong audience as I described above.

**Comment by DannyDainton** [comment]
With V11 of Postman, we have introduced the Postman Vault (https://learning.postman.com/docs/sending-requests/postman-vault/postman-vault-secrets/), which allows you to store your sensitive data in an encrypted local vault that is not synced with the Postman Cloud. Also, we have added multiple security features to help prevent accidental exposure of your API credentials.
