### ISSUE TITLE
Add enhanced merge tools to make merging similar to git pull requests

### ISSUE THREAD

**Issue by yossarian123** [a85/POSTMan-Chrome-Extension#6659]
With the ability to fork/comment/merge, Postman has some of the basic functionality of a git PR.  However, the following capabilities would really help:
- mark a merge as "needs work" - which will prevent the merge from taking place
- show a list of comments along with the ability to toggle those comments as resolved
- if there are any unresolved comments then postman would prevent the fork from being merged (unless there was an override by an admin)

Our team is currently storing collections in git - when changes are made we modify the .json file and track a pull request directly in git.  We'd like to move away from this and only use collections in team workspaces.  The above enhancements would make the merge & collaborative features extremely useful for us.

**Comment by preethammavin** [comment]
@yossarian123 thanks for the feedback, we are looking at bettering the experience on Fork and Merge , no ETA as of yet but be tuned :)

**Comment by preethammavin** [comment]
@yossarian123 we are working on implementing the merge request flow, there are certain things which we will release in stages. 

Taking your feedback, wanted to validate a few things 
Would the ability to request review from another team member solve the issue around ensuring for the merge request.  We would also be introducing the approve stage for request which could help you govern, no merge request would be merged if there is not at-least 1 approval.

**Comment by arlemi** [comment]
From a [user on Discourse](https://community.getpostman.com/t/how-do-collection-editors-get-notified-when-a-collection-viewers-create-a-merge-request/10305):

> When a Collection Viewer wants to update a collection, they can fork it and make their changes. Then they can create attempt to merge the changes, but they won’t be able to because their Collection Viewer role doesn’t allow them to. Which is perfect! However, how do Collection Editors get notified that a merge request has been created so that they can review the merge request and appropriately approve/deny it?

**Comment by hackley2** [comment]
Thank you @arlemi for directing me here from Discourse! I'll elaborate on @yossarian123 's questions and what functionality we think would lead to a great "collection management and collaboration" workflow.

1. @preethammavin The ability to request review would be great, but would really only be useful after merge requests already automatically notified Collection Editors that there was a merge request that needed attention. Because otherwise, there could be many situations where a Collection Viewer wants to have someone review a merge request, but doesn't know who the appropriate people are to request a review from (i.e. people might be on vacation, perhaps opaque ownership, etc).
2. It would be amazing if an additional permission setting was introduced: "Collection Merge Request Approver". In this way, multiple team members could have the ability to approve a collection's merge request, but they wouldn't be able to accidentally edit the collection itself. (I can't tell you how many times, as a collection editor, I've accidentally inadvertently slightly messed up a collection's request by saving an open request. I'd love the ability to force myself to fork a collection before being able to edit it... or at least a warning if i'm editing a shared collection... or something)

**Comment by arlemi** [comment]
Pull Requests are available as of 7.19.1! Update, give it a try and let us know what you think. :)  

![Screenshot 2020-02-25 at 10 58 09](https://user-images.githubusercontent.com/5029719/75241438-ff301c80-57bd-11ea-8f0f-0409a4d0b720.png)
