### ISSUE TITLE
Unable to sync my team collection

### ISSUE THREAD

**Issue by HugoBCuri** [a85/POSTMan-Chrome-Extension#6663]
**Describe the bug**
I was working in a collection and my colegue update the postman team version to v7.
Now I can't update to the latest version, because the postman installation is not working correctly on ubuntu 18.04, the postman is installed but the version is 6.7.1.  

**To Reproduce**
1.  Download version Postman-linux-x64-7.1.1 .
2. Try to install on ubuntu 18.04, following [postman instructions](https://learning.getpostman.com/docs/postman/launching_postman/installation_and_updates/).

**App information:**
- Postman for Linux
- Version 6.7.1
- linux 4.18.0-20-generic / x64

**Comment by jessica-pixvana** [comment]
Same here

**Comment by harryi3t** [comment]
@HugoBCuri @jessica-pixvana 
Could you provide us some more information about the issue you are facing?

> the postman installation is not working correctly on ubuntu 18.04

1. Is the App not opening after downloading from our website? Can you try opening it from the terminal add see if there are any errors? Also, if this is the case, please share the logs (View -> Developer -> View logs in File Manager) at `help@getpostman.com` with the title `Logs for GitHub #6663`

2. Also, we have seen issues where people tried to unzip the contents over an old installation. **Please do not do this, if you have an old installation please delete that first.** More information here: https://github.com/postmanlabs/postman-app-support/issues/5039#issuecomment-420258338

**Comment by HugoBCuri** [comment]
### It worked
1. I have to remove manually
```
sudo snap remove postman
sudo rm -rf var/run/snapd/lock/postman.lock 
```
2. Install libgconf-2-4
```
sudo apt-get install libgconf-2-4
```
3. Download [latest version](https://www.getpostman.com/downloads/)
4. Unzip file
```
tar -xvzf Postman-<VERSION>.gz
```
5. Move to directory that I want to install it 
6. Create the file ~/.local/share/applications/Postman.desktop
```
vim ~/.local/share/applications/Postman.desktop
```
copy and paste, change **YOUR_INSTALL_DIR**
```
[Desktop Entry]
Encoding=UTF-8
Name=Postman
Exec=*YOUR_INSTALL_DIR*/Postman/app/Postman %U
Icon=*YOUR_INSTALL_DIR*/Postman/app/resources/app/assets/icon.png
Terminal=false
Type=Application
Categories=Development;
```
 7. Open the app

**Comment by preethammavin** [comment]
Thanks letting us know, will be closing the issue for now

**Comment by harryi3t** [comment]
@HugoBCuri Thanks for sharing the steps to fix the issue.
Here's a short explanation about what might have happened.

You had installed Postman from snap where the latest version on the `stable` channel is 6.7.x
Installing from snap also creates the desktop file automatically for you. So when you search for Postman, the icon in the search comes because of this desktop file.
Then, you downloaded the latest Postman from our website (7.1.x). Since it's just a tar file, it does not automatically create the desktop file and hence it won't appear in any application search.
I am guessing after extracting latest Postman, you tried to search for it and opened it from the search result. Since the installation from snap was still existing, that old app would have been opening.

When you removed the snap version of the app and manually created the desktop file, after that in the search the latest app started appearing, thereby fixing the issue.
