### ISSUE TITLE
Dynamic query in graphql without graphql schema

### ISSUE THREAD

**Issue by LakhanMaq** [a85/POSTMan-Chrome-Extension#6667]
![image](https://user-images.githubusercontent.com/45222693/59015868-9aaee500-885d-11e9-8c43-9492913a1708.png)

this is what i am trying to run but   getting 400 bad request

I am not using content-type: application/graphql
i have pass this in body as raw data with application/JSON

Please provide me solution
if more clarification required please let me know

@a85

**Comment by numaanashraf** [comment]
@LakhanMaq Postman's GraphQL support is available for early access on our Canary channel. You can edit and send query and graphql variables directly from the UI. Please follow this thread and refer this comment to download the Canary builds - https://github.com/postmanlabs/postman-app-support/issues/1669#issuecomment-494384520.

Regarding the 400 bad request, I'm afraid this is specific to your GraphQL API and query and we wouldn't be able to support this issue here. We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
