### ISSUE TITLE
App not starting on Ubuntu

### ISSUE THREAD

**Issue by AnvarNazar** [a85/POSTMan-Chrome-Extension#6684]
### Output
```
1560076069011 main error {"name":"Error","message":"PluginHost~hostErrorOrExit: Exited with code null with signal SIGINT","stack":"Error: PluginHost~hostErrorOrExit: Exited with code null with signal SIGINT\n    at ChildProcess.host.on (/home/anvar/Programs/Postman/app/resources/app/node_modules/@postman/app-plugins-host/index.js:63:25)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}
1560076069013 main error {"name":"Error","message":"PluginHost~bootHost: Disabling boot since it has exceeded the maximum allowed boot count 2","stack":"Error: PluginHost~bootHost: Disabling boot since it has exceeded the maximum allowed boot count 2\n    at PluginHost.bootHost (/home/anvar/Programs/Postman/app/resources/app/node_modules/@postman/app-plugins-host/index.js:26:9)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"}
```

**Comment by numaanashraf** [comment]
@AnvarNazar Please fill the following template:



**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
Add any other context about the problem here.

**Comment by AnvarNazar** [comment]
it started to work again after a restart.
