### ISSUE TITLE
Feature Request: Auto-generate GraphQL schema

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6713]
**Is your feature request related to a problem? Please describe.**
When sending a request to a GraphQL endpoint, it would be useful to have Postman build/import/generate the schema automatically.

**Describe alternatives you've considered**
Explicit file imports or manual creation within the app which already exists

**Additional context**
[Filed by Postman]

**Comment by simplynutty** [comment]
I'm interested in this as well and was confused when my schema didn't show up after creating an API as shown here https://learning.getpostman.com/docs/postman/sending_api_requests/graphql/#importing-graphql-schemas.  The ability to browse schema docs is the biggest reason I'm still using Graphiql instead of Postman.

**Comment by JoeDevGeeeee** [comment]
@preethammavin Do you have a time line for releasing this feature.
For reference, Insomnia already has this: https://insomnia.rest/graphql/

**Comment by preethammavin** [comment]
@JoeDevGeeeee this is something that is on our mid term roadmap, will get back with the exact dates once we get the details ironed out :)

**Comment by ulgens** [comment]
@preethammavin What about that details? :slightly_smiling_face:

**Comment by loganaaaflag** [comment]
+1 for this, would be helpful for us too 😄

**Comment by TheThinker01** [comment]
+1 This would be really helpful
[https://altair-gql.sirmuel.design/](https://altair-gql.sirmuel.design/) has a similar feature available, would love to see it on postman too.

**Comment by SterlingChin** [comment]
Postman's new GraphQL client is currently in [Open Beta](https://blog.postman.com/announcing-postmans-new-graphql-client/). As part of the new client, we have automatic introspection enabled, so now there are 3 ways to get your schema: 1. Introspection, 2. API Creation in the App, 3. Import from your local machine. 

## Introspection
![graphql-schema-explorer](https://user-images.githubusercontent.com/8900638/221677295-69586456-754f-410f-b6a6-e53d4648049d.gif)

**Comment by timhall** [comment]
Closing as automatic introspection is now supported in the HTTP and GraphQL clients, thanks for reporting!

**Comment by DSchau** [comment]
Like @timhall said! We support this as part of the Postman GraphQL protocol feature set. 

As a user, if your GraphQL service supports schema introspection we'll automatically use that, otherwise you can use a custom GraphQL schema file or Postman API. 

<img width="954" alt="Screenshot 2023-12-04 at 11 05 56" src="https://github.com/postmanlabs/postman-app-support/assets/3924690/d6d34266-518c-4b69-ab86-fdcfab3d47be">

You can read up more on Postman's GraphQL support here ➡️ https://www.postman.com/product/graphql-client/

As always, if you have feature requests, bug reports, or want to share any feedback, please feel free to use this repository and we'll do our best to triage them and keep improving the GraphQL experience in Postman 🚀
