### ISSUE TITLE
Could not export the data. Please check the DevTools.

### ISSUE THREAD

**Issue by TangQingFengPHP** [a85/POSTMan-Chrome-Extension#6721]

**Comment by preethammavin** [comment]
Description does not provide enough information to look into the issue. Closing the issue for now, feel free to reopen it with the appropriate description so that we can look into the issue

**Comment by qhreul** [comment]
When trying to export a complete collection with Postman 7.2.0 on Windows 10, I get an error with regards to the inability to export the data (see screenshot).
![unnamed](https://user-images.githubusercontent.com/20356112/59622315-d7e56380-90f6-11e9-9ff8-ec601eb7955b.png)

**Comment by sffej** [comment]
I'm getting the same error message: 
"Could not export the data. Please check the DevTools."

Here are my settings:
Version 7.2.0
win32 10.0.17134 / x64

I've rebooted and current with system updates.

Since this has been closed created new issue: https://github.com/postmanlabs/postman-app-support/issues/6730
