### ISSUE TITLE
I would like the option to mark a collection that I've created as read-only

### ISSUE THREAD

**Issue by stianlagstad** [a85/POSTMan-Chrome-Extension#6735]
**Is your feature request related to a problem? Please describe.**
I have a collection of requests that I use as a reference, and that I should not edit, but every now and then I edit wrong requests by mistake.

**Describe the solution you'd like**
I would like the ability to mark a collection that I've created myself as read-only.

**Describe alternatives you've considered**
I could for example move my read-only collection to another workspace, and I could be more careful about which requests I modify. But I think the ability to mark a collection as read-only would be much much better.

**Additional context**
I've read other issues, such as the below:
- https://github.com/postmanlabs/postman-app-support/issues/6582 (not the same request)
- https://github.com/postmanlabs/postman-app-support/issues/3422 (I'm not currently using postman pro and I'm not in a team. I just have my own collections, and I want to mark one of them as read-only)
- https://github.com/postmanlabs/postman-app-support/issues/1381 (I don't think this is relevant as I'm not in a team)
- https://github.com/postmanlabs/postman-app-support/issues/1328 (I don't think this is relevant as I'm not in a team)

**Comment by preethammavin** [comment]
@stianlagstad I would suggest 2 ways to do it with the current set of features, as I do not think we would be picking up a similar feature in the short to mid term
1) This would be to organise it according to the workspace so that you know which collection/request to edit in the context of a workspace
2) If you would want to enforce a read only collection create a team (which is free) manage permission between you and the contributor. 

1 of the major reasons why we do not think we will be picking it up soon is because it does break the RBAC notion and complicates the product in terms of understanding the access control behaviour

**Comment by stianlagstad** [comment]
Thank you for the response @preethammavin. For your second suggestion: Do I need multiple postman accounts in that team to do so?

**Comment by preethammavin** [comment]
Yes, you would need multiple accounts for this.
