### ISSUE TITLE
I am using MAC OS Mojave, Cant expand PHP and other Dropdowns while generating code snippet

### ISSUE THREAD

**Issue by pdctpa** [a85/POSTMan-Chrome-Extension#6781]
Unable to generate a code snippet for PHP curl post method and other which has drop downs, it simply won't expand the dropdowns of PHP, NodeJS, and Java, etc.,

<img width="176" alt="image" src="https://user-images.githubusercontent.com/12509947/60076969-7f414680-9746-11e9-8459-a1f871066355.png">

**Comment by abhijitkane** [comment]
@pdctpa Please include all information requested in the issue template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
Add any other context about the problem here.

Without this, it's impossible to debug the problem you're facing.

Also, in Postman 7.2+, you can enable the 'Experimental codegen mode' in Postman's global settings. This will let you use an updated Codegen feature with new languages (JS-Fetch and Powershell), and various bugfixes.

**Comment by preethammavin** [comment]
Closing the issue has with the current information , we are not able to deduce the issue. Please feel free to reopen the issue with the required information so that we can get it resolved.
