### ISSUE TITLE
Why I cannot use environment's variables from environment by BODY? 

### ISSUE THREAD

**Issue by tester1234562020** [a85/POSTMan-Chrome-Extension#6789]
For example, I have created a json like {a:data.a ,b:data.b} to get data from csv file, and I save it by environment when I use runner. But its value becames [object Object]! Finally,I use the enviroment like {{this}} to postman in body,BUT it is error~！

**Comment by preethammavin** [comment]
@tester20183450 can you provide the information as required by the template, with steps to reproduce this so that we can get this sorted.

**Comment by codenirvana** [comment]
@tester20183450 The variables lacks support for types that's why the object value is converted/represented as `[object Object]`. However, you can store the stringified object and parse the variable content whenever needed.

Example:
```js
pm.environment.set("this", JSON.stringify({a: data.a, b: data.b}));
```

I hope this solves your problem. Also, we recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with issues like these.
