### ISSUE TITLE
When i use csv file for body(raw, application/json),after using runner ,the value is not string!

### ISSUE THREAD

**Issue by tester1234562020** [a85/POSTMan-Chrome-Extension#6793]
![image](https://user-images.githubusercontent.com/44419851/60239244-91a2b800-98df-11e9-8ad8-989d8594a34f.png)
![image](https://user-images.githubusercontent.com/44419851/60239873-b13ae000-98e1-11e9-828a-a168b8bd2fc7.png)

**Comment by vikiCoder** [comment]
Hi @tester20183450 

I did not understand your issue, can you please elaborate more. If possible, please provide exact steps to reproduce your issue with a sample collection and a CSV file without any sensitive data. Also, mention the Postman App version you are using.

**Comment by vikiCoder** [comment]
Looking at the screenshot you sent, seems like your problem is the string `YQTAPP` for `CUST_TYPE` is not in quotes. Using the variable in body only replaces its value without adding anything extra. So if you want this to be a quoted string you can use it as shown below:

```
{
    "CUST_TYPE": "{{CUST_TYPE}}"
}
```

which will result in the body as shown below:
```
{
    "CUST_TYPE": "YQTAPP"
}
```
