### ISSUE TITLE
Feature request: Postman app doesn't have UK timezone for the monitors

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6847]
**Is your feature request related to a problem? Please describe.**
We are running our monitors in UK timezone, however that option is not available in the Postman App during the creating, meaning they have to be created on the web interface or edited afterwards.

**Describe the solution you'd like**
Add all available timezones from the web interface into the Postman app.

**Describe alternatives you've considered**
Editing monitor after creation through web interface to adjust the timezone.

**Comment by preethammavin** [comment]
@VicKetchup  this is something we are working on , will let you know once its out on production .

**Comment by ArjunSingh-PM** [comment]
@VicKetchup Could you please confirm that you are being able to set the UK timezone from the app now. Thanks!

**Comment by VicKetchup** [comment]
@ArjunSingh-PM Can confirm, all good :) 
![image](https://user-images.githubusercontent.com/43671684/70443276-8532a600-1aa0-11ea-9c99-972376cc02c4.png)

**Comment by ArjunSingh-PM** [comment]
Thanks a lot @VicKetchup!

**Comment by ceefour** [comment]
This thread may confusing for some people. Since at first it talks about **time zones** but then it switches to **regions**.

My interpretation:

this doesn't seem to be related at all to time zone. But instead it is about the datacenter region that the monitoring request will be sent from. Reference: https://learning.postman.com/docs/monitoring-your-api/faqs-monitors/#how-many-regions-can-my-monitor-run-in

Regardless of the region, the timezone used to select the time, depends only in the user's browser/computer that is being used to edit the monitor. Reference: https://learning.postman.com/docs/monitoring-your-api/faqs-monitors/#what-time-zone-is-my-monitor-set-to
