### ISSUE TITLE
Random conflict state for some opened tabs

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6848]
**Describe the bug**
Some open tabs go into Conflict state, this happens randomly and there is no one clear way to reproduce the issue. I have confirmed with other team members that the issue also happens with them. Weirdly it is mostly happening with the requests that have not been modified for a very long time (over a year).

**To Reproduce**
This mostly can be seen after Postman App has been opened for a while, then it is quit and upon launch some of the tabs will become in Conflict. However also may happen when switching between workspaces or after a crash.

**Expected behavior**
The tabs should not go to Conflict state if there has been no updates to the request from any side.

**Screenshots**
Before app is quit (Made some calls, switched to another workspace and back):
![image](https://user-images.githubusercontent.com/43671684/60590823-ad0d3780-9da5-11e9-9c4f-90842c227a11.png)
After launch:
![image](https://user-images.githubusercontent.com/43671684/60592317-0d51a880-9da9-11e9-958e-07fd79fc8a63.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.2.2 - has been an issue in earlier versions as well
 - OS: macOS Mojave 10.14.5

**Comment by sujayvenaik** [comment]
Duplicate of #6383

**Comment by VicKetchup** [comment]
@sujayvenaik this is different behaviour, nothing is ever edited on the requests I've provided as an example. when I made the calls, the requests were still in their original state, the other issue market as duplicate requires an edit to happen.

**Comment by cj-scott-prive** [comment]
As noted by @VicKetchup, this is not a Duplicate of [#6383](https://github.com/postmanlabs/postman-app-support/issues/6383)

`6383` requires an Edit in order to happen. The issue Vic describes does NOT require an edit. Moving this issue onto 6383 has only confused things because now that ticket has people with both types of problems. 

There's clearly some irregularity with the UI toolkit used to build Postman. Issues here just get closed all the time without validation from those reporting the problem. This isn't confidence-inspiring.
