### ISSUE TITLE
No response received when Request is sent with AWS Signature

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6868]
**Describe the bug**
When sending the GraphQL query without AWS authorization It succeeds. But the same request cannot pass with AWS authentication.

**To Reproduce**
1. Create request with GraphQL query
2. Set AWS signature to authorize the request
3. Click on "Send" 
4. No response received 
"Loading...." with "Cancel Request" button will be displayed at the response view pane. 

**Expected behavior**
Be able to receive the response for the request.

**Screenshots**
![AWSSignature](https://user-images.githubusercontent.com/47771757/60788429-55dade80-a17a-11e9-95f2-fbfa18a71b13.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.2.2

**Comment by shamasis** [comment]
Hello there. It looks like something with auth signing is erroring out. Cannot be certain. It will be great if you could send us errors that you see, *right at the moment around sending this request*, in Postman Console (and if nothing shows up there, then the developer console.

**Comment by vikiCoder** [comment]
Hi

You don't need to send the logs anymore. We have found the bug, it is because of the newly added body type - `GraphQL` which is not accounted while calculating AWS signature right now. So GraphQL requests with AWS auth are freezing because of that.

We will fix the issue ASAP (possibly in next release) and update this thread.

**Comment by codenirvana** [comment]
Fixed in the latest version of the Postman app v7.6.0.
