### ISSUE TITLE
Request parameter "access_token" not being sent, when Authorization type is OAuth2

### ISSUE THREAD

**Issue by andrei-chirinciuc** [a85/POSTMan-Chrome-Extension#6870]
**Describe the bug**
Request parameter with name "access_token" not being sent to the endpoint

**To Reproduce**
1. Under Authorization tab, select type: OAuth2
2. Add authorization data to request headers
3. Obtain a valid access token using the Get New Access Token button.
4. Send a request to a rest service using request parameter name access_token for e.g.
localhost:8080/sdk/v1/apis?access_token=69e34bcb-7568-4686-bd89-6c0261b00444

**Expected behavior**
the request parameter "access_token" should be sent to the endpoint

**Screenshots**
![image](https://user-images.githubusercontent.com/17107939/60803441-e0740b80-a183-11e9-81a7-c2d33ce40e85.png)

**Workaround**
- Solution one: Change the parameter name from "access_token" to "code" or anything else. 
- Solution two: Under Authorization tab, select type: None and set the authorization header manually
![image](https://user-images.githubusercontent.com/17107939/60803738-8c1d5b80-a184-11e9-89c5-52369d93dfd5.png)

**App information:**
 - App Type [Java Spring Web App]
 - Postman Version [7.3.1]
 - OS: [macOS High Sierra 10.14.5]

**Comment by vikiCoder** [comment]
Hi @andrei-chirinciuc 

You are right, we remove the `access_token` parameter from URL while sending the request with OAuth2 (even though `Add authorization data to request headers` is selected). Because many of the OAuth2 protected resource servers use Bearer token (obtained by OAuth2 flow) while accessing resources. And according to [RFC-6750 section-2.3](https://tools.ietf.org/html/rfc6750#section-2.3), Bearer token can be passed as URL query parameter with `acccess_token` as the name of the parameter.

So even if `Add authorization data to request headers` is selected, sending different tokens in both (`Authorization` header and `access_token` query parameter) at the same time can cause ambiguity and unexpected results for some servers.

So for now, I would suggest you to change the parameter name from `access_token` to something else as you already mentioned.

**Comment by giridharvc7** [comment]
Are you still facing this problem? As @vikiCoder mentioned, having `access_token` as a custom parameter in a request that used OAuth, which already has a header parameter of `access_token` will only cause ambiguity. I'm closing this issue as this is not something we'll be picking up for now. Let us know what you think
