### ISSUE TITLE
Request never stops executing causing App Crash and Monitor hang

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6890]
**Describe the bug**
Was testing a collection created for a different bug and now experiencing crashes on Postman App as well as hang in the monitor. I tried to call the request on which the crash happens on it's own and saw some strange behaviour. While response was given, the "Time" for it kept increasing all the way to 50.84 seconds before Postman crashed.
Please see the attached collection and the second request is the one causing the issue.

**To Reproduce**
Either:
- Run collection runner (will crash the app on second request)
- Run the monitor on the collection (the monitor will hang)
- Run the second request in the collection and the response will be given, however response time will keep rising until a crash.

**Expected behavior**
Once the response is obtained, "Time" should not increase, the connection should be broken to prevent the crash. If Postman notices this error, display some sort of warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/43671684/60959441-dcc1bf80-a310-11e9-9499-fc8e75b59616.png)

**App information (please complete the following information):**
 - App Type Native App & Monitors
 - Postman Version  7.3.2
 - OS: macOS Mojave 10.14.5 

**Additional context**
[Wrong URL in Console Log (Monitors).postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/3376872/Wrong.URL.in.Console.Log.Monitors.postman_collection.json.zip)

**Comment by coditva** [comment]
Hi @VicKetchup, I was able to reproduce the issue (thanks for providing the sample collection!). Let me try and find the cause and I'll get right back to you.

**Comment by coditva** [comment]
@VicKetchup So, turns out the URL that you're requesting (http://petstore.swagger.io/v2/pet/findByStatus?status=available,available) keeps on sending data (probably a loop gone wrong 🤷‍♂).

This is why the Time keeps on increasing because the request never ends! You can even see this behaviour when you access the endpoint with a web browser.

Postman keeps on receiving the data and hangs/crashes because incoming data spikes the memory usage. This is an issue that we're tracking here: #4751

**Comment by VicKetchup** [comment]
@coditva This is not an API we have any contact with, so wouldn't be able to tell what is going on, but the data isn't supposed to be large, so maybe there are some checks that could be put in place to see if the data that is being received is actually changing anything, cause the data size for the response was not changing. 
And failing that at least display an error rather than crash :)

**Comment by saswatds** [comment]
Hi @VicKetchup, you are absolutely right, we had identified that such a situation may arise because of which in the latest canary we added a setting to define a maximum response size. 
<img width="718" alt="Screenshot 2019-07-11 at 9 50 51 PM" src="https://user-images.githubusercontent.com/8796447/61067779-06b8d600-a426-11e9-92c3-e3eda2f3322a.png">
We set the value to be 50mb by default. There is a limit to response size that we can show in the UI and it varies from system to system. You can tweak this value to a higher number if your system can handle it (We are constantly working on reducing our memory footprint).

We are also working on a new streaming model for the response so that data shows up in the UI as an when it arrives, but until then the above options is the rescue. We will soon add this option to monitors as well.

Try it out in our latest canary build https://www.getpostman.com/downloads/canary

Thanks

**Comment by DannyDainton** [comment]
I'm going to close this out as it appears that a solution to set the max response size was added to an earlier version.
