### ISSUE TITLE
[Feature Request]: "Select all" checkbox on "Params" and "Headers" tabs

### ISSUE THREAD

**Issue by AstroARTY** [a85/POSTMan-Chrome-Extension#6928]
**Description:**
URL may have a lot of query parameters and headers, but I do not need to use them all for the one particular request. It would be great to have "Select all" checkbox on "Params" and "Headers" tabs, so that I can easily enable/disable them all by 1 click.

<img width="102" alt="parameters" src="https://user-images.githubusercontent.com/26251216/61277323-a2e23480-a7ba-11e9-90c3-e6ceca182c6f.png">

**Postman type/version:**
 - App Type: Postman for Windows
 - Postman Version 7.3.2
 - OS: win32 10.0.17763 / x64

**Comment by giridharvc7** [comment]
Hey @AstroARTY , just trying to understand your use case better here, can you share some scenarios you face where you have the need to deselect all parameters?

**Comment by liguoqinjim** [comment]
Also want this feature!
It's very useful when test a query API which has a lot of params.

**Comment by cirelli94** [comment]
@giridharvc7 I usually import my API from an OpenAPI specification file.
While I import them I have all checkboxes enabled, but I usually don't need all query params enabled together because they filter data, I often don't need any of them, but the default value is enabled!

So I'd like to have a checkbox in the header of the query params as draw by @AstroARTY  with this possible values:
![image](https://user-images.githubusercontent.com/1636493/140034373-4c1b0cb4-87a3-4fc4-8560-3877a5f39a09.png)
When I press it on `some` state it should switch to `none` or `all`, when I press it on `none` it switch to `all` and reversal.

**Comment by avivdolev** [comment]
This feature would be great, also ran into it with an imported OpenAPI schema scenario - the file has a "placeholder" value for each parameters, most of which are not relevant at first (e.g. filtering examples, offsets value and so on).

In addition to the above suggestion, I'd like to add it will be nice to have a "comment out" shortcut when in bulk-edit mode: 
For example (common shortcut in various editors) - `ctrl + /` will:
- If a cursor is on a line, toggle (change state to with/without) "//" prefix 
- If multiple lines are selected, toggle "//" for each line

Thanks!

**Comment by helsont** [comment]
Is there another way to achieve this while waiting for the feature? Dealing with Postman APIs that have 1) a lot of of parameters 2) default inputs for each parameter and 3) usually I just want to use 1 or 2 of the defaults, so I have to uncheck 50+ parameters just to get the one I want.

**Comment by jordie23** [comment]
Just ran into this problem.

We have APIs with lots of optional params. Would be good to be able to check and uncheck them all to quickly do requests with few or many params.

**Comment by madsringblom** [comment]
+1 for this feature :)

As a temporary hack if using the web-version of postman.
open your console and type
const boxes = document.querySelectorAll('.input-checkbox')
boxes.forEach(box => box.click())

**Comment by branets-dasha** [comment]
What I do is switch to Bulk Edit, copy parameter list to Visual Studio Code, change the language to something like JavaScript (it's usually initially recognized as YAML which uses `#` for comments instead of `//`), select all text, use the keyboard shortcut to comment it out and then paste it back into Postman and switch back to Key-Value Edit.

This is quite tedious, but still beats clicking checkboxes one by one.

Please add an easy way to disable all parameters in Postman. An "all" checkbox would be perfect, but supporting "toggle comments" keyboard shortcut in bulk edit mode would already be a huge help.

**Comment by jacekgajek** [comment]
+1. I also copy it to an editor which can prepend lines with //.

**Comment by MemsourceTesting** [comment]
Yes please...we need a select/deselect all for params

**Comment by vedkribhu** [comment]
In our upcoming release, we have plans to introduce a "Select All" checkbox for query parameters. Rest assured, we will keep you informed through this thread once the feature is officially released. Feel free to share any thoughts or feedback you may have.

https://github.com/postmanlabs/postman-app-support/assets/37595282/97695ca6-73bd-40bf-ba67-b8e9354a225d

**Comment by vedkribhu** [comment]
This feature is now available in v10.22. 

Edit: Phased rollout is in progress for v10.22 and should be available for all by 16th Jan.

**Comment by Rohanb47** [comment]
I have been waiting for this change for a long time.
As I had to test a lot of query parameters had to select all of the query parameters one by one which used to take a lot of time and effort. Now, these will be done just by a single select-all checkbox. 
Great!
