### ISSUE TITLE
Please support TSV files in the runner

### ISSUE THREAD

**Issue by sixcorners** [a85/POSTMan-Chrome-Extension#6936]
**Is your feature request related to a problem? Please describe.**
I have test cases that I'm copying to the runner from google sheets. It copies as tab separated values. It would be nice if the collection runner supported this format so I don't have to replace tabs with commas.
**Describe the solution you'd like**
Support TSV files.
**Describe alternatives you've considered**
I replace tabs with commas.
**Additional context**

**Comment by vikiCoder** [comment]
Hi @sixcorners 

I would suggest you to export the file in `CSV` format directly from Google Sheets instead of copy-pasting data from Google Sheets to text file and then replacing spaces with commas. You can download CSV file from Google Sheets by clicking on File->Download as->Comma-separated values(.csv).

However, we are considering the possibility of supporting TSV files by allowing the user to specify custom column separator while using a file in collection runner. There is no ETA for that as of now, but we are tracking this in the following issue: https://github.com/postmanlabs/postman-app-support/issues/6746.

I am closing this issue in favour of https://github.com/postmanlabs/postman-app-support/issues/6746.
