### ISSUE TITLE
OTRS Create Ticket Issue

### ISSUE THREAD

**Issue by SupriyaYenaganti** [a85/POSTMan-Chrome-Extension#6955]
I am trying to create Ticket using Rest Generic Interface Webservices in OTRS. I downloaded the packge from OTRS github in which I am having yml files which consist of operations like create ticket,search ticket and update ticket
The image of the TicketConnectorRest.yml is below
![image](https://user-images.githubusercontent.com/52815330/61511144-63faeb80-aa13-11e9-825d-530539d9d7c7.png)

I imported this package in OTRS and used postman to create Ticket
![image](https://user-images.githubusercontent.com/52815330/61511227-a9b7b400-aa13-11e9-98a6-42836a03c634.png)

But the issue is in response I m getting Ticket ID of the Ticket already present in OTRS
The postman performs Get for the operation Search TicketID for my post request so I deleted the search operation from the yml file and tried out but it throws internal server error
Bascially, the create Ticket operation in yml file is not being called
Can I know what the ways to solve this issue

Regards,
Supriya

**Comment by sankalp0o** [comment]
Hi @SupriyaYenaganti , the problem might be with the OTRS API and not with Postman. To confirm, can you try the same request using cURL? If the behaviour is wrong in Postman, please let us know and we will work on fixing it. If not, you should try reporting it to OTRS instead.

I'm closing the issue for now, but feel free to reopen this if you find that the problem lies with Postman.
