### ISSUE TITLE
Postman reading response body as request body when importing file

### ISSUE THREAD

**Issue by beflymontreal** [a85/POSTMan-Chrome-Extension#6965]
Dear friends of Postman,

We noticed that when importing a file, for one of the POST calls, postman is adding the response to the body of the request, instead of reading the correct request body and adding the response to the example of successful response. In this case, there are no examples also.

In the other POST call, it shows both request and response as "null" when they're provided.

Testing the same file on other tools, it works as expected. Could you, please, help me understand what may be happening?

A second issue is that when editing the Authorization for the Collection, it is not being added to the requests. I make the request and still asks me to enter the authorization although it was configured in the Edit option for the collection and the "update" button was clicked.

Looking forward to your reply.

Best,
Flora

**Comment by abhijitkane** [comment]
@beflymontreal Can you attach a sample file that you're able to reproduce the issue with? The following details will help us isolate the issue faster - 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
Add any other context about the problem here.

**Comment by vikiCoder** [comment]
Hi @beflymontreal 

I am not able to understand your issue. Please explain the issue in detail and provide detailed steps as suggested in previous comment by @abhijitkane to reproduce the issue at our end.

**Comment by beflymontreal** [comment]
Hi,
One of our developers has opened a bug report with you. I'll let you deal with his ticket since he will be able to better explain the situation than me. You can close this ticket. Thank you!
Best,Flora
    On Thursday, August 1, 2019, 01:41:07 AM PDT, Premang Vikani <notifications@github.com> wrote:  
 
 
Hi @beflymontreal

I am not able to understand your issue. Please explain the issue in detail and provide detailed steps as suggested in previous comment by @abhijitkane to reproduce the issue at our end.
