### ISSUE TITLE
Intermittently get error "Could not get any response" 

### ISSUE THREAD

**Issue by joled** [a85/POSTMan-Chrome-Extension#6990]
Our team intermittently gets the error "Could not get any response" when sending requests with the Postman app. When we do get the error message I can look on the target system and see that the request did actually work. For instance, I have a request that hits an integration endpoint URL to update a netSuite RMA> When I get the error I can see the NetSuite RMA has been updated. 

The timeout for our team workspace is set to 0. Any ideas on how to resolve this are appreciated.

**Describe the bug**
When I click Send, the request is sent but the response payload is not displayed. Instead is the message that reads "Could not get any response ..."

**To Reproduce**
1. Load the request
2. verify the correct body 
3. Click Send
4. View the response message 

**Expected behavior**
The expected behavior is to display the response from the server which is something like this
{
  "success" : true,
  "status_code" : 200,
  "data" : {
    "id" : "71384"
  },
  "timestamp" : "2019-07-24T16:39:36.090"
}

**App information (please complete the following information):**
App Type:  Native App
Postman Version: Version 7.3.2 (7.3.2)
OS: macOS Majave V10.14.6 (18G84)

![PostmanError](https://user-images.githubusercontent.com/52076783/61827381-63f35500-ae32-11e9-879e-e5c64d2e7f8e.png)

Regards,
Joe

**Comment by chrisdeso** [comment]
Hey @joled – Interesting, would you be able to update your original post with the info listed below?



**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
Add any other context about the problem here.

**Comment by joled** [comment]
Hi Chris,
I updated the original post. Thanks.

Regards,

Joe Ledva
Famous Smoke Shop
jledva@famous-smoke.com<mailto:jledva@famous-smoke.com>
610-559-7000 x118

**Comment by chrisdeso** [comment]
Thanks for updating the post @joled!

Have you worked through the list of items/settings surfaced in the `Could not get any response` modal?

1. The server couldn't send a response 
2. Self-assigned SSL certs are being blocked 
3. Proxy Config

---

**For # 1:**
Does sending the same request using cURL (or any other tool/script) return the desired response?
There's an in-app [code generator](https://learning.getpostman.com/docs/postman/sending_api_requests/generate_code_snippets/) that you can leverage to generate the cURL request.

![image](https://user-images.githubusercontent.com/4734306/61833189-2219dd00-ae39-11e9-9a89-4135ce054694.png)

**For # 2:**
Does turning off `SSL certificate verification` in the app settings change the behavior?

**For # 3:**
Proxy! This doesn't seem like it would be the issue as the records are being updated on the server 🤔

**Comment by joled** [comment]
Hi Chris,

Thanks for the response. I have not actually checked the NetSuite server to see if it actually responded to the request after it was finished with it. I will do that the next time it happens. SSL cert is not the issue, Postman displays the response most of the time. Same for proxy settings. If I get it figured out I will let you know, fyi.

Regards,

Joe Ledva
Famous Smoke Shop
jledva@famous-smoke.com<mailto:jledva@famous-smoke.com>
610-559-7000 x118

**Comment by joled** [comment]
Hi Chris, or whomever picks this up.

I received the error again and looked at the response from the server. The response was actually sent back from the server. Fyi, in case this helps.
Regards,
Joe

**Comment by SabriH10** [comment]
Hi @joled,
I just wanted to reach back out following the issue you observed here. Judging by the elapsed time since, are you still encountering this intermittent issue? As Chris inquired, were you able to reproduce this issue when using cURL or just while with Postman? 

Finally, could you confirm if you are running the latest version of Postman and if so, does this problem still show up intermittently? Thank you, and looking forward to your response.

**Comment by joled** [comment]
Hello,
Yes I am still getting the message. I gave up trying to figure out what is causing the issue. It is a Postman thing. Thanks you for checking back.

Regards,

Joe Ledva
Famous Smoke Shop
jledva@famous-smoke.com<mailto:jledva@famous-smoke.com>
610-559-7000 x118

**Comment by DannyDainton** [comment]
Hey @joled 

I'm going to close this issue due to inactivity, if this is still an issue in the latest versions, we can reopen it and investigate further.
