### ISSUE TITLE
Environment shared to another workspace  can be edited/deleted

### ISSUE THREAD

**Issue by blackasninja** [a85/POSTMan-Chrome-Extension#7028]
**Steps/ Description**
I have Workspace-A and Workspace-B. 
I share an environment from Workspace-B to Workspace-A.
Switch to Workspace-A and make changes to the newly shared environment.
Switch to Workspace-B and the changes from Workspace-A changes  are applied to my Workspace-B environment. 

**Expected behavior**
Environments should operate individually in each workspace 

**App information (please complete the following information):**
- Postman Desktop App
 - Postman Version  v7.3.4
 - OS: Windows 10

**Comment by sankalp0o** [comment]
Thanks for reporting @blackasninja !
In Postman, things shared across workspaces maintain the same reference so that different groups of people can work on them together. If you do not want this, you can follow the following steps
1. Have workspace-A and workspace-B
2. Duplicate environment E in workspace-A, new environment E` is created
3. Share new environment E` to workspace-B
4. Remove Environment E` from workspace-A
This way, E and E` can be changed without affecting each other.

I'm closing this ticket but feel free to reach out if this does not solve your problem.
