### ISSUE TITLE
v7.3.4 and Up - mac , postman doesn't recognize url in body of a JSON response

### ISSUE THREAD

**Issue by giripriyav** [a85/POSTMan-Chrome-Extension#7049]
_Monaco editor_ used for displaying the response in v7.3.4 and up doesn't recognize urls in body.
This subsequently prevents us from following any urls in JSON response
_Ace Editor_ which was used in v7.2.2 and below had this feature. 

**Screenshots:**
Same API call has been made to generate both these screenshots 
1) Url recognized on hover in v7.2.2
![Screenshot 2019-08-02 at 5 00 28 PM](https://user-images.githubusercontent.com/51907546/62367583-bbd33f80-b547-11e9-948d-d8f5f856f791.png)

2) Url not recognized on hover in v7.3.4 and v7.3.5
![Screenshot 2019-08-02 at 5 07 37 PM](https://user-images.githubusercontent.com/51907546/62367771-2a180200-b548-11e9-9029-8312c61441bc.png)

**App information (please complete the following information):**
 - Native App
 - v7.3.5
 - OS: macOS 10.14.16

**Comment by saswatds** [comment]
Hey @giripriyav, I not able to reproduce the issue. I am using out test server `postman-echo.com/get` endpoint to construct your url as seen below. 
<img width="994" alt="Screenshot 2019-08-03 at 10 01 10 AM" src="https://user-images.githubusercontent.com/8796447/62407397-a99fe280-b5d5-11e9-8ec7-0078f615fdd9.png">

Prior to 7.3.x the response viewer was un-intentionally ignoring escape character being sent in responses. In the latest version, we do not perform any kind of parsing on the response so that we do not render false information.

Is it possible that your server is actually sending the escape characters in the url `\` ?

**Comment by giripriyav** [comment]
@saswatds You are right about our server sending the escape characters. It is necessary for our client. Can you suggest any way to allow that "un-intentional" parsing in newer versions? This may be a feature request then.

**Comment by saswatds** [comment]
@giripriyav At this moment I am afraid there is no way. Currently we are tracking all these kind of hidden bug/features associated with the old editor following which we planning to provide a bunch of settings to re-enable the old behaviour in a case to case basis. We will keep this issue in mind. 

Thanks.
