### ISSUE TITLE
Proxy not saving requests in latest 7.5

### ISSUE THREAD

**Issue by danijelk** [a85/POSTMan-Chrome-Extension#7118]
Latest Postman on Mac doesn't capture any traffic through the proxy requests feature. Tested in chrome where I turn proxy off to ensure chrome isn't able to connect to internet, once it's on requests are sent through but never logged.

Haven't tried interceptor, but we I can't use it on the device I use Postman for as device sends requests though scripts.

**Expected behavior**
Worked in 6.3.0

**App information**
 - Native app 7.5.0
 - OS: MacOS 10.14.6

**Comment by m3dbedb** [comment]
Same issue with Postman 7.3.6 in windows 7 32 bit. Also in Postman 6.7.1 Capture API button was marked with light square then turned on, current Postman 7.5.0 does not signal API capture status.
![cat](https://user-images.githubusercontent.com/25632818/63165327-c572a200-c033-11e9-85cf-a81feabfe7e3.JPG)

**Comment by shanemgrey** [comment]
Also experiencing this issue since last update.  Using Firefox with FoxyProxy to send all localhost requests to 5555.  When Postman Proxy "Capture Requests" is on, the requests are forwarded as expected, but no log of them is showing in the history tab.

When I turn off Postman proxy, or just close Postman, the requests fail, unless I also turn off FoxyProxy.  The shows that Postman is performing proxy service.

Release notes for this 7.5.0 show a new feature "Added support for request capture via the Interceptor"  

Seems likely the problem with normal proxy function is related to this new feature.

**Comment by abhijitkane** [comment]
@shanemgrey @danijelk @m3dbedb Confirmed as a bug. A temporary workaround is to add the comma-separated list of methods in the `Show additional filters > Methods` textbox: `GET,POST,PUT` should do for most cases.

We'll be pushing out a patch in the next release.

**Comment by shanemgrey** [comment]
The workaround doesn't work for me.  The  Methods textbox is only in the Interceptor tab.  I'm using the Proxy since I'm not using Chrome.  Putting that list in the interceptor methods textbox seems to have no effect on the proxy log.

**Comment by mccannt** [comment]
@shanemgrey What OS and version are you running?
It should be there ...

![image](https://user-images.githubusercontent.com/14275144/63286008-6c05af80-c28d-11e9-9dbf-6ce4f05e235c.png)

**Comment by shanemgrey** [comment]
@mccannt You are right.  Since it expands the length of the window upon clicking additional options, I didn't notice the scroll bar.  Adding those methods did work as a workaround.  Thanks for the response!

MacOS (current), Postman v7.5.0

**Comment by Hajawata** [comment]
@abhijitkane - Unfortunately the workaround does not work. No requests get captured (Windows 10, x64, 7.5.0). The only "solution" I found so far is to downgrade to 7.3.6 version. Since Postman starts to update immediately, I have to keep it open, so it does not switch to 7.5.0. Frankly speaking, I really do not understand, why it is not possible to disable minor upgrades to be downloaded automatically. This is a prominent example, where forcing user to update actually makes things worse.

**Comment by danijelk** [comment]
Would love to hear that a unittest is made for this important function to avoid future issues. 👍

**Comment by Hajawata** [comment]
This should definitely be the case, however the possibility to postone updates would also do the job. I found several threads requesting this possibility, but Postman team seems to be really stubborn here, claiming it is to users' best interest to have the newest version installed.

**Comment by satishkn** [comment]
My env is Windows 10 (64 bit). I have also noticed the problem that the requests are not saved with Capture Requests setting 'On'. The workaround suggested seems to work. I had to spend a lot of wasted cycles on this - thinking it could be proxy issue, or firewall blocking in my company's environment and such. The indicator on 'Capture requests and cookies with Postman' doesn't indicate that the Capture Requests is selected ('On'). when the window is closed. It is really confusing and one has to keep on checking regularly.

**Comment by Hajawata** [comment]
Just checked the newest version (7.6.0). The bug is still there.

**Comment by DannyDainton** [comment]
Is anyone still facing this issue on the latest version of the app?

**Comment by danijelk** [comment]
Confirmed and works on Mac - Version 7.32.0.
