### ISSUE TITLE
OAuth 2.0 Client Credentials: Client ID and Secret not urlencoded when using Basic Auth header

### ISSUE THREAD

**Issue by mvdriel** [a85/POSTMan-Chrome-Extension#7138]
**Describe the bug**
OAuth 2.0 Client Credentials: Client ID and Secret not urlencoded when using Basic Auth header

**To Reproduce**
1. Go to 'Authorization'
2. Click on 'Get New Access Token'
3. Select 'Client Credentials' for 'Grant Type'
4. Fill in ':' for Client ID
5. Fill in ':' for Client Secret
6. Select 'Send as Basic Auth Header' for 'Client Authentication'
7. Click on 'Request Token'

**Expected behavior**
Request Headers (expected):
Authorization: Basic JTNBOiUzQQ==

base64_encode(urlencode(':') . ':' . urlencode(':'))

Request Headers (actual):
Authorization: Basic Ojo6

**App information:**
 - Postman for Linux
 - Version 6.7.1 and 7.5.0
 - OS: Ubuntu 18.04

**Additional context**
Relevant section of the RFC of The OAuth 2.0 Authorization Framework: https://tools.ietf.org/html/rfc6749#section-2.3.1

**Comment by vikiCoder** [comment]
Hi @mvdriel 

Thanks for reporting the issue. We have confirmed the issue and will be fixing this in our upcoming release of Postman app. 

Until the fix is released, you can urlencode the required fields (`Client ID` and `Client Secret` in this case) manually in `Get new acccess token` window by right-clicking on the field and selecting `EncodeURIComponent` option.

**Comment by vit100** [comment]
Any update on this issue?

**Comment by vikiCoder** [comment]
Hi @mvdriel, @vit100 

We have decided not to automatically percent-encode the client credentials in OAuth2 because we haven't received any other issues related to it. So it might break for some users who are already using it without encoding. However, we have added a warning and started highlighting such characters that might need encoding in the client credentials grant type. It is displayed in the below screenshot. You still need to encode such characters manually by right clicking and selecting `encodeURIComponent` option.

These changes are out in the latest [Postman canary (v7.21.0-canary01)](https://www.postman.com/downloads/canary). The same will be there in the production app soon.

Screenshot:
![image](https://user-images.githubusercontent.com/16588032/76423049-357bb780-63cc-11ea-8cac-2d37ff5b7322.png)

**Comment by vit100** [comment]
Wanna add option to url encode button, as helper..

**Comment by vikiCoder** [comment]
The changes mentioned in my [previous comment](https://github.com/postmanlabs/postman-app-support/issues/7138#issuecomment-597642899) are out in the latest version of the Postman app (v7.21.0).

**Comment by iSatishYadav** [comment]
Successfully spend this afternoon explaining this issue internally. 😆 
Jokes apart, thanks @mvdriel for reporting the issue. @vikiCoder It would be helpful if Postman highlights and issues warning for other characters which require URL encoding like in #7378 @hmoratopcs had issue with +.

**Comment by carnahanliam** [comment]
> Hi [@mvdriel](https://github.com/mvdriel), [@vit100](https://github.com/vit100)
> 
> We have decided not to automatically percent-encode the client credentials in OAuth2 because we haven't received any other issues related to it. So it might break for some users who are already using it without encoding. However, we have added a warning and started highlighting such characters that might need encoding in the client credentials grant type. It is displayed in the below screenshot. You still need to encode such characters manually by right clicking and selecting `encodeURIComponent` option.
> 
> These changes are out in the latest [Postman canary (v7.21.0-canary01)](https://www.postman.com/downloads/canary). The same will be there in the production app soon.
> 
> Screenshot: ![image](https://user-images.githubusercontent.com/16588032/76423049-357bb780-63cc-11ea-8cac-2d37ff5b7322.png)



I just spent a few hours debugging until I realized this was the issued I was having, as my client secret contained a "+" sign. I see the warning message feature was released in v7.21.0, but has this since been removed? I only see this message encouraging me to store the secret in Vault, and having the encoding warning message you've shown here would have saved me a lot of time. 

![Image](https://github.com/user-attachments/assets/cf8a8995-2b7f-4664-be5a-65f92908a6ee)

**Comment by omaristalis** [comment]
I've wasted a lot of time fighting with this one - I even ended up reading the RFC where it clearly states that the client ID / client secret MUST be URI encoded.

Surprised that a) this isn't done in Postman, and b) it doesn't warn you that it's not compliant with the standard.
