### ISSUE TITLE
Unpublishing Docs as part of the collection deletion

### ISSUE THREAD

**Issue by AquaHippie808** [a85/POSTMan-Chrome-Extension#7143]
**Is your feature request related to a problem? Please describe.**

**Summary: Unable to Unpublish docs when removing a user & deleting the collection**

1) Employee leaves the company
2) Admin Removes User
3) Admin Deletes Collection/s from Removed User
4) Published Docs from Collections are still accessible
5) Admin cannot unpublish from Native App or Dashboard

**Describe the solution you'd like**

1) Employee leaves the company
2) Admin Removes User
3) Admin Deletes Collection/s from Removed User
4) Published Docs from Collections should be removed as part of the process

**Comment by Cazaimi** [comment]
@asi851 , could you describe what happens when you try to hit the Published doc's url? 

Ideally, when anyone tries to hit this user's documentation they will receive a HTTP 404, since you've already mentioned that the Admin has gone ahead and deleted the collection. Once you delete the collection, the public documentation will no longer be accessible. 

Please feel free to reply on this thread if this is not the case.

**Comment by AquaHippie808** [comment]
@Cazaimi Sorry for the delay on this. The customer can confirm that a 404 is being returned when trying to hit the url.

**Comment by Cazaimi** [comment]
@Raja-Simha , this can be marked as closed, since this was resolved internally.
