### ISSUE TITLE
I tried to record the interface, but failed

### ISSUE THREAD

**Issue by TestOpsFeng** [a85/POSTMan-Chrome-Extension#7145]
It's OK before I upgrade it, It's awful!

**Comment by TestOpsFeng** [comment]
The version is Version 7.5.0

**Comment by numaanashraf** [comment]
@TestOpsFeng Could you give us more information on the issue you are facing? Do follow the guidelines and issue templates while reporting issues.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

**Comment by preethammavin** [comment]
@TestOpsFeng closing the issue for now, kindly provide the necessary information and reopen the issue so that we can address it.
