### ISSUE TITLE
I'm not able to capture any request/ response of API in newly update Postman version v7.5.0

### ISSUE THREAD

**Issue by SorbAggarwal** [a85/POSTMan-Chrome-Extension#7149]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by RichardJFoster** [comment]
While the initial bug report is somewhat lacking, I'm seeing the same thing when running Postman 7.5.0 on Windows 10 attempting to access a url available on a local IIS instance.

The URL I am attempting to access is http://[LocalMachineName]/[VirtualFolder]/api/endpoint.

I can access the URL successfully using a web browser (specifically Chrome, but I imagine it'll work in the other browsers too). From Fiddler, I'm getting a 406 response, but I think that error is misleading.

According to Teltronic Fiddler (v5.0.20192.25091), the request actually being made by Fiddler is http://[LocalMachineName]/. The request headers appear to be correct, however and the user agent identifies itself as PostmanRuntime/7.15.2

Attempting to use http://localhost/.... instead of the local machine name results in the same problem.

Requests to non-local hosts appear to be operating correctly.

**Comment by shamasis** [comment]
I am closing this issue for lack of useful information from the original poster. The subsequent info from @RichardJFoster, I am appending to #7125 since they are eerily close in how they are responding.
