### ISSUE TITLE
Ability to fetch a particular version of collection with newman and postman API

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7170]
**Is your feature request related to a problem? Please describe.**
Have the ability to specify version tags when running collections using `newman` and Postman API

Currently, we can only do something similar to the following:
`newman run https://api.getpostman.com/collections/{{collection_uid}}?apikey={{postman-api-key-here}}`
Which runs the latest version.

This helps a team test a particular version before updating the version in Production.

Ref: https://learning.getpostman.com/docs/postman/postman_api/continuous_integration/

**Describe the solution you'd like**
Have a way to specify the version tag, to fetch and run a particular tagged version of a collection.

_For example:_
```newman run https://api.getpostman.com/collections/{{collection_uid}}?apikey={{postman-api-key-here}}&versionTag=<versionTag>```
OR
```newman run https://api.getpostman.com/collections/{{collection_uid}}/{{versionTag}}?apikey={{postman-api-key-here}}&versionTag=<versionTag>```

Where *versionTag* parameter can be used to specify the version tag to use.

**Additional context**
Logged on behalf of a user.

**Comment by ryanmmmmm** [comment]
hello,

monitors do not work because these are applications restricted by AWS firewall rules/security groups they are not publicly available.

if we do not have versioning then we do not have the ability to run tests in an environment for a particular version after a deployment.  aka staging is version 4, QA is version 5!

this is a pretty severe limitation of testing given this "enterprise and environment heavy" workflow.  wish it could always be continuous delivery where mast is always pushed to prod!!!  but thats not the world we live in for this particular system.

any update?  if monitors can run a version then it MUST be close to getting this in newman and/or the postman client right?????

**Comment by davidespihernandez** [comment]
Hi! In the new Postman app version (v10), collection tags don't exist anymore. 

However, I think you can perhaps solve your issue by forking the collection and using a different (forked) collection for each environment. 

See more information about forking Postman entities here: https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-entities/
