### ISSUE TITLE
Show Collection deletions in workspace history

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7185]
**Is your feature request related to a problem? Please describe.**
Collections deletions are not currently displayed in workspace history. This recently affected a large team that was unable to determine who had a deleted a Collection published to a custom domain.

The user who deleted the Collection was also out-of-office, but fortunately was able to respond and restore it from their trash.

**Describe the solution you'd like**
- Log Collection deletions in workspace history

- (Optionally) Allow workspace and/or team Admins to recover any deleted Collections from workspace history, and allow workspace Collaborators to restore their own deleted Collections from workspace history.

This would help in scenarios where a Collection needs to be restored from trash, but the person who deleted it isn't available or aren't aware that they deleted it.

**Describe alternatives you've considered**
None

**Comment by JP-from-Postman** [comment]
@preethammavin @sankalp0o 

Also worth noting about deleted Collections in this scenario:
- A Collection was created by User A, who has the Editor role for it
- User B (who also has the Editor role) deletes this Collection (it goes to their Trash)
- User B restores this Collection from their Trash
- User B is granted the Editor role for the restored Collection, Team is granted Viewer by default.
- User A does not initially have the Editor role for this Collection, and User B must grant it to them.

Thoughts on how to mitigate this problem:
a. Restore the exact state of a Collection at the time it was initially deleted. Example: return it to all the same workspaces it was saved to, and restore all permissions that were assigned to it, etc.

b. Add a "Team Trash", or "Workspace Trash" where deletions from Team Workspaces end up, that can be accessed by anyone on the team, in that workspace, or maybe just Workspace /Team Admins. See issue https://github.com/postmanlabs/postman-app-support/issues/7377

**Comment by yoniholmes** [comment]
This affected my team. At a critical moment as were making a first production build, 2 things happened: Postman archived our collection, then (it turns out after over a week fo investigation with Postman support), a colleague uploaded his own collection (in an attempt to restore what had been lost), only without realising it he deleted our master collection. After paying for the Pro plan, we still could not find the collection. Eventually (through much support help), Postman figured out what had happened.

I can think of 3 separate fixes which would have helped us:

1. A shared Team Trash can so that we could have found the lost collection without relying on our team member.
2. Improved UI to prevent it being possible to delete collections at all when uploading another. Make it impossible to do this accidentally.
3. Don't pre-emptively archive people's collections when they reach a threshold - find another way to encourage people to pay. This is what caused us so much difficulty in the first place. 'Ransomeware' is how it was described by one - which no doubt you'd agree reflects badly on the Postman brand. We all lost some faith with Postman when this happened. It felt like quite an accurate description as it seemed we had nw way to access our collection other than by paying money for it.

All the best with it.

**Comment by sankalp0o** [comment]
Hey @JP-from-Postman , @yoniholmes 
We've added collection deletes to the workspace activity feed as part of our initiative to improve the activity feed.

We're tracking suggestions around Team trash on #7377. 

You can always recover archived collections from https://go.postman.co/usage/archive. Detailed steps are covered here - https://community.postman.com/t/archived-collection/2679/4
We are also working on improving flows so collections are not archived inadvertently while importing other collections. 

I'm closing this ticket since the original issue was fixed, but please feel to create another issue if you'd like to suggest more improvements!
