### ISSUE TITLE
PATCH request with JSON body is processed as GET 

### ISSUE THREAD

**Issue by budik21** [a85/POSTMan-Chrome-Extension#7188]
**Describe the bug**
I try to send PATCH request with JSON body (raw) and I expect, that I get PATCH method on my server, but I don't. It seems, that Postmant doesn't process PATCH request with JSON body as PATCH, but as GET. I have tried the same request in INSOMNIA, and all was OK.

**To Reproduce**
Prepare some request with PATCH method with raw JSON body and send i to the server. Try to detect method of the request. You will GET.

**Expected behavior**
When I set the request as PATCH, I expect PATCH on servr side, not GET.

**App information (please complete the following information):**
 - Postman Version 7.5.0

**Comment by coditva** [comment]
Hey @budik21, thanks for reaching out! We suspect that there's a redirect happening here. Can you try the request with automatic redirects turned off?

Go to Preferences > General > Headers; and turn off the "Automatically follow redirects" option.

If the problem still persists, we may have to investigate further.

**Comment by budik21** [comment]
Hey @coditva, thanks for reply. I have tried it, but the behavior is a bit confusing. The request return 302 status, but a payload contains HTML code fragment. On the server no request has ben detected.

```<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>

<head>
	<title>302 Found</title>
</head>

<body>
	<h1>Found</h1>
	<p>The document has moved <a href="https://api.azurable.com/auth">here</a>.</p>
</body>

</html>

**Comment by coditva** [comment]
@budik21 it is normal to send some response with `302`. Since, there _is_ a redirect, the HTTP request is changed from `PATCH` to `GET` on redirection.

There can be multiple issues for the redirection. Maybe the request is not authenticated and you're being redirected to `https://api.azurable.com/auth`.

Or maybe you're trying to access an API that has indeed moved to `https://api.azurable.com/auth`. You can solve this problem by changing the request URL in Postman to the one mentioned in the response (`https://api.azurable.com/auth`).

Do let me know if it does/doesn't work out. :)

**Comment by coditva** [comment]
Closing this issue since this is the intended behaviour. Please feel free to comment or re-open if any doubts.

**Comment by slavaOtonomo** [comment]
The bug still exists in Version 10.13.4, Postman produces GET instead of PATCH or PUT...
