### ISSUE TITLE
incorrectly showing scientific notation in Pretty and Raw JSON views 

### ISSUE THREAD

**Issue by yoimnik** [a85/POSTMan-Chrome-Extension#7197]
**Describe the bug**
when i make a GET request to an API via postman, the JSON response shows floating point numbers in scientific notation, ie:

`"event_time": 1.566475228535E9,`

this is both the case when i'm viewing the JSON response in `Pretty` and `Raw`.

i've verified that when i hit the API using python's `requests` library, the JSON response does not show floating point numbers:

`"event_time": 1566475228.535,`

**Expected behavior**
it should show `"event_time": 1566475228.535,`

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.5.0
 - OS: macOS High Sierra 10.13.6

**Comment by shamasis** [comment]
This should not happen. But let me rope in @kamalaknn and @saswatds who would be able to point out why this could be happening (or if I’m missing some recent change.)

**Comment by kamalaknn** [comment]
Hi @yoimnik, thanks for reporting this issue. 

In the recent versions of Postman, we made some changes to the response rendering section. We *do not parse* the response JSON anymore to format the response. We do this so that we can preserve as much information from the actual response without any loss due to language limitations (e.g. big numbers cannot be represented accurately in JavaScript).

I'm guessing in this case, your server always returned the response as `{"event_time": 1.566475228535E9}` which would be converted to `{"event_time": 1566475228.535}` by the `JSON.parse` (in case of JavaScript, or equivalent in your language).

To confirm this you can open the devtools of any browser and compare the results of 
```
fetch('{{url}}').then((res) => res.json()).then(console.log.bind(console, 'JSON parsed:'))

fetch('{{url}}').then((res) => res.text()).then(console.log.bind(console, 'Text:'))
```

**Comment by saswatds** [comment]
Hi @yoimnik , I have performed independent test and verified that current pretty and raw mode are not converting or parsing any values in the JSON. If the server sends scientific notations then the notation is preserved. 

Will be closing this issue now.
