### ISSUE TITLE
Change rename keyboard shortcut to F2 to match common usage

### ISSUE THREAD

**Issue by idevtech** [a85/POSTMan-Chrome-Extension#7235]
It would be helpful, and more consistent, w/ many other programs if F2 was used for rename.

**Comment by oliverm2112** [comment]
This one drives me nuts. I can't stop hitting F2! I had to install a keyboard re-mapper for this app so that I could use F2 to edit names ;)
It would be best is all keyboard shortcuts were customizable.

Hack - change to this in /app/resources/app/js/vendor-ui.js:
{
  name: 'rename',
  label: 'Rename Item',
  shortcut: 'f2',
  keyLabel: 'F2',
  keyLabelDarwin: 'F2' 
},

**Comment by chris-torruella** [comment]
Hi folks, thanks for your patience with this issue.
We recently launched the capability to [customize your keyboard shortcuts](https://blog.postman.com/postman-customizable-keyboard-shortcuts/) and enabled Function keys for it.
So, while it is not in our plans to change the defaults, you can tailor these to the best of your use cases.
Hope this helps.
