### ISSUE TITLE
I'd like to use the result of one API response, to inform another API using that data

### ISSUE THREAD

**Issue by sshadmand** [a85/POSTMan-Chrome-Extension#7242]
Problem:
I generate access tokens as part of my API. I would like to keep using those temporary tokens as part of the test cycle. Currently, since each test in discretely independant, I can't generate that token to be used in subsequent tests. 

Suggested Solution:
I'd like for one API result to set variables for subsequent tests to be used in the request headers.

**Comment by sshadmand** [comment]
Doing some reading of Docs. I think it may be possible using Pre-Request Scripts, and Setting Global variables, but haven't put 2 and 2 together yet. Still reading, but if anyone has an example, (or knows if I am headed the wrong way) help would be appreciated :-)

**Comment by sankalp0o** [comment]
Hey @sshadmand ! You're right and it is one very common use case using Tests and variables. Generally our Docs should be informative enough to figure this out but if you need help with something particular, perhaps ask the community - https://community.getpostman.com 
@kaustavdm are there any other resources that Sean can refer to?

I'm closing the issue since this is neither a bug or a feature request, but please feel free to continue the conversation.

**Comment by kaustavdm** [comment]
@sshadmand You need to use a combination of tests and pre-request scripts with variables to get this done. I recommend going through the article on [APIOps with Postman](https://medium.com/better-practices/apiops-the-art-of-mixing-apis-b0d85de88864) which goes into this in quite detail.
