### ISSUE TITLE
When I updated postman the icon doesn't appear correctly

### ISSUE THREAD

**Issue by Noeury** [a85/POSTMan-Chrome-Extension#7243]
When I **updated** postman the program icon doesn't **appear**, it shows the default windows icon.

That happens after the last update

**Comment by harryi3t** [comment]
@Noeury Thank you for reporting this issue. We are tracking this issue here https://github.com/postmanlabs/postman-app-support/issues/6897 
You can also find the workaround here https://github.com/postmanlabs/postman-app-support/issues/6897#issuecomment-520352830

Please subscribe to the original thread for any future updates.
