### ISSUE TITLE
Double-quotes are escaped in generated code snippets, leading to lower readability

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#7250]
Reported by @berend 

Now curl code is generated with " as string delimiter for the -d/--data option. Since I guess most of the people here send json, which also requires " as string delimiter, all " from the json are now escaped via \". The code still works, but it looks ugly.

Without that experimental flag, curl code is generated with ' as string delimiter for curls -d/--data option. json " quote do not need escaping, looks way better.

**Comment by shreys7** [comment]
Hey @abhijitkane In Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'New Code Generation Mode' flag enabled in Postman's global settings.
This bug has been fixed with new code generation mode.
![Screenshot 2020-01-02 at 1 40 19 PM](https://user-images.githubusercontent.com/20665864/71661321-dbc79300-2d73-11ea-8bba-70006c3cc90b.png)
