### ISSUE TITLE
Failed to import collection

### ISSUE THREAD

**Issue by anilloutombam** [a85/POSTMan-Chrome-Extension#7309]
**Getting an error on importing a collection "Failed to import collection <>"**

1. Go to Import
2. Click on Import From Link
3. Click on Import
4. See error "Failed to import collection ***"

 - App Type : Native App
 - Postman Version: 6.7.1
 - OS: Ubuntu 18.04.3 LTS

**Comment by anilloutombam** [comment]
Unable to use native app still..it's been 13 days @abhijitkane @preethammavin

**Comment by abhijitkane** [comment]
@anilloutombam Can you attach the file you're trying to import, or send it to help@getpostman.com? Also, are you seeing this issue with version 7.7 of the app too?

**Comment by anilloutombam** [comment]
Sorry it's for the company, so unable to upload the file

**Comment by ddjurgensen** [comment]
I also have this problem and can provide a file, since the collection is a Open API. Its fairly large and the error that I get is Error while importing Swagger 2.0 Could not import. It has something like 1163 elements. Here is the file:

[NSX-T Manager API.json.zip](https://github.com/postmanlabs/postman-app-support/files/3659462/NSX-T.Manager.API.json.zip)

**Comment by ddjurgensen** [comment]
I see that it has a element:
	"swagger": "2.0",
	"basePath": "/api/v1",
	"version": "2.4.1.0.0",
so maybe its related.

**Comment by abhijitkane** [comment]
@ddjurgensen I'm able to import this collection in v7.14 of Postman. Can you confirm?

@anilloutombam I'm afraid we'll be unable to investigate further without a sample input file you can provide. You can redact company-specific data in your file before sharing.
