### ISSUE TITLE
Laravel errors show as nothing

### ISSUE THREAD

**Issue by Luke-SF** [a85/POSTMan-Chrome-Extension#7336]
**Describe the bug**
Cannot see Laravel errors that come back.

**To Reproduce**
1. Fresh install of Homestead. Make any route that has an error or missing include.
2. Try the get/post in Postman.
3. Note that although it has the html, it will show nothing, perhaps because the preview doesn't even have javascript?

**Expected behavior**
There should at least be an option to have js and show preview like you can see if you showed it in a browser.

**Screenshots**
![Screenshot from 2019-09-17 11-32-01](https://user-images.githubusercontent.com/2318837/65069505-aa9b9200-d93f-11e9-9c5f-001ca4f8f7ce.png)

**App information (please complete the following information):**
 - App Type Native
 - Postman Version 6.7.1
 - OS: Ubuntu 18.04

**Additional context**

**Comment by chrisdeso** [comment]
@Luke-SF What does cURL return when you send the same request?

You can use the `Code` feature to generate the request formatted for cURL:

- https://learning.getpostman.com/docs/postman/sending_api_requests/generate_code_snippets/

**Comment by Luke-SF** [comment]
Well it is unfortunately doing the same in a Firefox REST tool, I'm sure it is not the requesting that is broken. It looks the same and has a `<script>` with the data, when I use that curl command.

**Comment by saswatds** [comment]
Hi @Luke-SF, you are currently viewing the response in `Pretty` mode. If you click on the `Preview` tab you should be able to see a rendered page. 
When you say
> Note that although it has the html, it will show nothing, perhaps because the preview doesn't even have javascript?

Do you mean that `Preview` tab is not loading the page?

**Comment by Luke-SF** [comment]
Right, it seems I can't get it to load in the preview tab because it depends on javascript in the later Laravel versions.

**Comment by saswatds** [comment]
Okhay got it. @Luke-SF you are right javascript has been disabled in the Preview tab due to security reason. We have been exploring solution for this and might have a something in the near future. 
We are tracking this issue in https://github.com/postmanlabs/postman-app-support/issues/2646
So in-favour of the master feature request I will be closing this issue as duplicate.

Thanks for reaching out. Feel free to re-open this issue if you think the above feature does not full-fill your request.
