### ISSUE TITLE
Bug - custom Content-Type header being reset to text/plain

### ISSUE THREAD

**Issue by dltacube** [a85/POSTMan-Chrome-Extension#7337]
**Describe the bug**
On version 7.7.2, changing any text inside the body of a `POST` request will automatically change the `Content-Type` header to `text/plain`.

**To Reproduce**
1. Create a `POST` request
2. Fill out the request body
3. Fill out the `Content-Type` header to something custom, in my case it's a variable
4. Go and make any change to the request body
5. Look at the headers tab, `Content-Type` will be set to `text/plain`

**Expected behavior**
Expected behavior is that custom `Content-Type` headers will not be automatically set unless none exist already.

**App information (please complete the following information):**
 - Native App
 - 7.7.6
 - macOS Mojave 10.14.6

**Comment by saswatds** [comment]
Hi @heyoni, thank you for reporting this issue. I can confirm that this is happening. 
Prior to v7.7 the app did not understand language of the raw body and ephemerally tried to infer the language from content-type. This prevented us from providing support for standard languages with custom content type. In the latest app version we internally added support for raw body language.

So I can see that the bug is in the very first time when a content-type header is set and the laguage selector is not able to infer the language from headers it falls back to Text and set Content-Type to `text/plain`. While we get this flow in order, you can just set the Content-type again and it won't get replace.

In next upcoming release we will stop the automatic inference which should fix this inconsistent flow for everyone.

Really sorry for the inconvenience.

**Comment by saswatds** [comment]
Hi @heyoni, 
We've pushed a fix for this on v7.7.3. Can you update your app and confirm if that fixes your issue?

**Comment by dltacube** [comment]
Just tested this and it works!

Thank you so much for the quick turnaround.
