### ISSUE TITLE
Alt + Shift = Menu

### ISSUE THREAD

**Issue by makhnanov** [a85/POSTMan-Chrome-Extension#7349]
I want to switch language. I press Left Alt + Left Shift. But I open Content Menu "File". Can you fix it?

**App information:**
 - App Type: Desktop
 - Postman Version: v7.7.2 x64 for Linux
 - OS: `Linux System-Product-Name 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harryi3t** [comment]
@makhnanov Could you give us some more information about what's the expected behaviour?
A screen-recording/gif would really help

**Comment by makhnanov** [comment]
Of course.

**Comment by mistralbkru** [comment]
- App Type: Desktop
- Postman Version: v8.0.6 x64 for Linux

same behaviour.
It is really sad

**Comment by mistralbkru** [comment]
Left Alt + Left Shift get file menu, but if i press  Left Shift first (Left Shift+Left Alt) it is ok, language switched

**Comment by madhead** [comment]
I had the same issue in Slack for a while, and recently it began to behave this way in Postman.

- App Type: Desktop, version 9.0.5
- OS: Manjaro Linux
- DM: KDE

I think it's something related to OS / Electron (do you use Electron?) and, probably, could not be solved on the application level. Although it really makes it impossible to use the app in a multi-language environment. Check the video with a bug:

https://youtu.be/9Zu96cHp_1I

Note that a menu appears on every language switch and the editor loses focus.

I have `Alt` + `CapLock` as a language switch shortcut, but it doesn't work with `Alt` + `Shift`. Actually, anything starting with `Alt` would not work, as `Alt` instantly triggers a menu to appear. The problem is that pressing the keys in the other way round (i.e. `CapsLock` + `Alt`) doesn't switch the language (and, of course, breaks my habits and my muscle memory).

**Comment by RaisinTen** [comment]
Is this reproducible in the latest version of Postman?

**Comment by madhead** [comment]
I'm now on Ubuntu 20.20, Postman v9.13.2 and sadly, the issue is still there: changing the layout with `Alt` + `Shift` moves the focus to the menu.

**Comment by RaisinTen** [comment]
Hmm, that was unexpected because that version of Postman uses Electron v13.6.7 and the [fix](https://github.com/electron/electron/pull/29328) for this issue has been backported to all release lines >= v12.

Assuming that you have Git, Node.js and npm installed on your system, could you please try to:
1. clone the [electron-quick-start](https://github.com/electron/electron-quick-start) repo
2. change [this line](https://github.com/electron/electron-quick-start/blob/2c9d5a10573cbbe4613e1100c97d4847e15a24d9/package.json#L20) to `"electron": "13.6.7"`
3. run `npm i` to install the deps
4. run `npm start` to start the app and see if the issue is still reproducible there

?

If the issue is still present in this bare bone electron app, it could mean any of these:
* the fix from Electron doesn't entirely work
* something might be wrong on your setup

and if it's not so, it would mean that we are doing something wrong in the implementation.

FYI, I wasn't able to reproduce this issue.

**Comment by madhead** [comment]
I've reproduced and recorded a video:

https://user-images.githubusercontent.com/577360/155823034-ac74f9e9-9f3b-4489-816d-d02f84121469.mp4

The `Alt` + `ISO_Next_Group` is just `Alt` + `Caps Lock`.

**Comment by RaisinTen** [comment]
IIUC, the key combination does switch the language correctly but at the end, the `File` menu steals focus, so when you do `↑` `↓`, it toggles between the inner items of the `File` menu.

I'm not sure if this is a bug or an expected behaviour. Do you see the same behavior in non-electron applications too?

Since this reproduces in the basic electron app, I think it would be better if you could open an issue in [Electron's bug tracker](https://github.com/electron/electron/issues) with all of this info and cc `@zcbenz` to it because he worked on a potential fix and so he might have some more context. Also, please don't forget to share the issue link, so that we can follow the discussion there.

Let's also keep this issue open in parallel because we'll close this issue when we complete backporting the fix if any.

**Comment by madhead** [comment]
Done

**Comment by xym4uk** [comment]
i have same problem in latest postman from snap. any ideas how to fix it?
OS: linux mint 20.2

**Comment by RaisinTen** [comment]
@xym4uk this an upstream bug and the issue has been reported to Electron - https://github.com/electron/electron/issues/33101. I don't think there's much that can be done here until it gets fixed there, so let's continue the conversation there.

**Comment by RaisinTen** [comment]
Closing as per https://github.com/electron/electron/issues/33101#issuecomment-1322237881. Feel free to comment if anyone knows of an actionable item for us and I'll reopen this.
