### ISSUE TITLE
Unable to send request from Team workspace

### ISSUE THREAD

**Issue by elyaell** [a85/POSTMan-Chrome-Extension#7425]
**Describe the bug**
When connected on the team workspace, it became suddenly impossible to send request from the workspace : the response received is *404 not found* and there is no log about a request trying to find a non existing endpoint on the server. Moreover, using the same request with the same configuration on a personal workspace work just fine.

**Expected behavior**
I expect... Being able to send request from the team workspace ?

**Additional context**
No proxy configuration involved.
The bug has already occured to another teammate and has been resolved by a loggout of the account (already tried here, not working). 
Uninstalling/reinstalling postman didn't do the trick either.

**App information**
 - Native app
 - Postman v7.8.0
 - OS: Windows 10

**Comment by shamasis** [comment]
Can you check if your request uses a variable and if the same is missing in team workspace?

**Comment by elyaell** [comment]
It doesn't work even with the requests using no variables.

**Comment by preethammavin** [comment]
@FaithFeather  that does seem weird can you try sending a get request to `https://postman-echo.com/get?foo1=bar1&foo2=bar2` and check if you do get a response. Sending a request is independent of the workspace that you are sending it from. If it is not able to send the request can you shoot us a mail with the logs (found in top Bar View-> Developer-> view logs) and if possible a screen recording to help@getpostman.com so that we can take a closer look and sort it out for you.

**Comment by elyaell** [comment]
@preethammavin well, i tried again this morning and... It works now.
There has been no change in the environment or the requests, so i'm kind of awestruck.
I will keep in touch if it happens again.
Thanks
