### ISSUE TITLE
Cancel shares and return to free plan

### ISSUE THREAD

**Issue by 3579km** [a85/POSTMan-Chrome-Extension#7480]
Hello,

For now my collections is archived.
How can I cancel my shares for team and continue use and add collections without sharing it?

**Comment by sankalp0o** [comment]
Hey Igor,

You can go to https://go.postman.co/me/export and take an export of the data. You can re-import this data into a personal workspace so that it isn't shared. For existing shared collections which aren't archived, you should be able to "Remove" them from the team workspaces they are in.

Let me know if you face problems doing this, happy to guide you further. If you don't mind, I'm curious as to why you want to stop sharing your collections. Is it only because of archiving?
