### ISSUE TITLE
Extend Postman Monitor API to ingest results of externally run collections (e.g. via Newman)

### ISSUE THREAD

**Issue by matt-ball** [a85/POSTMan-Chrome-Extension#7490]
**Is your feature request related to a problem? Please describe.**
Whilst Newman's reporting function is highly customizable, it doesn't provide a method for feeding its results back into Postman's web dashboards.

Newman is often run on a scheduled basis whenever a Postman Monitor is not feasible: private networks, local testing, strict security requirements etc.

This is crucial to (at minimum) enable true collaboration when it comes to debugging and assessing service performance over time.

**Describe the solution you'd like**
Extend Postman's API to include an endpoint to ingest collection run data for an "externally run collection", this would mean that any collection run that occurs outside of Postman Monitors (typically Newman) can be tracked in the same dashboards.

_Or offer some method for importing external results in Postman Monitors._

Following the creation of such an endpoint, either Postman or the community would be able to create a Newman reporter which hooks up to this to feed through the data. Since both Newman and Postman Monitors use the same underlying runtime/collection execution flow, the resulting summary/report data should align.

**Comment by CarlosEduR** [comment]
@davidespihernandez is there anyone working on it? We'd appreciate to have a feature like this!

**Comment by davidespihernandez** [comment]
Hi, @CarlosEduR! 
Sorry for the delay in the response.
I was reviewing the pending GitHub issues and this one is really old... Currently, you have an alternative to Newman, the [Postman CLI](https://learning.postman.com/docs/postman-cli/postman-cli-overview/). If you check the Postman CLI documentation, you will see that the Postman CLI automatically sends the collection runs to Postman by default.
I think the easiest way would be to use the Postman CLI instead of Newman.
Please let me know if you have any other concerns.
