### ISSUE TITLE
Version mismatch detected error on launch

### ISSUE THREAD

**Issue by andalike** [a85/POSTMan-Chrome-Extension#7553]
OS: MAC Catalina
Version: Postman-osx-7.9.0

Issue:
1) On Opening Postman, Error prompts: 

"Look's like you've used a newer version of the postman app on this system. Please download the latest app and try again".

2) I am already using the latest app.

**Comment by andalike** [comment]
![Screenshot 2019-10-29 at 1 51 15 PM](https://user-images.githubusercontent.com/43137695/67749666-a3de5f80-fa53-11e9-9885-ac4a60d1b330.png)

**Comment by andalike** [comment]
![Screenshot 2019-10-29 at 1 55 02 PM](https://user-images.githubusercontent.com/43137695/67749724-bce71080-fa53-11e9-98d8-4c0892bcb43a.png)
![Screenshot 2019-10-29 at 1 55 06 PM](https://user-images.githubusercontent.com/43137695/67749725-bce71080-fa53-11e9-92ce-e73ac6cffe6d.png)

**Comment by cyrielle-hada** [comment]
The issue was reported to Product  Support as well. 

![image001](https://user-images.githubusercontent.com/47351631/67756678-50a7e500-fa32-11e9-886c-03e1c753686d.png)

**Relevant information**
The app is running on Windows 
Version 7.9.0

The application stopped working and threw the `Version mismatch detected` error before spinning for hours with no progress. 

Downloading version 7.9.0 from the [download page](https://www.getpostman.com/downloads/) leads to the same error on launch.  

**Error found in the logs** (available internally)
["main~makeSingleInstance: New Requester window instance not found"]
Error","message":"ENOENT: no such file or directory

**Comment by andalike** [comment]
Installed another version of postman by below

1) Renamed the folder "/Users/ankit/Library/Application Support/Postman" to "/Users/ankit/Library/Application Support/Postman.old".
2) Reinstalled Postman, it works now.

Issue:
1) The old data is gone
2) If i rename "Postman.old" to "Postman", the same "Version Mismatch" issue appears.

**Comment by nbstrat** [comment]
Having same issue as described by cyrielle-hada.

Relevant information
The app is running on Windows
Version 7.9.0

The application stopped working and threw the Version mismatch detected error before spinning for hours with no progress.

Downloading version 7.9.0 from the download page leads to the same error on the launch.

Attemping to uninstall the application and rename the AppData/Local/Postman directory results in the same error message.

**Comment by numaanashraf** [comment]
@andalike @nbstrat Could you try re-installing the latest version of Postman, while we investigate this further? `7.10.0` is available at https://www.getpostman.com/downloads/

**Comment by bikash019** [comment]
I had the same issue but solved when I reinstalled a newer version i.e  7.10 for window 10(64 bit).

**Comment by andalike** [comment]
@numaanashraf :
1)Tried with 7.10.0 on Catalina.
2) Postman app does not respond(open)
3) Renamed the folder "/Users/ankit/Library/Application Support/Postman" to "/Users/ankit/Library/Application Support/Postman.old".
4) Reinstalled Postman, v 7.10 works now


I find the issue is below.
1) If there is a existing folder in "/Users/ankit/Library/Application Support/Postman"( 7.9) then it errors out, Renaming the folder solves the issue.

**Comment by cyrielle-hada** [comment]
@numaanashraf issue was reported to be solved with the latest version 7.10.0

**Comment by kamalaknn** [comment]
Hey @andalike @bikash019 @nbstrat 

Can you give us some information on what led to this? Did you try manually downgrading to an older version(7.9) after the update(to 7.10), by downloading or opening the 7.9 version of Postman?

Can you share the logs from `View -> Developer -> Show logs in Finder` with us at `help@getpostman.com`?

Also, can you confirm that updating to 7.10 fixes the issue?

**Comment by ValGashi** [comment]
So I was just struggling through this error on my mac. I was able to fix it by first moving Postman to my applications folder and then opening the app (after uninstalling and reinstalling).

**Comment by andalike** [comment]
The Data was recovered? I Mean the Data in history was present? As per my deductions it was lost and no support update helped me.

    On Saturday, January 11, 2020, 2:37:01 AM GMT+5:30, ValGashi <notifications@github.com> wrote:  
 
 
So I was just struggling through this error on my mac. I was able to fix it by first moving Postman to my applications folder and then opening the app (after uninstalling and reinstalling).

**Comment by PRRB** [comment]
I had the same issue after doing a rollback/restore on my windows machine to a point before I updated Postman, after that I wasn't able to run/open Postman application and reinstalling it with the same version (latest version 7.14.0) produced the error mentioned in the title.

Renaming my **AppData\Roaming\Postman** directory to **Postman.old** as mentioned above also resolved the issue for me.

**Comment by davepatel95** [comment]
I'm still encountering this problem on my Mac, uninstalling/reinstalling is not solving it either. Any solutions?

**Comment by Arneoldenhave** [comment]
Same here, it suddenly started giving me this error. Removed and reinstalled latest version but the error persists.

**Comment by jeotte** [comment]
I'm encountering this as well, on mac with the latest version of postman

**Comment by stcalica** [comment]
Users reporting issue. One on Mac and another on Windows. 

Try clearing the cache to see if this resolves the issue. 

**PLEASE BACK UP DATA BEFORE DOING THIS!**
Instructions below. 
https://support.getpostman.com/hc/en-us/articles/360025359014

**Comment by SamuelDuke** [comment]
Postman help center has a guide for how to correct the issue for Mac, Windows, and Linux.

[https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-](url)

**Comment by thrixton** [comment]
> Postman help center has a guide for how to correct the issue for Mac, Windows, and Linux.
> 
> [https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-](url)

Correct link [How to resolve the Could not open Postman error?](https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error)

**Comment by stcalica** [comment]
@thrixton  PLEASE BACKUP DATA BEFORE DOING THIS! 
Same article as I posted above.

**Comment by Arneoldenhave** [comment]
I've tried to the steps, but error persists. Postman asks the user to put itself in the applications folder if you say yes it starts throwing this error. There might be an issue there

**Comment by Neeraj-Natu** [comment]
I faced this issue with postman version 7.18.1 I donot have admin rights to my work system so I cannot install the latest version (7.21.1). The app had automatic updates on and it got updated to the latest version after which i had uninstalled the postman app, now as currently the latest version is not available at my workplace. What can i do? Cause i am not able to go on an older version because of this issue and newer version is not available at workplace I am stuck.

**Comment by japavinayteja** [comment]
Go to C:\Users\{your user folder}\AppData\Local and delete the existing postman folder and then try to install postman

This works !!

Note: If Appdata folder is not visible , go to views and check the hidden items.. then it shows the AppData folder

**Comment by DannyDainton** [comment]
Hey All,

Is this something that folks are having an issue with on the latest version?

**Comment by cyrielle-hada** [comment]
@DannyDainton last time this issue was reported via the Support seemed to be in January 2020. 

The issue was resolved by [clearing the local data](https://support.getpostman.com/hc/en-us/articles/360025359014). Doesn't seem like the issue was reported since then.

**Comment by DannyDainton** [comment]
Thanks @cyrielle-hada - I'm going to close this one them and we can open it again if more issues are reported.

**Comment by PtrZjc** [comment]
This has just happened to me and looking for the solution, I've come to this issue. 
Downloaded Postman version is 7.34.0, Windows version x64

Deleting Postman folder as @vinayjapa suggested did not work and after each reinstall I got the message `Version mismatch detected` and then spinning electrons are stuck.
I hope I will solve it somehow, as I can't work without Postman.

Edit. It finally worked - as stated in troubleshooting link given above, it was also needed to delete Postman folder in `\AppData\Roaming`, not only `Local`

**Comment by katerinachinnappan** [comment]
I am trying to reinstall Postman v7.34.0, but running into the `version mismatch` issue. I cannot find the `Postman` folder in `/Users/{user}/Library/Application Support`. I uninstalled v7.35.0 completely and tried installing the older version, but nothing seems the work. The `Postman` folder does not appear under `Application Support` folder. Any tips?

**Comment by xk0der** [comment]
Hey @katerinachinnappan try the following
* Check for Postman app under `/Users/<username>/Applications/` (You can use the Finder app) - move the Postman app to the bin to uninstall it
* You have already checked `/Users/<username>/Library/Application Support` - but just make sure there is no `postman` folder in it
* Reboot your machine - this will clear any temporary files
* Now download 7.34.0 from here: https://www.postman.com/downloads/ and install to see if things work
* If you run into any error during the installation, try running the installer from the command-line
* If you run into any errors when launching the Postman app, try to launch it from the command-line as well
* Note down any errors/logs in the terminal and head over to https://www.postman.com/support to log a ticket with us

**Comment by katerinachinnappan** [comment]
@xk0der I was able to reinstall the older version after rebooting my laptop. Thanks for the help!

**Comment by fstugren** [comment]
I ran into this today trying to downgrade because the latest version of postman, which had been auto-upgraded on my machine (gotta disable that somehow) broke Oauth2.0. Postman doesn't clean up after it's uninstalled. This is a major source of frustration - when a program is uninstalled in windows any trace that it's been there should vanish, and if it leaves some data files behind they should certainly not prevent an older version from being installed.
Eventually after deleting both AppData\Local and AppData\Roaming I was able to install the older version - but now it prompts me to create a user name and password and there doesn't seem to be a way to bypass that. Create an account just so I can send http requests? I don't want to create yet another account and I really don't need to sync my test request parameters to any cloud, but if that's what you want me to do to use your software then ok.

**Comment by unleashit** [comment]
In my case I got the version mismatch after a routine update using Chocolately (Windows 10). It also leaves several processes running that I then have to manually kill.

I've tried uninstalling, then installing the latest version from the download site to no avail. I haven't yet deleted the files in appData as suggested above because I'm assuming I would lose my data. Also, I do not use a cloud account, and will simply stop using Postman if the new policy is to force you as @fstugren says above. I guess that means I'll have to switch to another http client which is a shame since I like Postman. Just don't need it phoning home and frankly even if the basic features are free to use, forcing users to use a cloud account (especially when for years you didn't) if true is bait and switch and pretty evil. Atlassian Source Tree did this, and... I'm probably not the only one that stopped using it at that point.

**Comment by unleashit** [comment]
This issue should be reopened as it's still a problem with the latest version

**Comment by pasdam** [comment]
I don't know if that helps anyone, but the way I solved it was:

1. Rename Postman application data folder, as described [here](https://support.postman.com/hc/en-us/articles/360025359014#h_b38048ee-6505-4f83-a0f0-5d4f51fcb6d5);
2. Open Postman, in order to recreate the folder;
3. Recover data using [Postman canary](https://www.getpostman.com/downloads/canary) as described [here](https://support.postman.com/hc/en-us/articles/360035071313-How-to-recover-my-data-).

Anyway I do think this is a bug in the app that should be investigated, mine is merely a workaround.

**Comment by unleashit** [comment]
Thanks, that actually does help if I'm able to recover my data!

That said, yes I too think it's a pretty glaring bug and don't see why the issue is closed. In my case, I didn't try to install an older version, I simply updated... although it was through Chocolatey, the Windows package manager so I suppose there's a small chance they could have accidentally uploaded an older/bad version. I haven't checked yet, since I've already made the switch to Jetbrains http client (which is the same as the VS Code plugin and it rocks!).

**Comment by danstis** [comment]
Same issue for me on 7.34.0 updated using Chocolatey. 
Noticed this in the `appdata/roaming/storage/settings.json`:
```
"lastKnownVersion": "7.35.0",
```
At this stage I'm just going to stop using and hope the next update causes it to start working again (due to a higher version number).

**Comment by pasdam** [comment]
I'm on MacOs and installed Postman using brew, so I don't think the issue is Chocolatey. I also noticed the `lastKnownVersion` value as @danstis, but even after removing only that files the issue still stand

**Comment by danstis** [comment]
After some further reading it turns out there was a version 7.35.0 that was published. This version had an issue and was revoked due to a bug.
It seems that we have installed this version before it was revoked (using Chocolatey or Brew) and therefore our config is uplevel. So when it rolled back to version 7.34.0, it's acting as designed and protecting our config.
The Postman team have stated (can't find the source again to link it here) that they will not re-issue version 7.35.0, rather they will replace it with version 7.36.0. 

So hopefully very soon this will all be sorted.

**Comment by compwron** [comment]
This is happening to me also 
osx 11.6 
postman 8.6.2 (latest on the website download link)
It is just hung forever on "preparing your workspaces" :(

**Comment by numaanashraf** [comment]
@compwron Could you try installing v8.12.4 from the website?

<img width="478" alt="Screenshot 2021-10-05 at 8 10 55 PM" src="https://user-images.githubusercontent.com/3295568/136045644-11231d14-211b-481f-a429-e3048631cfac.png">

**Comment by micaela-romero7** [comment]
I downloaded version 9.13.0 on my mac mojave 10.14.6 but giving me this error message when i try to open Postman app:
<img width="410" alt="Screen Shot 2022-02-19 at 7 37 31 PM" src="https://user-images.githubusercontent.com/99832248/154827462-e134713d-06ac-44ff-b0a1-30e858838479.png">

**Comment by formalist** [comment]
I'm getting the same error, trying to upgrade to version 10.10.3 

![image](https://user-images.githubusercontent.com/17143426/219126206-57c70dfd-4b7a-47e2-9eff-ac347ea430a4.png)

**Comment by numaanashraf** [comment]
@formalist Could you grab the logs from your device and send it to us at help@postman.com?

You can find the logs here - https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app#h_01G396RG1PATWM520KV442RCSJ

**Comment by formalist** [comment]
@numaanashraf I've sent the logs, thank you.

**Comment by Danielliudov** [comment]
Hello today my postman stopped working and i tried to reinstall it and i get the same error my machine is running macOS Monterey 12.6.3 with m1 max chip, and i also doesn't find the postman folder inside  ~/Library/Application Support to collect some logs.

**Comment by formalist** [comment]
Today I downloaded again the installer from postman site, installed and... it worked 🤷

**Comment by xyperam** [comment]
i deleted postman file at \AppData\Roaming\Postman and reinstall postman.... it worked

**Comment by ndr3wl33** [comment]
I have POSTMAN installed on a RDS that multiple users are using. One of the users is currently affected. I can't uninstall the POSTMAN which affects all other users every single time this issue occurs. is this a bug that hasn't been fixed since 2019?

**Comment by ronghao-em** [comment]
For macos, go to ~/Library/Application Support/Postman and delete it. after that reinstall postman
