### ISSUE TITLE
500 response on large collection POSTMAN API

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#7556]
filed on behalf of user. 

**Describe the bug**
> Using a POST request to the https://api.getpostman.com/collection endpoint. It is returning a 500 internal server error with a large collection. However, the Postman desktop app has no problem importing the collection. Something is different about the API.

**EXAMPLE REQUEST:**
```
import json
with open('/path/to/redacted-collection.json') as json_file:
    collection = json.load(json_file)
    response = requests.request(
        'POST', f'{base_url}/collections?workspace={WORKSPACE_ID}',
        headers = headers,
        json = { 'collection': collection }
    )
    response.raise_for_status()
```
**RESPONSE**: 
`requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.getpostman.com/collections?workspace=XXXXXX-XXXX-XXXXX-XXXX-XXXXXX`

**To Reproduce**
1. Generate a large collection 
2. create a `POST` request with the `collection.json` file to `https://api.getpostman.com/collections`
3. Returns a 500 Internal Server Error 

[redacted-large-collection.zip](https://github.com/postmanlabs/postman-app-support/files/3790531/redacted-large-collection.zip)

**Comment by jviotti** [comment]
Hi @stcalica, sorry for the late reply! I encountered this issue myself today and I have a PR that should fix it. In case it helps in the mean-time, it seems that the Postman API will reject any collection payload that exceeds 1 MB. It should work fine if its less than that. Hopefully this change lands in production soon.

**Comment by mynameistodd** [comment]
Hi @jviotti, I believe I'm running into this same issue, using the "Create a collection from a schema" request in the Postman Public workspace (forked locally).

Using the Postman Desktop application (macOS) to import an OAS schema as an API, and ticking the "Generate collection from imported APIs" works successfully. Retrieving that collection via the GET /collections/{id} reports that it is 2.53MB.

Did the PR you mention get merged? I'm suspecting the 1MB limit is the issue I'm encountering. Thanks!

**Comment by mynameistodd** [comment]
> Hi @jviotti, I believe I'm running into this same issue, using the "Create a collection from a schema" request in the Postman Public workspace (forked locally).
> 
> Using the Postman Desktop application (macOS) to import an OAS schema as an API, and ticking the "Generate collection from imported APIs" works successfully. Retrieving that collection via the GET /collections/{id} reports that it is 2.53MB.
> 
> Did the PR you mention get merged? I'm suspecting the 1MB limit is the issue I'm encountering. Thanks!

Update: Tested using a smaller schema, and generation of the collection via API works as expected, so further suspicion of the 1MB limit.

**Comment by davidespihernandez** [comment]
Hi! We also noticed that some update operations on collection (a PUT using the Postman API) fail when the payload size is huge (usually several MB). This happens because the backend takes too much time in processing that large payload, and ends up returning a timeout internally.

In order to provide a way to update huge collections, we have exposed a public API that allows users to update specific elements in a collection, like requests, responses, or folders. You can find more information and examples of that API here: https://www.postman.com/postman/workspace/postman-public-workspace/collection/16473433-f2f0cb8f-609d-443f-913c-9831187c326e?ctx=documentation

We are working on optimizations in the backend in order to process these big payloads faster, but there will always be a limitation for the maximum size of the payload. In case you receive a 500 error while performing a PUT or POST `/collections`, please try to use the collection individual items API if possible.

**Comment by davidespihernandez** [comment]
For future reference:
- The POST and PUT collection requests can fail if the payload is too big, mainly because of an internal timeout.
- In case you need to manipulate big collections, you can use the [collection items API](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-efeda219-66e1-474c-a83b-253d15723bf7).
- In addition, in November 2023 new APIs that allow to copy and move folders, requests, and responses between collections (or in the same collection) will be exposed publicly.
- We will continue improving the efficiency of the PUT and POST collection to be able to manage bigger payloads, but there will always be a limitation.
