### ISSUE TITLE
Generate code snippet doesn't include GraphQL data

### ISSUE THREAD

**Issue by software-opal** [a85/POSTMan-Chrome-Extension#7559]
**Describe the bug**
When trying to generate a code snippet for a request with a GraphQL body, the GraphQL body is not included in the generated code.

**To Reproduce**
1. Create a POST request with a GraphQL body(the content doesn't matter)
2. Click on `Code`
3. Note that the GraphQL body is absent from the code snippet.

**Expected behavior**
The code snippet should contain the GraphQL body

**Screenshots**
<img width="1121" alt="Screen Shot 2019-10-31 at 11 30 50 AM" src="https://user-images.githubusercontent.com/2038057/67903995-efb71300-fbd1-11e9-800d-baf18bf05728.png">
<img width="710" alt="Screen Shot 2019-10-31 at 11 31 28 AM" src="https://user-images.githubusercontent.com/2038057/67904021-ff365c00-fbd1-11e9-95b1-0c3225d5e222.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Version 7.9.0 (7.9.0)
 - OS: macOS Catalina 10.15 (19A603)

**Comment by software-opal** [comment]
This also affects the documentation view

**Comment by software-opal** [comment]
For those who need to access the request as-sent, you can use `nc -l 8080` and send the request to localhost:8080

**Comment by shreys7** [comment]
Hey, @software-opal In Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'New Code Generation Mode' flag enabled in Postman's global settings
This particular bug is fixed in new code generation mode. Here I have selected the body mode as GraphQL.
![Screenshot 2020-01-02 at 1 48 24 PM](https://user-images.githubusercontent.com/20665864/71657687-ef203180-2d66-11ea-915b-f87ef8102129.png)
![Screenshot 2020-01-02 at 1 48 35 PM](https://user-images.githubusercontent.com/20665864/71657688-efb8c800-2d66-11ea-9b36-97683b0676b4.png)
