### ISSUE TITLE
OAuth2 authorization not working when backend uses cookies with SameSite=None

### ISSUE THREAD

**Issue by piether** [a85/POSTMan-Chrome-Extension#7592]
**Describe the bug**
Cookies with SameSite=None are not sent on subsequent requests in the OAuth2.0 authorization pop-up

**To Reproduce**
1. Create a new request
2. Go to Authorization tab
3. Choose OAuth 2.0 as type
4. Click 'Get New Access Token'
5. Fill in the required fields. I'm using the Authorization Code flow but I don't think it matters.
6. Postman makes a request to the /auth endpoint
7. The /auth endpoint redirects to an interaction url
8. The interaction url sets a session cookie **with SameSite=None** and redirects to the login page
9. The login page returns an error because the session cookie is not sent in this request

**Expected behavior**
A token is returned. Whether the cookie is specified with SameSite=None or not should not have any impact.

**App information (please complete the following information):**
 - Native App
 - 7.10.0
 - OS: Ubuntu 18.04.3 LTS

**Additional context**

I have verified that this is the problem by using mitmproxy to modify the Set-Cookie header `mitmproxy --replacements "/~s/ samesite=none;/"`

**Comment by vikiCoder** [comment]
Hi, thanks for reporting the bug. We have verified the bug and will try to fix this as soon as possible. I'll update the thread once it is fixed.

**Comment by rustichowie** [comment]
Any updates on this bug? We are experiencing the same thing, and it looks like the problem also happens in other REST debugging tools based on Electron (Insomnia).

**Comment by devployment** [comment]
According to `navigator.appVersion.match(/.*Chrome\/([0-9\.]+)/)[1]` Postman is using embedded Chrome version `66.0.3359.181`. That's fairly old.

According to `process.versions.electron`, the Electron version `3.1.8-postman.5`  seems to be kind of outdated as well, given `3.1.8` is the Electron version. 

According to [this document](https://www.chromium.org/updates/same-site/incompatible-clients), Chrome 66 is incompatible with `SameSite=None` cookies.

So, looks like Postman should update the Electron version being used to fix this problem.

Maybe somebody "official" could elaborate a bit on this topic.

**Comment by Eugeneator** [comment]
@vikiCoder Any updates on that?

**Comment by Eugeneator** [comment]
Is there any workaround to solve the problem?

**Comment by jfcere** [comment]
Using AspNet Core 3.1, I've implemented my workaround following Microsoft documentation: [Work with SameSite cookies in ASP.NET Core - Supporting older browsers](https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1#supporting-older-browsers).

Basically, I just configured Cookie Policy to detect Postman in `User-Agent` request header and set `SameSite=Lax` to be able to retrieve token successfully.

**Startup**

```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseCookiePolicy();
    app.UseAuthentication();
}

public void ConfigureServices(IServiceCollection services)
{
    services.ConfigureCookiePolicy();
}
```

**ServiceCollectionExtensions**

```csharp
public static class ServiceCollectionExtensions
{
    public static IServiceCollection ConfigureCookiePolicy(this IServiceCollection services)
    {
        services.Configure<CookiePolicyOptions>(
            options =>
            {
                options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
                options.OnAppendCookie = cookieContext => CheckSameSite(cookieContext.Context, cookieContext.CookieOptions);
                options.OnDeleteCookie = cookieContext => CheckSameSite(cookieContext.Context, cookieContext.CookieOptions);
            });

        return services;
    }

    private static void CheckSameSite(HttpContext httpContext, CookieOptions options)
    {
        if (options.SameSite == SameSiteMode.None)
        {
            var userAgent = httpContext.Request.Headers["User-Agent"].ToString();

            if (userAgent.Contains("Postman/7"))
            {
                options.SameSite = SameSiteMode.Lax;
            }
        }
    }
}
```

**Comment by likemike91** [comment]
> Using AspNet Core 3.1, I've implemented my workaround following Microsoft documentation: [Work with SameSite cookies in ASP.NET Core - Supporting older browsers](https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1#supporting-older-browsers).
> 
> Basically, I just configured Cookie Policy to detect Postman in `User-Agent` request header and set `SameSite=Lax` to be able to retrieve token successfully.


Isn't the Postman User-Agent header = "PostmanRuntime/7..."?
![image](https://user-images.githubusercontent.com/11736645/77202918-8b98db00-6aef-11ea-99ae-49d8bdf3f503.png)

**Comment by jfcere** [comment]
Maybe your scenario is different... this is what I have in the `User-Agent` request header on Windows 10 with Postman v7.20.1 using pop-up window to enter credentials on our Identity Server.

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Postman/7.20.1 Chrome/66.0.3359.181 Electron/3.1.8-postman.5 Safari/537.36
```

But I guess the matching condition could validate both...

```csharp
if (userAgent.Contains("Postman/7") || userAgent.Contains("PostmanRuntime/7"))
{
    options.SameSite = SameSiteMode.Lax;
}
```

**Comment by cpwood** [comment]
Lost several hours of my life to this as our support team had been unable to connect to our APIs via Postman.

Given we had to make changes for `SameSite` cookies by the beginning of February 2020 and Chrome 80, it means Postman is now two-months (at least) behind the curve in terms of browser security and expected interoperability standards. I find that _deeply_ troubling as a paying user.

I've had to add hacky code into our auth server to say "if the user-agent is Postman, don't apply `SameSite` attributes to the cookie" just to keep support operations going.

In our case, simply being able to authenticate via our _normal_ web browser would've mitigated the problem, however, Postman insists on using its _own_ browser window for OAuth2 implicit grant. Why not launch the ordinary browser and then redirect to a Postman-hosted `localhost` web address to complete the auth process?

**Comment by ptncafe** [comment]
`  
app.UseCookiePolicy(new CookiePolicyOptions
            {
                MinimumSameSitePolicy = SameSiteMode.Lax,
            });
`
 Did you try it? It work with me

**Comment by vikiCoder** [comment]
Hi, we are currently working on providing an option to authenticate via the system's default web browser. It will be out soon. It will solve this problem. We will update here once the feature is released.

**Comment by vikiCoder** [comment]
Hi everyone,

We've added an option in OAuth2 that allows you to authenticate using your system's default browser while generating OAuth 2.0 token.

To use this feature, select `OAuth 2.0` under `Authorization` tab and open `Get New Access Token` dialog box. You'll see a new checkbox `Authorize using browser` when `Authorization code` or `Implicit` grant type is selected. Selecting this option will allow you to use your external browser for authentication instead of using Postman's built-in browser.

However, selecting this option will automatically use the callback URL `https://oauth.pstmn.io/v1/callback`. You can't change this callback URL. This is necessary to return the generated token information back to the Postman app on successful authentication. So you'll have to whitelist this URL to be used as callback in your respective OAuth provider if required.

You can refer to [this link in our learning center](https://learning.postman.com/docs/postman/sending-api-requests/authorization/#requesting-an-oauth-20-token) for more details about generating OAuth 2.0 token. Here is a screenshot showing off this new feature. Please update to the latest Postman app (v7.24.0) and check it out. Let us know if you are still facing any issues related to this. Any feedbacks are welcome 🙂

![Capture](https://user-images.githubusercontent.com/16588032/81491083-6d598b00-92a7-11ea-937e-8b80f1f1cee5.PNG)

**Comment by cpwood** [comment]
This isn't quite working for me and I suspect others will run into similar issues.

Here's how the redirect link looks when I've logged in successfully:

https://oauth.pstmn.io/v1/callback#access_token=eyJhbGci...abc&token_type=bearer&xsrf_token=&state=

Note that the access token is included after a `#` and not a `?`. This is done deliberately so that the access token isn't sent in the `GET` for `https://oauth.pstmn.io/v1/callback` and doesn't leave the browser, which is a common technique used within Single Page Applications (SPAs).

Because it isn't being sent in a *querystring*, the authentication process in Postman isn't completing.

Ideally, some Javascript running on the `oauth.pstmn.io` web page should send those details back to your systems if they're spotted in the hash part of the URL and not the querystring. You could just do a `location.href = location.href.replace('#', '?')` tbh.

Could you look at making this change?

**Comment by cpwood** [comment]
FYI - I thought this wasn't working until I realised that my Chrome pop-up blocker was borking the process. You might want to tell people to keep an eye out for any pop-up warnings.

**Comment by arlemi** [comment]
@cpwood Thanks for letting us know, I've created an issue on our docs repo. :)
