### ISSUE TITLE
{{guid}} generated twice during an api call

### ISSUE THREAD

**Issue by saurabh-jas** [a85/POSTMan-Chrome-Extension#7618]
**Describe the bug**
{{guid}} generates a new guid value in code section everytime it is clicked. 
Suppose you send an API request with a header name 'unique-id' and value {{guid}}. 
Now if initially when the request is sent, the guid is say xxx-yyy-zzz-aaa-bbb . Now after sending the request, if I want to check which unique token is used so I'll click on the code button. 
But when I do so, it regenerates the guid and my previous guid is lost. It is fine in scenarios where the unique guid is returned as part of response headers. 
But in other scenarios it becomes difficult.

**To Reproduce**
1) Send a sample api request
2) Add a unique header with value as {{guid}}
3) To check the sent {{guid}}, click on code button

**Expected behavior**
{{guid}} value in code section should be retained to the initial value of the sent {{guid}}

***App information (please complete the following information):**
 - App Type Chrome app
 - Postman Version 7.1.1
 - OS: Windows 2012 R2

**Additional context**
I understand it happens due to behavior of the dynamic variable but creates a lot of confusion.

**Comment by xk0der** [comment]
@saurabh19911 - You should utilize Postman's console to view and validate request values and headers for a _sent_ request.
Reference: https://learning.getpostman.com/docs/postman/sending-api-requests/debugging-and-logs/#network-calls-with-postman-console

The [code tab](https://learning.getpostman.com/docs/postman/sending-api-requests/generate-code-snippets/) is to generate executable code in different languages/framework - HTTP is the default one selected. Since the variable `{{$guid}}` will not auto-resolve in for these languages/framework, Postman resolves any dynamic variables when generating the code, which is the correct behaviour.
