### ISSUE TITLE
Cannot encode a plus sign  in generated example code

### ISSUE THREAD

**Issue by arusahni** [a85/POSTMan-Chrome-Extension#7646]
**Describe the bug**

I have a code example that has a `x-www-form-urlencoded` value with a plus sign. I'd like to escape this as a `%2B` instead of having it treated as a space or `%20`.  However, if I encode it in Postman, the rendered API documentation's cURL example escapes the `%` sign, resulting in `%252B`.

**To Reproduce**
1. Create an example code snippet
2. Select `x-www-form-urlencoded` in the `Body` tab.
3. Add a key/value pair with a value of `%2B`
4. Render the documentation
5. Observe the generated cURL docs display this as `%252B`

**Expected behavior**

The generated docs preserve the `%2B`

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

In Postman

![Screen Shot 2019-11-14 at 8 58 45 AM](https://user-images.githubusercontent.com/139487/68863260-fd35c800-06bc-11ea-9129-e12260f539f7.png)

In the generated example doc

![Screen Shot 2019-11-14 at 8 53 40 AM](https://user-images.githubusercontent.com/139487/68862957-62d58480-06bc-11ea-8fc6-3624e6111546.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.11.0
 - OS: macOS Mojave

**Additional context**

This appears tangentially related to #4555, but that ticket doesn't appear to focus on the issue with the generated API docs.

It'd be great to have an option to mark a field as "safe", and have the API generator just pass the value through.

**Comment by umeshp7** [comment]
@arusahni 
Hey thank you for reaching out! I tried reproducing this in the latest versions of documentation and the postman app, but I was not able to reproduce this. Could you please verify if the issue still persists for you? 
Since Nov 2019 we have made a bunch of improvements and bug fixes to the code generation. 
This is a screenshot from documentation. 
<img width="479" alt="Screenshot 2020-11-13 at 11 50 09 AM" src="https://user-images.githubusercontent.com/31915995/99036113-18286a00-25a7-11eb-8bda-fb8c6a677b75.png">

**Comment by arusahni** [comment]
@umeshp7 I can confirm that this is now fixed!
