### ISSUE TITLE
newly replaced IndexedDB files error on startup.

### ISSUE THREAD

**Issue by kings38jk** [a85/POSTMan-Chrome-Extension#7653]
Why cant I use the IndexedDB files in my new win comp...?????? being going at it for hours, even tried the new canary postman and replaced the IndexedDB folder with my old files, but same shiet.."contact help@postman.com" work on this. Kindly.

**Comment by kamalaknn** [comment]
Hey @kings38jk,

The offline data stored in Postman has many other components outside of indexedDB. There are also a lot of system-dependent configurations that go into storage systems. We do not recommend copying over internal storage files.

If you are looking to move data from one installation to another we recommend 

1. Signing up to a Postman account which will sync your data across all devices/installations
2. If you are limited by any factor that prevents you from signing up, you can open up `Settings > Data` to export the data from your previous installation and import it into your new installation.

I'm closing this issue since copying over indexedDB files is not a supported flow from Postman.
