### ISSUE TITLE
Ask for workspace before importing collection from Run in Postman button

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7654]
**Is your feature request related to a problem? Please describe.**
Currently for users on the free plan, if they import collections with requests that may exceed the sharing limit, there is no warning and the older Collections just get archived.

_References:_
* https://www.getpostman.com/pricing
* https://learning.getpostman.com/docs/postman/launching-postman/collaboration/#usage-limit-for-free-users

**Describe the solution you'd like**
User should be warned indicating that the Collection that they are importing will put them over the limit and will trigger archiving of collections.

At this stage, the UI may also provide a way to select one of the Personal workspaces - so that the user may continue to import into their personal workspace.

**Describe alternatives you've considered**
None available.

**Additional context**
Logged by Postman.
I thought of this after one of our users found the current flow confusing as every time they re-imported their archived collections, the older ones would get re-archived.

**Comment by sankalp0o** [comment]
Thanks Amit! 
We understand this experience can be jarring. For the time being, users can import collections in personal workspaces to avoid archiving other collections. We're considering allowing workspace selection at the time of import but don't have an ETA. Will keep you updated!

**Comment by JasonTheAdams** [comment]
I just ran into this when trying to import a collection from PayPal — which is a huge collection. It was so big it didn't even work, but it also managed to completely remove all of my other collections. No warning or anything, just poof, all of the collections I've built over time are gone. It doesn't even give you a clear idea of how to recover from this, or warn you that "hey, if you do this you'll loose everything, sound good?"

I totally understand the 25 limit, but saying that the ["easiest way to recover"](https://blog.postman.com/free-teams-faq/) everything is to upgrade just feels like a dark pattern at this point. A warning that says, "this pushes you past your limit, to add them please upgrade" is completely acceptable. Erasing a bunch of stuff and saying, "Want it back? Easiest way is to upgrade!" feels very underhanded and dishonest.

I know that's not the ethos of the Postman team. Please make this change. Not only for ethical reasons, but also so that you don't lose potential revenue and reputation from frustrated customers who feel cornered.

**Comment by arlemi** [comment]
@JasonTheAdams You should have been getting two different warnings before any of your collections get archived, 1 yellow bar warning you about approaching the 25 request limit, then a red bar warning letting you know you've passed the limit and that your collections may get archived if you keep importing things. Did you not get any of these? 

Also, were you able to recover your data correctly?

**Comment by JasonTheAdams** [comment]
@arlemi Eventually, I did figure out how to recover the collections. Thanks for asking!

Keep in mind that in my example I was importing a collection that went far beyond the limit in and of itself, so I never saw any kind of approaching warning. I went from 8-9 collections to 40-50 by importing one collection. That's why I consider it important to provide a warning if the act of importing will push the user pas the limit. I had no idea there even was a limit until after I already had stuff automatically archived. From a UX standpoint it just suddenly felt like I lost everything.

**Comment by celestebancos** [comment]
> You should have been getting two different warnings before any of your collections get archived, 1 yellow bar warning you about approaching the 25 request limit, then a red bar warning letting you know you've passed the limit and that your collections may get archived if you keep importing things. Did you not get any of these?

In my case, I got the warning but didn't realize that archiving would be so difficult of a process to reverse. I was only sharing for someone to take a quick look at my code; not intending for it to be a long-term thing. I figured if it got archived, I could just unshare the collection and get it right back. But now I'm waiting for a download that I'll then have to figure out how to reinstall. 

The "Archive" wording does not clearly communicate what's going to happen.

I also agree with @JasonTheAdams that getting a message saying "You can't add this new thing unless you upgrade" is much better than "We took your stuff — better upgrade if you want it back without any hassle." I feel a loss of trust in Postman — what  other pitfalls might there be that would cause me to inadvertently lose my work?

**Comment by arlemi** [comment]
@celestebancos Thanks for the feedback. We offer the ability to go over that limit for a short amount of time so people are able to try the collaboration features without having to pay money up-front. Kind of a free trial but you don't even have to give your card number to enable it. We can do better on the UX side of thing though, I've passed it along to the product team. 🙂

**Comment by celestebancos** [comment]
Thank you, @arlemi. In my case the benefit of getting to try out the feature for free did not outweigh the hassle of spending over an hour figuring out how to get my main project back into working order. 

A transparent warning would be "Since you're over the limit, we might delete your project and make you restore from backup."  The "archive" term did not communicate that for me — I assumed I could un-archive it with just a few clicks and all I'd lose was the ability to share it. 

Do you know if there's any way to get rid of the little message that says "Some collections were archived because you've reached the shared requests limits." ?  I click the x to close it but every time I launch Postman it's back again. I've already brought my collection back to life so it just serves as a reminder of this bad experience which I'd rather just put behind me. (That's why I'm back to comment — I figure I might as well channel the bad feelings into trying to make things better for everyone!) 

That would be another recommendation for the product team: don't keep reminding your users of the bad experience once the problem's been solved.

**Comment by arlemi** [comment]
@celestebancos Sorry for the (very) late reply! Did you manage to get rid of your archived collection? If not, this needs to be achieved through the Postman API, here's a collection that shows you how to achieve that: https://documenter.getpostman.com/view/6034746/SzYgPu4t

We have some improvements in the work for archival flow but I cannot give an ETA yet unfortunately.

**Comment by gitThingsDone** [comment]
@xk0der Happy to share that we have introduced the ability to select a workspace while importing a collection using Run In Postman. This is available in the latest version of the Postman App https://www.postman.com/downloads/
