### ISSUE TITLE
Enterprise SSO sign-in hangs.

### ISSUE THREAD

**Issue by senojj** [a85/POSTMan-Chrome-Extension#7668]
**Describe the bug**
When attempting to sign in as an enterprise user, the application hangs on a loading screen after selecting the configured SSO authentication method. 
- This can be reproduced every time a user attempts to sign in via the SSO authentication method.
- This is verified to happen for users that have previously signed in via SSO method; it is unknown if this happens for new users who have never signed in using the SSO authentication method.

**To Reproduce**
1. Go to 'Sign in page'
2. Click on 'Enterprise user? Sign in here'
3. Enter your team domain
4. Click continue
5. Click on configured SSO authentication method
6. Observe the indefinitely spinning logo

**Expected behavior**
I expected to be prompted for credentials for my SSO provider.

**Screenshots**
![image](https://user-images.githubusercontent.com/5853354/69094271-0d7fd700-0a1e-11ea-9951-409d1cb16129.png)

![image](https://user-images.githubusercontent.com/5853354/69094183-e45f4680-0a1d-11ea-95a9-1fb9c86b37ef.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.11.0
 - OS: Linux Ubuntu 18.04.3, OSX Mojave

**Comment by jjware** [comment]
I have verified that this issue is network related. However, it may be a good idea to introduce a timeout here with appropriate messaging.

**Comment by senojj** [comment]
I have confirmed that this does not happen on Windows and appears to be specific to *nix distributions.

**Comment by jjware** [comment]
This issue can be resolved by adding the SSO provider URL to my hosts file, indicating a relation to DNS.

**Comment by jjware** [comment]
When on an internet connection, I have no problem signing-in to the Postman native app through our SSO provider... However, as soon as I get on our organization's internal network, I am no longer able to get passed the loading screen pictured in the original issue statement. 

I believe this is related to DNS. I have two DNS servers listed by systemd-resolve, and am able to ping both of those servers successfully from an internet connection... However, once on our organization's internal network, the first listed DNS server becomes unreachable, and only the second is reachable.

It is my understanding that Unix resolves names by trying each DNS server configured, sequentially. Is it possible that the Postman app is getting stuck on the first server in the list due to it not being reachable?

**Comment by elssar** [comment]
@jjware is there a firewall or proxy that could be blocking requests from the Postman app to your Identity Provider? We usually see this behavior when the app is unable to connect to the Identity Provider.
It would help if you could send the [app logs](https://learning.getpostman.com/docs/postman/launching-postman/troubleshooting-inapp/) to us via help@gepostman.com.

In the mean time you can try using the browser to login to the app on Linux platforms.
![postman-browser-login-for-app](https://user-images.githubusercontent.com/1042301/71239303-37356200-232c-11ea-8621-8dedd12be207.png)

**Comment by ArjunSingh-PM** [comment]
Closing this ticket for now as we have not heard back from the user.

@jjware Feel free to re-open this ticket if you are still experiencing this issue.
