### ISSUE TITLE
Chrome 66 embedded browser for Postman.co login blocked due to security concerns

### ISSUE THREAD

**Issue by alexwaddell** [a85/POSTMan-Chrome-Extension#7672]
The embedded Chrome browser that is used to signing to Postman.co is using Chrome v66 - as this has significant security issues, this version and all others up to v77 are blocked at one of our clients, which means we cannot sign into Postman.co

Could someone please advise if/when the embedded browser will be updated to Chrome v78 or newer?

**Comment by numaanashraf** [comment]
Thanks for reporting this @alexwaddelluk. We are working on moving our authentication flows to the local installed browser and this change is scheduled to be available on an upcoming app version.

**Comment by alexwaddell** [comment]
Thanks @numaanashraf - do you have any timeline for this updated version as it is currently a blocker for my client!

**Comment by choowie** [comment]
This problem is blocking quite a few people. Version 66 was released in April 2018 and one year later, some serious security issues have been fixed in the latest version. Version 78 of Chrome fixes a vulnerability rated 9 out of 10 on the CVE scale.

Most companies are blocking older browsers and even Google complains when I authenticate with my google account "you are trying to sign in from a browser or app that doesn't allow us to keep you account secure".

When will a fix be released?

**Comment by yjjnls** [comment]
same problem on chrome78, is it solved?

**Comment by elssar** [comment]
We’ve enabled a new auth option which will allow you to sign in via your browser. Could you try this out and let us know if it works for you?
![browser-based-login-link](https://user-images.githubusercontent.com/1042301/70425730-b78bd580-1a97-11ea-993b-6064b65933c2.png)

**Comment by yjjnls** [comment]
@elssar It works, thank you.
