### ISSUE TITLE
Second menu selector doesn't work in Code snippets

### ISSUE THREAD

**Issue by tomjoht** [a85/POSTMan-Chrome-Extension#7675]
**Describe the bug**
When I try to click the arrow to see the second-level menu for code snippets, such as Javascript > jQuery, the second level isn't appearing. See https://www.screencast.com/t/lLrQpEz3

**To Reproduce**
1. Click Code.
2. Click the JavaScript option.
3. Click the arrow to expand the second level. The arrow doesn't show the submenu.

**Expected behavior**
Second level should appear.

**Screenshots**
https://www.screencast.com/t/lLrQpEz3

**App information (please complete the following information):**
Mac OSX

**Additional context**

**Comment by tomjoht** [comment]
I noticed that the submenu becomes visible if I scroll right at the bottom: https://www.screencast.com/t/R6L84vLcWiI. It looks like the fix would just involve widening that drop-down column or something.

**Comment by shreys7** [comment]
Hey, @tomjoht The list is present there but it has become x-scrollable. You need to scroll on the x-axis to get the nested list for the javascript snippets.
We are working on fixing this. Meanwhile, an alternative solution can be to switch the App to full-screen mode, and then the nested list would be displayed on hovering.

**Comment by umeshp7** [comment]
@tomjoht 
In the latest versions of postman we have removed this modal to add a new modal with our in-house code generators. These have great customization and there is support for a few more languages. We also have an open source project for the same and you can find it [here](https://github.com/postmanlabs/postman-code-generators). 

<img width="878" alt="Screenshot 2020-12-19 at 6 17 03 PM" src="https://user-images.githubusercontent.com/31915995/102689735-683dc080-4226-11eb-89ee-bb8a69169d17.png">


Closing this issue for now since the UI in question doesn't exist in the recent versions of the app. Feel free to open a new ticket if you face any issues with the new UI and code snippets.
