### ISSUE TITLE
Selecting all in the Postman Console only copies visible contents of Window

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7685]
**Describe the bug**
First reported here: https://community.getpostman.com/t/copy-from-console-broken-only-partial-output-on-clipboard/9110/3

When selecting all (command + A) of the contents of the Postman Console and copying, only the contents visible in the window (plus a little extra) are copied. If the console contains a lot of log messages, this mean a lot is missed.

This is problematic if a user needs to copy the content of the Postman Console, and paste it into (e.g.) a text editing app.

**To Reproduce**
1. Open Postman Console (command + option + C)
2. Populate the Console with more log messages than fit on the screen (i.e. send a bunch of requests)
3. Click anywhere on the Console and select all (command + A, on MAC), then copy (command + C, on Mac)
4. Paste this into a text editor.
5. Notice that what is pasted is only a small subset of the total Console logs.

**Expected behavior**
Selecting all + copying grabs the entire contents of the console.

Ideally, I think we should have a button for Copy all, or a button to write the raw contents of the console to a file.

**Screenshots**
![2019-11-20 10_54_24-](https://user-images.githubusercontent.com/43283131/69263146-94959200-0b79-11ea-877b-b4fb5ac34c1e.png)
![2019-11-20 10_54_54-](https://user-images.githubusercontent.com/43283131/69263148-94959200-0b79-11ea-8f06-04996214eabe.png)

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.11.0
 - OS: MacOS Mojave 10.14.6, Windows 10

**Additional context**

**Comment by kanmaytacker** [comment]
Any updates on this?

**Comment by Simon0362** [comment]
Another "any updates?"

**Comment by kkalpakchyan** [comment]
any idea when this will be fixed??

**Comment by keeleyt83** [comment]
I'd also like to see this fixed. Maybe this wasn't a use case you considered for the console, but I would use the runner to produce delimited output for quick and dirty reporting based on REST apis. I'd really like to see this come back.

**Comment by Super-Net-Ops** [comment]
I’ve come up with an ugly workaround.

In the CSS, change:

```
.console-container {
    display: flex;
    flex-direction: column;
    height: 100%;
}
```
to

```
.console-container {
    display: flex;
    flex-direction: column;
    height: 100000px;
}
```
Adjust the height as necessary to capture all of the console output.

**Comment by kartiknagappa** [comment]
Dear Postman peeps,

// Value prop
What you've created is a great tool - it makes it super easy build and share API collections with others. I share my collections with TAMs and Customer Support because it's far easier for them to run a Postman collection than a python script. I've written small tools (employing the Tests portion) that help them be proactive in their role and diagnose/solve customer issues.

// Pain-point
Many of these use cases require them to be able to copy the console output to share with others via email, Slack, or other means. However, being unable to copy this console output reliably in Postman means that I might need to consider using a different tool.

// Workarounds
It looks like there are tons of articles on the internet about ways to address the issue of being able to save Postman console output. Just imagine how many people are wasting valuable time trying to find a workaround - mucking with the CSS, doing stuff with newman, etc.

// My 2cents
The workarounds do not scale well and I don't want to become the guy who is debugging the workaround for everyone. The point is to increase value, not pain.

Please fix this issue before I decide to switch to another tool. Thanks!

**Basic use cases**

1. When I **select-all** (e.g. cmd+A) and **copy** the text in the console, and then paste that copied text in another (external to Postman) document/application, then I can see that all the text from the Postman console is now present in the document/application.

2. When I first filter/search for text in the console, and then perform a select-all/copy/paste, then only the filtered text (matching search criteria) is present in the document/application.

**Comment by kartiknagappa** [comment]
> I’ve come up with an ugly workaround.
> 
> In the CSS, change:
> 
> ```
> .console-container {
>     display: flex;
>     flex-direction: column;
>     height: 100%;
> }
> ```
> 
> to
> 
> ```
> .console-container {
>     display: flex;
>     flex-direction: column;
>     height: 100000px;
> }
> ```
> 
> Adjust the height as necessary to capture all of the console output.

@Super-Net-Ops - you don't need to muck with CSS. If the focus is on the Postman console, then you can zoom out (e.g. `cmd` + `-`) as needed.

**Comment by keeleyt83** [comment]
@saswatds just saw you added the "feature" tag to this back in 2020. As being able to copy the console was working prior to 7.11.0, I don't see how it could be considered a feature. This is a bug.

Its 2021, version 8 has been released, and this is still unresolved. Could we get an update on where this bug stands?

**Comment by Super-Net-Ops** [comment]
> @saswatds just saw you added the "feature" tag to this back in 2020. As being able to copy the console was working prior to 7.11.0, I don't see how it could be considered a feature. This is a bug.
> 
> Its 2021, version 8 has been released, and this is still unresolved. Could we get an update on where this bug stands?

I agree that this is a bug and should be fixed, but a much, much better option would be to support writing the console output to a text file.

**Comment by Super-Net-Ops** [comment]
> > I’ve come up with an ugly workaround.
> > In the CSS, change:
> > ```
> > .console-container {
> >     display: flex;
> >     flex-direction: column;
> >     height: 100%;
> > }
> > ```
> > 
> > 
> > to
> > ```
> > .console-container {
> >     display: flex;
> >     flex-direction: column;
> >     height: 100000px;
> > }
> > ```
> > 
> > 
> > Adjust the height as necessary to capture all of the console output.
> 
> @Super-Net-Ops - you don't need to muck with CSS. If the focus is on the Postman console, then you can zoom out (e.g. `cmd` + `-`) as needed.

To a degree, but if there is too much information you can't zoom out enough to capture all of it.

**Comment by kumar-nitish** [comment]
Copy all logs to clipboard is now available in console window and it works as expected

 ![copy-all-logs](https://user-images.githubusercontent.com/3117614/229599528-7e06ee70-bb65-4278-b507-5a56337806aa.png)
