### ISSUE TITLE
Datadog Integration not working for users on the EU site

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#7701]
Hi,

Currently, the Datadog integration with the domain **datadog.eu** doesn't work as postman sends data only to the US site which is **datadog.com**. However, Datadog has different API hosts for users using the EU site versus the US site and thus requested for this feature to be added in postman.

**Comment by maxpastor** [comment]
This issue is related to all of the European users wanting to connect Postman and Datadog. 
Here's our example at Tactill. 
We implemented API into Postman to have nice documentation and monitors. 
But, Datadog is our main data and monitoring tool, as we print dashboards on TVs in the office and investigate errors with their tools. 
With that in mind, we don't really go check our Postman monitors since Datadog is what we have near us all the time. 
Missing this information inside our dashboard can lead to an unseen issue or unseen downtime. 

So by adding the other domain **datadog.eu** to your integration, you would solve this issue and let us enjoy our monitors onto our dashboards.

**Comment by chughmayank** [comment]
@Ramya-From-Postman   - the issue has been resolved and is available on live now. Please feel free to reopen in case you find any other issue here
