### ISSUE TITLE
Can't create mock servers on MacOS 10.14.6 with Postman 7.12.0

### ISSUE THREAD

**Issue by PedroBernils** [a85/POSTMan-Chrome-Extension#7704]
Having basically the same issue described [here](https://github.com/postmanlabs/postman-app-support/issues/4781), also getting the "Error occurred while fetching versions" message, except I'm on MacOS Mojave instead and using a considerably later version than the one mentioned.

Here's a screenshot of what happens:
<img width="2032" alt="Screen Shot 2019-11-26 at 19 41 56" src="https://user-images.githubusercontent.com/3812923/69678776-44d92e00-1085-11ea-98f3-9077ed538d1d.png">

**Comment by AmanDhembla** [comment]
Hey @PedroBernils, Thanks for taking your time and reporting this issue.
This issue has already been fixed in Postman app version 7.18 and change is available in all the newer versions of the app after that. So can you please update your app and report back if it gets fixed for you or if you still face a problem? 
Same issue was closed here https://github.com/postmanlabs/postman-app-support/issues/7751

**Comment by vvs11** [comment]
@PedroBernils closing this issue. Please let us know if you're still facing this problem
