### ISSUE TITLE
Set an environment variable as an array through the Pre-request Script method, and reference the variable when requesting, but not the array

### ISSUE THREAD

**Issue by luyao1991** [a85/POSTMan-Chrome-Extension#7713]
**Describe the bug**
Set an environment variable as an array through the set method, and reference the variable when requesting, but not the array.

**To Reproduce**
Set URL first.(url=https://postman-echo.com/post,method=POST,data-->"method=POST&param={{param}}"
1. Go to Pre-request Script,edit
`pm.environment.set("param", ["a","b"]);`
2. Click on Send
3. param in response is not an array
`"form": {
        "method": "POST",
        "param": "a,b"
    },`

**Expected behavior**
param in response is an array
`"form": {
        "method": "POST",
        "param": ["a","b"]
    },`

**Screenshots**
![image](https://user-images.githubusercontent.com/35060336/69776234-554cee00-11d6-11ea-9364-438bc435d879.png)
![image](https://user-images.githubusercontent.com/35060336/69776239-5e3dbf80-11d6-11ea-920e-62c1a6d94181.png)
![image](https://user-images.githubusercontent.com/35060336/69779237-49672900-11e2-11ea-9c32-05c3c2b6fa21.png)

**App information (please complete the following information):**
 - App Type :Native App
 - Postman Version :v7.12.0
 - OS: win10

**Comment by Quozzo** [comment]
Isn't the array being forced to a string because that's the only thing that postman can store? You would need to stringify it when saving.
[Environment and global variables are always stored as strings. If you’re storing objects/arrays, be sure to JSON.stringify() them before storing, and JSON.parse() them while retrieving.](https://learning.getpostman.com/docs/postman/environments-and-globals/manage-environments/)

**Comment by shamasis** [comment]
Environment variables are of string type and does not allow arrays.

**Comment by v-las** [comment]
> Environment variables are of string type and does not allow arrays.

So why do they behave like objects in v10.22.10?

I set an object in first request without `JSON.stringify` by
`pm.environment.set('test', { foo: ['bar', 'baz'] })`
and then get it from env without `JSON.parse` in second request by
`console.log(pm.environment.get('test'))`

There is no information about this change in the release notes, and documentation [remains](https://learning.postman.com/docs/sending-requests/variables/#variable-scopes) the same.

**Comment by vedkribhu** [comment]
Hi @v-las , 
The behaviour you are pointing out is an expected behaviour and it has not been changed in any of our latest versions.
Let me provide some clarification regarding the statement "variables are of string type and do not allow arrays." When you set a variable within scripts and you utilize these variables back in scripts, they retain the exact type you've designated. 

However this type designation is confined to the scope of scripts. For instance, when you send a request containing such a variable, we will convert it into a string format. This means that the variable will be stringified before being sent to your server.

I hope this explanation addresses any confusion you may have had regarding this matter.
