### ISSUE TITLE
Param value "+" is replaced with blank space.

### ISSUE THREAD

**Issue by vainiusr** [a85/POSTMan-Chrome-Extension#7715]
**Describe the bug**
When passing a `+` sign through params in `POST` request, postman replaces it with a blank space making validation testing useless, because it never passes a correct value.

**To Reproduce**
1. Go to Postman
2. Make a POST request to your server
3. Add a param with value `your+email@example.com` to request
4. Dump the param in code.
5. See that it became `your email@example.com`

**Expected behavior**
The dumped value should be `your+email@example.com` instead of `your email@example.com`.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.12.0]
 - OS: [macOS Catalina 10.15.1]

**Comment by shamasis** [comment]
@vainiusr Postman does not convert `+` to whitespace. I strongly suspect that this is the server doing it. I am pasting a screenshot of sending URL to `http://postman-echo.com/get?a=your+email@example.co`. Notice how the server response assumed + to be whitespace but wireshark result (on right) shows underlying network data sent had normal `+` sign in it.

![Screenshot 2020-03-12 at 02 11 59](https://user-images.githubusercontent.com/232373/76462092-19493c00-6407-11ea-8470-9c5539fda5a4.png)

**Comment by thechaudharysab** [comment]
I faced this issue today with trying to send the MongoDB connection string in params, which starts as `mongodb+srv://` and upon receiving it at the backend (which is in NodeJS/Express) the string became `mongodb srv://` which was weird and I didn't have time to explore it in depth, so here is a way around that worked for me. 

Instead of passing the connection string as params, I passed it via headers:

```
    // const connection_string = req.query['conn-url'] as string; // This was missing +
    const connection_string = req.headers['x-conn-url'] as string; // This worked fine
```
