### ISSUE TITLE
Filter Variables

### ISSUE THREAD

**Issue by joshua-bn** [a85/POSTMan-Chrome-Extension#7734]
**Is your feature request related to a problem? Please describe.**
I need to search for a variable in the environment/global/collection variables. I have a lot of variables.

**Describe the solution you'd like**
Input box above variables (collection, env, and globals) that will filter based on the variable and maybe value. The variable is much more important but I can imagine people wanting to filter by the value as well.

**Comment by preethammavin** [comment]
@joshua-bn can you explain the workflow a bit more so that I can recommend any solutions or device one in the product.

If you do have many variables that you would want to find, I would recommend using our find and replace which basically searches everything in your workspace (variables,globals,collections). Let me know if this works.

Else feel free to reopen the issue.

**Comment by joshua-bn** [comment]
I don't want to just find the variable, I want to edit the value. Say I have "contact_1" and "contact_2" and up to 10 or so like that. I want to find those by filtering down by "contact" and then I can see them all as a list. This would help me see the variables and values so I can make changes without the distractions of the other variables.
