### ISSUE TITLE
{{$guid}} system variable is executed each time the variable is accessed

### ISSUE THREAD

**Issue by bsnahrwold79** [a85/POSTMan-Chrome-Extension#7791]
**Describe the bug**
A REST API call with {{$guid}} in the payload modifies the guid not only when the call is executed but every time it is accesses when you click Code to see the request. The static request generated should not change.

**To Reproduce**
1. Create a rest POST call with a payload containing {{$guid}}
2. Click on Code  (Below Send / Save buttons) to view the request generated. In this case it  was:
    331612da-8846-42ed-997f-7b118eee3d86
3. Close this GENERATE CODE SNIPPETS window
4. Click it again and a new code will be generated for {{$guid}}
    981c8a14-c30d-4ed0-a19f-14973723fe6b

**Expected behavior**
The GENERATE CODE SNIPPETS window, by name, appears to let you enter code on the fly. Thus I guess it is not surprising the {{$guid}} would generate a new code each time the Code window is accessed. However, as far as I know, this is the only way to see the generated request sent to the system other than look at system logs. SoapUI, for all its faults, gives you this information quick easily and it is static
There should be a way to review the static REQUEST generated, with variables filled in, without having new values generated by system variables change, such as vales represented by {{$guid}}, each time you want to look at the, hopefully, static request text.

**Screenshots**
The description should be simple enough to recreate without screen capture entries added to thiss bug.

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.13.0
 - OS: macOS Mojave 10.14.6

**Comment by xk0der** [comment]
@bsnahrwold79 
Code generation is like sending a new request, and the reason why the variable is resolved every time a new code snippet is generated so that it can be copied and pasted wherever the request needs to be executed.

I believe you are already doing this unless you meant something else by system logs:
[Postman Console](https://learning.getpostman.com/docs/postman/collection-runs/debugging-a-collection-run/) is where you should be looking at to see what value `{{$guid}}` resolved to. 

Postman Console may be opened by navigating to `View > Show Postman Console` within the Postman app. Or by clicking the Console icon located at the bottom left in the status bar.
<img width="175" alt="Screen Shot 2019-12-13 at 12 57 53 PM" src="https://user-images.githubusercontent.com/21366/70758518-2f177880-1da8-11ea-876e-16ce0c6aa2ab.png">

If you were already looking at the Postman Console, but want something quicker, that might be a feature request.

**Throwing out my "feature" ideas in the open**
- Maybe a quick link to open the last request run within the Console might be what you are looking at?
- Or possibly a tooltip to quickly display the last request's details without having to open the Console?
