### ISSUE TITLE
Postman adds extra line in the header, when use a global variable

### ISSUE THREAD

**Issue by shleym** [a85/POSTMan-Chrome-Extension#7808]
**Describe the bug**
I try to run several request that uses AUTHORIZATION header.
When I defined AUTHORIZATION with some-authorization-key, everything is working fine.
When I defined global variable MY_AUTHORIZATION_KEY with value some-authorization-key and use this global variable for header definition, like {{MY_AUTHORIZATION_KEY}}, the post man put an extra empty line in the request header, which breaks the HTTP structure and does not work.

**To Reproduce**
1. Create a GET request to the URL, that requires authorization
2. Add header AUTHORIZATION and put the authorization key as a value
3. Send request, and see, that everything is working
4. Create a Global Variable MY_AUTHORIZATION_KEY_for_this_site with exactly the same authorization key
5. Go back to the header and put the {{MY_AUTHORIZATION_KEY_for_this_site}} variable as a value for the AUTHORIZATION header
6. Send request, and see, that it is failed
7. Click the **code** link in the right top cornet to see the raw request. You will see an extra empty line that is breaking the structure. 
The size of authorization key is 1080 characters

**Expected behavior**
The HTML Request should have only ONE empty line in the end of the header regardless of the way we specify the value for AUTHORIZATION header (directly or using global variable)

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [Postman v7.0.6]
 - OS: [Windows 7 Enterprise Service Pack 1]

**Additional context**

**Comment by preethammavin** [comment]
@shleym can you update to the latest version and check if the issue persists. We had pushed a few bug fixes around this and it looks like you are on very old version of the app

**Comment by vikiCoder** [comment]
Hi @shleym,

I think your request is failing while using a global variable in the request header is because the value of your global variable (`{{MY_AUTHORIZATION_KEY_for_this_site}}`) contains an invisible newline character in it. This usually happens while copy-pasting value of environment variable from some other resources (like a webpage). Can you please check and confirm my speculation?

If that is the case then we have made some changes towards making such unintentional white space characters more visible. Those changes are out in canary. Please download the latest [Postman canary](https://www.postman.com/downloads/canary) and checkout it out.

**Comment by vvs11** [comment]
@shleym Please let us know if you're still facing the issue.

**Comment by mccannt** [comment]
Closing this issue out. @shleym if you continue to experience this problem on the latest version of our application, please do reopen this issue with any additional details you can provide. 
Thanks.
