### ISSUE TITLE
Body string don't have bars on line endings

### ISSUE THREAD

**Issue by paulocoutinhox** [a85/POSTMan-Chrome-Extension#7817]
**Describe the bug**
Body string don't have bars on line endings

**To Reproduce**
1. Generate any request with json body (raw data and type json)
2. Click on code

**Expected behavior**
Each line need have their bar on right (line endings)

**Screenshots**
<img width="1552" alt="Screenshot 2019-12-17 17 43 28" src="https://user-images.githubusercontent.com/395096/71032923-1c2cdd00-20f5-11ea-97d3-a4d27c8adb99.png">

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.13.0]
 - OS: [e.g. macOS Mojave]

**Comment by chrisdeso** [comment]
@prsolucoes I wasn't able to reproduce this but I'm not super knowledgeable with cURL – would you try the new (open source) code generation feature to see if it yields the same results?
![image](https://user-images.githubusercontent.com/4734306/71036667-bd129c80-20e3-11ea-9d33-c9a93caeb819.png)

You'll need to navigate to `Settings` and select `New Code Generation Mode` from the settings menu.

![image](https://user-images.githubusercontent.com/4734306/71036966-5a6dd080-20e4-11ea-9269-405e6690fdbf.png)

**Comment by paulocoutinhox** [comment]
Hi,

Is because the current solution works on terminal and shell script. But if you paste on Makefile it doesn't work with this pattern. Postman is putting new-command line on all line endings, but not on latest lines (body data).

To reproduce better, create a file called Makefile and copy-paste curl command, like this:

**Makefile**
```
all:
	curl -X GET \
  https://postman-echo.com/status/200 \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 45' \
  -H 'Content-Type: application/json' \
  -H 'Host: postman-echo.com' \
  -H 'Postman-Token: 4fc92373-0b34-4a63-bc54-795535c130c8,64da8879-15c3-4250-8379-c803cafbf910' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'cache-control: no-cache' \
  -d '{
    "data": {
        "foo2": "bar"
    }
}'
```

And after create file execute on terminal **make**.

You will get error:
![image](https://user-images.githubusercontent.com/395096/71041029-c7925d80-2106-11ea-9061-8c6a8c0f6a2b.png)

This happen because left other line ending bars. If you add manually, and execute make it will work. Example:

**Makefile**
```
all:
	curl -X GET \
  https://postman-echo.com/status/200 \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 45' \
  -H 'Content-Type: application/json' \
  -H 'Host: postman-echo.com' \
  -H 'Postman-Token: 4fc92373-0b34-4a63-bc54-795535c130c8,71fc2bb7-70d2-4fb8-a1ff-da99f0d497c4' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'cache-control: no-cache' \
  -d '{ \
    "data": { \
        "foo2": "bar" \
    } \
}'
```

![image](https://user-images.githubusercontent.com/395096/71041104-fc9eb000-2106-11ea-818b-cb441ac3c654.png)

If you fix in this way that im suggesting, it will work on all ways.

Thanks.

**Comment by someshkoli** [comment]
@prsolucoes When we append \ at the end of line, wouldn't that alter the actual body of the request ? like i tested out what you were trying to explain and got this.
![image](https://user-images.githubusercontent.com/41543649/83331912-2cf19980-a2b6-11ea-9c23-0258862b8f4b.png)
Checkout the data property of the response, it has extra \\. Let me know if there's anything wrong in my request. 
Also I found a workaround for this here:
![image](https://user-images.githubusercontent.com/41543649/83332250-b3f34180-a2b7-11ea-8974-8d355ecb0495.png)
enclosing them in single quotes works

**Comment by SahilChoudhary22** [comment]
Hi @paulocoutinhox, just went through your issue.

`cURL` generated by Codegen is appropriate because as @someshkoli [mentioned](https://github.com/postmanlabs/postman-app-support/issues/7817#issuecomment-636344279) on the issue thread, if backslash are added to the JSON body, it'll alter the actual body of the request.

Therefore, the `cURL` generated is correct and the issue that you're facing is while executing the same command in a `makefile`. 

This is because `makefile` is parsed by `make` before execution. This means that if the backward slashes are present in the `makefile`, it’ll be first parsing those backward slashes and then forming the `cURL` command, so in this case, the backward slashes are ignored. On the other hand, if the backward slashes are not present, it'll think of it as a single line command resulting in a failure.
Ref : [Parsing Makefiles (GNU make)](https://www.gnu.org/software/make/manual/html_node/Parsing-Makefiles.html) 
[Reading Makefiles (GNU make)](https://www.gnu.org/software/make/manual/html_node/Reading-Makefiles.html#Reading-Makefiles) 
[How Make Works (GNU make)](https://www.gnu.org/software/make/manual/html_node/How-Make-Works.html)

To go around this problem with multiline `cURL` execution in a `makefile`, you can follow either of these 2 approaches -

1) `define` the cURL in the `makefile` and then call it, as follows
```
define JSON_TODO
curl --request POST 'https://postman-echo.com/post' \
--header 'Content-Type: application/json' \
-d '{
    "data": {
        "foo2": "bar"
    }
}'
endef
export JSON_TODO

all:
    @echo $$JSON_TODO | bash
```

Ref : [unexist.dev | Multiline commands in makefiles](https://blog.unexist.dev/tech/2021/05/21/multiline-commands-in-makefiles.html) 
This way, the defined snippet is separately loaded and then executed. This prevents the missing separator error that you're facing.


2) Convert the multiline `cURL` to single line and use it as the user's already using
```
all:
    curl --location --request POST 'https://postman-echo.com/post' \
    --header 'Content-Type: application/json' \
    --data-raw '{ "data": {"foo2": "bar"} }'
```


I think the product's current behaviour is right and doesn’t need modifications because the data param/arg in `cURL` output is multiline as default setting instead of single line for a cleaner output and to serve the larger audience. You can convert the `cURL` to single line by clicking on the cog wheel near the language dropdown.
Also, As you've suggested adding a slash at the end of each JSON line, I wouldn't advice this because it makes it a malformed `cURL` by altering the data/breaking JSON conventions.
