### ISSUE TITLE
Better resizing options for envirment settings managemnt

### ISSUE THREAD

**Issue by AlthalusDGr8** [a85/POSTMan-Chrome-Extension#7821]
**Is your feature request related to a problem? Please describe.**
We currently have collections with different APIS to mock requests against and so we store differnt URLS for a multitude of services in differnt enviroments (such as prod, staging and local).  The dialog window is small that adjusting a full dns name can be problematic

**Describe the solution you'd like**
A resizable window

**Describe alternatives you've considered**

**Additional context**

**Comment by delroyh** [comment]
I'd like to +1 this feature request (instead of creating a new issue/request)

When using postman for enterprise software (manual api testing, automated testing, etc) sometimes environments contain many many env vars, with delimited names for the sake of organization. These "enterprisey" names tend to be very long in the tooth

when viewing environment variables through the "Environment quick look" window, long variable names and values wordwrap making them hard to read. This would be much less of a pain if we could expand the size of the window such that the width allowed the names/values to display in one line.

**Comment by giridharvc7** [comment]
Environments are now a full size window and can be opened as a tab in postman version 8. Would love to know if these changes solve your problem @delroyh @AlthalusDGr8
