### ISSUE TITLE
Access collection run results more easily

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#7883]
If there's a collection selected in the collection runner, it's unclear in the current runner window how to view historical collection run results, or even that the results are something that I can view in aggregate.

<img width="1392" alt="Screen Shot 2020-01-07 at 3 36 23 PM" src="https://user-images.githubusercontent.com/17693714/71938233-9f28dc80-3163-11ea-9efc-44d2808041a3.png">

To access the historical collection run results, I can open a new collection runner window using the "Runner" button in the header. Also, it's not clear in the runner UI that I can de-select a collection, especially if I have accessed the collection runner window from the collection details flyout (and not actively selected the collection).

**Comment by malvikach** [comment]
This problem is solved in the latest Postman version 10. 

You have access to 'Runs' tab in a collection that will provide a list of all historical collection runs for that collection. It also provides easy access to view the details for each run by clicking on 'View Report'. 

Giving a sneak peak into this:

<img width="1004" alt="Screenshot 2022-09-21 at 7 30 04 PM" src="https://user-images.githubusercontent.com/89449769/191524687-fb835d4e-8d36-47b3-9130-c575a20dac0d.png">

Postman version 10 has many more exciting functionalities. Read more about it [here](https://blog.postman.com/announcing-postman-v10/). v10 is not generally available right now, but we are giving early access to interested users. 

If anyone who visiting this thread, is interested to give it a spin, please comment on the issue and I can help you with it.

[This](https://blog.postman.com/introducing-the-postman-cli-to-automate-your-api-testing/) is our blog that talks about the other Collection Run features we are offering along with the new Postman CLI.
You can also set up some time with me to discuss further using [this](https://calendly.com/malvika-chaudhary/v10-feedback).
