### ISSUE TITLE
How to login using SSO oauth 2.0 and then storing token to run all other API from postman automation script?

### ISSUE THREAD

**Issue by Riya1823** [a85/POSTMan-Chrome-Extension#7894]
I am not able to automate postman script for this procedure:
1.Open postman then in authorization tab select type->OAuth 2.0, Add authorization data->Request Headers and Access token->Get Access Token Filled fields-Token Name, Grant Type->Authorization Code, Callback URL, Auth Url, Acess Token Url, client Id, Scope, State, Client Authentication->Send as basic Auth header 
![Auth0](https://user-images.githubusercontent.com/46278421/72048226-53507180-32e2-11ea-99a5-819a2d421c3c.JPG)
then when request Token a pop up window opens for SSO enter image description here
![sso_popup](https://user-images.githubusercontent.com/46278421/72049810-babbf080-32e5-11ea-853b-1b06e0d45c3a.JPG)

2.Then Manage Acess tokens pop up appears, then select Use Token button at the bottom,
![image](https://user-images.githubusercontent.com/46278421/72049985-17b7a680-32e6-11ea-8ec6-8b8474e1c783.png)
 then when running api url 
![url_get](https://user-images.githubusercontent.com/46278421/72050198-9280c180-32e6-11ea-93fa-11d3c0ac4ac3.JPG)
which now contain token in the Header tab->temperory headers.
![temp_header](https://user-images.githubusercontent.com/46278421/72050524-5bf77680-32e7-11ea-8218-d471c5020d14.JPG)
 How to automate this procedure with storing token in environment variables,then running rest of the API's with it.

**Comment by aamir-ahmed** [comment]
@Riya1823 , After generating the access token for the first request, you can add the following Test Script in the Tests Tab for the given request which will set the value of the access token to the environment variable:
```
auth_token=pm.request.getHeaders()['Authorization'];
auth_token=auth_token.replace('Bearer ','');
pm.environment.set("ACCESS_TOKEN", auth_token);
```
You can go ahead and then access the access token value for the corresponding requests on the Authorization tab by referencing it within the double flower brackets as showcased in the below screenshot: 
![GetAccessToken](https://user-images.githubusercontent.com/51746288/76956374-ec7eb280-6939-11ea-878c-ad479c1c3f90.png)

If you wish to retrieve the value from within the test scripts instead of referencing it from the Authorization Tab, you can add the following script:
`pm.environment.get("ACCESS_TOKEN");
`
Please ensure the appropriate environment is selected when you are executing the given requests.

If there are multiple requests within folders, I would suggest you to reference the environment variable at a folder level by clicking on the ellipsis next to the folders within the collections, clicking on Edit, navigating to the Authorization tab and accessing the environment variable at a folder level instead of at a request level.

If you have any further questions about using Postman and how to execute certain workflows, you can ask them here on the Postman community website: https://community.postman.com/ which many of the Postman users to share their ideas and ask questions regarding the same. Hope this helps!
