### ISSUE TITLE
Windows: postman keeps spawning cmd.exe while using 100% CPU

### ISSUE THREAD

**Issue by demvin** [a85/POSTMan-Chrome-Extension#7925]
**Describe the bug**
Right after launch, Postman will continuously spawn cmd.exe subprocesses while using 100% cpu.
The subprocesses are all trying to run "C:\WINDOWS\system32\cmd.exe /d /s /c "REG QUERY HKCU\Software\Google\Chrome\NativeMessagingHosts\com.postman.postmanapp""

**To Reproduce**
1. Launch Postman

**Expected behavior**
Postman starts, doesn't use 100% cpu and is usable,

**Screenshots**
![image](https://user-images.githubusercontent.com/1210081/72556934-bbb4cb00-386d-11ea-8ba8-be7bddb5e989.png)
![image](https://user-images.githubusercontent.com/1210081/72556963-c7a08d00-386d-11ea-8510-2dcfec00dcee.png)

**App information:**
 - App Type : Native
 - Postman Version 7.16.0
 - OS: Windows 10 enterprise

**Additional context**
Worked well before, another collegue now has exact same problem.

**Comment by vinitshahdeo** [comment]
@demvin Users are facing the CPU usage issue when the **Interceptor isn't connected.** 
We're investigating the root cause and hope to have a fix soon. Please try to install Interceptor Bridge and restart the app after the installation is finished. Please let us know if CPU usage is reduced after the installation is completed and Interceptor is connected.

> Note: You can install Interceptor Bridge either from the Capture Cookies tab or Request tab with source toggled to Interceptor.

<img width="955" alt="Screenshot 2020-01-16 at 10 41 30 PM" src="https://user-images.githubusercontent.com/20594326/72560804-d0c14680-38cd-11ea-8f50-2a1509f303d0.png">

<img width="955" alt="Screenshot 2020-01-16 at 10 41 30 PM" src="https://user-images.githubusercontent.com/20594326/72560826-da4aae80-38cd-11ea-9d7c-cc6ff02a4ba1.png">

**Comment by demvin** [comment]
Thanks for the info. Is there another way to install the interceptor bridge than from within the app ? It always fails to download.  Probably the corporate network, but since automatic updates works, I'm not sure. 

![image](https://user-images.githubusercontent.com/1210081/72616218-6d9ed680-3904-11ea-92d4-40017267ec42.png)

**Comment by vinitshahdeo** [comment]
@demvin Please try using Postman Canary(`v7.16.0-canary01`). We've shipped a fix to reduce the CPU usage. Please confirm if this update helps.

- **You can download Postman Canary from [here](https://www.getpostman.com/downloads/canary).**

- Please follow the [troubleshooting guide](https://go.pstmn.io/interceptor-installation-troubleshooting) if you face any issues while installing Interceptor Bridge.

- Kindly note that the Postman Canary app doesn't need to be connected with Interceptor to reduce CPU usage.

> We're still working on improvements and hope to have a stable release soon.

**Comment by demvin** [comment]
Canary fixes it, thanks.
