### ISSUE TITLE
Path parameters not ignoring path extensions

### ISSUE THREAD

**Issue by unmultimedio** [a85/POSTMan-Chrome-Extension#7928]
**Describe the bug**
Some APIs support extensions to retrieve the results in a specific format:
- https://some.server/some/path/resource/resourceID.json
- https://some.server/some/path/resource/resourceID.xml

That returns the same info, but in different formats, but if we want to treat `resourceID` as a path `:variable` it will grab the extension as part of the variable name.

**To Reproduce**
1. Go to 'New Request'
2. Type in the URL this: `https://some.server/:path_variables/dont/support/:this_format.json?some_query=value`
3. Scroll down to 'Path variables'

**Expected behavior**
Expected result: There's a variable called `this_format`
Actual result: There's a variable called `this_format.json`

**Screenshots**
<img width="682" alt="Postman" src="https://user-images.githubusercontent.com/4431392/72582375-82517f00-38b0-11ea-95d5-5c6edb6e2302.png">

**App information (please complete the following information):**
 - App Type [Mac]
 - Postman Version [7.13.0]
 - OS: [macOS Mojave 10.14.6]

**Additional context**
N/A

**Comment by vikiCoder** [comment]
Hi @unmultimedio,

This is expected behaviour for path variables. I would suggest using environment variables with {{var_name}} syntax for more flexibility. Refer [this link](https://learning.postman.com/docs/postman/variables-and-environments/variables/) for more details on using variables.

Feel free to reopen this issue if you face any other problem regarding this.
