### ISSUE TITLE
Postman's window is not show when open the app

### ISSUE THREAD

**Issue by fengyangdi** [a85/POSTMan-Chrome-Extension#7934]
1. Postman Version: 7.16.0
2. App (Chrome app or Mac app): Mac App
3. OS details: macOS Catalina 10.15(19A603)
4. Is the Interceptor on and enabled in the app: n/a
5. Did you encounter this recently, or has this bug always been there: Upgrade the postman to 7.16.0  in two days, then it occurs

only can show this window
![WeWork Helper20200120102737](https://user-images.githubusercontent.com/8668258/72694304-85c65e00-3b6f-11ea-8ad5-3da391c5c6b9.png)
 
and I have tried ways in this issue but it didn't work  https://github.com/postmanlabs/postman-app-support/issues/2992

Related issue: https://github.com/postmanlabs/postman-app-support/issues/7823

**Comment by minakoto00** [comment]
Same problem here. 
Postman Version: 7.16.0
OS version: MacOS Catalina 10.15.2
It seems that after I updated the postman Version to 7.16.0. It occurs.

**Comment by Blacksmiss** [comment]
Similar issue - Postman shows a blank screen only.
Postman Version: 7.16.1
OS Version: Win10, Version 1903 (Build 18362.592)
Issue came up after update. 
![PostmanBlank](https://user-images.githubusercontent.com/57681944/73056689-faf7a300-3e8f-11ea-9245-49c01cb6aca8.png)

**Comment by sivajrm** [comment]
Hi there,
Is it possible to downgrade to a version that doesn't have this issue?

Thanks.

**Comment by Blacksmiss** [comment]
Hi Siva,unfortunately not - already tried to get back to the Version used before.My tries always resulted in the same error.Thanks to you,Udo Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Siva Sivasubramoniam Jayaram <notifications@github.com> Datum: 18.02.20  06:55  (GMT+01:00) An: postmanlabs/postman-app-support <postman-app-support@noreply.github.com> Cc: Blacksmiss <UdoMuellerNiederberg@googlemail.com>, Comment <comment@noreply.github.com> Betreff: Re: [postmanlabs/postman-app-support] Postman's window is not show when open the app (#7934) Hi there,
Is it possible to downgrade to a version that doesn't have this issue?
Thanks.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/postmanlabs/postman-app-support/issues/7934?email_source=notifications\u0026email_token=ANYCQGD7TR74A6QSQQGCGCDRDNZ6JA5CNFSM4KI5IL3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMAVXTA#issuecomment-587291596",
"url": "https://github.com/postmanlabs/postman-app-support/issues/7934?email_source=notifications\u0026email_token=ANYCQGD7TR74A6QSQQGCGCDRDNZ6JA5CNFSM4KI5IL3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMAVXTA#issuecomment-587291596",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sivajrm** [comment]
Oh, oh!  
That's sad to hear. I wish Postman allows us to download the previous stable version.

**Comment by harryi3t** [comment]
This is fixed in Postman v7.19.1 🎉 
Please let us know if you are still facing the issue.

**Comment by fengyangdi** [comment]
> This is fixed in Postman v7.19.1 🎉
> Please let us know if you are still facing the issue.

It’s OK , I upgrade to 7.20.1, Thank you!
