### ISSUE TITLE
Manage Tokens Produces Error Dialog

### ISSUE THREAD

**Issue by marshallr12** [a85/POSTMan-Chrome-Extension#7946]
**Describe the bug**

Selecting "Manage Tokens" produces error message every time.

**To Reproduce**
1. Go to any collection and  'Edit'
2. Click on 'Authorization' Tab
3. Click 'Available Tokens' dropdown
4. Scroll to 'Manage Tokens' and select.
-Error dialog opens

**Expected behavior**
The manage tokens dialog should open.

**App information (please complete the following information):**
 - App Type Native
 - Postman Version 7.16.0
 - OS: Windows 10
[main.log](https://github.com/postmanlabs/postman-app-support/files/4092610/main.log)
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/4092611/renderer-requester.log)
[renderer-shared.log](https://github.com/postmanlabs/postman-app-support/files/4092612/renderer-shared.log)
[renderer-shell.log](https://github.com/postmanlabs/postman-app-support/files/4092613/renderer-shell.log)

**Comment by deanjott** [comment]
I have this same issue.  Here is some specific info related to what I am seeing:  After I had about 30 old tokens in my list,  I started deleting them then get the popup "Something went wrong"  Now if I try to delete tokens maybe I can delete one of them before I get the error or sometimes I get the message right away.  It seems random as to when it starts.
Postman version: v7.17.0
OS version: Windows 10

**Comment by vikiCoder** [comment]
Hi everyone,

We have fixed this issue with `Manage Tokens` dialog and the fix is out in the latest [Postman canary (7.21.0-canary01)](https://www.postman.com/downloads/canary). It will be fixed in the next version of the Postman app (v7.21) soon. Meanwhile, please check out the latest [Postman canary](https://www.postman.com/downloads/canary) and let us know if you are still facing the same issue in it.

**Comment by vikiCoder** [comment]
The fix is out in the latest version of the Postman app (v7.21.0).
