### ISSUE TITLE
UI hangs when sync is in progress

### ISSUE THREAD

**Issue by gonensh** [a85/POSTMan-Chrome-Extension#7951]
**Describe the bug**
Whenever I open a team workspace, the UI hangs until the downstream sync is complete.

**To Reproduce**
1. Go to Postman App
2. Click on 'My Workspace'
3. Select a team workspace that will sync from the cloud
4. The UI becomes progressively unresponsive and hangs until the downstream sync is complete

**Expected behavior**
Two expected behaviors here:
- UI remains responsive while sync is happening in the background.
or
- UI shows a prominent visual indication that it should not be used until the sync is complete

**Screenshots**
N/A

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.11.0 (7.11.0)
 - OS: macOS Mojave 10.14.5 (18F203)

**Additional context**
N/A

**Comment by ankit-m** [comment]
@gonensh could you tell me how many collections and environments exist in your team workspace?

**Comment by gonensh** [comment]
> @gonensh could you tell me how many collections and environments exist in your team workspace?

We have ~114 collections of varying sizes in our shared workspace and 59 environments.

**Comment by Spielboerg** [comment]
I have the same problem, and it's really annoying because the user interface hangs for ~1-2 minutes (the time it takes to synchronize) before it becomes usable. Also, the synchronization process seems really slow to me. I thought it would take so long because all workspaces (5) are synchronized at once, but only the current workspace is synchronized. It contains 17 collections with ~240 requests. Only for this the sync took 1-2 minutes! When I changed the workspace, the sync for this workspace started and the UI hung for another minute... Please fix this.

**Comment by ankit-m** [comment]
We are aware of UI issues when large workspaces or workspaces with high activity are being synced. There are multiple things involved and we will gradually roll out changes to improve the UX around this. I will keep you posted.

**Comment by Spielboerg** [comment]
Nice to hear that and thank you for the quick response 👍

**Comment by ankit-m** [comment]
We have released first round of improvements in **v7.22**. You should see performance improvements while working in large and high activity workspaces. We will continue to release improvements and keep you notified.

**Comment by gonensh** [comment]
Thanks @ankit-m!

**Comment by ankit-m** [comment]
We have made further improvements in v7.27 and improved syncing performance.

**Comment by mccannt** [comment]
We have made many improvements around this recently. Closing this issue. 
If issues persist, please feel free to reopen this issue.
