### ISSUE TITLE
OAuth2 helper: Postman console does not log all requests

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#7952]
**Describe the bug**
It seems that the Postman console does not log all the requests that are being sent out. 
When the popup window opens, the HTTP traffic is not recorded.  

**To Reproduce**

- Go to Authorization
- Select OAuth 2.0
- Click "Get new access token"
- Select Grant Type "Client credentials" (or Authorization Code)
- Fill in some data
- The error appears: "Could not complete OAuth 2.0 login. Check Postman console for more details."
- The Postman console shows an error but not the request that was sent

**Expected behavior**
The Postman Console should log all HTTP traffic

**Screenshots**

![Screenshot 2020-01-23 at 13 09 36](https://user-images.githubusercontent.com/1197635/73011202-c9c09980-3de1-11ea-961f-3c80eb77e6e4.png)

You can notice that above the error, there is no HTTP request logged.

![image](https://user-images.githubusercontent.com/1197635/73010840-2b343880-3de1-11ea-82e3-8acc84a5f435.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.16.0
 - OS: macOS

**Comment by vikiCoder** [comment]
Hi @vdespa,

This issue is fixed in the latest release of the Postman app (v7.24.0). Postman console now logs all intermediate requests from the popup window while generating new OAuth 2.0 token. These requests are shown in the console with a lock icon to make it easily identifiable. Please update to the latest version of the Postman app to check it out. Feel free to reopen the issue if the problem still persists.

![image](https://user-images.githubusercontent.com/16588032/81491808-160be880-92b0-11ea-9c45-4532c5e905e1.png)

**Comment by orithena** [comment]
Requesting to reopen this issue: In Postman 8.02 and 8.03 on windows, this problem came up again.

**Comment by vdespa** [comment]
@orithena I can't replicate this issue in Postman 8.0.4

**Comment by XcrigX** [comment]
On Postman 10.15.2 - When I authenticate to a service, the auth request does not show up in the console.  The token request does after authentication, but not the initial call to the auth URL.
