### ISSUE TITLE
Error: unable to verify the first certificate - only in the Runner

### ISSUE THREAD

**Issue by danieladougan** [a85/POSTMan-Chrome-Extension#7968]
**Describe the bug**
When running the Runner in our testing environment, in the Postman console, I get:

**Error: unable to verify the first certificate
Warning: This request did not get sent completely and might not have all the required system headers**

And the Runner stops. This is the first route in that collection.

**To Reproduce**
1. Go to the Postman Runner.
2. Set the environment to the test server.
3. Run the collection.

**Expected behavior**
That the runner should function just as individual routes do instead of crashing.
My colleagues accessing the same test server are not experiencing this problem. We compared our settings, and they seem to all be the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/42144517/73306177-af275f80-41e9-11ea-9067-173c7bd6c720.png)

![image](https://user-images.githubusercontent.com/42144517/73306194-b64e6d80-41e9-11ea-8cf7-53ea5776a76e.png)

**App information (please complete the following information):**
 - App Type: Windows app
 - Postman Version 7.16.1
 - OS: Windows 10

**Additional context**
SSL certificate verification is turned off.
I am able to run the Runner on my localhost, just not on our test server. I used to be able to do this until recently when we had to install 7.16.1 on my computer. I can run a route individually against the test server, and it's fine. But when the Runner hits that exact same route, it crashes...as shown in the screenshots.

We also tried Postman Canary, and I had the same problem there.

**Comment by danieladougan** [comment]
This has somehow healed itself. I'm not sure how or why, but I'll take it.

**Comment by vikiCoder** [comment]
Hi @danieladougan,

I guess the problem might have been caused because you could have done something like this:
1. Open Postman app. (The SSL certificate verification is turned on by default)
2. Open Runner and run the collection (it will fail due to SSL verification)
3. Go to requester window without closing runner window and turn off SSL certificate verification
4. Go back to the already open runner window and run the collection again. (it will still fail)

The issue here is that changes in global settings form requester window are not synced to other already open windows like the runner. You have to restart the open window (runner) for the setting change to take effect.

**Comment by vikiCoder** [comment]
Hi,

This issue is fixed in the latest release of the Postman app (v7.24.0). Please update to the latest app and check it out. Feel free to reopen the issue if the problem still persists.
