### ISSUE TITLE
Incorrect status code name for HTTP 418

### ISSUE THREAD

**Issue by j9d** [a85/POSTMan-Chrome-Extension#7969]
**Describe the bug**
The description for HTTP 418 reads "Client Error (418)" where the official name is "I'm a teapot"

**To Reproduce**
1. Run a request that returns HTTP 418
2. Note the response

**Expected behavior**
HTTP 418 should be returned with the name "I'm a teapot" as per [RFC 2324, section 2.3.2](https://tools.ietf.org/html/rfc2324#section-2.3.2)

**Screenshots**
![image](https://user-images.githubusercontent.com/37175276/73329910-53290d80-42b3-11ea-9073-f498bd8db550.png)

**App information:**
 - App Type: Native App
 - Postman Version: 7.16.1
 - OS: Windows 10 build 18362

**Additional context**
Status code names should reflect their official specification, thank you.

**Comment by jpaquit** [comment]
418 is HTCPCP related, not HTTP ;)

**Comment by j9d** [comment]
HTCPCP is an extension of HTTP. The code is supported in Postman, its name should at least be correct.

**Comment by jpaquit** [comment]
418 is only available with BREW (or POST) method :)

**Comment by j9d** [comment]
It actually supports BREW/POST, GET, PROPFIND and WHEN. Either way, this ticket is about the name of the response, which is clearly incorrect.

**Comment by coditva** [comment]
Hey, I don't think this is a bug... I sent a request to `postman-echo.com/status/418` and got the correct status message. `postman-echo.com` does not send any message in its response status line and the message shown in Postman is the standard message:
![image](https://user-images.githubusercontent.com/8445768/75861810-ebbb2c00-5e23-11ea-9af2-1bb036e500a5.png)


The response message "Client Error" as reported in the issue is sent from the server itself in the status message line as:
```http
HTTP/1.1 418 Client Error
```
