### ISSUE TITLE
Pm.cookies.jar could not find cookies with secure=true

### ISSUE THREAD

**Issue by jeevananthank** [a85/POSTMan-Chrome-Extension#7977]
**Describe the bug**
I have a list of cookies in my response that has secure=true which is not accessible by the pm.cookies.jar()

This results in an issue where i wanted to clear all the cookies under a domain, which does not happen with the below code on the secure cookies. 
Issue opened after the comments from : https://stackoverflow.com/questions/60001892/pm-cookies-jar-could-not-find-cookies-with-secure-true

**To Reproduce**
1. Send a request in Postman which returns cookies with secure =true and false.
Test script: 
> const jar = pm.cookies.jar();
var domain = pm.environment.get("envUrl");    
jar.clear(domain, function (error){
    if(error){
        console.log("error",error);
    }});
3. After this script is run, i could see that the secure cookies are NOT cleared from the manage cookies window.

**Expected behavior**
It is expected that pm.cookies.jar holds all the cookies irrespective of the secure flag.

**Screenshots**
![image](https://user-images.githubusercontent.com/49391725/73547954-4554c300-4440-11ea-88b0-587f524aae46.png)

**App information (please complete the following information):**
Postman for Windows - Version 7.16.1 - win32 10.0.14393 / x64

**Comment by sarangjaiswal** [comment]
I am facing the similar issue. I am unable to access the secure cookie via cookieJar and unable able to clear it.

**Comment by jeevananthank** [comment]
@sarangjaiswal i think i have found a workaround to solve this temporarily.
Refer the post in stackoverflow for details. [stackoverflow](https://stackoverflow.com/questions/60001892/pm-cookies-jar-could-not-find-cookies-with-secure-true/60077320)

**Comment by coditva** [comment]
Hey, @jeevananthank as pointed out in [this comment](https://github.com/postmanlabs/postman-app-support/issues/8168#issuecomment-597465146), to access the cookie, you must add the protocol `https://` to the URL because the cookie is set for `https://www.google.com` and when protocol is not specified, cookie jar uses `http://` which doesn't match.

You can also use `pm.request.url` instead of `www.google.com` in your scripts to ensure that the exact URL as your request is used.

Hope that helps. Feel free to comment if you have any more doubts.

Ref: https://github.com/postmanlabs/postman-app-support/issues/8168
