### ISSUE TITLE
pm.cookies to set a cookie with hostOnly=false

### ISSUE THREAD

**Issue by jeevananthank** [a85/POSTMan-Chrome-Extension#8010]
**Is your feature request related to a problem? Please describe.**
pm.cookies.jar() and set method always set a cookie with hostOnly:true even if the cookie is set under a domain. 

>  var cookieJar = pm.cookies.jar();
 var domain = ".postman.com";
 cookieJar.set(domain,{name:"test", value:"test", httpOnly:true},function(error,cookie){
    console.log(cookie); });
 cookieJar.set(domain,"test1","test1",function(error,cookie){
   console.log(cookie); });

![image](https://user-images.githubusercontent.com/49391725/74012130-cf91af80-4989-11ea-831a-2b07300c811b.png)

**Describe the solution you'd like**
It should be possible to set a cookie with hostOnly:false such that the cookie can be access by subdomains of the host. (Like it is possible to control the httpOnly flag)

**Describe alternatives you've considered**
No alternatives. The cookies is only accessible from the host and postman considers the subdomains in the requestURL as host.
for example., host for learning.getpostman.com is expected to be getpostman.com , but postman sets complete learning.getpostman.com as host.
![image](https://user-images.githubusercontent.com/49391725/74012648-074d2700-498b-11ea-92cc-cfaace874b2d.png)

**Additional context**
Issue created with reference to a question from StackOverflow: 
[https://stackoverflow.com/questions/60055518/pm-cookies-to-set-a-cookie-with-hostonly-false](url)

**Comment by coditva** [comment]
Hi @jeevananthank,

In the syntax for `cookieJar.set`, the cookie will be set with `hostOnly=false` if it contains the `domain` attribute. This is because if a cookie does not contain a domain, its domain is inferred from the URL and it is implicitly, `hostOnly`.

```javascript
cookieJar.set(domain, { name: 'cookieName', value: 'cookieValue', domain: domain }, function (err, cookie) {
	if (err) {
		console.log(err);
	} else {
		console.log(cookie);
	}
});
```

![image](https://user-images.githubusercontent.com/8445768/76513022-a62ddd00-647b-11ea-9447-f24ae93547fb.png)

Note: This behaviour is same as with the `Set-Cookie` header which does not have any `hostOnly` flag and it is inferred by the presence of `domain` attribute (`true` if `domain` is not present, `false` if it is present).

Hope this helps. Feel free to reach out if you have any doubts. :)
