### ISSUE TITLE
Workspace pre request scripts/test 

### ISSUE THREAD

**Issue by ColdCerealAtWork** [a85/POSTMan-Chrome-Extension#8022]
**Is your feature request related to a problem? Please describe.**
I have code that I use in every collection. I globalize this by writing a the methods in the "pre request scripts" section at the collection level and setting it to an environment variable, but then I have to copy that into each collection, which fragments my code base.

**Describe the solution you'd like**
A workspace scoped pre request script/test option would allow us to put common code in one space.

**Describe alternatives you've considered**
Alternatively if there was a way to reference a request from an external collection, I could place the common code in that request, and reference it at the collection level.

**Comment by arlemi** [comment]
We're tracking a similar request in [Reuse the same request inside several collections #1535](https://github.com/postmanlabs/postman-app-support/issues/1535), admittedly it has been open for a while but any update regarding the feature will be provided there. 

Closing this one.

**Comment by krispenner** [comment]
@arlemi That similar issue is not the same, it's about sharing a "request". This issue is about a workspace level pre-request script. Which I think is quite different and probably much easier to implement. So re-opening this makes more sense to get a vary useful feature out sooner.

+1 for workspace level pre-request script.
