### ISSUE TITLE
Interceptor keeps capturing requests even when set to OFF in Chrome

### ISSUE THREAD

**Issue by arlemi** [a85/POSTMan-Chrome-Extension#8032]
Reported by a user on Twitter: https://twitter.com/jdgregson/status/1226925004803039234

**Describe the bug**
If the Interceptor is `on` in the Postman app and `off` on Chrome, requests are still being captured and shown in the `History` tab of Postman.

**To Reproduce**
1. Turn interceptor `on` on both the app and Chrome
2. Turn interceptor `off` on Chrome
3. See that the History on Postman is still logging requests

**Expected behavior**
When turning the Interceptor `off` on Chrome, it should stop logging requests.

**Screenshots**
![interceptor](https://user-images.githubusercontent.com/5029719/74176397-7fd41200-4c2f-11ea-8f63-043e82dba82d.gif)

**App information (please complete the following information):**
 - Native app
 - Version 7.17.0 (7.17.0)
 - macOS Catalina 10.15.1
- Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- Interceptor version 0.2.28

**Additional context**
NA

**Comment by saialekhya-postman** [comment]
@arlemi  This is not a bug.
Interceptor extension UI is only for the chrome app, filters the user adds and toggle switch state from the interceptor extension will be respected by the chrome app, not the native app. 
Since the capture requests is toggled on in the `native app` interceptor is capturing requests in this case.

**Comment by arlemi** [comment]
Cool, closing since it is working as expected. A redesign of the interceptor extension will make this clearer later on.
