### ISSUE TITLE
Request filter: hide all requests that don't match

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#8045]
**Is your feature request related to a problem? Please describe.**
In the current implementation of the request filter, typing in the name of a request shows all requests in the Collection and highlights the matching ones. This is problematic for Collections that have a large quantity of requests, as it requires the user to scroll through a long list to find requests that match the filter.

**Describe the solution you'd like**
When filtering requests, only show requests in a Collection that match the filter (hide all others). This way, a Collection with a large number of non-matching requests isn't a pain to scroll through.

<img width="597" alt="Screen Shot 2020-02-11 at 10 28 10 AM" src="https://user-images.githubusercontent.com/43283131/74266752-af2f6100-4cb9-11ea-8747-97e65a8c70d3.png">

**Describe alternatives you've considered**
None

**Additional context**

**Comment by cngrindstaff** [comment]
Please fix this; it has made Postman nearly unusable for my team.

**Comment by coditva** [comment]
@cngrindstaff We had updated the filter so that any items in the collection should not be hidden when filter was on, because it used to confuse some users that items were missing from their collections.

But your use-case seems valid. We're working on a solution right now. Sorry for the inconvenience and stay tuned for updates!

**Comment by mp-loki** [comment]
@coditva It is really frustrating to alter the application behavior like that, especially such basic functionality that worked for ages and users got used to it. I have circa 150 requests in a collection for a single project, and highlighting instead of filtering is the same as there would be no filter at all. You have to scroll 100+ requests to find out what you are looking for. If there are users that do want "highlight instead of filter" feature, please make it configurable, but the filter should be on by default.

**Comment by vkaegis** [comment]
@mp-loki Thanks for chiming in, we completely agree. Bit of an oversight on our part to change this behaviour without any warning. As @coditva mentioned, we're working on a quick fix which should be out with the next update.

**Comment by F-shaikh** [comment]
how long before this is fixed, scrolling through 200 requests just to find a single request has not been ideal for the last few days 😢 and scrolling after "filtering" causes hiccups and slow downs.

**Comment by coditva** [comment]
@cngrindstaff @mp-loki @F-shaikh This is fixed in the latest Postman App `7.18.1`! Do let us know if you have any more concerns.

**Comment by cngrindstaff** [comment]
@coditva This was fixed in 7.18.1, but it is happening again in 7.19.0

**Comment by coditva** [comment]
@cngrindstaff You're right, this does seem to be happening in `7.19.0`. Sorry about that! We're working on fixing this ASAP.

You can use Postman Canary (https://www.postman.com/downloads/canary) in the meantime.

**Comment by coditva** [comment]
@cngrindstaff This is now fixed in the latest Postman version `7.19.1`.
