### ISSUE TITLE
IterationData is not getting reflected in local variable value

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#8056]
#7800

I think the issue is misunderstood.

I know that the local variable has more precedence than any other variable, but as per the documentation, local variables are temporary variable that gets destroyed in each iteration.

In a scenario where I have a variable 'a' coming from a data file, and if I set pm.variables.set('a',1) only for iteration 1. Then in iteration 2, I expect the local variable to get destroyed and the value from data file to get reflected .

But here the value will be still a=1 for all the remaining iterations

**Comment by coditva** [comment]
@praveendvd As @saswatds pointed out in this comment (https://github.com/postmanlabs/postman-app-support/issues/7800#issuecomment-587303377), local variables get destroyed after the whole run, not iteration.

You can probably use the global variables for your use case:
```javascript
pm.globals.set('a', 1);
```
This way, the data variables will take precedence.

If you have any more doubts feel free to re-open this issue or reply to #7800 itself since it contains all the discussion related to this issue.
