### ISSUE TITLE
When deleting an item like a collection, I would like to see the name of the collection in the header of the confirmation widow so I am sure I clicked the correct item

### ISSUE THREAD

**Issue by GregMotenJr** [a85/POSTMan-Chrome-Extension#8058]
I'd like to be sure of the item I am deleting/removing from the workspace (test, collection, folder). Sometimes I close it out of the delete confirmation pop up just to really make sure I clicked the right one so I am not deleting something I am actually working on.

Adding the name of the item in question to the top of the label during the confirmation window would be very helpful to make sure you are deleting the correct item.

![image](https://user-images.githubusercontent.com/20836347/74471478-4210fc80-4e6e-11ea-8ab2-c3054269a24e.png)

**Comment by sony-mathew** [comment]
Hey @GregMotenJr , this was fixed in one of the previous releases. At the moment you can see the Delete confirmation pop up shows the name of the collection or folder or request that you are trying to delete.

<img width="528" alt="Screenshot 2024-03-18 at 11 01 03 AM" src="https://github.com/postmanlabs/postman-app-support/assets/2040199/063914b8-124b-43f9-a12b-751b1b92463f">

Closing this issue as this is resolved.
