### ISSUE TITLE
Google Couldn't Sign in using Postman Window

### ISSUE THREAD

**Issue by carljustineoyales** [a85/POSTMan-Chrome-Extension#8059]
**Describe the bug**
I'm going to create a oauth token for pinterest api and when signing in to my pinterest account using google. it detects that it is not a supported browser

**To Reproduce**
1. Open Desktop Postman
2. Follow Pinterest API Documentation for POSTMAN
3. Sign in to google account

**Expected behavior**
Sign In to google account and verify pinterest app for pinterest api

**Screenshots**
![image](https://user-images.githubusercontent.com/51884760/74473544-bedbbf00-4ede-11ea-9167-a598c2786cd4.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Version 7.18.0
 - OS: Win10 64bit

**Comment by carljustineoyales** [comment]
I created a new gmail account and it works. But all of my work is in my old account and still cant connect to it

**Comment by shamasis** [comment]
Is your old account a gmail account or GSuite one?

**Comment by carljustineoyales** [comment]
> Is your old account a gmail account or GSuite one?

old account

**Comment by vikiCoder** [comment]
Hi everyone,

We've added an option in OAuth2 that allows you to authenticate using your system's default browser while generating OAuth 2.0 token.

To use this feature, select `OAuth 2.0` under `Authorization` tab and open `Get New Access Token` dialog box. You'll see a new checkbox `Authorize using browser` when `Authorization code` or `Implicit` grant type is selected. Selecting this option will allow you to use your external browser for authentication instead of using Postman's built-in browser.

However, selecting this option will automatically use the callback URL `https://oauth.pstmn.io/v1/callback`. You can't change this callback URL. This is necessary to return the generated token information back to the Postman app on successful authentication. So you'll have to whitelist this URL to be used as callback in your respective OAuth provider if required.

You can refer to [this link in our learning center](https://learning.postman.com/docs/postman/sending-api-requests/authorization/#requesting-an-oauth-20-token) for more details about generating OAuth 2.0 token. Here is a screenshot showing off this new feature. Please update to the latest Postman app (v7.24.0) and check it out. Let us know if you are still facing any issues related to this. Any feedbacks are welcome 🙂

![Capture](https://user-images.githubusercontent.com/16588032/81491083-6d598b00-92a7-11ea-937e-8b80f1f1cee5.PNG)
