### ISSUE TITLE
Postman should follow OS's preferred theme

### ISSUE THREAD

**Issue by mikestopcontinues** [a85/POSTMan-Chrome-Extension#8075]
**Is your feature request related to a problem? Please describe.**
Postman has a great light/dark theme, but a growing number of users allow their desktop/mobile OS to adjust the theme of ALL apps based on the time or ambient light conditions. This feature is excellent from a UX perspective, because it maximizes readability regardless of context (and it also seems to have a benefit regarding circadian rhythm).

**Describe the solution you'd like**
Postman should follow the OS's preferred theme (dark/light), or it should at least allow the option to do so.

**Describe alternatives you've considered**
The only alternative is manually adjusting the Postman theme, the one app I rely on that doesn't implement this feature.

**Additional context**
This issue is related to the following:

App theme:
https://github.com/postmanlabs/postman-app-support/issues/6485
https://github.com/postmanlabs/postman-app-support/issues/5302
https://github.com/postmanlabs/postman-app-support/issues/5294

Readability:
https://github.com/postmanlabs/postman-app-support/issues/2450

**Comment by guneyozsan** [comment]
It is becoming common to have apps follow OS setting so that we can adjust for the conditions we are working multiple times a day. (Not just day and night because lighting conditions may differ greatly in every location).

What's postman's approach to this?

**Comment by tduek** [comment]
+1, please implement! I switch the theme in the Postman app manually every day when macOS switches automatically (mine auto switches to dark at night and light during the day). Please enable an option for it to follow the system. Most other apps I use already do this. We're one of the only ones that don't.

**Comment by zeetabit** [comment]
+1

**Comment by jamesmehorter** [comment]
YES PLEASE! +1

**Comment by fuyuanyua** [comment]
一年多过去了，竟然还没有支持跟随系统切换主题

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/5817

**Comment by DevSumonBD** [comment]
Please fix the system default theme option.

**Comment by DSchau** [comment]
This is how it works as of Postman v11. [You can download it here](https://postman.com/download/) and read up more about all the improvements we've made in [v11 in our blog post](https://blog.postman.com/announcing-postman-v11/).

Specifically, we built in theming functionality so that you can customize the day and "night" theme to your heart's content, and by default, it syncs with the system default. As you can see, I'm a fan of Dracula and my default OS setting is dark mode, so I'm using Dracula by default unless I change it or the default.

<img width="837" alt="Screenshot 2024-05-09 at 14 16 18" src="https://github.com/postmanlabs/postman-app-support/assets/3924690/7eb38770-f226-4e74-b531-29f8022db3c3">

cc @jellevandevelde @chris-torruella
