### ISSUE TITLE
Link to APIs in the API Usage page

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#8103]
_Filed by Product Support_ 

**Feature request**
The API usage should provide a link to the API so that users can head to the API and find it easily.

**Comment by sankalp0o** [comment]
@cyrielle-hada thanks for the feedback! Currently, we show **who** has created API for all APIs in the team here - https://go.postman.co/usage/apis
Going forward, we'd also provide a link to the API so that users can visit the API and find it easily. I'll keep this ticket open and update it when we make this change.

**Comment by cyrielle-hada** [comment]
@sankalp0o sorry, I've completely missed this page: https://go.postman.co/usage/apis.

**Comment by sankalp0o** [comment]
With the release of Postman v7.30, API usage limits have been removed!
