### ISSUE TITLE
Postman doesn't send GET query params when using Environment variables.

### ISSUE THREAD

**Issue by abdulghani** [a85/POSTMan-Chrome-Extension#8112]
Postman didn't send GET query parameters when using the `env variables`

Screenshots
![image](https://user-images.githubusercontent.com/11703983/75429447-64ca0780-597c-11ea-971a-8bba82f3a11a.png)

however, when sending the request through literal url, it sends the param
![image](https://user-images.githubusercontent.com/11703983/75429540-87f4b700-597c-11ea-8de2-d9679f249865.png)

my env variable
![image](https://user-images.githubusercontent.com/11703983/75429610-a490ef00-597c-11ea-9356-d4f7236ea734.png)

App information:
 - Native App
 - PostmanRuntime/7.22.0
 - OS: macOS Catalina 10.15.3

**Comment by coditva** [comment]
Hey @abdulghani, it seems to be working for me:
![image](https://user-images.githubusercontent.com/8445768/76392077-e0717e80-6396-11ea-95b8-7650e5284ba4.png)

Can you try it again in the latest Postman app (7.20.0) and let me know if it's still re-producible?

**Comment by coditva** [comment]
Hey, looks like your environment variable has a newline. This causes the query parameters to not get sent!

This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.

Feel free to leave your feedback at #8154 or reopen this thread if the issue persists.
