### ISSUE TITLE
Update collection endpoint is particularly strict on request body

### ISSUE THREAD

**Issue by matt-ball** [a85/POSTMan-Chrome-Extension#8149]
**Is your feature request related to a problem? Please describe.**
`PUT https://api.getpostman.com/collections/{{collection_uid}}` 

One use case for this endpoint is updating related collections - if I have a collection as the source of truth in a team workspace, but have a duplicate copy in my personal workspace, should I wish to update the version in my personal workspace, I `GET` the collection from the team workspace, then look to run `PUT`(update) on the collection in my personal workspace.

I'm sure there are many other use cases where you might take the contents of one collection to apply to another.

This returns the following `400 Bad Request` error:

```
{
    "error": {
        "name": "instanceFoundError",
        "message": "This collection already exists in the database."
    }
}
```

1) This is a confusing error because if I am updating a collection, the fact the collection already exists is a given - that should not be a reason for failure.
2) This behavior is not described in the examples/documentation:
https://documenter.getpostman.com/view/631643/JsLs/?version=latest#aa3701e8-7f99-b421-7d74-0d571b051f3c

This appears to be because of `id`'s sitting within most elements of a collection. If these are removed, the collection can be updated. It's not straightforward to crawl the collection JSON yourself to remove all these IDs.

**Describe the solution you'd like**
- Error messaging improved
- The endpoint is less strict on the request body/IDs are ignored/stripped for you

**Describe alternatives you've considered**
For my use case, I now run a `DELETE`, followed by a `POST` in order to get the same effect, rather than manipulate the collection JSON. 

**Additional context**
https://community.postman.com/t/publishing-documentation-to-custom-urls-for-each-environment/7088

**Comment by davidespihernandez** [comment]
Sorry for the late reply, @matt-ball.

Currently, Postman allows forking a collection in your personal workspace. A forked collection can be updated by pulling changes from the original collection. I think that could be a more convenient workflow for you. Please have a look at https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-entities/ for more information.

However, you are right about the Postman API. We are going to change the API to use only the collection id in the path, and ignore the `_postman_id` field in case it's sent in the body.

**Comment by davidespihernandez** [comment]
Hi, @matt-ball!
This error is already solved. Please let me know if you find any other problem.
Regards,
David.

**Comment by davidespihernandez** [comment]
I know this is closed, but I'll add a new comment here for future reference.
The PUT collection **needs** the IDs and UIDs in the request body if you are updating an existing collection (which should be the case). If these IDs are not passed, the existing requests, responses, and folders will be deleted, and new ones will be created. The result is apparently correct, but internally, it is very different.
If you want to read a collection and then use the response to update another different collection, you **must** remove the IDs and UIDs fields in the response, or use the ones in your new collection, to make a successful request. Otherwise, the request will fail, and that's actually the expected behavior.
