### ISSUE TITLE
Postman Canary: Unable to Edit Path Parameters Descripion

### ISSUE THREAD

**Issue by jcald1** [a85/POSTMan-Chrome-Extension#8200]
I'm running Version 7.21.0-canary04 (7.21.0-canary04) on Mac OS.  

I'm trying to edit a collection's path variable's.  I can't edit the value or description.  The typed characters don't appear in the text boxes.  I can edit the Key.  The collection was previously created with the regular version of Postman.  

I can click Bulk Edit and edit the values, but I'm not sure how to enter in the Description in Bulk Edit mode.

This is what I have in Bulk Edit right now: "groupIds:{{currentMediaGroupId_Publish}},{{currentMediaGroupId_PublishUnpublish}}"

**Comment by appurva21** [comment]
Hey, @jcald1 thank you for reporting this. 
I was able to reproduce the issue for the description column only. 
Can u please verify once if this issue is also there with the value column as you have mentioned. If so, it would be very helpful if you could provide us with more information that might help us in reproducing it.

Thanks

**Comment by appurva21** [comment]
Hi @jcald1, we have fixed this issue and is available in the latest Postman Canary app `v7.22.0-canary02`.
