### ISSUE TITLE
Cookies from cookie manager, get injected into cookie header

### ISSUE THREAD

**Issue by forgotPassword** [a85/POSTMan-Chrome-Extension#8214]
I don't know if this is some magic feature or a bug.

If I set the header cookie:

`cookie:a=1;`

All works as expected.

But if I remove the semicolon,

`cookie:a=1`

~~Postman injects the cookies from the cookie manager~~. This was not expected, and had no visual indication. Luckily in postman console, I could see the raw request and figure something was wrong.

Win10, Postman v7.20.1.

**Comment by coditva** [comment]
Hey @forgotPassword I was not able to reproduce this issue with the information you provided. Can you check that there are cookies present (or not present) in the Cookies manager when you send request in both cases (with and without semicolon)?

If cookies are present in the Cookies Manager, they will be sent with the request in both cases.

You can also try out the new live preview of headers which show the headers for the request before actually sending it. This feature is in [Postman Canary](https://www.postman.com/downloads/canary). Please do try it out!

**Comment by forgotPassword** [comment]
You are right, it appears Postman always sends cookies. Sorry for the wrong information. It just didn't cause issues before. How can I disable this behavior? If I want an explicit control over 'Cookie' header? Do I have to clear the cookie manager after each request?

Edit:
The issue was, if `a=1;` Postman sends `Cookie: a=1;; ..other cookies..` with 2 semicolons. This for some reason confuses the server, and it (I assume) ignores the rest of the cookies. Are double semicolons meet spec? Thanks!

**Comment by coditva** [comment]
@forgotPassword You're in luck! We just added an option to disable using cookies from the Cookie manager: "Disable cookie jar"

![image](https://user-images.githubusercontent.com/8445768/77392675-7eb30a80-6dc1-11ea-9d27-0981ded340ab.png)

You can find it in the "Settings" tab for your request in Postman `v7.21.0` 🎉 

For the issue where two `;` are added, it is because when there are multiple headers with cookies, we send a single header with all the cookie values by joining them with a `;` as expected.

Hope that helps! Do let me know if you have any more questions. :)
