### ISSUE TITLE
Feature Request:  Dock Postman Console

### ISSUE THREAD

**Issue by maplion** [a85/POSTMan-Chrome-Extension#8219]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to be able to dock the Postman Console as part of the main window and open it and use it by default.  Would be nice to have both bottom and side-dock options.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by shurrey** [comment]
upvote

**Comment by vvs11** [comment]
@maplion We have released this in Postman v7.28. Please check it out and let us know your feedback

**Comment by kabbottcc** [comment]
Came here because I had the same question. Am using 8.9.1, so theoretically this should be available.  Bottom implies it's displaying the console (underlined tab title), but it's only showing the response data, no error data. Error count is displayed in the console title bar, but it's not selectable/clickable.. There doesn't appear to be a way to view the logs without going to View > Show Postman Console.  This only displays the console in a separate window.

I'm sure it's there and I'll eventually figure it out, but this doesn't feel like it was implemented well from a user perspective.

**Comment by aleksey-korolev** [comment]
I was struggling to find dockable console too, so posting it here to save time for all the other users looking for this:
in Postman (my current version is 9.31.8) there are 2 independent console windows, one is floating, accessible from View top level menu, the other is docked at the bottom, accessible from bottom status bar, see screenshot:
![image](https://user-images.githubusercontent.com/2145883/199953316-1928e043-aac6-4bc4-8bdb-f0cb161b9362.png)
