### ISSUE TITLE
Option to use id_token instead of access_token from OAuth 2.0 Flow

### ISSUE THREAD

**Issue by chriskinsman** [a85/POSTMan-Chrome-Extension#8231]
Currently when using an OAuth 2.0 flow with a number of idp (Azure AAD, Auth0) they return both an access_token and an id_token.  Postman will only use the id_token by default when you click use token.  Many apis require you to use the id_token instead.

**Describe the solution you'd like**
Give me an option of which token to use!

**Describe alternatives you've considered**
Work around is to go into manage tokens, select the id_token, close manage tokens and paste this value into access token.  A hassle with a feature that is so close. 

**Additional context**
I have seen several other requests for this going back almost 5 years.

https://github.com/postmanlabs/postman-app-support/issues/1854
https://community.postman.com/t/copy-id-token-from-manage-access-tokens/5734

Please consider finally fixing this issue.

Thanks!

**Comment by buszu** [comment]
Hey, I'm not sure if the issue is related to requesting a token or using tokens received, but maybe it's a right place to ask for a possibility to set `response_type` parameter on OAuth2 implicit flow. Some auth providers (auth0) require setting it to 'id_token token'.

**Comment by kappaj2** [comment]
With the different providers, this will be absolute gold to be able to select which of the tokens to use. PLEASE PLEASE Postman!!

**Comment by andrew-luminal** [comment]
Adding a +1 to this, really would help for those of us using Auth0

**Comment by zaboslav** [comment]
It is not nice but I did some workaround:
In file: resources/app/js/RequesterModalContainer.js, class OAuth2TokenDetails, in render I added this :
```
  render() {
    // My modification - start
    if (!this.props.token.access_token && this.props.token.id_token) {
        this.props.token.access_token = this.props.token.id_token;
    }
    // My modification - end

    let token = this.props.token,
    maskedToken = _.pickBy(token, (detailValue, detailName) => {
      return !_.includes(BANNED_DETAILS, detailName);
    }),
    isAccessTokenMissing = !token.access_token,
    isTokenTypeIncorrect = token.token_type && token.token_type.toLowerCase() !== 'bearer';

```
It works.

For Windows users:
Required file is part of app.asar on Windows. So, you can unpack file c:\Users\{username}\AppData\Local\Postman\app-{version}\resources\app.asar, add my modification and pack it again. We have fould no issue with it.

How to install asar: install npm from website. Install asar `npm install -g asar`  other command:
```
copy app.asar app.asar.backup
asar extract app.asar folder
```
Modify folder\js\RequesterModalContainer.js
```
cd folder
asar pack . ../app.asar
```

**Comment by JanC** [comment]
Hi,
I'm in the same situation. I use Auth0 and need to send the `id_token` and not the `access_token` from OAuth flow. Without this, using Postman becomes impossible :/

**Comment by zaboslav** [comment]
> Hi,
> I'm in the same situation. I use Auth0 and need to send the `id_token` and not the `access_token` from OAuth flow. Without this, using Postman becomes impossible :/

JanC, I've just added description relevant for OS window, modification is pretty easy and works without any problem.

**Comment by JanC** [comment]
yes I've seen it, thanks. However, I'm evaluating Postman to be used in a company environment where several people would use it.

Another workaround is to use the pre-request script that takes care of the OAuth exchange

https://gist.github.com/bcnzer/073f0fc0b959928b0ca2b173230c0669

**Comment by CaptainStealthy** [comment]
Is there any other workaround for this? I'm trying to test my Azure AD OAuth app with Postman, and the fact that Postman doesn't even show me the id_token is ridiculous. This is making it impossible for me to even use Postman at this point. :|

**Comment by nkalra0123** [comment]
Auth0 authentication needs the audience, 

Token Name | Any name you like

Grant Type | Authorization Code
Callback URL | https://www.getpostman.com/oauth2/callback
Auth URL | https://{{auth0_domain}}/authorize?audience={{auth0_audience}}
Access Token URL | https://{{auth0_domain}}/oauth/token
Client ID | {{auth0_client_id}}
Client Secret | {{auth0_client_secret}}
Scope | openid profile email
State | Some random string of your choosing
Client Authentication | Send client credentials in body

Create an API in auth0 and set auth0_audience to identifier name 
https://auth0.com/blog/manage-a-collection-of-secure-api-endpoints-with-postman/#Authorization-in-Postman

**Comment by olegkorol** [comment]
Any updates on this?

**Comment by Venkatavarun** [comment]
@postman-support @abhijitpostman any update on this one?

**Comment by sathyarajagopal** [comment]
+1

**Comment by DanielLaberge** [comment]
We need to use the id_token to test our APIs. We won't purchase a Postman subscription until this is supported.

You're already so close! All you're missing is an option to specify which token to use (access_token vs id_token).

**Comment by DanielLaberge** [comment]
Our team is giving up on postman based on this. I'm writing this as a warning for other devs finding this through Google.

Turns out that this [issue](https://github.com/postmanlabs/postman-app-support/issues/1854) has been [reported](https://github.com/postmanlabs/postman-app-support/issues/6987) as far [back](https://github.com/postmanlabs/postman-app-support/issues/1464) as [2014](https://github.com/postmanlabs/postman-app-support/issues/492) with no commitment ever given...

**Comment by DanielLaberge** [comment]
I was about to give up on postman since it turns out that this [issue](https://github.com/postmanlabs/postman-app-support/issues/1854) has been [reported](https://github.com/postmanlabs/postman-app-support/issues/6987) as far [back](https://github.com/postmanlabs/postman-app-support/issues/1464) as [2014](https://github.com/postmanlabs/postman-app-support/issues/492) with no commitment ever given...

But I ended up implementing a workaround using a pre-request script that exchanges an OAuth2 refresh_token for an id_token. You can find it here: https://gist.github.com/DanielLaberge/5c311b7adb835efc004fcc8e1ea7822a

**Comment by Elip-tdlr** [comment]
This seems like such a simple change. Just support configuration for the attribute name. Why has this been an issue for like 7 years! Not being able to auth using OIDC with B2C or other providers with `id_token` is ridiculous.

**Comment by kappaj2** [comment]
Man - I wish I could just move my work out like this...
`saswatds moved this from Pending triage to Later in Runtime Triage and Development on 21 Jul 2020`
So a year later and still no feedback, no new feature, nada, nothing....
Postman being our tool of choice for running tests with Newman and testing e2e. 
Please guys - just this one change!!!!!! Beg you guys!

**Comment by giridharvc7** [comment]
We will take this as a part of our roadmap to enabling Open ID connect in OAuth2.

**Comment by kappaj2** [comment]
> We will take this as a part of our roadmap to enabling Open ID connect in OAuth2.

Great stuff guys - this will be an amazing feature!

**Comment by MrBenGriffin** [comment]
> We will take this as a part of our roadmap to enabling Open ID connect in OAuth2.

Erm - when would that be?
It's a feature we've needed for a few years now.

**Comment by dominicfarr** [comment]
+1 for this feature. I would like to use id_token, not access_token

**Comment by andrewcarretta** [comment]
Shocking that this is not implemented. +1 for this feature.

**Comment by mitchell-garcia** [comment]
+1 for this. It's a blocker for using OAuth 2.0 as an authorization type for any API Secured by Auth0 which is a bummer. 

Postman is able to get the token it's just not accessible in request. `Access Token` value is taken, and there's no way to access it programmatically (i.e. `managedTokens.id_token`).

**Comment by joshtrotter** [comment]
+1 this feature will be hugely appreciated

**Comment by milosloub** [comment]
Same issue here. In my case I need to set response_type=token id_token. This feature would be super cool.

**Comment by alexei-moneyr** [comment]
+1. please please add

**Comment by vladimirblaz** [comment]
+1 hey guys, any update on this? Auth0, Azure AAD, AWS Cognito, etc, use id_token, it isn't a particular case...

**Comment by zyrif** [comment]
I don't understand why this issue is in the backburner. The 'Use Token' button only picks the access_token when many IDPs expect the id_token. This is one of those subtle details which you can easily miss and waste hours trying to figure out why the API is returning 401 when the Authorization header is being passed properly. Or am I the only one stupid enough to experience this?

**Comment by jake-unl** [comment]
+1 on this. Seems like it should be a simple fix that would save a lot of hassle

**Comment by zzFluke** [comment]
I guess and hope that above-mentioned "Roadmap to enabling Open ID connect in OAuth2." will have more then just fix for this particular issue and has much broader scope. **The other one, not less needed feature is proper handling of the 401 and utilize refresh_token to obtain new access_token/id_token.**

Does anybody know the place where there is a place for roadmap item and release timeline?

**Comment by Buzzology** [comment]
+1 on this

**Comment by justinhrobbins** [comment]
count me as another +1

**Comment by alexei-moneyr** [comment]
guys!!!! its been two years now!
Please add this option. Please!

**Comment by tgpadua** [comment]
+1

**Comment by nathankitchen** [comment]
And one more.

**Comment by dat-producepay** [comment]
+1

**Comment by vadymhimself** [comment]
+1

**Comment by sstefanov94** [comment]
+1

**Comment by MrBenGriffin** [comment]
> We will take this as a part of our roadmap to enabling Open ID connect in OAuth2.

We are no longer recommending Postman due to #8231. 
I note that 8231 doesn't even feature on your roadmap. 
It would be remiss of me to mention that, of all the fine work you seem to have stacked yourselves with, this one issue is *far and away* the most important for you to fix.

**Comment by cvietor** [comment]
+1 
any updates on this one?

**Comment by AndreasHuber-CH** [comment]
+1
I'm also interested to get this issue fixed, any news?

**Comment by esoca** [comment]
+1 
Another team that needs this issue fixed ...

**Comment by andakawa** [comment]
Guys, cmon now - it's been years now.

**Comment by cjuega** [comment]
@esoca @AndreasHuber-CH @cvietor... If you guys are still interested on this _and you can use vscode instead of postman_, this very same issue has been just fixed in the ThunderClient vscode extension:
https://github.com/rangav/thunder-client-support/issues/304

(credits to @rangav)

**Comment by timreibe** [comment]
+1

**Comment by andakawa** [comment]
+1

**Comment by jf-paquin-web** [comment]
+1

**Comment by giridharvc7** [comment]
I'd like to understand your workflows around tokens a bit deeper, would anyone be willing to join a quick meeting with me for this? Feel free to use this [link](https://calendly.com/giridhar-vc-postman/hello) to schedule a call

**Comment by MrBenGriffin** [comment]
I should be able to meet sometime soon.

**Comment by AndreasHuber-CH** [comment]
Hi, in my case my need seems pretty straightforward:
I'm working on some project where a mobile client sends the "id_token" in API calls to our backend. (For some reason the "id_token" is required instead of "access_token", but that's not something I can or want to change right now).

To be able to test the backend API with postman, I need to get the "id_token" somehow and be able to set it as Bearer token in the Authentication header.
The OAuth 2.0 authorization flow in Postman *almost* does that. I can login and see all three token "access_token", "id_token" and "refresh_token". But I cannot chose which one to use in REST calls.

As a workaround. I can copy the value of "id_token" that postman displays and paste it into the "Access Token" field after closing the dialog. But this is not so much fun and refreshing the token automatically does not work in this case.

So if there would be a drop down that let's me chose whether "access_token" or "id_token" is included in the REST requests, that would be perfect.

**Comment by dat-producepay** [comment]
@giridharvc7 My use case is exactly as described by @AndreasHuber-CH : https://github.com/postmanlabs/postman-app-support/issues/8231#issuecomment-1180106429

I'm guessing most people on this thread have the same issue.

**Comment by cvietor** [comment]
Same here, use case as described by @AndreasHuber-CH

**Comment by esoca** [comment]
Same use case @AndreasHuber-CH : https://github.com/postmanlabs/postman-app-support/issues/8231#issuecomment-1180106429

**Comment by wilkovanderveen** [comment]
Am I doing something wrong in my backend api, asking the user to provide the id_token instead of the access_token? My proof of concept works, but postman does not have the option to use the id_token instead of the access_token. Should I change my API to require both the id_token and the access_token? because I dont want to have an extra call from the API to the IDP to request the userinfo (how would I do that anyway with only an access_token).

**Comment by zzFluke** [comment]
@wilkovanderveen you can read some info here - https://auth0.com/blog/id-token-access-token-what-is-the-difference/, however I've seen commercial IdPs to disobey this practice and recommend id_token to be used by Resource Server - https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-id-token.html. Anyway, I still believe that Postman can have this flexibility.

**Comment by jsiragusa** [comment]
also same use-case as @AndreasHuber-CH.  @giridharvc7 I am happy to meet with you to describe in more details if that is helpful, just let me know.

**Comment by TheInvoker** [comment]
Any updates on this yet? really need this feature.

**Comment by brandonyoung** [comment]
+1

**Comment by tinkermakar** [comment]
+1

**Comment by time-to-beem** [comment]
+1
Same here
That is crazy it is still open in 2022. Especially as it seems really easy to fix

**Comment by zackbrown-producepay** [comment]
A bit shocked to see all the requests for status updates going unanswered. Can we please receive some ETA, or at least some status update, for this feature?  While the proposed workaround does work, it isn't very intuitive and has caused a lot of friction in our workflows. It sounds like such a small feature with low priority, but it is becoming increasingly difficult to drive user-adoption within my team for our Postman collection due to this. Since our API utilizes id tokens, most people would rather use other, more intuitive solutions over Postman instead of following the workaround provided. 
API testing can be a fairly tedious process, so any additional, seemingly frivolous steps greatly degrade a user's experience.

**Comment by ghassett** [comment]
I agree, it's shocking that this simple and very important feature has not been implemented yet -- please, POSTMAN, let's allow OATH2 authentication flow to capture `id_token` for use in subsequent requests.

**Comment by wrkntwrkn** [comment]
+1 (have to manually do it every time it expires atm... copy id_token -> paste in access token)

![image](https://user-images.githubusercontent.com/94405711/199455626-fcf7118c-53c8-4bed-a21d-3f3897243ab3.png)

**Comment by gperego-pirelli** [comment]
+1

**Comment by angeldima** [comment]
+1

**Comment by exinmusic** [comment]
<img src="https://www.meme-arsenal.com/memes/4a60db49ea0c4fd3bfc99bbf7e781062.jpg" alt="please help" width="200"/>

**Comment by ghost** [comment]
+1

**Comment by sgoodluck** [comment]
There is a useful article here: https://auth0.com/blog/id-token-access-token-what-is-the-difference/

**Comment by DieCi007** [comment]
+1

**Comment by angeldima** [comment]
+1

**Comment by DieCi007** [comment]
> +1 (have to manually do it every time it expires atm... copy id_token -> paste in access token)
> 
> ![image](https://user-images.githubusercontent.com/94405711/199455626-fcf7118c-53c8-4bed-a21d-3f3897243ab3.png)

+1

**Comment by AndreasHuber-CH** [comment]
I've read again a bit through the oauth docs. And I understand now better why this option doesn't exist in the first place:
The id_token is intended for the party that performed the login, and it is not supposed to be share it with anyone else.
(e.g. a mobile app wants to be able to display username, email, phone number, etc. of the logged in user)

For any API call, the access_token should be used.
And any API service that wants to access personal user info that is typically contained inside the id_token is supposed to request this information itself from the identity provider using his clientId (+clientSecret) & the received access_token.
By doing that each API service will only get access to personal user information authorized for the corresponding app client.

If you just send the id_token to an API service, potentially detailed user information (like email, phone number, address, ...) could be shared with the API service unintentionally.

And the opposite works as well. You could authorize access to some personal user information only for an API service, but not for the app client that performs the initial login - in that case this info would not even be in the id_token, but will still be available to the API service.

But from this thread here I can see that many people did use the simplified solution of sending the id_token around, to skip having to call the identity provider in each API call to get access to the user information.
So it would still be cool if Postman could support this small feature. Or do they intentionally not provide this feature so that people rather think about fixing their usage of oauth?

**Comment by wilkovanderveen** [comment]
@AndreasHuber-CH  nice work diving in to this I am also going back to the drawing board to fix this, and check up with the guys from ForgeRock/OpenAM to take a look at this also.

**Comment by zackbrown-producepay** [comment]
EVERYONE! I just opened Postman and saw this beautiful dialog: 
![image](https://user-images.githubusercontent.com/98350830/210963538-b60e8b75-38dc-4e02-a8df-079e3c5f63d2.png)

I have been unable to update to this version and confirm if it is working as intended yet, but it looks like IT IS COMING!!!!! 🥳

**Comment by raman-nbg** [comment]
![image](https://user-images.githubusercontent.com/20013423/211000353-5362fcf5-099e-4cf6-9d12-9710c9bd13cb.png)

**Comment by abhijeetborole** [comment]
Thank you for being patient with us. The ID token option will be available with Postman V10.7.

With these changes, this option will be available for any new token you generate which has a valid `id_token`. This can also be refreshed with the current refresh flow alongside `access_token`

This is only available for signed in users right now, we’ll add support for `scratchpad` soon.

Do let us know if you have any issues.
PS : Postman app v10.7 is being rolled out will be available for everyone in couple of days

![OAuth2 ID Token](https://user-images.githubusercontent.com/9638586/211007228-a580d8dd-c7b8-4fe5-9cf3-88875fd8d5e9.gif)

**Comment by kappaj2** [comment]
Wow - what a good start to this year! Thank you guys... amazing !

**Comment by Employee87** [comment]
When will support for scratchpad come out?

**Comment by giridharvc7** [comment]
@Employee87  Support for id token and token refresh in scratchpad is in our priority.  We'll keep you posted here. Keep this ticket open till we roll that out

**Comment by jhsenjaliya** [comment]
@giridharvc7
+1, thanks for this useful feature, I had to manage this via variable earlier. - better late than never!

btw, token type selection goes back to access_token once user refreshes it via "get new access token". it should stay to what user has selected.

**Comment by Employee87** [comment]
Any ideas when this will come out? Still waiting for scratchpad support badly.

**Comment by abhijeetborole** [comment]
@Employee87 support for scratchpad will be out with the next release. It will be rolled out in the next few days.

**Comment by Employee87** [comment]
@abhijeetborole  10.9.0 came out but scratchpad support wasn't listed in the release notes, and I don't see any option for it when I try it out in postman. Is it still pending to come out?

**Comment by abhijeetborole** [comment]
@Employee87 We released it with 10.9.0. Could you share your version from `Settings` -> `About`? The option to select an `ID token` will show up once you generate a token with `id_token` in response.
![Screen Recording 2023-01-31 at 9 17 34 PM](https://user-images.githubusercontent.com/9638586/215808698-73367061-7efa-4c81-bb8f-b5587788328d.gif)

**Comment by Employee87** [comment]
When I try it out, the browser opens and says `Your call is authenticated`. But then in postman I get an error saying `Error: AADSTS900144: The request body must contain the following parameter: 'client_id'.↵
Trace ID: af9f67a3-ec48-4ba7-871d-48171bbcf200↵
Correlation ID: 0d27a51d-c98d-4519-a78c-4a20f7ef534e↵
Timestamp: 2023-01-31 15:54:18Z`

And I definitely have client_id set in the field.

**Comment by abhijeetborole** [comment]
@Employee87 Are you seeing this error when generating an access token? Could you try generating it with `Client Authentication` set to `Send client credentials in body`.
![image](https://user-images.githubusercontent.com/9638586/215813988-51c6dabe-3e64-4de7-9d5c-1cd015a736b6.png)

**Comment by giridharvc7** [comment]
We've released the support for `id_token` to scratchpad with version 10.9.x
Closing this ticket now. Thank you everyone for your patience. 🙏

**Comment by Employee87** [comment]
> @Employee87 Are you seeing this error when generating an access token? Could you try generating it with `Client Authentication` set to `Send client credentials in body`. ![image](https://user-images.githubusercontent.com/9638586/215813988-51c6dabe-3e64-4de7-9d5c-1cd015a736b6.png)

Yes it is working now.

**Comment by av-2024** [comment]
> btw, token type selection goes back to access_token once user refreshes it via "get new access token". it should stay to what user has selected.

This is a constant source of confusion on my teams.

**Comment by chrisjaimon2012** [comment]
> This is a constant source of confusion on my teams.

@abhijeetborole will the defaulting to `access_token` be fixed anytime soon?
