### ISSUE TITLE
Postman 7.21 hangs on Preparing workspaces

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#8234]
**Describe the bug**
After auto installation Postman failed to start

**To Reproduce**
1. install Postman 7.20
2. Run Postman-win32-7.21.0-Setup.exe
3. See flying balls "Preparing your workspaces"

**Expected behavior**
After update Postman expected to run

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.21
 - Windows 7 32 bit
![pr](https://user-images.githubusercontent.com/25632818/77449865-901d0680-6e03-11ea-93e0-f23d60c1ef2d.JPG)

**Comment by m3dbedb** [comment]
Temporary solution to update 7.20 to 7.20.1
Same issue under windows 10 64, but it says "unable to connect to authentification service, use email authorization instead"

**Comment by harryi3t** [comment]
Hey @m3dbedb 
We are tracking this issue here https://github.com/postmanlabs/postman-app-support/issues/6723

Can you share with us the logs from `%USERPROFILE%\AppData\Roaming\Postman\logs` or at help@getpostman.com? It would really help us triage and fix the issue.

Please mention the GitHub issue ID (8234) in the subject line.

**Comment by m3dbedb** [comment]
done
