### ISSUE TITLE
Preview Request button missing in latest version of postman.

### ISSUE THREAD

**Issue by yv1989** [a85/POSTMan-Chrome-Extension#8244]
When i select Basic Auth in Authorization tab , i am not seeing Preview Request.

In screenshot you can see it present in previous versions.

Postman : 
Version 7.21.1 (7.21.1)
Mac os: 10.14.6 (18G3020)

![Screenshot 2020-03-25 at 4 36 45 PM](https://user-images.githubusercontent.com/7301656/77595918-be5c1e00-6eb7-11ea-84cc-004b94aa2990.png)

**Comment by appurva21** [comment]
Hi @yv1989,

With the release of the Postman App `v7.21.0`, we have made previewing of a request super easy. So instead of every time clicking the `Preview Request` button to check your headers, now all the headers that are going to be sent with your request will be added to the Headers tab dynamically. 

So, in this case, you can directly go to the Headers tab after adding the Basic Auth to see the `Authorization` that is going to be sent with your request.

![preview-basic-auth](https://user-images.githubusercontent.com/24985700/77612901-53f6bc80-6f4f-11ea-9f25-06e47222ff09.gif)
