### ISSUE TITLE
Exporting collection should export tests

### ISSUE THREAD

**Issue by pksilen** [a85/POSTMan-Chrome-Extension#8258]
When exporting a collection and I have defined tests in requests, it should export the javascript code of the tests also. And when importing a collection, it should import the javascript code of tests also.

**Comment by cyrielle-hada** [comment]
@pksilen Postman allows the export of test-scripts at collection, folder, and at request level. I wasn't able to reproduce the behavior locally – request level scripts were successfully exported.

Would you please make sure the test script is saved before exporting the collection? 

If the issue persists, please submit a support ticket from this page: https://support.getpostman.com/hc/en-us/requests/new.

**Comment by DannyDainton** [comment]
As there has been no response in 8 months - I'm going to close this issue.

**Comment by swmech** [comment]
I know, leaving a comment on a closed issue.  But I was just bit by this one myself.  The issue IS the "Save" button, as @cyrielle-hada noted.  If the request isn't saved then some changes (Request name, for example) DO export, but others (test scripts, in this case) do NOT.

Let's face it, the "Save" button isn't incredibly obvious.  You can make all the changes to a request that you want and not notice it.  So is it feasible to add a "You have unsaved changes" message to the export process?

**Comment by theqa-ninja** [comment]
I just hit this issue also.  I had written tests, but none were being exported by default even after the save.  The export file has no `test` entry for any of the APIs in my collection.

So what I did was modified the body of each one with a space, saved it, then removed the space, and saved it again.  Then when it exported it had all the tests being written in the export file.

**Comment by vedkribhu** [comment]
@theqa-ninja I am not able to recreate this issue on my end. It will help if you can share your screen recording if you are able to recreate this. Also since this issue might be related to not saving the request/collection, I recommend checking out the new autosave setting described here: https://learning.postman.com/docs/getting-started/installation/settings/#application
