### ISSUE TITLE
Unable to create collection from API

### ISSUE THREAD

**Issue by spenceclark** [a85/POSTMan-Chrome-Extension#8275]
When trying to create a collection from an API definition, I get an error message 

> "SyncRequestService~request: Undefined response returned"

In the log files I get:

`[4689][1585831162781][requester][warn]["APIDevService~generateCollection: Failed to generate collection from schema",{"error":{"message":"SyncRequestService\\x7erequest: Undefined response returned"},"headers":{"Access-Control-Allow-Credentials":"","Access-Control-Allow-Headers":"","Access-Control-Allow-Methods":"","Access-Control-Allow-Origin":"","Access-Control-Expose-Headers":""},"status":500}]
`

This happens from 2 different computers of mine.

**To Reproduce**
1. Go to and API defintion
2. Click on 'Generate Collection'
3. Enter a new Collection Name and chose type of "Documentation"
4. Press "Generate Collection"

**Expected behavior**
I expect a collection to be generated

**App information (please complete the following information):**
 - App Type - NativeApp on Linux, NativeApp on Mac, Website via Chrome
 - Postman Version - 7.21.1
 - OS: Linux Mint, MacOS 10.15.3

**Comment by sankalp0o** [comment]
Thanks for letting us know @spenceclark , this shouldn't be happening and we'll immediately take a look!

**Comment by jazzyarchitects** [comment]
@spenceclark This seems like an intermittent issue. Can you check if this is still happening with your schema?

**Comment by spenceclark** [comment]
Its still happening for me both from the Postman Native App and the Postman Website

**Comment by jazzyarchitects** [comment]
@spenceclark Would you be able to share your Specification here or can you send it to help@getpostman.com ?

**Comment by spenceclark** [comment]
> @spenceclark Would you be able to share your Specification here or can you send it to [help@getpostman.com](mailto:help@getpostman.com) ?

Sure - its sync'd to github already - https://github.com/portemis/api-documentation/blob/master/Portemis.json

**Comment by jazzyarchitects** [comment]
Hi @spenceclark, we have identified an issue with our systems when trying to convert this schema. We are working on a fix and should be available soon. We will inform you when the fix is ready. Thanks for bringing this to our attention.

In the meanwhile, there is an alternative approach you can use. Kindly follow the steps 1-7  as shown in the screenshots.

Once you have completed these steps, a collection generated from the schema should have been created in your account (you can check the collections tab to find collection) after which you can link this collection as documentation to the API.

<img width="888" alt="Github 1" src="https://user-images.githubusercontent.com/11012686/78389194-f4a84480-75ff-11ea-9166-ff135846aa61.png">
<img width="957" alt="Github 2" src="https://user-images.githubusercontent.com/11012686/78389201-f8d46200-75ff-11ea-9ba0-8b139ce58c4a.png">


<img width="548" alt="Github 3" src="https://user-images.githubusercontent.com/11012686/78388559-d55ce780-75fe-11ea-932c-c8bac8f5f199.png">

**Comment by jazzyarchitects** [comment]
@spenceclark We have deployed a fix for this and you should now be able to directly generate a collection from your schema. Can you check and let us know if it works for you now?

**Comment by sankalp0o** [comment]
I'm closing this issue as this bug was fixed. If you continue to face the same problem, please let us know! Thanks again for reporting :)

**Comment by denitsa-md** [comment]
I am getting the same error (on the canary version as well) - cannot generate a mock nor a collection from an API.

**Comment by jazzyarchitects** [comment]
@denitsa-cm Would you be able to share your API specification here or mail at `help@getpostman.com` so that we can take a deeper look?

**Comment by denitsa-md** [comment]
Hey @jazzyarchitects , the mistake was all mine - I had a small error in the schema. I started just trying to create it piece by piece, gradually adding stuff until I started getting the error. However, since the error I was getting was a 500 I thought it was something else that didn't have to do with the schema being invalid.

Thanks for the quick reaction, you can disregard my comment!

**Comment by jazzyarchitects** [comment]
Hey @denitsa-cm, thanks for the feedback regarding the error messages. We are currently working on having more understandable errors and you should be able to see improvements regarding this soon.

**Comment by nathando** [comment]
Hi, on latest Postman desktop version (v9.17.2), I cannot deselect Import as API if I've signed in. If I didn't sign in, the default is import as Collection and this works fine.
