### ISSUE TITLE
Postman crashes when handling large responses

### ISSUE THREAD

**Issue by akhsiM** [a85/POSTMan-Chrome-Extension#8288]
This issue is related to #4751 & #7232, 

 # Steps to reproduce

1. Open Postman
2. Select POST and type URL
3. Insert appropriate Body
4. Hit Send
5. Wait..
6. Initial response is displayed:

![image](https://user-images.githubusercontent.com/50348688/78500782-d70fe200-779b-11ea-8aa3-f481d6765bdf.png)

then Postman blacks out and becomes non-responsive:

![image](https://user-images.githubusercontent.com/50348688/78500794-e727c180-779b-11ea-8558-44816ae0d2c8.png)

## Additional Note

This behaviour also happened when Postman tried to handle a large response from a GET request.

# Log

I'm unsure if this would be helpful but these are collected from Terminal when I opened Postman via CLI. 

Funnily I got two different types of responses

## Response 1

```

<--- Last few GCs --->

[88947:0x3a124116d000]   160902 ms: Mark-sweep 1998.7 (2091.7) -> 1998.6 (2091.7) MB, 1812.9 / 0.1 ms  allocation failure GC in old space requested
[88947:0x3a124116d000]   162727 ms: Mark-sweep 1998.6 (2091.7) -> 1998.6 (2062.7) MB, 1824.4 / 11.4 ms  last resort GC in old space requested
[88947:0x3a124116d000]   164559 ms: Mark-sweep 1998.6 (2062.7) -> 1998.6 (2060.2) MB, 1832.1 / 10.4 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x2920cc0841fd]
Security context: 0x2aa13b4b301 <String[7]: file://>
    1: substring(this=0x686a3cff4a9 <Very long string[43874940]>)
    2: /* anonymous */ [file:///opt/postman/app/resources/app/js/0.js:9801] [bytecode=0xcc73a2772c1 offset=43](this=0x228abb086e29 <JSFunction BracketsUtils (sfi = 0x28233e7ec739)>,reversedBracketRegex=0x381d73284911 <JSRegExp <String[9]: (\{)|(\})>>,lineNumber=1,lineText=0x34ceddf822...

```
## Response 2

```
#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#
#
#
#FailureMessage Object: 0x7fd3a7548fe0#0 0x000001f48ff3 <unknown>
#1 0x000002b5bfcb <unknown>
#2 0x7fd3b5ea9a18 V8_Fatal()
#3 0x7fd3b5797540 <unknown>
#4 0x7fd3b5908242 <unknown>
#5 0x7fd3b58f7033 <unknown>
#6 0x7fd3b58f68ea <unknown>
#7 0x7fd3b58f6587 <unknown>
#8 0x7fd3b5912b6e <unknown>
#9 0x7fd3b58e436e v8::internal::ItemParallelJob::Task::RunInternal()
#10 0x000001f4ad04 <unknown>
#11 0x000001f607ae <unknown>
#12 0x000001f60e8b <unknown>
#13 0x000001f6000b <unknown>
#14 0x000001ee659b <unknown>
#15 0x000001f71331 <unknown>
#16 0x7fd3b4e5b46f start_thread
#17 0x7fd3b34df3d3 __GI___clone
```
# Expected Behaviour

JSON response should be formatted and displayed to user.

# Information

Postman version: 7.21.2-1
System Info:
```
Kernel: 5.4.28-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.3.0 
Desktop: KDE Plasma 5.18.3 tk: Qt 5.14.1 info: latte-dock wm: kwin_x11 dm: SDDM 
Distro: Manjaro Linux 
```

# Method of installation

I tried all these channels and got the same results:

- Download of executable file from official site: https://www.postman.com/downloads/canary
- Install from: https://aur.archlinux.org/packages/postman/
- https://aur.archlinux.org/packages/postman-bin/

**Comment by akhsiM** [comment]
Same issue in Windows 10 running as guest system in VirtualBox:

![image](https://user-images.githubusercontent.com/50348688/78503112-e6952800-77a7-11ea-8a42-13931731e927.png)

**Comment by dhcrees** [comment]
Also experiencing this since installing the lates MacOs (10.15.4) Supplemental Update.  I'm able to make one request with postman then it freezes, the Postman Helper task hits 600% cpu and then the Postman window goes Black...   Quitting and reopening allows me to do the same one request then it happens again.

My organisation is paying for the teams subscription and over the last few releases there have been a number of complaints from our developers because postman constantly hangs/freezes for about 10 seconds and then becomes responsive, this is just another nail in the coffin I'm afraid,    any help would be much appreciated.

**Comment by preethammavin** [comment]
@dhcrees can you let me know the version of the app that you are using?

**Comment by dhcrees** [comment]
Postman version 7.22.1.  All our developers use MacBooks running the latest MacOS 10.15.4

**Comment by preethammavin** [comment]
@dhcrees we have pushed multiple fixes on performance, can you share the size of the response for the request? If the request size is either in the range or greater than 20 MB, we recommend downloading the response with send and download to inspect the response. Postman does process the rest of the data but cannot render a response size greater than 20 MB reliably depending on the device configuration. 


If you do not want your workflow to be disrupted, then in the settings tab you should be able to find Max Response size which is set to a default of 50 MB, you can set it to 20 MB so that it is prompted automatically when the response size is greater than that. 

While we are also continuing to optimize our application performance can you add a few details
Size of the requests where this becomes an issue?
Config of the device (Mac model, RAM etc)

**Comment by dhcrees** [comment]
@preethammavin size of the request is 11k.  I'm more concerned at the moment with the Black screen that happens approximately 20 seconds after loading the app.  All I do is load the app, this happens to the CPU usage:
![Screenshot 2020-04-13 at 14 28 02](https://user-images.githubusercontent.com/4402911/79123922-20ab8e80-7d93-11ea-875c-127ed1a1f91a.png)
and then the postman window become unresponsive and turns black as in the screenshot above.  **Im not even making a request.**
I'm currently running this on a Mac Mini, i7 2.3 GHZ with 8GB of Ram, MacOs 10.15.4

**Comment by preethammavin** [comment]
@dhcrees can you write to us at help@postman.com from your registered email id.
please mention the GitHub issue id, along with app logs which you should be able to find in top menu-> View-> Developer -> view logs in finder. Also, mention the workspace that you are on in the email. This will help us get to the bottom of this get the fix out.

**Comment by preethammavin** [comment]
@dhcrees we should be able to deep dive into the issue, also the ticket would let us coordinate to schedule a call with the team to take a closer look if necessary.

**Comment by dhcrees** [comment]
As discussed with the postman team (Subramanya Raj) I solved the problem I was having by removing postman and its support files and reinstalling.

**Comment by akhsiM** [comment]
> If you do not want your workflow to be disrupted, then in the settings tab you should be able to find Max Response size which is set to a default of 50 MB, you can set it to 20 MB so that it is prompted automatically when the response size is greater than that.

Hi @preethammavin thank you for the response. I have done this on my Postman and will see if there is any further issue.

**Comment by davidasbury** [comment]
@preethammavin Postman is crashing when attempting to download large responses. 

Postman Version 7.24.0
MacBook Pro, 2.6 GHz Quad-Core Intel Core i7, 16 GB RAM, macOS 10.15.4

Requests are successful, returning warning messages if response is >50MB. But after choosing "Send and Download" app crashes. Changing Max Response Size under Preferences produces no meaningful difference.

Any help appreciated

**Comment by preethammavin** [comment]
@davidasbury assuming from your message that the response size is >50MB. Any chance you can tell me what the size of the response is?

**Comment by davidasbury** [comment]
@preethammavin Yes, you're right. Failing with file sizes from 93MB to 287MB. Calls return a zip file. Not seeing any issues when using a browser for the call.
Thanks

**Comment by dylanh724** [comment]
Related: https://github.com/postmanlabs/postman-app-support/issues/4751

**Comment by akhsiM** [comment]
> If you do not want your workflow to be disrupted, then in the settings tab you should be able to find Max Response size which is set to a default of 50 MB, you can set it to 20 MB so that it is prompted automatically when the response size is greater than that.

The above workaround has been good for me. However it would be great if this issue could be fixed. 

Apart from that, I have been using Postman fine as most responses aren't 20MB in size.

**Comment by davidasbury** [comment]
Thanks @akhsiM 
Unfortunately, changing the Max Response size has had no effect for me. Responses >50 MB still cause the application to crash ungracefully.

**Comment by devinnicholson** [comment]
I'm seeing the same issue-- tried changing the response time as well and nothing. The max I can get a csv file is about 120MB. Any more and it crashes.

**Comment by aprknight** [comment]
Replication of Postman 7.29.1 crash on Mac OS 10.15.6 using free public API
Execute: curl --location --request GET 'https://api.covid19api.com/all' >response.json
Note that the output file size is ~195MB
In Postman Preferences, set max response size to 0 (unlimited) [ Also tried with setting to 200 - same problem ]
In Postman attempt to GET https://api.covid19api.com/all
Postman will crash with SIGILL
<img width="1000" alt="Screenshot 2020-08-07 at 08 19 01" src="https://user-images.githubusercontent.com/29652671/89619956-cb861200-d886-11ea-893b-df5df327951d.png">

**Comment by saswatds** [comment]
Hi everyone 👋 . We have had some breakthrough over the last few releases of postman app. If you are on the latest version of Postman, ie. `v7.32.0` you should no longer be facing the issue of postman crashing when receiving large responses. 

We had some deep technical limitations before which caused response > 100MB to sometimes crash the app. 
With the latest release, we were able to overcome most limitations and can now **support response up to around ~700MB** (This is the max we can do because beyond this we hit the limits of how large a string can be in javascript 😞 ). 
_**Note**: This number may vary based on your system configuration._

Here is my attempt to load around 600MB of data, which loads just fine. 🎉 
<img width="985" alt="Screenshot 2020-09-12 at 7 58 57 PM" src="https://user-images.githubusercontent.com/8796447/92997901-469cb100-f534-11ea-94cc-66553e78f8e6.png">

I shall close this issue now. Feedbacks are most welcome.

**Comment by NikhilKGupta** [comment]
We are using 7.33.1, still seeing the same issue on mac. Postman hangs with the data response of 499 mb

**Comment by a85** [comment]
@NikhilKGupta Curious. What exactly is being downloaded here? Are these like video files or machine images?

**Comment by NikhilKGupta** [comment]
It is the usual json payload. We are calling an HTTP endpoint, it returns the response. But as soon, as I click the UI say for saving the response, it hangs until terminated. @a85

**Comment by codenirvana** [comment]
@NikhilKGupta Thanks for verifying that it's not crashing while sending the request. 😄 
Currently, saving a large response to the file works for 100-150 MB size. We are tracking this issue internally and will let you know once we have an update on this.

**Comment by NikhilKGupta** [comment]
> @NikhilKGupta Thanks for verifying that it's not crashing while sending the request. 😄
> Currently, saving a large response to the file works for 100-150 MB size. We are tracking this issue internally and will let you know once we have an update on this.

@codenirvana Is this issue fixed yet?

**Comment by filt3rek** [comment]
Hej !

I have, I think the same issue, I'm on v7.36.1.
It worked once for a huge mp4 movie 483Mb, I was able to save the response. Then I tried another movie, bigger and the app opens dialog to save the response and the next second the app just close without any report nothing so I can't save the response.
Maybe a workaround could be to save anyway the response to a temp file and then ask user to save it as a regular file where he wants ? I was looking for something like temporary folder but there is nothing like that.

**Comment by peti123x** [comment]
Hey,

Postman is still crashing on 8.3.0 with a response of 21MB :/ Its odd, I get a response, for about 5-6 seconds I can even view it and then the screen turns grey.

**Comment by 1Const1** [comment]
8.10 Postman Canary 1310 crashes on response 700mb

I think the limitation here is electron app that after 4gb memory consumption stop growing and fault user interface but processes Postman stay working in memory

Can you please increase memory limit of 4gb electron app? 

Memory of computer not a problem in my case. 64GB RAM, Free about 40GB

**Comment by Frikster** [comment]
This is still very much a problem... my 646MB response would not be displayed and crashed Postman. I have since given up and started using [Insomnia](https://insomnia.rest/). Works immediately in that it simply doesn't allow responses over 100MB to be shown. I can just download to file if I need to view it, which I mostly don't.

![image](https://user-images.githubusercontent.com/10172142/141035276-0808565d-3314-45ed-aafe-df448bf21d60.png)

Postman on the other hand continues to lock up and crash with the same request. I don't know why there is no option set to by default disable parsing a large response. It would prevent Postman from crashing.

**Comment by Vaibhav7Prakash** [comment]
> @NikhilKGupta Thanks for verifying that it's not crashing while sending the request. 😄 Currently, saving a large response to the file works for 100-150 MB size. We are tracking this issue internally and will let you know once we have an update on this.

@codenirvana Postman is crashing when sending request of size 240-250 MB. After giving the payload in Body in json format, the application freezes for some time and then turns into a grey screen.
![Screenshot (345)](https://user-images.githubusercontent.com/32938521/153142261-fb267ea7-4381-47da-87cd-6d13ec64b614.png)
.

**Comment by jviotti** [comment]
Thanks for opening a new ticket for this @Vaibhav7Prakash !

**Comment by mljohns89** [comment]
What's the new ticket?  Is there a resolution?  Just encountered this issue too.

**Comment by rafaell94** [comment]
I am having the same issue, PostMan shows the save dialog, but a second later the app crashes.

**Comment by gbtec-martinfruehauf** [comment]
I still have the Problem... Postman crashes if the response is more than 10 MB

**Comment by swotiendang** [comment]
Same problem

**Comment by nonickyet** [comment]
Same problem :(

**Comment by Frikster** [comment]
Solution still seems to be to use an alternative instead. I've switched to [Insomnia](https://insomnia.rest/) and have no complaints yet. This was a big enough issue for me to uninstall Postman and move to something else entirely.
