### ISSUE TITLE
Spelling mistake in response header

### ISSUE THREAD

**Issue by team-altworks** [a85/POSTMan-Chrome-Extension#8320]
I posted a form using Postman. Noticed a spelling mistake in the response headers. See screen shots below

![image](https://user-images.githubusercontent.com/63542806/79067904-96a2ed80-7ce0-11ea-866c-23e2d863be20.png)

![image](https://user-images.githubusercontent.com/63542806/79067852-18dee200-7ce0-11ea-8301-6161b0245e61.png)

**Comment by preethammavin** [comment]
@team-altworks can you let me know the version of the App you are on?

**Comment by team-altworks** [comment]
Postman for Windows
Version 7.22.1
win32 10.0.18363 / x64

**Comment by preethammavin** [comment]
@team-altworks I believe these are response headers and would be sent by the responding server. Can you test the same using Curl? Or can you see if the same issue occurs for any other API requests sent in Postman?

**Comment by kamalaknn** [comment]
@team-altworks Like @preethammavin mentioned the response headers are returned by the server handling the API request. 

I'm attaching the screenshot with an API request to `postman-echo.com/get` for reference.

<img width="958" alt="Screenshot 2020-04-13 at 9 09 16 AM" src="https://user-images.githubusercontent.com/8401064/79090265-baa91200-7d66-11ea-9836-2bfc4feb84db.png">

Closing this since this is not an issue with Postman itself.
