### ISSUE TITLE
[Can't sign up with google, Postman Offline]

### ISSUE THREAD

**Issue by letanloc1998** [a85/POSTMan-Chrome-Extension#8333]
**Describe the bug**
Does Postman down? I can't sign up by google account or using Postman app

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/26348718/79314158-99455300-7f2b-11ea-9c60-63d057660ff3.png)

![image](https://user-images.githubusercontent.com/26348718/79314222-af531380-7f2b-11ea-93d7-ce8c31b8939f.png)

**App information (please complete the following information):**

**Additional context**

**Comment by ash007-postman** [comment]
@letanloc1998  Some of our services were experiencing some downtime but those issues have since been addressed. We apologize for any inconvenience it may have caused you.

Below is a link to our status page which has to most up-to-date information on the uptime of our services.

http://status.getpostman.com

If you're still having issues, please do reach out!

**Comment by ash007-postman** [comment]
Ref ticket- ZD-49380

**Comment by letanloc1998** [comment]
May be it not fix, I can't sync ~~
![image](https://user-images.githubusercontent.com/26348718/79320251-b9791000-7f33-11ea-8d31-3e937d7b1758.png)

**Comment by letanloc1998** [comment]
Ok, it's working.
Thank you very much
