### ISSUE TITLE
Cookies not getting set when URL is variable

### ISSUE THREAD

**Issue by YassienW** [a85/POSTMan-Chrome-Extension#8348]
**Describe the bug**
When using a URL set from an environment variable, cookie header doesn't get automatically added

**To Reproduce**
1. Create new get request, set request URL to {{baseUrl}}
2. Add an environment with the variable baseUrl = https://github.com/ and use that environment
3. Send the request, cookies will be returned but the header will not be added
4. Change the URL to https://github.com/ instead of {{baseUrl}}, cookie header will get added
5. Change the URL back to {{baseUrl}}, cookie header is removed

**Expected behavior**
The cookie header should be added regardless of the method used to set the URL

**App information (please complete the following information):**
 - App Type: Electron
 - Postman Version 7.22.1
 - OS: Ubuntu 19.10

**Comment by jrobinson-efirst** [comment]
I'm having the same issue, but even switching to typing the url in rather than using the environment variable does not resolve the issue.
Postman version: 7.25.0

**Comment by arlemi** [comment]
This was fixed in the latest version of the app, please update and let us know if this is still not working!

**Comment by profplum700** [comment]
If you are setting setting the URL from a Collection variable this issue still occurs.

**Comment by shubhbhargav** [comment]
@profplum700 Can you please share a recording of the issue and also let us know which Postman app/web version you are using?

I tried reproducing the issue on Postman Web Version 9.22.5-220624-0940, but it worked as expected. Sharing the recording from my end to verify the steps:

https://user-images.githubusercontent.com/41579749/175645117-9beaaeae-7110-41ca-ba8a-3910531078ea.mov

**Comment by mateuszzz88** [comment]
I am having this issue with 9.27 version. But direction is different than in shubhbhargav's video. I am setting cookie manually in "cookies window" and I want it to add itself as a header in request (which doesn't work). Video shows that cookie is added from parameters which I don't care about

**Comment by shubhbhargav** [comment]
@mateuszzz88 The above video is for illustration purposes only. :) Can you share a screen recording of the issue once? Will help figure out how to reproduce the issue and fix it accordingly.

**Comment by mateuszzz88** [comment]
I can't share screen or actual requests - it is for work and security team would be angry. Instead I can flesh out steps a little

1. Website needs specific cookie to work (`foo=token`). Value for token changes daily
2. Configure request in collection. It goes to variable `{{base_url}}`
3. Configure variable base_url in collection settings.
4. Configure cookie `foo=token` for site company.com. Note that in my case base_url is NOT company.com, but the website does something in background that goes to company.com and needs that cookie
5. No manually specified headers or params relate to cookie `foo`
6. Send request. Website behaves as if cookie foo=token is not present
7. Extract code for curl. Cookie foo=token is not present

I currently use workaround:

1. Manually add header `Cookie: foo={{token}}`
2. Add variable to collection settings `token=<token>`
3. Sending requests works
4. Code export contains cookie `foo=token`
It is a slight pain that I have to add extra header to all requests in collection, but at least I can specify value once in a variable.

**Comment by shubhbhargav** [comment]
@mateuszzz88 Got it. Thanks for the detailed steps. :)

I see that you are trying to share cookies across domains, which is not supported as of now (because it is considered a security risk).

As an alternate, you can try using environment variables to set the cookie value and use that in the request (for the other domain). Something like below:

<img width="1089" alt="Screenshot 2022-10-14 at 1 26 58 PM" src="https://user-images.githubusercontent.com/41579749/195937649-a4990ab4-ea82-460d-8b84-3802a493efc1.png">

This can be done programmatically as well in-case you have an endpoint to get the cookie from `company.com` with the following script in the test script of the request:

```
var cookieValue = pm.cookies.get('<cookie-key>');

pm.environment.set('<variable-name>', cookieValue);
```

Let me know if this helps.

**Comment by lookto** [comment]
This seems to be an issue again (or still?).
Somehow the cookie manager sets the variable name as host for the cookie.

**To reproduce:**

1. Create environment variable `base_url` (in my case `http://gateway.localhost/graphql`)
2. Create request with `{{base_url}}` as url 
3. Send request, cookie gets returned and added to the cookie manager (but with `{{base_url}}` as host)

<img width="854" height="313" alt="Image" src="https://github.com/user-attachments/assets/94d71a49-e544-4e07-88ff-ef60c636441f" />

4. Request another resource, cookie doesn't get send.

When I don't use the variable as url but enter it directly everything works as expected and i see the correct url as host in the cookie manager.
Cookie is not set as secure, so it can't be related to https://github.com/postmanlabs/postman-app-support/issues/10185.

**Expected behavior**
The cookie header should be added regardless of the method used to set the URL

**App information**
    App Type: Native
    Postman Version 11.56.4
    OS: 6.15.9-arch1-1

**Comment by lookto** [comment]
@vvs11 Any progress on this?
