### ISSUE TITLE
Response is not formatted if there are newlines

### ISSUE THREAD

**Issue by ankita379** [a85/POSTMan-Chrome-Extension#8362]
salesforce is sending a string of json format with newlline.
abc
def
but in postman response, its coming as abc\n def. how to display in the same form as salesforce is sending

**Comment by kamalaknn** [comment]
@ankita379 Can you attach screenshots of the issue you are seeing? It will help us debug the issue better.

**Comment by kamalaknn** [comment]
Hey @ankita379 

Could you share a screenshot of your raw JSON response by selecting `raw` view in the response view? It should look something like

<img width="1440" alt="Screenshot 2020-05-10 at 3 19 39 PM" src="https://user-images.githubusercontent.com/8401064/81496007-0d2c0e80-92d2-11ea-9945-c8f4db34f412.png">

**Comment by kamalaknn** [comment]
Hey @ankita379 

I'm assuming your JSON response contains a newline character. If there are newline characters in your JSON, accessing them through a browser or any other client that parses the JSON, they would be converted into newlines as you consume them. Here's an example snippet and its behavior in Chrome.

<img width="346" alt="Screenshot 2020-05-16 at 10 34 23 PM" src="https://user-images.githubusercontent.com/8401064/82125728-a6bd5980-97c5-11ea-882e-fb00500645bd.png">

However, Postman being a debugging tool does not parse your response. Hence it does not convert newline characters into actual newlines. To give you an example, this is how the same response would like, unparsed on Chrome.

<img width="283" alt="Screenshot 2020-05-16 at 10 34 35 PM" src="https://user-images.githubusercontent.com/8401064/82125769-d53b3480-97c5-11ea-83d2-465dccd791ea.png">

Parsing the newline character into actual newlines might break the actual view of the JSON response and might not be suitable for all users. Here is a reference issue related to this [6991](https://github.com/postmanlabs/postman-app-support/issues/6991).

I'm closing this now. Please let us know if we missed anything.

**Comment by mkczyk** [comment]
> Postman being a debugging tool does not parse your response.

I assumed that tab "Raw" not parse response, but tab "Pretty" try show response in the most friendly form and have to parse response according to this assumption. 

If user wants to read not parsed response he can use "Raw" tab. 
But I understand some users want to see raw response but with pretty printing.

I found workaround for this problem:
1. On tab "Tests" write your visualizer:
```
pm.visualizer.set("<pre>{{text}}</pre>", {
    text: pm.response.json().myProperty
});
```
- Visualizers are for rendering HTML: https://learning.postman.com/docs/postman/sending-api-requests/visualizer/#rendering-html But we can use this for render only one HTML tag `<pre>` (it's default behavior causes that new lines are preserved).
- You have to indicate which field you want to show with new lines (in my case `myProperty`).
2. After sending request on tab "Visualize" you see you value with new lines.

Of course it has inconveniences (you have to indicate field(s) in JSON instead of simply show all fields with new lines), but maybe it helps author of the issue.

Pretty tab without new lines:
![pretty](https://user-images.githubusercontent.com/11051213/83144262-6d54ea00-a0f3-11ea-9e95-ec487a5dab69.png)
Visualizer with new lines:
![visualize](https://user-images.githubusercontent.com/11051213/83144276-704fda80-a0f3-11ea-99fa-ef7d3a4fd99d.png)

**Comment by 27shutterclicks** [comment]
Great solution @mkczyk ! I spent two hours looking for a way to display query output somewhere other than the Console. Initially, I kept trying to display it in Test Results, but your approach is better, since it separates control over display output and the test results area which can be kept for what it is meant - tests.

This solution should become part of the Postman documentation somewhere.

Many thanks!
