### ISSUE TITLE
URGENT Please help .--- error messages to install app on new windows OS

### ISSUE THREAD

**Issue by JamesWBS** [a85/POSTMan-Chrome-Extension#8363]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment]
@JamesWBS I'm afraid we can't help without enough information. Please provide the details requested in our new issue template.

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

App information (please complete the following information):

App Type [e.g. Chrome App, Native App]
Postman Version [e.g. 6.0.1]
OS: [e.g. macOS High Sierra 10.13.2]
Additional context
Add any other context about the problem here.
