### ISSUE TITLE
Choose a token type from Dropdown

### ISSUE THREAD

**Issue by neetgupta7** [a85/POSTMan-Chrome-Extension#8418]
I want to choose a token from Available Tokens dropdown. And when i do that it shows last generated token from that selected option. But when i click on 'Get New Access Token' it always shows details from last option in the dropdown. Am I missing something or is this by design.

**Comment by vvs11** [comment]
@neetgupta7 could you attach a screenshot or a video so that we understand the ask clearly?

**Comment by vikiCoder** [comment]
Hi @neetgupta7,

I am not fully understanding your issue. From what I understand, you are saying that clicking on `Get New Access Token` button shows information for the last generated token, right? Yes, that is correct. The information showed in `Get New Access Token` dialogue is not related to currently selected token in the request. It always shows the information you last updated while generating new token.

I think your issue is similar to this already open feature request: https://github.com/postmanlabs/postman-app-support/issues/7537. Please correct me if I misunderstood your issue.

**Comment by vvs11** [comment]
@neetgupta7 closing this for now. Please feel free to reopen if you are still facing issues. Also, we have a very active community that can solve your problem quickly http://community.getpostman.com/
