### ISSUE TITLE
Postman API Schema -> Collection (OpenAPI 3.0)

### ISSUE THREAD

**Issue by vadminn** [a85/POSTMan-Chrome-Extension#8438]
I created an API Schema in Postman.

I marked all the requests by tags and checked the correctness on https://editor.swagger.io/ Everything looks correct.

But when I generate a collection from the scheme I have some issues:
-  Some requests were placed out of the tag directory. (They are placed correctly on swagger editor)
<img width="525" alt="Screenshot 2020-05-05 at 11 35 37" src="https://user-images.githubusercontent.com/45597633/81053257-1463ae80-8ec5-11ea-929f-671f84b239cb.png">
<img width="730" alt="Screenshot 2020-05-05 at 11 38 44" src="https://user-images.githubusercontent.com/45597633/81053263-162d7200-8ec5-11ea-987e-f6b81b157b1a.png">

-  Some requests generate “documentation” and “mock server” validating issues, like providing '
integer' to the query param, instead of “example” integer value.
<img width="1033" alt="Screenshot 2020-05-05 at 11 43 21" src="https://user-images.githubusercontent.com/45597633/81053766-e59a0800-8ec5-11ea-90f0-4791163037a2.png">
<img width="813" alt="Screenshot 2020-05-05 at 11 44 16" src="https://user-images.githubusercontent.com/45597633/81053733-d74bec00-8ec5-11ea-87b1-947f848dacb0.png">

Is it a bug or I do anything wrong?

App Type: Native App
Version 7.23.0
OS: macOS Catalina 10.15.4

**Comment by VShingala** [comment]
@vadim-nilov Currently [OpenAPI Importer](https://github.com/postmanlabs/openapi-to-postman) groups requests based on their paths and not based on tags. Due to this they belong in different folder in your case.

We are currently working on grouping requests based on tags using an option, You can find detailed discussion here https://github.com/postmanlabs/openapi-to-postman/issues/57

**Comment by vadminn** [comment]
@VShingala what about using example's value in the request instead of schema type?

**Comment by shreys7** [comment]
@vadim-nilov With Postman 7.24.0, we have added support for configurable options for OpenAPI, GraphQL, Swagger and RAML imports. For using example values in the request instead of schema, you can use the `Request parameter generation` option. Set its value to example and the collection will pick the example's value if provided.
The options are available in the Import flow. Click on Import button on top left -> select a file -> configure the option -> Import
![image](https://user-images.githubusercontent.com/20665864/82138627-7fa36e00-983f-11ea-8a9b-57824c1b170f.png)
![image](https://user-images.githubusercontent.com/20665864/82138637-8e8a2080-983f-11ea-9771-35ff437f97f4.png)

We will soon be integrating the options in the Generate collection flow from an API.

**Comment by VShingala** [comment]
Closing this issue as resolved, feel free to reopen for any further problems.
