### ISSUE TITLE
-

### ISSUE THREAD

**Issue by trnchawla** [a85/POSTMan-Chrome-Extension#8444]

**Comment by trnchawla** [comment]
This happens when postman auto archives your data and it is shown as locked. When you download your archive data and then try to import the downloaded data then you will see that all request bodies data have been lost. 

And worst part was not notification that data is going to be archived, either you don't allow greater than 25 requests or if allowing then give enough time that I copy paste it. Ruined my 1 week work, now I have to carefully create jsons again.

**Comment by trnchawla** [comment]
Seriously stupidest way to get premium customer, I will never allow postman in any of my teams no matter what.

**Comment by preethammavin** [comment]
@trnchawla We have identified the bug in the system and the issue will be fixed ASAP. While we do fix the issue you can export the data using the app using settings for now, which will export all the data from the app to be imported. 
For reference you can find it in the settings tab:
<img width="1109" alt="Screenshot 2020-05-06 at 7 28 15 PM" src="https://user-images.githubusercontent.com/34742239/81186030-f636a500-8fcf-11ea-90b3-a5dbe9c0194f.png">
 

And secondly, while I understand your frustration I would not use abusive words in a public forum that would not paint anyone in a decent color. I have gone ahead and edited the request name so that the post could be useful if anyone else faces the same issue.

**Comment by trnchawla** [comment]
Above also does not work and it is not a recent bug, I have seen so many issues reported by many people earlier. Where I have abused anyone, am talking about product.

**Comment by trnchawla** [comment]
You can create your own issue.

**Comment by trnchawla** [comment]
carry on liking your own comments and disliking my comments.

**Comment by trnchawla** [comment]
Please, You can create your own issue and work on it.
