### ISSUE TITLE
Request time is wrong

### ISSUE THREAD

**Issue by AykutCevik** [a85/POSTMan-Chrome-Extension#847]
The request time (in ms) is not the actual time of the request, but the sum of the whole procedure of the POSTMan request itself.

So the value itself is not accurate and can not be used for any benchmarking purposes - thus it's unnecessary.

What I need is just the time of the request itself like it is shown in the Google Chrome developer tool network overview.

To reconstruate this:
If I'm in my "collection view", the request time is shown far less than that in the "history view" for the same request. The reason for this is, that my history itself is really huge. So at every request, the history refreshes and the CPU time for this operation is also added to the request time.

![image](https://cloud.githubusercontent.com/assets/1965251/5411762/b8174bfa-8204-11e4-8f92-1903b407c74a.png)

**Comment by abhijitkane** [comment]
Fixed in 1.0.4

**Comment by GF-Huang** [comment]
Incorrect again.

--------------------------------------

![image](https://user-images.githubusercontent.com/4510984/58373140-c2e43d00-7f5b-11e9-9580-632ac0fa1751.png)

-------------------------------------------

![image](https://user-images.githubusercontent.com/4510984/58373127-9f20f700-7f5b-11e9-93e7-788bad0f1654.png)

------------------------

![image](https://user-images.githubusercontent.com/4510984/58373148-edce9100-7f5b-11e9-80a3-116172ff4b07.png)

**Comment by saswatds** [comment]
Hi @GreatFireWall, The Chome browser is able to achieve much lower time due to internal caching. 
As of App version v7.1.1, if you hover over the time display you will be able to see with much granularity what aspect of the request is taking so much time.

As an example, for the very first request here the time taken is much longer due to DNS lookup and TCP and SSL Handshake.
<img width="882" alt="Screenshot 2019-05-26 20 23 30" src="https://user-images.githubusercontent.com/8796447/58383421-2b7ef880-7ff4-11e9-947e-b1f4e7f99e41.png">

Sending the same request again results in a much lesser time
<img width="882" alt="Screenshot 2019-05-26 20 23 42" src="https://user-images.githubusercontent.com/8796447/58383438-5c5f2d80-7ff4-11e9-9cbd-a6f396f11660.png">

If you are still finding the time taken by postman is much longer then feel free to get back to us.

Thanks
