### ISSUE TITLE
Can't import definition from Swagger

### ISSUE THREAD

**Issue by emcence** [a85/POSTMan-Chrome-Extension#8554]
**Describe the bug**
When i try to import definition from Swagger I am stuck on “Confirm your Import” window.

**To Reproduce**
1. Go to Improt > Link > https://petstore.swagger.io/v2/swagger.json
2. Click on 'Continue'
3. In Import window click on "Import" button

**Expected behavior**
To see imported collection

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.24.0
 - OS: Win 10

**Comment by umeshp7** [comment]
@emcence This issue is currently being tracked here: #8542 

Here is a workaround for this issue which will allow you to import at least the collection. On the "Confirm your Import" screen deselect the "API" option for now and the collection will be imported successfully. 
<img width="780" alt="Screenshot 2020-05-26 at 2 04 09 PM" src="https://user-images.githubusercontent.com/31915995/83156591-39dc8480-a120-11ea-948b-6ca3c6827eea.png">

For creating the API you could use the "New API" button in the APIs tab. 
<img width="365" alt="Screenshot 2020-05-26 at 2 07 57 PM" src="https://user-images.githubusercontent.com/31915995/83156638-4660dd00-a120-11ea-875c-c684d3f154f6.png">

Closing this issue as duplicate.
