### ISSUE TITLE
Cannot open postman with WIN10

### ISSUE THREAD

**Issue by jiangdai27** [a85/POSTMan-Chrome-Extension#8568]
**Describe the bug**
i cannot open postman even if i reinstalled it. (version 7.25.0)
it still pop-up same error 

main error "Main~AppEvents - Shared window boot failed",{"adapterMethodName":"find",
"cause":{"adapterMethodName":"find","message":"Malformed error from adapter: Should always be an Error instance, but instead, got:\n```\n
[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]\n```","modelIdentity":"user","name":"AdapterError","raw":{"_e":{"message":"","name":"Error","stack":"Error\n    at getErrorWithStack 

![image](https://user-images.githubusercontent.com/46912406/83382368-87edd280-a415-11ea-9e89-43bd9f43b49b.png)

and after i close pop-up window 
it show the preparing status and doesn't complete.
![image](https://user-images.githubusercontent.com/46912406/83382741-617c6700-a416-11ea-9bc0-e03a2aa7f800.png)

**Comment by ankurdengla** [comment]
Hey @jiangdai27 ! 

Inconsistencies in the underlying storage of the app can sometimes prevent the app from launching. You can unblock yourself by following this troubleshooting guide - https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-

We are already tracking this issue here - #6723

Closing this as a duplicate.
