### ISSUE TITLE
ffmpeg.dll was not found

### ISSUE THREAD

**Issue by jarlarntzen** [a85/POSTMan-Chrome-Extension#8574]
Running the 64-bit Windows installer for Postman Canary results in this error.
![image](https://user-images.githubusercontent.com/2108412/83509514-d8276c00-a4cb-11ea-8a5b-95aa2099298b.png)

**Reproduce**
1. Download canary 64-bit for Windows
2. Start the installer
3. Halfway through the installation, the above error message appears. Not possible to continue after that.

Windows 10
PostmanCanary-win64-7.26.0-canary02-Setup.exe

The setup and log files are attached below.

[SquirrelTemp.zip](https://github.com/postmanlabs/postman-app-support/files/4717433/SquirrelTemp.zip)

**Comment by SabriH10** [comment]
Hi @jarlarntzen ,
Thank you for reaching out, happy to help troubleshoot here. Usually, this can be fixed by clearing the local data and re-installing Postman Canary. I believe it should be the following on Windows:

```
**Windows**

Open File Explorer and paste in the Path field

C:\Users\<user>\AppData\Local\PostmanCanary and
C:\Users\<user>\AppData\Roaming\PostmanCanary 

And delete the files in both locations.
```



You can make a copy of the local files just in case ( if you don't want to lose any Data- I'm guessing this shouldn't apply here considering you're unable to install Canary )

Once that's completed - I'd recommend re-installing Postman Canary and see if that helps. I've referenced the article below with the steps suggested above if needed.

Let us know if this helps and we'll continue following your response.

[0] https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-

**Comment by jarlarntzen** [comment]
@SabriH10 Thanks for getting back to me. PostmanCanary did install properly it seems, despite the error message.

My main agenda here was to mention that the error message popped up during installation and also, partly, to ask what ffmpeg.dll has to do with Postman? I've only used ffmpeg to transcode video etc in the past.

**Comment by numaanashraf** [comment]
@jarlarntzen Postman's Desktop Apps is build on [Electron](https://www.electronjs.org/) which internally bundles a version of Chromium to render the UI. `ffmpeg.dll` is a dependency of Chromium.

**Comment by iamshubhamjangle** [comment]
Thanks the solution worked!!!!
just deleted files in local and roaming folder (delete only postman folder if exist);

**Comment by strongpapazola** [comment]
when i install postman for the first time 
```the code execution cannot proceed because ffmpeg.dll was not found```
this error pops up
when i install chrome and install postman again, it's works for me

**Comment by angelcabrera-nr** [comment]
Uninstalling and reinstalling postman worked for me
