### ISSUE TITLE
Add posibility to configure max-http-header-size

### ISSUE THREAD

**Issue by Telmah** [a85/POSTMan-Chrome-Extension#8587]
there is no possibility to specify maximum allowed header size. for node JS is was dropped to 8kb in some of latest releases, so it's not possible to get answer from server if header size is more that 8Kb. Workaround solution is to specify global variable for nodejs like NODE_OPTIONS=--max-http-header-size=800000 or similar, but it could be better to have possibility to set and save it globally

**Comment by codenirvana** [comment]
Since Postman v8.4.0, the max response header size is increased to 100 KB.

<img width="372" alt="Screenshot 2022-01-04 at 4 43 04 PM" src="https://user-images.githubusercontent.com/4865836/148070306-d5cfc5e9-f276-4bff-8ae9-b8b827ea987d.png">

Closing this feature request since the underlying bug #8656 is fixed and there’s not much utility in supporting this configuration.

In terms of API and Security testing, we can add the following **test script** to ensure the header size is within the limit.

```js
pm.test("Response header size is less than 8 KB", function () {
    pm.expect(pm.response.size().header).to.below(8 * 1024)
});
```

Please feel free to reopen if I am missing a valid use case.
