### ISSUE TITLE
Problem with CryptoJS function. Syntax Error

### ISSUE THREAD

**Issue by rvit34** [a85/POSTMan-Chrome-Extension#8592]
**Describe the bug**
It seems functions from cryptoJS library are not available in pre-request script. 

**To Reproduce**
1. Create request to any webserver endpoint
2. Go to Pre-request script tab
3. Add a call to library function. For instance: `const​ hash = CryptoJS.HmacSHA256('msg', 'secret');`
4. See syntax error in the console

**Expected behavior**
CryptoJS functions should be available without any additional effort from the user as it built-in library.

**Screenshots**
![Screenshot from 2020-06-05 20-06-50](https://user-images.githubusercontent.com/20579813/83899166-04134d80-a769-11ea-8d78-05474c0cd19f.png)
![Screenshot from 2020-06-05 20-04-15](https://user-images.githubusercontent.com/20579813/83899169-05447a80-a769-11ea-9ee1-9881c3fe669d.png)
![Screenshot from 2020-06-05 19-59-11](https://user-images.githubusercontent.com/20579813/83899171-05447a80-a769-11ea-9ad1-9bc1a0366066.png)

**App information (please complete the following information):**
 - App Type: Postman Native App
 - Postman Version: 7.25.2
 - OS: Ubuntu 18.04 (Linux 4.15.0-101-generic / x64)

** Additional info **
I also tried to call it the such ways:
```
 $.when(
     $.getScript( "https://cdnjs.cloudflare.com/ajax/libs/jsSHA/2.0.1/sha256.js" ),
     $.Deferred(function( deferred ){
         $( deferred.resolve );
     })
 ).done(function(){
     const​ hash = CryptoJS.HmacSHA256('message', 'secret');
     console.log('hash:' + hash);
}
```
```
var CryptoJS = require("crypto-js");
const​ hash = CryptoJS.HmacSHA256('message', 'secret');
```
But have no success.

**Comment by codenirvana** [comment]
Looks like there's a Unicode character '[ZERO WIDTH SPACE](https://en.wikipedia.org/wiki/Zero-width_space)' in-between `const` and `hash`.

<img width="494" alt="Screenshot 2020-06-06 at 11 57 41 AM" src="https://user-images.githubusercontent.com/4865836/83937764-4a11f500-a7ed-11ea-8f5d-1a3bbe4fffbb.png">

The following script with zero width space will always fail:
```js
const​ hash = CryptoJS.HmacSHA256('msg', 'secret');
```

And, without zero width space it will work fine:
```js
const hash = CryptoJS.HmacSHA256('msg', 'secret');
```

Since it's an invalid token in JavaScript, the script execution fails.

You can solve this issue by just deleting the Unicode char after `const` but, keeping this issue open until we improve the authoring experience of scripts within Postman which will automatically highlight these invalid characters.

**Comment by rvit34** [comment]
Thank you. It's really the reason of the issue. 
And yeah, please make output of script evaluation more friendly.
Now it does not point even the line where the syntax is broken.
It I have 100 line script I have no idea where it's.

**Comment by kool79** [comment]
This happens for me also when I copied examples from CryptoJS site.
I removed lines of code one-by and code started to work when I removed line with comment! 
Reopened this issue as #9642
