### ISSUE TITLE
not syncing properly

### ISSUE THREAD

**Issue by bharatramawat28** [a85/POSTMan-Chrome-Extension#8607]
the sync icon always rotating while not doing any changes. and also data is lost after closing postman.

**Comment by SenthilvelSomasundaram** [comment]
Same issue. Postamn sync not working consistently. Also Unable to create pull requests. Looks server is down.

**Comment by ankit-m** [comment]
@SenthilvelSomasundaram could you provide some more details? Screenshots and reproduction steps would be helpful.

**Comment by SabriH10** [comment]
@SenthilvelSomasundaram @bharatramawat28 Are you still observing this issue? As mentioned above by Ankit, if you could provide more details in the form of screenshots so we can get a better understanding and we'll be happy to help.

**Comment by bharatramawat28** [comment]
no its fine now,
I am looking for a feature of send and download while running collection
runner if u can help that will be very fine.

Thanks

**Comment by SabriH10** [comment]
@bharatramawat28 Try the following suggestion from the Community Forum, it should help: https://community.postman.com/t/how-to-download-file-while-running-collection-runner/13080/2

I'll close this issue for now considering your issue is resolved, but for the send and download with the Collection Runner, you may leverage the Forum if you still have questions.
