### ISSUE TITLE
After update doesnt connect to publish API

### ISSUE THREAD

**Issue by garycsebastian** [a85/POSTMan-Chrome-Extension#8633]
We worked through a proxy and it all worked fine until it stopped connecting to publish an API.

![image](https://user-images.githubusercontent.com/25212475/84419669-8fb03280-abde-11ea-86e8-aa13dfef6b87.png)

it appears and I dont know for what...

Theres a new port that you using lately?

**Comment by numaanashraf** [comment]
@garycsebastian Could you write to us at help@postman.com? We'll help you get this issue resolved.

**Comment by acmor** [comment]
Same here. Yesterday I updated Postman on Windows to 7.26.0 and since then the API and the synchronization are offline. The Postman requests still work (Settings / Proxy / Proxy configurations for sending requests).

I'm on a corporate network and must use a proxy server to connect to the internet. I can't use the "normal" system proxy server settings, I have to configure a special proxy server.
Under https://learning.postman.com/docs/postman/sending-api-requests/proxy/ I found this picture https://assets.postman.com/postman-docs/proxy_global.png but I can't find the "Global Proxy Configuration" in my Postman settings.

How can I setup Postman to use a specific proxy for ALL network requests?

### UPDATE_0:
Just found this maybe that will solve my problem too:
 Update - We have identified a more reliable fix to resolve the NTLM handshake issue while establishing a WebSocket connection via a proxy. This fix is available on our early-access Canary channel (v7.27.0-canary07) and we are working with affected teams to verify the fix.

If you are impacted by this issue, do try this Canary build (https://www.postman.com/downloads/canary/) and let us know via help@postman.com.
Jun 17, 19:19 UTC

### UPDATE_1:
The canary version **solved** the error for me, the API and the synchronization are working again.

**Comment by DannyDainton** [comment]
Hey @garycsebastian 

Are you still seeing the issue in the latest version of the app?

**Comment by havaball** [comment]
I have removed and reinstalled the app and I am still getting the same issue.

Chris Havard
QA Analyst II



National Client Conference, May 19-22 in San Antonio - Register Today!<http://www.cpsi.com/2019conference>

[cid:Evident(2)_c424fa98-fee0-4bf5-a86b-76ad66aca665.png]
Electronic Mail Confidentiality Notice:
This electronic mail message and all attachments may contain confidential information belonging to the sender or the intended recipient. This information is intended ONLY for the use of the individual or entity named above. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution (electronic or otherwise), forwarding or taking any action in reliance on the contents of this information is strictly prohibited.  If you have received this electronic transmission in error, please immediately notify the sender by telephone, facsimile, or email to arrange for the return of the electronic mail, attachments, or documents.


<https://www.cpsi.com/>[cid:2020.CPSI.SigLine.224x83_8d106c4f-e7b1-4117-aa2c-fa6292baf149.png]

Electronic Mail Confidentiality Notice:
This electronic mail message and all attachments may contain confidential information belonging to the sender or the intended recipient. This information is intended ONLY for the use of the individual or entity named above. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution (electronic or otherwise), forwarding or taking any action in reliance on the contents of this information is strictly prohibited.  If you have received this electronic transmission in error, please immediately notify the sender by telephone, facsimile, or email to arrange for the return of the electronic mail, attachments, or documents.

**Comment by mccannt** [comment]
@havaball We have been making continuous improvements since this issue was logged. 
Can you confirm if this is still happening for you on the latest version of the app?

**Comment by mccannt** [comment]
No updates from users on this currently. Closing for the time being, please feel free to reopen if this is still happening in the most recent version of the application.
