### ISSUE TITLE
Can't sign in on Manjaro Linux

### ISSUE THREAD

**Issue by Gibbo3771** [a85/POSTMan-Chrome-Extension#8671]
**Describe the bug**
Clicking "Sign in" on the Postman app takes me to an infinite loading screen.

**To Reproduce**
1. Install Postman from AUR
2. Try to Sign In via the app

**Expected behavior**
Not sure, is it supposed to be a popup? Browser link with callback? Embedded view?

**Screenshots**
The app is stuck here:
![stuck-postman](https://user-images.githubusercontent.com/10871784/84884960-494d4e80-b08a-11ea-97f5-a662145fdd3e.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version 7.26.0
 - OS: Manjaro Linux - Kernel 5.4.44-1-MANJARO

**Comment by ArjunSingh-PM** [comment]
@Gibbo3771 Thank you for reporting this issue. Could you please provide more details on how you are trying to log in - are you using an email/password combination, signing in from Google or trying out our browser interface to authenticate?

**Comment by RocketFever22** [comment]
Hello,

I've got this issue. It's still there, but I could skip it by:

1. Clicking "Skip signing in and take me straight to the app"
2. Click the "sign in" button on the top right of the main window. It will redirect you to the log in screen
3. This second time the app actually logged me in.

I hope it helps for other people.

I'm using the latest AUR snap version in Manjaro

**Comment by kasir-barati** [comment]
I faced the same issue in Postman. I was signed in. Then when i open postman it stuck at the preparing workspace step. so I install the chrome extension. In chrome i forced to change my password. After login into the chrome extension it stucked in synchronization step. So i try to open the native Postman app. but this time i logged in first but it could not resolve my workspace. and now it just stuck in loading or it does not show the postman app at all. 

```
$ uname
Linux kasir 5.10.79-1-MANJARO #1 SMP PREEMPT Fri Nov 12 20:26:09 UTC 2021 x86_64 GNU/Linux
```
Postman version: IDK, i just install it with snap

Note: I face this bug in chrommium too: `sigsegv`. I think it is something related to your memory management and or v8 memory management.
Why i think this way? Due to my problems with other electron apps like VSCode. VSCode crashes too much for me.
Or maybe it is something related to my PC.


Thanks regardless
Kasir Barati - Node.JS developer

**Comment by ArjunSingh-PM** [comment]
Closing this issue as this is not reproducible.
