### ISSUE TITLE
When I fire a GET request form Postman using Parameters, preview window is not showing the web page

### ISSUE THREAD

**Issue by Dipankar151** [a85/POSTMan-Chrome-Extension#8744]
![Postman](https://user-images.githubusercontent.com/67973385/86821052-89ab5580-c0a7-11ea-8a4b-ba4486628973.png)

**Comment by arlemi** [comment]
Google uses Javascript to render results by default, if it is deactivated it will redirect to a non-JS friendly version of Google. The Preview tab of Postman doesn't execute JS nor redirects for security reasons, that's why you're staying stuck on that page. 

You can add a `gbv` parameter with a value of `1` to force google to send the non-js friendly page back, this will work with Postman. For example, try calling `https://www.google.co.in/search?q=google+no+js&gbv=1`
