### ISSUE TITLE
Postamn crashes everytime after opening(shows greyed out screen)

### ISSUE THREAD

**Issue by nitinnagpal61** [a85/POSTMan-Chrome-Extension#8754]
**Describe the bug**

**To Reproduce**
1. Go to '..Postman'
2. Don't do anything, just wait for 15 to 20 sec, the app greys out & crashes.

**Expected behavior**
It should open

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![image](https://user-images.githubusercontent.com/20840183/87115324-80311180-c290-11ea-981f-9df1f6951c0c.png)

**App information (please complete the following information):**
 windows Postman app

**Additional context**

**Comment by hgalai** [comment]
Hi,
I have had the same issue, but:
1. my OS is Ubuntu 20.04 lts
2. the color is not grey but orange

To solve the issue, I uninstalled and reinstalled the app.
It asked me to login again.
I could find there all my previous setting.

I'm not specialist, but it seems the issue was coming from the automatic login process (I can't say if it was coming because of an OS or an app update or from something else).

I hope I could help

**Comment by hgalai** [comment]
Hi,
I had the same issue until I found this ticket about an hour ago, but in my case:
1. the OS is Ubuntu 20.04 lts
2. the color was not grey but orange

To solve the issue, I uninstalled and reinstalled the app.
It asked me to login again.
I could find there (i.e. from postman's server) all my previous settings and history.

I'm not specialist, but it seems the issue was coming from the automatic login process (I can't say if it was coming because of an OS or an app update or from something else).

I hope it can help

**Comment by hgalai** [comment]
Sorry
1. I forgot to add (same answer both before and after uninstalling/reinstalling):
from terminal I asked :  "postman --version"

the answer in terminal was : 
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Could not get the lock, quitting

2. from terminal I asked: postman

the answer in terminal was (it opened a normal postman window):
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Not disabling GPU
ProtocolHandler~setDefaultProtocolClient: Command failed: xdg-mime default Postman.desktop x-scheme-handler/postman
/bin/sh: 1: xdg-mime: not found

Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
Main\~createDefaultWorkingDir - Default working dir creation already attempted
xxxxxxxxxxxxxx main info "Booting Postman 7.28.0, linux-5.4.0-40-generic on x64"
xxxxxxxxxxxxxx main info "EventBus\~initialize - Success"
xxxxxxxxxxxxxx main warn "CloudProxyManager\~init: Error while reading proxy configuration from user data - ",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/xxxxxxxxxxxxxx /snap/postman/117/.config/Postman/Postman_Config/proxy","name":"Error","message":"ENOENT: no such file or directory, open '/home/xxxxxxxxxxxxxx /snap/postman/117/.config/Postman/Postman_Config/proxy'","stack":"Error: ENOENT: no such file or directory, open '/home/xxxxxxxxxxxxxx /snap/postman/117/.config/Postman/Postman_Config/proxy'"}
xxxxxxxxxxxxxx main info "CloudProxyManager\~init - Success"
xxxxxxxxxxxxxx main info "UpdateHandler\~init - Success"
xxxxxxxxxxxxxx main info "RuntimeExecutionService\~initialized: Success"
xxxxxxxxxxxxxx main info "LinuxAutoUpdater\~Cleanup - Initial cleanup successful"
xxxxxxxxxxxxxx main info "Bootstrap-models\~bootstrap - Success"
xxxxxxxxxxxxxx main info "window-manager\~newSharedWindow: Shell loaded"
xxxxxxxxxxxxxx main info "Main\~AppEvents - Received booted event for process shared"
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
InterceptorBridge: Trying to connect Native App IPC\~Interceptor Bridge
xxxxxxxxxxxxxx  main info "Main\~AppEvents - Received booted event for process requester"
IPCClient \~ WindowHandler: New event is received { type: 'window-opened' }

nota bene: "xxxxxxxxxxxxxx" replaces some local informations

3.  from terminal I asked: sudo postman

the answer in terminal was (it did not open any window):
[sudo] Mot de passe de xxxxxxxxxxxxxx : 
mkdir: cannot create directory '/run/user/0': Permission denied
No protocol specified

**Comment by kamalaknn** [comment]
Hey @nitinnagpal61 @hgalai 

Could you share the application logs from `View -> Developer -> Show logs in Finder` with us at `help@postman.com` so we can take a deeper look at this?

**Comment by hgalai** [comment]
Hi @kamalaknn 
log files are sent!
Thanks for your kind help.

**Comment by sachinzoman** [comment]
Hey, I'm getting the same issue for a week on my system. I've also uninstalled/install the latest version of Postman, but the issue still persists. Please help.

**System information:**
macOS 10.14.6
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Processor: 2.3 GHz Intel Core i5
Graphics: Intel Iris Plus Graphics 640 1536 MB
Serial Number: FVFYG9MUHV29

**App Information**
Version 7.28.0 (7.28.0)

**Logs**
[main.log](https://github.com/postmanlabs/postman-app-support/files/4924004/main.log)
[pluginHost.log](https://github.com/postmanlabs/postman-app-support/files/4924005/pluginHost.log)
[renderer-auth.log](https://github.com/postmanlabs/postman-app-support/files/4924006/renderer-auth.log)
[renderer-console.log](https://github.com/postmanlabs/postman-app-support/files/4924008/renderer-console.log)
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/4924009/renderer-requester.log)
[renderer-shared.log](https://github.com/postmanlabs/postman-app-support/files/4924010/renderer-shared.log)
[renderer-shared1.log](https://github.com/postmanlabs/postman-app-support/files/4924011/renderer-shared1.log)
[renderer-shell.log](https://github.com/postmanlabs/postman-app-support/files/4924012/renderer-shell.log)

**Comment by andrew-jones** [comment]
Getting the same console errors on Ubuntu 18.04.  Second time in a couple of weeks I've had to reinstall. `View -> Developer -> View logs in File Manager` did not launch file manager.

**Comment by andrew-jones** [comment]
Run into this again, third time.  Starting to look for alternatives.

`
~ » postman
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Could not get the lock, quitting
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
`

**Comment by hgalai** [comment]
> Run into this again, third time. Starting to look for alternatives.
> 
> `~ » postman (electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead. Could not get the lock, quitting Gtk-Message: Failed to load module "canberra-gtk-module" Gtk-Message: Failed to load module "canberra-gtk-module"`

It seems the issue is coming from a framwork (Electron V7.0.0) used to develop Postman. 
In oct 2019 the release of version V7.0.0 made obsolete the use of 'getName' function. This one should be replaced in Postman's code by  'name'.
Thus 'app.getName() ' should be replaced by 'app.Name()'
Source: https://github.com/sindresorhus/electron-util/issues/22

@kamalaknn : do you think this could be the reason of  the app instability?

**Comment by andrew-jones** [comment]
And again, another snap remove and snap install.

**Comment by JamesElliott-Wren** [comment]
Same issue for me, It works if I use a windows laptop. 
It's been like this for months, is there no progress on this issue?

**Comment by andrew-jones** [comment]
More problems, can't save, can't sync.

```
Malformed error from adapter: Should always be an Error instance, but instead, got:
[InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.]
```

**Comment by andrew-jones** [comment]
And I'm reinstalling again.

**Comment by andrew-jones** [comment]
How do I get support on this?  We pay for a 20 person team.  Now seriously looking for alternatives.

**Comment by xk0der** [comment]
Hey @andrew-jones sorry to see you run into that issue, it does sound bad 🙁 

May I request if you try out the steps listed here: https://support.getpostman.com/hc/en-us/articles/360025359014 to remove/rename the local Postman folder and then re-install the app again.

If that doesn't fix it either, please do reach out to our Support Channel either by logging a ticket here: https://www.postman.com/support/ or by emailing us directly at help@postman.com so that we can have a closer look.

**Comment by xk0der** [comment]
Anyone facing this issue - try out the steps at this article: https://support.getpostman.com/hc/en-us/articles/360025359014
If that doesn't work, do submit a ticket with us at the [Support Channel](https://www.postman.com/support/) so that we can dig further.

Cheers

**Comment by azormpas** [comment]
I faced the same issue. I solved that doing the following steps:
1)Uninstall desktop Postman app
2)Go to C:\Users\<user>\AppData\Local\Postman and C:\Users\<user>\AppData\Roaming\Postman and delete all files from these folders.
3)Install the Postman App again.

**Comment by elreydetoda** [comment]
I installed postman from a snap on Ubuntu 21.04 ( technically Pop-OS, but still Ubuntu ), but I tried all the suggestions above ( and I don't remember seeing this suggested ) and nothing worked.

So, I ran postman in snap's strace mode ( `snap run --strace postman` ) and noticed that it was saying it couldn't find a .Xauthority file. So, I just copied my .Xauthority file into the snap ( `cp ~/.Xauthority ~/snap/postman/current/.Xauthority` )

Afterwards everything worked.

Still getting the error message of `(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.` , but at least it is actually launching the program now instead of seg faulting.

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/5980
