### ISSUE TITLE
AWS V4 Signature w/form-data do not include x-amz-content-sha256

### ISSUE THREAD

**Issue by bramski** [a85/POSTMan-Chrome-Extension#8770]
**Describe the bug**
I am using S3 to generate a pre-signed POST which then gives me a set of keys to upload with.  I have a session key and credentials and have set the Authorization to AWS Signature.  When I then attempt to run the pre-signed POST I get the following error:
`<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>InvalidRequest</Code>
    <Message>Missing required header for this request: x-amz-content-sha256</Message>
    <RequestId>80EE385D4D76B4F3</RequestId>
    <HostId>mxJ+TjtVFVaCM4sviYrLsiC1gsnkkx/eE/d5RU/V6VjoIYFCrzV1q9h1HTGchznjpakm8uhcqY4=</HostId>
</Error>`

**To Reproduce**
Download AWS credentials and set Authorization to AWS Signature
FIll out the required fields from the form-data for the pre signed POST.
Send the request

**Expected behavior**
The post succeeds

**Screenshots**
![Screen Shot 2020-07-13 at 1 22 17 PM](https://user-images.githubusercontent.com/421781/87349983-0c02a200-c50c-11ea-814b-96655b99ad47.png)
![Screen Shot 2020-07-13 at 1 23 49 PM](https://user-images.githubusercontent.com/421781/87350030-1fae0880-c50c-11ea-96e1-44631002c09b.png)

**Comment by vikiCoder** [comment]
Hi @bramski,

If you are using the pre-signed POST request, you don't need to set the Authorization in Postman for that request. Because the AWS signature authorization helper in Postman is supposed to sign the request with given credentials. But since you are using **pre-signed** request, there is no need to sign it again. Just send the normal POST request with the keys (you've got while pre-signing the request) added to form-data and it should work.

**Comment by DannyDainton** [comment]
Closing due to age of issue and response time. Please feel free to reopen this if this is still an issue. Thanks!
