### ISSUE TITLE
unable to execute requests after Friday's update - 404 Not  Found

### ISSUE THREAD

**Issue by minakshi-goel** [a85/POSTMan-Chrome-Extension#8775]
I am getting "404 Not Found" error for every single request I am executing after Friday's update. All the requests were good before update.  This has stopped out testing completely. Could you please look into the issue at your earliest? I am available to talk/web call and show screen

Same requests with same URLs are good if executed thru swagger

This is the version I have : 
Postman for Windows
Version 7.28.0
win32 10.0.19041 / x64

**Comment by codenirvana** [comment]
Can you share more details about the request or a scaled-down collection/endpoint which we can use to reproduce this issue?

**Comment by minakshi-goel** [comment]
Hello Udit,

I am sending you the request and POST URL . but its in out QA environment. Not sure how you will be execute the same.

URL :  https://qa-edfi-api.tneducation.net/api/v31/ed-fi/classPeriods

{

  "classPeriodName": "02 - Traditional",

  "schoolReference": {
    "schoolId": 47
  },

  "_ext": {
    "tdoe": {
      "submittedForSchoolYearTypeReference": {
        "schoolYear": 2020
      },
      "submittedByEducationOrganizationReference": {
        "educationOrganizationId": 47
      }
    }
  }
}


[Small Department Logo for Email Signature]
Minakshi Goel| QA
Andrew Johnson Bldg, 10th Floor
710 James Robertson Pkwy, Nashville, TN 37243
615-770-3873
tn.gov/education
#TNBestforAll

**Comment by codenirvana** [comment]
This internal API will not help but due to 404, this problem looks specific to this particular endpoint.

Are you getting 404s for all the `qa-edfi-api.tneducation.net` APIs?
Are you getting 404 any other API endpoint (say `https://postman-echo.com/get`) as well?

**Comment by ParsonsProjects** [comment]
I am also getting this issue but with a GET request that is using pipelines in the query string.
For example: list-of-values?q=type=ISAUTO|keyGroup=branch 
Returns a 404: The request cannot be fulfilled due to bad syntax.
This is in version 7.28.0

**Comment by minakshi-goel** [comment]
I got the same error on one of our GET request yesterday.
Something is definitely wrong. All the end points were working until Friday.

Appreciate your quick help.

Thanks
Minakshi

**Comment by codenirvana** [comment]
@ParsonsProjects In the latest release, the default URL processor is [updated](https://github.com/postmanlabs/postman-app-support/issues/8154) due to which you are facing this issue.

The `|` used in the query string are no longer encoded by default which is causing the issue at your server-side.
This is because `|` is not an unsafe character in the query and hence doesn't require encoding. You might be facing the same issue when you send this request from any browser.

As a workaround, you can either manually encode the `|` to `%7C` or add the following script as part of your Pre-request script: 
```js
pm.request.url.query.each((q) => {
     q.update(encodeURI(q.toString()))
});
```

You can know more about this change [here](https://github.com/postmanlabs/postman-app-support/issues/8154).

**Comment by minakshi-goel** [comment]
Hello Udit,

So how soon you expect the updated version with this fix?
I practically can not write Pre-request script in all of my 1000s of scripts unless there is some common place to write once and accessed by all. Would be able to help with the same in the meantime?


Thanks
Minakshi

**Comment by minakshi-goel** [comment]
Hello Udit,

Unfortunately, the Pre-request script did not work. Still getting 404 Not Found !

Thanks,
Minakshi

**Comment by minakshi-goel** [comment]
Is there any way to revert the update and go back to previous version without disturbing anything else?

Thanks
Minakshi

**Comment by chrisdeso** [comment]
Hey @minakshi-goel!

Here's a link to the previous build that should work – [https://dl.pstmn.io/download/7.27.1/win64](https://dl.pstmn.io/download/7.27.1/win64)

Does toggling the next-gen URL processing setting **off** in the latest build yield different results?
![image](https://user-images.githubusercontent.com/4734306/87700636-41053380-c75c-11ea-8111-cd6df4daa05c.png)

**Comment by minakshi-goel** [comment]
Hello Chris,

Toggling worked for couple of POST but GET is still an issue.

Any special instructions to  install previous build? Would it overwrite all build files and keep my collections and setup as it is?

Thanks
Minakshi

**Comment by codenirvana** [comment]
> So how soon you expect the updated version with this fix?

This is not an issue, the requests are failing because of the restrictions on the requesting server. You can check the workarounds mentioned [here](https://github.com/postmanlabs/postman-app-support/issues/8791#issuecomment-661813107) for explicitly encoding additional characters.

> Toggling worked for couple of POST but GET is still an issue.

Looks like a separate issue then.

> Any special instructions to  install previous build? Would it overwrite all build files and keep my collections and setup as it is?

Make sure you are logged in and all your unsaved requests are synced.

@minakshi-goel To move forward we need more information about the requests or steps which we can follow to reproduce the issue locally.

**Comment by markyun** [comment]
I also encountered this error, but closing it solved the problem


![image](https://github.com/postmanlabs/postman-app-support/assets/2833137/e4816ead-ee7a-41c5-85ed-61c6a73959dc)
