### ISSUE TITLE
Error: tunneling socket could not be established, statusCode=407

### ISSUE THREAD

**Issue by orlowski-ra** [a85/POSTMan-Chrome-Extension#8783]
**Describe the bug**
After the 7.28 update, I am unable to use a custom proxy, while connecting to any URL. Each call ends with an error:

Error: tunneling socket could not be established, statusCode=407

The rollback to 7.27 does not fix the problem. This was tested on several different machines, and the proxy stops working the moment when the 7.28 update is applied.

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.28
 - OS: Windows 10

**Comment by stephan-tho** [comment]
Hi,
I'm getting exactly the same error since the update to v7.28.0. I've also tried removing the custom proxy config completely and setting it once again, but it didn't helped.

Other colleagues with v7.27.1 and the same proxy configuration can access still fine. Also executing a curl with that proxy worked fine.

**Comment by orlowski-ra** [comment]
Well, I expected at least some kind of response.

Since 7.28 you have started to encode the proxy password. The workaround is to stick to numbers/digits passwords only.

**Comment by shadow1163** [comment]
Mac 10.15.6 and PostMan v7.26 (upgraded to v7.28)
Ubuntu 20.04 and Postman v7.28 

I have same problem.

**Comment by m-urban** [comment]
Confirming this problem (macOS 10.14.6). Also experiencing the issue since updating to v7.28.
@orlowski-ra's workaround of sticking to numbers/digits in the password is unfortunately not an option for me, as I am depending on my corporate environment's password policy.

**Comment by Rikysonic** [comment]
Same thing here, we're stuck with calling APIs through VPN (proxy is needed and every call results in 407), and we cannot set the password as we want, due to password policy.

**Comment by srajamohan** [comment]
I am also facing same problem. I tried by setting proxy configuration manually but still it didn't work. In the logs I can see 
Error: tunneling socket could not be established, statusCode=407
Proxy
authenticate: true
disabled: false
host: "proxy-host"
match: {…}
password: "password"
port: 8080
tunnel: false
username: "username"

Postman for Mac
Version 7.29.1
OS X 19.6.0 / x64
macOs Catalina: version 10.15.6

**Comment by m-urban** [comment]
Dear Postman maintainers, @DannyDainton, @codenirvana,

Is there any progress on this regression? Not only is this bug a major annoyance but it renders the program unusable for me and others in our proxy-bound environments at the moment.

Let us know if we can help squashing this problem, e.g. by providing logs or anything.

Thanks,
Manfred

**Comment by codenirvana** [comment]
As mentioned in https://github.com/postmanlabs/postman-app-support/issues/8783#issuecomment-660046721, is everyone facing this issue because of any special character in the username or password field?

@orlowski-ra @m-urban @stephan-tho @Rikysonic Can you provide the following details:
* Proxy Setting: Custom or System
* Proxy Type: HTTP, HTTPS or BOTH
* Any special character in username or password:

I am not able to reproduce this issue locally so I must be missing the character set to test with.

**Comment by m-urban** [comment]
Hi @codenirvana,

Thank you for looking into this. Regarding your question:

> Proxy Setting: **System**
> Proxy Type: **BOTH**
> Any special character in username or password: **Yes, a hash character _#_**

This only recently became a problem with v7.28, evidently on both macOS and also Windows (as mentioned by @orlowski-ra)

**Comment by stephan-tho** [comment]
Hi @codenirvana,

below you find the requested information:

Proxy Setting: Custom
Proxy Type: BOTH
Any special character in username or password: Yes "_" character

Unfortunately the workaround (setting password without special characters) doesn't work for me, because my corporate environment requires special characters.

Edit:
Sorry, forgot to mention it: Also my Username contains a backslash (DOMAIN\User)

**Comment by Rikysonic** [comment]
Hi @codenirvana,

I can confirm that the problem is related to special characters, because if I remove the domain from username, and so the backslash (from DOMAIN\USERNAME to only USERNAME), then the 407 error disappears and everything works normally.

Here's my configuration:

Proxy Setting: Custom
Proxy Type: BOTH
Any special character in username or password:
- Username has a backslash (DOMAIN\USERNAME);
- Password has no special characters, only uppercase, lowercase and numbers.

Thanks,
Riccardo

**Comment by m-urban** [comment]
@codenirvana, were you able to reproduce this issue? Anything we can do to support?

**Comment by fermin-silva** [comment]
I can confirm I'm experiencing the same problem when the password contains the # symbol.
Going through cURL works, but getting error 407 in postman

**Comment by stephan-tho** [comment]
Are there already news related to that topic?
I'm still facing the same error in v7.34.0

Please let me know in case you need any additional information, in order to reproduce that issue. Thanks!

**Comment by vidushi1989** [comment]
Is there any update on this bug, as I have changed the password and removed special characters. I am still facing the same issue

**Comment by codenirvana** [comment]
Hey everyone 👋 

It took us a while to reproduce this issue locally and identify the root cause but finally, this issue will be fixed in the next app release (releasing this week).

**Comment by srajamohan** [comment]
Finally a good news 😀

**Comment by arlemi** [comment]
We had to delay the release of the app, I'm reopening this issue for now and will close it again once 7.35 is widely available. 🙂

**Comment by stackintrinsic** [comment]
> Mac 10.15.6 and PostMan v7.26 (upgraded to v7.28) Ubuntu 20.04 and Postman v7.28
> 
> I have same problem.





https://command-line-arguments16.github.io/7lBPpyWJfWoaR1jDUk1QQVvWj72wWIMtxwFb6rY/
