### ISSUE TITLE
Scrolling experience changed in this version?

### ISSUE THREAD

**Issue by vitor-piaia** [a85/POSTMan-Chrome-Extension#8784]
Why has the scrolling experience changed in this version?
I would like to know how to downgrade the version where I will get the top-level scroll.

**Comment by coditva** [comment]
Hey @vitor-piaia,

The scrolling has been improved in this version so that now you can **control** which pane you want to scroll at a time. You can also **resize** and **collapse** panes which you don't need for a decluttered UI.

You can also drop a mail at help@postman.com to get in a discussion around what is getting in the way. Since we understand that any change that we are accustomed to over the years may feel disruptive, our goal is to overall make the experience better in the new UI system. The more underlying feedback we get around the **workflow**, the better it will help us make the current system meet the remaining use cases.

Related: https://github.com/postmanlabs/postman-app-support/issues/5903
