### ISSUE TITLE
bring back the main window scrollbar, not just in the body window!

### ISSUE THREAD

**Issue by ariel-inmanage** [a85/POSTMan-Chrome-Extension#8788]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by coditva** [comment]
Hey @ariel-inmanage,

The scrolling has been improved in this version so that now you can **control** which pane you want to scroll at a time. You can also **resize** and **collapse** panes which you don't need for a decluttered UI.

You can also drop a mail at help@postman.com to get in a discussion around what is getting in the way. Since we understand that any change that we are accustomed to over the years may feel disruptive, our goal is to overall make the experience better in the new UI system. The more underlying feedback we get around the **workflow**, the better it will help us make the current system meet the remaining use cases.

Related: https://github.com/postmanlabs/postman-app-support/issues/5903
