### ISSUE TITLE
Workspace vertical scroll bar is missing in latest version v7.28.0

### ISSUE THREAD

**Issue by varrinagasai** [a85/POSTMan-Chrome-Extension#8789]
**Describe the bug**
After updating the latest version of Postman v7.28.0, unable to scroll down completely in workspace window. Individual Request and Response scroll is working fine.
**To Reproduce**
1. Update to latest postman version v7.28.0
2. Restart the postman app
3. Close the default Launchpad window
4. Open any REST API from collection

**Expected behavior**
Workspace window vertical scroll should be visible along Request and Response individual scroll's. 

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version :7.28.0
 - OS: win32 10.0.18362 / x64

![Postman_Scroll](https://user-images.githubusercontent.com/51435800/87676316-1637d100-c796-11ea-9913-d42975fef9dd.png)

**Comment by vaibhav-malpani** [comment]
Facing same issue and it's really annoying as I work on postman for almost half of my day. Please fix this ASAP.

**Comment by coditva** [comment]
The scrolling has been improved in this version so that now you can **control** which pane you want to scroll at a time. You can also **resize** and **collapse** panes which you don't need for a decluttered UI. For e.g. you can collapse the request section by dragging the response pane to the top and focus on the response.

![Screen Recording 2020-07-17 at 13 08 32](https://user-images.githubusercontent.com/8445768/87761262-c6591880-c82e-11ea-89bf-8223b0afd2a4.gif)

You can also just expand a collapsed section by clicking on the tab you want to work on

![Screen Recording 2020-07-17 at 13 11 46](https://user-images.githubusercontent.com/8445768/87761557-4c755f00-c82f-11ea-8338-080b0e1c6243.gif)


We understand that this might not be the most ideal solution for your use-case and would love to understand what the real problem is so that we can find the solution that fits everyone.

Related: https://github.com/postmanlabs/postman-app-support/issues/5903

**Comment by varrinagasai** [comment]
@coditva Thanks for the response. Improvisation is better when using Request and Response independently. But it is difficult every time resizing the scroll, checking and validating details between Request and Response sections. It's better to provide whole workspace scroll along with this. 
As a end-user using Postman app daily won't face any problem till now. Latest scroll improvisation isn't user friendly.

**Comment by sorin21** [comment]
I have the same problem varrinagasai. I downgrade to a prev version and disabled from settings download automatically updates.
[https://learning.postman.com/docs/administration/migrating-to-v7/#team-user-on-postman-v7](https://learning.postman.com/docs/administration/migrating-to-v7/#team-user-on-postman-v7)

**Comment by Lietsaki** [comment]
Same problem here. I understand that this was done intentionally, but it actually doesn't improve the UX. For example, I can't take screenshots of postman where more than one panel is shown, or at least most of it. @varrinagasai is right.

**Comment by JDHannan** [comment]
Instead of simply scrolling up and down, now you have to find the drag handle and drag the panel size up and down. This is not as good :(

**Comment by Delindel-ML** [comment]
This is beyond inconvenient, having a generalized scroll for both the request body and the response was seamless, it really felt bad when i noticed it was missing.

Time to roll back while this is reverted, i have installed version 7.28 and will stick to it for the time being, Postman is a free and amazing tool that a lot of us would dread not having, i hope the team can fix it but it they dont its fine.

Cheers!

**Comment by M-AamirBakhtiar** [comment]
This is just beyond frustrating  to have to constantly resize the two panes. Instead of Removing it Completely why cant we have the option to either select this new  method of resizing or choosing to stay with the old version of scrolling. Please i encourage you to consider this.

**Comment by Padmahas** [comment]
> I have the same problem varrinagasai. I downgrade to a prev version and disabled from settings download automatically updates.
> https://learning.postman.com/docs/administration/migrating-to-v7/#team-user-on-postman-v7

@sorin21 ,

Even I downgraded and disabled auto update. But it's not considering to stop auto updating. Every time I restart my laptop, I'm uninstalling the Postman and downgrading. Every single time. It's so frustrating. Is there is any way to forcefully stop updating?

**Comment by Padmahas** [comment]
> The scrolling has been improved in this version so that now you can **control** which pane you want to scroll at a time. You can also **resize** and **collapse** panes which you don't need for a decluttered UI. For e.g. you can collapse the request section by dragging the response pane to the top and focus on the response.
> 
> ![Screen Recording 2020-07-17 at 13 08 32](https://user-images.githubusercontent.com/8445768/87761262-c6591880-c82e-11ea-89bf-8223b0afd2a4.gif)
> 
> You can also just expand a collapsed section by clicking on the tab you want to work on
> 
> ![Screen Recording 2020-07-17 at 13 11 46](https://user-images.githubusercontent.com/8445768/87761557-4c755f00-c82f-11ea-8338-080b0e1c6243.gif)
> 
> We understand that this might not be the most ideal solution for your use-case and would love to understand what the real problem is so that we can find the solution that fits everyone.
> 
> Related: #5903

@coditva,

We can't search the bar to resize every single time to see Request body and Response body. Both windows are daily used by users. Resizing every single time is very much frustrating and it slows down the speed of working with Postman. Please add the vertical scroll bar back.
I simply mean, it's OK to have resize option, but not without vertical bar.

Thank you.

**Comment by haizhuling** [comment]
it updated,but the problem is still not solved,terrible UE :(

**Comment by krycha2341** [comment]
Hi,
when can we expect new version with old scrolling bar?
Working with new bar is really annoying.

**Comment by mohitranka** [comment]
@krycha2341 We have a solution that allows for seamless scrolling that should be available in the next or the release after next.

**Comment by malpanivaibhav** [comment]
Wow. Thanks. Time to turn ON automatic updates now 😂

**Comment by Garry14** [comment]
Dear, postman.. 

Old Vertical Scrollbar is more expected.. 
And ur new system is annoying at all, and makes me headache.. 

I hope you give it back to us for the next version..

**Comment by coditva** [comment]
Hey everyone, with the new release (version `7.31.0`), you will be able to easily switch to working on request or response with just a scroll, similar to how you're used to! 🎉

Simply press and hold the `Alt` (or `⌥` on MacOS) key and scroll the request or response to resize it. You can also use `Win+Alt` (or `⌘ + ⌥` on MacOS) while scrolling (in case you have the `Alt` key bound to something else).

![Screen Recording 2020-08-25 at 11 04 25](https://user-images.githubusercontent.com/8445768/91135044-8b6ac000-e6cb-11ea-8801-51ae9ede1167.gif)

You can also find the reference to this in the Shortcuts:

![image](https://user-images.githubusercontent.com/8445768/91133452-19927680-e6cb-11ea-8ece-4e1bf727b340.png)

We hope this would be easier and faster than dragging. We ask everyone to give it a try and let us know if we could solve your problem. Please do reach out with any concerns you have about this. ⌨️ 📜

**Comment by Garry14** [comment]
No.! I need old whole-area scrollbar.!
Do U get it?!

**Comment by saswatds** [comment]
@Garry14 some constructive feedback will be really helpful to us to understand why this new interface is annoying to you. 
The old vertical scroll bar caused the long standing double scrollbar problem which also annoyed a lot of people. Not having any easy solution made us complete rethink so that we can make UI better for everyone. 

We would like know a few things
1. Was the double scrollbar that happened with the previous implementation not a issue for you, if not then why?
2. What is the use-case that you are still not able to achieve with the new scroll to resize feature? (Our understanding and internal user feedback showed us that scroll to resize was as friction-less as the old scroll behavior)
3. Anything else that you want to add so that it will help us understand your root problem better. 

Please help us to help you. And sorry again, we are really trying our best to get it.

**Comment by Garry14** [comment]
> @Garry14 some constructive feedback will be really helpful to us to understand why this new interface is annoying to you.
> The old vertical scroll bar caused the long standing double scrollbar problem which also annoyed a lot of people. Not having any easy solution made us complete rethink so that we can make UI better for everyone.
> 
> We would like know a few things
> 
>     1. Was the double scrollbar that happened with the previous implementation not a issue for you, if not then why?
> 
>     2. What is the use-case that you are still not able to achieve with the new scroll to resize feature? (Our understanding and internal user feedback showed us that scroll to resize was as friction-less as the old scroll behavior)
> 
>     3. Anything else that you want to add so that it will help us understand your root problem better.
> 
> 
> Please help us to help you. And sorry again, we are really trying our best to get it.

Thank you.. 
1. Not at all, because I can see the height of scrollbar, It's whole-windows-vertical.. 
Furthermore I'm helped by the double scrollbar.. 

2.  How about making in Postman Setting Configuration (Full Vertical Scrollbar: On / Off)? 
I can get the Full Vertical Scrollbar which you mentioned as "Double Scrollbar" if I check (Turn On) that.. 
And whosever annoy that "Double Scrollbar", just uncheck it to Turn Off.. 

3. Thank you, i think that's enaugh

**Comment by cueo** [comment]
+1 to making it configurable via Settings.
Holding down Alt (or ⌥) is still an inconvenience. I think everyone would be happy if we could just have a toggle in the settings.

>1. Was the double scrollbar that happened with the previous implementation not a[n] issue for you, if not then why?

It isn't an issue since it always was seamless. Once a user hits Send, (s)he is mostly interested in the response. So even if the scrolling is hiding the request pane, it is fine.

### Please make it configurable in Settings. 🙏

**Comment by blquinn** [comment]
I think people are a little confused about what is going on here. There used to be _nested_ scrolling. Two scrollable panes inside of one larger scrollable pane. That was honestly really hard to use in my opinion and I do prefer the new layout so thanks for changing that.

It did introduce a new problem however, which is that on smaller screens, like on my macbook pro 13" (2020) I can see very little of either the request or response panes. The shortcut does help and is a good one to know. However I think perhaps a 3rd configuration may help. Given that there is so much going on in this app, you might consider having a stacked view with the request and  response panes on top of one another and a toggle to switch back and forth. Something like that would probably be ugly, but be much more usable on small screens.

With my screen size, I can get at most 13-14 lines of code on the request editor and response pretty view (28 total). That is very few lines to get a good idea of what is happening in the response, you generally want as much vertical real estate as possible when looking at code / data.

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/6005812/98726727-e3c56b80-2364-11eb-9958-abf26f4633da.png">

**Comment by blquinn** [comment]
Horizontal is kind of a bummer too. Super cramped both ways. @coditva 

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/6005812/98726990-3e5ec780-2365-11eb-91cd-2e9abf1d28c3.png">
