### ISSUE TITLE
URL encoding is not happening for postman version 7.26.1 for Content-Type: application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by dadasopawale** [a85/POSTMan-Chrome-Extension#8791]
**Describe the bug**
URL encoding is not happening for postman version 7.26.1 for Content-Type: application/x-www-form-urlencoded.
Same request tried in postman version 7.25.0, working as expected 

**To Reproduce**
try request with special character.

**Expected behavior**
it is should pass values by encoding the request

**Comment by appurva21** [comment]
Hey @dadasopawale !!

I am unable to reproduce the issue on the latest app version (`v7.28.0`). I can see the characters are getting encoded correctly.

![image](https://user-images.githubusercontent.com/24985700/87760471-6ada5b00-c82d-11ea-9aae-efd2c84dd249.png)

Can you please share the characters from request body that are not getting encoded for you so that we can try to reproduce this issue on our end?

Also, try updating the App to the latest version (`v7.28.0`) and check if the issue still persists.

**Comment by ManikandanRajendran** [comment]
@appurva21 I'm also facing the same issue. when passing the decoded params in the URL, Its returning 400 Bad Request. Its returning success response when passing the encoding params.

**When passing direct values**
![image](https://user-images.githubusercontent.com/17049131/87777018-a4589980-c820-11ea-9748-0a37056ed69d.png)

**After passing Encoded value**

![image](https://user-images.githubusercontent.com/17049131/87777261-18933d00-c821-11ea-8a90-320e8c4ba5ec.png)

**Comment by dadasopawale** [comment]
Hi Appurva,

Pass value in query parameter,

Test data : password=abcd@12%&

**Comment by atmullan** [comment]
Also getting 400 Errors with encoded Query Strings, using fiddler Postman  v7.28.0  is sending a Param like this `filter={%22resource_id%22:%22vol-0419229b038dc6442%22,%22resource_name%22:%22vol-0419229b038dc6442%22}` instead of `filter=%7B%22resource_id%22%3A%22vol-0419229b038dc6442%22%2C%22resource_name%22%3A%22vol-0419229b038dc6442%22%7D`

**Comment by codenirvana** [comment]
Hey everyone 👋 
Looks like you're all facing issue because of encoding in query param, the issue title is misleading.

In the latest release, the default URL processor is updated due to which you are facing this issue. You can read more about this change [here](https://github.com/postmanlabs/postman-app-support/issues/8154).

The new URL processor follows the [WHATWG (URL) standards](https://url.spec.whatwg.org/) which is widely adopted in web browsers and modern programming languages. You can try sending the same request via a browser and see similar behavior.

According to the WHATWG standard, only the following characters in the query string needs to be encoded: `SPACE`, `"`, `#`, `&`, `'`, `<`, `=`, `>`. For any additional character which requires explicit encoding because of the requesting server restrictions, I suggest either:
-  Manually encode those particular characters
- Highlight the text and right-click to encode the selection using the helper
![Screenshot 2020-07-21 at 5 25 33 PM](https://user-images.githubusercontent.com/4865836/88052150-70120f80-cb77-11ea-9c06-e8d2cfa0b373.png)
- Add the following script as part of your Pre-request script to do the same:
```js
pm.request.url.query.each((q) => {
     q.update(encodeURI(q.toString()))
});
```
