### ISSUE TITLE
'{', '}' and ':' not being URL encoded in query params

### ISSUE THREAD

**Issue by 1raghavmahajan** [a85/POSTMan-Chrome-Extension#8808]
**Describe the bug**
For some reason some characters like `{ } :` not being URL encoded in query params.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new request.
2. Add a query parameter with value = ` {"hello":{"$word":"world"}}`
3. See console output with your request. The param will be partially encoded as `{%22hello%22:{%22$word%22:%22world%22}}`
4. Now select the query param value in the parameters list, right-click, and select `EncodeURIComponent`, you will see the correctly encoded value as `%22hello%22%3A%7B%22%24word%22%3A%22world%22%7D%7D`.

**Expected behaviour**
The query params should be correctly encoded.

**Screenshots**
![image](https://user-images.githubusercontent.com/12858001/88096578-7ffc1480-cbb4-11ea-8de6-5f73afd8491f.png)

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : v7.28.0
 - OS: Windows 10

**Comment by codenirvana** [comment]
@Raghav-intrigue The [new URL processor](https://github.com/postmanlabs/postman-app-support/issues/8154) follows the [WHATWG (URL) standards](https://url.spec.whatwg.org/) for encoding the different parts in the URL and `{`, `}`, and `:` are not reserved characters which require automatic encoding. You can try sending the same request via a Browser and notice a similar behavior.

If your requesting server needs explicit encoding, you can check the different workarounds [discussed here](https://github.com/postmanlabs/postman-app-support/issues/8791#issuecomment-661813107).
Are you facing any particular issue because of this?

**Comment by cowtowncoder** [comment]
This will definitely cause issues for Java services that apply stricter validation of URLs, including query parameters.

Quarkus/RESTeasy combo seems to barf on un-encoded curly braces, for example; probably same for brackets.
