### ISSUE TITLE
Postman sandbox api reference document mentions test specifications can be written inside Pre-request Script

### ISSUE THREAD

**Issue by saiudayakella** [a85/POSTMan-Chrome-Extension#8836]
**Describe the bug**
Postman sandbox api reference document mentions test specifications can be written inside Pre-request Script

**To Reproduce**
1. Go to 'https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#pmtest'
2. Look at the introduction part for `pm.test` function
```
pm.test(testName:String, specFunction:Function):Function
You can use this function to write test specifications inside **either the Pre-request Script or Tests sandbox**. 
```
**Expected behavior**
I presume, tests can be defined only under `Tests` tab and not under `Pre-request` tab. 

**Screenshots**
![image](https://user-images.githubusercontent.com/19469293/88474952-c368d100-cf6e-11ea-8b7b-f62679cfdba1.png)

**App information (please complete the following information):**
 -NA-

**Additional context**
-NA-

**Comment by DannyDainton** [comment]
Hey @saiudayakella

Would you be able to clarify your issue here, please? Not sure that I follow what your concern is here, is it the documentation or the functionality? 


Tests can be created in either the `Pre-request` or `Test` sandbox. These would be specific to that part of the sending flow - You couldn't for example, assert (`pm.expect`) that something is present in the response body, within a `Pre-request Script` as that is run **before** the response has been received.

What you could use it for is to assert that specific Request Headers are used or that a required property is part of the Request payload.

**Comment by saiudayakella** [comment]
Hey Danny,

I mentioned the issue w.r.t api reference document and attached respective screemshot of that section as well.

Are you referring to assertions as tests (or)are you saying, similar to ‘Tests’ tab, tests/test scripts can be written (inside pm.test function) under ‘pe-request script’ tab as well?

**Comment by DannyDainton** [comment]
The `pm.test` function can be used inside the `Pre-request`, as stated in the documentation. Just like you would use it in the `Tests` tab. 

The only change in the different contexts would be _what_ you're asserting.

**Comment by DannyDainton** [comment]
I'm going to close this issue out as it's not related to the functionality within the sandbox. 

If this doesn't answer your original question, could you raise an issue on the documentation repo please. 

https://github.com/postmanlabs/postman-docs
