### ISSUE TITLE
Plus sign not encoded in x-www-form-urlencoded body

### ISSUE THREAD

**Issue by danbars** [a85/POSTMan-Chrome-Extension#8849]
**Describe the bug**
When adding body key/values, and setting the body to `x-www-form-urlencoded`, plus sign in the values is not encoded. Therefore it is being decoded as a space by the server

**To Reproduce**
1. Create a new `POST` request
2. Set body to `x-www-form-urlencoded`
3. add param key `P1` and value `A&B`
4. add param key `P2` and value `A+B`
5. Click the `code` snippets link, and choose `http` on the left side of the dialog
6. You'll see the request body (after all the http headers) as `P1=A%26B&P2=A+B`

This is also the way the actual request is sent to the server, which is wrong.

**Expected behavior**
Plus sign should be URL Encoded just like `&`. Expected result is **(EDIT)** ~~`P1=A%26B&P2=A%20B`~~ `P1=A%26B&P2=A%2BB`

**EDIT - MORE DETAILS** - I expect the characters entered in the key/value UI to be treated literally, and not as if I entered an escaped code. Currently `&` is treated as literal while `+` is treated as escaped space character. This is inconsistent behavior.

**App information (please complete the following information):**
 - Native macos app
 - Postman 7.28.0
 - OS: Mac 10.14.6

**Comment by mohitranka** [comment]
@danbars I just tried reproducing it ( [with this](https://gist.github.com/codenirvana/afb41744865e13d77da7be7ed2f2539c) ) , and it seems to be working fine. This is still a valid issue for code generation.

Can you please post the result of the output, when you try to reproduce the result using the above http server?

**Comment by danbars** [comment]
Hi @mohitranka , I'm not sure what's the connection between the raw echo server that you've sent and the bug that I've opened. 
The bug is in postman app. I've provided exact step-by-step how to reproduce it using the app itself. 
Have you tried reproducing using the app itself using the steps that I've described?
You can see the problem even without making any actual request, just by looking at the generated http code. 
Therefore I don't think the problem is with the underlying http server. I think it's the code that generates the request for that server.

**Comment by danbars** [comment]
Hi @mohitranka ,

Actually there's a mistake in my bug description. 
I wrote that the expected result is `P1=A%26B&P2=A%20B` while the expected result is really `P1=A%26B&P2=A%2BB`
`%20` is space character, while plus character should be encoded as `%2B`
When I use the key/value UI to add parameters, I expect them to be encoded so the server will get them literally, and not as if I entered them escaped.
I'm updating the bug description to reflect that

**Comment by mohitranka** [comment]
@danbars the expect result on App v7.29.1 is `P1=A%26B&P2=A%2BB`, for the request.
![image](https://user-images.githubusercontent.com/80672/89122896-d2103480-d4e8-11ea-90ef-bcb82c6009e5.png)

**Comment by danbars** [comment]
Excellent! Thanks

**Comment by danbars** [comment]
Actually I just now see that the `%2B` is the response from the echo server, not the request that was sent. The request as seen in line 1 contains the character `+` which is interpreted as space by the server when url-decoding the body.
So let me ask this:
When I use the UI to enter key/value, am I expected to enter escaped values, or unescaped ? 
My point is that currently there's inconsistent behavior that `&` is being escaped to `%26`, and `+` is sent literally as `+`.
You can see that in line 1 of your screenshot.

**Comment by xk0der** [comment]
@danbars The spec states that `+` is a reserved character, thus it will not be automatically encoded to %2B.
_Reference_: https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1

https://www.ietf.org/rfc/rfc2396.txt states
> 3.4. Query Component
> 
>    The query component is a string of information to be interpreted by
>    the resource.
> 
>       query         = *uric
> 
>    Within a query component, the characters ";", "/", "?", ":", "@",
>    "&", "=", "+", ",", and "$" are reserved.

You must manually pass `%2B` instead of `+` in the data being passed to your server if you need that.

**IMPORTANT**
* Do note: `+` and `%2B` interpretation by the receiving server is totally depended on the server itself or the code being executed via the server.  The behaviour may be configurable at the server-side or within the programming language framework you are using. 
* Ideally, `+` is treated as space and `%2B` is decoded as literal "`+`" symbol at the server end per the specification. Depending on the language/framework you may have to explicitly decode the data to convert `%2B` to `+`

Just out of curiosity: Which language/framework is being used at your server's end?

**Comment by xk0der** [comment]
@mohitranka I believe this should be a `feature-request` rather than a bug.

Developers are used to their libraries and framework auto encoding form data in most instances, and most modern libraries and framework encode "`+`" to "`%2B`" in form data.

While Postman's default behaviour is correct as per spec, a setting to encode "`+`" to "`%2B`", especially in form data may be useful. This would make it easier to write and consume data visually while working within Postman and user/developers will get expected behaviour parsing the request at their server's end.

~Thoughts?~ Nevermind, I see you have already mentioned about "code-generation" which makes more sense. 
Keeping this comment here for completeness.

**Comment by codenirvana** [comment]
> Actually I just now see that the %2B is the response from the echo server, not the request that was sent. The request as seen in line 1 contains the character + which is interpreted as space by the server when url-decoding the body.

@danbars As per specification, there's a difference in how characters in `x-www-form-urlencoded` body and query params in URL are percent-encoded.

> When I use the UI to enter key/value, am I expected to enter escaped values, or unescaped ?
My point is that currently there's inconsistent behavior that & is being escaped to %26, and + is sent literally as +.

`&` is percent-encoded automatically when entered in the key or value field of query params because `&` and `=` are reserved characters in the URL (`&` is used to separate params) and requires explicit encoding.
You can know more about our URL encoding here: https://github.com/postmanlabs/postman-app-support/issues/8154.

> I believe this should be a feature-request rather than a bug.

@xk0der Here it is https://github.com/postmanlabs/postman-app-support/issues/8626 😄

**Comment by danbars** [comment]
ok, commented on #8626 
Closing this issue.
