### ISSUE TITLE
Adding PFX certificate in settings results in wrong path to file

### ISSUE THREAD

**Issue by RaptorCZ** [a85/POSTMan-Chrome-Extension#8852]
**Describe the bug**
Adding a new certificate to handle domain results in invalid path. Instead of "C:\Temp\cert\aaa.pfx" is path stored as "
/C:/Temp/cert/aaa.pfx". Then it is unable to create request.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Certificates'
3. Click on 'Add Certificate'
4. Fill data and select pfx certificate from disk
5. See 'PFX file' path

**Expected behavior**
Path to certificate is stored correctly

**Screenshots**

**App information (please complete the following information):**
 - Postman Version [7.29.1]

**Additional context**

**Comment by saswatds** [comment]
Hi @RaptorCZ the file path that you see `/C:/Temp/cert/aaa.pfx` is postman normalised file path that we store in order to maintain compatibility between different operating systems for collaboration. 
We updated all of the files handing used in postman to use this generic implementation and use a custom file resolver for all files reference which enables us to understand this path and resolve the path based on the operating system. 

Having given the context, we tried reproducing the issue in windows, where having given the normalised path if the pfx certificate was not loading correctly and we were not able to reproduce any failures. Can you confirm that the requests are actually failing?

**Comment by RaptorCZ** [comment]
Well, tried it again and now I can't get any error. So it seems it has been related to something else, not path itself. Tried to remove/add new certificates etc. no problem now. So false alarm. Thnx for your time.
