### ISSUE TITLE
Getting 404 Not Found error

### ISSUE THREAD

**Issue by rahul2891987** [a85/POSTMan-Chrome-Extension#8860]
**Describe the bug**
I am trying to access an end point URL with a POST request and getting 404 Not Found error. My other team mate is able to access the same end point and able to get the response back successfully. The only difference I could see is I am on version 7.29.1 and he is using 7.29.0.

**To Reproduce**
1. Download 7.29.1 version & run the request .
2. Check for the error.

**Expected behavior**
Expecting a successful response back.

**Screenshots**
![Postman Error](https://user-images.githubusercontent.com/68972636/88855616-2651a680-d1c1-11ea-962b-9d7dcf177352.jpg)

**App information (please complete the following information):**
 - App Type [Chrome App]
 - Postman Version [7.29.1]
 - OS: [Windows 10

**Comment by SabriH10** [comment]
Hi @rahul2891987 , It would help if you can provide more information about the request itself ( omitting any sensitive information of course ) I'm not quite sure the difference in version would be the culprit here. 
A few things worth checking, did you look at the [Postman Console](https://learning.postman.com/docs/sending-requests/troubleshooting-api-requests/#debugging-and-logs) to see how the request is being sent? ( I'd compare that to your teammate's request to see if there are any significant differences ) 

- Have you tried making a cURL request to the same endpoint to see if this issue persists outside of Postman? You can use the [Code Generator](https://learning.postman.com/docs/sending-requests/generate-code-snippets/#generating-code-snippets-in-postman), if needed, to generate the cURL request.

I believe the Postman Console should help troubleshoot this and will be helpful to compare the request sent ( vs your teammates ). Hope this helps!

**Comment by harrymaurya05** [comment]
> Hi @rahul2891987 , It would help if you can provide more information about the request itself ( omitting any sensitive information of course ) I'm not quite sure the difference in version would be the culprit here.
> A few things worth checking, did you look at the [Postman Console](https://learning.postman.com/docs/sending-requests/troubleshooting-api-requests/#debugging-and-logs) to see how the request is being sent? ( I'd compare that to your teammate's request to see if there are any significant differences )
> 
> * Have you tried making a cURL request to the same endpoint to see if this issue persists outside of Postman? You can use the [Code Generator](https://learning.postman.com/docs/sending-requests/generate-code-snippets/#generating-code-snippets-in-postman), if needed, to generate the cURL request.
> 
> I believe the Postman Console should help troubleshoot this and will be helpful to compare the request sent ( vs your teammates ). Hope this helps!

I am facing a same issue and I have tried cURL its working fine outside the postman.

**Comment by SabriH10** [comment]
Hi @harrymaurya05 , Did you get a chance to follow some of the suggestions to troubleshoot? I'd suggest comparing the request via Postman vs cURL - The Postman Console should help in that regard. Are you running behind a VPN or Proxy? 
Are all requests failing for you via Postman or just a particular request?

**Comment by harrymaurya05** [comment]
> Hi @harrymaurya05 , Did you get a chance to follow some of the suggestions to troubleshoot? I'd suggest comparing the request via Postman vs cURL - The Postman Console should help in that regard. Are you running behind a VPN or Proxy? 
> Are all requests failing for you via Postman or just a particular request?

Just a some particular request are failing. I tried some of troubleshoot but nothing work.

**Comment by SabriH10** [comment]
Hi @harrymaurya05,

Thanks for following up. What troubleshooting suggestions did you try? The Postman Console should provide more insight for the request. If some requests are failing but not all I'm inclined to believe digging deeper into those particular requests ( why it works outside of Postman vs the app ) by comparing the request (e.g. compare the request in Postman vs cURL ) should help here.

**Comment by SabriH10** [comment]
Hi @harrymaurya05 & @rahul2891987 ,
I'll be closing this issue as we haven't received a follow-up with additional information to help troubleshoot further. 
Feel free to reach out to help@postman.com or the [Community Forum](https://community.postman.com/) if you still require assistance and please do include the information requested above. Have a great day!
