### ISSUE TITLE
Resizing header columns does not resized the rows under it

### ISSUE THREAD

**Issue by retzloff** [a85/POSTMan-Chrome-Extension#8918]
**Describe the bug**
With a request selected, adjusting the width of the "description" header column does not resize the rows beneath it. This only occurs when "Headers" is selected. "Params" works as expected. 

**To Reproduce**

1. Open a request.
1. Select "Headers".
1. Click and drag on the column separator between "Value" and "Description". 
1. See the head columns adjust but the following rows do not. 

**Expected behavior**
I would expect all the rows to resize when a header is resized - just like how the "Params" tab behaves.

**Screenshots**
Expected:
<img width="519" alt="correct" src="https://user-images.githubusercontent.com/18519/89965522-10a99b80-dc1b-11ea-9977-5d81ccf505a0.png">

Actual:
<img width="487" alt="incorrect" src="https://user-images.githubusercontent.com/18519/89965532-156e4f80-dc1b-11ea-85a3-ba24f56f5a8c.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.30.1
 - OS: macOS Catalina 10.15.6

**Additional context**
---

**Comment by DannyDainton** [comment]
Hey @retzloff 

This is due to no being able to add a `description` against the system auto-generated headers. The cells that you can add a description can be resized to allow for the length of the text added. Granted is _looks_ a bit strange. 🤔 

![Screenshot 2020-08-12 at 09 21 45](https://user-images.githubusercontent.com/17089546/89992522-47b09900-dc7d-11ea-8461-9fbbcca98f68.png)

If you were to hide the auto-generated headers, you wouldn't be seeing this _mis-allignment_.

![Screenshot 2020-08-12 at 09 23 26](https://user-images.githubusercontent.com/17089546/89992768-a8d86c80-dc7d-11ea-8983-949284325d6c.png)

I'm going to raise this internally as an issue as it should probably be all the same alignment when resizing the columns, regardless if they are auto-generated headers or not. Thanks for flagging this. 🏆

**Comment by joebiker** [comment]
@retzloff Thanks for posting this issue.  I was really confused. 
I guess it makes sense if the auto-generated columns are hidden, but would be a good fix.
