### ISSUE TITLE
View panel that displays all variables

### ISSUE THREAD

**Issue by ericchansen** [a85/POSTMan-Chrome-Extension#8937]
It would be fantastic if I could view a vertical panel that displays all of the variables. It's inconvenient to have to open up the little eye in the upper right hand corner whenever I want to view them. I want to run my requests, use the tests to automatically update the variables and then be able to see the new variables without clicking on the little eyeball.

**Comment by DannyDainton** [comment]
Hey @ericchansen

As a workaround, you could use this in the `Tests` tab of the request, to see those variables printed in the console? 

```
console.log(pm.environment.toObject())
```

Now that the console opens within the app, you could see those new values after the request is made without needing to use the quick view. 

```

**Comment by ericchansen** [comment]
That's a nice temporary workaround. Thanks! Anyway, it'd still be a really cool feature if someone on your front end team is feeling bored. 😁

**Comment by skatikia** [comment]
@ericchansen Sorry for the delayed action, but this is done! (not because we were bored, but because we got excited!)

With Postman **V11.14**, we have introduced **a way for you to view all your variables in one place**.

Click on the button next to the environment switcher to bring up the variables pane. This pane bubbles up the variables used in the request and also shows variables that are accessible from different scopes (collections, environments and globals).

![variables-pane](https://github.com/user-attachments/assets/28443513-2c48-4065-82fa-48c7cb02bb63)

I hope you like this change as much as we do! Update your app to start working with this change and many more, and let us know what you feel ([over a call](https://calendly.com/shobhit-katikia/meet-with-shobhit) or just drop an email to [shobhit.katikia@postman.com](mailto:shobhit.katikia@postman.com)).

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)
