### ISSUE TITLE
Custom domain with app.br TLD is bugged

### ISSUE THREAD

**Issue by andre-bohlsen** [a85/POSTMan-Chrome-Extension#8987]
**Describe the bug**
We were publishing one collection on the postman website and decided to put it on a custom domain. In brazil we can have app.br TLDs. So when we tried to register our domain. It didn't recognize our domain
**To Reproduce**
1. Go to https://XXXX.postman.co/settings/team/custom-domains
2. Click on add a new domain
3. type the domain example.domain.app.br
4. the service will now look at app.br for the txt

**Expected behavior**
the service should look at domain.app.br for the txt

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] website
 - Postman Version [e.g. 6.0.1] NA
 - OS: [e.g. macOS High Sierra 10.13.2] NA

**Additional context**

**Comment by ahcode0919** [comment]
Hi @andre-bohlsen , are you encountering an error with the TXT and CNAME fields being populated on the website? Or is it unable to verify the the domain after you've updated the DNS records?

**Comment by andre-bohlsen** [comment]
Its unable to verify the domain. I'm trying to verify the domain
docs.mydomain.app.br. the site states:

TXT record on app.br

Add the following token as a TXT record associated with app.br
instead of mydomain.app.br

Hope it clarified your doubt.

Regards,

André

**Comment by Cazaimi** [comment]
@andre-bohlsen , it looks like the CNAME and TXT records for your domain, `docs.mydomain.app.br` have not been created yet (Since, we're past the propagation time).

<img width="1266" alt="Screenshot 2020-09-07 at 6 14 21 PM" src="https://user-images.githubusercontent.com/13660453/92475799-9d844c80-f1fb-11ea-8ba0-eb4b73515f3f.png">
<img width="1264" alt="Screenshot 2020-09-07 at 6 14 29 PM" src="https://user-images.githubusercontent.com/13660453/92475820-a1b06a00-f1fb-11ea-83a1-0002d3c1a351.png">

As for your issue with adding the TXT record, please check your domain provider's documentation around adding TXT records to a domain. 

This is not an issue with Domain Verification. Please feel free to leave a comment if your issue remains unsolved. 🙂

**Comment by ranchanarajasekaran** [comment]
We have fixed this. Please feel free to reopen if you still face any issues
