### ISSUE TITLE
unable to use self signed cert during mutual tls authentication. the cert is self signed with local with subaltname value being 127.0.0.1

### ISSUE THREAD

**Issue by PNat01** [a85/POSTMan-Chrome-Extension#9012]
![image](https://user-images.githubusercontent.com/58553892/91957866-824aa600-ecfe-11ea-8447-866f4aec6819.png)

**Comment by DannyDainton** [comment]
Hey @PNat01 

Could you fill out the following template with as many details as you can please:

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
Add any other context about the problem here.

**Comment by PNat01** [comment]
i got it working. Sorry about the bother.
