### ISSUE TITLE
Change Variables Order is Very Slow

### ISSUE THREAD

**Issue by VincentChen1212** [a85/POSTMan-Chrome-Extension#9015]
When I Change the Order for Variables / Global Variable,
if items a little much, it is very very very slow.
Sometimes crash.

**Comment by DannyDainton** [comment]
Hey @VincentChen1212 

Could you fill out the following template with as many details as you can please:

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
Add any other context about the problem here.

**Comment by DannyDainton** [comment]
Hey @VincentChen1212,

Without the basic information, we will be unable to do anything about this issue. I'm closing the issue for now but we can reopen if we receive more context about the problem.
