### ISSUE TITLE
Drag-n-drop one call scrolls the console

### ISSUE THREAD

**Issue by plysachev** [a85/POSTMan-Chrome-Extension#9031]
**To Reproduce**
1. Take a collection with 100+ requests
2. Run it couple of times so you get a lot of records in the console
3. Take one request from the top of the list
4. Start dragging to the bottom of the collection

**Actial Result**
When your mouse pointer moves over the console window, console messages are scrolled up

**Expected behaviour**
When your mouse pointer moves over the console window, console messages are NOT scrolled up (because if makes no sense to drop a request into console window).

**Screenshots**
Can not share, it contains sensitive information

**App information** (please complete the following information):
•	Native app
•	7.31.1
•	OS: Windows 10

**Comment by DannyDainton** [comment]
Hey @plysachev 

Could you fill in the template issue please, this will allow us to investigate the issue that you're currently seeing? We need to ensure that we're looking at the correct platform, OS and Postman version. The more details you can provide the easier it will be for us to see what's going on.

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
Add any other context about the problem here.

**Comment by plysachev** [comment]
Done

**Comment by DannyDainton** [comment]
Hey @plysachev 

I've been able to replicate what you're seeing, this is also the case if you had the `Find and Replace` tab open. 

![console_scroll](https://user-images.githubusercontent.com/17089546/92920014-7317d680-f429-11ea-810d-2ea33cbe87d5.gif)

I'm going to open a Bug for this issue - We will update this thread once we have more information.

**Comment by giridharvc7** [comment]
This is now fixed in v10+ version of Postman. Feel free to open this if you face this issue again.
