### ISSUE TITLE
JSON pretty response stopped working in 7.32.0 on MacOS

### ISSUE THREAD

**Issue by carcus88** [a85/POSTMan-Chrome-Extension#9049]
**Describe the bug**
Pretty JSON response no longer working

**To Reproduce**
1. Run an API query that returns JSON
2. View it using the "Pretty" output

**Expected behavior**
A JSON tree should be produced

**Screenshots**
![image](https://user-images.githubusercontent.com/95110/92974703-cb180280-f454-11ea-92a8-509c6e486da0.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.32.0
 - OS: macOS 10.15.6

**Comment by agdgdh** [comment]
This issue was very critical especially 2byte iso overlaying works. 
"I'm from ,U.K.,U.S.,Fr.,De.,Japan.
Strong especially From Japan.
Often Japanese page appears this pages do not translate and stalking effectively.
License file is locked do not modify. This means third party like harm real attacking material. Combined python fake trapped.

**Comment by DannyDainton** [comment]
Hey @carcus88,

Thanks for writing in, I mocked out a response that I thought might cause the issue after seeing your response body. It looks like a mixture of single and double quotes is impacting the beautify option.

<img width="1498" alt="Screenshot 2020-09-12 at 07 13 25" src="https://user-images.githubusercontent.com/17089546/92988903-b6288700-f4c7-11ea-96de-7ace301b9c14.png">

I tried the same thing in the Request Body and it looks like a similar thing is happening and it's showing a validation issue.

<img width="1026" alt="Screenshot 2020-09-12 at 07 14 39" src="https://user-images.githubusercontent.com/17089546/92988904-b759b400-f4c7-11ea-9001-c1791e792839.png">

Would you also be able to paste your full response body, please? Mask out/change any sensitive values.

I'm going to raise an issue for this so that we can take a closer look at what's going on - We will update the thread once we have more information.

**Comment by carcus88** [comment]
Sure thing, here is the full response 


[response.json.zip](https://github.com/postmanlabs/postman-app-support/files/5218964/response.json.zip)

**Comment by DannyDainton** [comment]
Hey @carcus88 

I created a mock server which returns you response body and I was unable to see the same response as you were getting.

![Screenshot 2020-09-15 at 13 55 01](https://user-images.githubusercontent.com/17089546/93212966-31ee3200-f75b-11ea-8e68-ffd5021f9f21.png)

My example was using invalid JSON so the expectation there would be that the formatting work work upto the point of the single quotes.

Is there any other details about the request that might be causing this issue on your side? Could you provide us some information about the request and response headers? Are you using an scripts that could impact the request?

Anything else that help us to reproduce the issue would be awesome! 😄

**Comment by carcus88** [comment]
Quitting and restarting a couple times fixed the issue somehow. Sorry about the false positive...

![image](https://user-images.githubusercontent.com/95110/93233812-7f61a380-f749-11ea-92a2-e3c2f7d6d2c6.png)

**Comment by DannyDainton** [comment]
Yay, no worries. Glad that sorted it out for you.

**Comment by uuf6429** [comment]
I have the same problem... and frankly, the "restart a few times" approach reminds me of the reliability of Windows 98...
Just saying, if it's a bug it's a bug.

**Comment by rajesh38** [comment]
Same issue happened just now. Just restarted postman. It got sorted on its own.

**Comment by trentjones21** [comment]
Same issue here.  Had to restart twice to get it fixed.

**Comment by colin-extend** [comment]
Same for me

**Comment by fojuth** [comment]
The problem still exists, I've restarted Postman just today and (again) the problem came back.

**Comment by Fyb3roptik** [comment]
Still an issue here on macos. I have restarted several times to no avail

**Comment by nairs** [comment]
I have this problem, with GraphQL request on Mac running macOS Ventura Version 13.4.1 and Postman 
Version 10.17.4
UI Version: 10.17.4-ui-230825-0719
Desktop Platform Version: 10.17.4 (10.17.4)
