### ISSUE TITLE
Contract Tests Bug

### ISSUE THREAD

**Issue by michael-molina-by** [a85/POSTMan-Chrome-Extension#9142]
Currently there is a bug with contract testing. When I have an OpenAPI 3.0 component with multiple types and use oneOf or anyOf, it will only validate it against the first on that list.

![image](https://user-images.githubusercontent.com/62351017/95395788-433ae200-08b4-11eb-9465-a9d2eeb98891.png)
![image](https://user-images.githubusercontent.com/62351017/95395802-49c95980-08b4-11eb-8f51-0b971d12efbe.png)
![image](https://user-images.githubusercontent.com/62351017/95395821-55b51b80-08b4-11eb-8285-6b9639eab9f4.png)

**Expected behavior**
Match expected validation according to Open API 3.0 standards.

**Comment by michael-molina-by** [comment]
The validation errors changes on the ordering of the oneOf/anyOf. I have also tried directly putting the types such as string, number, boolean and the same error happens.

**Comment by jan-kleiss** [comment]
This bug makes the validation feature useless because we get tons of false errors which cover actual errors. The issue has already been [reported one and a half years ago](https://community.postman.com/t/how-much-of-openapi-3-syntax-is-currently-supported-by-collections/15817) without any reply. Furthermore, I don't think there's a way to filter certain types of errors which could at least temporarily serve as a workaround. I guess we'll have to evaluate SmartBear Connect or another solution because we need to ensure that the schema delivered to our customers matches our implementation.

**Comment by 5thdimensional** [comment]
@raghumurthy-jayandran I've re-tagged this for api-design since the issue relates to validation

**Comment by VShingala** [comment]
@michael-molina-by This issue should be addressed now. Can you let us know if you're still able to reproduce it?

**Comment by shashankawasthi88** [comment]
Hi All, this issue should be solved with the latest release of Postman. Read more about the latest updates [here](https://learning.postman.com/docs/designing-and-developing-your-api/developing-an-api/adding-api-elements/#keeping-a-collection-in-sync-with-an-api). Feel free to reopen this issue if it still exists.
