### ISSUE TITLE
Edit Folder Authorization Bearer Token popup variables displayed BELOW the form

### ISSUE THREAD

**Issue by m4ss1m0g** [a85/POSTMan-Chrome-Extension#9161]
**Describe the bug**
When entering the {{ on the Token field under Edit folder / Authorization tab the _intellisense_ display the popup **UNDER** the form (see the image attached)

**To Reproduce**
1. Edit Folder
2. Select Authorization
3. Set Bearer Token
3. Enter the {{ on the Token field

**Expected behavior**
The correct display of variables

**Screenshots**
![Screenshot 2020-10-14 104425](https://user-images.githubusercontent.com/4323707/95965476-45e48c80-0e0a-11eb-8519-8b4a3d159975.png)

**App information (please complete the following information):**
 - Postman Version 7.34
 - OS: Windows 10

**Additional context**
I don't know if is related, but entering manually the value of the variable is not set on folder's request

**Comment by DannyDainton** [comment]
Hey @m4ss1m0g 

Thanks for raising this - we're tracking this issue here:

https://github.com/postmanlabs/postman-app-support/issues/8819

I'm going to close this issue out and you can follow the other thread for information.

If you have additional details not covered on the thread, please do add them.

Thanks again.
