### ISSUE TITLE
Installation has failed

### ISSUE THREAD

**Issue by Trialucifer** [a85/POSTMan-Chrome-Extension#9195]
Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\zbc\AppData\Local\Postman\packages\.betaId”的一部分。
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\zbc\AppData\Local\Postman\packages\RELEASES”的一部分。
InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: 未能找到路径“C:\Users\Postman\buildkite-agent\builds\postman-ci-agent-windows-1\postman\electron-package-and-deploy\resources\postman-prod.ico”的一部分。 ---> System.Net.WebException: 未能找到路径“C:\Users\Postman\buildkite-agent\builds\postman-ci-agent-windows-1\postman\electron-package-and-deploy\resources\postman-prod.ico”的一部分。 ---> System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\Postman\buildkite-agent\builds\postman-ci-agent-windows-1\postman\electron-package-and-deploy\resources\postman-prod.ico”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

**Comment by DannyDainton** [comment]
Hey @Trialucifer 

Can you provide more details and context about this issue, please? In its current form, we're not going to be able to do anything to help here.

---

Could you supply the following basic information:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See an error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
Add any other context about the problem here.

**Comment by DannyDainton** [comment]
Hey @Trialucifer

As there has been no response to this request for additional information, I'm going to close this issue out.

We can look to reopen it again if we receive more clarity about the issue, without that we're unable to do anything here.
