### ISSUE TITLE
Custom Objects no longer are global 7.35.0

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#9230]
**Describe the bug**
In order to do swagger validation in tests, we are importing javascript code for swagger-tools. We used to be able to load it once in pre-request for collection with eval() and use this object in collection test, however now the object is undefined when it comes to the test.
(Monitors still seem to be fine).

**To Reproduce**
1. Load/Create an object in collection Pre-Request
2. Check the type of the object in any other location
3. The object will be undefined

**Expected behavior**
If object is defined, it should be available globally.

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.35.0
 - OS: macOS Catalina 10.15.7

**Additional context**
This prevents us from updating to the newest version of Postman, as swagger validation tests are really important for us.

**Comment by codenirvana** [comment]
@VicKetchup We've made a few security fixes in our script execution sandbox, that might've affected this.
Can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by VicKetchup** [comment]
Hi @codenirvana,

Please see the attached collection
[Object not global example.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/5483009/Object.not.global.example.postman_collection.json.zip)

**Comment by VicKetchup** [comment]
Still an issue in 7.36

**Comment by countzero** [comment]
@VicKetchup: Can confirm, that this is still an issue in v7.36.0: #9319

**Comment by countzero** [comment]
**Is there a viable workaround to this bug?**

I need some support for a workaround to run my tests in postman v7.34.0.

I am assuming this takes a long while and customers out there are NOT willing to rewrite all their requests until this bug is fixed. So there should be a documented workaround in place.

Reverse engineering your download links gave me: https://dl.pstmn.io/download/version/7.34.0/win64

But the installer states, that it is not possible to install the old version since there is a more recent version.

**Question:** How can I install an older version of postman on my machine and block any updates?

**Comment by VicKetchup** [comment]
@countzero On macOS I go to 'MacHD > Users > <user> > Library > Application Support' and delete/rename Postman folder there, which unblocks the install. So just need to figure out where the Postman folder is in Windows, probably in %appdata%.

**Comment by vikiCoder** [comment]
@VicKetchup @countzero You can follow the steps mentioned here to clear the local app data and install old version: https://support.postman.com/hc/en-us/articles/360025359014. Please check out 'Clean up local files and restart the app' and ‘Resolution steps to rename your Postman folder’ sections.

**Comment by codenirvana** [comment]
@VicKetchup Sorry for the delayed response.

So the issue is, globals set in asynchronous scripts are not presented across pre-request/test scripts.
e.g, the following script in the collection's pre-request will not expose the global variable `x` in the request's test script.
```js
setTimeout(() => { x = 1; }, 100);
```

A workaround for this is to initialize the globals synchronously and update asynchronously, like:
```js
x = null;
setTimeout(() => { x = 1; }, 100);
```

As I mentioned before, this bug is introduced because of security fixes in [Postman Sandbox](https://github.com/postmanlabs/postman-sandbox), and by design, it's a little difficult to support the previous behaviour.

I know this is preventing you from upgrading to the latest version and the workaround suggested might require changes in multiple collections. So, we are actively looking for ways to fix this as soon as possible. Will keep you posted.

**Comment by VicKetchup** [comment]
@codenirvana Thanks for the suggestion for the workaround, looks like it is working with the newest version.

**Comment by VicKetchup** [comment]
@codenirvana If there is no way to support old behaviour, I think the workaround is good enough and ticket can be closed.
