### ISSUE TITLE
OAuth2 token is not getting updated in the request when selected from available tokens dropdown

### ISSUE THREAD

**Issue by pimly4x** [a85/POSTMan-Chrome-Extension#9238]
Postman update's even when the update button is turned off. The current update (Postman v7.35.0) does not send the access token when I make the request.

**Comment by auraxangelic** [comment]
I'm experiencing the same issue with the access token issue. Postman, please fix. The token does not get set when I retrieve a new OAuth2.0 token.

As for the update button, are you sure you're looking at the major version? The previous version was 7.34.0, and would not have prevented the upgrade to the buggy authentication since it's a minor version upgrade. It would only prevent an upgrade to 8.0.0.

**Comment by stakAtak** [comment]
Same here, I have an access token issue. I am really frustrated with all this Postman auto updates. I am considering to move to another tool...

**Comment by DannyDainton** [comment]
I'm going to close this out as it's all related to #9056 - just trying to keep all the conversations in 1 place.
