### ISSUE TITLE
Spaces in URLs are not trimmed

### ISSUE THREAD

**Issue by atonse** [a85/POSTMan-Chrome-Extension#9248]
**Describe the bug**
Sometimes when users paste a URL that has a space in the end, postman does not trim the URL.

**To Reproduce**
1. Create new Request (or take an existing request)
2. Paste in URL with a white space at the end
3. Perform the request
4. You should see a 404 since your target probably isn't expecting a space at the end of the URL

**Expected behavior**
This is a user-friendliness bug, where you should trim whitespaces at the end of URLs in case of a bad copy-paste

**App information (please complete the following information):**
 - App Type: Native App
 - OS: macOS Catalina

**Comment by codenirvana** [comment]
@atonse Thanks for reporting this but we do this intentionally because Postman is a debugging tool and we don’t want to mutate user input like this.

For user-friendliness, we try to highlight these trailing whitespaces.
<img width="422" alt="Screenshot 2020-11-10 at 10 52 41 AM" src="https://user-images.githubusercontent.com/4865836/98631220-f9c23480-2342-11eb-8d2b-6581be752b2e.png">

Maybe we can add a request setting to automatically trim whitespace from the URL.
