### ISSUE TITLE
CookieStore: programmatic access to "127.0.0.1" is denied

### ISSUE THREAD

**Issue by flleeppyy** [a85/POSTMan-Chrome-Extension#9253]
**Describe the bug**
Following [this](https://learning.postman.com/docs/sending-requests/cookies/#creating-a-cookie-jar) tutorial, but I cannot set cookies on 127.0.0.1, or 0.0.0.0

**To Reproduce**

1. Create a new request that is going towards localhost, 127.0.0.1 or 0.0.0.0
2. Go to pre-request scripts
3. Insert something like the following from the above linked tutorial
```js
const CookieJar = pm.cookies.jar()
CookieJar.set('127.0.0.1', 'authorization', 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJ1c2VybmFtZSI6ImNpcm5vIiwiZW1haWwiOiJjaXJub0BjaXJub3N5c3RlbXMueHl6IiwicGVybWlzc2lvbnMiOiJBTEwiLCJkaXNhYmxlZCI6MCwiZGV2b25seSI6MX0sImlhdCI6MTYwNDgyNjQ1MSwiZXhwIjoxNjA3NDE4NDUxfQ', (err, cookie) => { // fyi the token is useless, its just for development for my stuff
    if (err) {
        console.error(err)
    }
     console.log(cookie)
})
```
```
{type: "Error", name: "Error", message: "CookieStore: programmatic access to "127.0.0.1" is denied"}
type: "Error"
name: "Error"
message: "CookieStore: programmatic access to "127.0.0.1" is denied"
```
**Expected behavior**
I expected it to set the cookie, but it did not, and returned with an error instead.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
Postman for Windows
Version 7.34.0
win32 10.0.18363 / x64

**Comment by DannyDainton** [comment]
Hey @flleeppyy 

In order to get programmatic access the cookie jar, you would need to add the domain to the list inside the `Manage Cookies` section. 

![image](https://user-images.githubusercontent.com/17089546/98537733-9e7c3d80-2281-11eb-9771-348c0f11185d.png)

![image](https://user-images.githubusercontent.com/17089546/98537771-adfb8680-2281-11eb-8d2a-7135783ec816.png)

More information can be found here:
https://learning.postman.com/docs/sending-requests/cookies/#whitelisting-domains-for-programmatic-access-of-cookies

**Comment by flleeppyy** [comment]
Ahhh, okay. Thanks

**Comment by darkomenx** [comment]
For me, this do nothing : 

![Image](https://github.com/user-attachments/assets/9f5ca1ad-85fe-470a-be39-1f148b381a88)

**Comment by MatrixRave** [comment]
Just whitelisting adresses or cookies doesn't seem to work anymore
