### ISSUE TITLE
Feature request: export and import member lists for workspaces

### ISSUE THREAD

**Issue by maydaymarina** [a85/POSTMan-Chrome-Extension#9256]
I need to add the same set of users to multiple workspaces. It would be good to be able to export members list from one workspace, and import it into another workspace.

**Comment by akshay-kulkarni-03** [comment]
Hi @maydaymarina , exporting of members from a workspace cause security issues since their personal data can be exported and shared across different mediums over which we don't have control over. 
Alternatively, you can use our postman APIs to do this programmatically update roles for a specific workspace: https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-133e2d90-ce1f-4309-ac77-0635bbc24696
