### ISSUE TITLE
Postman Agent icon showing in panel, but can't able to open the app

### ISSUE THREAD

**Issue by nasr18** [a85/POSTMan-Chrome-Extension#9322]
I installed latest version of Postman Agent v0.2.4 in linux mint 20 and I'm facing the same issue. Postman icon showing in panel, but can't able to open the app.

![image](https://user-images.githubusercontent.com/7514936/100263013-f77eed80-2f72-11eb-9ade-d631c9565954.png)

_Originally posted by @nasr18 in https://github.com/postmanlabs/postman-app-support/issues/5514#issuecomment-733851378_

**Comment by vvs11** [comment]
@nasr18 It could be the desktop agent. You'll have to open postman on web and try sending the request. Alternatively, you can download Postman app.

**Comment by DannyDainton** [comment]
Hey @nasr18 

The Postman Agent (the one you see in the toolbar) enables request sending in our web platform. This is needed due to CORS limitations.

Head over to https://go.postman.co/build to use this Agent and see our brand new UI ❤️ 

What is it that you're trying to do - Just use the native app or the Web version?

**Comment by nasr18** [comment]
@vvs11 @DannyDainton thank you so much for the fast reply. I'm really sorry for raising an issue. Its my bad. I wrongly installed Postman Agent. Now I installed Postman app and its working fine.
