### ISSUE TITLE
[Feature Request] Add a "Share Link" action for Public Workspaces

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#9353]
**Is your feature request related to a problem? Please describe.**
It's not always clear that the best (only?) way to share a public workspace URL is to grab the address that's in the browser's URL bar.

**Describe the solution you'd like**
It would be great to see a "Share Public Workspace" action in the Sharing section of a public workspace

**Additional context**
![image](https://user-images.githubusercontent.com/4734306/101535696-a56c9d80-395e-11eb-8f5d-fde06e1cd4bc.png)

**Comment by akshay-kulkarni-03** [comment]
Hi @chrisdeso , we recently enhanced our existing sharing feature through which you will now be able to share workspaces via a copy invite link. For more details on sharing you can visit our learning center doc [here](https://learning.postman.com/docs/collaborating-in-postman/sharing/). In order to use this you need to be on the latest version of postman app. 

Feel free to open the issue again if you face any problem with sharing.
