### ISSUE TITLE
Oauth2 Postman browser Callback URL is not working as expected

### ISSUE THREAD

**Issue by ActuallySPH** [a85/POSTMan-Chrome-Extension#9390]
**Describe the Issue**

> In our API automation script, we are generating the Oauth2 token using the postman call back URL (https://app.getpostman.com/oauth2/callback). 
This call back URL was working fine until Dec 22nd. 

> We started to observe this error message recently “Could not make access token requests. The feature has been deprecated, please download the latest Postman app.”

> Looks like the postman call back URL(https://app.getpostman.com/oauth2/callback) is not working. We have also tried with the postman Call back URL(https://oauth.pstmn.io/v1/callback) but no luck. 

> Redirected to this URL: https://fhbjgbiflinjbdggehcddcbncdddomop.chromiumapp.org/oauth2-request?result=failure&message=Could+not+make+access+token+requests.The+feature+has+been+deprecated,please+download+the+latest+Postman+app

**Screenshots or Videos**

>  https://www.screencast.com/t/k13Z73csdKE0

**Comment by PhilGood1989** [comment]
I can also reproduce this behaviour. It was working until recently

**Comment by tominaus** [comment]
Same issue here

**Comment by tophil** [comment]
This is also happening for us. In Postman, we are seeing a 503 status code for these calls now. Error shown is:
Error: tunneling socket could not be established, statusCode=503

**Comment by adarshkr** [comment]
Any workaround available for callback url?

**Comment by PhilGood1989** [comment]
For me **https://www.example.com/oidc_callback** works as redirect URL

**Comment by DjSt3rios** [comment]
Same issue here :-(

**Comment by tominaus** [comment]
I have got it running now in the app. With a different URL. This won't work in the web version you have to use a different URL  You are going to have to bear with me and I might sound like a dummy hear as I have only been doing this for a few weeks. But this is what I did 

I have 4 APIs some were working on the web app and some were working on the desktop app it was a pain so to get them all working on the desktop app as I cant get one working because of a new SSL issue that postman has now with ssl1 and 1.1. So the Desktop was my choice in the end.  You will have to change the callback settings to these URLs or it won't work and change your callback variation as well but these both work.

•	Desktop app - https://oauth.pstmn.io/v1/callback

•	Web app - https://oauth.pstmn.io/v1/browser-callback

Final note this is what Postman is telling me

The callback URL https://www.postman.com/oauth2/callback used to provide functionality for requesting OAuth2 toke at server-side and send it back to the deprecated Postman chrome app. Now that the Postman chrome app is deprecated and that functionality is not needed anymore in the native/desktop app, we have decided to deprecate the URL as well.

Right now, we don’t have any other endpoint that can get the OAuth2 token at the server-side on the behalf of the client and return it. Now we enable Postman users to provide any custom redirect URL and request the token locally from the app. However, if you need a URL that simply works as a redirect URL, then you can use the one below depending on the Postman version you’re using. 

I hope this helps it help me and I am a beginner 

Cheers

**Comment by tophil** [comment]
I was able to get it to work by turning on Capture requests using Postman's built-in proxy. Then under Settings -> Proxy, instead of using the system proxy, use a custom proxy that's pointed at localhohst:5555.
I still see a DNS lookup failure because it's still looking for fhbjgbiflinjbdggehcddcbncdddomop.chromiumapp.org, but I still get a valid token back.

**Comment by celsooliveiraTBDE** [comment]
updating the URL did the trick.  thanks @tominaus

**Comment by savageCoder55** [comment]
As mentioned by @tominaus the older callback url at https://www.postman.com/oauth2/callback has been deprecated.
If you'd like to get this working, please upgrade to the latest version of the Postman desktop app.

In case you're unable to upgrade, please change the callback urls to the following:
- If you're using the desktop app use - https://oauth.pstmn.io/v1/callback
- If you're using the web app use - https://oauth.pstmn.io/v1/browser-callback

This will help you resolve this issue.
Thanks

**Comment by raghuramratan** [comment]
Both Desktop and Web App redirect Url's are not working for me

**Comment by mikhailkaushovik** [comment]
Updating the Redirect URL to https://oauth.pstmn.io/v1/browser-callback for web app did a trick. Thanks

**Comment by sagarpise** [comment]
![image](https://user-images.githubusercontent.com/10513971/131501601-73c78590-de4f-450d-b742-51070742d729.png)

In the ubuntu postman desktop version,  after attempting multiple times finally I am able to manage authenticated by **unchecking authorize using browser** and manually added callback url to **`https://oauth.pstmn.io/v1/callback`**.

**Comment by NirajCricket** [comment]
setting the uri in oauth consent worked for me

**Comment by denven** [comment]
I find the latest postman v10.3+ supports the full OAuth2 token fetch flow ( I tested the Authorization Code grant flow), it works perfectly.
![image](https://user-images.githubusercontent.com/16745984/204077778-1469b8f2-7043-4113-910d-e1012616bbd0.png)

**Comment by denven** [comment]
If anyone just needs a callback URL to get the authorization code during your project **development state**, you can use this link https://openoauth2callback.eastus.cloudapp.azure.com/callback as your Redirect URL and put your code authorize full link into the browser, to get it by a click of the copy button. The callback URL is provided by the simple nodejs application, repo: [oauthopencallback](https://github.com/denven/oauthopencallback)

![image](https://user-images.githubusercontent.com/16745984/204078480-c375fbd1-385d-47dd-b785-37759ff2da45.png)

**Comment by gsingh0101** [comment]
> turning on Capture requests using Postman's built-in proxy

This works but you can also simply use the Dev Console of chrome
