### ISSUE TITLE
Unable to remove null from Workspace error on removing a collection from Teams Workspace

### ISSUE THREAD

**Issue by dmoryani** [a85/POSTMan-Chrome-Extension#9419]
1. Try to remove a collection from teams workspace. Right click on Collection - "Remove from Workspace" option. 
2. 
![image](https://user-images.githubusercontent.com/31031890/104298105-90a39c80-54fe-11eb-8359-c7e07d1d787f.png)

Environment:
![image](https://user-images.githubusercontent.com/31031890/104298147-9b5e3180-54fe-11eb-87bd-0a476127d69c.png)

**Comment by DannyDainton** [comment]
Hey @dmoryani 

Thanks for flagging this problem - We have investigated this on our side and have found where the copy of the message can be improved - The inability to remove the entity from the workspace is likely due to the socket connection/syncing not being active. 

Quitting the application and restarting again should reestablish the connection.

**Comment by DannyDainton** [comment]
Hey @dmoryani - Is this still causing you an issue?

**Comment by DannyDainton** [comment]
Closing this issue as we have had no further response about the connection issue - If you're still unable to remove the collection from the Workspace in the latest version, we can open this up again.

**Comment by dmoryani** [comment]
Hi Team,

Not facing this issue anymore.
Thank you for the support.

Thanks,
Divya
