### ISSUE TITLE
Certificates not adding correctly

### ISSUE THREAD

**Issue by andrewwardell** [a85/POSTMan-Chrome-Extension#9443]
Recently, when I attempt to add a certificate, it is showing up differently than prior certificate additions, and I get a "proper client ssl certificate was not presented" error when I try to use it.

I have 4 domains that use the exact same certificate/key pair.  These all worked fine until recently.  I recently removed the certificate for the 4th domain as part of testing, and when I re-add it, the issue appears:
![image](https://user-images.githubusercontent.com/77742696/105204095-d7525180-5b11-11eb-97f5-7d9dd37f3191.png)

Note that what are backslashes ('\') in the 3 working domains are now forward slashes ('/'), and a forward slash is prepended to the path for the cert.   This has occurred before, and we had to revert to Postman v6.7.4 in order to use certificates until a newer version fixed the issue.

Is there any way to manually set the certificate paths, bypassing the dialog?  older versions of postman allowed a manual path, the current version does not.

**Comment by postman-staff** [comment]
Hey @andrewwardell 👋 - May I request you to check under the Postman Console log to verify if the right client certificates are being sent?

You can access the Postman console by clicking on the icon located at the bottom left in the Postman app:
​ ![](https://postman.zendesk.com/attachments/token/9A8vLiygAc5pPHao0yClyEW1J/?name=Screen+Shot+2021-01-21+at+2.40.53+PM.png)​

Alternatively, from the Postman app's menu navigate to `View > Show Postman Console` to open the Console in a new window

In the console tab/window - expand the request you want to verify and then expand the "`Client Certificate`" section and see if the right certificate was sent.
​ ![](https://postman.zendesk.com/attachments/token/MXpWb5Sjz2InSQMZtMkEXIcx6/?name=Screen+Shot+2021-01-21+at+2.44.15+PM.png)​

If right certificates are being sent, the issue lies on the server-side, if not - this would signify a likely issue with the Postman app.


via @xk0der | Postman Support

**Comment by andrewwardell** [comment]
The error is in the Console is “Error: proper client ssl certificate was not presented”.  These are known good certificates, and worked before I removed/readded.  I can use the same certificate in another environment (where I didn’t do the remove/re-add) without issue.

I believe that Postman is not sending the certificate at all.  This seemed to be the case the last time this issue showed up.

Regards,
[cid:image001.gif@01D6EFD0.D26133F0]<https://www.adp.com/>
Andrew Wardell
NAS Tech Support Advisor
NAS - Field Support Services

99 Jefferson Road, Parsippany, NJ 07054
T: 973 974 6181   C: 781 548 1374

andrew.wardell@adp.com
[cid:image002.gif@01D6EFD0.D26133F0]<https://www.linkedin.com/company/adp>[cid:image003.gif@01D6EFD0.D26133F0]<https://twitter.com/ADP>[cid:image004.gif@01D6EFD0.D26133F0]<https://www.facebook.com/AutomaticDataProcessing>[cid:image005.gif@01D6EFD0.D26133F0]<https://www.youtube.com/user/adp>
Emails will be reviewed within 24 hours of receipt on a regularly scheduled work day.
Please see Office Hours and Upcoming Out of Office Dates below to verify availability.

Office Hours (all times EST/EDT):
Monday through Friday, 8:30am to 5:00pm
Upcoming Out of Office Dates

**Comment by andrewwardell** [comment]
This seems to have spontaneously corrected itself.  I appreciate the time/effort, but I think we can close this.

Regards,
[cid:image001.gif@01D6EFD7.DF481AA0]<https://www.adp.com/>
Andrew Wardell
NAS Tech Support Advisor
NAS - Field Support Services

99 Jefferson Road, Parsippany, NJ 07054
T: 973 974 6181   C: 781 548 1374

andrew.wardell@adp.com
[cid:image002.gif@01D6EFD7.DF481AA0]<https://www.linkedin.com/company/adp>[cid:image003.gif@01D6EFD7.DF481AA0]<https://twitter.com/ADP>[cid:image004.gif@01D6EFD7.DF481AA0]<https://www.facebook.com/AutomaticDataProcessing>[cid:image005.gif@01D6EFD7.DF481AA0]<https://www.youtube.com/user/adp>
Emails will be reviewed within 24 hours of receipt on a regularly scheduled work day.
Please see Office Hours and Upcoming Out of Office Dates below to verify availability.

Office Hours (all times EST/EDT):
Monday through Friday, 8:30am to 5:00pm
Upcoming Out of Office Dates

**Comment by postman-staff** [comment]
@andrewwardell great to hear that the issue is now resolved for you! I appreciate you letting us know.

Do not hesitate to reach out to us in the future!


via @xk0der | Postman Support
