### ISSUE TITLE
Monitoring: Error occured while fetching versions

### ISSUE THREAD

**Issue by akbbhatt** [a85/POSTMan-Chrome-Extension#9444]
If I try to create a monitor  on my  collection then I get this error: "Error occured while fetching versions"

my postman version is:  Postman v7.36.1 

ps: There is also a typo in the error message, please fix that as well.

**Comment by postman-staff** [comment]
Thanks for pointing out the typo in the error message.

By default, Postman Monitors access APIs from dynamic IP addresses and it seems you're trying to access the APIs behind a restricted firewall. Would you please confirm if this is not the case?

via @ | Postman Support

**Comment by xk0der** [comment]
Hey @akbbhatt checking to see if you are still getting the error when trying to create a monitor? If yes, do create a ticket here: https://www.postman.com/support/ and provide the following details, so that we can troubleshoot this further:

- Collection name and UUID - You can find this from the web-app: https://go.postman.co/build and open the Collection and copy the URL
- Postman app logs https://learning.postman.com/docs/getting-started/troubleshooting-inapp/ 

Also, check to see if you continue to face the issue with the Postman-web app and Postman native app v8: https://postman.com/downloads

**Comment by DannyDainton** [comment]
@xk0der

Was this issue resolved in the end? Are we able to close this out?

**Comment by xk0der** [comment]
We didn't get further information to be able to troubleshoot this. Closing next!

@akbbhatt feel free to log a new issue with the requested information if you face this issue again. 👍

**Comment by postman-staff** [comment]
Typo on the error message "occured" instead of "occurred" has been fixed

via @labifrancis | Postman Support
