### ISSUE TITLE
DNS Lookup really long on localhost

### ISSUE THREAD

**Issue by Ragnar-Oock** [a85/POSTMan-Chrome-Extension#9466]
**Describe the Issue**

When sending a request to localhost:8080 the DNS lookup time is always around 500-550ms, even repeating the request does not trigger the use of the DNS cache and the DNS lookup keeps stagnating around 500ms. Using 127.0.0.1:8080 as a host work around the issue.
> might be related to #3882 

**Steps to Reproduce**

1. send a request to a localhost webserver with `localhost:[some port]` as base url
2. log DNS lookup time
3. send a second request to the localhost webserver with `localhost:[some port]` as base url
4. log DNS lookup time
5. send a request with `127.0.0.1:[some port]` as base url
6. log DNS lookup time
7. the first 2 results are significantly higher than the last one even after the first request

**Screenshots or Videos**

> request with 127.0.0.1 :
![postman issue screen shot 127 0 0 1 1](https://user-images.githubusercontent.com/38219333/105883974-bf923600-6007-11eb-881d-65936b7e8b34.png)

> first request with localhost :
![postman issue screen shot localhost 1](https://user-images.githubusercontent.com/38219333/105883978-c02acc80-6007-11eb-9903-80853b6d147d.png)

> second request with localhost :
![postman issue screen shot localhost 2](https://user-images.githubusercontent.com/38219333/105883981-c02acc80-6007-11eb-8645-6f4f6b6e5cf0.png)

**Environment Information**

 - Platform Type: Native windows app
 - Postman Version: 8.0.2
 - Operating System: windows 10 x64

**Comment by sandeep-singh-pstmn** [comment]
In Postman we cached the DNS that's why it's showing cached in 127.0.0.1:3000 (https://community.postman.com/t/postman-response-time-vs-curl-response-time/4882/2)

<img width="1026" alt="Screenshot 2023-06-16 at 12 28 11 PM" src="https://github.com/postmanlabs/postman-app-support/assets/85243040/5a1050dc-a858-4c21-97ce-656e42221b1b">

<img width="1026" alt="Screenshot 2023-06-16 at 12 29 13 PM" src="https://github.com/postmanlabs/postman-app-support/assets/85243040/d81f35b3-b577-4920-875d-0c0377a477e3">

for me, the DNS lookup time for localhost:3000 is 0.17 ms 

@Ragnar-Oock  can you please confirm that still, the DNS lookup for you is 400+ ms if yes can you please provide the server details?

**Comment by sandeep-singh-pstmn** [comment]
@Ragnar-Oock closing this issue for the time being. If the issue arises again, feel free to reopen it.

**Comment by dream7prod** [comment]
Hello,

I experience very slow DNS Lookup time when using custom local domain (api.localhost.local) : about 5 seconds, and 9ms when using 127.0.0.1. I need to use local sub-domain for my testings...

Is there a way to force DNS cache ?

Thank you :)

@sandeep-singh-pstmn

![Capture d’écran 2024-03-31 à 19 09 13](https://github.com/postmanlabs/postman-app-support/assets/48924192/03cb03c2-4c74-46f6-82a4-51f72ebc10a9)
![Capture d’écran 2024-03-31 à 19 09 53](https://github.com/postmanlabs/postman-app-support/assets/48924192/11354652-8761-48b3-a42e-8943d8a2603b)
