### ISSUE TITLE
Connection Error to sync data with your servers... account based

### ISSUE THREAD

**Issue by Rab815** [a85/POSTMan-Chrome-Extension#9487]
**Describe the Issue**

> I've had a gmail account that I've been using for years to sign into postman... however upon going to version 8 when I sign in using that account I get a websocket connection error at the top of postman.  I created a new gmail account and sign in with that and the connection error goes away and I'm able to back up my data.

**Steps to Reproduce**

> A list of steps that can be followed to recreate the issue.

**Screenshots or Videos**
original gmail account sign in
![2021-01-28_8-44-27](https://user-images.githubusercontent.com/6784505/106158197-1e12fd80-6149-11eb-93ec-150174aeddef.png)

new gmail account sign in...
![2021-01-28_9-14-39](https://user-images.githubusercontent.com/6784505/106158393-4bf84200-6149-11eb-8c39-dc26d297fbd8.png)

**Environment Information**

 - Native desktop app
 - Postman Version: 8.0.3
 - Operating System: windows 10

Other than the account sign in there are no differences in settings

**Comment by DannyDainton** [comment]
Hey @Rab815 

Would it be possible to quit the app completely, sign in with your previous email and if your problem still occurs - send over the logs to help@postman.com so we can take a look at what's going on, please?

You can find the logs at View -> Developer -> View logs in Finder/Explorer.

Feel free to reference the GH Issue number in the subject line of the email.

Are you able to login to the web version (http://go.postman.co/) with your old email details?

**Comment by Rab815** [comment]
will do sending over every log that has todays date on it now.

yes I can go to http://go.postman.co/ and log in with my old email details fine, the web based client seems to be ok but I need the desktop version

web based version with my old user profile, you can see the successful connection icon in the upper bar.
![2021-01-28_9-30-05](https://user-images.githubusercontent.com/6784505/106160504-84991b00-614b-11eb-8fc2-91acc0ee5843.png)

**Comment by epopisces** [comment]
I am having the same (or very similar) issue. Had a working login on version 7.  Was about to demo the product to some new team members, realized they were downloading the new version and did likewise.  In version 8 got that same error.  Tried logging out, and then back in again with the same account, but it didn't resolve the issue.

Wondering if the new Postman desktop client is using a different protocol to connect to the backend servers, and our firewall is blocking it perhaps?  We don't use proxies, just a content-inspection firewall.  Is the client now using the QUIC protocol, perhaps?  Many companies block that protocol because it can't be inspected.

We do also use a VPN, though I don't believe that would have any impact on this vs another connection method.

(leaving the above for historical context)
It isn't the firewalls, it appears bound to the account: the same issue occurs outside of the corporate network/VPN; the issue follows the account, not the device or network environment.

**Comment by Rab815** [comment]
I put it on a personal machine connecting through my phone. So i wasn’t
even going through my router. Same problem.

**Comment by NateJSchmidt** [comment]
I'm also having this problem.  I'm not sure if this is a weird side effect or not, but all of my local collections were gone as well (and I don't think they are recoverable since I had not sync'ed them).

Thinking that something maybe got corrupted in the upgrade to v8.0.3, I completely uninstalled Postman (including deleting both the AppData\Local\Postman and AppData\Roaming\Postman directories.  I then reinstalled v8.0.3 and experienced the same problem (with the same error message as @Rab815).

In addition, any local changes I make w.r.t. creating collections/folders/requests are deleted after I close the program.  I'll send my logs over as well and reference this Issue number.

**Comment by DannyDainton** [comment]
@NateJSchmidt 

Were your old collections etc in the scratch pad view?

You can get to this via `Settings > Scratch pad`

**Comment by alem5001** [comment]
Same problem here. After the update to 8.0.3 all collections in my workspace are gone (scratchpad included).
I'm on Mac, logged in with my account just as before, no proxy needed: icon says Connection error (establishing websocket).
It seems in the postman work dir there is still what appears to be a json export backup from last month: I hope at the very least to be able to reimport this one. Frankly as a software developer, I can't think of a more catastrophic bug than this. Guess no more  updates for me.

**Comment by DannyDainton** [comment]
If you have experienced the issue and you haven't done so already, please send all of the log files to help@postman.com. 

It will help us to investigate the root cause of the problem. 

You can find the logs at `View -> Developer -> View logs in Finder/Explorer.`

Similar issues have been raised on the repository and to try and keep the flow of information in a central place, I'm going to close this issue and kindly ask that you follow the thread, on the issue below, for more information. 

https://github.com/postmanlabs/postman-app-support/issues/9481

**Comment by NateJSchmidt** [comment]
@DannyDainton
Sorry to pull you back to this closed thread, but I figured this was for my specific case and isn't really relevant to the larger discussion.  I did have a look in `Settings -> Scratch pad`, but I didn't see anything.  I suspect I blew everything away when I did my clean install and the Scratchpad space might still be helpful for other developers to recover their lost collections.

FWIW, I did realize I was giving up any hope of recovering my collections when I did the clean installation.  I made this conscious decision because I truthfully only had 4-5 requests saved at the time.

**Comment by natan88** [comment]
I'm using version 8.5.1 on elementary os, I just migrated from windows 10. Both operating systems have the same problem reported here.

**Comment by amnporter** [comment]
Same as everyone above, web works fine BUT app doesn't sync. On mac Catalina, Postman app Version 8.7.0 (8.7.0)

**Comment by natan88** [comment]
I created another user account. With this new account everything worked fine.

**Comment by amnporter** [comment]
I also deleted and re-created my acct which seemed to fix things. I believe it may have had to do with logging in via google.

**Comment by dirablue** [comment]
> I also deleted and re-created my acct which seemed to fix things. I believe it may have had to do with logging in via google.

thank you so much. it works for me.

**Comment by ivanbogomoloff** [comment]
Hello all. I have same problem today.
I fixed this by sign out in desktop app and then i changed password in my acct and then login in desktop app and it works. 
I hope that problem is seldom thing , otherwise i will plan to migrate

**Comment by ryemyer** [comment]
> Hello all. I have same problem today.
> I fixed this by sign out in desktop app and then i changed password in my acct and then login in desktop app and it works.
> I hope that problem is seldom thing , otherwise i will plan to migrate

Worked for me!

**Comment by Stirda** [comment]
I just logged in to the web app then restarted the desktop app.

**Comment by fionnachan** [comment]
Had the same problem. I signed up using my Google account. Can't even change password because I didn't have a password to begin with so I had to delete the account and create a new one from scratch (not using Google account). Now the websocket connection on the desktop app works again.

Btw after deleting the account, the public name doesn't completely go away with it so when I created a new account I cannot use the same public name again.

Please fix these bugs :(

**Comment by NikitaKosolapov** [comment]
DesktopApp:

Sing out -> Sign in (via browser)

Works for me

**Comment by aibmakesense** [comment]
I face same problem.

**Comment by n1xan** [comment]
Having same issue on the desktop app. Completely unusable. I signed up using google account.

**Comment by Betristor** [comment]
I logged out firstly and then signed in again and it worked. It might be because I've changed my profiles before.

**Comment by iganev0886** [comment]
I changed the password, and it worked. I'll probably move out of Postman. How is this acceptable?

**Comment by jeffschuler** [comment]
Logging out from desktop app and changing password did not work for me, nor removing all local app data/preference files (on Mac). Deleting my Postman account and signing up again worked.

**Comment by NemishShah** [comment]
I created a new account --> That _**worked**_

But I wanted to have the access fixed for my old account 

I tried to change password --> Did not work
I cleared the cache and also did a full reinstall. --> did not work.
I tried to launch Postman in the browser (web). There it works. --> https://support.postman.com/hc/en-us/articles/360025359014-Troubleshooting-steps-for-Postman-desktop-issues
I then followed the following steps to collect logs --> https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs-

Finally, the postman support team found the root cause. 

**_It looks like sync is disabled for your account. For context, earlier versions of Postman allowed for an option to disable sync, and later on, this option was removed. Unfortunately, we cannot automatically enable sync due to privacy/legal reasons. If you can write back to me saying you are okay with the Sync being enabled for your account, I will quickly go ahead and enable it for you._**
