### ISSUE TITLE
Disable Working locally in Scratch pad warning

### ISSUE THREAD

**Issue by bjpayne** [a85/POSTMan-Chrome-Extension#9488]
**Describe the solution you'd like**
Add ability to toggle the warning to off for users who don't want to create an account.

![image](https://user-images.githubusercontent.com/8144159/106162727-6ab10580-6156-11eb-8909-292e00b29c5e.png)

**Comment by ManiacDC** [comment]
Somewhat related to #9472

**Comment by sylveon** [comment]
This please! I don't see why what amounts to me as a glorified curl needs an account to the point of pestering me each time I boot it up.

**Comment by KWottrich** [comment]
My organization does not allow the use of workspaces with Postman, so I'm stuck being warned about this every time I open Postman.  Please either add an option or only warn me once!

**Comment by franz-at-dns** [comment]
100% agreed.
it's completely okay to inform about your more advanced features - but please don't annoy us with it all the time. if i didn't want it the first time, i won't want it the 42nd time.

**Comment by ghost** [comment]
I appreciate the feature but when building labs for training, it's a bit of an annoyance. Ability to disable would be great.

**Comment by HenningLanghorst** [comment]
I use Postman at work and do want to put potentially sensitive data into the cloud. Hence, I would appreciate if the warning could be disabled permanently.

**Comment by jeremysmitherman** [comment]
I simply don't want to create an account.  This warning should be permanently dismissable

**Comment by Kupie** [comment]
Leaving this in as-is would be a ridiculous thing. Surely it wouldn't come back on startup every time, would it?

Oh wait

**Comment by gorkhadk** [comment]
If there should be a warning it should be when you use the workspace and freely give your data to some 3rd party in the cloud you almost certainly cannot trust.
Please dont warn about something that is as it should be.
Warning: you are alive ...

**Comment by blackr1234** [comment]
## Hey, after several `8.x` and `8.x.x` updates (now I'm on `8.7.0`) I still can't disable it permanently

## May I know how hard it is to add a setting for disabling it PERMANENTLY?

## I recall that the first version that came with this banner didn't even have the close (`✕`) button

## Please be user-centric

## If you want us to pay, please show some other text, ok?

**Comment by Sascha-69** [comment]
There are several reasons to avoid storing data or code in the cloud. Please respect and support users' choices.

**Comment by franz-at-dns** [comment]
is there any progress on this?
i mean: implementing it should be trivial.
and not implementing this is a design choice that's basically a big, fat middle finger to you user base.

**Comment by Vadigor** [comment]
This banner and the overall pushiness around accounts has me looking for alternatives.

Here's the deal: I am **never** going to upload my corporate interface tests to some random cloud provider. Who on earth in their right mind would? This data is about as critical as it gets and it has me worried the tool could be insecure even while I'm logged out and have disabled usage data. 

Surely this is an almost existential risk?

**Comment by 3omar-mostafa** [comment]
Hey there if you are interested, I've created a node app to patch Postman to remove this banner
Manual patching method is also included in the Readme if you are intersted about the methodology

You can have a look [Postman-Scratchpad-Banner-Fix](https://github.com/3omar-mostafa/Postman-Scratchpad-Banner-Fix)
I hope this can help you

**Comment by CalamityLorenzo** [comment]
Ignoring all the privacy concerns.
The banner constantly appearing is obnoxious.

**Comment by tomikmar** [comment]
It is really annoying :(

**Comment by xaamt** [comment]
> It is really annoying :(

like a sharp pencil in the a s s.

**Comment by dmaltsiniotis** [comment]
> Ignoring all the privacy concerns. The banner constantly appearing is obnoxious.

It very much is.

I wouldn't even mind if it showed up after every update/install, but stayed dismissed after that. It _feels_ disingenuous, like an intentional push toward a paid subscription under the guise of "You need an account to continue exploring Postman", even if that's not the intent.

**Comment by franz-at-dns** [comment]
just a little reminder that in 2022, this is still _fiendishly annoying,_

**Comment by johnnybenson** [comment]
Focusing Postman around the paid service (accounts, cloud hosted config) was a product decision made by non-engineers. This banner will never go away. But maybe the company will. 🥴

**Comment by myViseu** [comment]
In a secure working environment without access to internet is completely impossible to connect to my workspace.
Also is completely impossible to work with Postman with this annoying banner.
Please remove it!

**Comment by SynapseScribe** [comment]
any updates?

**Comment by Eugeny** [comment]
Postman is a VC racehorse, they care about the workspace signup numbers, not your convenience.

**Comment by Kupie** [comment]
Guess I'm using an alternative, Postman is a bloated piece of crap now

**Comment by SynapseScribe** [comment]
> Guess I'm using an alternative, Postman is a bloated piece of crap now

Other than Insomnia, which one?

**Comment by Kupie** [comment]
Insomnia's pretty good. It's like what Postman wanted to do before they sold out

**Comment by textpain** [comment]
Postman has SHOW_BANNER_IN_SCRATCHPAD flag in the code. They just want you to use workspaces. @3omar-mostafa's solution works

**Comment by textpain** [comment]
By the way, for me the persistence of this banner is a part of the reason I don't want to give you my data.

**Comment by SynapseScribe** [comment]
me too, i block all the enpoints. All this mishmash is so counter open source principles. Feel free to remove my comment, if this company has such low standards. This app starts to look more and more like spyware.

# Postman
0.0.0.0 config.getpostman.com
0.0.0.0 sync-v4.getpostman.com
0.0.0.0 sentry-app.postmanlabs.com
0.0.0.0 go.pstmn.io
0.0.0.0 bifrost-public-v4.gw.postman.com
0.0.0.0 bifrost-https-v4.gw.postman.com
0.0.0.0 bifrost-v4.getpostman.com
0.0.0.0 bifrost-v10.getpostman.com
0.0.0.0 skills-assets.pstmn.io
0.0.0.0 identity.postman.com
0.0.0.0 st-ar.cdn.postman.com
0.0.0.0 analytics.getpostman.com
0.0.0.0 dl.pstmn.io # blocks updates, might freeze temporarily the top toolbar because of timeout

# 3rd party - LAUNCHDARKLY. REF: https://docs.launchdarkly.com/guides/account/user-data/
0.0.0.0 events.launchdarkly.com # analytics API
0.0.0.0 clientstream.launchdarkly.com # streaming API [optional, might break features]
0.0.0.0 app.launchdarkly.com # feature flag API [optional, might break features]

0.0.0.0 o1224273.ingest.sentry.io # sentry.io

**Comment by textpain** [comment]
@fusionneur this is immensely helpful. Thank you

**Comment by SynapseScribe** [comment]
banner seems to be gone on 10.12.13 (not sure if it is missing since some previous versions). Can some1 confirm?

**Comment by dmaltsiniotis** [comment]
@fusionneur I noticed a few weeks ago with the last update that the banner did not appear when the app launched after install, but I was pessimistically waiting for some time and usage before coming here and reporting that the banner seemed to be gone in case it popped back up again.

**Comment by preethammavin** [comment]
We have deprecated the scratchpad with the release of V10.14; you can read more about it [here](https://blog.postman.com/announcing-new-lightweight-postman-api-client/).

We recommend using Workspaces for better organization of your requests using Collections. Workspaces also give you the ability to collaborate with your teammates. If you are not able to use or need help in moving to Postman workspaces drop us an email at [migrate@postman.com](mailto:migrate@postman.com)

**Comment by sylveon** [comment]
Does the replacement lightweight API client support working offline/locally without ever uploading data (which could be sensitive) to postman's servers?

**Comment by franz-at-dns** [comment]
@preethammavin so your solution is to just remove the offline functionality and force users to go into the cloud, even though there is absolutely _no_ technical reason for doing so?

why - so you can gather and sell more data? so you can just pull a switcheroo and force subscriptions onto us? or just because your marketing department says "cloud is cool, everything must be in the cloud"?

postman was great before you started moving it into the cloud. but with the scratchpad being deprecated, it'll basically become useless for me.

**Comment by SynapseScribe** [comment]
The good news from the blog, worth mentioning:
"For users currently using the Scratch Pad mode, it will continue working in deprecated mode until September 15, 2023"

This is enough time to migrate to alternatives and stop using Postman all together. The business decision is a direct attack to their open source community and to all their users privacy. Just throwing in words like AI and cloud isn't a reason why basic features of this app shouldn't work offline... what about closed systems where you interact with APIs internally, what about new users just trying the app, what about privacy advocates and what about enterprise where due to securities policies the app shouldn't reach Internet? 

I really hope someone realizes what a bad decision this is and stop this fuckery in the making and implicitly the beginning of the end for this once great tool.

**Comment by BrandonDusseau** [comment]
As a result of the decision to deprecate and remove scratchpad, I will discontinue my use of Postman and use an alternative like Insomnia, even if it doesn't have feature parity. I can't use a tool that is now built with a focus on profit over the user experience.

**Comment by bjpayne** [comment]
@preethammavin - I would highly encourage the team to revisit deprecating the scratch pad. Some users will never want to put their data in a cloud based solution while others may need to stop using Postman until it has gone through a vendor management process etc. Having the ability to work with Postman only locally seems like a pretty basic feature.

**Comment by preethammavin** [comment]
Hey, @sylveon the lightweight API client stores the history and requests locally and does not send the data to our servers. 

You can read about why we had to take the decision to discontinue the scratchpad [here](https://blog.postman.com/announcing-new-lightweight-postman-api-client/). If you have any concerns on using our cloud offering both free and paid, please contact migrate @ postman.com so that we can understand the case better and help you.

**Comment by GENnetuk-DEV** [comment]
I think as many have said, I certainly don't want my API's and credentials anywhere except locally or the SecOps guys would loose their tiny minds. I can see the 'logic' for 'cloud' in that it makes it easier to charge for it, and that's the whole point because this isn't open-source, its a business, and the primary driving force is profit. If we could have disabled the constant nags about a free account (the purpose of this track) then it wouldn't really change anything, pay or loose. 

In the end we've migrated away, which for what its worth was time consuming because the option to export collections in bulk has magically vanished and now we have to do it one by one ( the 3 dots to the right of the collection, then Export for anyone else wondering where it went ). 

As for Postman, I have to say I've enjoyed the ride, it was great software, well designed and did everything I could have asked for, until recently.
