### ISSUE TITLE
Code snippet: cURL settings: there is a problem with unchecking the 'Use long form options' option

### ISSUE THREAD

**Issue by calvinit** [a85/POSTMan-Chrome-Extension#9511]
**Describe the Issue**

> When I uncheck the 'Use long form options' option, I find the result problematic:

![s](https://user-images.githubusercontent.com/27403411/106409380-5f721880-647b-11eb-9d6c-6dd069a31b66.png)

> In fact, the request body option will still use the long form option (--data-raw) instead of the correct short form option (-d):

![c](https://user-images.githubusercontent.com/27403411/106409375-5da85500-647b-11eb-8500-154793652819.png)

> This is not supported on some systems:

![p](https://user-images.githubusercontent.com/27403411/106409378-5f721880-647b-11eb-98cf-5c4ca556d55e.png)

> I hope this can be corrected like the request header (-H), thank you!

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: Version 8.0.3
 - Operating System: Windows 10

**Additional Context**

> This problem has been around since version 7.x.y, and it still exists today.

**Comment by umeshp7** [comment]
Hey @calvinit! Thanks for reaching out. 

We are aware of this and this special handling was added for raw bodies only. Using `-d` assigns special meaning to some characters which was not desirable for raw bodies. 
We will be working on handling this better and come up with a fix soon. 

Which version of `curl` are you on? Since `--data-raw` was added in `curl 7.43.0`. If you are on a version higher than that you should hopefully not face any issues.
ref: https://curl.se/docs/manpage.html#--data-raw

**Comment by calvinit** [comment]
> Hey @calvinit! Thanks for reaching out.
> 
> We are aware of this and this special handling was added for raw bodies only. Using `-d` assigns special meaning to some characters which was not desirable for raw bodies.
> We will be working on handling this better and come up with a fix soon.
> 
> Which version of `curl` are you on? Since `--data-raw` was added in `curl 7.43.0`. If you are on a version higher than that you should hopefully not face any issues.
> ref: https://curl.se/docs/manpage.html#--data-raw

**Comment by cv3x** [comment]
@umeshp7 Hi, I checked that I am currently using version `7.29.0`. But in fact, there may be more than one version because there is usually not only one application server machine. Wouldn't it be more common for us to use the "-d" short form option? Generally speaking, the higher version of the syntax is compatible with the lower version.

```
# curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
```

**Comment by umeshp7** [comment]
Yes that makes sense, and I understand your concerns. We will be fixing this issue soon and I have labeled it as bug to track it faster. You could try using curl v7.43 or higher as a workaround till we have a fix. 
Will update this thread as soon as we have released that fix.
