### ISSUE TITLE
Cannot delete cookies gathered during OAuth2 authentication

### ISSUE THREAD

**Issue by orithena** [a85/POSTMan-Chrome-Extension#9532]
**Description**

If I want to test an OAuth2 authorization flow, I cannot reproduce everything without restarting Postman, because I cannot delete all cookies I received during OAuth2 authorization.

**Steps to Reproduce**

* Create a new request
* Under "Authorization", use type OAuth2 and enter configuration for your test server. Do not enable "Authorize using browser".
* Click "Get New Access Token". Postman should now show you the login dialog of your test server. 
* Log in.
* The authorization dialog of your test server should now show up.
* Close the Login window.
* Use the "Cookies" dialog to delete all cookies, if there are any.
* Click "Get New Access Token". 
* Instead of the login dialog, I now immediately see the authorization dialog. That shows that there are still cookies floating around in a jar somewhere.
* Restart Postman, try again: I now get the login dialog, as expected.

With the last Postman7 version I used (can't remember which exactly), this wasn't a problem: I could delete all relevant cookies from the cookies dialog of the request.

Additionally, I cannot see any requests emanating from the OAuth2 in the console; this looks like a regression from #7952, #7551, and #7992. Also, I cannot open the DevTools for the authorization dialog window.

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: 8.0.3
 - Operating System: Windows10

**Comment by Quaternions** [comment]
I have a similar problem.

Since the Postman callback URL (https://oauth.pstmn.io/v1/callback) isn't a valid call back URL in our IDP, I'm don't get my access token with the Authorize using browser option selected.

When I get an access token, and since I have all my endpoints inherit from the parent, I can see the bearer token being added to each header when I send a request.  I even see the auth flow in the Postman Console.

However, when I open up the cookie manager, no cookies are being saved from the authentication.  If I need to change users for follow up testing, I have to close the Postman client down and restart it in order to get a new login prompt.

**Environment Information**
Platform Type: Native Desktop Application
Postman Version: 8.0.4
Operating System: Windows 10 Professional (64bit)

**Comment by alexayers** [comment]
How I've worked around this is:

1  I intentionally supply a bad Callback URL this causes the call to fail leaving the postman authentication window open. 
2. Then I open up developer menu, "Show Dev Tools (Current Shell)." 
3. Select Application Tab
4. Click "Clear site data"
5. Close postman
6. Open postman
7. Now I can reauthenticate with a different username

**Comment by appurva21** [comment]
Hey @orithena @Quaternions @alexayers! 

We have fixed this issue with the latest release of Postman App (`v8.0.5`). Now there is a new `Clear cookies` option in the OAuth 2.0 window itself so that you can effortlessly clear all the cookies from the previous OAuth 2.0 sessions!

![Screenshot 2021-02-09 at 6 11 51 PM](https://user-images.githubusercontent.com/24985700/107365581-ffc2df80-6b02-11eb-946d-5cc4675453fa.png)

You can update you existing app or download the latest version from [here](https://www.postman.com/downloads/).

I'll be closing this issue but please feel free to reopen this if there are any more concerns.

**Comment by Quaternions** [comment]
@appurva21 Thank you very much.  I've verified that the new version works.  Much appreciated, you just made my life that much simpler.

**Comment by parthpanchal3399** [comment]
Hello @appurva21 !
I am using Postman v11.54.6 (which is the latest as of writing this comment).
I have been using the "clear cookies" button previously to delete the cookies and re-authorize with different users. Altough for some reason, I am noticing the same issue as mentioned by @orithena 

One more thing that I noticed is that the "clear cookies" button does not give the message "All cookies cleared successfully.", as it used to previously. However, I get this message when I clear them using the Cookies tab at the bottom of the window. Yet, it looks like it does not clear all cookies, because when I try to click "get access token" it uses the previously saved credentials to retrieve the token without asking me to login. 

Can you please look into this and reopen the issue?

**Comment by coditva** [comment]
@parthpanchal3399 Thanks for reaching out. I was able to replicate this issue and am happy to report that we've fixed this in v11.55.2. Let me know if you still face any issues due to this.

**Comment by parthpanchal3399** [comment]
Thanks @coditva for the prompt action!
I updated my app version to v11.55.2 and confirm that the issue has been fixed.
