### ISSUE TITLE
Disable or fix the spell checking in the description editor

### ISSUE THREAD

**Issue by d-schmidt** [a85/POSTMan-Chrome-Extension#9557]
**Is your feature request related to a problem? Please describe.**
The system is de-DE, we write English so everything is red.

**Describe the solution you'd like**
English text is not red.

**Describe alternatives you've considered**
Add an option, add a locale chooser.

**Additional context**

![grafik](https://user-images.githubusercontent.com/3226483/107028549-002f4380-67ae-11eb-9e2d-014b36cd6876.png)

**Comment by ChrisEt** [comment]
I know, "me too" posts are frowned upon, but I'd like to add additional details:

We have the same problem here - although we are all German-speaking and our systems are set to German language, we document our code and especially our APIs in English. Postman's spell checker marks almost every word as a typo. That means the built-in spell checking is the opposite of what is intended: instead of being a support it's an obstruction.

It would be great if there was at least the option to manually set the spell checker's language!

Btw, if you ever thought about localizing Postman: don't. Developers are usually good in English, and if a localization is not done really well, it's better to use the English version anyway.

**Comment by kamaraj-p** [comment]
Hi @ChrisEt , thanks for your feedback. We are working on a fix and will update this issue.

**Comment by kamaraj-p** [comment]
This issue is fixed on Postman v10.2. Spell check is only enabled when english is the browser language.
