### ISSUE TITLE
Editing the description doesn't save

### ISSUE THREAD

**Issue by fredrickace** [a85/POSTMan-Chrome-Extension#9564]
**Issue**

> While editing the documentation of a route in a collection, after clicking the save button the description is not updated. 

**Steps to Reproduce**

> Edit the description
> Click save
> The edited content is not saved

**Screenshots or Videos**

> https://user-images.githubusercontent.com/20112286/107108163-e9f3a880-67ea-11eb-945f-0888ba5c4431.mov 

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: 8.0.4
 - Operating System: macOs BigSur 11.1

**Comment by Raja-Simha** [comment]
@fredrickace thanks for reporting and we are looking into this. I'll keep you posted.

**Comment by mreis1** [comment]
Hey @Raja-Simha , don't know if the bug was solved or not. 
In my case, edit works if we create a new request, but if we clone an existing request with a description on it, save doesn't work.

**Comment by JaggedJax** [comment]
In my case, the edit looks like it doesn't work, but actually does work. The UI just serves up an old cached version making it look like the save failed. If I wait some amount of time and reload (minutes?), then the content that I edited will show up.

However if I try and edit it again before that happens, the edit is lost because the edit screen will show the old cached content.

OS: Pop!_Os 20.10
Postman native app: 8.0.6

**Comment by mccannt** [comment]
@fredrickace Can you try this on the most recent version of the app and confirm if this is resolved?

**Comment by ranchanarajasekaran** [comment]
This is not occurring in the latest version of the app.
 Please feel free to reopen the issue, if you still face this.
