### ISSUE TITLE
Ability to Supress Changelogs from showing in Public Workspace

### ISSUE THREAD

**Issue by mgrofsky** [a85/POSTMan-Chrome-Extension#9586]
**Is your feature request related to a problem? Please describe.**
Sometimes mistakes are made when modify and saving collection or API information and unwanted data is exposed.
When this occurs that exposed data is shown in the changelog if the workspace/collection is public.

**Describe the solution you'd like**
It would be nice to be able to completely suppress changelogs from being shown publicly or at least have the ability to delete or remove specific changes from the log.

**Describe alternatives you've considered**
My alternative is just exporting the API and reimporting it into a new Collection and sharing that instead.  If a change is made I just delete and reimport it again and not change that collection directly.

**Additional context**
None

**Comment by ankit-m** [comment]
@mgrofsky thank you for filing a ticket and explaining your use case. We are working towards improving our changelog offerings especially now that we have public workspaces. We're looking to introduce the ability to cleanup changelog so that you do not expose any mistakes.

I will update this thread once the feature is released.

**Comment by ankitjaggi** [comment]
@mgrofsky We released a new feature that allows you to hide diffs for certain changes in the changelog. You can find more information here: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections/#hiding-diffs-in-the-changelog
