### ISSUE TITLE
Importing cURL once blocks next imports

### ISSUE THREAD

**Issue by JacekKijewskiGelato** [a85/POSTMan-Chrome-Extension#9596]
**Describe the Issue**

Importing cURL once block next imports.

**Steps to Reproduce**

I click File > import and paste cURL as raw. The cURL goes to the proper collection and works. I click File > import again and nothing happens.

No information on terminal (where I start the app)

**Screenshots or Videos**

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: v8.05
 - Operating System: 
 Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by timbochamp** [comment]
Hi @JacekKijewskiGelato, I checked and this should be addressed in the fix for #9528 if you want to follow the resolution there. A workaround for now would be to use the Import button in the attached screenshot instead of the File > Import or the Import keyboard shortcut which are both affected by this issue
![Screen Shot 2021-02-11 at 11 52 49 AM](https://user-images.githubusercontent.com/4521134/107661782-fbf89f80-6c5f-11eb-8451-9e1a5669db29.png)
