### ISSUE TITLE
I have lost all my configurations!

### ISSUE THREAD

**Issue by Abdelkrim** [a85/POSTMan-Chrome-Extension#9637]
**Describe the Issue**

1. It has been a long time since I used Postman and my collections are empty for no reason

**Steps to Reproduce**

2. I opened it, postman asked me to download the latest version

3. I continued the opening of Postman

**Now, I have lost all my collections!**

**Screenshots or Videos**

![Screenshot from 2021-02-19 12-43-20](https://user-images.githubusercontent.com/791663/108500610-545b1d00-72b0-11eb-84c1-7f97fd8808cb.png)

**Environment Information**

 - Platform Type: Chrome 88.0.4324.150
 - Postman Version: Version 5.5.5
 - Operating System: Ubuntu 20.04 64 bits

**Additional Context**

This is simply unacceptable that you keep my files as hostage of a tool running on my desktop!

Stating that I must use Postman v7.0 to access my workspace or collections is NOT acceptable

**Comment by postman-staff** [comment]
Hi,

It looks like you are using the very old version of the application due to which you are unable to view the data. Can you navigate to the below link and see if that helps you locate your collections?


- Postman Web: http://go.postman.co
- All Collections: https://go.postman.co/me/collections
- All Environments: https://go.postman.co/me/environments

Looking forward to your response.

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@Abdelkrim Just checking to see if you were able to locate the collections using the link?

via @Raj-postman | Postman Support

**Comment by Abdelkrim** [comment]
@raj-postman I have deleted the old version of postman; my comments remain.

thank you
