### ISSUE TITLE
Created and Imported Collections disappear after exiting postman app

### ISSUE THREAD

**Issue by ccvermeulen** [a85/POSTMan-Chrome-Extension#9667]
After importing, or creating a sample collection everything works as expected.
![image](https://user-images.githubusercontent.com/10669909/109282597-0600cd80-781e-11eb-869c-7ed68ae9f977.png)

However, after restarting postman, everything disappears from view and even open calls cant be reopened.
![image](https://user-images.githubusercontent.com/10669909/109282787-49f3d280-781e-11eb-898d-34527b5e242f.png)
 
As far as I can see, everything is up-to-date;
![image](https://user-images.githubusercontent.com/10669909/109282938-7b6c9e00-781e-11eb-9bfd-1322aab13d7c.png)

Does anyone have a solution?

**Comment by postman-staff** [comment]
Hi @ccvermeulen,

Thank you for reaching out, and happy to help. Looking at your screenshot, it looks like your app isn't syncing to our servers which would most likely explain this behaviour:
 ![](https://postman.zendesk.com/attachments/token/INPT1UuHS7tzrGhlbOJqVrmM9/?name=inline732008860.png)
For reference: https://learning.postman.com/docs/getting-started/syncing/#states

Could you reach out to us by submitting a ticket here: https://www.postman.com/support/ ​so we can investigate further? It'll help determine if it's account specific or get more insight on the issue here. We look forward to hearing from you.

via @SabriH10 | Postman Support

**Comment by postman-staff** [comment]
Hi @ccvermeulen,

Just following up here. Let me know if you have any follow up questions or concerns as we haven't heard back.

via @SabriH10 | Postman Support

**Comment by postman-staff** [comment]
Hi @ccvermeulen,
I'll be closing this on our end as we haven't heard back. Hopefully, the information shared was helpful. If you still require assistance, please reach out to us by submitting a ticket here: https://www.postman.com/support/ ​so we can investigate further.
Have a great day!
via @SabriH10 | Postman Support

**Comment by DannyDainton** [comment]
Close this as there has been no response about the initial issue.
