### ISSUE TITLE
Upgrade fails with error "Error Migration: indexedDB schema migration failed.  IndexedDb was not upgraded successfully after 'dexie.open'

### ISSUE THREAD

**Issue by polydectes** [a85/POSTMan-Chrome-Extension#9690]
During an upgrade from 5.3.2 R02, Postman goes through 2 update cycles.

The first updates the application to version 6 successfully.  The second updates to version 7.  After the second update Postman is failing to open on my Windows 10 machine.  It displays the following error:

"Error Migration: indexedDB schema migration failed.  IndexedDb was not upgraded successfully after 'dexie.open'

And recommends restarting the app to clear up the problem.  Restarting does not fix the issue.  I have been able to uninstall the app and remove the %USERHOME%\AppData\Local\Postman folder and reinstall version 5.3.2 R02 and reproduce this problem multiple times.

**Comment by taehoshino** [comment]
Hey @polydectes, 

Thanks for reaching out! I am more than happy to assist you with the issue!

I understand you are unable to upgrade your app to the latest version due to an error. 
Sorry for the hassle, but happy to help!

Can you try renaming the “Postman” folder from below two locations to “Postman.old” and then reinstall the latest version 7 from [here](https://go.pstmn.io/dl-win64-v7-latest) to see if that helps?
```
C:\Users\<user>\AppData\Local
C:\Users\<user>\AppData\Roaming
```

I hope this helps. Please let me know how it goes.

Thanks for your cooperation here.
I am looking forward to hearing back from you!

@taehoshino | Postman Support

**Comment by postman-staff** [comment]
Hey @polydectes,

I hope all is well! I just wanted to follow up on my previous message - are you still experiencing the issue here?

If there's anything I may help you with, please do let us know.

via @taehoshino | Postman Support

**Comment by smai** [comment]
I had the same issue when upgrading to the latest release, 9.8.3 from...I believe 8.10.0 on win64.  The above suggestion did not help, same issue.  I uninstalled postman, and I ran agent ransack to find anything with 'postman' in the filename.  I deleted all that.  Then did a fresh install with 9.8.3 and it worked.
