### ISSUE TITLE
Cookies captured by interceptor are not added to request headers

### ISSUE THREAD

**Issue by vsosnin** [a85/POSTMan-Chrome-Extension#9691]
**Describe the Issue**
After upgrading to Postman version 8.0.6 I noticed that cookies captured by interceptor were not being added to request headers (Disable cookie jar was OFF under request Settings)

**Steps to Reproduce**
1. Set Capture Cookies to ON in Postman Interceptor
2. Capture cookies and verify they appear under right domain in MANAGE COOKIES modal
3. Navigate to request's Headers tab, click to show hidden headers. 
Expected result: captured cookies for the domain should appear in Value column for hidden Cookie key
Actual result: Cookie key was missing 

**Workaround**
Manually add Domain=<domain_name> attribute to the cookie via MANAGE COOKIES modal

**Environment Information**

 - Platform Type: MacBook Pro
 - Postman Version: 8.0.6
 - Operating System: macOS Catalina (10.15.7)

**Comment by vinitshahdeo** [comment]
@vsosnin This issue seems similar to #9541. The latest [Postman Interceptor](https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en) `v1.1.2` contains fix for #9541.  Can you please update your extension and confirm?

If above doesn't help, can you please share the exact cookie string(after removing sensitive info) to help us investigate further?

e.g., `foo=bar; Path=/; Domain=env.company.com; Secure; Expires=Sat, 27 Mar 2021 15:55:41 GMT;`

**Comment by vsosnin** [comment]
@vinitshahdeo the upgrade to v.1.1.2 resolved the issue. Thank you!
