### ISSUE TITLE
Trim trailing whitespace

### ISSUE THREAD

**Issue by zmharker** [a85/POSTMan-Chrome-Extension#9707]
Postman macOS client, version 8.0.6

Basic test case:
1. Using the Postman client, make a GET request to `https://api.getpostman.com/collections` without providing any authorization. Response is 401 Unauthorized as expected.
2. Add a single space to the same request: GET `https://api.getpostman.com/collections `. Response is 404 Not Found.

It's hard to imagine a use case where it's important to preserve trailing whitespace, as it's most likely a typo (browsers ignore it). If preserving it is intentional and needed for some reason, consider requesting confirmation from the user or allow power users to override a sensible default. Thanks!
![postman_error](https://user-images.githubusercontent.com/4250080/110533941-bf438b00-80db-11eb-8b0d-c639bec05fb6.gif)

**Comment by vvs11** [comment]
@zmharker We have made the trailing whitespaces visible in the URL bar. We don't want to restrict any use case that users might have since Postman is a debugging client. Users in some cases would want to test how the servers would respond to some scenarios. If you think the whitespace is not very visible, we can take that as a feature and plan it in our roadmap. 
However, we are still debating about keeping it as a setting because it's difficult for users to access and manage them. 
I will close the issue for now. Please feel free to post your comments here or file a new issue for making whitespace more visible. 
Thanks for using Postman :)
