### ISSUE TITLE
Error connect EACCES on latest version with a VPN

### ISSUE THREAD

**Issue by qaoru** [a85/POSTMan-Chrome-Extension#9708]
**Describe the Issue**

I'm using a VPN (Pulse) to remotely access some services and I'm getting an `Error: connect EACCES <server_ip>:443` when sending requests to remote servers (using private IP adressing).

**Steps to Reproduce**

Might be an isolated case, but trying to reach servers through VPN produces this error.
It is not a server issue as they are reachable with other tools (i.e. browser, newman).

**Environment Information**

 - Platform Type:  Desktop
 - Postman Version: 8.0.7
 - Operating System: Windows 10

**Additional Context**

It seems to be related with the latest update. I tried with an older v7, no problems. It is also working without issues on v8.0.6 but since the minor updates are done automatically, I'm basically stuck here.

**Comment by bavulapati** [comment]
@rahveiz Please help us investigate the root cause of the problem with the logs. We request you to share the additional network log information for understanding the issue better. We suggest you to use canary application for generating these logs, so that your existing application and data is not impacted.

Please find the following instructions for generating the logs.

1. Download and install the latest canary app from https://www.postman.com/downloads/canary
2. Launch the application using the following commands (Use command prompt or Powershell to execute these commands)
cd %LOCALAPPDATA%\PostmanCanary .\PostmanCanary.exe --log-net-log=%APPDATA%\PostmanCanary\logs\postman-net.json
3. Once you are able to see the error, close the application.
4. Please send all the logs from %APPDATA%\PostmanCanary\logs folder to help@postman.com.

**Comment by qaoru** [comment]
@bavulapati Hi, is there any other kind of logs that I can include as well ?
I don't think the error will be logged on the network log as nothing is sent (based on what I've seen on the DevTools).

**Comment by bavulapati** [comment]
@rahveiz The logs you will be providing include network logs as well as postman logs. We will try to analyze the logs and come back to you if we need additional information for understanding the issue better.

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/6053

**Comment by jviotti** [comment]
See https://github.com/postmanlabs/postman-app-support/issues/7240
