### ISSUE TITLE
Postman generated documentation uses initial value of environment variables instead of current value

### ISSUE THREAD

**Issue by E-Thang** [a85/POSTMan-Chrome-Extension#9747]
**Describe the Issue**
Postman generated documentation seems to use the initial value of environment variables instead of current value. Collections/runners use the current value. This difference is confusing. I don't see this behavior documented anywhere, so I'm assuming it's a bug. A second part of this is that the documentation feature seems fine with a variable that resolves to an empty string. I can't think of a case where I would want an empty string in a document. Perhaps when a document uses a variable and it resolves to an empty string it should trigger a warning that can be silenced if it was intended to be empty.

If this is an intentional security decision it would be great if it were mentioned prominently in the documentation.

**Reproducibility**
Happens **almost** all of the time. I intermittently had the current value though, which made it even more confusing. I can't say definitively if that was something I had a hand in or not though.

**Steps to Reproduce**
Create an environment variable with different values for initial and current value. Create a new collection that uses the environment variable. Open the generated documentation and observe that it pulls the initial value.

I had a variable that I intentionally left with no initial value as a reminder that I wanted that to not be synced through Postman, but when I created documentation using it I was stumped by it just being blank even though the current value was filled in. Using a variable like that, http://{{hostname}}:5000/endpoint becomes http://:5000/endpoint in documentation with no indication of an issue. The same variable functions fine inside a collection.

**Screenshots or Videos**
Here's an example with a variable that has different initial and current values, to show which one is used.
![image](https://user-images.githubusercontent.com/19691760/111556833-a88add00-8748-11eb-8e3a-39d1edfe1583.png)
![image](https://user-images.githubusercontent.com/19691760/111556773-885b1e00-8748-11eb-8def-d05b0f018832.png)

**Environment Information**

 - Platform Type:       Windows and Linux
 - Postman Version: 8.0.7 (Windows) and  7.36.5 (Linux)
 - Operating System: Windows 10 and Linux Mint 20.1

**Comment by mark-anthony-postman** [comment]
@ethangrinnell78 Thanks for letting us know about your experience. Collection documentation shows the initial value for variables (rather than the current value), which is documented here: https://learning.postman.com/docs/publishing-your-api/documenting-your-api/#associating-environments-with-documentation

An option you can consider is persisting variables. When you persist variables, your local current values are synced to the Postman servers and replace the initial values in the shared collection. The documentation will then show these new initial values. You can learn about persisting variables here: https://learning.postman.com/docs/sending-requests/variables/#sharing-and-persisting-data

**Comment by Himanshu0781** [comment]
Closing the ticket with the resolution as provided above.
Feel free to re-open the ticket if you still face any issue. 🙇
