### ISSUE TITLE
Postman not picking up certificate

### ISSUE THREAD

**Issue by RejiMat** [a85/POSTMan-Chrome-Extension#9751]
**Describe the Issue**
I am a window10 user.  I have postman version 8.0.7.
When i add certificate to postmand. I use the file selector in postman window. 

After select a certificate and provide passphrase.
In next certificates screen i see PFX file path starting with / 
eg /C:/Gen1/Postman/rrqa/rrqa.pfx

And when invoking api i get below error,
"Error: write EPROTO 1276089048:error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE:../../third_party/boringssl/src/ssl/tls_record.cc:592:SSL alert number 42"

**Steps to Reproduce**
add certificate and invoke api. certificate is not pickup.

**Environment Information**

 - Platform Type:  Postman for windows
 - Postman Version: 8.0.7
 - Operating System: win32 10.0.18363 / x64

**Comment by postman-staff** [comment]
Hi,

Thanks for reaching out to us! Sorry to hear you're having issues with the client certificate. Would you turn off SSL certificate verification and let us know how that goes?


- Settings > General > SSL certicate verification > Off

Also, could you please provide us the logs for the endpoint while sending the request with client certificates? Here's a full OpenSSL s_client command that'll help us check this further.

**> openssl s_client -state -connect <request-domain>:443 -cert /path/to/client-cert -key /path/to/client-cert-key | openssl x509 -text**

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @RejiMat

Just following up here. Let me know if you have any follow-up questions or concerns as we haven't heard back.

via @Raj-postman | Postman Support

**Comment by RejiMat** [comment]
Sorry couldn't respond earlier.
Please see inline comments

**Comment by postman-staff** [comment]
@RejiMat Looks like the screenshot did not get through. You can also share these details by submitting a ticket via link https://www.postman.com/support and we will check this further.

With regards to "/" at the beginning of the file path - this is Postman normalized file path that we store in order to maintain compatibility between different operating systems for collaboration. More details in this thread here: https://github.com/postmanlabs/postman-app-support/issues/8852#issuecomment-665603793

via @Raj-postman | Postman Support

**Comment by RejiMat** [comment]
Hi,

Yesterday my postman was updated to v8.0.8 and after that i dont see this certificate issue any more.

Thankyou for your prompt response and support.
