### ISSUE TITLE
Publish collection from Windows app with environment gives error

### ISSUE THREAD

**Issue by E-Thang** [a85/POSTMan-Chrome-Extension#9764]
**Describe the Issue**
Publishing a collection from the native Windows application and including an environment throws an error when the "Publish Collection" button is clicked in the web application. If I don't include an environment it works without issue.

**Steps to Reproduce**
1. In Windows application, create a collection with a request
2. Create an environment
3. Publish collection
4. When web browser launches select the environment to include in the published document
5. Click Publish Collection and observe error

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/19691760/112550914-561b7300-8d7d-11eb-92d7-df44ae1e3ebb.png)
![image](https://user-images.githubusercontent.com/19691760/112550589-d9889480-8d7c-11eb-97bb-dc64535d540b.png)
![image](https://user-images.githubusercontent.com/19691760/112550717-08066f80-8d7d-11eb-9a86-49a70e79d49d.png)
**Environment Information**

 - Platform Type:      Windows x64
 - Postman Version: Postman for Windows  Version 8.0.9
 - Operating System: Windows 10 20H2

**Additional Context**
When the web application is launched I can navigate to the workspace, view the collection, and publish the collection from there and it works. It only seems to be a problem when the Windows application initially triggers the publish.
I don't have the same issue in Linux, but the Linux application doesn't actually do much without launching the web app, so I can only publish from the web app in Linux.

I tried making my profile public, a public workspace and a private workspace, and also created a second Postman account with a different email address.

**Comment by Raja-Simha** [comment]
@ethangrinnell78 This issue has been fixed in a recent version of the App. Let us know if you are still facing this problem.

**Comment by arun07as** [comment]
Just adding some extra info.

I had a collection which I had published in a version of the windows app where this bug was occurring. Back then, I had published without environment as I was unable to publish with environment at that time due to the error

Now I updated to latest version of the app, but when I tried to edit the published documentation settings to include environment, it still showed error no matter what I tried.

In the end, I unpublished the collection and published again and this time it worked.

So if anyone else is on latest version of the app and still getting the error, unpublish the collection and publish again
