### ISSUE TITLE
Collections will not load 

### ISSUE THREAD

**Issue by F-shaikh** [a85/POSTMan-Chrome-Extension#9776]
**Describe the Issue**
"Couldn’t load collections
Try refreshing this page or check back in some time."

Collections will not load on desktop client, or browser client. 110 collections total. 

**Steps to Reproduce**
Open postman (desktop or web browser) and your collections will fail to load. I have 110 total collections. 

**Screenshots or Videos**
WEB:
![image](https://user-images.githubusercontent.com/38937921/112887372-f75d3e80-9087-11eb-9dde-a2183c78df8e.png)

MacOS Client: 
![image](https://user-images.githubusercontent.com/38937921/112887427-06dc8780-9088-11eb-8d5d-c97a2bc289af.png)

**Environment Information**

 - Platform Type: Web & Desktop Client
 - Postman Version: 8.0.10
 - Operating System: MacOS

**Additional Context**
This only happened after updating today to the latest version of the client, but I am not sure why this will not load on the browser client either. Happens for the entire team, and it says we are all In Sync.

**Comment by postman-staff** [comment]
Hey @F-shaikh,

Thank you for reaching out, and apologies for the hassle.
We have received similar reports, and our engineering team is currently looking into it.

So that we can locate your account information, would you please submit a support request from the following link?
https://support.postman.com/hc/en-us/requests/new

In the support request, please tell us about the following so that we can troubleshoot further.

**1. Can you please provide us with answers to the following questions:**


- Can you navigate to a different Workspace to see if you can open the collections there?
- Are you able to preview your environments?

**2. Just so we can check your particular case further as well, could you please provide us with the HAR files**
**How to capture HAR files**
https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting

**3. Canary version**

- Could you try using Postman Canary to see if it can serve as a temporary unblock option? - https://www.postman.com/downloads/canary/

Again, sorry for the troubles. Please let me know if you have any questions.

via @taehoshino | Postman Support

**Comment by F-shaikh** [comment]
@postman-support i've done this already, please see all info in Ticket ID: #71491.

To summarize here:
1. Can navigate only to "My Workspace" which contains 2 collections. The other 2 workspaces (76) and (110) collections wont load. 

2. I've sent the HAR via Google Drive Link on the ticket ID: #71491

3. Canary version does not work, web client does not work, regular desktop app does not work.

**Comment by postman-staff** [comment]
Hey @F-shaikh,

Thanks for getting back to me!

I can see one of our team members is handling your support request and your case is already escalated to our engineering team.

Monitoring the backend log, it appears that the issue might be mitigating. Could you please check now if the issue is still persisting?

Thanks for your cooperation on this.
I am looking forward to hearing back from you!

via @taehoshino | Postman Support

**Comment by F-shaikh** [comment]
yup its fixed! thanks!

**Comment by postman-staff** [comment]
Hey @F-shaikh,

Excellent! Thanks so much for confirming the fix!

Please do let us know if you have any other questions. We'd be happy to help!

Thanks for using Postman 🚀​

via @taehoshino | Postman Support

**Comment by iyvinjose** [comment]
@postman-support 
I'm also having the same issue,
Tried updating the desktop app, installing the canary version, but still, collections are not loading.

What is the fix for this issue?

**Comment by taehoshino** [comment]
@iyvinjose 

Thanks for getting in touch! 
So that we can look into your case closely, would you please submit a request from the following link?
https://support.postman.com/hc/en-us/requests/new

We are looking forward to hearing from you!

**Comment by iyvinjose** [comment]
it looked like a low-bandwidth issue, that day there were some bandwidth issues with my internet connection, but the browser was working fine, postman failed to load both collections and environments, 

But the next day it worked, the only difference I could notice is this slow internet that day.

**Comment by viktor111** [comment]
@postman-support
Same issue. Tried reinstalling the app nothing. Tried web version does not work too.

**Comment by arlemi** [comment]
@viktor111 We are currently experiencing some downtime, Engineering team is working quickly to get everything back up and running. We will keep you posted as soon as we have the systems running as expected!

**Comment by arlemi** [comment]
@viktor111 Everything should be back to normal now.
