### ISSUE TITLE
Autogenerated CURL doesn't work

### ISSUE THREAD

**Issue by jonforcade** [a85/POSTMan-Chrome-Extension#9791]
Folks,

I wanted to bring your attention to something that I noticed. I'm not a super expert - so please bear with me if I'm off base.

I created a working json request to a server of mine.

From within Postman, I asked to see the curl that matches what I have working and it shared this:

```
curl --location --request POST 'https://10.21.1.50/jsonrpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "method": "exec",
    "params": [
        {
            "data": {
                "passwd": "test",
                "user": "user"
            },
            "url": "/sys/login/user"
        }
    ],
    "session": "string",
    "id": 1
}'
```
However, that doesn't work on my systems. 

The following does:

```
curl -k -X POST -H 'Content-Type: application/json' -d '{
  "method": "exec",
  "params":[
      {
        "data":{
             "passwd": "test",
             "user": "user"
        },
        "url": "/sys/login/user"
     }
  ],
  "session": "string",
  "id": 1
}' https://10.21.1.50/jsonrpc
```
```
{ "id": 1, "result": [ { "status": { "code": 0, "message": "OK" }, "url": "\/sys\/login\/user" } ], "session": "hcrYZeeWmnUvPCWLvNERGTDMtpHjrqc8hilibewShAflWzCvB\/rYyQhEDjLyE2ebhhAe7CErK+iGVvoiS0m\/KA==" }
```
Also, when you select Disable SSL certificate verification the CURL should add -k to the script.

**Comment by DannyDainton** [comment]
Hey @FortiJon

Which version of Postman are you using to generate that command?

When you say _it doesn't work_, what does that mean? 

Are you shown an error response, no response, something else? 

Does adding the `-k` flag to the Postman generated command make it work?

**Comment by jonforcade** [comment]
Postman: 8.1.0

Error messages: 
  curl: option --data-raw: is unknown
  curl: try 'curl --help' or 'curl --manual' for more information
The platform is CentOS 7

On my Mac, the code works after I add a -k to the original Postman script.
Adding the -k on the CentOS 7, generates the same data-raw error.

**Comment by DannyDainton** [comment]
As a workaround you could remove the `-raw` part and use `data`. 

That should work the same as your command.

Just to confirm, this is only not working on CentOS 7?

**Comment by jonforcade** [comment]
Will do - remove raw!

Yes, I believe so - just CentOS 7.

Thank you Danny for the fast response, much appreciated!

**Comment by Tipo-4ek** [comment]
JFYI
i have same problem on linux_ubuntu_14.04_trusty

use `--data` or `--d` solve issue

**Comment by SahilChoudhary22** [comment]
@jonforcade @Tipo-4ek The error is due to the difference in curl versions. The `--data-raw` option was introduced in curl version 7.43.0 (released on June 17, 2015) ([PR](https://github.com/curl/curl/issues/198)), while CentOS 7 and Ubuntu 14.04 uses an older version of curl that doesn't support this option. The `--data-raw` was added to escape special characters like `@` within the `--data` option.

Default cURL versions in the mentioned OS  -
CentOS 7: curl 7.29.0
Ubuntu 14.04: curl 7.35.0

We're working on the fix where if you disable this option(shown in the image) within the snippet settings

![s](https://user-images.githubusercontent.com/27403411/106409380-5f721880-647b-11eb-9d6c-6dd069a31b66.png)
you'll always get the short form options i.e. `-d` instead of `--data` or `--data-raw` unless absolutely necessary. This should be live with the next release of the module. Stay tuned! ✨

Until then, as @DannyDainton suggested, you can use the `-d` or `--data` option instead of `--data-raw` in the cURL command on CentOS 7, Ubuntu 14.04 and older Ubuntu versions which have older version of curl pre-installed.

**Comment by akshaydeo** [comment]
Upgrading the curl should solve this issue. The codegen in Postman plans to focus and take advantage of the latest stable version of curl 🙇‍♂️ 

Please feel free to open the issue if I still need to include anything here.
