### ISSUE TITLE
8.2.1 can not sign in (Linux desktop)

### ISSUE THREAD

**Issue by shalltears** [a85/POSTMan-Chrome-Extension#9817]
I am a package under Linux. In the latest version 8.2.1, I can't log in. Sign in via web browser is always displayed. Click open your browser. There is no response

**Comment by postman-staff** [comment]
Hey @shalltears,

Thanks for writing in and sorry to hear that you are experiencing some issue on the app.

So that we can precisely understand the issue, would you please share some screenshots of what you are seeing while you reproduce the issue?
**Please make sure to redact any sensitive information from screenshots before posting.**

Thanks for your cooperation on this.
I am looking forward to hearing back from you!

via @taehoshino | Postman Support

**Comment by shalltears** [comment]
![image](https://user-images.githubusercontent.com/37053882/114649017-5373c400-9d12-11eb-9651-9a0905a20997.png)
![image](https://user-images.githubusercontent.com/37053882/114649195-9f266d80-9d12-11eb-983f-34cdf8ba0b63.png)

It's this interface. You can't start the browser by waiting or clicking, nor can you switch to the default browser, but you can jump to version 7 and upgrade to 8.2.1

**Comment by postman-staff** [comment]
Hey @shalltears,

Thanks for the screenshots. Again sorry for the troubles.

Can you try the following and see if that works?
1. Open go.postman.co on web browser
2. Sign into your account
3. Launch the desktop app

If the issue is still persisting, would you please create a support request from the below link and send over the application logs so that we can look into this further?
https://support.postman.com/hc/en-us/requests/new

Here is how you can find application logs:
https://support.postman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application-
Please send over the logs as a zip file attachment.

In your request, please mention the GitHub issue URL https://github.com/postmanlabs/postman-app-support/issues/9817 so that we can keep track of your case.

Thanks for your cooperation on this.
I am looking forward to hearing back from you!

via @taehoshino | Postman Support

**Comment by postman-staff** [comment]
Hey @shalltears,

I hope all is well! I just wanted to follow up on my previous message - are you still experiencing the issue here?
Please do feel free to reach out if there is anything we can help!

Have a great day and thanks for using Postman!

via @taehoshino | Postman Support

**Comment by shalltears** [comment]
Sorry, because I'm busy with the project, I'll use the lower version first, and I'll give feedback immediately when I have time to test later.

**Comment by chrisdeso** [comment]
Hey @shalltears - that sounds great! We'll close this issue in the meantime but feel free to reopen it if you have any further feedback 👍🏽
