### ISSUE TITLE
Clicking requests in Postman runner should open the request for the user

### ISSUE THREAD

**Issue by margiehu** [a85/POSTMan-Chrome-Extension#9858]
The new Postman runner UI cuts off the name of the request in order to show more of the request URL. I rely on the request names to know which request is failing since I don't memorize the URLs.

I think a great enhancement to the runner would be allowing the user to click on the request name and have a new tab automatically open with the request.

Currently I have to search for the name in the search bar and open it myself. I think it is more intuitive to automatically open the request. Currently clicking on the request gives options to see parameters etc. All that information could be given to the user faster by just opening the request.

**Comment by DannyDainton** [comment]
Hey @margiehu

Could you provide an image of this in the runner UI, where the name is cut off, please?

Just so that we can visual see what issue you're referring too.

**Comment by margiehu** [comment]
@DannyDainton 

Here's an example of the request names being cut off. As you can see I can still see enough of the title to see which request it is but we have many tests that are named very similarly named so I always have to go to the search bar to find the exact test. 

![image](https://user-images.githubusercontent.com/5385615/115563375-7576c480-a285-11eb-85f7-ef08c4614f02.png)

**Comment by malvikach** [comment]
Hi @margiehu 👋 

Thanks for your feedback. I agree that the current behavior can be made better. We are taking a look at this. 

We are tracking both problems as below:
1. Request names are hidden in the Interface of Results: https://github.com/postmanlabs/postman-app-support/issues/10015
2. Requests cannot be opened directly from results: https://github.com/postmanlabs/postman-app-support/issues/10978

cc: @wittyneo 

I am closing this issue here. However, I will be updating the attached tickets as we have news on the fixes respectively. Please do feel free to provide any more inputs. 

Thanks again for writing down to us and letting us know about the problem.

Cheers!
Malvika
