### ISSUE TITLE
Import Swagger: required path params imported with "Lorem ipsum" instead of empty value

### ISSUE THREAD

**Issue by stokito** [a85/POSTMan-Chrome-Extension#9866]
When a Swagger file imported the path variables has a random lorem ipsum values:
![postman-path-param-lorem](https://user-images.githubusercontent.com/415502/115959868-031d1300-a517-11eb-8c83-12b9fa0857c3.png)

This confuses and also I have a pre-request script that populates request path variables from environment variables and it first checks that the path var doesn't have a value.
Could you please disable this behavior and import as is without any modifications?

Example of a simple swagger file to test:
```yaml
swagger: '2.0'
info:
  version: 0.0.1
  title: Example
paths:
  /groups/{groupId}:
    get:
      operationId: getGroupById
      summary: Get a specified group
      description: Get a specified group including its immediate descendants
      parameters:
        - name: groupId
          in: path
          type: string
          required: true
          description: Group ID under which we wish to retrieve children groups
      responses:
        200:
          description: A list of groups
          schema:
            type: array
            items:
              $ref: '#/definitions/Group'
definitions:
  Group:
    type: object
    properties:
      id:
        type: string
        description: Group ID
        format: string
        maxLength: 255
      parentId:
        type: string
        description: Parent Group ID
        format: string
        maxLength: 255
      name:
        type: string
        description: Name for the Group
        maxLength: 255
```

Using latest Postman v8.3.0-canary01

**Comment by VShingala** [comment]
@stokito While importing or generating collection from Swagger file, you can provide options under `Show advanced settings` dropdown menu. Here you can use `Schema` instead of `Example` for parameter value generation. This will make sure a placeholder like `<string>` (i.e. `<{type_of_param}>`) is used instead of a randomly generated string.

As an empty value does not indicate the type of parameter, it is not something appropriate for all user's use cases.

**Comment by stokito** [comment]
Great! thank you @VShingala
