### ISSUE TITLE
Colors of the json are wrong

### ISSUE THREAD

**Issue by Danielyago1** [a85/POSTMan-Chrome-Extension#9949]
as for now the colors of the request and the respond were red and blue and that was perfect
but now after updating to 8.3.1 using Mac, the colors are all grey. this is very hard to read
how can i change it to what it was/?\

your help is very appreciated
Thanks

**Comment by postman-staff** [comment]
Hi there,

The current version of the app is v8.4.0 and you can update it from settings->update. I could see the response that I'm getting for a request is having the expected color in red & blue.

​ ![](https://postman.zendesk.com/attachments/token/7KOVPBOltnbOp5jVzrlI4tK50/?name=Screenshot+2021-05-20+at+3.32.26+PM.png)​

Also, the request is having the relevant color as shown in the screenshots.

 ![](https://postman.zendesk.com/attachments/token/ibHXnBAKdfYf0YvqUomY0v4H5/?name=Screenshot+2021-05-20+at+3.35.26+PM.png)​

My apologies, if this is not something you are referring to. It would be really helpful if you could share the relevant screenshots.

In addition, you can also open a new ticket on our support channel using this link - https://www.postman.com/support/. Also, do add the GitHub issue number (#9949) and your GitHub username in the request description to make it easy for us to track.

via @Swapnil-getpostman | Postman Support

**Comment by postman-staff** [comment]
Hi there,

Hope you are doing good. Since we did not hear back from you for a while, so just wanted to follow up with you on this ticket to check if you need any further assistance.

Let me know if you have any other queries or if it's okay to close this ticket from here?

Best,
Swapnil | Postman, Inc.

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by postman-staff** [comment]
Since I did not hear back from you for a while, I’ll be closing this support request next. If you still require my assistance on any matter, please reopen it by responding to this message. Alternatively, feel free to submit a new support ticket using this link - https://www.postman.com/support/ on any matter and at any time. I’ll be happy to help.

via @Swapnil-getpostman | Postman Support
