### ISSUE TITLE
Postman proxy certificate missing for MacOS

### ISSUE THREAD

**Issue by jazzgershoam** [a85/POSTMan-Chrome-Extension#9962]
Hi Team,
Greetings.

I'm trying to find the proxy certificate for MacOS to enable https proxy.
Ref: https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/#capture-https-traffic-with-postmans-built-in-proxy

But unfortunately the folder/certificate is unavailable in MacOS.
[ ~/Library/Application Support/Postman/proxy]

Can you please help here.

**PFB the environment details:**
Postman Version: 8.5.0
Operating System: Mac OS Big Sur [Version 11.1]

Thanks,
Jazz
<img width="892" alt="Screen Shot 2021-05-21 at 5 37 51 PM" src="https://user-images.githubusercontent.com/41484047/119134870-4ce81300-ba5b-11eb-9748-f189a8b48a6a.png">
<img width="341" alt="Screen Shot 2021-05-21 at 5 48 39 PM" src="https://user-images.githubusercontent.com/41484047/119136050-cf250700-ba5c-11eb-8e95-4adf9cce20c3.png">

**Comment by postman-staff** [comment]
Hey @jazzgershoam

Thanks for reaching out to Postman Support. Sorry that you are facing issues while using Postman --- Happy to help.

This is not an expected behaviour.

Could you please try manually searching for the proxy folder to find if it is located in any other file path? (just to confirm if the folder is moved or Postman is installed in another location other than Applications folder inadvertently)

If that doesn't work, may I request you to do a fresh install to see if the 'Application Support' folders created properly?

Will wait to hear back from you.

via @VaishnaviChallaPostman | Postman Support

**Comment by upieez** [comment]
Experiencing the same issue here. Can't seem to find the certificate even after searching for a proxy folder. The mac I'm using  is brand new.

**Comment by postman-staff** [comment]
Hey @upieez and @jazzgershoam

May I request to know if you have OpenSSL installed. Could you please verify this using `openssl version` command in the CLI.

If not installed, please [install OpenSSL](https://franz.com/support/documentation/current/doc/installation.htm#macosx-ssl-install-2), quit Postman app and reopen to see if the files are present.

Will wait to hear back from you.

via @VaishnaviChallaPostman | Postman Support

**Comment by postman-staff** [comment]
Hey @upieez and @jazzgershoam

Reaching out to see if the information provided was helpful.

Looking forward to your response. Have a great day :)

via @VaishnaviChallaPostman | Postman Support

**Comment by upieez** [comment]
Hey @postman-support, thanks for getting back. 

Yes I have verified that I have openssl installed with the version `LibreSSL 2.8.3` and still do not see the certificate folder.

**Comment by postman-staff** [comment]
Hey @upieez

Thanks for writing back. Sorry for the inconvenience.

To troubleshoot further we will need app logs. Could you please open a new ticket on our support channel using this link - https://www.postman.com/support/

Getting Postman logs - https://support.postman.com/hc/en-us/articles/360033270134-Where-can-I-find-logs-for-the-Postman-app-

Also, do add this GitHub issue number and your GitHub username in the request description to make it easy for us to track.

via @VaishnaviChallaPostman | Postman Support

**Comment by upieez** [comment]
> Hey @upieez
> 
> Thanks for writing back. Sorry for the inconvenience.
> 
> To troubleshoot further we will need app logs. Could you please open a new ticket on our support channel using this link - https://www.postman.com/support/
> 
> Getting Postman logs - https://support.postman.com/hc/en-us/articles/360033270134-Where-can-I-find-logs-for-the-Postman-app-
> 
> Also, do add this GitHub issue number and your GitHub username in the request description to make it easy for us to track.
> 
> via @VaishnaviChallaPostman | Postman Support

Hey the strange thing about it is that when I follow the link to find the logs, it points me to the ~/Library/Application Support/Postman/logs which is unfortunate because this whole issue is that the folder doesn't exists. Hence I will not be able to get the postman logs as well

**Comment by postman-staff** [comment]
Hey @upieez

Thanks for writing back.

This is definitely not expected, as the logs should be present in the default location unless the installation directory is changed/ is deleted. But I understand it is being a problem on your end.

Could you please try our Canary version, and let us know if it helps? - https://www.postman.com/downloads/canary/

Will wait to hear back from you.

via @VaishnaviChallaPostman | Postman Support

**Comment by upieez** [comment]
Hey @postman-support, tried your Canary version and still can't seem to get the folder to appear in `~/Library/Application Support/`. Any other method I should try?

**Comment by postman-staff** [comment]
Hey @upieez

Thanks for writing back. That is actually strange.  Sorry for the inconvenience  :/

Could you please open a new ticket on our support channel using this link - https://www.postman.com/support/ to take this forward. We may need to investigate this further in detail to identify the root cause.

Also, please do add this GitHub issue number and your GitHub username in the request description to make it easy for us to track.

Thank you!

via @VaishnaviChallaPostman | Postman Support

**Comment by upieez** [comment]
Hey @jazzgershoam I've successfully set up the request on my machine. I believe you and I share the same problem and I'll document it over here step by step so that in the future if anyone has the same issue, they can refer here as well.

The main issue here is that the folder is tucked away in **User** and not **Macintosh HD**. 

The path from the root of your Mac is `Macintosh HD > Users > YOUR_USERNAME`

The `Library` folder is hidden by default so you need to enable it by following the steps below

### Show Library Folder

This is inside your `YOUR_USERNAME` folder

<img width="582" alt="Screenshot 2021-06-03 at 9 25 59 AM" src="https://user-images.githubusercontent.com/56812343/120571944-b699f100-c44d-11eb-9e3d-f46b9d06144b.png">

<img width="239" alt="Screenshot 2021-06-03 at 9 28 38 AM" src="https://user-images.githubusercontent.com/56812343/120572169-155f6a80-c44e-11eb-8a7a-ee0a9fa6fc87.png">

You can then navigate to `Library > Application Support > Postman > proxy` to find the certificate

### Enabling keychain access

If you're like me and you don't have the Proxy certificate in your `System` portion of keychain, fret not! Mine is in `login` and it will still work fine. When you double click on the Proxy certificate, the `Trust` section will be folded automatically you just need to unfold it 

<img width="513" alt="Screenshot 2021-06-03 at 9 37 40 AM" src="https://user-images.githubusercontent.com/56812343/120572906-57d57700-c44f-11eb-875f-6864a370013f.png">

After which you can follow the instructions from Postman under the section '**Capture HTTPS traffic with Postman's built-in proxy**' [here](https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/)

### Final step

Since this issue is specifically for MacOS, I'll only document the steps for Macbook to enable the capturing of request on Postman.

Firstly, you have to go to System Preference > Network and remember your ip address

![image](https://user-images.githubusercontent.com/56812343/120573549-58224200-c450-11eb-88ec-d9545421a122.png)
_Credit to Postman for the image_

After which you have to click on Advanced (at the bottom right corner) > Proxies and check the Web Proxy (HTTP) and Secure Web Proxy (HTTPS) and key in your ip address along with the port `5555` (assuming you did not change anything in postman)

![image](https://user-images.githubusercontent.com/56812343/120573705-9e77a100-c450-11eb-8774-3f828fa4f521.png)
_Credit to Tae Hoshino from Postman Support for the image_

After you have done all of that, you should be able to see the request coming in to your native Postman app under `History`!

<img width="119" alt="Screenshot 2021-06-03 at 9 49 16 AM" src="https://user-images.githubusercontent.com/56812343/120573954-ff9f7480-c450-11eb-8daf-07e863c436e4.png">

Hope this helps to anyone that is stuck!

**Comment by jazzgershoam** [comment]
@upieez Thanks Bro.. That was awesome.. 👏 

I have my files inside the library folder.. 😃 

I have my proxy configured now..  Thanks a lot.

@postman-support Is it possible to document these steps as well in the postman learning page?. There might be people facing the same issue.

**Comment by upieez** [comment]
No problem @jazzgershoam! However, one caveat that I have experienced is that somehow if you turn off postman, you lose connection to the internet. So you need to disable the proxy inside the network tab and restart your wifi again for you to be connected to the internet

**Comment by postman-staff** [comment]
Hey @upieez

Thank you so much for providing the steps you have followed in a very detailed manner.

@jazzgershoam Glad that you are able to resolve this using the steps given by @upieez 😃​ and I have raised a request internally to add this to the documentation.

Sorry for being just a little help here. Once again thank you so much @upieez, and @jazzgershoam

I am closing this thread here, just for the time being. Feel free to reply if you have any further queries regarding this.

👋​ Stay Safe - Have a great day :)

via @VaishnaviChallaPostman | Postman Support

**Comment by jiangliwei123** [comment]
@upieez thanks a lot !how amazing that you can find this solution!
