### ISSUE TITLE
"Conflict" shows in header even though same API endpoint is not open in any other tab once the system is restarted

### ISSUE THREAD

**Issue by snsnihit** [a85/POSTMan-Chrome-Extension#9993]
Steps to reproduce :
1. Keep any request open
2. Close the application and restart the system
3. Open Postman and observe header of already opened request

Bug : "Conflict" shows in header even though same API endpoint is not open in any other tab

**Comment by mnabe** [comment]
If you use the Desktop application, try to log out of Postman in the browser (so that you are only logged in on the Desktop application). This seemed to solve it for me.
Still inconvenient though.

**Comment by DannyDainton** [comment]
Hey @snsnihit 

Is this still an issue for you in the latest version of the platform? If so, could you expand on the information that you have provided to include screenshots and version details, please?

**Comment by mnabe** [comment]
@DannyDainton I am not the OP, but I experienced the same issue for a long while. I wasn't able to reproduce as of this moment (I am on v9.14.14), but lets await others and see, if the problem still exists. 

Could possibly have been fixed with v9.14.5 and v9.14.7 according to the release notes - they link to issue https://github.com/postmanlabs/postman-app-support/issues/10694. 
Keen to see if others still experience this problem.

**Comment by DannyDainton** [comment]
Thanks for responding and providing those details @mnabe ❤️

**Comment by snsnihit** [comment]
> Hey @snsnihit
> 
> Is this still an issue for you in the latest version of the platform? If so, could you expand on the information that you have provided to include screenshots and version details, please?

Nope this is no longer reproducible on v9.15.2. Seems like it has been fixed.
