### ISSUE TITLE
malformed PHP curl code generated

### ISSUE THREAD

**Issue by DraqueT** [a85/POSTMan-Chrome-Extension#9999]
**Describe the Issue**
When generating PHP curl example code, the code is malformed.

**Steps to Reproduce**
- Create a post request with multiple key/value pairs
- Open Code Snippets
- Select PHP - cURL
- Observe that the value for CURLOPT_POSTFIELDS is malformed: the first key points to an array that contains the first value, then a named value which should be the second key/vaule pair.

Current: CURLOPT_POSTFIELDS => array('key1'=> ['value1', 'key2'=>'value2'])
Corrected: CURLOPT_POSTFIELDS => array('key1'=> 'value1', 'key2'=>'value2')

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/8284425/120567084-bce48a80-c3c5-11eb-8d1d-1fae7c7520d4.png)

**Environment Information**

 - Platform Type: MacBook Pro
 - Postman Version: 8.5.1 (8.5.1)
 - Operating System: Mac OS 11.2.3 (20D91)

**Additional Context**
The only reason I caught this is that it can create a situation where the array depth is too great, and the generated code will result in a "Array to string conversion" exception being thrown. This is how I found it.

**Comment by VShingala** [comment]
@DraqueT Could you confirm if this issue is still present for you with the latest Postman App? I tried this and it's now having the correct value that's the expected behavior mentioned by you.

I'll close this issue, feel free to reopen it if you're still facing the same issue.

![image](https://user-images.githubusercontent.com/16756296/200841542-f33a1c14-5d1b-4907-a4ea-b3324f931001.png)
